### ISSUE TITLE
[Bug Report] Tagger Config Blacklist keywords aren't saved

### ISSUE THREAD

**Issue by plotr** [stashapp/stash#1001]
**Describe the bug**
After adding keywords to the Blacklist in tagger configuration they are not saved after some amount of time.

**Expected behavior**
The added keywords are permanently added to the tagger Blacklist.

**Stash Version: (from Settings -> About):**
v0.4.0

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Safari
 - Version 14.0.2

**Additional context**

**Comment by WithoutPants** [comment]
This is currently implemented as a UI-only session config. It should be persisted in the config.
