### ISSUE TITLE
[Feature] Alert user when closing the browser window of an unsaved (but modified) scene.

### ISSUE THREAD

**Issue by ALonelyJuicebox** [stashapp/stash#1012]
As there's currently no real indication that the edit tab on a scene has been modified but not saved, I propose implementing a JS pop-up stating something along the lines of "You haven't saved your modifications. Are you sure you want to exit?".

This helps to avoid scenarios where you've overlooked that you've added tags, etc and Stash completely fails to let you know what the current status of that edit page is.
Thanks! 🙏

**Comment by jeremymeyers** [comment]
Also an "Apply And Save" feature when committing scrape data. (ideally there would be an autosave of drafts but that is probably for down the line)

**Comment by WithoutPants** [comment]
> Also an "Apply And Save" feature when committing scrape data. (ideally there would be an autosave of drafts but that is probably for down the line)

This should be raised as a separate issue. It should be applied for all scraping dialogs.
