### ISSUE TITLE
[Feature] Replace "Scrape With" with "Identify"

### ISSUE THREAD

**Issue by jeremymeyers** [stashapp/stash#1018]
Movie server back-ends like Kodi, Plex and Emby use 'Identify' to denote the function of searching internet databases and pulling metadata based on information provided.  This, combined with a way to set a default scraper, would make the process more newbie-friendly.

**Comment by SpedNSFW** [comment]
I don't see how renaming the button would help. "Scrape With" is very clear as to what it's doing and "Identify" is vague.

**Comment by secondfolder** [comment]
That makes sense to me. More inline with the convention set by other media managers and to my mind clearer too. "Scrape With" could be interpreted as "Scrape site for other media similar to this one" for example.

**Comment by SabinBC** [comment]
Scraping is the conventional term for what is happening (web scraping). I do not know why you mention that Kodi/Emby use Identify... they do not seem to.

https://kodi.wiki/view/Scraping_Music
https://support.emby.media/support/solutions/articles/44001162214-plugins-overview

It would be a disservice to users to change the name. If they take to the web to find new "identifiers" for their content they'll have a hard time finding what they need - scrapers.

**Comment by WithoutPants** [comment]
Agree with others here. I don't think renaming is the right thing to do given that we mention "scrapers" in the context of metadata scraping in multiple places. Renaming would (imo) cause a great deal of confusion and I can't see any real benefit to renaming to "Identify".
