### ISSUE TITLE
[Bug Report] On Performer screen, saving an image from a scrape does not refresh the image on the page.

### ISSUE THREAD

**Issue by jeremymeyers** [stashapp/stash#1019]
**Describe the bug**
The image on the performer profile page is not refreshed after a scrape save, making it appear as tough the image didn't get applied.

**To Reproduce**
1. Search for a performer,
![Screenshot 2020-12-23 22 35 35](https://user-images.githubusercontent.com/3514095/103058244-b547cc80-456f-11eb-8e78-ace9bae75cc3.png)

2.  Get a result with an image. 
![Screenshot 2020-12-23 22 35 42](https://user-images.githubusercontent.com/3514095/103058277-c09af800-456f-11eb-837b-b32f2fafd986.png)

3.  View and confirm changes to profile and click "Save".
![Screenshot 2020-12-23 22 35 51](https://user-images.githubusercontent.com/3514095/103058324-de685d00-456f-11eb-92e3-45fe3b86d289.png)

**Expected behavior**
1. Performer page is populated with downloaded metadata including image

**Actual behavior**
All data is populated other than image (seems like the block is not refreshed)
![Screenshot 2020-12-23 22 35 55](https://user-images.githubusercontent.com/3514095/103058394-05269380-4570-11eb-8f5f-1f0bb020b01b.png)

Refreshing the page and clicking "Save" again will force a reload of the image (With spinning arrow) .

**Screenshots**
If applicable, add screenshots to help explain your problem please ensure that your screenshots are SFW or at least appropriately censored.

**Stash Version: (from Settings -> About):**

Version: | v0.4.0
-- | --
Build hash: | f0ec37c
Build time: | 2020-11-24 03:43:25

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version 84.0.1

**Comment by SpedNSFW** [comment]
Duplicate of #993 and #869

**Comment by jeremymeyers** [comment]
Sorry, didn't see those after searching. Will close.
