### ISSUE TITLE
[Bug Report] Downloads folder in user home is deleted

### ISSUE THREAD

**Issue by InfiniteTF** [stashapp/stash#1021]
Stash empties its downloads folder when initializing. From what I can tell, if the generated folder isn't set, i.e. on first start, the downloads path is "./downloads", which means stash can wipe the user's downloads folder. This has happened at least twice that I'm aware to new users on mac, and probably more times that we haven't heard of.

In general I don't think we should empty the downloads folder if the generated path is blank. It might also be preferable to use a pattern to only delete files which stash actually creates.

**Comment by bnkai** [comment]
As a quick and dirty fix we could change the default `downloads` folder in the config  ( `const Downloads = "downloads" ` ) to something more unique eg `stash_downloads` just to avoid the initial folder removal.
