### ISSUE TITLE
[Feature] Add file path and other parameters in json sceneByFragment

### ISSUE THREAD

**Issue by Tweeticoats** [stashapp/stash#1027]
**Is your feature request related to a problem? Please describe.**
When using a scraper with sceneByFragment it returns the current data of the scene ie title as well as any current data that has been populated.
For the xbvrdb scraper I am trying to match based on file name to retrieve metadata and am getting this from the title as the initial scan sets the title to the file name.
If we can include the file name, path and other metadata it might give more options when writing scrapers.

**Describe the solution you'd like**
Can we include some more fields included in the json sent to sceneByFragment.
Suggested new fields: name, path, ohash, md5, file size, duration, dimensions, video codec, audio codec.

Suggested json:
{
"title": "filename",
"filename": "filename.mp4",
"path": "/data/filename.mp4",
"ohash":"eda430de0c7ab56b",
"md5":"08960c5898a585a8aea4ffb5c55a6ed5",
"size":"683107833",
"duration":"11:18"
"dimensions":"1920 x 1080",
"video_codec":"h264",
"audio_codec":"aac"
}

**Comment by niemands** [comment]
Some python script scrapers also query the database directly via sqlite3. That works, but is prone to fail and for me it feels like bad practice. Maybe the scraper parameters could get connection information, like plugins do, to request the GraphQL API instead for getting arbitrary scene information. (Although it can be argued, that this would just be another way for starting plugin tasks)
