### ISSUE TITLE
[Feature] Search Filter for Items That Have a Certain Number of Tags

### ISSUE THREAD

**Issue by icedstick** [stashapp/stash#1034]
**Is your feature request related to a problem? Please describe.**
Currently there are 4 tag-related options to filter search results for items (e.g. Scenes/Images/Galleries etc) 

1. Search > Filter > **Is Missing > tags**
2. Search > Filter > **Tags > Includes All**
3. Search > Filter > **Tags > Includes**
4. Search > Filter > **Tags > Excludes**

**Describe the solution you'd like**
I think it would be valuable to include another filter that would be able to specify items with a certain number of tags. Under the additional Tags filter option could be 'Total Number', which offers four filter options (i.e. similar to the current options for Duration)

1. Search > Filter > **Tags > Total Number > Equals**
2. Search > Filter > **Tags > Total Number > Not Equals**
3. Search > Filter > **Tags > Total Number > Greater Than**
4. Search > Filter > **Tags > Total Number > Less Than**

This could help with cataloguing/tagging files that are in the process of being tagged or may have not yet been categorized yet as 'organized' by the clickable icon on each scene/image etc page.

For example, a search for:
- **Tags > Total Number = 0** would find untagged items (would functionally perform the same as the **Is Missing** filter).
- **Tags > Total Number = 1** would find items that only have 1 tag (could be any tag).
- **Tags > Greater Than = 9** would find items that have 5 or more tags, which may be helpful in finding items that are almost complete and ready to be categorized as 'Organized'.

**Comment by WithoutPants** [comment]
Resolved by #1254
