### ISSUE TITLE
[Feature] Would be great to list videos that have zero tags

### ISSUE THREAD

**Issue by ukcuddlyguy** [stashapp/stash#1039]
I just wanted to say, I've wanted something like this for years, have considered writing one but never got round to it - so I was amazed to find your project today. I've just donated ($100, incognito) a minute ago.

**Is your feature request related to a problem? Please describe.**
I always want to have every video tagged in some way (tag, person, rating, etc), so if there are any videos without them it means they are still due processing by me.

**Describe the solution you'd like**
On the scenes, Add Filter modal, I'd like a "Tags" -> "Has none" option

**Describe alternatives you've considered**
I couldn't find any other alternatives that already exist, but I'm happy to be pointed to them!

**Additional context**
This is the modal I'm referring to:

![Screenshot 2021-01-02 at 14 15 04](https://user-images.githubusercontent.com/62703727/103459169-093b7980-4d05-11eb-8832-b9540d63d86d.png)

**Comment by 7dJx1qP** [comment]
I think support for this feature currently exists now. There's `Tags is null`, `Tag Count is 0`, and `Is Missing tags` filters that can be applied, any of which should give you videos with no tags. This can also be combined with `Performer Count is 0`, `Rating is null`, and various other `X is null` filters.

**Comment by bnkai** [comment]
`Tags` -> `Is Null` as mentioned above covers the original request.
These cases imho  are the definition of the `organized` functionality. When editing a scene set it to organized when you think it is `complete` 

Closing this
