### ISSUE TITLE
Scene Filename Parser issue?

### ISSUE THREAD

**Issue by executivoclub** [stashapp/stash#1046]
Guys,

I have a large collection (>220 TB) of a specific niche, and all the files are named as MODEL - TITLE.ext, I'm a new user in Stash, and I'm trying to use Scene Filename Parser, to organize my collection, where I'm setting the filename parser like `{performer}{d}{title}.{ext}`

The problem is that Stash gets the title but not the performer model, so I'm not able to organize my collection.

I'm doing something wrong or this is an issue?

Any help is appreciated!

**Comment by bnkai** [comment]
The filename parser expects the performers to be already in the database, do you have them there? The app manual  `? ->  Scene Filename Parser ` explains how the parser works in detail.

**Comment by WithoutPants** [comment]
Closing as stale. Can reopen if more information is added.
