### ISSUE TITLE
[Feature] [Scene grid mode] add option to move scene description to a button popover icon

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#1055]
**Is your feature request related to a problem? Please describe.**
- Scene card descriptions take up valuable screen real estate when browsing in grid mode.
- Yes this is subjective, but you'll notice many polished porn tube sites (xhamster, xhamsterpremium, pornhub, legalporno. bang, fap18, red tube, xvideos, xnxx, etc.) do not show the scene descriptions in their equivalent grid modes.

**Describe the solution you'd like**
- Add an option in the interface settings to hide scene descriptions from the scene card (because ppl are probably used to its current location)
- If the above option to hide is enabled, create a description button icon in the button popovers sections, `<div role="group" class="card-popovers btn-group"`, where the user can still access it.

**Comment by jeremymeyers** [comment]
Would generally like the ability to customize what information gets shown per scene. For example when browsing it would be helpful for me to have the studio, the performers and maybe the first few tags listed in the card? I'm not going to be able to choose what to watch based on thumbnail and the arbitrary scene title and am not necessarily gonna mouseover everything.

Is the "this tag is associated with # of scenes" data programmatically usable?
