### ISSUE TITLE
[Feature] add option for favorite studios

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#1060]
**Is your feature request related to a problem? Please describe.**
Large libraries accumulate hundreds of studios.  There's no way to filter for favorite studios.

**Describe the solution you'd like**
Add the option to favorite studios ala performer favorites

**Comment by jeremymeyers** [comment]
I would assume this could be addressed by #997

**Comment by DogmaDragon** [comment]
Studios now can have ratings and be filtered by them which is a more flexible favorite system.

**Comment by feederbox826** [comment]
can this be closed?
