### ISSUE TITLE
[Bug Report] Performer's Twitter and Instagram fields should assume a single word is a username and create url accordingly

### ISSUE THREAD

**Issue by jeremymeyers** [stashapp/stash#1062]
**Describe the bug**
If a performer's twitter or instagram fields only contain their username rather than the full https://www.twitter.com/[username], the link function doesn't recognize. There is no UI indication as to whether a full url needs to be pasted, and at least a few of the larger scrapers (freeones, etc) only deliver a username.

**To Reproduce**
Enter a username only in the instagram or twitter fields of a performer page

**Expected behavior**
link icon shows, allowing user to click to their profile

**Comment by bnkai** [comment]
I dont know which version you use but in dev and probably latest stable (0.4.0) this works fine (if i understood what you meant)
full url
![image0](https://user-images.githubusercontent.com/48220860/104773409-b12d5a00-577d-11eb-95e4-7024e88dd323.png)
usename only
![image1](https://user-images.githubusercontent.com/48220860/104773442-be4a4900-577d-11eb-96d4-0f42f2760d69.png)
and in both cases
![image2](https://user-images.githubusercontent.com/48220860/104773465-c86c4780-577d-11eb-9ad2-f80fb1fb75bb.png)
snapchat and twitter icon work fine

**Comment by jeremymeyers** [comment]
I see. I misinterpreted the UI. I expected an icon to appear in the edit section next to the form field like when URL is entered.

**Comment by WithoutPants** [comment]
This appears to be addressed, so closing.
