### ISSUE TITLE
[Bug Report] Character Encoding '

### ISSUE THREAD

**Issue by Belleyy** [stashapp/stash#1068]
**Describe the bug**
The character `'` can be replaced by `â€™` in title/details.

**To Reproduce**
Didn't manage to reproduce it atm but probably happened because i use Export/Import:
1. Full Export JSON
2. Wait till done
3. Full Import JSON
4. Check if there is `â€™` that appear

**Expected behavior**
Keeping the `'`

**Screenshots**
![Image](https://cdn.discordapp.com/attachments/559159910550732809/801071341159317524/unknown.png)

**Stash Version: (from Settings -> About):**

Version: | v0.4.0-43-g1e04deb
-- | --
Build hash: | 1e04deb
Build time: | 2021-01-18 01:26:46

But this problem was present before this version.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 84.0

**Additional context:**
Scene was scraped using URL.

I probably used python script (Python3) to edit the JSON:
- https://github.com/Belleyy/Public/blob/main/1.JsonToImage.py
- https://github.com/Belleyy/Public/blob/main/2.ImageToJson.py

Get small image (1), upscaling the image, change in JSON (2). 
Could be a mistake that a made during the process to create these script, since i am beginner with python 😅

**Comment by bnkai** [comment]
Tried to reproduce by doing a scrape export/import but couldn't
The most relevant issue i found <https://stackoverflow.com/questions/2477452/%C3%A2%E2%82%AC-showing-on-page-instead-of>  that points to something going wrong with the script/json conversion 
Feel free to update if a way to reproduce is found
