### ISSUE TITLE
[Bug Report] Problems playing scenes.

### ISSUE THREAD

**Issue by hassaffe** [stashapp/stash#1070]
The problem occurs in Firefox, Chrome, Brave and Safari(ios). The video stick constantly and the player has to reload. But when I call the stream directly via the link "File info" -> "Stream" the videos run without problems. I checked the files with ffmpeg and it found no errors.

File Size 774.82MB
Duration 15:54
Dimensions 1920 x 1080
Frame Rate 23.98 frames per second
Bit Rate 6.81 megabits per second
Video Codec h264
Audio Codec ac3

**Comment by bnkai** [comment]
Can you try to force stash to transcode the video? From the player select Webm HD or Webm Standard for example.
(I am guessing there is an issue when trying to copy the stream and only transcode the audio)

**Comment by hassaffe** [comment]
Even if the player transcodes the video, playback stutters regardless of which setting I select. The container of the video file is an mp4

**Comment by bnkai** [comment]
Can you provide some logs? or a sample clip from the file ?
`ffmpeg  -i file.mp4  -t 60 -c:a copy -c:v copy sample.mp4 `
Make sure to scan and try the sample again to see it has the same problem.

**Comment by bnkai** [comment]
The log seems normal. Unless you have a low power cpu where you are running stash ( 1080p vp9 needs a bit of cpu power ) you shouldnt have an issue. Have you tried forcing lower resolutions eg 480p? or using the mp4 profiles ?

**Comment by hassaffe** [comment]
CPU(s) 4 x Intel(R) Core(TM) i5 CPU 760 @ 2.80GHz

The same problem occurs with the Sample.mp4. But why does it run without a problem when I call up the stream via the link under "File info" -> "Stream"?

**Comment by bnkai** [comment]
The `Stream` only serves the file it doesnt process it.

**Comment by hassaffe** [comment]
It works very well with the new audio codec. I thank you.

**Comment by InfiniteTF** [comment]
We should probably do a better job of remuxing and optionally reencoding audio when the video is h264. I've got a bunch of flv files that are h264/aac for instance, which get fully transcoded.

**Comment by bnkai** [comment]
Yeah i tried something a lot of iterations of the transcoding process ago, the only thing left from then is that if the original contaier was an mkv and the video  codec is supported stash will try to only transocde the audio part in a new mkv container. The main issue was that at that time i couldnt remux the video to another container except mkv  and keep the file streamable ( i think i had some issues with the movflags when trying to copy the  stream). Seeing that the movflags work now it might be worth it to revisit the issue. Flvs should be doable if movflags work with the copy only,  ts files tend to have issues though
