### ISSUE TITLE
[Feature] Multiple Versions of the same Scene

### ISSUE THREAD

**Issue by SpedNSFW** [stashapp/stash#1072]
When multiple scenes have either the same data and/or the same Stash ID, it would be nice if they were merged together and then you had the option to play a specific version.

## Why?

There are many reasons to have multiple versions of the same scene. Maybe the studio released a remastered version. Maybe you have multiple resolutions or they're encoded differently. Perhaps it's a scene from a movie and one version contains all the added acting.

## What it could look like
![Example](https://user-images.githubusercontent.com/68614336/105467021-33230300-5ce9-11eb-86c4-f48b913acceb.png)

**Comment by kermieisinthehouse** [comment]
You can now find versions of scenes by going to a scene, hitting File Info, then clicking the phash. As long as it's the same scene, even at different resolutions, they will all appear.
