### ISSUE TITLE
[Feature] [Search] add 'Scene Count' filter option to performers and studios

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#1084]
**Is your feature request related to a problem? Please describe.**
There's no method to filter performers or studios by `scene count`

**Describe the solution you'd like**
Add a `scene count` filter to performers and studios

**Additional context**
since performers can be tagged to images, add an `image count` filter to performers as well

**Comment by julien0221** [comment]
has been added on #1307

**Comment by peolic** [comment]
> has been added on #1307

(for studios)
and the performer ones were added on #1254.

**Comment by WithoutPants** [comment]
Resolved by #1307 and #1254
