### ISSUE TITLE
[Feature] Improved Duplicate Handling

### ISSUE THREAD

**Issue by plotr** [stashapp/stash#1088]
**Is your feature request related to a problem? Please describe.**
I am currently replacing a lot of content with higher resolution version encoded in h265. I'm using the Duplicate Finder plugin to identify duplicates but the process is quite painful. None of the current views will show me the resolution, encoding, organized/scrape/match status, or let me easily delete the unwanted scene and remove the duplicate tag from the scene I want to keep.

**Describe the solution you'd like**

- Ideally there would be a way to group multiple files tagged to a single scene similar to Plex.
- The grid view could be improved to include more information about a scene but especially the encoding ('1080p HEVC' or '1080p H264' for example).
- Sometimes the file I want to delete is already scraped. It would be great to be able to copy the metadata to the scene I want to keep.

**Describe alternatives you've considered**
None at this time

**Additional context**
NA

**Comment by bnkai** [comment]
Files can now be merged from the duplicate finder and all requested info is displayed as well
Closing as completed
