### ISSUE TITLE
[Bug Report] Keyboard commands stop working after using player controls

### ISSUE THREAD

**Issue by Challion84** [stashapp/stash#1094]
Whenever i click on any player control other than play/pause with my mouse, all the keyboard commands stop working after a few seconds. I can press the right or left key a few times to seek forward or backwards, but after a few seconds all keyboard commands stop working. I have to click twice in the player to pause and start it again. Then everything works fine as long as i didn't click on any controls again.

It seems it only happens in Chrome (even in Inkognito mode). The problem doesn't exist in Firefox.

1. Start a video in Stash with Chrome
2. Click anywhere on the seek bar
3. Press the right arrow key a few times to seek forward.
4. After a few seconds it should stop working.

Stash Version: v0.4.0-52-g23d2668

**Comment by IAmKontrast** [comment]
Got the same experience. Looks like Chrome lose its focus and therefore the arrow keys won't work until a click in the video screen.

**Comment by WithoutPants** [comment]
Looks resolved with the videojs changes.

**Comment by DocFreeman** [comment]
I'd like to reopen this, I run into the same issue after rating a video.

**Comment by DogmaDragon** [comment]
> I'd like to reopen this, I run into the same issue after rating a video.

Open a new issue.
