### ISSUE TITLE
[Bug Report] Stash folders should be excluded from scan

### ISSUE THREAD

**Issue by mrbrdo** [stashapp/stash#1102]
**Describe the bug**
Stash data folders like generated and cache are included in the scan if the parent folder is a content folder, causing recursive behavior.

**Expected behavior**
When scanning, folders that include the path of any of stash data folders should be skipped. Should be an easy fix.

PS: haven't checked in code that this is the case, but I'm assuming this is what's happening for me.

**Comment by bnkai** [comment]
While i havent checked the code i think it could happen to certain extent.
I would like to  point out that it is not optimal/recommeded to use a media folder that includes stash folders.
While you could use the exclude patterns to work around that it would still add overhead to the scan process.
Instead of skipping stash folders i think that refusing to add media paths that include those is probably better.

**Comment by mrbrdo** [comment]
I think the overhead should be minimal if doing simple string comparisons, compared to IO operations it should be negligible. So no symlink resolving or something like this, which I think would be overkill.

The advantage of solving it by excluding the paths would be in a case like mine, where I have the root media folder as a network share, and I want to store the db on there too, so I can access it from multiple computers in my LAN. If I want to keep it outside of the media folder then I need to add a new network share, but then I have to always make sure that both the media network share and the config network share are both mounted, which is a little less convenient. As noted, the performance impact of a few string comparisons is nothing compared to even a single IO operation, so I think this solution would be superior.

**Comment by bnkai** [comment]
Yeah what i meant is with the current  code folders are expanded anyway. The exclude patterns are matched for all the contents of the folder. So if  a folder has 1k files all filenames from those folder will be retrieved and then discarded. That means we have to change that part too. Maybe discarding stash `system` paths from there (check if dir is in the fixed stash paths) would be easier and maybe adding an extra exclude folder/subfolder pattern where you select the media directories could be useful.

**Comment by mrbrdo** [comment]
Sounds good. There may be some optimized ways of string comparison to multiple strings - I'm not sure if this would be more efficient, but possibly a pre-compiled regexp with a pipe between all options - not sure how regexp would handle this and if it would be more efficient than n string comparisons. Namely if multiple paths have the same starting part, an efficient engine could discard all of them at once, and also only iterate through the tested path string once, instead of for each individual comparison.
