### ISSUE TITLE
[Bug Report] Setting Organised State Reverts Data to Last Saved State

### ISSUE THREAD

**Issue by SpedNSFW** [stashapp/stash#1110]
**Describe the bug**
Clicking on the organised button for a scene will revert the scene data back to the state it was at its last save.

**To Reproduce**
1. Go to a scene and scrape (or just enter some data)
2. Click on the organised button
3. All scraped/entered data will be gone.

**Expected behavior**
Any data entered should not be affected by the change of Organised state.

**Comment by nocrad349** [comment]
Clicking the o-counter button has the same problem.

**Comment by SpedNSFW** [comment]
> Clicking the o-counter button has the same problem.

Yes, InfiniteTF has already made a PR for this and is aware of that fact.
