### ISSUE TITLE
[RFC] Help with scrapers.

### ISSUE THREAD

**Issue by JaseNZC** [stashapp/stash#1113]
I have a question re the scrapers for scenes.
Copying over the required scraper and reloading the scrapers it shows up under scene fine.
When trying to select scrape within the scene it does not show up.
only scrapers that show as Scene Metadata, Url seem to be the ones that show up.
Any scrapers that are just listed as url will not show up.
Example porn hub shows up in the list to be able to scrape with but the other one wont.
Am I using this completely wrong ?? Any help would be most appreciated.

<img width="418" alt="Screen Shot 2021-02-09 at 12 42 09 AM" src="https://user-images.githubusercontent.com/64925341/107215132-c8572300-6a6f-11eb-9dc9-4db211741f78.png">

**Comment by InfiniteTF** [comment]
Hi, please join the discord to get help with the scrapers.
