### ISSUE TITLE
Include Aliases in Performer Search

### ISSUE THREAD

**Issue by velzy00** [stashapp/stash#1114]
**Is your feature request related to a problem? Please describe.**
At present, the performer Aliases field is not included in search results, so you can't search for a performer by any alias contained in that field.

**Describe the solution you'd like**
Please include aliases in search results when searching by performer name. It may also be necessary to develop some standard delimiters for that field. I see "," and "/" most often when scraping performers.

**Describe alternatives you've considered**
This seems pretty straightforward.

**Additional context**
This is particularly useful when a performer changes names (ie. Bunny Colby) or is commonly called different things on different sites.

**Comment by HereIam80** [comment]
I agree that it could be useful but this has to be optional in my opinion. I have >5200 performers in my DB and many of them have multiple aliases, that I wouldn't want to show up every time I do a search. Maybe there should be a checkbox if they get to be included or not.

**Comment by Stephan972** [comment]
> I agree that it could be useful but this has to be optional in my opinion. 
It may be also a global option. Users who like the current stash behavior would stay happy.
Users who want performer alias search feature would activate it.

**Comment by kermieisinthehouse** [comment]
This is already the behavior in the performer search field. Note that if your search has spaces, they should be replaced with underscores, e.g. Firstname_Lastname
