### ISSUE TITLE
[Feature] Add Remux to stream quality select

### ISSUE THREAD

**Issue by praul** [stashapp/stash#1116]
**Is your feature request related to a problem? Please describe.**
I have a lot of videos that are h264 but in containers, where stash assumes, my browser does not support direct play (for example .flv). These videos get needlessly reencoded

**Describe the solution you'd like**
An option in the videoplayer for remux without transcoding. This would leave compatibility issues untouched. Users can try if remuxing works and they can still choose to transcode if it doesn't.
It would be a simple ffmpeg command: ffmpeg -i input.flv -c copy -copyts output.mp4                                                                           

**Describe alternatives you've considered**
An automatic detection of supported codecs and automatic remuxing. But I guess, this would be more complicated.

**Additional context**
This is where I would like the remux option
![image](https://user-images.githubusercontent.com/38807639/107358639-eb1b2300-6ad3-11eb-8a9a-cf342f76ed04.png)

Thank you so much for stash. I really love it!

**Comment by bnkai** [comment]
The remux is already done for mkv files (eg h264 mkv with ac3 sound )
For `ts` it was skipped since most of the times a copy remux isnt enough (file not seekable)
For `flv`most samples available at the time where non h264 ( so that was skipped also) . That could be added i guess.

**Comment by praul** [comment]
Oh, nice. I would like this feature for flv very much.
I could remux all the files myself, but often they belong to a torrent I'm seeding - and I have to keep the originals therefore.
Thank you
