### ISSUE TITLE
[Bug Report] "Height: Not Null" Parameter Filters Nothing

### ISSUE THREAD

**Issue by theamazingjuju** [stashapp/stash#1136]
Basically the title.
I was trying to sort performers by height and exclude those that didn't have any data. I was pleasantly surprised to see that this was a feature, but quickly disappointed that it didn't work LOL. Interestingly, the "Height: Is Null" parameter works just fine.

**To Reproduce**
1. Go to 'Performers'
2. Add the "Height: Not Null" filter
3. Set sorting order to "Height, Ascending"
4. The first performers displayed are ones with no height data

**Screenshots**
[Pic of the the search](https://imgur.com/a/6MSCBtQ)
[Pic showing the lack of height data](https://imgur.com/a/ygvIhrG)

**Stash Version:**
v0.4.0-71-gdeebeab9

**Desktop Stuff:**
 - OS: Windows 10 Home v. 10.0.19041
 - Browser: Chrome v. 88.0.4324.150

**Additional context**
This is the best porn organizer out there, keep up the great work!

**Comment by theamazingjuju** [comment]
Actually, It seems like a height data-less few performers ARE filtered out. Not all of them though. Very strange.

**Comment by InfiniteTF** [comment]
It's a somewhat subtle bug. It correctly filters out NULL values, but if you erase a value the value is set to a blank string which is not filtered out.
