### ISSUE TITLE
Selection fields shouldn't lose focus or close after selecting something.

### ISSUE THREAD

**Issue by Challion84** [stashapp/stash#1140]
**Is your feature request related to a problem? Please describe.**
If you want to add a bunch of tags or performers to a scene, you can't just type them straight away. Every time after you're pressing enter, you have to grab your mouse to open the list again.

**Describe the solution you'd like**
The options list shouldn't close after each selection. It should stay open, until you click anywhere else or pressing escape. I believe in most cases you want to select more than one option, so it should be the default mode, so one can type and select multiple 15 tags in a row for example, without the extra clicks in between.

**Comment by 7dJx1qP** [comment]
Is this still an issue? I looked at adding performers and tags to a scene and they both allow you to just keep typing to add multiple in a row. The input does not lose focus and you don't have to click again. I tried both Chrome and Firefox.

**Comment by fun-git-user** [comment]
As @Challion84 mentioned it working as he requested, Should it be closed now? Who can close issue @WithoutPants ?
