### ISSUE TITLE
[Feature] Add "Title Text" to scene filter options

### ISSUE THREAD

**Issue by jeremymeyers** [stashapp/stash#1153]
I was trying to look for scene titles containing 'mp4' in them (indicating a mislabel) but putting 'mp4' in the search field shows both that and every mp4 file in the database.  Having a separate 'title' with 'includes/is/excludes' seems like useful functionality.

**Comment by SpedNSFW** [comment]
Duplicate of #1092

**Comment by jeremymeyers** [comment]
sorry i didn't find it in a search
