### ISSUE TITLE
[Bug] Max transcode settings are not applied. Plus: ability to choose default transcode format

### ISSUE THREAD

**Issue by praul** [stashapp/stash#1160]
Hi there, the settings at
![image](https://user-images.githubusercontent.com/38807639/109467408-6afd3300-7a6b-11eb-8c6a-e7ed45589908.png)
seem to have no effect on the player.

When transcoding it always defaults to 1080p webm (on 1080p source).
Since 1080p webm always is laggy for me, I would really like the option to set 720p mp4 as default.

Thanks for looking into it, I really enjoy the app.

I'm on latest dev docker image btw.

**Comment by praul** [comment]
Any news on this topic? I would be really happy about a fix. Thank you

**Comment by WithoutPants** [comment]
Thanks for the report. I've made a PR to fix this.

**Comment by praul** [comment]
Thanks a lot. Much appreciated :)
