### ISSUE TITLE
Help needed: How to handle authentification with stream link

### ISSUE THREAD

**Issue by praul** [stashapp/stash#1164]
Hi there, since https://github.com/stashapp/stash/issues/52 introduced a link for streaming to external players, I'm struggling to use this feature.

If I click the link in Chrome, it simply downloads the stream.

I can not open the URL in VLC directly due to missing cookies/authentification.

Would it be possible to add username/password parameters to the streaming url?

How can I use the generated link in VLC? Is there a possibility to auth and set cookie in VLC?

Answers would be much appreciated. Thank you :)

**Comment by InfiniteTF** [comment]
VLC can't open stream links when you use authentication, you have to disable it.

**Comment by praul** [comment]
Allright, I handled it with reverse proxy + http basic auth. VLC does support that.

**Comment by milindpatel63** [comment]
Can you provide a bit of details on how you achieved this.... I am having similar issue.

**Comment by kyuu840** [comment]
For future reference: after setting a username and password, click the _Generate API key_ button (in the Security page, same as where you set the credentials). After that, the external player links in the Scene pages will include the `apiKey=...` parameter, and VLC and MX Player should work. Don't forget to refresh the Scene page.
