### ISSUE TITLE
[RFC] Can't open on mac

### ISSUE THREAD

**Issue by puddingsoda** [stashapp/stash#1174]
I'm not able to open this on mac. I downloaded the osx release, `cd`'d to its folder, and tried running `./stash-osx`. It says `zsh: permission denied: ./stash-osx`. So I tried using sudo, so `sudo ./stash-osx`. I got the error `sudo: ./stash-osx: command not found`. What should I do now?

**Comment by bnkai** [comment]
Does it have exec permissions? 
`chmod +x stash-osx` should do it, if thats the case.

**Comment by puddingsoda** [comment]
Thank you, my bad, that was the issue.
