### ISSUE TITLE
[Feature] Add a "Has" filter - opposite of "Is Missing"

### ISSUE THREAD

**Issue by andbigdata** [stashapp/stash#1175]
I would like to see a filter that is the opposite of the "Is Missing" filter. It can be named "Has" or whatever makes sense from a usability standpoint. 

My specific problem is searching for videos that have URLs that I forgot to add custom tags to. With a Has:URL filter I'll be able to search through my collection much easier / quicker.

**Comment by WithoutPants** [comment]
I think it's better to use individual field criteria than a "has" filter. In this particular case, we should add a "URL" criterion, which would include `is null`/`not null` modifiers as per other criteria. This would solve both the has and has not requirements.

The Is Missing criteria should be deprecated in favour of individual and `_count` criteria, imo. Additionally, we should endeavour to ensure that all fields can be filtered on.

**Comment by julien0221** [comment]
You are right, and I already added URL on Filters for Scenes (it should be on dev branch), so now it is possible to choose URL is not null, to retrieve all scenes with URL or URL is null to retrieve all scenes without URL (so Is missing url does the same job)
I will check which field is not on filters and will add it. :)

**Comment by WithoutPants** [comment]
Closing as the original problem is largely resolved, and as mentioned prefer to have is null/not null individual field criteria.
