### ISSUE TITLE
[Bug Report] Performer "Scrape With"

### ISSUE THREAD

**Issue by cv702** [stashapp/stash#1181]
**Describe the bug**
When adding a performer, can clicking on "Scrape With", the menu that opens is unclickable (behinf fields on page)

**To Reproduce**
1. Go to Performers
2. Click on Click on New
3. Click "Scrape With"
4. Unable to click any scraper

**Expected behavior**
Able to click on scraper

**Screenshots**
![Screenshot 2021-03-07 091443](https://user-images.githubusercontent.com/80215297/110248382-9bd6df80-7f25-11eb-80a1-fb17d12bb72d.png)

**Stash Version: (from Settings -> About):**
v0.5.0-23-g9d1b716f

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 89.0.4389.82

**Comment by InfiniteTF** [comment]
Your theme is outdated, check the wiki for an updated version.
