### ISSUE TITLE
[Feature] Stream links should have an extension to allow launcing external applications

### ISSUE THREAD

**Issue by Tweeticoats** [stashapp/stash#1186]
**Is your feature request related to a problem? Please describe.**
For android devices if the url contains an extension ie /stream.mp4 it will offer the ability to play in a supported video player eg vlc.
Can we change the stream link on scenes page to include the file extension.

**Describe the solution you'd like**
Can we change the stream link on scenes page to include the file extension.
From what I can see the file extension urls ie /stream.mp4 will use ffmpeg to convert the file to mp4 even if it was a mp4 already.
Can we check if it needs to convert the file and stream directly instead of convert and stream as it currently will.
Can we then update the stream link on the scenes page to include the file name.

**Comment by kermieisinthehouse** [comment]
Resolved in Android - the "pop-out" button under a scene on mobile will launch an external player

See #679
