### ISSUE TITLE
Add "Issue Templates" to GH Repo for better visualization of bugs/feature requests/etc

### ISSUE THREAD

**Issue by jeremymeyers** [stashapp/stash#1189]
https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository so people can click on whether an issue is a bug or a feature request or whatever.

https://github.com/stevemao/github-issue-templates has a bunch of pre-made ones.

**Comment by WithoutPants** [comment]
We already do? 

![image](https://user-images.githubusercontent.com/53250216/110537831-53aefb80-8177-11eb-8cbe-8c1a944618e5.png)

https://github.com/stashapp/stash/tree/develop/.github/ISSUE_TEMPLATE

**Comment by jeremymeyers** [comment]
ugh weird wasn't working on my machine but now is. sorry.
