### ISSUE TITLE
Performer tags

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#120]
### Performer tags
In a nutshell, it would let the user add tags to performers. 
- Performer tags could act as a filter (as demonstrated in the attached concept image below)
- Performer tags would be another way of implementing "performer details" per #53 

(IIRC this might be another feature request that wasn't ported from the Ruby version, or I'm confusing it with Pornganizer functionality, or both.)

![performer tags](https://user-images.githubusercontent.com/37937507/64309856-f4fa3780-cf6b-11e9-84ab-2f28f853ed52.png)
(the tags in the image are repeating because I'm lazy af)

#### Concept image
The above front end ui #108  concept shows how performer tags might be implemented in a container on every url containing `/performers*`.
- Clicking a performer tag would have the equivalent functionality of filtering the performer list
- I would suggest display the performer tag container on the mobile version of Stash too. xHamster has something similar, and it lets you swipe through the tag container left or right to scroll through the list of tags.

#### Auto populate scene tags with performer tags
- Performer tags would automatically populate the scene tags of any scene the performer is added to. This might be an efficient way to add a mass of tags to any given scene.
- Some users might just want to use performer tags as a way to filter their performer list. Therefore, add the option to enable/disable auto tag population in `/settings?tab=tags` > `Performer tags` > `Populate scene with performer tags: Enable/disable`.
- Let the user specify tag exceptions that do not get auto populated in scenes. There would be some tags, like a performers country, that would probably be irrelevant to the scene. In `/settings?tab=tags` > `Performer tags` > `Exceptions (add any performer tags that you do not want to auto populate scenes): {input tag here}`.

![performer tags settings](https://user-images.githubusercontent.com/37937507/64309866-f9beeb80-cf6b-11e9-8ac4-200609d093e6.png)

#### Usage
Performer tags should probably be innate descriptions of the performer, as in qualities about them that don't vary from scene to scene in your Stash library.

For example, if you have scenes of a blonde performer that never (or only rarely) changes their hair colour, then _blonde_ would be a good performer tag if that's something you care about. However, if they do change their hair color often, a performer tag based on the colour of their hair would be an inaccurate performer tag. But this is just a guideline of how you could use performer tags, obviously the use-case could vary.

Real performer tag examples would be things like: _amateur_; _bbw_; _pawg_; _mature_; _Germany_; _Czech_; _hispanic_; _black_; _freckles_; _bdsm_ (if the performer is exclusive to that genre); _large breasts_; _ginger_

#### Relationship with scraping 
Would it be a good idea to automatically generate performer tags based on scraped data?
- Specifically I'm thinking of things like _ethnicity_ and _country_.
- _Fake tits_ is an iffy performer tag as it's a quality that isn't necessarily a permanent quality in the performers create, and could create inaccurate information.
- Of course, there could be a bunch of tick boxes in a `/settings?tab=tags` page that lets the user select which scrapped data to add as a performer tag, but it's more complexity for the devs.
- Some scraped tags would be so redundant I wouldn't even want to see them, eg. If _performer country = United States_ or if _ethnicity = white_. Most performers for many of us would be from white Americans, so we wouldn't ever care about filtering or seeing that.
- I'm proposing an exceptions option in `/settings?tab=interface` to hide a user provided list of performer tags. This could function exactly like adding or removing scene tags to an input box from the scene edit panel

**Comment by GernBlanston12** [comment]
Basically same issue as "Inherited Tags" (88) and has some elements of "tag aliases": Everyone's asking for there to be a way to automate the application of tags to a video, to go with the Other Tags, Performer Tags, and Studio tags they might describe.  If I tag Performer Jessa Rhodes with "blonde", then any video tagged "Jessa Rhodes" should also get the "blonde" tag. If I tag studio Cucked.xxx with "cuckolding", then any video with that studio tag should get the cuckolding tag. Same issue, each time.

**Comment by clemondo** [comment]
This would be a great feature. I can't seem to find the performer tags listed by echo6ix. Does this have to be enabled somewhere?

**Comment by nextbear** [comment]
Great feature ideal. Would be really useful.
I think the tag should remained linked to the performer only....
Tagging Jenna Jameson with 'blonde' doesn't need to update scene tags; however search function would ideally cover both.
For Example: scene:'cuckolding', performer where tag = 'pawg', etc.
