### ISSUE TITLE
[Bug Report] Performer Career Length Regex Filter

### ISSUE THREAD

**Issue by SpedNSFW** [stashapp/stash#1202]
**Describe the bug**
The Regex filter option for a performer's career length is currently broken. It will throw a long error.

```
Error executing count query with SQL: SELECT COUNT(*) as count FROM (SELECT DISTINCT performers.id FROM performers left join performers_scenes as scenes_join on scenes_join.performer_id = performers.id left join scenes on scenes_join.scene_id = scenes.id left join performer_stash_ids on performer_stash_ids.performer_id = performers.id WHERE performers.career_length regexp ? GROUP BY performers.id ) as temp, args: [-\s*.+$], error: argument must be BLOB or TEXT
```

The likely issue is that Career Length is nullable. Instead, if a career length is not set, it should default to an empty string. As you can't alter SQLite table columns, this would be the solution I'd go for:

1. Create a new column `career_length VARCHAR NOT NULL DEFAULT ""`
2. Insert data into the column based on the existing values.
3. Drop old column

**To Reproduce**
1. Go to the performer page
2. Apply a Career Length Regex Matches filter using (the pattern doesn't matter)
3. See the error

**Expected behavior**
The filter should work without throwing an error.

**Comment by bnkai** [comment]
Same goes for tattoos,piercings,ethnicity,country.... Idk if its easier to somehow change the rergex filter than making a migration for all the nullable text fields
