### ISSUE TITLE
[Bug Report] Gallery Tag selection leading to Scene

### ISSUE THREAD

**Issue by yoshnopa** [stashapp/stash#1216]
**Describe the bug**
When tagging a gallery, one can see the tags in the gallery view. On Click, those tags should filter by this tag, which they do, however they lead to a filter on the scenes page. This does not seem like it is intended and is rather annoying.

**To Reproduce**
1. Go to Galleries
2. Tag a Gallery
3. Hover over the Tag icon in Galleries, click the tag
4. You get the filtered page in Scenes

**Expected behavior**
You should get the selected Tag filter in Galleries. For now I didn't try it with images, but it should be a general rule that a Filter should be applied to the type of items the tag was associated with.

**Stash Version: (from Settings -> About):**
v0.5.0-32-g53cb9a1b

**Desktop:**
 - OS: Linux
 - Browser: Chromium
 - Version: 87.0.4280.141

**Comment by WithoutPants** [comment]
Same issue exists in the Images page.
