### ISSUE TITLE
[Feature] Javascript injection

### ISSUE THREAD

**Issue by yoshnopa** [stashapp/stash#1217]
**Is your feature request related to a problem? Please describe.**
I mentioned this already in #15, but as this is already closed I am opening this issue just in case. If this was already recognized there, feel free to close this issue.
It is possible to inject custom CSS to personalize Stash in an enriching way. However, even more customization would be possible by injecting custom javascript. This should probably be issued with a warning, but the possibilities would be limitless.

**Describe the solution you'd like**
I am talking about a solution that works pretty much the same as the css insert, a file thats always injected and that gets filled with the content one can enter in the settings page. Basically, it would be a server side Tampermonkey. 

**Additional context**
I Personally have adjusted the galleries Page using tampermonkey in a very specific way, but would like to set it in stone for the instane as a whole. Maybe other people have similar ideas for customizations on different pages, with javascript literally any change to the webpage is possible.

**Comment by echo6ix** [comment]
I've brought up JavaScript injection before on Discord. This was the reply from a contributor.

> Infinite — 12/02/2020
> Modifying the dom of a react page can quickly break things. Chances are it won't even work right.

**Comment by yoshnopa** [comment]
I was able to modify the code to my liking by adding eventlisteners. It may be more difficult depending on what you want to do, but there are certainly possibilities for customizations and not all of them are instable in nature.

**Comment by yoshnopa** [comment]
Just an update for those wanting something similar, I worked around the problem with the webserver in front injecting the javascript dependency. 

In nginx this can be done with the likes of
```
sub_filter_once off;
sub_filter "<head>" '<head><script type="text/javascript" src="/inject.js"></script>';
```

in apache with
```
AddOutputFilterByType SUBSTITUTE text/html
    Substitute "s|<head>|<head><script type='text/javascript' src='/inject.js'></script>|i"
```

Not really good enough to solve the issue in my opinion, but one can at least achieve the same result.
