### ISSUE TITLE
[Feature] URLs for Images

### ISSUE THREAD

**Issue by yoshnopa** [stashapp/stash#1218]
**Is your feature request related to a problem? Please describe.**
An Image right now is the most restricted item in the collection in terms of Metadata, which is understandable. However, many according image managers have a field for a source, for example any booru board, rule34 etc. Because of that, a field for a URL would be good to keep this standard.

**Describe the solution you'd like**
The same URL field as for other items/performers for images.

**Describe alternatives you've considered**
A custom description field could fill this purpose as well (if one is added, consider this request closed from my point).
See #1443

**Comment by WithoutPants** [comment]
Resolved via #3015
