### ISSUE TITLE
[Feature] Scene Filename Parser should skip scenes with `organized: true`

### ISSUE THREAD

**Issue by chirin1234** [stashapp/stash#1219]
**Is your feature request related to a problem? Please describe.**

It's frustrating when I'm running the scene filename parser against a pattern and scenes that already have their correct titles (which may or may not match the scene info) match and I have to scroll through the list and manually unselect those rows.

**Describe the solution you'd like**

Similar to how the auto tagger ignores organized scenes, the filename parser should skip organized scenes, or at least expose doing so as an option.

**Describe alternatives you've considered**

I've considered writing a plug-in that mimics the functionality, but I'm not sure there's a way to get the manual oversight ability the scraper has.

I've also thought about writing external scripts that interact with stash via curl/graphql and modify the db directly but that seems kind of fragile.

**Comment by kenetik** [comment]
+1 upvote for this.
