### ISSUE TITLE
[Bug?] Changing filter on performers page doesn't reset page parameter

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#122]
Suppose you're browsing the list of performers, and you're on the 3rd page, `p=3`, using the filter `scenes_count`: http://localhost:9999/performers?disp=0&p=3&q=&sortby=scenes_count&sortdir=asc

Now suppose you change the filter to `updated_at`, http://localhost:9999/performers?disp=0&p=3&q=&sortby=updated_at&sortdir=asc

The page parameter, `p`, doesn't reset to `1`, it remains `3`. I'm not sure if this is intended behavior but it's confusing.

I had always assumed changing the filter was akin to starting a new query and only noticed it when I changed the filter to scene_count and saw the list wasn't starting with performers who had 0 scenes.

**Comment by WithoutPants** [comment]
This can now be closed.
