### ISSUE TITLE
[Bug Report] Search results include entries with matching hash, giving unexpected results

### ISSUE THREAD

**Issue by hyde231** [stashapp/stash#1223]
**Describe the bug**
When searching for substrings that contain only the characters from a-f, the search results not only include performers with that search string in their name or alias, but also performers with a hash that contains this sequence. This is quite surprising and clearly not the expected behavior.
This is also true for scene searches, galleries, images and markers.

**To Reproduce**
1. Go to Performers
2. Enter for example "fae" int he search field and click search
3. Depending on your db, there will be results of performers with no attribute containing that search term. In my case performers like  "Cindy Dollar", "Thainee" and "Irina Kristy". None of them has an attribute containing the term "fae"

This is even better visible when searching for number sequences "321" and the like.

**Expected behavior**
Searching for a scene or performer, I wouldn't care about hashes, but rather for name, aliases, titles and other attributes only, but not hashes

**Comment by WithoutPants** [comment]
This is expected behaviour when dealing with entities that have an underlying file (zip galleries, images and scenes) since these all have hashes based on the file contents. It should not be used for performers and markers.

**Comment by peolic** [comment]
https://github.com/stashapp/stash/blob/73a8bad1bcda926ba5eb09543b9f9a4d3c41b68d/pkg/sqlite/performer.go#L195

**Comment by WithoutPants** [comment]
> https://github.com/stashapp/stash/blob/73a8bad1bcda926ba5eb09543b9f9a4d3c41b68d/pkg/sqlite/performer.go#L195

This should really name and alias only. Ethnicity already has a filter option. We have a birth year filter, but not birthdate.
