### ISSUE TITLE
[Feature] Add performers tab to a Studio page & filter Performers by studio on performers grid page

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#1225]
**Is your feature request related to a problem? Please describe.**
There's no ability to filter performers by studio and no ability to show studio specific performers on a studio page

**Describe the solution you'd like**
- Add a performers tab to a studio's page displaying all performers that have a scene or image associated to selected studio
- Add a `studio` filter parameter for performers on performers grid page
  - Studio Is < string >
  - Studio Is not < string >

**Comment by WithoutPants** [comment]
There is currently no direct link between performers and studios. The only link is from performers to scene to studio. As such, the studio filter parameter probably needs a more specific name to describe the relationship.

A dedicated studios tab is probably not necessary. A list of studios in the details page is probably sufficient.

**Comment by echo6ix** [comment]
Darn.

I'm ignorant about the backend. I assumed to list all the performers associated with any given studio it would be analogous to a simple SQL query like:

`SELECT DISTINCT performers_scenes.performer_id FROM scenes, performers_scenes WHERE scenes.studio_id = 98 AND performers_scenes.scene_id = scenes.id`

**Comment by gitgiggety** [comment]
In 0.8.0 the "Studios" filter has been added to the Performers page. A studios page now also has a Performers tab which lists all performers with scenes, images or galleries for that studio. This as implemented in #1405, so I guess this ticket is fixed?
