### ISSUE TITLE
[Feature] Update packr2 version in README

### ISSUE THREAD

**Issue by mrbrdo** [stashapp/stash#1233]
The 2.0.2 packr2 version doesn't compile the make ui step for me on MacOS Big Sur (M1). It generated some wrong import paths in the generated files.
I used version 2.7.1 instead and that seemed to work fine.

Line needs update in README:
`go get github.com/gobuffalo/packr/v2/packr2@v2.0.2`

I also needed to increase ulimit -n (I just used 10000, the default was 256 and was too low for packr2).

**Comment by WithoutPants** [comment]
packr has now been removed
