### ISSUE TITLE
[Bug Report] v0.6.0 and Docker - White screen

### ISSUE THREAD

**Issue by melavas** [stashapp/stash#1242]
**Describe the bug**
Blank page (empty response) after upgrading to latest docker image. 

**To Reproduce**
Follow the included instructions in the `docker/production` instructions to start the docker version of the application.

**Expected behavior**
The application should present the login screen and show the web application after logging in.

**Screenshots**
<img width="904" alt="Screen Shot 2021-03-29 at 12 37 40" src="https://user-images.githubusercontent.com/78136117/112825037-90da1f80-908b-11eb-8cae-dab35f5ee228.png">

**Stash Version: `stashapp/stash:latest`

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Previous version was working fine.
I've tried removing all previous cache, metadata, config, etc. Still same result

**Comment by TheTwist76** [comment]
I have exactly the same problem. After updating to the latest docker image, i get a blank page after login screen.

Clearing Bowser cache, restarting container etc. did not help

**Comment by JanJastrow** [comment]
Same issue here.
Was able to upgrade the DB and after that just a blank page.

**Comment by overloadedStasher** [comment]
I have the same problem also.
Docker logs shows the webserver responding, but nothing is happening.
There is no errors in the console log for me.
If i go to /login, I can access the login page and actually login, but then I get redirected to the blank homepage.

**Comment by bnkai** [comment]
As mentioned in the discord channel something is wrong with the stable docler image
For now anyone can switch to the dev version `stashapp/stash:development` till the issue is resolved.
The dev version is essentially the same with it stable atm so you can use it and switch back as soon as the stable image is fixed.

**Comment by WithoutPants** [comment]
Apologies to those affected by this. I had to build the docker image manually due to Github problems, and due to a memory issue on my VM, an empty UI was built and included in the docker image. This has now been addressed with a new image pushed.
