### ISSUE TITLE
[RFC] API to create scenes

### ISSUE THREAD

**Issue by overloadedStasher** [stashapp/stash#1243]
*### Scope*
I'm working on a scenes downloader and I would like to be able to push new scenes to Stash. Since my downloader already has the metadata and other infos (Title, desc,  tags, date, url, etc) it would be a waste to just dump the file and scan to stash afterward. Ideally, an API endpoint would be provided to create the scene.

I've researched on the sceneUpdate graphql query, but it's not well documented and it seems to only update, not create a new scene.

Thank you!

**Comment by InfiniteTF** [comment]
Scenes are added by scanning, that's why there's no `sceneAdd` mutation. As long as the scenes are in one of the stash paths you can instead run a `metadataScan` with the folder in question set in the paths param.

**Comment by overloadedStasher** [comment]
Thanks, that's where I was heading while continuing my research.
This way, will I be able to set other informations while running a metadataScan? Or should I keep the stashID provided and run a sceneUpdate after?

**Comment by InfiniteTF** [comment]
metadatScan doesn't return anything useful so you have to wait until it's done and then run findScenes with a path filter set to the file in question to get the sceneid. Then you can run sceneUpdate.

Tedious I know, but adding a sceneAdd mutation would be a non-trivial amount of work for little gain for most users.

**Comment by overloadedStasher** [comment]
Thanks for the reply, it's much clearer now.

Tedious for sure, but not impossible ;) and also easier than adding a sceneAdd mutation!
