### ISSUE TITLE
v0.6.0 and Docker - White screen

### ISSUE THREAD

**Issue by flightsim73** [stashapp/stash#1245]
On v0.6.0 using Docker latest tag, I'm only getting a white screen. I get the login screen and then the database migration, which appears to work successfully and then just a blank screen. I also did a fresh install and it goes straight to a white screen.

**Comment by bnkai** [comment]
duplicate of <https://github.com/stashapp/stash/issues/1242>

**Comment by bnkai** [comment]
closing and stealing your title :-)
