### ISSUE TITLE
[Bug Report] Whitespace is not trimmed from the end of query strings

### ISSUE THREAD

**Issue by ALonelyJuicebox** [stashapp/stash#1260]
**Describe the bug**
If any whitespace characters follow the final character of a query, the entire Stash DB is returned as a result.

**To Reproduce**
1. Given that "MacAndCheese" is the name of a file, enter a query of "MacAndCheese " 
2. Observe that the entirety of the Stash DB is returned from the query rather than just "MacAndCheese"

**Expected behavior**
1. Given that "MacAndCheese" is the name of a file, enter a query of "MacAndCheese " 
2. Stash should return a result as if "MacAndCheese" has been entered, regardless of how much whitespace is entered at the end.

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Browser: Google Chrome 89.x
 - Stash Version: v0.6.0

**Comment by InfiniteTF** [comment]
I can't reproduce single issues with single trailing spaces, but I'm seeing the issue with single leading spaces ` test`, and multiple spaces anywhere in the string `test  `.

**Comment by ALonelyJuicebox** [comment]
Hmm...If you take a look at the URL, is the whitespace character parsed and converted to %20? Or do you see the query but without the trailing whitespace? I don't know when stash is designed to trim the additional whitespace off the end prior to running the query.
 
For example, this is what I see:
`http://localhost:<portnumber>/scenes?perPage=120&q=**MacAndCheese%20**&sortby=path&sortdir=desc`
