### ISSUE TITLE
[Feature] Auto scroll user back to the top when page number/page navigation is clicked

### ISSUE THREAD

**Issue by ALonelyJuicebox** [stashapp/stash#1267]
**Current State** 
If you click First, Previous, <page number>, Next or Last, Stash will open the next page of results, but it will do so without changing where you are in the browser window.

This is particularly unfortunate when the number of thumbnails displayed exceeds the height of your browser window, and you have already scrolled all the way to the bottom of the page-- forcing you to first manually scroll all the way to the top to see the beginning of the new page of results.

**Request:**
When clicking on any of the following (First, Previous, <page number>, Next or Last) auto scroll the user back to the top of the page.

**Comment by victorhooi** [comment]
Discussed in Discord here - https://discord.com/channels/559159668438728723/559159668912553989/847939383134126100

User mentioned it might be a regression associated with:

https://github.com/stashapp/stash/issues/1451
