### ISSUE TITLE
API Documentation Incorrect

### ISSUE THREAD

**Issue by CorneliousJD** [stashapp/stash#1269]
**Describe the bug**
https://github.com/stashapp/stash/wiki/API
Can scan for new files with cookies per the doc, but generate content with a cookie.txt file fails and says Graphql Validation Failed

**To Reproduce**
```
curl --verbose --cookie-jar cookie.txt  --data 'username=USER&password=PASS' localhost:9998/login
curl --cookie cookie.txt -H "Content-Type: application/json" --data '{ "query": "{ metadataGenerate ( input : { sprites: false previews: true markers:false transcodes:false } ) }" }' localhost:9998/graphql
```

**Output **
```
curl --cookie cookie.txt -H "Content-Type: application/json" --data '{ "query": "{ metadataGenerate ( input : { sprites: false previews: true markers:false transcodes:false } ) }" }' localhost:9998/graphql
{"errors":[{"message":"Cannot query field \"metadataGenerate\" on type \"Query\".","locations":[{"line":1,"column":3}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}],"data":null}
```

**Expected behavior**
I would expect the generated content to happen, with no error.

**Stash Version: (from Settings -> About):**
0.6.0 (Docker)

**Comment by bnkai** [comment]
The wiki API  documentation is a little outdated.
Using 
```bash
curl  --cookie cookie.txt -X POST -H "Content-Type: application/json" --data '{ "query": "mutation { metadataGenerate ( input : { sprites: false previews: true imagePreviews: false markers:false transcodes:false } ) }" }' localhost:9998/graphql
```
 instead should work.

**Comment by peolic** [comment]
Looks like the query was missing a couple of keywords (`mutation` operation and `imagePreviews` input value).
Fixed up the wiki.

Try:
`curl --cookie cookie.txt -H "Content-Type: application/json" --data '{ "query": "mutation { metadataGenerate ( input : { sprites: false previews: true imagePreviews: false markers:false transcodes:false } ) }" }' localhost:9998/graphql`

**Comment by CorneliousJD** [comment]
> Looks like the query was missing a couple of keywords (`mutation` operation and `imagePreviews` input value).
> Fixed up the wiki.
> 
> Try:
> `curl --cookie cookie.txt -H "Content-Type: application/json" --data '{ "query": "mutation { metadataGenerate ( input : { sprites: false previews: true imagePreviews: false markers:false transcodes:false } ) }" }' localhost:9998/graphql`

Thanks, this works correctly now.

Is there a way to string together a scan, auto-tag, and generate, all into one command?

Right now if I try the following it only scans, and the genrate doesn't kick off.
Also not sure if the "usefilemetadata" is doing the auto-tagging or not? I'd like to automate all this to happen on a sechedule instead of doing it manually. 

`curl --cookie cookie.txt -H "Content-Type: application/json"  --data '{  "query": "mutation { metadataScan ( input: { useFileMetadata: true} ) } "}' localhost:9999/graphql && curl --cookie cookie.txt -H "Content-Type: application/json" --data '{ "query": "mutation { metadataGenerate ( input : { sprites: true previews: true imagePreviews: false markers:true transcodes:true } ) }" }' localhost:999/graphql`

Thanks in advance.

**Comment by bnkai** [comment]
I would advice you to have a look at  the playground. `staship:port/playground`. The schema and docs to the right provide a complere reference to the graphgql API
metadatascan for example can have the below
```yaml
input ScanMetadataInput {
  paths: [String!]
  useFileMetadata: Boolean
  stripFileExtension: Boolean
  scanGeneratePreviews: Boolean
  scanGenerateImagePreviews: Boolean
  scanGenerateSprites: Boolean
 }
```
The generate ones are what you need so that when scanning it  also does the generate.
The set name,date ... part i would leave as false. Not really useful and probably not what you think
The tag needs a separate query though

I would also recommend visiting our discord channel more direct help

**Comment by CorneliousJD** [comment]
Thanks, the playground will help a ton. I might need assistance in Discord on the auto-tag part, but I'll give it a shot myself first and see what I come up with. Thank you!
