### ISSUE TITLE
[Feature] Performer Roll-Up in Studio

### ISSUE THREAD

**Issue by GsMumbo** [stashapp/stash#1282]
**Is your feature request related to a problem? Please describe.**
For amateurs, performers are often tied to one “studio” such as OnlyFans. For pros, it’s nice to be able to see the videos from certain performers that exist in that studio or network.

**Describe the solution you'd like**
Add a tab to the Studio page for Performers. This will include any performers who have a scene , image, or gallery from that studio. When you click on them, it loads the performer with the filter set to only show content from that studio.

**Describe alternatives you've considered**
Instead of automatically rolling up those who have media with that studio, you could simply connect a performer to a studio. This would operate the same as connecting a scene, image, or gallery to a studio.

**Additional context**
This will make discovery of content so much easier, especially as you’re figuring out which performer and studios you tend to prefer.

**Comment by WithoutPants** [comment]
$20 bounty placed.
