### ISSUE TITLE
[Feature] Star Ratings for Performers

### ISSUE THREAD

**Issue by GsMumbo** [stashapp/stash#1283]
**Is your feature request related to a problem? Please describe.**
Performer tags are great, and have made filtering performers so much easier. There’s still no way to surface the ones you like though, aside from favorites. Unfortunately that puts all favorites on an equal level, which they aren’t. 

**Describe the solution you'd like**
Add a rating field to the performer page, implemented in the same way as scenes, images, and galleries.

**Describe alternatives you've considered**
1. You can instead have the ratings roll up, meaning that the performer’s star rating is an average of all their rated media.
2. You can create “5-star” performer tags. This is what I’m trying now, but you don’t have any way to sort by them efficiently.

**Additional context**
As someone with ADHD, if a performer is out of sight, then they’re out of mind. When I find someone I prefer, I would like to be able to assign the star rating so they can be easily resurfaced later via sorting. Plus when I get bored of the 5 star performers, I can easily scroll down to the 4 stars, then the 3 stars, etc.

**Comment by WithoutPants** [comment]
$20 bounty placed.

**Comment by MartinWe13** [comment]
_„You can instead have the ratings roll up, meaning that the performer’s star rating is an average of all their rated media.“_

+1 (also for studios and movies)
