### ISSUE TITLE
[Bug Report] Non-stopping transconding (live transcode)

### ISSUE THREAD

**Issue by Havaianas10** [stashapp/stash#1286]
**Describe the bug**

When I click the scene (not even start playing it), the container start transconding non-stop, even if i quit the scene and try navigating other areas.... only way to stop it is closing the browser and the container, then restart everything

**To Reproduce**
1. Open scene that need transcoding
2. Open any other tab (Performers, Tags, Galleries, etc)

**Expected behavior**
Transcoding only happens when on scene in playing, and should stop after navigating to other scenes or tabs

**Screenshots**
https://imgur.com/ncHRGN6
https://imgur.com/711Pbz7
(translation of the portuguese part on the ERRO msg in the second img:  _A established connection was annulled by the software on the host computer_. )

**Stash Version: (from Settings -> About):**
v0.6.0

**Desktop (please complete the following information):**
 - OS: Windows 10 Home - 2004 - 19041.867
 - Browser Chrome 
 - Version [89.0.4389.114 (oficial) 64 bits]

**Smartphone (please complete the following information):**

**Additional context**
Tried with a couple of file types:
mpeg4 and aac - (didnt stop until close stash)
vc1 and wmav2 - (in this file the trasconding stopped after 2-5 minutes)
Tried to change the resolution and format in the player configuration, same problem.
The transcoding starts as soon as I open the scene page, and dont stop even if I play-pause the video, or change tabs. Most of the videos plays normally, some of the videos get stuck.
Tried lowering "Maximum streaming transcode size" in configs, same problem

TY

**Comment by Havaianas10** [comment]
Apparently after restarting and disabling google extensions it stopped.

**Comment by bnkai** [comment]
For future reference did you find/single out  the specific extension that caused the issue?

**Comment by Havaianas10** [comment]
Only had 2 extesions active, but didnt test it out. They were both fetch in page video downloaders
