### ISSUE TITLE
[Feature] Hide Child Studios

### ISSUE THREAD

**Issue by GsMumbo** [stashapp/stash#1288]
**Is your feature request related to a problem? Please describe.**
Some networks have a lot of child studios. This tends to clutter up the list quite a bit. 

**Describe the solution you'd like**
Either a switch or a filter to hide child studios in the list. Or in other words, only show studios that do not have a parent studio set. That way it includes both parent studios, and standalone studios.

**Describe alternatives you've considered**
This could be setup as a setting in the interface page, but it’s something that honestly might get flipped on / off fairly often. Having it available directly on the studios page would make the most sense.

**Additional context**
With child studios hidden, you would access them directly via the parent. So you’d go to your studios page, click Reality Kings for example, then pick your child studio. There’s less clutter on the studio page, and the flow feels more like a parent-child flow than it does at the moment.

**Comment by kermieisinthehouse** [comment]
This would be resolved by a combination of #1785 and the saved filters feature. 

You could make the default studio filter to be "Parent Studio is null"
