### ISSUE TITLE
[Feature] Studio Star Ratings

### ISSUE THREAD

**Issue by GsMumbo** [stashapp/stash#1289]
**Is your feature request related to a problem? Please describe.**
Similar to #1283 this would solve the issue of it being hard to surface studios that you prefer. Being able to assign star ratings would allow you to not only rate each studio, but to sort them in order of rating.

**Describe the solution you'd like**
Add a rating field to the studio page, implemented in the same way as scenes, images, and galleries.

**Describe alternatives you've considered**
You can instead have the ratings roll up, meaning that the studio’s star rating is an average of all their rated media.

**Additional context**
As someone with ADHD, if a studio is out of sight, then they’re out of mind. When I find a studio I prefer, I would like to be able to assign a star rating so they can be easily resurfaced later via sorting. Plus when I get bored of the 5 star studios, I can easily scroll down to the 4 stars, then the 3 stars, etc.

**Comment by MartinWe13** [comment]
_„You can instead have the ratings roll up, meaning that the studio’s star rating is an average of all their rated media.“_

+1 (also for performers and movies)
