### ISSUE TITLE
Aim to use only internally served libraries and scripts to avoid insecure references to external resources in production behind a HTTPS proxy.

### ISSUE THREAD

**Issue by Leopere** [stashapp/stash#130]
The title basically sums it up.

**Comment by Leopere** [comment]
Fixed by @joyov in #134

**Comment by Leopere** [comment]
Closed too soon, after testing I've not seen any change. @joyov can you verify if your PR worked in the latest image?

**Comment by joyov** [comment]
Yes, I can confirm that it works for me.
Are you sure your reverse proxy sets the `X-Forwarded-Proto` header correctly? (Correct value would be `https`.)

**Comment by joyov** [comment]
@Leopere Yes, I can confirm that it works for me. Are you sure your reverse proxy sets the `X-Forwarded-Proto` header correctly? (Correct value would be `https`.)

**Comment by Leopere** [comment]
I've been using Traefik so theoretically it should be rewriting everything but it seems fixed now.
