### ISSUE TITLE
Phash generation for existing files?

### ISSUE THREAD

**Issue by victorhooi** [stashapp/stash#1300]
I saw that Phash generation was recently added to the Develop branch. That's great.

However, when I try to look for duplicates - it only seems to find any for recent files (e.g. files added to Stash after I installed the Phash build).

To confirm - it should be generating phash for all files, including pre-existing files, right?

Or is there any reason the duplicate checks only sees recent hits?

**Comment by peolic** [comment]
You can run the generation task for all the files in your library.
![image](https://user-images.githubusercontent.com/66393006/114654785-89558000-9cf3-11eb-9eac-b332cf0096bd.png)

**Comment by WithoutPants** [comment]
Phashes are only generated using the Generate task, or if you ticked to generate them during a scan.
