### ISSUE TITLE
[Feature] Clear button on the search input group components

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#1306]
**Describe the solution you'd like**
An "x" button on the search input forms to clear the input component of the existing string.

![bootstrap-clear-button](https://user-images.githubusercontent.com/37937507/114910849-5e028c00-9dec-11eb-92fa-890d975fc57a.png)

**Comment by Gykes** [comment]
Appears to have been solved. 

https://github.com/stashapp/stash/pull/1845
