### ISSUE TITLE
Show Scene Save/Delete/Scrape buttons when scrolled down

### ISSUE THREAD

**Issue by venturevoom** [stashapp/stash#1315]
UX Improvement/Request:

The Save/Delete/Scrape Buttons in a scene scroll with the lower Dataset. So if i add some tags (and scrolled that part) they are invisible and i have to scroll up to save. There is enough static space under "Details / Queue / Markers / Gallery ..." for the buttons.

So it would improve the usability to move these three buttons in the upper, static part of the UI

![image](https://user-images.githubusercontent.com/72347089/115068703-e1a6a080-9ef2-11eb-9e3c-e7de00040043.png)

**Comment by 7dJx1qP** [comment]
The buttons can be made static with some custom CSS
```
#scene-edit-details > form > div:first-child {
    position: sticky;
    top: 0;
    z-index: 999;
    background-color: #202b33;
}
```
