### ISSUE TITLE
[Feature] Add Image Count Filter to Galleries

### ISSUE THREAD

**Issue by GsMumbo** [stashapp/stash#1318]
**Is your feature request related to a problem? Please describe.**
You aren’t currently able to filter galleries based on image count. Thanks to some of the “packs” in my library, there are a bunch of one image galleries. As of now though you aren’t able to filter them out, so they end up cluttering up my library and make it hard to sift through.

**Describe the solution you'd like**
Image Count is added to the list of filters in the drop down for Galleries.

**Comment by julien0221** [comment]
it has been added recently.
