### ISSUE TITLE
Improve Toast positioning

### ISSUE THREAD

**Issue by QxxxGit** [stashapp/stash#1323]
Couldn't find an issue related to this but I apologize if there's already one.

**Describe the bug**
The `.toast-container` overlays buttons on pages where you want to edit multiple scenes, images, etc. This makes it a nuisance when editing multiple items because you have to wait until the toast disappears.

**To Reproduce**
1. Go to scenes.
2. Select an item to edit, click the edit icon and edit with a tag or assign to a performer (whatever works).
3. Save the changes. You will see the toast appear over the order dropdown, edit button, etc.

**Expected behavior**
I believe it's better to position the toast at the bottom right of the screen, out of the way so it's not overlapping anything.

**Stash Version: (from Settings -> About):** 0.6.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 87.0

**Solution:**
This works on my end. Anyone else want to verify/check for issues? Thanks to Belley from the Discord the solution seems to be (for bottom-right positioning):

```css
.toast-container {
    position: fixed;
    right: 2rem;
    bottom: 1rem;
    top: initial;
    left: initial;
}

**Comment by tonynca** [comment]
Please fix this! It's really annoying when trying to organize my library. TY
