### ISSUE TITLE
[Feature] Create movie from Scene edit dialog

### ISSUE THREAD

**Issue by hmahler2** [stashapp/stash#1331]
To introduce the ability to manually create a new movie by entering a title in the Scene > Edit > Movie dialog box. This would bring Movies into parity with the Performer, Studio and Tag dialogs on the same page. Otherwise you have to go out to the Movies page > New then come back to Scene > Edit.

**Comment by Ch00nassid** [comment]
If TPD (metadata.net) or Stashdb ever start making connections to scenes being part of a movie, having this function may be really good to incorporate into the plugins!  On the same hand, it may make it easy to pass the movie information from those 2 sites in the future...
