### ISSUE TITLE
[Bug Report] Tagger will continue to "stack" found fingerprints after you complete a large amount of tags

### ISSUE THREAD

**Issue by Ch00nassid** [stashapp/stash#1372]
**Describe the bug**
I found fingerprints, hit " hide unmatches scenes", did like 200 matches, showed all scenes, searched for fingerprints again, hid unmatched scenes.....

**To Reproduce**
1. Go to 'Scenes'
2. Click on 'match fingerprints'
3. Click on "hide unmatched scenes"
*Complete a large amount of saving -- leaving some _not_ saved*
4. Click on "unhide unmatched scenes"
5. click on 'match fingerprints'
*the scenes that were left "not saved" should have the same scene matched against it (duplicate found fingerprint)*

**Expected behavior**
I figured that if the scene that is found is already in the recommendations, it should ignore the scene when trying to find the fingerprints.

**Screenshots**
![image](https://user-images.githubusercontent.com/57732969/117388006-82afc800-aeaf-11eb-967a-676707531279.png)

**Stash Version: (from Settings -> About):**
Version:	v0.6.0-61-g2ab42e9c
Build hash:	2ab42e9c
Build time:	2021-05-03 04:28:17

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [chrome]

**Comment by InfiniteTF** [comment]
@Ch00nassid Could you try this in the latest build? I wasn't able to reproduce it.

**Comment by Ch00nassid** [comment]
The latest DEV build?  or stable?  I will download the latest DEV build tonight and give it a shot.
