### ISSUE TITLE
[Bug Report] Importing Via CSV Using GQL Iterate (Documentation Issue / Important Step)

### ISSUE THREAD

**Issue by meanjoep92** [stashapp/stash#1389]
Based off this specific link here...

https://github.com/stashapp/stash/wiki/Importing-via-CSV-using-gql-iterate

The latest versions of **NodeJS** (14>) will show an error stating that "required is not defined" upon trying to use gql-iterate...

The solution was to just go to the cli.js file found within it's directory (**C:\Users\MyUserName\AppData\Roaming\npm\node_modules\@efstajas\gql-iterate\bin**) and insert the following code at the top of the JavaScript file.

`import { createRequire } from 'module';
const require = createRequire(import.meta.url);`

Doing this in hopes that this helps anyone else attempting to follow the documentation.

**Comment by peolic** [comment]
This is more of a `gql-iterate` issue.
https://github.com/efstajas/gql-iterate/pull/4

**Comment by kermieisinthehouse** [comment]
Fixed upstream in gql-iterate
