### ISSUE TITLE
Travis-CI should upload builds to a temporary file locker like https://transfer.sh for more streamlined testing.

### ISSUE THREAD

**Issue by Leopere** [stashapp/stash#139]
## Requirements for completion
- [x] Windows binary upload to transfer.sh
- [x] Linux binary upload to transfer.sh
- [x] OS X binary upload to transfer.sh
- ~~Discord API connected push notification to send the returned URL's and a message containing the details regarding what PR the tests uploaded binaries are from and potentially a link back to that said PR to shortcut anyone having to review the binary.~~

**Comment by bnkai** [comment]
I'm not an exper but from what i understand [https://blog.questionable.services/article/build-go-binaries-travis-ci-github/](url) or [https://dev.to/hawkinjs/leveraging-travis-ci-for-continuous-deployment-to-publish-compiled-binaries-to-github-2k06](url) it may be easier to upload the binaries back at github as testing releases.
I see that also for discord [https://github.com/DiscordHooks/travis-ci-discord-webhook](url)
Both of those from what i see require access to the travis account though.

**Comment by Leopere** [comment]
I have access to travis from my perspective, not sure to what level yet though.  I just like transfer.sh because its a public filelocker that selfdestructs after a month and stores stuff up to 1gb in size with nothing but a curl.  We don't necessarily need PR builds recorded forever.

**Comment by WithoutPants** [comment]
Windows and linux binary uploads only? Why exclude the OSX binary?

Unless someone else has admin access to the Discord server, the Discord hook will need to be done by @StashAppDev .

It does seem a bit heavy handed to upload three ~50MB binaries (for mac, linux and Windows) for what is likely to be used by a very small proportion of people. Also adds extra time to the CI builds performing the uploads.

**Comment by Leopere** [comment]
@WithoutPants it was me assuming we didn't have OS X binaries last I heard there were only the two.

**Comment by WithoutPants** [comment]
I think this is sufficiently complete. Can reopen if we decide to pursue the Discord notification.
