### ISSUE TITLE
[Feature] Add NULL/Not NULL to Studios filter

### ISSUE THREAD

**Issue by SilentSpartan** [stashapp/stash#1398]
The URL filter has a option for "Is NULL" "Not NULL". I would really like this added to the Studios filter as well. Thank you!

**Comment by gitgiggety** [comment]
"studio is null" can be done using "is missing: studio". But there is no "has: ..." filter indeed.

Not sure though why it's implemented like this. As you can both do "url: is null" and "is missing: url" which yields the same result.
