### ISSUE TITLE
[Feature] German language

### ISSUE THREAD

**Issue by hassaffe** [stashapp/stash#1409]
I would like to do a translation. But I couldn't find a language file. Is there a template in which I could do the translation?

**Comment by InfiniteTF** [comment]
Translations are located in `https://github.com/stashapp/stash/tree/develop/ui/v2.5/src/locale`. All you have to do is copy `en-GB.json` to `de-DE.json` and add translations. Once the file is created it has to be added to `ui/v2.5/src/locale/index.ts` and `ui/v2.5/src/components/Settings/SettingsInterfacePanel/SettingsInterfacePanel.tsx` as well. You can just follow the same pattern as for `zh-TW`.

Unfortunately most text is not currently available for translation. It's something that has been in the backlog for a while.

**Comment by Belleyy** [comment]
> Unfortunately most text is not currently available for translation. It's something that has been in the backlog for a while.

I think #1406 add way more text/word.

I think it would be better for you to wait this PR then do the translation.

**Comment by hassaffe** [comment]
ok i'll wait until it is better supported.

**Comment by PhilippKeil** [comment]
PR #1471 is now merged as well. Now would be the time for a first translation. I'd offer my help as well.

**Comment by Phasetime** [comment]
I'll take on the task since the issue seems to have gone stale.

**Comment by hassaffe** [comment]
i will prepare a translation as soon as possible.

**Comment by WithoutPants** [comment]
Resolved by #1578

**Comment by hassaffe** [comment]
How can I test the language file I have adapted locally on my Linux system?

**Comment by kermieisinthehouse** [comment]
You can run `make ui-start` to start a development UI server, which will have your changes. You need to run stash at the same time to have a backend.
