### ISSUE TITLE
[Bug Report] SQL error on performers filter by missing image

### ISSUE THREAD

**Issue by CosimoVestri** [stashapp/stash#1420]
**Describe the bug**
When viewing performers and filtering by "is missing" "image" there occurs a SQL error:

> Error executing count query with SQL: SELECT COUNT(*) as count FROM (SELECT DISTINCT performers.id FROM performers LEFT JOIN performers_images ON performers_image.performer_id = performers.id WHERE performers_image.performer_id IS NULL GROUP BY performers.id ) as temp, args: [], error: no such column: performers_image.performer_id

Executing the same query on the SQLite database directly yields the same result.

**To Reproduce**
1. Go to Performers
2. Filter by "Is Missing" "Image"
3. See error.

**Expected behavior**
Return expected filtered table.

**Screenshots**
If applicable, add screenshots to help explain your problem please ensure that your screenshots are SFW or at least appropriately censored.

**Stash Version: v0.7.0-14-g33999d3e**

**Additional context**
I've not yet looked through the code, but I think I know what's causing the error (in terms of the SQL query).

The executed query is:
```
SELECT
   COUNT(*) as count 
FROM
   (
      SELECT DISTINCT
         performers.id 
      FROM
         performers 
         LEFT JOIN
            performers_images 
            ON performers_image.performer_id = performers.id 
      WHERE
         performers_image.performer_id IS NULL 
      GROUP BY
         performers.id 
   )
```

The problem appears to be in the LEFT JOIN, where the incorrect table is referred to. `performers_images` should be `performers_image`, should it not?

**Comment by bnkai** [comment]
PR is already available for this issue
<https://github.com/stashapp/stash/pull/1413>

**Comment by CosimoVestri** [comment]
That's what I get for not checking PR's before filing an issue.
