### ISSUE TITLE
[Feature] Keyboard shortcut for next scene in scene view

### ISSUE THREAD

**Issue by bliks06** [stashapp/stash#1423]
**Describe the solution you'd like**
While I'm in a scene's detail view, (with the video playing on the right side and details on the left) editing a scene I would like a shortcut for the next/previous scene. It would make going through scenes so much more convenient for tagging/marker purposes. It's a bit of a pain needing to back out then click in to the next scene.  I'm sure there's other use cases for such a feature as well. Cheers!

**Comment by WithoutPants** [comment]
Note that the queue tab allows you to travel to the next scene in the list when navigating from the scenes view. There is currently no keyboard shortcuts for navigating within the queue though.

**Comment by WithoutPants** [comment]
$20 bounty placed.
