### ISSUE TITLE
[Bug Report] Renamed files/directories keep getting detected as duplicates repeatedly

### ISSUE THREAD

**Issue by deliciousnights** [stashapp/stash#1426]
When renaming some of the already scanned files and re-scanning leads to the following log entries:
```
[2021-05-24 23:41:40] Y:\ph\thestartofus\thestartofus (20201202) [ph5fc7a8306a205].mp4 not found. Calculating oshash...
[2021-05-24 23:41:40] Y:\ph\thestartofus\thestartofus (20201202) [ph5fc7a8306a205].mp4 already exists. Duplicate of Y:\ph\thestartofus\THESTARTOFUS (20201202) [ph5fc7a8306a205].mp4
```
Looks like it happens only if the only change in the file name is a changed of a letter(s) case (upper/lower).
These messages do not go away with repeated scans.

**To Reproduce**
1. Have Stash scan a certain file
2. Rename the file, but only change a letter from uppercase to lowercase, or vice-versa
3. Scan the file again

**Expected behavior**
Stash should accept the new name and forget the old, non-existing one.

**Stash Version: (from Settings -> About):**
v0.7.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 88.0.1

**Comment by bnkai** [comment]
Stash relies on os.Stat for the duplicate checks. If `os.Stat` returns ok then that probably means that the filesystem is case insensitive? Can you check what filesystem is used in the `Y:` drive ?

**Comment by WithoutPants** [comment]
Confirmed on Windows local drive.

**Comment by deliciousnights** [comment]
Filesystem is NTFS on windows - case insensitive.
