### ISSUE TITLE
[Bug Report] Incorrect load of images on iOS devices

### ISSUE THREAD

**Issue by SuperEllipsis** [stashapp/stash#1430]
**Describe the bug**
Images in the gallery view and images view load incorrectly most (Almost all) of the time, when using the wall display type. This problem has only occured on iOS devices (Both iOS, and iPadOS).

**To Reproduce**
1. Go to the gallery tab
2. Open some gallery
3. Set display mode to 'Wall'
4. Open an image
5. If it loads correctly, change the device's orientation

**Expected behavior**
I expect the images to load in the correct size respective to the screen size of the device the image is being displayed on.

**Screenshots**
It sometimes works (image 1):
<img width="1112" alt="Stash" src="https://user-images.githubusercontent.com/82902785/119529286-7cf02880-bd71-11eb-9950-f0c2a1b267d7.png">

However change the screen orientation, and it disappears (image 2):
<img width="834" alt="Stash 2" src="https://user-images.githubusercontent.com/82902785/119529358-91342580-bd71-11eb-829d-033b8afffe90.png">

Change the orientation back, and it may return in a far smaller size (image 3):
<img width="1112" alt="Stash 3" src="https://user-images.githubusercontent.com/82902785/119529442-a6a94f80-bd71-11eb-89db-f6a2cc4a873a.png">

On the smaller screen of the iPhone it usually does not show up at all (image 4):
![Stash 4](https://user-images.githubusercontent.com/82902785/119529561-be80d380-bd71-11eb-967b-bd9dddfe0b3d.png)

**Stash Version:** v0.7.0 and v0.7.0-30-gd6ada236

**Smartphone:**
 - Device: iPhone 12
 - OS: iOS 14.5
 - Browser: safari

**Tablet:**
 - Device: iPad Pro 11-inch (1st gen)
 - OS: iPadOS 14.4
 - Browser: safari

**Additional context**
It seems typical for the images to not even render on iPhone, while it sometimes works on iPad until the screen orientation is changed. Once the orientation has been changed it usually makes all images in that gallery fail to render properly. It can be reset by closing the browser and opening it again. The state also does not seem to stick between galleries, one can open another gallery and the images in this gallery might work fine until the orientation is changed.

**Comment by thatbrick** [comment]
Not sure what's causing the issue, but by playing around with the styling, I was able to load the image by commenting out the height parameter entirely for ".Lightbox-carousel-image" class.
