### ISSUE TITLE
[Feature] Gallery custom thumbnail cover

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#1432]
**Describe the solution you'd like**
Add option to add custom thumbnail covers for each gallery

**Additional context**
There could be two avenues for adding a gallery cover image:

- 1. Add custom thumbnail via gallery edit options
  - Add cover image 
    - Upload image
    - image from Url
    - Delete image
- 2. Add gallery cover via `more menu` button
  - Select image in gallery > More menu button > Set as gallery cover

**Comment by FlashSpazzbo** [comment]
Ideally, this would allow for a cover image for which the filename is not cover.jpg

Or, allow for a cover.jpg that is a duplicate file of another image.

**Comment by YurikaL** [comment]
Related issues: #863 #872

**Comment by DogmaDragon** [comment]
@chenw191 select image in the gallery > ... > Set as Cover.

**Comment by Maista6969** [comment]
Pick an image in the gallery view and then it's in the kebab menu
![image](https://github.com/user-attachments/assets/4264b0ae-0056-4c3e-a03a-082152f52094)
