### ISSUE TITLE
Scanning should regenerate screenshots if missing

### ISSUE THREAD

**Issue by WithoutPants** [stashapp/stash#144]
If a scene's screenshot wasn't generated or was subsequently removed, then it is not possible to regenerate the screenshot without removing the scene and rescanning, or renaming the file and rescanning. The scan function should check for the presence of the screenshot, even if the scene is already found.

**Comment by ExceptionalError** [comment]
Shouldn't the screenshot generation only be done when generating and not while scanning?

**Comment by bnkai** [comment]
It is part of the scaning process anyway because we need these images anyway.
The generate part has parts that some people may not want ,need or whatever thats why they can be opted out.

**Comment by Leopere** [comment]
Closed by #145
