### ISSUE TITLE
[Bug Report] Navigating back scrolls you to the top of the page

### ISSUE THREAD

**Issue by GsMumbo** [stashapp/stash#1442]
**Describe the bug**
If you navigate to a specific piece of media, navigating back to the containing collection using the browser back button scrolls you back to the top of the page. If you’re for example going through your images and adding tags to then one by one, it quickly becomes unmanageable having to scroll back down to where you left off every time you finish with an image.

**To Reproduce**
1. Open a collection that includes a large number of items. For example the Images tab.
2. Scroll halfway down the page, then open an image.
3. Hit **Back** in your browser to navigate back to the original collection. You will be scrolled to the top of the page.

**Expected behavior**
You click **Back**  and resume viewing the collection from halfway down the page (where you were when you selected the image). You can then scroll down a negligible amount to open the next image.

**Stash Version: (from Settings -> About):** v0.7.0-33-gc70faa2a

**Smartphone (please complete the following information):**
 - Device: Various (primarily iPhone 12 Mini, iPad Pro 12.9”, and Galaxy Fold 2)

**Additional context**
I believe this started when a pull request was merged in that auto scrolled you to the top of the list in certain conditions. I don’t remember the PR offhand, but it wasn’t intended to also do this when navigating back via your browser.

**Comment by WithoutPants** [comment]
I've confirmed that the original behaviour works in commit https://github.com/stashapp/stash/commit/d042ec42ee0fb57df6956fd1701dd2c2444ae0ad for #1270 so this issue is caused by something else.

**Comment by WithoutPants** [comment]
After some further investigation, I have determined that this appears to have been introduced by https://github.com/stashapp/stash/commit/c38660d209d134b7b848721244ce31276f856990 (#1158). As of yet, I've been unable to determine why.

**Comment by WithoutPants** [comment]
This is happening because the `findScenes` query is being reloaded when pressing the back button, instead of loading from the cache. 

The problem was introduced by #1158. Specifically, the addition of `paths.sprite` to `SlimSceneData`. If I remove this (along with the referencing UI code), then the query is reloaded from cache and the position on the previous page is maintained. As soon as I add it back (without re-introducing the referencing code), it hits the network. I cannot figure it out.
