### ISSUE TITLE
[Feature] Add Description to Images

### ISSUE THREAD

**Issue by GsMumbo** [stashapp/stash#1443]
**Is your feature request related to a problem? Please describe.**
Right now you can add a description to Galleries and Scenes, but not individual images.

**Describe the solution you'd like**
Add a property to Images (and thus a field in the UI) for the description.

**Describe alternatives you've considered**
None

**Additional context**
Descriptions are especially useful when you have a gallery that contains an assorted mix of images instead of a specific set. With a set you could add the description to the gallery as a pseudo workaround, but with an assorted mix each image is vastly different from each other, so they each need their own descriptions.

**Comment by 4n70w4** [comment]
The same issue!
