### ISSUE TITLE
[Feature] Add Descriptions to Tags

### ISSUE THREAD

**Issue by GsMumbo** [stashapp/stash#1444]
**Is your feature request related to a problem? Please describe.**
Tags aren’t currently able to have a description set. Even (or especially) with tag aliases now enabled, it becomes important to be able to define what a tag means.

**Describe the solution you'd like**
Tags are updated to include a description property, and thus a description field in the UI. In addition, including a preview of the description in the tags dropdown would be amazing (but can be skipped if it’s too much work)

**Describe alternatives you've considered**
None

**Additional context**
The reason I mention tag aliases is that it highlights the need for a description. For example let’s say I have a tag called `skinny` and it has an alias `petite`. That makes sense, but I might also have a tag `tiny` that seems like it would fit under `skinny`, but in my categorization it means something different. In this case `tiny` is looking at the overall package, someone who’s both short and skinny, and is more of a gut feeling kind of tag. It’s hard to know that offhand, and when tagging if there are a few sets of tags that are like that then it can be hard to keep it straight. Having those descriptions helps with that, and keeps the tagging methodology consistent.

**Comment by ALonelyJuicebox** [comment]
+1 For this feature, _as well as_ a huge +1 to seeing a preview of the description of a given tag on mouseover in the tag form dropdown or on mouseover of the tag when viewed on the Edit or Details tabs.

**Comment by WithoutPants** [comment]
$50 bounty placed (8-Jun-2022).
