### ISSUE TITLE
[Feature] Performer Pairings

### ISSUE THREAD

**Issue by hdj2** [stashapp/stash#1455]
**Is your feature request related to a problem? Please describe.**
No problem. I think it would be awesome if people could see which actor works with witch actor.

**Describe the solution you'd like**
Please add an tab or a button which shows all performers he or she has a scene with. For Example if I click on Performer A than it shows me there are two scenes with Performer B, one with Performer C and four with Performer D.
Like iafd.com it has for example.

**Describe alternatives you've considered**
None

**Additional context**
I love your work <3

**Comment by houstonguy** [comment]
Could this feature become a bounty please?

**Comment by DogmaDragon** [comment]
> Could this feature become a bounty please?

Bounties are handled through [Open Collective](https://opencollective.com/stashapp).
![image](https://user-images.githubusercontent.com/103123951/215674207-0feb3c15-9040-4277-8e59-edacd61e7ffb.png)

**Comment by houstonguy** [comment]
I am aware that bounties are handled on Open Collective. Your screenshot literally says "confirm with the Stashapp team on github before proceeding". This is me confirming on github that it is OK for this feature to become a bounty.

**Comment by houstonguy** [comment]
Also basing this request on this comment.. which could be out of date: 

https://github.com/stashapp/stash/issues/2937#issuecomment-1253050605

**Comment by DogmaDragon** [comment]
> I am aware that bounties are handled on Open Collective. Your screenshot literally says "confirm with the Stashapp team on github before proceeding". This is me confirming on github that it is OK for this feature to become a bounty.

My bad. I wasn't sure what you meant by the initial comment.

**Comment by houstonguy** [comment]
No problem. How can I be clearer for getting approval for bounties? I want to financially support the project and which I had time to contribute code (Learning yet-another-fine-programing-language is not something I have time for), so I had thought that I would start putting bounties on some existing simple, well-described features and then add a few feature requests of my own.

**Comment by DogmaDragon** [comment]
> No problem. How can I be clearer for getting approval for bounties? I want to financially support the project and wish I had time to contribute code (Learning yet-another-fine-programing-language is not something I have time for), so I had thought that I would start putting bounties on some existing simple, well-described features and then add a few feature requests of my own... and then add bounties to those too.
> 
> This pattern, of keeping bounties as reasonable near-term goals and improvements, has worked for me well in the past.

Maybe it's just me that misunderstood what you meant. Something like `Is this feature request eligible for bounty?` would be more clear for me, but again it might be just me who misunderstood. 

I posted these on Discord for better visibility, someone from the Org will respond if they are eligible.

**Comment by houstonguy** [comment]
[This has been approved for a bounty on discord. ](https://discordapp.com/channels/559159668438728723/646522098746916874/1072359976414216203)

I have kicked things off with $25.

**Comment by WithoutPants** [comment]
$25 bounty placed (contribution no. 524297)

**Comment by SpedNSFW** [comment]
I think the best way to implement this is to have a new tab on a performer's page called "Pairings" or w/e. In that tab, you'd have the same layout as the Performers page, however instead the scene/movie/image counts will be for the pair, and they'll link to the Scenes page already filtered for both performers.

This way would likely require the least amount of work.

**Comment by WithoutPants** [comment]
I agree, the naming can be workshopped (I'd prefer something like "Appears with"). It will still require backend changes to support querying for this information.

**Comment by Teda1** [comment]
Resolved by https://github.com/stashapp/stash/pull/3563
