### ISSUE TITLE
[Feature] Allow Multiple Gender Filters for Performers Page

### ISSUE THREAD

**Issue by Slabster2000** [stashapp/stash#1457]
**Is your feature request related to a problem? Please describe.**
It would be nice to not be restricted to only one gender option for the Performers page Filter tab. Having only two (or more) genders selected for Filters is not possible at this time.

**Describe the solution you'd like**
I would simply like to be able to select multiple genders in the Filter tab for the Performers page. Example: only show "Male" and "Female" on the Performers page, and omit displaying all other genders.

**Describe alternatives you've considered**
None.

**Additional context**
I love StashApp! You guys have done a great job!

**Comment by WisdomWolf** [comment]
Would also be useful to be able to filter for not equals on gender.  I go through to make sure I have photos for all the female performers, but when they first get added they don't have anything but a name, so I'd like to filter for performers where gender != male and image is missing.
