### ISSUE TITLE
[Bug Report] DLNA error on Samsung TV

### ISSUE THREAD

**Issue by qqqzzzzzzqqq** [stashapp/stash#1465]
**Describe the bug**

I have a Samsung TV, model UE40MU6400.

I can get the Stash DLNA server running fine and can browse/play from a VLC client.

The TV finds the server but then displays only "No Content Found". Whenever I hit the refresh button on the TV I see the following in the Stash log:

```
strconv.Atoi: parsing "/": invalid syntax
```

**To Reproduce**

1. Enable the DLNA server and whitelist the TV's IP address.
2. Go to the "Source" menu on the TV and select the server (which appears just fine)
3. Hit "Refresh" on the screen labelled "No Content Found" (error appears in Stash logs every time the button is pressed).

**Expected behavior**

I should be able to browse my content.

**Stash Version: (from Settings -> About):**

v0.7.0-39-g975343d2

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 91.0.4472.77

I hope that's helpful! I know you don't support these TVs yet but I wondered if maybe it's some incoming data you can skip over rather than crashing?

**Comment by bnkai** [comment]
The issue seems to with the package used by stash for dlna <https://github.com/anacrolix/dms/issues/56>
It doesnt seem that a fix is available atm

**Comment by WithoutPants** [comment]
@qqqzzzzzzqqq can you turn on trace logging, retry connecting from the TV and post the log output?

It should look something like `<serverType>::Handle <action> - <xml>`

**Comment by qqqzzzzzzqqq** [comment]
Sure! Here you go:

```
TRAC[2021-06-17 22:25:13] ContentDirectory::Handle Browse - <u:Browse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1"><ObjectID>0</ObjectID><BrowseFlag>BrowseMetadata</BrowseFlag><Filter>*</Filter><StartingIndex>0</StartingIndex><RequestedCount>0</RequestedCount><SortCriteria></SortCriteria></u:Browse>
ERRO[2021-06-17 22:25:13] strconv.Atoi: parsing "/": invalid syntax
```

**Comment by WithoutPants** [comment]
@qqqzzzzzzqqq thank you. Are you able to test the fix in #1517 using the generated binaries?

**Comment by qqqzzzzzzqqq** [comment]
@WithoutPants Awesome - happy to! Can you remind me how to get the generated binaries for a branch? I've had trouble building it from sources successfully.

**Comment by MrX292** [comment]
@qqqzzzzzzqqq under Checks over the build log on the right click Artifacts

**Comment by MrX292** [comment]
@WithoutPants it shows the first set of folders like all, tags, movies, rating, studios, performers
but if i open one i get
`Error   strconv.Atoi: parsing "performers": invalid syntax`
````
2021-06-19 11:37:17Error   strconv.Atoi: parsing "tags": invalid syntax
2021-06-19 11:37:17Debug   ContentDirectory::Handle Browse - <u:Browse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1"><ObjectID>tags</ObjectID><BrowseFlag>BrowseMetadata</BrowseFlag><Filter>*</Filter><StartingIndex>0</StartingIndex><RequestedCount>0</RequestedCount><SortCriteria></SortCriteria></u:Browse>
2021-06-19 11:37:17Error   strconv.Atoi: parsing "tags": invalid syntax`
```

**Comment by qqqzzzzzzqqq** [comment]
@WithoutPants Same thing for me as what happens for @MrX292:

```
ERRO[2021-06-19 17:42:41] strconv.Atoi: parsing "performers": invalid syntax 
TRAC[2021-06-19 17:42:41] ContentDirectory::Handle Browse - <u:Browse xmlns:u="u
rn:schemas-upnp-org:service:ContentDirectory:1"><ObjectID>performers</ObjectID><
BrowseFlag>BrowseMetadata</BrowseFlag><Filter>*</Filter><StartingIndex>0</Starti
ngIndex><RequestedCount>0</RequestedCount><SortCriteria></SortCriteria></u:Brows
e> 
ERRO[2021-06-19 17:42:41] strconv.Atoi: parsing "performers": invalid syntax 
```

**Comment by WithoutPants** [comment]
@qqqzzzzzzqqq @MrX292 thanks!

Can you please retest with the latest binaries on the PR?

**Comment by qqqzzzzzzqqq** [comment]
@WithoutPants Hooray! I can now browse using any of the folders and see all the thumbnails successfully! Some clips play but most are just a black "loading" screen (nothing obvious in the logs). I'm guessing that's because as you said before you're not serving up the transcoded version if it's available?

**Comment by WithoutPants** [comment]
Thanks for confirming. That would indeed be my assumption if some videos are playing successfully. I'll merge in the PR which will close this issue. Thanks for the report and assistance.

**Comment by ctyjiuh** [comment]
Hi.
I'm still experiencing same problems in version v0.9.0. Is there any solution?

**Comment by MrX292** [comment]
@ctyjiuh did you enable the ip Adress in stash?
if so do you have any error messages in the log

**Comment by ctyjiuh** [comment]
@MrX292 I'm using docker version of the app in macvlan mode. So for logging I used docker-compose up and see stdout with info level.
I have enabled DLNA with these parameters:
- Recent IP addresses: blank (also tried stash's IP and TV's IP)
- Server display name: ppp
- Enabled by default: no
- Interfaces: eth0
- Default IP Whitelist: * (also tried TV's IP)

There were same records in all conditions (192.168.88.24 is stash's IP):

```
stash_1  | INFO[2021-09-18 07:58:11] stash is running at http://localhost:9999/
stash_1  | 2021/09/18 08:03:30 "POST http://192.168.88.24:9999/graphql HTTP/1.1" from 192.168.88.54:51259 - 200 52B in 20.874173ms
stash_1  | INFO[2021-09-18 08:03:30] Starting DLNA
stash_1  | 2021/09/18 08:03:31 "POST http://192.168.88.24:9999/graphql HTTP/1.1" from 192.168.88.54:51259 - 200 124B in 46.424517ms
```

Here are records from logs in stash's web interface
```
21-09-18 08:15:52
Debug   
ContentDirectory::Handle Browse - <u:Browse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1"><ObjectID>0</ObjectID><BrowseFlag>BrowseMetadata</BrowseFlag><Filter>*</Filter><StartingIndex>0</StartingIndex><RequestedCount>0</RequestedCount><SortCriteria></SortCriteria></u:Browse>
2021-09-18 08:15:52
Debug   
< map[NumberReturned:1 Result:<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/"><container id="0" parentID="-1" restricted="1" searchable="0" childCount="1"><upnp:class>object.container.storageFolder</upnp:class><dc:title>stash</dc:title></container></DIDL-Lite> TotalMatches:1 UpdateID:1]
2021-09-18 08:15:51
Debug   
ContentDirectory::Handle Browse - <u:Browse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1"><ObjectID>0</ObjectID><BrowseFlag>BrowseMetadata</BrowseFlag><Filter>*</Filter><StartingIndex>0</StartingIndex><RequestedCount>0</RequestedCount><SortCriteria></SortCriteria></u:Browse>
2021-09-18 08:15:51
Debug   
< map[NumberReturned:1 Result:<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/"><container id="0" parentID="-1" restricted="1" searchable="0" childCount="1"><upnp:class>object.container.storageFolder</upnp:class><dc:title>stash</dc:title></container></DIDL-Lite> TotalMatches:1 UpdateID:1]
```

**Comment by ctyjiuh** [comment]
can we open this issue back?

**Comment by WithoutPants** [comment]
Please open a new issue with the details.
