### ISSUE TITLE
[Feature] bigger clickable area for marking items

### ISSUE THREAD

**Issue by CuddleBear92** [stashapp/stash#1473]
Marking multiple items for edits/deletion should have a bigger clickable area.
Currently you need to click the small checkbox in the corner.

But this should work more like Plex, if one is selected then you should be able to click anywhere on the item, the title, the image, anywhere on the entire item.

This makes it much faster and easier to mark multiple quickly.

An de-select button might be needed as it would remove the ability to click the item to tner it.

**Comment by WithoutPants** [comment]
This already works like Plex. Once you have at least one item selected via checkbox, more can be selected/deselected by clicking on the thumbnail. You should also be able to click and drag to select others, but my testing indicates that there's a regression in that functionality.

**Comment by CuddleBear92** [comment]
ahhh, this does not work in Galleries... also i didnt have images tied too it as i cleared out and removed a huge image directory. 
It didnt work that way for those and i had 500 galleries i wanted to delete, it required the checkbox click sadly. 

Clicking the image works, but i think clicking the item as a whole, image+title+description. Everything in that item section should be clickable for this reason.

This issue is present across every type of selectable item i believe.
