### ISSUE TITLE
Freeones returning artist with matching alias instead of artist with matching name

### ISSUE THREAD

**Issue by ExceptionalError** [stashapp/stash#148]
Search "Jaclyn Taylor", scraper returns "Ally Breelsen".

**Comment by bnkai** [comment]
Although not ideal it is still technically correct.We should give a prority though to names or exhaust names before searching for aliases.
The scraper code will need to be rewritten anyway when freeones transitions to it new site/api (freeones.cc) so i don't know if it worth it for now.

**Comment by Leopere** [comment]
Marked as Wontfix for now due to @bnkai mentioning a need for a rewrite of the scaper once freeones migrates to it's new API
