### ISSUE TITLE
[Bug Report] Performer Studio Includes Filter is broken

### ISSUE THREAD

**Issue by MrX292** [stashapp/stash#1482]
**Describe the bug**
In Studio Performers i get `Response not successful: Received status code 422`
Also happens if i use the studio filter in Performers
**To Reproduce**
happens every time

**Screenshots**
![Screenshot 2021-06-05 at 10-46-31 Stash](https://user-images.githubusercontent.com/42774880/120886338-bdf80080-c5ed-11eb-8aa7-2f815bd16562.png)
![Screenshot 2021-06-05 at 10-38-45 Stash](https://user-images.githubusercontent.com/42774880/120886341-c18b8780-c5ed-11eb-97fb-059faa25b21f.png)

**Stash Version: (from Settings -> About):**
v0.7.0-47-g732cc571

**Additional context**
I think https://github.com/stashapp/stash/pull/1397 broke it

**Comment by Still34** [comment]
Can confirm, latest dev build.

**Comment by YouRockk** [comment]
+1 confirm

**Comment by gitgiggety** [comment]
This is an issue of #1405 and #1397 being developed in parallel and they conflict with each other (studios filter for performers not supporting the new depth field). I might be able to look into this after the weekend, but not any sooner as I can't use my (development) PC.
