### ISSUE TITLE
[Feature] Allow manually specifying StashDB ID.

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [stashapp/stash#1486]
**Is your feature request related to a problem? Please describe.**
I decided to move some of my local videos to a Stash instance I host, and I am using StashDB to tag some of them. One of my scenes is present on StashDB.org but for some reason Stash cannot find it. I have tried the tagger view in the scenes tab (using the title from StashDB and substrings of it) and the "scrape with" option from the edit tab, neither give any results.

**Describe the solution you'd like**
Preferably, it would be possible to manually enter the StashDB guid somewhere in the app, or allow it to be searched for in the tagger view.

**Describe alternatives you've considered**
Alternatively, the search/scrape features would be improved to work for the way I searched, but I don't have enough knowledge of how they work or are supposed to work to make any meaningful suggestions.

**Additional context**
Using the tagger view in the scenes tab did work for another scene from the same studio, so this shouldn't be related to StashDB credentials.

**Comment by CuddleBear92** [comment]
You can use the Stash-box ID in the scene tagger as a query.
For example this url: https://stashdb.org/scenes/70561514-ff93-4b02-a5fc-91a9722b962d
your query would be 70561514-ff93-4b02-a5fc-91a9722b962d and it would be a perfect match. 
Note that this is only in the scene tagger as far as i know ATM.

**Comment by HoLLy-HaCKeR** [comment]
Ah, my bad, I should have tried that. Thanks for the help!
