### ISSUE TITLE
[RFC] Stash on subpath with nginx reverse proxy

### ISSUE THREAD

**Issue by DerBunteBall** [stashapp/stash#1491]
Hi all,

I have a little problem with running Stash behind an Nginx revers proxy.

### Scope

Make Stash working on a subpath with nginx

##  Long Form

I'm trying to get an existing Stash to work on a subpath.

I have a Docker host with two Compose Files. One with nginx setup with HTTPS and the other with Stash. Both are connected to an Docker network configured as bridge.

I have created a location section in nginx like described in the wiki.

So I want something like this: https://x.x.x.x/stash should be the location to find my Stash.

Stash seems to be not able to handle this. So the /stash gets lost.

When I'm calling https://x.x.x.x/stash I'm getting to https://x.x.x.x/login?returnURL=%2F

This leads to a 404 because the / location gets called.

I also tried setting the external host to https://x.x.x.x/stash in the config but same result.

My location section looks like this:

```
location /stash/ {
     proxy_pass http://stash:9999/;
     proxy_set_header Host $host;
     proxy_set_header X-Real-IP $remote_addr;
     proxy_set_header X-Forwarded-For $remote_addr;
     proxy_set_header X-Forwarded-Port $server_port;
     proxy_set_header X-Forwarded-Proto $scheme;
}
```

I'm at the end of my knowledge actually. For me Stash seems to be unable to handle the subpath or something isn't passed to Stash correctly.

Every idea could help me.

Best Regards

**Comment by bnkai** [comment]
Stash doesn't work with a reverse proxy using subpaths. ATM you need to work with subdomains. There is already a feature request issue https://github.com/stashapp/stash/issues/740 for that. For a working nginx reverse proxy configuration ( using subdomains though ) you can refer to the relevant wiki section https://github.com/stashapp/stash/wiki/Reverse-proxy

**Comment by DerBunteBall** [comment]
I thought so.

Switched to a host. Would be helpful to have the ability to operate on a subpath. Not every local network has the ability of a fully DNS stack for internal name resolving. And not every router has the ability to configure it.

Best Regards
