### ISSUE TITLE
[Feature] Image/Gallery Wall View - Scaling & Zoom Options

### ISSUE THREAD

**Issue by ALonelyJuicebox** [stashapp/stash#1492]
The gallery wall view is fantastic, but for certain forms of image content (comics/manga in particular), it would be great to see the ability to set some scaling/zoom options. 

By default, wall view scales images to fit on screen. I'm requesting two new features here:
- Allow image to fit **horizontally** while ensuring the user has the ability to scroll down the page to see the remainder of the image as necessary should the image be taller vertically than the screen allows.
- Add an ability to set an image zoom level with a dropdown (100%, 110%, 120%, 130%, etc.)

No need to put this in settings area of Stash, ideally these options are ones that would persist _only_ while the lightbox is open.
In other words, if I were to continue to the next image by clicking next/arrow key, my settings would persist, but as soon as I exit the view, those settings would return to the default. (aka Zoom level = 100% / Scaling= Fit to screen).

These options could be added under the gear icon. 
As an additional note, currently the gear icon disappears if there's enough horizontal room-- ideally the gear icon would be made to be persistent regardless of horizontal space. 

![gallery wall viewer](https://user-images.githubusercontent.com/76471868/121510831-e6d91680-c99c-11eb-9430-e07e9e1dc2aa.png)

**EDIT 8/30/2021** - Just as a live demo of what this feature request is looking to accomplish, the settings found here with the LANraragi web application is what I'm looking to have emulated. (Link is completely safe for work)
https://lrr.tvc-16.science/reader?id=6646c24b0951483ff23709452e130ed2bc85defb&p=34

**Comment by ghfsa** [comment]
I think, ideally for zoom function, there should be single magnifier icon always visible.
**Scrolling up/down over this icon** should zoom in/out.

If that isn't possible, it should be like buttons present in most 'Image Viewers'
For eg. in IrfanView, theres zoom in, zoom out and percent dropdown in the toolbar.

**Comment by LinuxIsoGatherer** [comment]
Let me start off by saying, this app is really amazing! Great work author and collaborators for building this.

As pointed out by OP, the image viewer could do with some extra functionalities. Some additional ideas:
* like @ghfsa said, scrolling on an icon (or maybe just the image itself) could change the zoomlevel
* `numpad-0` to set zoom to "fit screen", `numpad-1` to set zoom to "original size", `numpad-2` to zoom in to 150% of original size, ... etc
* `numpad-Plus` to increase zoom with 10%, `numpad-Minus` to decrease with 10%
* `L` to rotate image left, `R` to rotate image right

This idea stems from using "FastStone Image Viewer". Keybinds could be customizable, and as OP suggested having the zoomlevel displayed in (and adjustable from) the navbar would be convenient.


I could give this a shot when I find some time. Go is not my main language but it's something I want to learn; also most of this change will be probably be frontend, so js/css/html which isn't _that_ hard.

**Comment by WithoutPants** [comment]
Additional $65 bounty placed. Total bounty: $85

**Comment by WithoutPants** [comment]
Additional $15 bounty placed. Total bounty: $100
