### ISSUE TITLE
[Bug Report] Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by Kallisti-I** [stashapp/stash#1499]
Clicking on "Scenes"  brings up a "Something went wrong" error. Details read:

> TypeError: Cannot read property 'map' of undefined
> at Nm (http://192.168.0.102:9999/static/js/main.f4ac8415.chunk.js:1:355287) at t (http://192.168.0.102:9999/static/js/4.e28b30fb.chunk.js:2:214002) at t (http://192.168.0.102:9999/static/js/4.e28b30fb.chunk.js:2:216050) at Xh at t (http://192.168.0.102:9999/static/js/4.e28b30fb.chunk.js:2:214002) at t (http://192.168.0.102:9999/static/js/4.e28b30fb.chunk.js:2:216050) at div at bl (http://192.168.0.102:9999/static/js/main.f4ac8415.chunk.js:1:124537) at O (http://192.168.0.102:9999/static/js/main.f4ac8415.chunk.js:1:56774) at t (http://192.168.0.102:9999/static/js/4.e28b30fb.chunk.js:2:1245488) at n (http://192.168.0.102:9999/static/js/main.f4ac8415.chunk.js:1:126754) at Jp (http://192.168.0.102:9999/static/js/main.f4ac8415.chunk.js:1:716205) at s (http://192.168.0.102:9999/static/js/4.e28b30fb.chunk.js:2:282408) at t (http://192.168.0.102:9999/static/js/4.e28b30fb.chunk.js:2:210605) at t (http://192.168.0.102:9999/static/js/4.e28b30fb.chunk.js:2:36189)

This happened most likely either after I scanned for new files or after generating content (didn't access the Scenes between). Also possible is the activation of Custom CSS (Night).

Since then it has stayed that way even after restarting stash and deactivating (and deleting the Custom CSS).

**Expected behavior**
Scenes should show in grid view. It works under the "Studios" view but only for scenes of the respective studio (as expected)

**Stash Version: v0.7.0-55-g3ae187e6**
(bug appeared probably two or three versions earlier)

**Desktop:**
 - OS: Windows 10
 - Browser: Opera, Firefox

**Additional context**
Views of Images, Movies, Galleries, Performers, Studios and Tags work as expected.

**Comment by peolic** [comment]
manually navigate to `http://192.168.0.102:9999/scenes?sortby=created_at&sortdir=desc` in order to clear the cached studio filters

**Comment by Kallisti-I** [comment]
Looking at the links lead to "500 Internal Server Error". Looks like this in the log file:

> 2021/06/14 23:47:10 "GET http://192.168.0.102:9999/static/js/4.e28b30fb.chunk.js:2:214002 HTTP/1.1" from 192.168.0.102:64632 - 500 50B in 0s

**Comment by Kallisti-I** [comment]
Thanks, that resolved the issue. Was it stuck at a filter view that did somehow not work anymore?

Also, would adding a "reset filters" option to the settings be feasible to enable users to fix an issue like that in the future themselves? Should I close the issue and submit that as a feature request?

**Comment by peolic** [comment]
> Was it stuck at a filter view that did somehow not work anymore?

it was discussed on discord on the #bugs channel last week, it's probably due to recent changes in the filters, specifically studio filters, that caused this error. ideally I think it shouldn't break the page completely...

> Should I close the issue

perhaps not, since someone (or myself) might look into making it not crash the page completely.

> Also, would adding a "reset filters" option to the settings be feasible to enable users to fix an issue like that in the future themselves?
> [...] and submit that as a feature request?

your call :)

**Comment by Kallisti-I** [comment]
I'll leave it open then and called it successful workaround found but not resolved. Thanks again.
