### ISSUE TITLE
Automated Docker Builds

### ISSUE THREAD

**Issue by egon6969** [stashapp/stash#150]
Hello,

the automated docker builds seem to build every commit instead of only building commits to master.
In my opinion it should only build commits to master for the "latest" tag.
Maybe introduce "development" tag for dev builds.

Builds see: https://hub.docker.com/r/stashapp/stash/builds

**Comment by Leopere** [comment]
I personally would prefer this behavior as well, however, all commits to the master branch should be functional aka a Squash & Rebase schema would be ideal to remove any commits that are not functional from the commit log at least by the time a dev branch is merged into a production branch.  

I for one prefer the GitLab flow where Master = Dev branch and there is a protected Production branch which can be the default view in the GitHub repository but that requires tweaking by @StashAppDev I believe in the repository settings.

**Comment by WithoutPants** [comment]
I definitely think that PR's shouldn't push new docker builds. There should be a setting in the docker hub for only building on the master branch.

**Comment by Leopere** [comment]
Pushing a Docker build from a PR isn't terrible so long as it gets cleaned up or is used somehow in testing.  If it's never used we should avoid wasting resources.

**Comment by endqwerty** [comment]
In addition tothis the docker builds are always 1 release behind. They build and pull from the latest release immediately when a merge occurs. However the new release binary isn't uploaded until a couple of minutes later. Do you want a separate bug for this?

**Comment by Leopere** [comment]
@endqwerty always one release behind is something that should not be happening at all the triggers are sent by GitHub to Docker Hub to pull the latest source code and build it isn't sent later.  I don't know whats going on there. This thing is set up correctly as far as I can tell.  The one thing you might be feeling is that some Docker builds can take hours to get around to happening since we don't pre-build the containers and then push the images up to the repository in post.  I would prefer to leave the build logs on DockerHub however what we could do instead is we could build them on TravisCI and then push them from there.

**Comment by endqwerty** [comment]
Looking at the timestamps and build hashes I see that the same build hash has a timestamp in dockerhub before the timestamp for the compiled executable. If it was completed before a new executable was ever available, I expect it could only have pulled the previous executable.

Also, dockerhub isn't pulling the source code.

From this line, I see that its pulling a release executable from the releases page.
```
RUN curl -L -o /stash $(curl -s https://api.github.com/repos/stashapp/stash/releases | grep -F 'stash-linux' | grep download | head -n 1 | cut -d'"' -f4) && \
    chmod +x /stash && \
    curl -o /ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz && \
    tar xf /ffmpeg.tar.xz && \
    rm ffmpeg.tar.xz && \
    mv /ffmpeg*/ /ffmpeg/
```

**Comment by Leopere** [comment]
AHHHHHH CRAP yes, it would be doing that as I wasn't planning on building the project within the container.  However, we could absolutely do that.

**Comment by endqwerty** [comment]
Could just have docker build as a triggered job (this project uses Travis I think?) after the binary build job is complete and do a docker push from there.

**Comment by Leopere** [comment]
Travis could be where we build the containers prior to pushing.

**Comment by WithoutPants** [comment]
This has been resolved. Travis now builds and pushes to docker hub as needed.
