### ISSUE TITLE
[Bug Report] Gallery images not showing in scene view

### ISSUE THREAD

**Issue by ciaron88** [stashapp/stash#1518]
**Describe the bug**
Gallery/Images not showing within a scene and the tab is listed as - "countables.gallery"

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a scene that has a gallery linked to it
2. Click on gallery

**Expected behaviour**
Images form gallery should show

**Screenshots**
![Screenshot 2021-06-19 105342](https://user-images.githubusercontent.com/31342057/122638604-f965f500-d0ec-11eb-81d6-dee21b245461.png)

**Stash Version**
Version: v0.7.0-60-g86bd993b
Build hash: 86bd993b
Build time: 2021-06-17 08:02:15

**Desktop**
 - Sash DB OS: Synology (Docker)
 - Browser OS: Wndows 10
 - Browser Firefox  89.0.1

**Comment by Still34** [comment]
On it; will be fixed in an upcoming PR.
