### ISSUE TITLE
[Feature] Sticky Navigation Menu

### ISSUE THREAD

**Issue by paddirn** [stashapp/stash#1520]
**Is your feature request related to a problem? Please describe.**
In larger collections, if you want to navigate around, you have to scroll all the way back up to the top of the page, this sometimes takes up precious seconds that could be better spent organizing or enjoying your pr0n.

**Describe the solution you'd like**
Make the top menu a "sticky" navigation menu, that is, the menu stays visible at the top of the page, even as you scroll down. Clicking on the menu items would obviously behave as expected, though re-clicking on the current page would pull you all the way back up to the top to get to the various sort/filter methods

**Describe alternatives you've considered**
Alternative might be to hide it when scrolling down, but then just make the menu pop back up again as soon as you start scrolling back up. Or, as an alternate to just making the top menu bar sticky, make the sort/filter options sticky as well right below the navigation menu.

**Additional context**
Older article, but it goes into the design of websites with regards to sticky menus and how those are just plain better to navigate and preferred by users:  https://www.smashingmagazine.com/2012/09/sticky-menus-are-quicker-to-navigate/

**Comment by Jimbo4041** [comment]
That's what the Custom CSS function unter Settings -> Interface is for. 

Takes two lines of code and less the 50 characters to achieve this.

.top-nav { position: fixed}
.main {margin-top: 25px}

**Comment by Gykes** [comment]
This appears to be a fully functional addition to stash already and this can probably be closed.

**Comment by DogmaDragon** [comment]
Can't find the PR that implemented this, but this is now implemented. 

> Or, as an alternate to just making the top menu bar sticky, make the sort/filter options sticky as well right below the navigation menu.

Needs to be a separate issue.
