### ISSUE TITLE
[Feature] Add 'date' field to images and display performer age

### ISSUE THREAD

**Issue by SakeNigiri** [stashapp/stash#1527]
**Is your feature request related to a problem? Please describe.**
Similar to how Galleries are treated, it would be nice for images under the Images tab to allow you to set a Date in the metadata and display the attached performer's age(s) accordingly.

**Describe the solution you'd like**
I would like to be able to click Images, select an Image with a Performer attached (with a valid birth date), click Edit, and have a Date field I can set.  After saving and returning to the Details tab on the image, the text under the Performer should change from 'XX years old.' to ''XX years old in this image.'  See also a Gallery (with the Date field set) that has a Performer attached (with a valid birth date).

**Comment by DogmaDragon** [comment]
Added in v0.19.0 with https://github.com/stashapp/stash/pull/3015.
