### ISSUE TITLE
Auto Tagger from tasks not tagging all scenes when compared to launching from a single tag

### ISSUE THREAD

**Issue by Wannabestraight** [stashapp/stash#1537]
**Describe the bug**
Different scenes are tagged when launching auto tagger from a single tag vs on all tags trough tasks page

**To Reproduce**
1. launch auto tagger from tasks
2. go to a single tag with multiple Aliases
3. Launch Auto Tag from that tag
4. Check log to see multiple new files tagged despite just running auto tag on all scenes

**Expected behavior**
When launching auto tag from tasks it should tag all scenes correctly and not leave out stuff.
Right now it looks like when using auto tag on all scenes it leaves some Aliases out of the tagging procedure.

**Stash Version: (from Settings -> About):**
v0.7.0-76-g4c838daa

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**

**Comment by gitgiggety** [comment]
I think this is fixed in the development version, as per #1713
