### ISSUE TITLE
[Feature] Mute Video Previews

### ISSUE THREAD

**Issue by TaylorSwiftFan13** [stashapp/stash#1541]
**Is your feature request related to a problem? Please describe.**
I'm not a huge fan of the video previews having audio. I was browsing on my phone when it suddenly started making *sounds*. It wasn't in a horrible location, but I would've prefered not to have that happen again.

**Describe the solution you'd like**
A checkbox to disable/enable Video Preview audio

**Describe alternatives you've considered**
In the meantime I've removed the audio from the video previews myself using ffmpeg, running this in the screenshots folder (which contains the MP4 video previews):

`for f in *mp4; do ffmpeg -i "$f" -c copy -an temp.mp4 && mv temp.mp4 "$f"; done`

But I have to go in and run this whenever I add new videos.

**Comment by ALonelyJuicebox** [comment]
Easy to fix. Under Settings>Interface and under scene / marker wall, uncheck "Enable sound"
![image](https://user-images.githubusercontent.com/76471868/124169280-e9d69c80-da5a-11eb-9ff4-e55dff6b543f.png)

Further, I think there's a PR for 0.8 that will allow users to not generate audio in previews at all but the above will address your issue.

**Comment by TaylorSwiftFan13** [comment]
Aha, it might be another issue then, because that checkbox does work in Chrome on my PC, but on Safari on my iOS devices it does not. I have it unchecked on my iPad (and iPhone), yet the audio starts playing on them.

**Comment by gitgiggety** [comment]
With 0.8.0 being released as stable you should now be able to (re)generate the previews without audio.
