### ISSUE TITLE
[Feature] Add the ability to copy tags to and from different scenes

### ISSUE THREAD

**Issue by ALonelyJuicebox** [stashapp/stash#1542]
**Challenge:**
When manually tagging scenes, the ability to copy the work you just did on a very similar scene and paste it into a new scene (or several new scenes!) would significantly reduce the amount of time needed for tagging. 

While multiple videos _can_ be tagged at once from the grid view, it is impossible to also review the content of those videos at the same time. Plus...sometimes you just want to copy tags. 

**Proposed Solution:**
As @jeremymeyers mentioned in his comment, the ideal means of approaching this would be to have a button that toggles the tag list between its current React JS autofill UX and a simple form where the tags that are associated with the scene become a comma separated list that can be freely copied and pasted to another scene.

Ideally this feature behaves in such a way where it doesn't break[ this feature request for disallowing new tags to be created on the edit page](https://github.com/stashapp/stash/issues/1265). I can envision a design where Stash warns the user that a tag that does not exist in the Tags db was attempted to be added. This would avoid scenarios where a typo accidentally generates erroneous tags.

Something a bit like this, which would need to include a link or a button to swap between the modes.
![taggg](https://user-images.githubusercontent.com/76471868/135591623-0960eda2-5bc8-418a-b2e2-9aed634a3d3e.JPG)
![tagg2](https://user-images.githubusercontent.com/76471868/135591625-32f456f9-b6cd-4a8e-b12f-fe94e749568c.JPG)

Would need to think about how tags with spaces are handled as well.

Issue modified (10/1/2021)
~~My idea is to introduce a **Tag Clipboard**.  The design I'm proposing plays off of the Filter UX from the scene wall. This would allow tags in the clipboard to be reviewed before copying them into a given scene.~~

~~Below you can see a link to the "Tag Options" which then leads to...~~

~~...the tag clipboard UI itself.~~
~~This would probably require a new table in the db (tagclipboard) to store the tagIDs~~

**Comment by jeremymeyers** [comment]
My preference would be this:
When in the edit tab, clicking on the "tags" box would convert the list of tags to a comma-separated list that could be copied and pasted as usual. Saving changes would return to the usual display.   (either that or make it so selecting tags in the list and copying will copy them as CSV.

**Comment by ALonelyJuicebox** [comment]
I thought about this design as well. 
I'm not opposed, but I do like that the design I proposed reduces the potential for mistagging/the creation of a new tag due to an ill placed whitespace character. It also allows us to keep the auto-fill functionality present in that form which again, also reduces the potential for mistagging

**Comment by jeremymeyers** [comment]
sure, just always gonna prefer system-level fixes rather than custom coded solutions requiring multiple steps

**Comment by ALonelyJuicebox** [comment]
...Honestly after further consideration, I agree with your perspective. That is a better approach.
