### ISSUE TITLE
[Feature Request] consider SSL cert and key in config path/current path

### ISSUE THREAD

**Issue by anothervolcano** [stashapp/stash#1552]
**Describe the bug**
stash.key and stash.cert are recognized when placed in the current path (same as conf, ffmpeg, database file, stash exec present)

**To Reproduce**
place stash.cert and stash.key in current exec path

**Expected behavior**
stash looks to stash.cert and stash.key like config, ffmpeg and start in https

**Screenshots**
None

**Stash Version: (from Settings -> About):**
v0.8.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 89

**Smartphone (please complete the following information):**
NA

**Additional**
Like to keep stash portable instead of using User Directory (~/.stash)

**Comment by bnkai** [comment]
While not working as you would expect the instructions <https://github.com/stashapp/stash#ssl-https> do say to put the certs in the home folder as it is hardcoded to that.
So i would treat that more like a Feature Request issue than a bug.

**Comment by Anon247** [comment]
Another thing to add here: when the stash.cert and stash.key is found, there is no redirect from HTTP to HTTPS, which can cause confusion as to why the client isn't able to contact the server.
