### ISSUE TITLE
[RFC] Database version 24 - can I ever switch back to stable builds?

### ISSUE THREAD

**Issue by praul** [stashapp/stash#1553]
Hi there, a while ago I made some custom changes to the code and therefore built from source.
Now I'm stuck for a long time. I have been waiting for official releases to catch up, but now I'm wondering if this ever will happen

`panic: Database schema version 24 is incompatible with required schema version 18`

Am I stuck forever with my custom build, or is there a way back?

Thanks for your answer

**Comment by bnkai** [comment]
If you made `custom changes` you should keep merging them pulling from the current stable/dev.
Your `panic` message means you are trying to access a newer database file with an older stash build.
If you only used your custom build that shouldnt happen
Were your changes UI based or did it involve a DB schema migration?

**Comment by praul** [comment]
Yes, maybe I wasn't clear. I've been on custom build for a long time, therefore my database schema is version 24.
I have wanted to go back to offical stable/dev releases for a while now, but the database schema version never catches up.

So I'm stuck on version 24 until official builds catch up to this version number? Is there a way to migrate? Thanks

**Comment by InfiniteTF** [comment]
> So I'm stuck on version 24 until official builds catch up to this version number? Is there a way to migrate? Thanks

The latest stable build, v0.8.0, is on version 25. You should be able to switch to that without issue.

**Comment by bnkai** [comment]
If you made changes so that the db schema is changed then you should keep doing those changes.
Even if the version number is ok the database schema will be different so something may not work as intended.
Thats if i understood correctly since you are not mentioning the exact changes.

**Comment by praul** [comment]
Ahh, stupid me. It worked, thank you. I tried development-x86_64 (still had this tag in my docker-compose) but now I realize this is an unmaintained tag now.

Thanks for your responses
