### ISSUE TITLE
[Feature] Custom Value for Items to Show

### ISSUE THREAD

**Issue by coreyp93** [stashapp/stash#1556]
When viewing on various different devices and different orientations I like to change the quantity of scenes on the page to different amounts, but find the current range of values to small and limiting (20,40,60,120,250,500,1000). 
If a custom value could be entered from 1+ items in intervals of 1, i could therefore save with a filter for different devices and achieve the desired look for each device.
Primarily wanted because I can't stand having some lines with different quantities of content than others when I can help it.

Also, the slider that changes the zoom level of scenes could really do with being saved along with the filters, as this also really affects positioning of items and would truly enhance the saved filters giving a more complete preset. Or maybe just the option before saving to include the current zoom level, I definitely can see that help with customising presets to achieve different looks. 

I guess could apply globally to for all filters not just scenes.

**Comment by ALonelyJuicebox** [comment]
Easy fix-- you can probably close this issue actually.
Set whatever filters you want, including the number of thumbnails per page, then in the URL bar change the _perPage_ variable to whatever you want.

**Before**
localhost:6969/scenes?_perPage=60_&sortby=created_at&sortdir=desc

**After**
localhost:6969/scenes?_perPage=61_&sortby=created_at&sortdir=desc

Hit enter, observe that the right number of thumbnails are displayed. Then go ahead and save your filter.

**Comment by coreyp93** [comment]
Thanks for the suggestion, Yes I'm aware of that, however that's more of a workaround than a fix imo. 
I would prefer the ability to edit within ui because I happen to use safari within a native safari view which doesn't allow me to edit the url at all, on several devices I own this is the case, therefore less than handy when I want to create new filters and such which I like to do from time to time.
I use this mainly for privacy reasons with the nature of stash. 

Also, I know it wasn't entirely related but it doesn't address the second part of the request, about zoom level controls being saved along with filters as again within the native safari view it doesn't seem to hold the zoom in cache so on every refresh it reverts back to default zoom.

**Comment by WithoutPants** [comment]
$10 bounty placed by Corey.
