### ISSUE TITLE
[BUG] Can't Filter Duration Range of Scenes 

### ISSUE THREAD

**Issue by meanjoep92** [stashapp/stash#1557]
So it seems that I can't filter the duration of scenes within a certain time. I think that by doing the following...

![image](https://user-images.githubusercontent.com/83387673/124522046-c34c9480-ddbf-11eb-9870-fcf6ca243b59.png)

The query is sorting by OR rather than doing AND.

**Comment by gitgiggety** [comment]
When applying the same filter multiple times stuff does "break" indeed.

But for duration range filtering a ticket already exists, #1504 .

And as it happens to be I am working on "between" / "not between" support for numeric filters, including duration.
