### ISSUE TITLE
.github folder for this project.

### ISSUE THREAD

**Issue by Leopere** [stashapp/stash#156]
We need a few templates for Issue and PR submission which will be used by passerby's who are contributing via issues or code submissions.  

Self assigning this because I have opinions about how this should be done but don't want to do it myself so if someone wants to it's up for grabs.

**Comment by Leopere** [comment]
Reading to do if you want to grab this and do it yourself.
https://github.com/stevemao/github-issue-templates
https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates

**Comment by halorrr** [comment]
This appears to have been done and can be closed https://github.com/stashapp/stash/tree/develop/.github
