### ISSUE TITLE
[RFC] Stash-box integration process.

### ISSUE THREAD

**Issue by gkddev** [stashapp/stash#1563]
# Title
I need to integrate stash-box into stash to  automated tagging of scenes and performers based on fingerprints and filenames. How to do it properly? I have already created some performers profile in my stash database manually  , so would I need stash-box now? How will it help me ?

I have a request for the developers, why don't you add a tutorial on how to use stash , when i first installed stash few days back , I faced a lot of problems. Not everyone is a developer and not everyone is familiar with GitHub and read me files. So it is better to give tutorial videos for better understanding all the buttons , task , configuration files.

## Examples
Like other big platforms have their own YouTube or daily motion channel to help normal user understand their platform. Even GitHub uploads video on how to use GitHub. Why not you?

**Comment by PhilippKeil** [comment]
I guess videos would make sense when the UI will not be altered significantly anymore. That's just not the case right now. And stash-box will be properly integrated when its actually ready.

**Comment by gkddev** [comment]
okay , I think you are right but when you are following agile methodology then saturation point will be hard to find.
