### ISSUE TITLE
[Bug Report] Studio hierarchy not auto-tagging correctly

### ISSUE THREAD

**Issue by QxxxGit** [stashapp/stash#1564]
**Describe the bug**
Let's say I have a folder structure of:

- dir/studio x/
    - dir/studio x/studio y/
    - dir/studio x/studio z/

When I run the Auto Tag on the Tasks page, all my contents from the studio y and z directories are pushed into the parent studio, x.

**Expected behavior**
IMO, if a sub-studio name exists in the path, the scenes and images should be routed to it and not the parent studio.

**Stash Version: (from Settings -> About):** 0.8

**Comment by WithoutPants** [comment]
Closing this as it's largely resolved by #2057. The new behaviour is that for the original scenarios described, the scenes will be allocated to studio y and z, respectively - choosing the studio that matches that latest in the path.
