### ISSUE TITLE
[Bug] [RFC] Issue in generating preview for ".ts" files. Stash is facing issue.

### ISSUE THREAD

**Issue by gkddev** [stashapp/stash#1565]
**Describe the bug**
Preview Files for mp4 files after generating it from stash are much fluid , feels like a smaller length video is running on hovering over the file,  but for .ts files, previews on hovering mouse over it, feels more like image preview even when I have selected "video" preview in configuration file.

**To Reproduce**
1. Add "ts" files containing folder path into Configuration settings.
2. Add "ts" in "Video Extensions" in "Configuration" tab.
3. Check "Preview Type" in "Interface" tab is set to "Video".
4. Go to 'Task'
5. Click on 'Generate'
6. Hover over the scene under Scene tab.
7. See error , preview is a mixture of video and images.
8. You can even repeat same after increasing length of each segment for preview under configuration tab.

**Expected behavior**
You can see the expected behavior by hovering over a scene which is stored as mp4 locally. Preview should be fluid but in case of "TS" files , previews stuck and freezes for a every segment.

**Screenshots**
I can upload the previews I received after generating it from within stash for .ts files. Kindly check two videos which are preview received from stash. Don't worry , these are censored. 

**Stash Version: (from Settings -> About):**
v0.8.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version :Version 91.0.4472.124 (Latest)

**Additional context**
See , Ts files are available everywhere, official studios are moving towards 432p or 576 .ts files rather 480p mp4 files. So this is a big deal, when you are supposed to provide organizer for offline content and modern contents are ".TS" Files and you are not even adding "ts" to default video extensions. 

first video is of "ts version" preview

https://user-images.githubusercontent.com/39620074/125051474-9f8b9600-e0c0-11eb-95f1-b0d2142d2b1d.mp4

second video is of "mp4 version" preview 

https://user-images.githubusercontent.com/39620074/125051516-a6b2a400-e0c0-11eb-8bed-d7909a296f44.mp4

check the difference. How it freezes.

Note: These preview were generated from stash itself.

**Comment by gkddev** [comment]
@mrbrdo @reynn @endqwerty @Leopere Kindly pay your attention to this issue.

**Comment by WithoutPants** [comment]
Please don't tag people without reason.

**Comment by WithoutPants** [comment]
@gkddev Can you please provide a link to the original ts video (used for the examples you posted above) for investigation purposes?

**Comment by gkddev** [comment]
I downloaded the mp4 video from https://www.youtube.com/watch?v=MtRzy2TJAOQ&t=11s
 and converted it to .ts file using online converter https://anyconv.com/mp4-to-ts-converter/ and then generated preview for both ts and mp4 files for comparison. Stash did not recognized those as duplicates.

**Comment by gkddev** [comment]
Hey I just checked, even video playback is freezing for ts files.

**Comment by bnkai** [comment]
ts files, especially older ones were mostly optimized for live streaming. Most of them dont even have an index, thats why the preview and the seeking when doing a live transcode is having issues. A simple remux with ffmpeg isnt enough in those cases and probably a complete reencode of the file is needed.
 I would suggest users to reencode those files with something like handbrake to a compatible format/container eg h264/mp4 vp9/webm or even hevc if they use a browser that supports it.

**Comment by gkddev** [comment]
cannot you add a web video player which supports ts file? or a converter or transcoder which can output files with same size but in mp4 inbuilt?

**Comment by gkddev** [comment]
Please understand, why have u created stash? simple, to organize our video contents. And from where do we have downloaded the contents? there are many like dafts** or p**nve . Most premium websites supports "ts" files and even free websites like p**nve . So how can you ignore such vast majority of files? Just add a simple player which supports "ts" files. That's all.

As you suggested handbrake, I used it but it will take a lot of time to convert 1 TB of file.

**Comment by ALonelyJuicebox** [comment]
Mate...take it down a notch.
Stash is an open source project-- no one is entitled to provide you any features. "Just add a player that supports ts files" isn't the simple request you're implying it is. From previous threads it sounds like Stash might see an eventual migration to Video.js...which I don't believe has direct support for index-less .TS files either without a good amount of work.

Personally, it is exceedingly rare for me to see the .ts format in the wild. I'd argue the claim "most premium websites support .ts" is a considerable stretch. I agree with bnkai...you might want to just start automating the conversion of your .ts files into something more usable.

**Comment by gkddev** [comment]
okay man, I understand, No one wants to work for free. Anyways, I will close this issue but can help me choose a software to convert ts files to mp4 other than handbrake , because on adding folder to handbrake , it also starts converting mp4 files along with ts files to "mp4" files. 

I just want a tool which is faster to convert my files in 480p mp4 with lower size of each output files. Priority is "fastest".

if you can please answer and then I will close this issue. Thanks.

**Comment by kermieisinthehouse** [comment]
I can reproduce this with .ts files that are converted from that website, but not with .ts files generated through ffmpeg. Either way, this is an upstream bug in ffmpeg, and should be reported there.
