### ISSUE TITLE
[Feature] If the filename has been rename and the title is the default one (filename), stash should change the title.

### ISSUE THREAD

**Issue by gkddev** [stashapp/stash#1570]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when changing file name does not update stash database as well. Upon scanning once again, log says file name not found for those files with name changed then on second line duplicate file found, as hash is same for newer file also.

Currently ,after scanning and generating previews and stripes for certain files ,if users want to change file name of one or two  ,they can do from stash itself by clicking on "Edit". But what if user chooses windows command line or power shell to rename group of files at once

**Describe the solution you'd like**
Solution can be, on scanning files after changing file name or destination, if hash code matches for both older and newer file & old file is also missing then why not just change the file name during scan only. If user has preview and stripes already generated for the file, then no need to generate it again , as hash matches, same preview can work for newer file also. 

This will even help user if duplicate files are found and stash has already stored  the files with low resolution and ignored other duplicate with higher resolution. Then they can simply delete low resolution file and scan again in stash, resulting no need to generate preview and stripes again, if user is not happy with previous stripes or previews, then stash has already an option to delete generated files and regenerate again.

**Comment by HereIam80** [comment]
I don't really know what you are saying. There seems to be two points you combining into one.

The solution you describe is already in stash. If you rename/move a file and then scan again it will get picked up as a new file. But as long as the hash remained the same and the old file is gone, stash will update the path in the database.

That is different however to comparing two files with different resolutions as the hash will be different and both files will be added into stash. But there are at least two tools in stash (the new duplicate checker using phash and a plugin) whch can identify duplicates with different hashes.

Unless I am misunderstanding you, the features you want are already in stash?!

**Comment by gkddev** [comment]
yes you are right , I just changed the file name locally, stash picked it up. New name is showing in log but not in stash. Its not reflecting in the browser.

This screenshot is of when I had not changed the name , I have only scanned it on stash.
![before changing name locally](https://user-images.githubusercontent.com/39620074/125164435-d096c400-e1af-11eb-8983-e8b8fd9287aa.png)

This is the log , which recognizes the new file , as hash code is same .
![scanning after changing file name locally](https://user-images.githubusercontent.com/39620074/125164449-e310fd80-e1af-11eb-99cd-95752d097aac.png)
after changing name I tried to search the file with new name, search worked but new name is not reflecting here.
![after chnaging name I tried to search the file with new name](https://user-images.githubusercontent.com/39620074/125164452-e4422a80-e1af-11eb-82b7-1b163937969f.png)

Thisis what I was talking about. Stash is capable to find if file name has changed but is not reflecting in webpage of stash.

**Comment by Belleyy** [comment]
It's normal that Stash don't change this, it's the title of the scene. You can have a title that have nothing to do with the filename.

I guess your feature should be: 
If the filename has been rename and the title is the default one (filename), stash should change the title.

**Comment by gkddev** [comment]
yeah sorry, I should better update the title of the issue. My bad, sorry.

**Comment by gkddev** [comment]
But now you understood what is the problem, how can I be assured that developers will work on this?

**Comment by Belleyy** [comment]
> 
> 
> But now you understood what is the problem, how can I be assured that developers will work on this?

You made a issue, they will see. When they will work on it ? No idea, there are tons of a feature, issue.
If you really want a feature "fast", you can "Bounty Feature" by donating money to the project, it will put your feature on top (Ask a dev team before donating).
You can also contribute by making PR if you are a programmer.

**Comment by o-fl0w** [comment]
https://github.com/stashapp/CommunityScrapers/pull/1136

**Comment by WithoutPants** [comment]
This latest development version (0.17) no longer explicitly sets the title of scenes/images/galleries during scanning. If an object has no explicit title set, then it uses the basename of its primary file. This does not address instances where people have titles set on objects already. That will need to be data massaged manually.
