### ISSUE TITLE
[Feature] Ability to save view options in settings

### ISSUE THREAD

**Issue by grimlertk** [stashapp/stash#1575]
**Is your feature request related to a problem? Please describe.**
Whenever a user navigates to any tabs, such as scenes, they need to select how they want to order their scenes or galleries or performers, or how many items they need to see on one page. However, these settings are lost as soon as user navigates away from that tab.

**Describe the solution you'd like**
I think a better feature would be set pagination and Order settings for pages directly in settings. That way, user can set their preferences and the grids of scenes or galleries will always be listed as the user prefers.

**Describe alternatives you've considered**
No other alternative possible.

**Comment by Belleyy** [comment]
It's already a feature on 0.8. 
Left to the search bar you can save your filter. Set as default to keep your settings everytime you go to this page.
So choose what you want as default (Sort by create_at, 20 result per page, ...), click on button then save as default.
![image](https://user-images.githubusercontent.com/23707269/125416327-ad0fb4e0-4b6c-4d8c-83e6-a0aab1a95944.png)

**Comment by grimlertk** [comment]
Ok, got it thanks. I will close the issue now.
