### ISSUE TITLE
[Feature] Default sorting and view mode in galleries

### ISSUE THREAD

**Issue by Perdition-117** [stashapp/stash#1581]
**Is your feature request related to a problem? Please describe.**
Need to set gallery display settings whenever adding/opening a gallery.

**Describe the solution you'd like**
Setting a default sorting algorithm and view for all galleries.

**Additional context**
I understand something of this capacity was added in the latest version, but I'm not entirely sure what it encompasses. I think it does not include gallery views?

**Comment by feederbox826** [comment]
https://github.com/stashapp/stash/pull/4962 adds default views to galleries
