### ISSUE TITLE
[Feature] Add more performer fields to the batch edit performer window

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#1582]
**Is your feature request related to a problem? Please describe.**
There's no way to batch edit performer fields other than rating, favorite, and adding/deleting performer tags.

**Describe the solution you'd like**
Add more performer fields to the batch _Edit Performer_ modal window:
- Gender
- Country
- Ethnicity
- Hair color
- Eye color
- Height
- Weight
- etc

**Comment by hyde231** [comment]
this has a lot of overlap with https://github.com/stashapp/stash/issues/1408. The solution I suggested tries not to overload by allowing to choose "field name" from a drop down, and a text box for the values

**Comment by echo6ix** [comment]
> 
> 
> this has a lot of overlap with #1408. The solution I suggested tries not to overload by allowing to choose "field name" from a drop down, and a text box for the values

Thanks, sorry for the duplicate.
