### ISSUE TITLE
[Feature] Buttons to go to next Picture for Images and Galleries

### ISSUE THREAD

**Issue by racoon-one** [stashapp/stash#1591]
Request:
When using the Picture and Galleries Dashboard to get to the next picture i need to exit back to the Gallerie / Picture Set.
It would be nice to add buttons so you can get to the next picture. 

Concept Art:
https://i.imgur.com/XPDFojN.png

**Comment by racoon-one** [comment]
Is allready implemented in WALL mode

**Comment by meanjoep92** [comment]
Would love to be able to have this UI change too.

I'm trying to tag thousands of images, and can't do this with the current UI.

Being able to implement this in Grid mode would be amazing.
