### ISSUE TITLE
[Feature] To allow sorting based on contents which are not tagged as well as tagged to any studio.

### ISSUE THREAD

**Issue by gkddev** [stashapp/stash#1593]
**Is your feature request related to a problem? Please describe.**
As we all know, In the most cases performers names are in the file name itself. But studio name is not on filename nor in meta data, so most of time files gets tagged to performer but not to correct studio.  Currently , if we have to tag studio ,first step would be  to look for if its tagged or not and then tag it using thumbnail.

And most users have files locally organized based on performer and not on studio, so you can't also take studio name from path name of that file.

**Describe the solution you'd like**
 if you give sorting option in the homepage based on files which are not tagged to any studio will help us to tag faster one by one just by seeing preview or thumbnail. So you can eliminate some time wastage.

**Describe alternatives you've considered**
Add selecting multiple files by dragging mouse, so we don't have to click each file checkbox and then edit their properties. so allow us to select multiple files by dragging mouse. I will add this feature in a new issue.

**Comment by ALonelyJuicebox** [comment]
Doesn't the "Is Missing: Studio" filter address this problem?
![ergerge](https://user-images.githubusercontent.com/76471868/126450812-32fc0ccc-a717-4cfe-bc8c-46fd42c7bb8f.png)

**Comment by gkddev** [comment]
oh god , once again , we do have the features but no docmentation. Thanks.
