### ISSUE TITLE
[Feature] Select multiple files by dragging mouse

### ISSUE THREAD

**Issue by gkddev** [stashapp/stash#1594]
**Is your feature request related to a problem? Please describe.**
we don't want to click checkbox of each file to select multiples of them. As the checkbox is small, we find it difficult to click each one by one. Instead allow drag to select multiple files ,like we select in file explorer of windows, by pressing "ctrl" to not loose previously selected files.

**Comment by ALonelyJuicebox** [comment]
This feature exists-- check one of the videos you want to select, then click and hold inside that checkbox. Drag the cursor across the other videos you want to select-- all of those additional videos will also be selected.

**Comment by gkddev** [comment]
Thats' why I said in another issue to generate some videos or a good documentation. There are lots of features here and we don't even know. so we fillup github issue page for no reason.
