### ISSUE TITLE
Mixed content errors when ssl/https enabled

### ISSUE THREAD

**Issue by endqwerty** [stashapp/stash#160]
## Issue
The new websocket connections creates issues for Stash deployments hosted behind a SSL layer. I'm using a letencrypt cert on my host and reverse proxying to the Stash docker container. This means Stash doesn't recognize itself as needing to use secure connections.

For reference: `REACT_APP_HTTPS` is not set.

## What it shows
Chrome, for example, will load a grey page and require manually allowing insecure connections for the page. 

The following errors are seeing in the console log.

Warning `Mixed Content: The page at '<URL>' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://<my_stash_url>/graphql'. This endpoint should be available via WSS. Insecure access is deprecated.`

Warning `Connecting to a non-secure WebSocket server from a secure origin is deprecated.`

Error `WebSocket connection to 'ws://<my_stash_url>/graphql' failed: Error during WebSocket handshake: Unexpected response code: 422`

**Comment by Leopere** [comment]
I recently stopped having insecure sources warnings via Traefik is this still an issue for you @endqwerty

**Comment by endqwerty** [comment]
This all started with the last build

**Comment by Leopere** [comment]
Oh I thought this was a previous issue I guess I should've seen the issue number and thought for a second about that.

**Comment by Leopere** [comment]
Re-Open this if it's still not fixed in the next hour after Docker builds it.

**Comment by endqwerty** [comment]
Issue still exists in
```
Build hash:	707bd09
Build time:	2019-10-25 01:22:29
```
