### ISSUE TITLE
[Feature] Run command periodically per folder

### ISSUE THREAD

**Issue by ghost** [stashapp/stash#1602]
I'd like to run a youtube-dl command in some folders.

Stash would need to know what the folder structure is, and then I would select a folder and write a command for it, I would also select how often I want it to run.

**Comment by jeremymeyers** [comment]
why would you not fun this as a cron job or scheduled task? is there anything specific to your request that would mean it needed to be done by Stash

**Comment by Maista6969** [comment]
This can be closed

**Comment by DogmaDragon** [comment]
Outside of Stash scope. Can be accomplished via API or plugin.
