### ISSUE TITLE
[Bug Report] Performer URL scraping don't work correctly

### ISSUE THREAD

**Issue by Belleyy** [stashapp/stash#1614]
**Describe the bug**
Pressing the button next to the URL don't popup the window "Performer Scrape Results".

**To Reproduce**
1. Go to Performer
2. Set a URL to scrape (https://www.freeones.com/mia-malkova/bio)
3. Press the button.
4. Log show that the scraper work but the popup don't appear.

**Expected behavior**
Show the popup to select the information you want.

**Stash Version: (from Settings -> About):**

Version: | v0.8.0-17-g9d641c64
-- | --
Build hash: | 9d641c64
Build time: | 2021-08-04 03:42:55

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 90.0

**Additional context**
If you select any scraper in the `Scraper With...` dropdown after the URL button, it will show the popup.

**Comment by Alexisback** [comment]
same problem

https://github.com/stashapp/CommunityScrapers/issues/676

**Comment by Belleyy** [comment]
> 
> 
> same problem
> 
> [stashapp/CommunityScrapers#676](https://github.com/stashapp/CommunityScrapers/issues/676)

Not same problem, i don't have any issue with the `Scraper With...` button.
