### ISSUE TITLE
Set date from scene

### ISSUE THREAD

**Issue by egon6969** [stashapp/stash#162]
Hello,

I already posted my feedback on #103 , but was notified, that it was the wrong place.
The current implementation to set metadata, appears to try and extract the file date from ffprobe.
The tag "creation_time" used to extract the date doesn't exist in most of my files.
So I would like to suggest a fallback on the file creation date from the filesystem, as a backup.
This could be done with https://github.com/djherbis/times.

**Comment by WithoutPants** [comment]
File creation date would almost never reflect the media creation date.

**Comment by stg-annon** [comment]
If you truly wish to do this, it could be accomplished via plugin, I don't believe it will be implemented in the main app for the reasons stated above
