### ISSUE TITLE
Select Lists Do Not Function in Firefox

### ISSUE THREAD

**Issue by xcjs** [stashapp/stash#1621]
**Describe the bug**
Any and all select lists do not open when using Firefox as a browser - so far they only work in Blink based browsers such as Chrome.

**To Reproduce**
1. Find any select list with known values.
2. Click on the select list.
3. Nothing happens - no values are shown.

**Expected behavior**
I would expect the select list values to be shown.

Version: | v0.8.0
-- | --
Build hash: | 0c417ad4
Build time: | 2021-07-01 23:59:02

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox
 - Version 90.002

**Comment by gitgiggety** [comment]
Can you elaborate what you mean with "select lists"?

I just tested the following things and all seem to work fine in Firefox 90.0.2:
* Applying a tag filter
* Setting one or more tags on a scene
* Applying a Studio filter
* Setting a studio on a scene

**Comment by xcjs** [comment]
I ran into it in several places, but I have since seen several lists that do work - sorry about that.

Here's an example of a select list that I cannot get to function in Firefox - Parent Studios:

![image](https://user-images.githubusercontent.com/5085205/128744564-fbe6c380-7086-42f7-b2aa-82ff7377df59.png)

**Comment by xcjs** [comment]
I've just confirmed this is due to an extension that prevents click events from being overridden called "Enable Right Click and Copy". 

This issue can be closed.
