### ISSUE TITLE
[Feature] Studio aliases

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#1625]
**Is your feature request related to a problem? Please describe.**
Some studios have alternate names or spellings, and some studios have changed their name over the years. Since each studio entry can can only have one name, this limits their auto-tagging scope. The end-user either has to make a duplicate studio entry with the alternate/defunct name, or tag files of said studio manually.

**Describe the solution you'd like**
Create the capability for the end-user to add studio alias names that will be part of the auto-tagging process for studios.

An example use-case is the website studio PornWorld formerly called DDF Networks, and often denoted in filenames as DDF.

- Main studio: PornWorld
  - Alias: ddf
  - Alias: ddfnetwork

**Comment by gitgiggety** [comment]
As an FYI: I started working on this. It's mostly finished but still need to add it to importing and exporting and fixing all unit tests.
