### ISSUE TITLE
[Feature] Movie gridview cosmetic consistency

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#1638]
**Is your feature request related to a problem? Please describe.**
Cosmetically the movies page isn't consistent with the rest of Stash's gridview pages

**Describe the solution you'd like**
- Display the scene count as a button
- Display the date beneath the movie title

**Comment by gitgiggety** [comment]
Started working on this. Currently the "Scene number" is shown on the Movies tab of a scene. Question is how to display this after the changes. When adding "everything" (date, synopsis, popover button for scene count) I don't think it really fits in anymore.
At first I thought to show it on the scenes count button / popover, for example `2/5` for scene 2 out of 5. But the number / index is arbitrary, so you can have a movie with 5 scenes, but only have 2 available in stash, for example scene 3 and 4, so the button would then show `3/2` which is really odd.

**Comment by echo6ix** [comment]
> When adding "everything" (date, synopsis, popover button for scene count) I don't think it really fits in anymore.

Don't add everything?

I think the scene count number and date is enough at this point. Adding the number/index is confusing; it breaks the continuity from the rest of Stash of having scene popover icon only display a total scene count.

Is it /really/ that useful to show the synopsis in the movie cards view or is that overkill that begins to clutter the cards ui with too much information?  displaying the synopsis in the card (if my assumption is correct) breaks the simple visual symmetry of the movie poster grid view. 

Down the road it might be cool to add a performer popover and image count popover, and perhaps even an organized popover icon.
