### ISSUE TITLE
[Feature] Add stash-freebsd to built binaries.

### ISSUE THREAD

**Issue by cjemorton** [stashapp/stash#1640]
**Is your feature request related to a problem? Please describe.**

This is not so much of a problem, but more of a request to provide FreeBSD native binaries.

**Describe the solution you'd like**

Release freebsd binaries for 64 bit systems. [stash-freebsd]

**Describe alternatives you've considered**

I can run the stash-linux binaries with kldload linux64; it does work, it just requires extra steps and additional code loaded at boot.

**Additional context**

I can and have built from source myself; having a pre built binary on each release would be nice as it saves a lot of time.

USECASE: I run all my services in separate jails - having to kldload linux64 etc. on the host breaks the ability for me to quickly shift and migrate the jails between running servers; I try to keep the running host environments as close to a stock install as possible - and make all modifications inside jails, which backups are then performed on.

**Comment by kermieisinthehouse** [comment]
According to the survey, 5/1500+ people run Stash on FreeBSD.

**Comment by IntoTheBlackHole** [comment]
> According to the survey, 5/1500+ people run Stash on FreeBSD.

+1

**Comment by cjemorton** [comment]
- Thank you! 
I just pulled down the build for stash-freebsd

I seriously appreciate this, now I don't have to run it in Linux compatibility mode.

I previously had an alias in my ~/.cshrc
`alias lin       'kldload linux64'`
to run the stash-linux binary builds.

I probably could have and should have loaded it on boot like normal. Now with a correct binary I don't have to. Yes I could have built it myself from source each and every time a version changed. But this makes updates to new binary releases so much easier.

So thank you!
