### ISSUE TITLE
Creating and deleting performers and studios does not refresh the applicable view

### ISSUE THREAD

**Issue by WithoutPants** [stashapp/stash#166]
Create a new performer or studio, then return to the performer/studio page. The new item is not added to the list. It requires a page refresh to show the new item. Likewise, the item is still shown in the list after returning to the page after deleting.

Appears to be something to do with graphql's cache.

**Comment by WithoutPants** [comment]
There is likewise an issue with the select boxes after creating a new tag, studio or performer. 

Create one of these, then navigate to edit a scene to add the new tag/studio/performer. The new entry will not be present.

There are a number of ways to address this, with varying complexity:

- change all requests to `network-only`. This means that nothing is cached, and all requests will go to the server. The data is essentially guaranteed to be valid and current, but at the cost of increased queries to the server.
- change mutation calls to update the cache after mutation. Based on my reading, this is error-prone and complicated. You would need to iterate through the cache for _any_ query impacted, and adjust it. For some queries, this will be simple. But for others it could be quite complex. For example, a mutation to remove a tag from a scene would need to go through any queries that have been called that filter on that tag and remove the scene from it, plus adjust the count. In addition, it would also need to adjust possible scene_marker queries that filter by scene tag. This will be complex to implement and is likely to be error prone.
- For any call that mutates the data, call `ApolloClient.resetStore`. This wipes the client cache. This means that any subsequent queries will need to hit the server again, but it also means that any data that it gets is now valid and correct. The downside to this is that unrelated queries now need to be refetched. This seems like a decent expense to take in order to get current data.

Ideally, we would also invalid the cache when certain backend tasks are completed, such as scanning, cleaning or importing.

**Comment by StashAppDev** [comment]
Reopening due to https://github.com/stashapp/stash/issues/195#issuecomment-553115201

**Comment by thundergreen** [comment]
When Trying to create a new Actor i get this: 

```
Error: GraphQL error: Internal system error. Error <runtime error: invalid memory address or nil pointer dereference>
```

**Comment by WithoutPants** [comment]
Please raise a new issue with the details. The stack trace should be output to the console when this happens, so please include that in there as well.
