### ISSUE TITLE
[Feature] Option to remove autoplay from Random/Queue

### ISSUE THREAD

**Issue by Belleyy** [stashapp/stash#1667]
**Is your feature request related to a problem? Please describe.**
When you use "Play Random" or select a a scene from Queue tab, the video will autoplay.

**Describe the solution you'd like**
I would like a option in settings to turn this off. (like the `Settings > Interface > Scene Player > Auto-start video` checkmark)

**Describe alternatives you've considered**
For Queue, could have a button in the queue-controls div to enable/disable autoplay.

**Comment by WithoutPants** [comment]
This drives me up the wall as well. I'd probably add both the solution you wanted plus the alternative.
