### ISSUE TITLE
[Bug Report] Transcode file formats doesn't line up exactly

### ISSUE THREAD

**Issue by qqqzzzzzzqqq** [stashapp/stash#1683]
**Describe the bug**

Stash allows me to generate an MP4 transcode for unsupported file formats to avoid transcoding to webm on the fly (something my GPU-less server can't handle in real-time).

There is at least one file format (it always happens for files from "PureTaboo", for example) where if I ask stash to generate a transcode it refuses (presumably it believes the file format to be supported) but when I try to play the file, it always tries to generate a transcode to webm in realtime.

**To Reproduce**
1. Add a file in this format to the stash library
2. Go to the scene player for that file
3. Try to play it (it generates the transcode on the fly with "[stream] transcoding video file to video/webm" in the log)
4. Click "Generate", select "Transcodes" and "Overwrite"
5. Stash does not generate a transcode (with "Generating 0 sprites 0 previews 0 image previews 0 markers 0 transcodes 0 phashes" in the log)

**Expected behavior**
The transcode is generated and it is used when I try to play the video.

**Stash Version: (from Settings -> About):**  v0.8.0-49-g50cb6a9c

**Desktop (please complete the following information):**
 - OS: Linux (Arch, latest)
 - Browser: Chrome
 - Version: 93.0.4577.58

**Additional context**

Video info from ffprobe of one of the affected files:

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '<filename redacted>':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:40:50.48, start: 0.000000, bitrate: 3467 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 3399 kb/s, 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (HE-AACv2) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 62 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
```

**Comment by qqqzzzzzzqqq** [comment]
One additional bit of info: Generating the transcode manually using ffmpeg and placing it in the files/transcodes folder with the right filename does work around the issue.

**Comment by WithoutPants** [comment]
The backend tries to work out when a transcode is needed based on what the typical browser can support. If the browser does not support the direct stream, then it falls back to a live transcode. It's not going to be easy for me to determine if there's a problem with the backend detection code without a sample file. 

However, we should probably just add an option to force a transcode file to be generated, regardless of whether one is needed, so that users can explicitly generate a transcode for files like this.

**Comment by qqqzzzzzzqqq** [comment]
Yeah that's a tricky one because I can't readily share the file with you. Do you have a link to the function that does the detection? I couldn't find it when browsing the sources myself - maybe something will stand out to me?

And yeah - an option to force the transcode would be amazing! In general, actually, because I also have several clips my browser thinks it _can_ support but then plays really incorrectly with jittery playback (they play fine in VLC).

**Comment by WithoutPants** [comment]
This is the code in `task_transcode.go`:
https://github.com/stashapp/stash/blob/6ce57a9a43e876f7f6dddcfb38ad0078a7d1defa/pkg/manager/task_transcode.go#L25-L46

And then in `ffprobe.go`:
https://github.com/stashapp/stash/blob/6ce57a9a43e876f7f6dddcfb38ad0078a7d1defa/pkg/ffmpeg/ffprobe.go#L192-L197

That should get you started.

**Comment by qqqzzzzzzqqq** [comment]
Thanks!!

**Comment by bnkai** [comment]
As mentioned in the discord channel most files that have issues are from streaming sites like PH. identifying those files in the generate phase will be very difficult imo as the codec/container is usually fine and there is nothing suspicious from the meta that ffprobe can fetch. What I would do is probably tag the problematic file and then through a plugin go through all files with that tag and either generate a transcode or reencode them (using better/archive quality settings than the transcode task) and replace the original files

**Comment by qqqzzzzzzqqq** [comment]
Yeah - that lines up with my local experiments. The file shows up as mp4/h264 but won't play in a browser. If I visit the video's URL directly, it renders a player with the correct length counter but won't play. I wish the browser (Chrome) would drop messages in the console when it can't play a video but it doesn't give me any hints as to why it doesn't like the video.

**Comment by kermieisinthehouse** [comment]
@qqqzzzzzzqqq 
Can you post the results of `mediainfo affected_file.mp4`?

**Comment by qqqzzzzzzqqq** [comment]
@kermieisinthehouse Certainly!

```
Complete name                            : [redacted]
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 1 013 MiB
Duration                                 : 40 min 50 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 3 467 kb/s
Writing application                      : Lavf58.29.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 3 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 3 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 40 min 50 s
Bit rate mode                            : Variable
Bit rate                                 : 3 400 kb/s
Maximum bit rate                         : 6 000 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 23.976 (24000/1001) FPS
Minimum frame rate                       : 23.974 FPS
Maximum frame rate                       : 23.981 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.068
Stream size                              : 993 MiB (98%)
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC SBR PS
Format/Info                              : Advanced Audio Codec Low Complexity with Spectral Band Replication and Parametric Stereo
Commercial name                          : HE-AACv2
Format settings                          : Implicit
Codec ID                                 : mp4a-40-2
Duration                                 : 40 min 50 s
Bit rate mode                            : Constant
Bit rate                                 : 62.7 kb/s
Channel(s)                               : 2 channels
Channel layout                           : C
Sampling rate                            : 48.0 kHz
Frame rate                               : 23.438 FPS (2048 SPF)
Compression mode                         : Lossy
Stream size                              : 18.3 MiB (2%)
Language                                 : English
Default                                  : Yes
Alternate group                          : 1
```

**Comment by WithoutPants** [comment]
There is now (in the dev version) an option to force generation of a transcoded video file by selecting the problem scene in the Scenes page, clicking `Generate...` from the overflow menu and enabling `Force transcode generation`. Can you please test (either with the dev build, or when the next release comes out) with the problem file and see if it resolves your issue?

**Comment by qqqzzzzzzqqq** [comment]
@WithoutPants Sorry it's taken so long to get back to you on this. It's taken until today to find another movie that had this issue but there it was and I tested this and it works perfectly!

**Comment by Flashy78** [comment]
@qqqzzzzzzqqq you can probably close this bug report if it's working for you.
