### ISSUE TITLE
[Feature] Adds a scene filter by "File Size"

### ISSUE THREAD

**Issue by FelipeFernandesLeandro** [stashapp/stash#1706]
Would be nice to have that filter so we could find some scenes to compress.

**Comment by SuperEllipsis** [comment]
If what you are looking for is the largest file sizes, then there is already the option to *sort* the scenes by `File Size`. Alternatively you can *sort* the scenes by `Bit rate` (Mb/s).

![image](https://user-images.githubusercontent.com/82902785/132370093-42e3a6c9-fd0a-4d3d-b5c3-c7ef3308f621.png)

**Comment by FelipeFernandesLeandro** [comment]
> If what you are looking for is the largest file sizes, then there is already the option to _sort_ the scenes by `File Size`. Alternatively you can _sort_ the scenes by `Bit rate` (Mb/s).
> 
> ![image](https://user-images.githubusercontent.com/82902785/132370093-42e3a6c9-fd0a-4d3d-b5c3-c7ef3308f621.png)

Nice, tnx. Didn't know about it.
