### ISSUE TITLE
[Bug?] freeones scraper returns only first match when actual match contains multiple performers with same name

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#171]
If you scrape a performer name like [Lauren Tayler]( https://www.freeones.ca/search/?t=1&q=lauren+taylor&sq=), there are multiple performers with a 100% relevance score and the same name. The scraper is only grabbing the result with the higher rank, which will obviously yield an incorrect match on scenarios like this.

I propose the scraper shows all 100% relevant matches and to differentiate between them show the career start date next to the result. Eg:

```
Matches
---------
Lauren Taylor (2013)
Lauren Taylor (2016)
```

**Comment by bnkai** [comment]
The way the scraper currently works is like this.
It gets first the list  of names from here https://www.freeones.com/suggestions.php?t=1&q=lauren%taylor
That's where you get the list you select from
Once you select a name it queries that name https://www.freeones.com/search/?t=1&q=lauren%20taylor
and parses the first result that matches 

As you see for the first part where you get to choose the name is one and the same for both
The second part is not interactive and it gets the first result that has the name in the name or aka field.
The scraper is mostly wip afaik and so i would prefer just making a new one for freeones when they transition to the new api.
We could append a `&p=p`(proffesion porn star) or  `&filter=137` (porn star or adult model) to the search query for the second part as a quick fix to limit the results but i don't know if we 'll miss something if the attribute is not set in the profile.If anyone is willing to test with a fairly big number of performers i can make the change

**Comment by bnkai** [comment]
Closing as issue is resolved in latest stash version. (No dedup when searching using the scrapers)
