### ISSUE TITLE
[Bug Report] Navigating away from scenes resets sort filter

### ISSUE THREAD

**Issue by halogod35** [stashapp/stash#1727]
**Describe the bug**
Navigating away from the scenes page always resets sort filter back to date in ascending order.

**To Reproduce:**
1. Go to scenes.
2. Click on sort by: (default should be Date in ascending order)
3. Change it to something random like random.
4. Navigate away from the page then return the scenes page. The sort should now be set back to data in ascending order.

**Expected behavior:**
When you leave the page and come back, it should remember the sort that was selected. This works on Stashapp versions 0.6.0 - 0.7.0. (I haven't tested versions 0.1.0 - 0.5.0)

**Stash Version:**
0.8.0 - 0.9.0

**Desktop 1:**
 - OS: Windows 8.1 Pro
 - Browser: Google Chrome
 - Version: 92
 
 **Desktop 2:**
 - OS: MX Linux 19.4
 - Browser: Firefox
 - Version: 87

**Smartphone:**
 - Device: iPhone 7
 - OS: iOS 14
 - Browser: Safari
 - Version: 14

**Comment by WithoutPants** [comment]
This is intended behaviour introduced by the saved filter changes (#1474). Clicking on the top-level nav buttons navigate to the applicable page with the default filter set. To return to previous query results, you can use the back button.

**Comment by halogod35** [comment]
How do I go back to version 0.7.0 on docker?

**Comment by halogod35** [comment]
Would you at least be willing push a v0.7.0 tag for Docker? Since we now have a v0.9.0 tag.

**Comment by WithoutPants** [comment]
I will try to build and manually push a build this morning.

Keep in mind that this new functionality means you can set the default filter/sorting order as you want, and allows you to save filters. The only thing that has changed that is no longer possible is keeping the same filtering/results as the last search when clicking on the top-level nav buttons (which is worked-around by clicking back).

**Comment by halogod35** [comment]
I completely understand, I just liked the cached version better than the current model (as mentioned in #1255). I became very upset when it didn't work like that anymore. I thought it was intended and perfect.

**Comment by WithoutPants** [comment]
stashapp/stash:v0.7.0 is now available. Note that you will need to reuse a database backup (which should have been made as part of the schema migration), since the 0.9 schema is incompatible with 0.7.

**Comment by halogod35** [comment]
I completely understand, I actually had to set up the new release today (v.0.9.0) I was seeing if the cached version was restored on the new one before submitting it as a "bug" not realizing it was the redesign.

Thank you so much for taking your time for pushing a v0.7.0 tag!
