### ISSUE TITLE
[Feature] Gallery card: scene count and description

### ISSUE THREAD

**Issue by QxxxGit** [stashapp/stash#1755]
Gallery cards currently do not display attached scene count and a description.

Next to image count (X images) should be a scene count. Below that would fit a description. This would match scene cards nicely.

**Comment by gitgiggety** [comment]
They do show the scene count already? Using the icons just as on a scenes card. It's in the code [here](https://github.com/stashapp/stash/blob/b14d5c56504dfcea2f5a7b86706b0ecdafd0b68c/ui/v2.5/src/components/Galleries/GalleryCard.tsx#L25).

But I do agree that it should be aligned with scenes. So I will move the image count to the "buttons", and show the date & details between the title & "buttons" / "counts".

**Comment by QxxxGit** [comment]
Oof you're right. I assumed it wasn't showing scene count because of the inconsistency (image count as text).

Thanks for fixing this!
