### ISSUE TITLE
[Bug Report] Sort Dir is reset when dynamic filter

### ISSUE THREAD

**Issue by Belleyy** [stashapp/stash#1762]
**Describe the bug**
When you click on a Perf/Tag/Movie during Grid scene, the filter is correctly apply but sortdir is set ASC.

Default view:
`http://localhost:9999/scenes?perPage=20&sortby=created_at&sortdir=desc`
When you apply a tag:
`http://localhost:9999/scenes?c={"type":"tags","value":{"items":[{"id":"24","label":"Big%20Tits"}],"depth":0},"modifier":"INCLUDES_ALL"}&perPage=20&sortby=created_at`

The url forget the `sortdir`.

**To Reproduce**
1. Go to Scenes (maybe you need to set a Default Saved Filter with `sortdir=desc`)
2. Click on Tag/Performer within a card
3. See error, `sortdir` change to ASC

**Expected behavior**
Don't change the current direction.

**Stash Version: (from Settings -> About):**

<html><body>

Version: | v0.9.0-52-gb14d5c56
-- | --
Build hash: | b14d5c56
Build time: | 2021-09-24 02:02:53

</body>
</html>

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Firefox 92.0

**Additional thing**
When you applied the filter and press Back on your browser, the filter is still apply. I think the good behavior would be to remove the filter. Maybe it's worth a other issue ?

**Comment by gitgiggety** [comment]
> When you applied the filter and press Back on your browser, the filter is still apply. I think the good behavior would be to remove the filter. Maybe it's worth a other issue ?

Could you confirm this only happens when you didn't have a filter set? So you have the scenes listing without a filter, click a tag on a card, and then use the back button it won't remove the filter? But when you click a tag, and another one, and then using back it will show the previous filter correctly (but when using back again, where it should return to the unfiltered state, it doesn't work).

**Comment by Belleyy** [comment]
> Could you confirm this only happens when you didn't have a filter set? So you have the scenes listing without a filter, click a tag on a card, and then use the back button it won't remove the filter? But when you click a tag, and another one, and then using back it will show the previous filter correctly (but when using back again, where it should return to the unfiltered state, it doesn't work).

Yes i can confirm, when you do tag to tag it work, but no filter to tag don't do anything.
