### ISSUE TITLE
[Feature] Show stats / totals for list results

### ISSUE THREAD

**Issue by kermieisinthehouse** [stashapp/stash#1775]
List results pages should include details about results, such as duration and filesize (for scenes), and megapixels and filesize (for images). This would ideally be under the pagination, and the pagination should be visible both on top and below the list results. 

Examples (obviously the number rounding is incorrect)

![Screenshot_20210926-171511_1](https://user-images.githubusercontent.com/84814418/134829532-f44fdaf2-7e74-40ef-934f-03f9e4ab01d5.jpg)
![Screenshot_20210926-172050_1](https://user-images.githubusercontent.com/84814418/134829535-95ace9a8-6424-4b1f-b822-8de9fdd212bd.jpg)

The formula for megapixels is (height*width/1_000_000). Also, the Query() function needs some refactoring for performance, so that it returns a struct of stats that are specifically requested instead of running all of them.

I have a half-baked [branch](https://github.com/kermieisinthehouse/stash/tree/show-duration-and-filesize-in-results) if it's useful for some reference, but I can't finish it, it has some issues I'm happy to discuss if it matters.

**Comment by WithoutPants** [comment]
Bounty placed for $35

**Comment by ALonelyJuicebox** [comment]
Can I just ask that this data get its own ID (throw it in a <span> tag or something) so that we can customize how its viewed using CSS?

**Comment by Belleyy** [comment]
> 
> 
> Can I just ask that this data get its own ID [...] Not everyone may want this.

Can confirm, i would personally like having the filesize but not the duration.
