### ISSUE TITLE
[Feature] Allow hiding scene sidebar by hotkey

### ISSUE THREAD

**Issue by ctyjiuh** [stashapp/stash#1788]
When opening scene, it shows up sidebar which slightly disturbs
Also you can't navigate within scene with hotkeys (0-9 and left/right)

First suggestion is to add a couple new hotkeys:
- hide sidebar
- fullscreen

Second suggestion is to focus on player by default when opening scene page

**Comment by WithoutPants** [comment]
A fullscreen hotkey is already available: `f`

A hotkey for hiding the sidebar sounds pretty simple and reasonable.

I agree that the player should probably be focused when loaded.

**Comment by growwithlogan** [comment]
Would like to propose hiding the scrubber as well, some people may not want to fully watch in full screen that takes over the screen but rather more or less fill up most of their screen while still easily having access to menu UI
