### ISSUE TITLE
[Bug Report] Stash Panic when deleting Marker

### ISSUE THREAD

**Issue by Belleyy** [stashapp/stash#1794]
**Describe the bug**
When you delete a marker that is no generate, you get a panic in the program.

**To Reproduce**
1. Go to Scene - Marker
2. Create Marker
3. Delete Marker

**Expected behavior**
No panic, even if you get this error everytime the marker is still removed so don't know what this 'panic' do.

**Error LOG**
[err.txt](https://github.com/stashapp/stash/files/7273254/err.txt)

**Stash Version: (from Settings -> About):**
<html><body>

Version: | v0.9.0-78-ga5ca8fc6
-- | --
Build hash: | a5ca8fc6
Build time: | 2021-10-03 00:52:10

</body>
</html>

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox 92.0

**Comment by WithoutPants** [comment]
It's not a huge issue. It panics in the handler only and doesn't kill the system. Pretty simple fix though.
