### ISSUE TITLE
[Bug Report] Cannot clear search query after selecting a saved filter

### ISSUE THREAD

**Issue by 7dJx1qP** [stashapp/stash#1803]
**Describe the bug**
If you select a saved filter, enter a search query, and then delete the search query, the results do not get updated and are still filtered by the search query that was deleted.

**To Reproduce**
1. Go to Scenes
2. Save an "Is missing studio" filter
3. Select the saved filter
4. Enter a search query
5. Delete the seach query

**Expected behavior**
The results should only be filtered by the saved filter and there should be no search query filter applied. Manually applying filters rather than using saved filters and then deleting search queries behaves as expected.

**Stash Version: (from Settings -> About):**
Version: | v0.9.0
Build hash: | a73c99a6

**Additional context**
When you delete the search query you can see it briefly removed from the url but then it immediately comes back.

**Comment by kermieisinthehouse** [comment]
I've been hitting this one for a while, but I think there are a few other ways to trigger it. 

I usually just type a space in the search field, wait half a second, then backspace it.
