### ISSUE TITLE
[Feature] Show Sub Items in all pages

### ISSUE THREAD

**Issue by ciaron88** [stashapp/stash#1822]
Add a global option to show all sub-studios, sub-tags etc... on the Parent Studio/Tag etc... page by default. like you currently can when using the filter on Scenes, Images etc...

So for example 

- Studio A is the parent of Studio B
- Video A is tagged as part of Studio B

Currently, Video A will only show on Studio B's page. I want Video A to show on, Studio A's AND Studio B's page (like if you would use the filter with include sub-scene ticked). Maybe also with a line under the title saying "Part of sub-studio Studio B" on Studio A's page

Thanks

**Comment by Daitaiva** [comment]
I would really love this feature as well.
And maybe the same could be done for the performers?
So the parent studios displays the performers of the substudios as well.

**Comment by WithoutPants** [comment]
Is this addressed by #2832?
