### ISSUE TITLE
[Feature] Bulk edit tags

### ISSUE THREAD

**Issue by 7dJx1qP** [stashapp/stash#1836]
**Is your feature request related to a problem? Please describe.**
Editing tag hierarchies can only be done one at a time. I would like to be able to select multiple tags and set their parent and child tags all at once.

**Describe the solution you'd like**
Add a bulk edit to the Tags page, just like the bulk edit options on the other pages. The edit options should let you override/add/remove parent tags, override/add/remove child tags, and merge into another tag.

**Comment by bennyz327** [comment]
Are there any updates on this issue?

I'm in the process of organizing my ton of tags recently.
It pains me to switch tab pages repeatedly in order to set parent and child tabs
