### ISSUE TITLE
[Feature Request] Make gallery cover image filename detection more flexible

### ISSUE THREAD

**Issue by n0bodyyouknow** [stashapp/stash#1856]
**Is your feature request related to a problem? Please describe.**
Currently the gallery cover image detection is extremely sensitive, and only recognizes a filename that ends in exactly "cover.jpg".  It does not, for example, recognize a filename that ends in "Cover.jpg" or "cover.jpeg"

Depending on where you download image sets from, it's fairly common to find slightly different capitalization of the cover image, and sometimes a "jpeg" file extension instead of "jpg".

**Describe the solution you'd like**
It would be nice if the cover image filename detection was a bit more flexible, and supported:
  - File extensions "jpg" and "jpeg"
  - Ignore capitalization of the word "cover" and file extension at the end of the filename.  (e.g. "Cover.jpg" or "COVER.JPG" or "cover.JPEG" etc..)

**Additional comments**
Stash has no problem supporting images with various derivations of "JPG" and/or "JPEG" file extensions _in general_, it's only the cover detection logic that is very sensitive.

**Comment by n0bodyyouknow** [comment]
Actually, I think to make this more predictable, and consistent with the main Stash image support, it should support any of the image format file extensions from the configuration settings, as opposed to hard-coding it to only "jpg" or "jpeg".

**Comment by stg-annon** [comment]
I think a good solution here that should be simple here is a configurable regex expression to match a gallery cover that defaults to `cover\.*`

**Comment by n0bodyyouknow** [comment]
> I think a good solution here that should be simple here is a configurable regex expression to match a gallery cover that defaults to `cover\.*`

I had kept the scope of my initial report as small as possible, but if we want to make this truly flexible, it would support one or more regex expressions, similar to the current "Excluded Image/Gallery Patterns" setting.  There are different naming conventions used by different studios, it would be very nice to be able to support more than one.
