### ISSUE TITLE
[bug] z-index property conflict with bp3-navbar

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#186]
The new `.grid-item label.card-select` class shares the same z-index property value with the `.bp3-navbar` class. When the scene cards scroll beneath the navbar, the new scene tick boxes overlap the navbar content as a result.

![Annotation 2019-11-07 185840](https://user-images.githubusercontent.com/37937507/68437984-b01f9680-0190-11ea-8173-8df7e51b1c3a.png)

I think the simple fix would be to change the z-index value for the following class

```
.bp3-navbar {
     z-index: 99;
}
```

It worked for me in ChromeDevTools. Please confirm.

**Comment by Leopere** [comment]
@echo6ix one of the things you can do without learning anything about git is editing the file on the website.
When you click the pencil on the file you need to edit you will be offered an option to create your own fork and create a PRR.

**Comment by echo6ix** [comment]
Just looking through Blueprint's stylesheet and I see that my hack of modifying z-index to 99 would probably break the overlays at least.

I tried modifying the z-index property in `.grid-item label.card-select { z-index: 9; }` , and this seems to work in my browser.

@Leopere I'm going to give it a shot. My first PR!

**Comment by Leopere** [comment]
Ideally, reference this issue number in your PR with something like `fixes #186` and when your PR is merged it will auto close this issue.
