### ISSUE TITLE
[Bug Report] Fullscreen image slideshow does not work on Safari

### ISSUE THREAD

**Issue by shanty-chits** [stashapp/stash#1864]
**Describe the bug**
When using Safari on Mac, there is no option to go to fullscreen when viewing image slideshows. Option is available on Chrome and Firefox for Mac.

**Stash Version: (from Settings -> About): 10

**Comment by shanty-chits** [comment]
Is there any progress on this?

**Comment by JoeShymoe** [comment]
Also in safari scrolling to zoom in doesn't work while in google chrome it does.
