### ISSUE TITLE
[Bug Report] active plugin stops identify from working

### ISSUE THREAD

**Issue by ferengi82** [stashapp/stash#1933]
if the SQLITE Renamer for Stash (rename on update) plugin is active the new Identify-function stops working.
Not sure if its a Problem at the plugin or the Identify-function

**Comment by WithoutPants** [comment]
Going to need a little more info than "stops working". Can you provide a little more detail?

**Comment by ferengi82** [comment]
i know its not optimal, but ther is no error in the log, it stops, but ill try to explain when it happens as good as i can:

- if the plugin is deactivated, everything works as expected (start idetify -> checks all scenes)
- if the plugin is activated, it runs until identify hits its first match, the last entry in the log is
`[Plugin / Update_Hook] --Starting Hook 'Update' Plugin--`
after that the identify function stops. I let it run for a few minutes, but nothing changs. then i hit the red X to cancel the identify operation. now i get an
`error executing post hooks: operation cancelled`
in the log.

**Comment by ferengi82** [comment]
if it helps its Version v0.10.0-57-g07a1cdd9 running on linux

**Comment by Belleyy** [comment]
Did some testing:
**Plugins don't stop the Identify.**

The issue that @ferengi82 got is that plugin don't use Timeout for a request. My plugin wait for the request to end but Stash never send a response so it wait indefinitely.

The real issue is: Why the request that hook plugin send never got a response.

**Comment by Belleyy** [comment]
So i find the reason why `FindScene` stay blocked:
It's this part:
```
    movies {
      movie {
        id
      }
    }
```
If you remove this part from the `FindScene` query, it work correctly.

-------------
To test by yourself:
- Take a Python scraper that can be use in Identify. (`Adultime.py`)
- Add this at start, to make the scraper do nothing but wait so you have time to test the playground:
```py
time.sleep(60)
sys.exit()
```
- Then go to the playground (http://localhost:9999/playground)
- Use this query:
```
query FindScene($checksum: String) {
  findScene(id: "1", checksum: $checksum) {
    id
    title
    movies {
      movie {
        id
      }
    }
  }
}
```
- Try this query without Identify (It work), then try while doing Identify (It doesn't work), use the Python scraper to have time to test.

**Comment by SmallCoccinelle** [comment]
We are using a write txn in the Movies(...) path:

```
diff --git a/pkg/api/resolver_model_scene.go b/pkg/api/resolver_model_scene.go
index 5d909f6b..185ef2e0 100644
--- a/pkg/api/resolver_model_scene.go
+++ b/pkg/api/resolver_model_scene.go
@@ -140,7 +140,7 @@ func (r *sceneResolver) Studio(ctx context.Context, obj *models.Scene) (ret *mod
 }
 
 func (r *sceneResolver) Movies(ctx context.Context, obj *models.Scene) (ret []*models.SceneMovie, err error) {
-       if err := r.withTxn(ctx, func(repo models.Repository) error {
+       if err := r.withReadTxn(ctx, func(repo models.ReaderRepository) error {
                qb := repo.Scene()
                mqb := repo.Movie()
```

It is probably worth this as a test for a fix.

**Comment by WithoutPants** [comment]
This is occurring because the update hook is being called while a write transaction is still active. Any update hook that tries to perform a mutation is going to end up in a deadlock.

**Comment by ferengi82** [comment]
working great so far, thanks
