### ISSUE TITLE
[Bug Report] DLNA cannot start in a freebsd Linux-compatible jail

### ISSUE THREAD

**Issue by kermieisinthehouse** [stashapp/stash#1937]
**Describe the bug**
User reports that on truenas, using an iocage jail with Linux compatibility, the DLNA server cannot start because of the error:
`error getting interface for name epair0b: route ip+net: netlinkrib: address family not supported by protocol`. Note that this interface is a macvlan interface set up by iocage, and is independently addressable by the router and has its own mac address and ip, using ipv4.

**Stash Version: (from Settings -> About):**
v0.10.0

**Comment by cjemorton** [comment]
Having this same issue on FreeBSD using iocage and stash in a jail. Everything else works fine.

**Comment by WithoutPants** [comment]
I am affected by this as well. As far as I can tell, it's a go-level issue and not something I can address within the stash source code.

**Comment by WithoutPants** [comment]
I have verified that DLNA now works using the `stash-freebsd` dev build binary on freebsd.
