### ISSUE TITLE
[Feature] Being Able to Save a Default Sorting in Studio Tab

### ISSUE THREAD

**Issue by BViking78** [stashapp/stash#1938]
**Describe the solution you'd like**
As title.
At least it would be nice to read your saved defaults in the other tabs (galleries, etc.) and use those.

**Comment by kermieisinthehouse** [comment]
The studios page can already save a default sort, with the same function as the other tabs. You can't share saved filters among some tabs, since they have different filterable properties.

**Comment by BViking78** [comment]
Sorry my fault for having worded it poorly.
I didn't mean main studios page but when browsing scenes/galleries of a studio. there's no "set as default" button there.
