### ISSUE TITLE
[Feature] Add blurred background to portrait aspect ratio scene thumbnails

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#1945]
**Is your feature request related to a problem? Please describe.**
Scene and image cards that have thumbnails with portrait/vertical aspect ratio have blank space on the left and right of the thumbnail since they cannot fill the width of their card.

**Describe the solution you'd like**
Add a background image of the thumbnail zoomed in to fill the width of the scene card and blurred. This is pretty standard for a lot of vertical/portrait aspect ratio content that that is viewed landscape viewports (which the cards are)

See here for an example https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.ytimg.com%2Fvi%2FyCOrqUA0ws4%2Fmaxresdefault.jpg&f=1&nofb=1

Add an option in the settings to enable/disable this feature?

**Comment by DogmaDragon** [comment]
There is a custom Javascript that adds this functionality to those that want it <https://docs.stashapp.cc/add-ons/scripts/#blurrycardbackground>

**Comment by Gykes** [comment]
Was looking into this. 

https://github.com/stashapp/stash/pull/2671

Makes it seem like this was a net negative and the PR was closed. Should probably close this one as well as it is better suited for 3rd party plugins.
