### ISSUE TITLE
[Feature] Scan only new files (automatically)

### ISSUE THREAD

**Issue by inject3d** [stashapp/stash#1946]
**Problem:**
On low end machines, a scan takes a long time to complete. For every new file which should be added a new scan must be triggered. A user could use a selective scan but if you add multiple files you lose the overview.

**Solution:**
Scan only files which are not known to the database yet. Scan could be initiated, but file could should be bypassed.
As a second improvement it would be nice to detect folder changes automatically and scan files which were just copied to the folder.

**Additional context**
Creation of a new configuration menu as the normal scan menu to define how files should be added automatically. How should they be scanned, converted, checksum created and so.

**Comment by kermieisinthehouse** [comment]
Scanning on reaction to a filesystem change is currently in the early stages of design: a design document is available here: https://gist.github.com/SmallCoccinelle/a9d362887ab2ab3b9ea3e28ae09a51e3

As for skipping scanned items, we already do this. An item that has the same name and mod time is not processed any further.

**Comment by kermieisinthehouse** [comment]
Closing as duplicates of #191

**Comment by SmallCoccinelle** [comment]
FYI: I updated the document today. The earlier design was largely rejected because it's way too complex to implement and maintain. Now, we are focused more on small QoL changes, among those an improved scan rate.
