### ISSUE TITLE
[Feature] Automatic preview playlist from directory 

### ISSUE THREAD

**Issue by mayonnaise3141** [stashapp/stash#1950]
**Is your feature request related to a problem? Please describe.**
Sometimes I've got a huge folder of vids (eg a megapack of some new talent) and I just want to preview the whole thing while handling some mindless task.  If something turns out to be hot, I'll keep it after re-seeding.   

**Describe the solution you'd like**
Some way to  play the first 5 min of every vid in a directory, one after the other.
Or examples/documentation on how to script such behavior.

**Describe alternatives you've considered**
I thought about creating individual preview vids of every file, then queueing them up in vlc or something, but that seems a bit heavy-handed

**Comment by kermieisinthehouse** [comment]
This seems out of scope for Stash. You can probably use `mpv --shuffle` or something.
