### ISSUE TITLE
[Bug Report] Performer Tagger loses performer data on save

### ISSUE THREAD

**Issue by 7dJx1qP** [stashapp/stash#1972]
**Describe the bug**
When on the Performers page Tagger view, if you link a performer to a stash-box performer and save or refresh, then its performer url will get cleared.

**To Reproduce**
1. Go to 'Performers' page
2. Click on 'Tagger' view
3. Click 'Refresh' on a performer that has a performer url set and is tagged with a stashid
4. Click 'Save' on the update dialog
5. Go to the performer page and see they will not have a url anymore

The issue also happens if you use an untagged performer, click search, select a match, and save.

**Expected behavior**
Updating a performer in the Tagger view should not lose their url data.

**Stash Version: (from Settings -> About):**
 - Version: v0.10.0-79-gbcd6d4fb: Latest development build

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave

**Additional context**
For the tagger configuration excluded fields, I have everything excluded except for 'Eye Color' and 'Fake Tits'

**Comment by 7dJx1qP** [comment]
I'm also seeing death date, hair color, twitter, instagram, and details being lost when tagging.

**Comment by kermieisinthehouse** [comment]
Darn, if it's broken in this release, I'm gating it as a 0.11.0 issue.

**Comment by InfiniteTF** [comment]
I'll take a look, I think I broke it as part of a PR I did not long ago.
