### ISSUE TITLE
[Bug Report] Galleries: Overzooming on Edge Browser

### ISSUE THREAD

**Issue by praul** [stashapp/stash#1974]
**Describe the bug**
The new (scrollwheel) zoom function in gallery picture view works great on chrome. However, on edge browser the script somehow does not detect the scrollwheel movement right. A slight scroll, and the pic gets zoomed to far over 500%.

**To Reproduce**
1. Use Edge Browser
2. Click on pic in gallery
3. Scroll up to zoom

**Expected behavior**
Normal zoom behaviour like on chrome

**Stash Version: (from Settings -> About):**
v0.10.0

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser edge
 - Version  95.0.1020.44

**Comment by ALonelyJuicebox** [comment]
Hmm..I can't replicate (Windows 10, Edge 95.0.1020.44, Stash 0.10).
OP can you perhaps save a short video demonstrating what you're seeing?
