### ISSUE TITLE
[Bug Report] AirPlay/Casting option not present

### ISSUE THREAD

**Issue by HybrisF** [stashapp/stash#1978]
**Describe the bug**

Somehow any option for casting either by AirPlay or Chromecast seems to be missing from the JWPlayer panel. Even when castin through control center, no video is sent to the receiver. My stash instance is setup with a valid public SSL certificate (ZeroSSL).

I was digging throught the code and atleast the necessary property seems to be set during the setup of the player object: [https://github.com/stashapp/stash/blob/60c4f7e99216ff068d0207fe7a29d54c9cc63856/ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx#L311](https://github.com/stashapp/stash/blob/60c4f7e99216ff068d0207fe7a29d54c9cc63856/ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx#L311)

**To Reproduce**
1. Go to any scene video
2. Start playing
3. No option to cast possible

**Expected behavior**
Option to cast should be present on the right side of the video controls like in this screenshot:
![Bildschirmfoto vom 2021-11-09 10-36-17](https://user-images.githubusercontent.com/87122445/140899589-fa7cef5f-3f4c-4c2f-bc40-bb6716e048c0.png)

**Screenshots**
![Bildschirmfoto vom 2021-11-09 10-39-04](https://user-images.githubusercontent.com/87122445/140899942-a47dc486-e3a5-4e34-bbd7-74d2f168b6b9.png)
No option here

**Stash Version: 0.10.0 compiled for Windows

Desktop (please complete the following information):

OS: Window Server 2019
Browser: Chrome and Safari
Version: latest

Smartphone (please complete the following information):
Device: iPhone 7 Plus, iPad Air 3
OS: 14.3
Browser: Stock Safari

**Comment by HybrisF** [comment]
I might add, that my server is on a remote network. However I managed to stream the scene to an AirPlay receiver by removing the login credentials and enable the unsafe access property inside of the config.
The casting symbol won't be there either, by streaming is possible by the iOS casting option (insided of control center), but this option is not very feasible.

So it this certainly does have to do with authentication on remote networks, but of course it would be nice to have a casting option from within the player.

**Comment by LeGrosFromage** [comment]
This definitely would be a nice-to-have.  Using PornHub or xHamster, in Safari on a Mac, it's trivial to cast to an AppleTV.  Having the ability to cast a scene from within Stash in the same manner would be wonderful and would also remove my need to keep Synology DS Video on my NAS.  Right now I have to use that to watch my scenes on TV (via the DS Video app on the AppleTV).

Thank you!
