### ISSUE TITLE
[Feature] Add a "play all" button for performers or tags that play a mix of images, scenes and movies from them.

### ISSUE THREAD

**Issue by masterofobzene** [stashapp/stash#2019]
It would be good to have a "play all" feature in the performer profile or tags cloud so we can start playing a mix of both, videos and images.
Nowadays you have to go over one of the topics but they can't be mixed in a playlist.

![imagen](https://user-images.githubusercontent.com/94469116/142023971-3163eb29-7856-4cde-8451-9b8b9ff036ea.png)

**Describe the solution you'd like**
A solution to this would be to add a "play all content" button that appears in the performer profile page and tag cloud pages.

**Comment by ALonelyJuicebox** [comment]
How do you "play" an image? 🤔

**Comment by masterofobzene** [comment]
> 
> 
> How do you "play" an image? 🤔

In a playlist on a slideshow, smart guy.
Next time try to be a little less acid if you want to ask someting.

**Comment by ALonelyJuicebox** [comment]
> > How do you "play" an image? 🤔
> 
> In a playlist on a slideshow, smart guy. Next time try to be a little less acid if you want to ask someting.

Relax. It was a genuine question. I'm not sure why you're assuming malicious intent. 
How do you "play" an image? 

Are you thinking something that works in JWPlayer itself? (not even sure if this is feasible looking at supported formats, you may have to convert) The benefit here is that it would keep the general UX the same and potentially be less jarring from a UX perspective as the user proceeds through the mixed playlist.

Or are you thinking of something where the existing image lightbox feature is used? In this case you're probably also asking for...
- An ability to stitch together the scene queue concept with the lightbox playlist concept. 
- A UX that makes sense for when you exit the lightbox. Today, if you're on the performer page, you exit back to the performer page if you click out of an image. How does that look for mixed media when you might also be on the scene viewer page?
- Modifiable delay that persists for the playlist session for images
- Persistence when image settings are modified for the playlist session

**Comment by masterofobzene** [comment]
> 
> 
> > > How do you "play" an image? 🤔
> > 
> > 
> > In a playlist on a slideshow, smart guy. Next time try to be a little less acid if you want to ask someting.
> 
> Relax. It was a genuine question. I'm not sure why you're assuming malicious intent. How do you "play" an image?
> 
> Are you thinking something that works in JWPlayer itself? (not even sure if this is feasible looking at supported formats, you may have to convert) The benefit here is that it would keep the general UX the same and potentially be less jarring from a UX perspective as the user proceeds through the mixed playlist.
> 
> Or are you thinking of something where the existing image lightbox feature is used? In this case you're probably also asking for...
> 
>     * An ability to stitch together the scene queue concept with the lightbox playlist concept.
> 
>     * A UX that makes sense for when you exit the lightbox. Today, if you're on the performer page, you exit back to the performer page if you click out of an image. How does that look for mixed media when you might also be on the scene viewer page?
> 
>     * Modifiable delay that persists for the playlist session for images
> 
>     * Persistence when image settings are modified for the playlist session

I took it as malicious because of the quotes, as you were trying to remark that pictures cannot be "played".

I think its easy to play videos and show images all from the selected performer, maybe switching from the player to the slideshow interface for each file.
I leave the techie part to you if you know how to implement it.

Anyway, I leave the idea here, but I will use another software since stash is very limited for me. Other problem I stumbled is that it transcodes the videos and videos that are low res but OK look like shit and are presented in 240P.

**Comment by masterofobzene** [comment]
Ok, since I got no real attention with this post and no other porn management app out there can play videos and pictures in the same auto generated playlist which to me is CORE functionality, I think that I will go back to the primitive but working windows 10 file explorer and my potplayer set to random play and configured to "play" image formats too. I can watch my collection in two clicks that way (play folder).

Sadly I will have to format the PC again and go back to Win 10 since Win 11 (besides still being an alpha even after MS saying it was final) removed folder thumbnails making my porn collection a mess to navigate. 
Yes that is why I started looking for a porn collection manager but I don't know if devs are not thinking the features very well or it is technically impossible to do what I need.

Anyway,  goodbye and try to think this soft a little better, not only from the tagging system and management point of view but the actual usage (who needs a perfectly scrapped and tidy porn collection if watching it is a pain in the ass???)

**Comment by philpw99** [comment]
Relax man. Your request is co-incidentally the next feature I am trying to implement in my windows App Stash_Helper. So it will be done soon.
You got to understand that JWPlayer has its limits. This feature is hard to implement in the Stash browser, but it's much easier to do it in my App.
Anyway, it should be done this week. You can check my app out in the mean time.
https://github.com/philpw99/Stash_Helper/releases
Version 2.0 will have the awesome "Add All to the playlist" feature.

**Comment by masterofobzene** [comment]
> 
> 
> Relax man. Your request is co-incidentally the next feature I am trying to implement in my windows App Stash_Helper. So it will be done soon. You got to understand that JWPlayer has its limits. This feature is hard to implement in the Stash browser, but it's much easier to do it in my App. Anyway, it should be done this week. You can check my app out in the mean time. https://github.com/philpw99/Stash_Helper/releases Version 2.0 will have the awesome "Add All to the playlist" feature. Just to be clear, "Add All" means add all the scenes, images... in the current browser tab to the playlist. It doesn't mean it will add all the scenes/images from this performer or studio. You should filter the scenes/images yourself first.

Thanks bud. 
But anyway I've reverted to Win 10 so all my collection has the thumbnails again =). 
The best porn browser is the file browser explorer itself with a video player configured to play both video and image formats and if you make a coherent folder structure, you don't even need tags. 

Stash has a good idea badly implemented. I've browsed webpages serving images and videos all in the same queue so its possible to do; problem here is that maybe nobody cares about that. (maybe they use it just for "one-video-at-a-time" or just want tags for files)
Keep it up and maybe you could come up with a standalone porn browser-manager that is far better than all the managers out there including this one ;) .

**Comment by philpw99** [comment]
I disagree with your idea of folder management. I like Stash because it links Studios and performers to movies, scenes, images and galleries. A folder structure can never link like that. Plus since a "movie" actually doesn't exist as a file, I can organize them any way I want: I can put multiple scenes for a movie, or one actress's scenes to a single movie, or one Studio's all videos to a movie...etc. Basically the way of Stash is super flexible, and I don't even need to concern about where I store the file. Stash will label them properly for me.
I can never did what Stash guys here had done for all the great coding. My thing is just a humble assistant to their wonderful achievement.

**Comment by philpw99** [comment]
Stash_Helper 2.0 is out, which can add all your scenes/movies/galleries/images, or some of them to a play list with just one click or a combined key "Ctrl-Alt-A". I found it super useful for myself. Now I can filter the scenes anyway I want, then add them to a play list in one click. The previous way requires me to add scenes/movies one by one.
It took me a long time to get this feature done. I am happy to see it finally works.

**Comment by masterofobzene** [comment]
> I disagree with your idea of folder management. I like Stash because it links Studios and performers to movies, scenes, images and galleries. A folder structure can never link like that. Plus since a "movie" actually doesn't exist as a file, I can organize them any way I want: I can put multiple scenes for a movie, or one actress's scenes to a single movie, or one Studio's all videos to a movie...etc. Basically the way of Stash is super flexible, and I don't even need to concern about where I store the file. Stash will label them properly for me. I can never did what Stash guys here had done for all the great coding. My thing is just a humble assistant to their wonderful achievement.

Well I disagree with you since you can perfectly do all that if you want to. You can even use symbolic links to do that. I use windows but I know that linux can also do that too even before windows.
Stash is "super flexible" if you just want to hoard data and admire a clean tidy collection.
Stash fails strongly when you try to enjoy your files. You suddenly realize (as it happened to me after losing days of data tagging in stash) that you have to stay in front of the computer to watch the porn or use a smartphone/tablet to use it like pornhub (which again means going file by file); intrincate keyboard shortcuts for this and that....  

Nah bud... its not good for other thing than tagging and navigating, but ACTUAL use of the collection is not taken into account. 0 planning on that sector. This is a "collector fever" software. Not meant to be used to actually watch your porn in a simple way.

The file browser method only takes 2 clicks. Literally, 2 clicks first to open context menu over a folder, second to tell potplayer or whatever you configured to play all files inside.

Sorry but not even your 3rd party- stash friendly sofware can fill the hole stash left in the "lets watch porn" dept.

Not gonna be mean to you since you tried.
Think about it... you had to make a 3rd party soft to try to make this thing usable in a maningful way... that says something don't you think?-

**Comment by masterofobzene** [comment]
> Stash_Helper 2.0 is out, which can add all your scenes/movies/galleries/images, or some of them to a play list with just one click or a combined key "Ctrl-Alt-A". I found it super useful for myself. Now I can filter the scenes anyway I want, then add them to a play list in one click. The previous way requires me to add scenes/movies one by one. It took me a long time to get this feature done. I am happy to see it finally works.

Again... so you have to select your files first, then add them with that odd shortcut, then play them in that order, no shuffle, no randomness, you have no control and it takes you 3 fatalities to start watching porn. 

Think that you can switch in 2 clicks to any performer/kink with the file browser method.
Its not preety as Stash to watch, but it is surely easier. 

Lets be honest, if you are masturbating, you don't want to do 5 konami codes to switch to another kink, perfomer videos/pics. 

sorry but the truth is the truth.

**Comment by philpw99** [comment]
Well, I usually use only the "play current scene" button or "play current movie" button to watch the one that I like. Just 2 clicks.
The shortcut key "Ctrl-Alt-A" is not necessary if you choose to run the same thing from the menu.
However, the big help from Stash is that: I usually forgot where I put the file, what was the studio, what was the actress's full name... etc.
Like I remember only the first name of an actress I like, I want to watch her movies but in a tree-like explorer I will be lost. Now I can just type in her first name. Several actresses with the same name will come up, and I will choose her by her face. Then under her tab it will show all the movies and scenes she was in, even with different Studios. Now I can just choose the movie by the cover.
After I find a good movie for her, just two clicks, my PotPlayer starts playing that movie/scene, which I don't even know where I stored.
You see ? This is a much easier way for me. I am a Windows user too. I rarely do symbolic links and avoiding it if I can. Stash does alleviate lots of pain of finding the right movie/scene from thousands of entities. File browsing is too inefficient for me.

**Comment by masterofobzene** [comment]
> Well, I usually use only the "play current scene" button or "play current movie" button to watch the one that I like. Just 2 clicks. The shortcut key "Ctrl-Alt-A" is not necessary if you choose to run the same thing from the menu. However, the big help from Stash is that: I usually forgot where I put the file, what was the studio, what was the actress's full name... etc. Like I remember only the first name of an actress I like, I want to watch her movies but in a tree-like explorer I will be lost. Now I can just type in her first name. Several actresses with the same name will come up, and I will choose her by her face. Then under her tab it will show all the movies and scenes she was in, even with different Studios. Now I can just choose the movie by the cover. After I find a good movie for her, just two clicks, my PotPlayer starts playing that movie/scene, which I don't even know where I stored. You see ? This is a much easier way for me. I am a Windows user too. I rarely do symbolic links and avoiding it if I can. Stash does alleviate lots of pain of finding the right movie/scene from thousands of entities. File browsing is too inefficient for me.

Use the file browser search. The problem I see here is that your collection may be a real mess to start with. I took the precaution at the very beginning to store the vids on folders one for each actress, and some folder for mixes of different kinks. 
I really don't care about studios... again I want to watch porn, not to be a porn connoisseur so the only things I care are 2: 
1- Actresses.
2- Kinks.
Everything is inside their respective folders so no problem. Videos and photos.
I don't care about "scenes" and "movies". I don't even get the idea of why they are supposed to be different because both are videos to me. If you like a "movie" you could search it in windows search; you could even name the file you like so much as a [FAVORITE] ..Mary Lou Boobs .. .. .MP4
It´s not that complicated, but again... if your collection is a mess... you will have a hard time.
That doesn't mean that the browser method is worse than yours... you just have to work hard one time and the rest is enjoy.
I could for example fly from one kink to another getting exactly what I want and in the middle fly again to one actress that I recall being really hot and so on and on.

If its good for you, thats ok. But that doesn't mean that its better than a well mantained file browser collection. 
Have a look:

![imagen](https://user-images.githubusercontent.com/94469116/142963577-122e5e66-a861-49cb-b294-a06d19b4e337.png)

![imagen](https://user-images.githubusercontent.com/94469116/142963441-25068784-6aae-4425-83b1-68550a511f7f.png)

![imagen](https://user-images.githubusercontent.com/94469116/142963098-93453d82-3e83-40cc-b170-a78a1b527380.png)

![imagen](https://user-images.githubusercontent.com/94469116/142963510-79127819-b713-48e3-9fba-c203c514bfdf.png)

all in litterally 2 clicks.
BTW; potplayer is set to randomize so I don't get the exactly same experience every time I play it

PD: sorry if anything got through my "censorship".

**Comment by philpw99** [comment]
I guess you already know what my problems is: I organized the files by using a scheme of :
G:\collection type(VR/HD/4K/Image)\Studios\original file name

then later I found out it's hard to find the actresses. If I search for "Helen", a lot of videos with the name "Helen" will pop up, and I don't even know which Helen that video contains. So here in my case, Stash is a must have. I can easily find "that Helen" not "the other Helens" by face. More often than not, that Helen works in different Studios with different aliases.

Anyway, if file browser works for you, then all the better. I think people here who use Stash in a regular basis are not so keen on managing a well-maintained file structure, just like me. I don't want to create any folders beyond 3 levels.

**Comment by magma2017** [comment]
It's important to keep in mind that Stash is still a work-in-progress with a lot of demand for various features/improvements.  I don't know how this could implemented though, especially with how JWplayer functions.  Could something be added in the future that does similar?  Possibly, but it'd probably be lower in priority compared some other requests based on what most people have been asking for.  Or it may come along with various UI improvements that have been discussed.

As for using File Explorer, that works fine until your collection reaches the size that some users' of stash have acquired over the years.  I know that with my personal collection that method may have worked for me when I first started downloading some years ago, but now?  Searching through File Explorer would be an awful experience no matter how well I structured my file folders.  Browsing/searching large collections of files based on metadata is far faster and simpler.  And scraping metadata for your collection is getting better and better over time as more people add to available databases to pull from.

If stash didn't work for you at the time, that's fine.  It's definitely better suited for people such as myself at this time, but that doesn't mean I don't want to see improvements to the overall user experience.

**Comment by masterofobzene** [comment]
Sorry to read that. Then I guess it will be always limited to one-file view and no controls. Basic stuff for porn viewing.
Again, this soft is aimed to people caring more for their collection than using it. A porn viewer with almost no controls? no videos and pics mix in a playlist? ...no sir... that is a core feature.
It seems there are two types of hoarders: 
the ones caring to collect and admire a collection (plain simple collectors like any other type of collectors)
the ones caring to actually being able to use the collection.

Stash goes for the first.
I go for the second.

Regards

**Comment by philpw99** [comment]
To be honest, I don't think my collection is  a mess. It is arranged by the type and studios, and it works pretty well for me. Because like 80% of time, I'll watch videos by the Studio, not by the performer. It's the other 20% that is the challenge, and I solved it by using Stash. Then I found out that Stash can do a lot more. Right now I watch my collections with Stash only.

The way you arrange the files is not neat as well. Images should have their own folders. And in your example pics, you put the actress Britney White's videos from different studio into the same folder. This is unacceptable for me. I'll never mix the videos from different studios.

Plus, many videos have 2 or 3 actresses in it. How do you put the video files then? Do you save one copy in each performer?

Anyway, I think the biggest problem here is that, you see the many lacking of Stash, but you didn't see the strength Stash has. Scanning and Organizing are their best features. Playlist creation is just an afterthought. Yet you are making it such a huge issue here. It's not really necessary.

**Comment by masterofobzene** [comment]
> To be honest, I don't think my collection is a mess. It is arranged by the type and studios, and it works pretty well for me. Because like 80% of time, I'll watch videos by the Studio, not by the performer. It's the other 20% that is the challenge, and I solved it by using Stash. Then I found out that Stash can do a lot more. Right now I watch my collections with Stash only.
> 
> The way you arrange the files is not neat as well. Images should have their own folders. And in your example pics, you put the actress Britney White's videos from different studio into the same folder. This is unacceptable for me. I'll never mix the videos from different studios.
> 
> Plus, many videos have 2 or 3 actresses in it. How do you put the video files then? Do you save one copy in each performer's folder?
> 
> Anyway, I think the biggest problem here is that, you see the many lacking of Stash, but you didn't see the strength Stash has. Scanning and Organizing are their best features. Playlist creation is just an afterthought. Yet you are making it such a huge issue here. It's not really necessary.

Thats because you are more pending of how your mess of collection looks than the actual usage. You are a collector, you could be collecting stamps or coins in the same way, you only care to have them neatly ordered however you never look at them. The only thing that puts your mind to rest and makes you feel good is to know how tidy your collection is.
Thats the collector fever. Don't care what you have, don't care if its easy to use it you just want to have nice looking studio banners and trivial info about the pornstars.. "brown hair, 1,50, likes lemon ice cream. .. .."    -who cares if its hot? 
You like to see trailers for porn movies.... .... come on... 
Want the synopsis too?  pfff

**Comment by masterofobzene** [comment]
https://www.schinagl.priv.at/nt/hardlinkshellext/hardlinkshellext.html

Thank me later.

**Comment by masterofobzene** [comment]
**eazyflixpix** 

BTW this seems to be more or less what I was looking for. Nice looking, tag support, can use my external player, has controls is customizable, CAN BE CLOSED LIKE ANY APP

Its a shame that development stopped but it will do anyway.

**Comment by magma2017** [comment]
Again, I'm sure in the future, improvements will be made to the overall viewing experience for people using stash.  However, at the moment, much of the development has been focused around the functionality of the organizational side.

Also, you're not the only person who uses their collection, you know, right?  Users such as myself who hoard a lot of data on a NAS don't have many good options.    Does my large collection mean I don't use it?  No, I just prefer to download things that catch my eye and keep it even if it doesn't turn out to be something I might watch more than a few minutes of.  And based on what you've shown of your own personal collection, I highly doubt you've watched every single minute of your collection either.   Definitely not more than once, unless you consider skipping through a 30min. video on a playlist as having watched it. 

People such as myself desire better ways to sort, identify, and deduplicate files.  Stash with each update is getting better and better at automating this process for its users.  Eventually that work will be done and I imagine development will move towards greater improvements towards usability.  A better way to organize and view one's own collection was the entire reason stash began development in the first place.  It's entire premise for existing is to improve the individual user experience decoupled from online sites.  File explorer can only get certain users so far, but development has to progress in stages, so certain aspects are given more attention than others early on.  However, some improvements to the UI are already in the works or have been discussed recently.

Everyone who uses stash wants to see it get better at its stated purpose.  It will just need further development.  Development, which is done mostly through people volunteering their own efforts.  Plus, one of the best things about Stash is that it is designed in such a way that if a friend wanted access to my massive library it could be given to them with relative ease should I decide to do so.  So the user experience is absolutely going to see changes/improvements.

Why you feel the need to keep shitting on a project clearly still in beta lacking a feature you desire is beyond me.

**Comment by masterofobzene** [comment]
Don't try to turn the tables putting yourself on the "poor missunderstood guy" side. You devs have that tendency. When arguments fail, you activate the protocol: "ohh poor me, giving my life on this and this is my payment"...  cut the crap please.

If you make an app to just tag the porn and add trivial info then do it, describe it as what it is and do your marketing accordingly. Then I won't be able to say anything. If you all say this is the best app to manage and watch porn, then you have to live to the expectations. 
An app to watch porn has controls to watch it and tries to make it easy as a minimum. This app doesn't.
You are all more concerned on having studio banners, (this is kind of funny) porn movies synopsis and trivial personal information about pornstars. 
You cannot even compete against a common video player.

You what is happening here? DONORS.
You will do what they like. And that's your free software vision after all. Money.

Do what you like, its your software but you know what hurts? that MY TIME has been wasted because of your scam-like marketing.

Go tell the truth in the front page, say that this soft is not intended as player but a way to put trivial info on your collection to make it look nice.

And no, nobody said that this was a Beta either.

Keep collecting unknown trash. I couldn't care any less. That alone is proof of how good the reasoning is.

**Comment by WithoutPants** [comment]
This has long gone past the point of being constructive. Locking the thread.

@masterofobzene given your entitlement and the way you've repaid the courtesy of the community members who chose to engage with you (none of which are stash developers fwiw), I don't feel obliged to address any of your points or concerns. If you don't like the product you are entitled to a full refund of the purchase price.
