### ISSUE TITLE
[Feature] Add an exit button

### ISSUE THREAD

**Issue by masterofobzene** [stashapp/stash#2020]
**Is your feature request related to a problem? Please describe.**

I use Stash as an standalone application, using a dedicated firefox installation in kiosk mode (fullscreen, no window controls visible).
Some of you that tried this have stumbled with the same situation: its impossible to close firefox in kiosk mode without having to execute ALT+F4. 
Problem is, I use a small RII remote keyboard when I'm confortable in bed and shortcuts like that are troublesome.
Also, I'm a little obsessive and want to make the experience VERY easy to control =)

**Describe the solution you'd like**
An internal EXIT button in Stash UI to close the tab (or browser) would be more than enough to mitigate this. Could be near the right top next to the options icon.

**Describe alternatives you've considered**
Installed a firefox extension to close the browser with a middle click, but just wanted to share my idea cause I think it would solve a problem.

**Comment by kermieisinthehouse** [comment]
Pages cannot close themselves, the browsers won't let them. You COULD do this with a pop up window or descendant tab, but Stash doesn't have anything like that.

**Comment by masterofobzene** [comment]
Is it possible to make a keyboard shortcut to do this? (it is part of my other feature request to make keyboard shortcuts easier and customizable)

**Comment by kermieisinthehouse** [comment]
Have you tried Ctrl-W?

**Comment by masterofobzene** [comment]
I'm trying to make it easier for use with small wireless keyboards where you cannot use combinations easily and need either UI imput with the mouse (like this button I'm requesting) or a single keypress that needs to be configurable by the user...

**Comment by kermieisinthehouse** [comment]
There is nothing we can do from the page to close its own tab. `window.close()` wouldn't work in this situation. Closing as out of scope
