### ISSUE TITLE
[Feature] add filter for "created at" and "updated at"

### ISSUE THREAD

**Issue by Ch00nassid** [stashapp/stash#2026]
**Is your feature request related to a problem? Please describe.**
I am adding new content to my stash but my collection backlog has grown out of control.  There are no means to sort, watch and then mark points of interest all at the same time.  This is too time consuming.

**Describe the solution you'd like**
I'd like to have a filter where i can add date ranges for videos to show up based on the "create at" or "updated at".  This way I can say that i know i haven't watched many scenes from X date forward.  show me all of those scenes that i have added after X date.

**Additional context**
I was hoping that once i selected the dates, i could use "random" and still have confidence that the scenes are from the specific date range i chose.

**Comment by SmallCoccinelle** [comment]
This is relevant for https://github.com/stashapp/stash/discussions/1964 so I added it to there as well. Should be fairly easy to add as a filter, but it might actually be more worthwhile to have a facet on it:

* new: 17
* >7 days: 34
* >30 days: 153
* >90 days: 427
* >1 year: 1710

So you can drill down on the facet you are interested in. A filter "cuts" to a given slice, but you don't get to know what's in the other "buckets" so to speak.
