### ISSUE TITLE
[Bug Report] Funscript files not being added to already scanned videos

### ISSUE THREAD

**Issue by Jules-WinnfieldX** [stashapp/stash#2031]
**Describe the bug**
Funscript files added to directories (with matching filenames to matching video) aren't being picked up by the scanner.

**To Reproduce**
1. Scan video files
2. Add funscript file to the same directory
3. Rescan
4. See video isn't recognized as interactive.

**Expected behavior**
Funscript files should be picked up and added to the matching file resulting in interactive and available playback.

**Stash Version: (from Settings -> About):**
Version v0.11.0
Build hash 1096fe81

**Desktop:**
 - OS: Windows 11
 - Browser Chrome

**Additional context**
Unsure if this has to do with the video having scraped data from ThePornDB after initial scan.

**Comment by stublu** [comment]
Can't help but can confirm this is an issue for me too.

**Comment by WithoutPants** [comment]
Fixed in #2096.
