### ISSUE TITLE
Allow creating movies with duplicate names

### ISSUE THREAD

**Issue by brnkaj** [stashapp/stash#2042]
**Describe the bug**
Adding movie with the same name but with different studio.

**To Reproduce**
1. Go to 'movies'
2. Click on 'new'
3. Scrape by URL
4. Save

**Expected behavior**
It should be possible to add movie with the same name but with different studio.

**Stash Version: (from Settings -> About):**
v0.11.0

**Desktop (please complete the following information):**
- dockerized app

**Comment by IAmKontrast** [comment]
Great idea. Outside the porn world there are a lot of movies with the same name even same release year.
I would like to get rid of the restriction completely but I don't know if this causes trouble in the backend.

**Comment by brnkaj** [comment]
Maybe it would help to have URL as part of user/unique key? I mean I don't know how DB is structured but you could have ID generated from sequence and if we assume that URL could be unique then you could easily make multiple records with the same name. ID is then used as foreign key in other tables ...

**Comment by IAmKontrast** [comment]
Why scenes have to be unique?
