### ISSUE TITLE
[Feature] Auto Tagging for organized files with opt-in

### ISSUE THREAD

**Issue by IAmKontrast** [stashapp/stash#2054]
I use folders and filenames for auto tagging performers, tags and studios. There are a lot of organized files in these folders. Sometime I change the folder name or path to change the studio or add some tags. Unfortunately auto tagging excludes organized files and therefore the tags won't be added to the scenes.

I would like to have an option like `Ignore organized media` checkbox (checked by default) but you can uncheck it and let the auto tagger run for all media or the other way around: Checkbox with `Include organized media` which is unchecked by default.

**Comment by SmallCoccinelle** [comment]
Sounds reasonable to me. We could expand the GraphQL to have the option first, then add it to the front-end.

**Comment by IAmKontrast** [comment]
Closed because its a micro minor case. Feature would cause more "damage" to our hard-earned tagged files than helping.
