### ISSUE TITLE
[Bug Report] ThePornDB Scraping in Tagger view renders oddly

### ISSUE THREAD

**Issue by jeremymeyers** [stashapp/stash#2058]
**Describe the bug**
When using tagger view to scrape from ThePornDB, some scenes come back as "Unnamed" in the results, but with accurate tags.

**To Reproduce**
1. Go to "Scenes"
2. Click on "Tagger"
3. Set tag source to "ThePornDB"
4. Hit "Scrape All"

**Expected behavior**
either return results in standard form or show 'not found'

**Screenshots**

![Screenshot 2021-11-23 18 42 04](https://user-images.githubusercontent.com/3514095/143146700-3eccf6e3-7082-47a9-b42f-346ef0c93054.png)
![Screenshot 2021-11-23 18 26 12](https://user-images.githubusercontent.com/3514095/143146702-e3e636d7-9294-4e0a-988a-2ecf04bd2580.png)
**Stash Version: (from Settings -> About):**
stash version: v0.11.0 (1096fe81 - Official Build) - 2021-11-15 22:49:08
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 94.0.1

**Comment by PartisT** [comment]
Can confirm!
If the scene is not found in TPDB, expanding the unnamed part shows tags that have already been applied to the scene being searched. Console returns
WARN[2021-11-24 14:23:46] Could not find json path 'data.0.date' in json object
WARN[2021-11-24 14:23:46] Could not find json path 'data.0.description' in json object
WARN[2021-11-24 14:23:46] Could not find json path 'data.0.background.small' in json object
WARN[2021-11-24 14:23:46] Could not find json path 'data.0.title' in json object
WARN[2021-11-24 14:23:46] Could not find json path 'data.0.url' in json object

**Comment by jeremymeyers** [comment]
cc @Tweeticoats @stg-annon @bnkai

**Comment by Maista6969** [comment]
This can be closed
