### ISSUE TITLE
[BUG] Immediatelly after setup screenshots  and generate tasks can't be created.

### ISSUE THREAD

**Issue by bnkai** [stashapp/stash#207]
After the initial setup through the web setup page i think the config info isn't propagated to the manager.As a result the first run of scan or generate without a restart uses null as the generated / metadata dir and so screenshots and metadata get a plain "screenshots" or "vtt" directory (instead of the metadata+screenshots one) that depending on chance could work.
As soon as you stop the app and restart it , it reads properly the config file and all is well
I think this could also be related to #83 #114 as the watchconfig on the manager side would notice the update on the config file.
To reproduce you can just rename the .stash directory and do a clean setup with different metadata dir , just make sure you don't run stash from within the metada directory so you can see the ffmpeg errors.
I tried a bit running the manager.Initilalize() after the config.Save in api/server.go but it didn't work and i'm not sure if thats the right way anyway.
Force restarting the app after the setup is complete might be a little brute force ?

**Comment by WithoutPants** [comment]
This is also reproducible by modifying the Generated Path field then scanning. The system will continue to try to put generated files in the old location.
