### ISSUE TITLE
[Feature] Add option to disable gallery swipe animation

### ISSUE THREAD

**Issue by HappyAxolotl** [stashapp/stash#2070]
**Is your feature request related to a problem? Please describe.**
The swipe animation when viewing images in the lightbox viewer is distracting and slows down the speed at which you can go through the gallery.

**Describe the solution you'd like**
I'd like to have an option to disable the swipe animation in the lightbox viewer. Instead the next image should be shown immediately (like in the nextcloud image viewer or the Photos app on Windows 10).

**Describe alternatives you've considered**
An alternative would be to remove the swipe animation completely but this is just my personal preference so I feel this should be configurable.

**Additional context**
The option could be added to the lightbox settings dropdown:
![image](https://user-images.githubusercontent.com/95097933/143621875-792d7e55-3a42-4c45-95e5-c85ed6aaa112.png)

**Comment by WithoutPants** [comment]
This is possible using a custom css directive (which I have added to the [wiki page](https://github.com/stashapp/stash/wiki/Custom-CSS-snippets).

```css
.Lightbox-carousel {
  transition: none;
}
```

Given that it is possible this way, I don't think it's worth making a setting for it.
