### ISSUE TITLE
[Bug Report] Height input is missing in Performers tab after an update

### ISSUE THREAD

**Issue by UncleRoger33** [stashapp/stash#2074]
**Describe the bug**
Height input is missing after updating the stash-win.exe from **v0.10.0** to **v0.11.0** (i assume migrated database schema is messed up, couldn't pinpoint the issue.)

**To Reproduce**
1. Try to create a new performer after updating  from **v0.10.0** to **v0.11.0**

Alternative:
1. Create a performer, Fill in the "Height" of the model in **v0.10.0**
2. Update the stash-win.exe from **v0.10.0** to **v0.11.0**
3. Go to performer tab and try to edit.

**Expected behavior**
Performer Height input should be there

**Screenshots**
 How it looks like in **v0.11.0**
![Performers](https://user-images.githubusercontent.com/66418211/143778975-2c72ecf8-b974-4abc-8dcd-88995a311ce3.png)

I created this performer in **v0.10.0**, i can see the height, but i can't edit that value in **v0.11.0**.
![Performers_(old)](https://user-images.githubusercontent.com/66418211/143778994-2c8ef94e-05f3-4fd6-9f63-f5bdbf27bee8.png)

**Stash Version:**
Version: v0.11.0
Build hash: 1096fe81
Build time: 2021-11-15 22:47:45

**Desktop:**
 - OS: Windows 10
 - Browser Mozilla Firefox
 - Version 94.0.2 (64-bit)

**Additional context**
None.

**Comment by 7dJx1qP** [comment]
There's no database migration when upgrading from v0.10.0 to v0.11.0. I also tried your reproduction steps and couldn't reproduce the issue.

Are you using any custom css?

**Comment by UncleRoger33** [comment]
Just this one which removes the Donation button:
```
.btn-primary.btn.donate.minimal {
  display: none;
}
```

**Comment by kermieisinthehouse** [comment]
Hi, I can't reproduce this on latest develop or the 0.11.0 tag. Are you running and browser extensions or plugins that might do this? That CSS is not the issue.

**Comment by UncleRoger33** [comment]
>  Are you running and browser extensions or plugins that might do this?

What the .... Thanks for the heads up, i've found the culprit. It is uBlock Origin.

![ublock](https://user-images.githubusercontent.com/66418211/143997456-93225e43-dd00-4c23-9e1b-d54e62c51ec0.png)

It seems i selected "Block element..." instead of "Inspect" 🤦‍♂️ 

![ublock2](https://user-images.githubusercontent.com/66418211/143997785-fec8c6ca-db13-4fe0-84e1-f96a3d7dcec1.png)
