### ISSUE TITLE
[Feature] Previous/Next Buttons in Player and Keyboard Shortcut support.

### ISSUE THREAD

**Issue by stashTX** [stashapp/stash#2089]
The random/queu play feature in StashApp has some behaviors that seem less good than some of the other similar projects (Jellyfin in this case).

- No Previous/Next buttons on video player
- Player exit's full screen when playing next item in queue
- Cannot seem to enable continuous play default in my current version (might just be my issue).

In Jellyfin for example,  one can click "Shuffle" when in a folder or at the top level library and an asset will start to play.   The player has "next" and "previous" buttons to skip forward or backwards through the queue.    One can full screen this player and skip forward and backward through the queue and the player remains full screen and plays the previous or next video.

The player also supports keyboard shortcuts for those features.

Not sure this is possible with the current stash player choice/architecture, but the feature request in a nutshell:

- Add Previous/Next buttons to player
- Enable keyboard shortcuts for these features
- Prevent player from exiting fullscreen when flipping forward and backwards in queue.

thanks!

**Comment by ALonelyJuicebox** [comment]
Just adding that there are keyboard shortcuts for these features. The keyboard sequence pn (next scene) and pp (previous scene)

**Comment by stashTX** [comment]
Ah.  Thanks.  I somehow missed those ones.

So that could narrow down this FR to "Make player stay full screen when flipping between scenes"

**Comment by masterofobzene** [comment]
just need to hit CTRL + ALT + F12 while doing the konami code with the other hand and it will work.

**Comment by WithoutPants** [comment]
I suspect this will be easier to implement once we switch to videojs (which is a pending pr).

**Comment by stashTX** [comment]
I think so!
