### ISSUE TITLE
unraid jlesage/handbrake docker support

### ISSUE THREAD

**Issue by binarygeek119** [stashapp/stash#209]
i use jlesage/handbrake docker to convert all my videos into the formate i want (480p30fps as mp4).
this setup works great i have a temp folder i dump all my videos into it.
jlesage/handbrake will then go one by onbe and convert it for me, and drop it in to my stash video folder. this works great and no trouble with it but it does have one this i wish it wouldnt.
when the convertor is converting it place the temp file soon to be the competed file in a temp folder then moves it down a level

stash temp = handbrake
stash done = stash video folder

server
folder 1
folder 2
folder3
stashdata
stashappdata
stash   > stash done > video65.mp4
                                 > .y38sn38~ >y38sn38~.mp4.temp -- will rename back to original name after completing 

           > stash temp > video.wma -- converting now
                                 > video2.mp4

after converting

stash   > stash done > video65.mp4
                                 > .video.wma completed

           > stash temp > video2.mp4

as you see it cretae a dot random name ( .y38sn38~) and rename the video to that as well
when done with will rename it to original name and drop it in to the main stash folder (go up a level) then it will remove the dot folder  ( .y38sn38~) 

all i would like is for stash to ignoring  any folder with a dot

the only reson i want this is for this issue 

2019-11-15 11:33:13 Error    FFProbe encountered an error with </stash/stash done/.ckRVp1/.ckRVp1.mp4>.
Error JSON:
{
    "error": {
        "code": -1094995529,
        "string": "Invalid data found when processing input"
    }
}

**Comment by Leopere** [comment]
Not sure if we should be responsible for transcoding your content back into your libraries since there are many tools available already for this.  However, it's not a hard no on this, but it seems redundant.  

Transcoding is also fundamentally wrong when it comes from an already lossy source.  Yes, there is machine learning-based resolution upscaling solutions options, but archival transcoding should likely be done by the experts.

**Comment by bnkai** [comment]
@Leopere i think he means ignore file / folder functionality that's been asked also in the discord channel.
In his case it would be a little more complicated though.

i would either choose a different directory and move the files with a postscript or something or simply scan only after handbrake is finished....

**Comment by Leopere** [comment]
Ignore files are not the worst idea but I think at the moment would it not make the most sense to just use separate directories `./in` `./out`

**Comment by Leopere** [comment]
Doesn't Stash already only include certain filetypes? #180

**Comment by bnkai** [comment]
Related to #253 
The hidden directory regex should work for this .

**Comment by bnkai** [comment]
Closing since #253 was commited
For reference the hidden directories exclude example from the [wiki page](https://github.com/stashapp/stash/wiki/Exclude-file-configuration )  covers this issue.
