### ISSUE TITLE
[Feature] Extending Metadata, more flexibility 

### ISSUE THREAD

**Issue by cmuc24** [stashapp/stash#2095]
**Problem Statement**
for larger amounts of videos, Metadata becomes more important

**Solution**
more flexibility for importing or even providing metadata 

Thanks in advance for any kind of feedback

**Comment by DogmaDragon** [comment]
Could you expand on this?

**Comment by Maista6969** [comment]
This can be closed

**Comment by DogmaDragon** [comment]
Too vague.
