### ISSUE TITLE
[Feature] (lack of) 

### ISSUE THREAD

**Issue by masterofobzene** [stashapp/stash#2104]
**Is your feature request related to a problem? Please describe.**
Alright this is the "bad vibes" post.
Lack of features:

1. cannot play videos + pics in the same playlist.
2. playlists are a pain to make. Everything requires +6 clicks
3. lack of media playback controls
4. no easy way to play "all videos + pics containing this tag" or "all videos + pics from this pornstar"
5. transcoded video that didn't needed to be transcoded, and the final video looked horrible. (source was 320p, final was 240p)
6. keyboard shorcuts are a combination of letters, no option to change them.
7. cannot jump from "this kink" to "that kink" since all media has to be played handpicked again requiring to search, filter, hand pick the movie and watch it until the end OR repeat. Also again; if you are watching pictures, don't expect videos to pop up in a playlist. Have to select them manually again.
8. Devs said that all these features are "trivial".

**Describe the solution you'd like**
All the above solved. Some people actually wants to watch their porn instead of just adding the personal tastes and history of the e-prostitutes they collected.

**Describe alternatives you've considered**
Use the good old Explorer.exe, symbolic links and a video player that accepts pics too. 
Artists folder holds all pornstars. Kinks folder holds symbolic links from the artists based on the action of the movie or pic. The links could be whole folders (all content inside) or hand picked videos or pics.

**Additional context**
The dev road for this software is set to "add metadata to porn" instead of making it easy to watch it. I consider that dumb since these are not normal movies. No plots, or any kind of culture stuff in it. There is no art here. No themes. Want a plot for a porn movie? here, copy and paste this to all of them: "they all fucked." Do you imagine yourself reading porn movie plots? ha! that's a good one.

-"shh! honey, I couldn't understand what they said..." 
- "oh yeah that porn movie! I had to watch it twice to understand it"

Its just plain porn in all the possible flavors. Metadata is cool but the core here is being able to use the collection not just mantain it. Even mantaining it doesn't even make sense since that metadata is transparent to video players so you cannot do anything useful with it outside of stash.
Its like making a perfect Ferrari... without accelerator, brakes and direction wheel.

Why on earth would someone prefer to have all possible data about X pornstar and X studio if playing the stuff is complicated is beyond my comprehension. But here we are, that's the main road here.

If you cry that you have lots of terabytes of content and cannot find your stuff, then you have done things wrong and missed the step of curating; your fault sorry.

**Comment by QxxxGit** [comment]
This is incredibly antagonistic and rude. Why would the devs give you the time of day because of your attitude?

Your feature requests are fine; some of which have been mentioned in other feature requests. I just dont get the hostility and entitlement towards people who are developing free software.

**Comment by masterofobzene** [comment]
Because they already have been rude.
https://github.com/stashapp/stash/issues/2019

And because one can have respect for some questioning, but cannot respect stupidity. Sorry but if you make a software to manage your collection and intentionally "forget" about how you will actually play your stuff... that's not a big "oops" only.

**Comment by QxxxGit** [comment]
The devs have been incredibly nice in my experience. This is just weird my guy.

@WithoutPants hopefully this gives you a notification. Not sure how to report this thread on mobile.

**Comment by InfiniteTF** [comment]
A lot of people spend a lot of their free time on this project. There are certainly numerous improvements that could be made, and are being made, but mocking the project isn't very fruitful. I'm sorry you're unhappy with the time you've wasted, but I would suggest you move on and use something else.
