### ISSUE TITLE
[Bug Report] No options from 'Settings > Tasks > Library' are saved when configured

### ISSUE THREAD

**Issue by SmartPhoneLover** [stashapp/stash#2106]
**Describe the bug**
When the user enables/disables any of the options available from the Library section, located in the Tasks tab, non of them are kept after re-loading the interface. Also, no 'Save' green button is shown in the Tasks category.

**Expected behavior**
The options under Tasks section should be saved after configuring them.

**Stash Version: (from Settings -> About):**
v0.11.0 ('1096fe81')
Docker

**Comment by SmartPhoneLover** [comment]
Or is this the expected behaviour?

**Comment by kermieisinthehouse** [comment]
This is expected behavior, BUT, this feature is being added in https://github.com/stashapp/stash/pull/2086
