### ISSUE TITLE
[RFC] SHow do I set up stash with a subfolder based reverse proxy?

### ISSUE THREAD

**Issue by JustAnotherUserName32** [stashapp/stash#2110]
Hi there,

I currently have Stash set up with nginx using a subdomain based reverse proxy, but I want to switch to subfolder based reverse proxies. I found #740 and #1719 but I can't seem to get this proxy header to work. Am I not using the header correctly? Does my build of stash not support the header yet? This is my nginx config that I made by adapting another subfolder conf provided by LSIO's SWAG container: [stash.subfolder.conf.txt](https://github.com/stashapp/stash/files/7699911/stash.subfolder.conf.txt)

According to stash I'm on version 0.11.0 with build hash 1096fe81. I'm using hotio.dev's stash container.

Thanks

.

**Comment by Tweeticoats** [comment]
you probably want to specify localhost or the ip address running stash.
You are setting upstream app to the host name stash. unless you also put the host name stash in your /etc/hosts file it does not know what that computer name is. change this to 127.0.0.1

You also need to use web sockets to connect to stash by allowing the connection to "upgrade" to web sockets with the following options.
 
           proxy_http_version 1.1;
           proxy_set_header Upgrade $http_upgrade;
           proxy_set_header Connection "Upgrade";

https://github.com/stashapp/stash/wiki/Reverse-proxy

**Comment by JustAnotherUserName32** [comment]
Hmm I added those to my location subsection and now nginx won't respond

    location /stash {
        return 301 $scheme://$host/stash/;
    }

    location ^~ /stash/ {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app stash;
        set $upstream_port 9999;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        proxy_set_header X-Forwarded-Prefix /stash;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

I don't know how docker's internal DNS works, but I can reference containers by a name so long as the container's name matches.

**Comment by kermieisinthehouse** [comment]
Look in your logs. Specifying a FQDN in nginx config usually means you have to specify a "resolver", which is a big pain in docker.

FYI, I use [this nginx config](https://github.com/kermieisinthehouse/stash-subpath-tester/blob/main/nginx.conf)  to test the subpath feature while developing on Stash. It proxies a stash instance running on the host through an nginx instance running in docker, for reference.

**Comment by JustAnotherUserName32** [comment]
I think the rewrite line in your config is what did the trick:

    location /stash {
        return 301 $scheme://$host/stash/;
    }

    location ^~ /stash/ {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;

        set $upstream_app stash;
        set $upstream_port 9999;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        proxy_set_header X-Forwarded-Prefix /stash;
        rewrite ^/stash/(.*)$ /$1 break;
    }

I'm not sure about the websockets that @Tweeticoats mentioned, I can play most content that I've got, only 5K content won't play, I get an error code of 244002

**Comment by kermieisinthehouse** [comment]
We don't use error numbers, so I assume that came from FFMPEG? Can you post the entire error string?

**Comment by JustAnotherUserName32** [comment]
The full error message is "This video file cannot be played. (Error Code: 224002)"

**Comment by kermieisinthehouse** [comment]
That's a jwplayer error, it seems there's an issue with the codec or something. We're switching to a different video player solution soon, that might help (or the file is busted)

**Comment by JustAnotherUserName32** [comment]
I've tried multiple 5K videos and they all fail with the same error code. I checked the codec stuff in VLC and everything appears to be ordinary, H264 video, 24FPS, 4:2:0 chroma, and AAC audio.
