### ISSUE TITLE
[Feature] Performer filter: compare option for Height

### ISSUE THREAD

**Issue by Belleyy** [stashapp/stash#2113]
**Is your feature request related to a problem? Please describe.**
The current **Height** filter don't have a option to give you performer based of a desired amount. 
Tbh the current option for **Height** are not really useful... (Include ?, regex ?)

**Describe the solution you'd like**
Having `greater than`, `less than`, `between` and `not between`.

**Additional context**
**Weight** filter already have it but not **Height** 😋

**Comment by kermieisinthehouse** [comment]
This probably requires a migration casting height into an int, and perhaps renaming it height_cm. 

In a test of my database using `SELECT height FROM performers WHERE printf("%d", height) != height;`, the only entries that I had that were not a simple cast just included the string 'cm' at the end, or were only whitespace.

**Comment by WithoutPants** [comment]
$30 bounty added (6-May-2022)
