### ISSUE TITLE
[Feature] Only one step away from full DeoVR support.

### ISSUE THREAD

**Issue by philpw99** [stashapp/stash#2116]
**Is your feature request related to a problem? Please describe.**
 Need to have a stream link with file extension like .mp4 or .mkv so DeoVR can play the scene.

**Describe the solution you'd like**
Add a stream link with file extension, like "http://192.168.1.10/scene/123/stream.mp4".

**Describe alternatives you've considered**
A "Launch File" button? Which will open the local file directly, not through the web interface.

**Additional context**
Stash has been my favorite porn organizer since I discovered it. I wrote an app to help me launch the DeoVR player to play a scene I selected from the browser. It works well for me.

The reason I want this feature, because I see right now Stash has come so close to fully support the DeoVR playback. Just a little modification, and DeoVR will be working great with Stash, either with Quest 2 remotely, or with other HMD locally.

Right now in DeoVR, I can browse the movies like this:
![s1](https://user-images.githubusercontent.com/22040708/145867539-80fcf7e4-ad40-41d2-a084-b41869b2d91f.png)

Then view the movie poster like this:
![s2](https://user-images.githubusercontent.com/22040708/145867624-4088a005-19ac-4e89-a428-96541066cc54.png)

Then go in to the scene like this:
![s3](https://user-images.githubusercontent.com/22040708/145867693-b5529b8a-3b3e-45a9-8317-0d64fc153715.png)

It's almost perfect, except the stream link doesn't work yet. ( The file link doesn't work either because web browser cannot access local files.)
DeoVR just need a link with file extension, like "http://192.168.1.10:9999/scene/123/stream.mp4", and it's done. No need to re-encoding or remuxing, just serve the original file with "stream.mp4" or "stream.mkv". DeoVR player will happily take over from there.

**Comment by philpw99** [comment]
Also if we implement this, there is no need for DLNA serving for DeoVR users any more. We can just view and play the files directly from the browser.

**Comment by kermieisinthehouse** [comment]
#2105

**Comment by philpw99** [comment]
> #2105

This is different than the JSON approach. I tried JSON before, and it requires a HTTPS connection. Yet if we use a direct file name, suddenly it works without https.

**Comment by philpw99** [comment]
@Caleripo  I don't know about other VR players. For me DeoVR comes very close to be able to fully functional in its own browser.
Skybox doesn't work with a gamepad or keyboard/mouse and it was abandoned long time ago. So I don't use Skybox. I don't see a web browser in Skybox either.
I don't have Oculus browser either. Don't really know how it works.
The DeoVR team wants to use JSON for websites, but the HTTPS requirement severely limits its use. Even you create json files that fully comply with their specs, you still are left with a nonfunctional website. Their web-hub implement is also unfinished. We cannot wait a long time for them to finally finish it.
Therefore, the fastest and easiest way to support DeoVR with VR files playback, is just to add ".mp4" or ".mkv" to the end of the stream. It should be easy, right?

**Comment by SilentSpartan** [comment]
I hate DEO but love Skybox. So if it helps browsing through Stash on there as well, I'm all for it.

**Comment by kermieisinthehouse** [comment]
This is actually already supported. You can add .mp4, .webm, .mkv, .ts, .m3u8 to the end of a stream url and get the video streamed in the requested format.

**Comment by philpw99** [comment]
Wow, why only now I see this ?! I am so stupid not to check this !!
Thank you @kermieisinthehouse  for telling me this. This is wonderful news to me !

**Comment by philpw99** [comment]
Sorry, but it turns out the "stream.mp4" or "stream.mkv" are extremely slow because they are not directly served.
So once again, this issue is not resolved, but I think it's better just keep it closed.
