### ISSUE TITLE
Can't access webui after logging in

### ISSUE THREAD

**Issue by MC1R-13** [stashapp/stash#2117]
After updating to the latest dev build, I can't do anything beyond logging in.  There's just a blank screen.
The only message in the log was this:
> level=warning msg="Database schema version 28 does not match required schema version 29."

So I let it create a new one, but the result was the same.

I'm not sure which of the recent updates could have caused it, but it was after v0.11.0-43-gd659411c, which I believe was the first one from Sunday, and the only one I used until today's.
I've reverted to v0.11.0 for now, which works fine.

1. Download latest dev build
2. Log in

**Stash Version: (from Settings -> About):**
v0.11.0-51-gd176e9f1

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur 11.6.1 (Intel)
 - Browser: Safari
 - Version: 15.1

**Comment by kermieisinthehouse** [comment]
Make sure you disable any custom themes, some conflict with the database migration page

**Comment by WithoutPants** [comment]
Have you tried doing an F5 refresh of the browser after logging in?

**Comment by jchilders99** [comment]
I have the same issue and I do have a custom theme.  But how do I disable it if I can't get into the UI?

**Comment by jchilders99** [comment]
Never mind.  @MC1R-13 I opened it in Firefox and the database migration screen loaded fine.  All's well now; try a different browser :)

**Comment by MC1R-13** [comment]
Thanks for the suggestions.  The issue is definitely Safari. I logged in on Chrome and it was able to do the database migration, but it's still not working in Safari.
I have tried refreshing the page, which worked in the past, but no such luck this time.

**Comment by jchilders99** [comment]
Thanks @kermieisinthehouse.  The updated build fixed my Safari issue.
