### ISSUE TITLE
[Feature] 'Default Filter' & Full Width For Performers>Scenes & Studios>Scenes

### ISSUE THREAD

**Issue by ghfsa** [stashapp/stash#2118]
**Is your feature request related to a problem? Please describe.**
Just like the 'Scenes' tab:
- Need  '_Set As Default_' filter option for '**Performers>Scenes**' & '**Studios>Scenes**'
- To show the above two pages in full width just like 'Scenes' tab

**Comment by feederbox826** [comment]
resolved by https://github.com/stashapp/stash/pull/4962
