### ISSUE TITLE
[Bug Report] 'Tasks' not saving in Dev Preview

### ISSUE THREAD

**Issue by WhoIsThisGuyForReal** [stashapp/stash#2135]
**Describe the bug**
If you change something under the settings in 'Tasks', it is not saved. All other settings are saved.

**To Reproduce**

1. Download the latest Dev Preview
2. Click on the Settings Icon
3. Select 'Tasks'
4. Change something
5. Reload the Page

**Expected behavior**
The settings in 'Tasks' should be saved.

**Stash Version**
v0.11.0-59-gbf1b835d

**Desktop**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 96.0b5

**Comment by kermieisinthehouse** [comment]
This is the expected behavior. Task options are not settings, they're just how you would like to run the task you're about to kick off.

Relatedly, setting them and then kicking off the task will remember your options for next time as the default
