### ISSUE TITLE
[Bug Report] Stash no longer running after update

### ISSUE THREAD

**Issue by tpl551** [stashapp/stash#2143]
I recently downloaded v0.11.0 (Linux) after having not used Stash in a while. I'm not sure what version I was running previously, but it was working perfectly. Now when I try to start it, I get the error:

./stash-linux: line 7: syntax error near unexpected token `newline'
./stash-linux: line 7: `<!DOCTYPE html>'

Haven't changed anything else in my setup - any ideas what could be causing this?

**Comment by InfiniteTF** [comment]
Can you try downloading stash again, and checking the command you're using to start it with? This looks like a bash error.

**Comment by kermieisinthehouse** [comment]
You've downloaded the wrong file. Try using one from https://github.com/stashapp/stash/releases/latest
