### ISSUE TITLE
[Bug Report] Filters are not internationalized, other i18n

### ISSUE THREAD

**Issue by kermieisinthehouse** [stashapp/stash#2151]
**Describe the bug**
Filter selection is not completely internationalized

- "Is missing" filter all selections are hardcoded
- "Has marker"
- "Organized"
- "Interactive"
- In images when opening an image,  if it's part of a gallery "Galleries" doesn't translate.
- When editing a scene the items at the bottom are "Performers/Scene/Tags" while editing a gallery it's "Performers/Tags/Scene", it's not a big deal but maybe it would be nice to have some consistency slight_smile

Thanks to BViking78 for reporting these

**Comment by WithoutPants** [comment]
I can't find any of the first four items that aren't internationalised.

I don't know what is meant by the last item.

**Comment by WithoutPants** [comment]
Closing as resolved. If there's anything missed, then this can be reopened.
