### ISSUE TITLE
[Feature] Move files between drives.

### ISSUE THREAD

**Issue by z8r8xsmbxciryzv3g46j** [stashapp/stash#2158]
Right now if I want to move some files from one drive to another I have to cut and paste the files from one drive into another and then I have to delete all generated files for the first drive and generate all files again. Unless I want to search for each scene one by one and delete the generated files.
I would like to be able to do this from stash by just selecting the scenes and indicating the destination.

**Comment by HereIam80** [comment]
There is a much simpler way of doing this than you describe.
If you want to move files, do that by cutting and pasting as usual. After that just run a scan (or selected scan) for the new files.
All files will be discovered in the new directory and the paths will be changed in the database.

**Comment by z8r8xsmbxciryzv3g46j** [comment]
Oh that's much simpler. Just to be sure if I run the scan on the destination drive the files I've moved there get their generated files updated automatically and not duplicated?

**Comment by HereIam80** [comment]
Yes. That is because the files are recognized by their unique hash value and not their path. This way they can be rediscovered. The name of the generated files IS the hash value so no need to delete the generated files.

There are some plug-ins for moving files according to their studio etc. but I never tried them.

**Comment by ajr-dev** [comment]
What is the reason for closing it?

**Comment by kermieisinthehouse** [comment]
The proper method for moving files is described in the first comment. Just moving/renaming files and doing a scan is all you need to do, Stash was designed with moving files in mind.

**Comment by ajr-dev** [comment]
I still can't filter by tags if I want every file of a specific category or performer in the same drive.

**Comment by z8r8xsmbxciryzv3g46j** [comment]
I still can't filter by tags if I want every file of a specific category or performer in the same drive.

**Comment by kermieisinthehouse** [comment]
If you're saying that you want to move stuff to a specific location based on tags, Stash doesn't support that, but there are renamer plugins that can get you at least part way there

**Comment by z8r8xsmbxciryzv3g46j** [comment]
I know it doesn't, that's why I opened the issue. If you mean Stash will never support that, then if you know so well what Stash will be like why don't you tell us instead of making a survey to ask our opinion?

**Comment by kermieisinthehouse** [comment]
That's unnecessarily hostile for my response. The OP is confusing, there's no valid workflow where you have to delete scenes just to re-add them; I thought this was about migrating scenes. If you want to mass-move scenes based on some filter criteria, that feature has never been planned or discussed in very much detail. You should probably create a new issue that sketches out the feature more concretely.
