### ISSUE TITLE
[Feature] Add DLNA "Random" and "Last Added (Updated at)" categories

### ISSUE THREAD

**Issue by kitsuragi** [stashapp/stash#2166]
Being able to sort scenes by random or last-added in the web-interface scenes page is a great feature that can save you a lot of time, however in DLNA interface which is what I mostly use the scenes are always sorted alphabetically in  the "all" category, and my player doesn't have the option to change the sorting method.
Is it posible to add that as a "random" and "last added" categories to DLNA, and maybe give user an ability disable unwanted categories for DLNA?

**Comment by wirbelsaeure** [comment]
I'd also like to request this.

Perhaps DLNA categories could even be customizable the same way we can customize the start page since v0.16? Or at least add more useful categories to browse by. (e.g. Recently added scenes, recently released scenes, random ...)

**Comment by apache202119** [comment]
It'd be great to use the saved filters / sorting on DLNA, watching the scenes on a TV currently is a pain in the ass
