### ISSUE TITLE
[Feature] Multiple scrape URL for performers

### ISSUE THREAD

**Issue by devster31** [stashapp/stash#2171]
**Is your feature request related to a problem? Please describe.**
Many performers have multiple profiles on various sites and most sites have different information.

**Describe the solution you'd like**
Add multiple URLs for the same performer all of which can be scraped by the appropriate scraper.

**Comment by stg-annon** [comment]
Seems like this is a duplicate of Issue #1868 and is currently a WIP in PR #1959
