### ISSUE TITLE
Config should be read from cwd before user profile

### ISSUE THREAD

**Issue by WithoutPants** [stashapp/stash#219]
Current behaviour is to look for the config file in the `$HOME/.stash` directory, and only if it is not found there, check the current working directory. In my opinion this should be reversed. The current working directory should always be checked first, falling back to the user directory if not found. 

I think also that the system should print the config file that it ends up reading from. It can be confusing to find that the system is running from a specific config and not being able to check. It could perhaps be printed in the configuration UI as well.

Finally, add the ability to specify the config file location from the command line. This will make running and testing multiple deployments easier.

I realise that this probably won't affect 90% of users, but this will improve things for people that test changes in a separate deployment.

**Comment by Leopere** [comment]
I don't know why it was done the original way so we should see if @StashAppDev wants to weigh in.

**Comment by Ch00nassid** [comment]
Yeah i was trying to seperate my import work from doing testing on a different version.  I would love this feature.
