### ISSUE TITLE
[Bug Report] Performer tagger don't save transgender

### ISSUE THREAD

**Issue by Belleyy** [stashapp/stash#2192]
**Describe the bug**
The gender is not saved if the performer is transgender.

**To Reproduce**
1. Go to Performers
2. Click on Taggers
3. Search transgender performer (ex: `Korra Del Rio`)
4. Save

**Expected behavior**
The gender to be set.

**Screenshots**
![image](https://user-images.githubusercontent.com/23707269/147822299-2d16b61a-2d2b-4e26-9a80-6c3f47363924.png)

**Stash Version: (from Settings -> About):**
Version: v0.12.0-3-g7f831524
Build hash: 7f831524
Build time: 2021-12-29 23:55:06

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Firefox 95.0

**Additional context**
Only checked for Transgender Female

**Comment by peolic** [comment]
Looks like #2191 might fix that.

**Comment by Belleyy** [comment]
> Looks like #2191 might fix that (as well).

Well actually it's worse, the gender don't appear in the tagger UI anymore

**Comment by Belleyy** [comment]
So re-tested on a performer, don't seem to be fixed. This issue should be re-open.
