### ISSUE TITLE
[Feature/RFC] Integrate miles-deep, automatic tagging

### ISSUE THREAD

**Issue by Xorike** [stashapp/stash#22]
Hey there!

I tried your new Go version, and it's already looking really good as well as being easier to get running!

I'm not sure if you are looking for requests yet, and this one is low priority so feel free to close the issue for now, but just wanted you to be aware of this software written by a Redditor.

It's called [miles-deep](https://github.com/ryanjay0/miles-deep), it's a neural network which can analyze a porn video and give you timestamp for various sexual acts.

My English isn't that great so please have a look at the project's readme, it will explain it better!

Just thought this would be a nice match for your project!

Looking forward to the full Go version :+1: 
Have a nice day.

**Comment by bobmadoshi** [comment]
Another cool "feature" would be uploading those tags to pastebin (or similar) along with the hash of the clip so anyone with the same clip could pull the tags 👍

**Comment by Leopere** [comment]
If the software is any good then it sounds like it could be a great value addition.

**Comment by jeremymeyers** [comment]
We've spoken about this in the Discord and the general consensus is that Miles-Deep is slow and not especially accurate at this point.  Personally I think this would be better suited as a plugin rather than core functionality.
