### ISSUE TITLE
[Feature] Add for actor dick cut or uncut

### ISSUE THREAD

**Issue by baloodusudouest** [stashapp/stash#2202]
Hi,

Can you add a field to select if the actor / performer has is dick cut or uncut?

Thanks

**Comment by sleetx** [comment]
This would ideally take the place of the "Fake Tits" field on male profiles ("Fake Tits" is currently a field for every performer). Both of those should be gender-specific

**Comment by baloodusudouest** [comment]
No update?

**Comment by Maista6969** [comment]
This can be closed since #3627 was merged
