### ISSUE TITLE
ThePornDb (metadataapi.net) down

### ISSUE THREAD

**Issue by ibillabong** [stashapp/stash#2203]
Can anyone else confirm that ThePornDB website is down/offline?  

"404 page not found"

**Comment by VonTittyslappen** [comment]
Yep, it's down, not sure why, I have alerted the owner but it's night time for him now, there was downtime yesterday as well, not sure of the reason why.

Your best bet is checking the TPDB discord for info, not raising issues on here, TPDB isnt part of Stash :)

**Comment by ibillabong** [comment]
Thank you @VonTittyslappen ! I did notice that the Discord link was also down :) I wonder if it's related?

**Comment by VonTittyslappen** [comment]
no the Discord server was still up, site is back now :)
