### ISSUE TITLE
[Bug Report] Tags manually added in scene tagger being removed when clicking + icon on new tags

### ISSUE THREAD

**Issue by VonTittyslappen** [stashapp/stash#2204]
**Describe the bug**
It's quite hard to explain in text, so I have recorded a video which I'll attach to this issue, which better explains it.

I am using the Scene Tagger, and up pops a list of tags it wants to add to the scene, but I want to add an additional tag I manually created my end (scraped_from_stashdb), I therefore type that in the top box, but if I then decide "okay, there are some tags that I want to add that havent been set up, and I click the + icon to add them, it removes the tag I had manually typed in to add (which already exists).

I have the settings in the tagger to merge tags, not overwrite.

Hopefully your head hasn't exploded in trying to understand what I just said, watch the video if you care about your head :D :)

**To Reproduce**
As above

**Expected behavior**
The tagger should remember that I have just manually added a tag to the list, and recognise that its still there, not undo what I just did.

**Screenshots**

**Stash Version: (from Settings -> About):**
v0.12.0-12-gbe5dc7e5

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 for using Stash via Chrome, but Stash is located on my Synology NAS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 96.0.4664.110 (Official Build) (64-bit)

**Additional context**

**Comment by VonTittyslappen** [comment]
Please let me know when one of the staff have looked at the video evidence, so I can then remove it :)

**Comment by TorvaldUtne** [comment]
Note: This also happens if you manually add a tag and then go back up and click to create a performer.

**Comment by VonTittyslappen** [comment]
> Note: This also happens if you manually add a tag and then go back up and click to create a performer.

^ yep, can confirm, just tested it now
