### ISSUE TITLE
[Feature] Allow for scrubbing of videos on hover in the grid view

### ISSUE THREAD

**Issue by newadventure079** [stashapp/stash#2206]
**Describe the solution you'd like**
When in the grid view, I'd like to be able to hover over the video and scrub thru it

**Additional context**
[VideoHubApp](https://videohubapp.com/en/ ) has this feature.  [Example](https://videohubapp.com/images/1.mp4)

On Discord, Kermie said `If you have sprites, we technically have all the data necessary for this feature.`

**Comment by feederbox826** [comment]
resolved by https://github.com/stashapp/stash/pull/4022
