### ISSUE TITLE
[Feature] Generic key / value store for plugin config

### ISSUE THREAD

**Issue by Tweeticoats** [stashapp/stash#2207]
**Is your feature request related to a problem? Please describe.**
For plugin config it would be useful to have a generic key / value store configuration needed for plugins.
If there was a graphql api for  get_config(key) and update_config(key,value)

Ideally you could store a json object as the value allowing you to store as many options as needed for the scraper or plugin.

**Describe the solution you'd like**
A table in the database to store this config:
config (key varchar(255) primary key, value text)

A put config method in graphql:
mutation update_config(key,value)

A get config method:
query get_config(key)

**Describe alternatives you've considered**
Storing this config in a studio.
You can easily create a new studio if it does not exist and store all the config in the description field as that is a text field.

**Comment by Maista6969** [comment]
Solved by #4143
