### ISSUE TITLE
Human Intelligence Task  Notification System and tagging Queue

### ISSUE THREAD

**Issue by Leopere** [stashapp/stash#221]
When the app is going to perform something potentially destructive to the original stored files, including meta-tagging and file pathing and all of that, we should request the approval of the user.  This would warrant the creation of a few things.

## Notifications
Administrators should have a notification queue somewhere, that can be used for the app to communicate with the Admin or Users. If we ever differentiate that could contain information about Human Intelligence Tasks that can't be done or should not be done automagically at least in early versions of Stash. It would also be bad to do things without the user knowing such notifications.

## System Tagging Queue
It would be prudent to scan the scenes in the background passively at a rate that is potentially aware of the load being put on the Stash-Box API as not to overload it and politely request any additional metadata on releases. If the data has a certain confidence level or above about the tag information it should be brought to the attention of the end-user/admin.

Perhaps this is either a premium-ish feature where the user has either submitted valid data recently to the API or has a supporter subscription.

Associated PR #204

**Comment by kermieisinthehouse** [comment]
I think this has been covered - file deletion has confirmation modals, and tasks are now queuable.
