### ISSUE TITLE
Organizr and localhost version Broken by CSP hardening

### ISSUE THREAD

**Issue by tamndhzd** [stashapp/stash#2211]
This issue was introduced by the following change: https://github.com/stashapp/stash/pull/2108/files

* setting X-Frame-Options to DENY prevents displaying stash in an iframe, hence it breaks Organizr completely. There should be a user override here in `.stash/config.yml`
* The new Content Security Policy directives seem to prevent images and media from loading when viewed from http://localhost:PORT rather than through an nginx reverse proxy.
* External theming via nginx subfiltering is now broken, again due to CSP changes.

**Comment by kermieisinthehouse** [comment]
>     * setting X-Frame-Options to DENY prevents displaying stash in an iframe, hence it breaks Organizr completely. There should be a user override here in `.stash/config.yml`

I'll probably just remove this completely. A "real" site would send this, but for something self hosted it's probably more of a pain 

>     * The new Content Security Policy directives seem to prevent images and media from loading when viewed from http://localhost:PORT rather than through an nginx reverse proxy.

This is fully intended behavior. You should serve all of your content from the same origin. Removing this would defeat the security guarantees of the CSP.

>     * External theming via nginx subfiltering is now broken, again due to CSP changes.

You can use the built-in custom CSS mechanism for theming, or if your custom themes are extensive, you can load the files into `.stash/custom` and have nginx rewrite to those paths, as they will be served from Stash directly
