### ISSUE TITLE
[Feature] Allow Images to have Date, Details and URL

### ISSUE THREAD

**Issue by ALonelyJuicebox** [stashapp/stash#2213]
Much like Scenes and Galleries, it would be nice to be able to provide date, details and an URL to an image.
This would bring images in line with the other major objects in Stash (Scenes for example)

Useful for associating metadata from various services where there are available details about a picture outside of just its title.

This would require a UI change (to align the edit and info tabs with the details form), modifications to the lightbox, as well as new columns `date`, `details` and `URL` to the SQLite database for storing the metadata.

Thanks! 🙏🏾

**Comment by QxxxGit** [comment]
+1 

This has been requested multiple times in other places as well (but in parts, whereas this requests all) #1218 #1443

There are several usages for images having extra metadata (url, date, details):

* Calculation of performer ages at time of specified image date.
* Artwork (i.e. h*ntai) with a source to the author, extra details/comments, and date of creation.
* Sometimes performers will use Twitter to post one image with some text. It's not great to make a gallery for just one or two images. Instead, allowing end-users to specify the tweet date, text, and link to tweet would be beneficial for the individual images. 

On that note, if these fields are adding, I recommend adding these fields to the bulk editing dialog box when selecting multiple images.

**Comment by DogmaDragon** [comment]
Partially implemented. `date` and `URL` support were added in https://github.com/stashapp/stash/pull/3015.
