### ISSUE TITLE
[Bug Report] Performer Batch Update does not pull all/ "the right" data from StashDB

### ISSUE THREAD

**Issue by toby666123** [stashapp/stash#2214]
**Describe the bug**
When running a performer batch update from StashDB
- birthday is not being pulled => age does not show up
- country is being pulled as abbreviation (e.g. "US") instead of full name (e.g. "United States") => flag icon does not show uo

**To Reproduce**
Run Performer batch update on new performer entry and scrape same performer afterwards from StashDB => all/correct fields only available after scraping

**Expected behavior**
Update birthday and pull full country name

**Stash Version: (from Settings -> About):**
V0.12

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20
 - OS: Android 11
 - Browser: Chrome 97

**Comment by bnkai** [comment]
- #2189 was merged into develop and fixes the birthday issue
- for the country there is an open PR #1922  that could be related and an already open issue #1567

**Comment by toby666123** [comment]
For birthday:
Great, thanks for the info! :)

For country:
You are right, it is 100% the same as https://github.com/stashapp/stash/issues/1567
The ISO topic is something separate imho
