### ISSUE TITLE
[Feature] Image selection in Performer scraping from StashDB

### ISSUE THREAD

**Issue by toby666123** [stashapp/stash#2215]
**Describe the solution you'd like**
When scraping a performer from StashDB using "Scrape with..." it offers me the first (out of several) images as new performer image. Instead I would like to select which of the images to take over. E.g. via left arrow / right arrow buttons.

The solution already exists for Scene Search / Scene Scraping:
If I create a new performer during Scene Scraping (of one individual scene) by clicking on "create" it offers me the option to select performer image from StashDBs several images. That is exactly what I also would like to see in performer scraping.

**Comment by MC1R-13** [comment]
It also works on the main performer page, if you change to tagger view (as opposed to list, etc).

**Comment by toby666123** [comment]
Thanks for the hint! At least a workaround to retrieve the different StashDB images after a Performer has been created. 
Nevertheless, I think a direct integration into the Performer Edit Dialog / "Scrape with" option would be great and more usable.

**Comment by Maista6969** [comment]
This can be closed
