### ISSUE TITLE
[Bug Report] Unexpected TOken S 

### ISSUE THREAD

**Issue by mcangeli** [stashapp/stash#2216]
![image](https://user-images.githubusercontent.com/6456272/148625268-44d1f8c9-adcc-4b53-8325-60cc4157403e.png)

Unexpected Token S in JSON at position 0

**To Reproduce**
This is on a linux server.
Removed previous app and directories.
Started stash-linux
Launched web browser (this is on a hosted server offsite)
Ran configuration
When site loads in to the settings page I get this error on the library and other pages.
I cannot set the username and password.

**Comment by kermieisinthehouse** [comment]
Try a ctrl-shift-R to clear your local state. Is this behind a reverse proxy?

I suspect you might be hitting https://github.com/stashapp/stash/wiki/Authentication-Required-When-Accessing-Stash-From-the-Internet as that message begins with an 'S'

**Comment by mcangeli** [comment]
When I hit CTRL-Shift-R I get the "Stash is exposed to the public internet without authentication, and is not serving any more content to protect your privacy. More information and fixes are available at https://github.com/stashapp/stash/wiki/Authentication-Required-When-Accessing-Stash-From-the-Internet"
Message and cannot setup the authentication.

Its on a webserver (my torrent server) in germany and I am on my couch in Atlanta.
Can I add authentication via the config.yml file in order to access the settings?

**Comment by kermieisinthehouse** [comment]
Shutdown Stash, edit config.yml and add:

```
password: $2a$04$DYM.l0Li6J9k6akFqRxl/.nsSWO3hnpfZtqF2cYLxXyaxQjS.JXo6
username: user
```

The password will be 'password', make sure to change it. You'll need to remove `security_tripwire_accessed_from_public_internet`.

**Comment by mcangeli** [comment]
@kermieisinthehouse that was exactly what I needed! Thanks!
