### ISSUE TITLE
Native HEVC (h265) in Safari

### ISSUE THREAD

**Issue by throwawaynate** [stashapp/stash#2226]
Currently, Safari supports native HEVC video see [this](https://caniuse.com/hevc).  The majority of my library is h265 and it would be great to view it in Stash without needing to transcode the videos if I am using Safari on my iPad or macbook.  

This was discussed before in #31 where the decision was made to NOT support HEVC due to lack of browser support.  I would love to revisit that decision if possible for Safari users.

**Comment by bnkai** [comment]
If your browser supports the media file natively it will be played natively. I have a lot of hevc files and using a Chromuium allcodecs+ build (in linux)  they all play directly in stash without transcoding.
Are you sure that your media files are in the correct container ( afaik safari doesnt support mkv only mp4 for hevc) and they dont include any unsupported audio codec?
You could try  a chromium build from here for your mb <https://github.com/macchrome/macstable/releases>, one with  the `HEVC playback requires CLI flag: --enable-clear-hevc-for-testing` in the release description

The referenced issue #31 isn't relevant anymore as stash's code has changed a lot.
