### ISSUE TITLE
[Bug] filename parser will not complete "remove" updates 

### ISSUE THREAD

**Issue by Ch00nassid** [stashapp/stash#224]
![image](https://user-images.githubusercontent.com/57732969/69585960-c312d300-0fa6-11ea-8f40-f2deaac2c255.png)

(pre-req):
- filename pattern used: {performer}

Steps 
1. click the "X" on each of the performers i want to remove from the scene
2. click the blue checkbox next to the scene
3. click apply
4. Visit scene to ensure proper update

visit the appropriate scene and all performers still remain attached to the scene.

**Comment by WithoutPants** [comment]
Thanks for the report. In fact, it appears that none of the performer/studio/tag updating functionality was working at all.
