### ISSUE TITLE
[Feature] reverse proxy with apache2

### ISSUE THREAD

**Issue by rotwange** [stashapp/stash#2242]
Is it possible to use reverse proxy with apache2? I have several reverse proxies set up on my server for different services, but Stash doesn't seem to work like the rest of them. Can we get reverse proxies working for Apache2?

**Comment by kermieisinthehouse** [comment]
Can you post the configuration you're using? And can you try the development branch? Some bugs were fixed. Make sure you're passing the Host header transparently, using `ProxyPreserveHost on`

**Comment by rotwange** [comment]
Well right now I am stuck at the simplest: 
`   # Stash ProxyPass

    ProxyPass "/stash" "http://127.0.0.1:9999/stash"
    ProxyPassReverse "/stash" "http://127.0.0.1:9999/stash"
`
And I can't get this to be recognized. It just redirects to the front page of the base URL.

**Comment by rotwange** [comment]
That worked after a slight modification. Here is the final config: 

`    ProxyPass "/stash" "http://127.0.0.1:9999"
    ProxyPassReverse "/stash" "http://127.0.0.1:9999"
    <Location "/stash/">
      RequestHeader setIfEmpty X-Forwarded-Prefix "/stash"
      ProxyPreserveHost on
    </Location>
`

As I have several other proxies running, each one of them seems to want to either preserve or not preserve the host, so having location-specific directives works out better for me. Also it didn't work correctly with the trailing slashes after the port number, but it did after I removed them.

Thanks for pointing me in the right direction. Trying to convert nginx configs going on  first principles wasn't working out for me.
