### ISSUE TITLE
[Bug Report] Can't disable Custom CSS

### ISSUE THREAD

**Issue by cafuneandchill** [stashapp/stash#2249]
**Describe the bug**
Disabling Custom CSS doesn't do anything.

**To Reproduce**
1. Add [this CSS snippet](https://github.com/stashapp/stash/wiki/Custom-CSS-snippets#blur-nsfw-images) as Custom CSS
2. Click 'Custom CSS enabled'
3. Reboot the PC
4. Run stash
5. Click 'Custom CSS enabled' (to disable it)

**Expected behavior**
CSS should be disabled and the content shouldn't be blurred.

**Stash Version: (from Settings -> About):** v0.12.0

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2 x86_64
 - Browser: Firefox
 - Version: 95.0.1 (64-bit)

**Additional context**
Rebooting the PC after enabling CSS is required, since Custom CSS doesn't enable after reloading the page, as well.

**Comment by kermieisinthehouse** [comment]
This sounds like a browser caching issue. You shouldn't have to reboot your PC at all. Have you tried doing a hard refresh, ctrl-shift-R?

**Comment by cafuneandchill** [comment]
Nope, haven't tried.

I launched stash again today, though, and the problem seems to have resolved itself. I guess it really was a cache issue.
