### ISSUE TITLE
[Feature] Treat webp files as animation rather than static, like gifs

### ISSUE THREAD

**Issue by xarathos517** [stashapp/stash#2266]
**Is your feature request related to a problem? Please describe.**
I've begun the process of converting my animated gif library to webp format. The space savings are massive. There's just one downside; Stash appears to generate .jpg files as thumbnails for them, so in the gallery wall view they appear static. Once viewed they animate as expected.

**Describe the solution you'd like**
Ideally the animations would be handled the same way animated gifs are. I assume this is some kind of exception buried somewhere in the thumbnail code? Something that tells stash not to generate thumbnails, and to pass the gif directly instead? I'd like this available for webp as well.

**Describe alternatives you've considered**
I suppose some difficulty might arise if a gallery also includes static webp files and they might need to be handled separately, or ignored. There might be unintended side effects I haven't considered. Maybe a toggle for the format instead, or a white/blacklist for files that shouldn't be thumbnailed, if it can't be detected automatically?

**Comment by WithoutPants** [comment]
This should be addressed in the latest dev build. Note that this does not address already created thumbnail images, which will need to be deleted manually.
