### ISSUE TITLE
DVD Section?

### ISSUE THREAD

**Issue by Cutters1982** [stashapp/stash#227]
Hi there

Apologies if this has already been covered under another issue, I had a bit of a search and couldnt find it discussed.

I wanted to request a DVD section be added to Stash to be alongside the Scenes section, but with obvious differences where you can upload the front & back cover images of the DVD, and add the individual scenes under the DVD entry with subsequent performer tagging and scene infos. So you would left-click on the DVD in the list, and it would show all of the scenes of that DVD as if it were the Scenes section

The app is coming along really nicely, very excited to see what will come in the next UI release!

Cheers

**Comment by binarygeek119** [comment]
i would also like to add with cover uploads disc image upload this could tie into the metadata where it could upload missing images for the ui part i like to see  in dvd broswer part just the front image when hovering over dvd it inlarges and then after X secs fades to back cover

in the dvd movie part (milfs 3) the front and back cover show side by side with disc in middle
with the disc spinning
![poc3](https://user-images.githubusercontent.com/47513721/69692035-76a6c080-1096-11ea-9a35-9fbbb262b5e4.gif)
![poc2](https://user-images.githubusercontent.com/47513721/69692037-773f5700-1096-11ea-821f-78c9b67f1e34.jpg)
![poc1](https://user-images.githubusercontent.com/47513721/69692038-773f5700-1096-11ea-87e2-1f675b097b01.jpg)

**Comment by Leopere** [comment]
If we do a DVD section could we aim for something that shows how complete the data is?  Like includes the main video content or also includes alternative scene data (dvd extras) and whatnot.

**Comment by WithoutPants** [comment]
#338 addresses this and is now merged, so closing. If there are outstanding features, please raise a separate issue.
