### ISSUE TITLE
[Feature] Store all blob binaries (images) outside of Stash's SQLite database

### ISSUE THREAD

**Issue by ALonelyJuicebox** [stashapp/stash#2271]
As this project scales and as we add more and more performers/studios/etc to our databases, the database size of our Stash databases is becoming a bit bloated with these blobs.

Given the size of the images, there's no performance gain in storing the images in the database itself over storing them on the filesystem.

I'm of the opinion that we should migrate towards storing these images in the `/generated/ ` folder instead, only storing a reference to the file path in the database itself. 

Thanks!

**Comment by InfiniteTF** [comment]
I don't disagree. However, we would need some way to export images. Unlike content in `generated`, the images in the db can't be regenereated on demand, so they need to be separated from generated content.

**Comment by deezero** [comment]
Which would be a good option for that ?

- create a new structure (`/var/lib/stash/database`) with subfolders like `generated` so it's another top level storage.
  - maybe then put the sqlite file in the root of that (`/var/lib/stash/database/stash-go.sqlite`).
- put it in the existing config directory (`{CONF_DIR}/static`) again with generated style sub directories.

it could default to `{CONF_DIR}/static` or similar but be configurable.

**Comment by WithoutPants** [comment]
I'd introduce a new location setting for image storage - defaulting to `images`. The folder would be sub-divided based on object types (`performer`, `scene`, etc).

**Comment by deezero** [comment]
I was wondering about segmenting the path, so something like `images/performer/6/3/b/63b84b824d1835a59d2a7e514daa9109.png`

stash doesn't usually get a performance hit from the mega directories (like in generated) since it doesn't list them, but doing backups is slower because of it, since generated is considered more like a cache you wouldn't normally back it up, but this would be first class data so segmented directories could be helpful for backups.

**Comment by WithoutPants** [comment]
For storing images for objects (scene covers, performer images etc), I think dividing by id would be better. Segmenting the path would be suitable for objects that we see large numbers of, such as scenes, galleries and images.

**Comment by WithoutPants** [comment]
This will allow setting gallery covers without relying on the current `cover.jpg` detection.
