### ISSUE TITLE
Stash.app cannot find config file on MacOS

### ISSUE THREAD

**Issue by shanty-chits** [stashapp/stash#2284]
**Describe the bug**
On Mac, opening the latest development Stash.app opens the new setup screen no matter what. Console logs show current working directory as `<private>` even though the app is located with the library on a removable volume. Granting Stash.app full disk permissions does not fix the issue. If the setup wizard is completed, it ends with `error creating config file: open config.yml: read-only file system`. If `-c` or `--config` flags are passed like `open Stash.app --args -c [path/to/config]`, the app does not open at all. If a symlink to the config file is placed in $HOME/.config/stash, the new setup screen still opens.

**To Reproduce**
Open Stash

**Stash Version: (from Settings -> About):**
v0.12.0-40-gc857e301

**Desktop (please complete the following information):**
 - OS: MacOS 12.2 Monterey

**Comment by kermieisinthehouse** [comment]
Hi, thanks for the report. We'll get this fixed before this hits stable.

Out of curiosity, when you filled out the setup to create a new stash folder, which option did you choose? If you put it in your home folder, does it work?

Is this a fresh Monterrey install, or did you upgrade an existing system to it?

**Comment by shanty-chits** [comment]
> Out of curiosity, when you filled out the setup to create a new stash folder, which option did you choose? If you put it in your home folder, does it work?

Selecting "current working directory" fails with the indicated error. Selecting the $HOME option hangs and the program has to be force-quit. Moving the app to the home folder doesn't seem to have any effect.
 
> Is this a fresh Monterrey install, or did you upgrade an existing system to it?

Upgrade from an existing system.

**Comment by kermieisinthehouse** [comment]
Alright, I think I've got a handle on what's causing this. I need special handling on MacOS for "current directory".

**Comment by kermieisinthehouse** [comment]
Using `open ./Downloads/Stash.app --args -c ~/my_custom_path/stash/config.yml` should be a workaround at the moment.

**Comment by MC1R-13** [comment]
This must be Monterey-specific. The latest Big Sur (11.6.4) has no such issue.

**Comment by newadventure079** [comment]
I'm on macOS 12.2.1 and am seeing this too.  

`open /Applications/stash/Stash.app/ --args -c /Applications/stash/config.yml` doesn't work.  The command completes and nothing happens

**Comment by newadventure079** [comment]
I finally got this to work.  Not with the `-c` arg, but I left all that out and just ran `open Stash.app` and moved my config file from where I had it before to `~/.stash` so it would pick it up.  I had to massage my config file because it was for version `.13` and this .app file was build against `.12`.

I found a couple of bugs specific for macOS and I'll report those separately

**Comment by DingDongSoLong4** [comment]
With the new `Stash.app` from #4153, `open Stash.app --args -c <PATH_TO_CONFIG_YML>` now works (tested on macOS 14.1.1).

An `.app` cannot reliably access the current directory, so if you use the `.app` you either need to move your `config.yml` to `$HOME/.stash/config.yml` or use the `open` command above to specify its location using the `-c` flag.
