### ISSUE TITLE
Stash.app for MacOS can't find cloudscraper

### ISSUE THREAD

**Issue by MC1R-13** [stashapp/stash#2289]
The new app version for MacOS can no longer find cloudscraper, but it still works with the previous version.

Using the IAFD scraper (apparently the only one I have that uses cloudscraper) just gives an error:

> ModuleNotFoundError: No module named 'cloudscraper'

when it's definitely installed.

Running the non-app version works as it should.

Stash Version: (from Settings -> About):
v0.12.0-40-gc857e301

Desktop (please complete the following information):
 - OS: Mac OS Big Sur 11.6.3 (Intel)
 - Browser: Safari
 - Version: 15.3

**Comment by MC1R-13** [comment]
I downloaded v0.12.0-41-gcee36cb1 and now it's working.

**Comment by LukeSal88** [comment]
Hmmm...I still seem to be getting the same error when using the .app version.

**Comment by MC1R-13** [comment]
I've since learned it was being blocked by the built-in firewall.
Try running this in your Terminal:

```
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /Applications/Stash.app
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp /Applications/Stash.app
```
The first may not be necessary, if it's already been added to the firewall.

**Comment by LukeSal88** [comment]
Sadly, I've already added it to the firewall, and tried with the firewall disabled. :-/

**Comment by MC1R-13** [comment]
Hmm, I just tested it a few minutes ago and it worked. Make sure you completely exit stash first.
Try:

```
killall "stash"
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp /Applications/Stash.app
```

**Comment by LukeSal88** [comment]
I finally got it working! In the end, I had to run the following:

>  xattr -dr com.apple.quarantine Stash.app

It seems MacOS had quarantined it for some reason.

**Comment by MC1R-13** [comment]
Oh, yeah. I think it quarantines everything extracted from a .zip file.
