### ISSUE TITLE
[Bug Report] Python Scrapers and plugins broken

### ISSUE THREAD

**Issue by DefinitelyNotSpicy** [stashapp/stash#2290]
**Describe the bug**  
Whenever I try to use something in Stash that starts a python script it opens about 5 or 6 Windows terminal windows open and close one after another except for the last one which stays open. This problem started to occur after the Desktop integration of stash. It seems the open scraper window is waiting on the fragment input. If I manually paste the fragment into the open window and CTRL+Z the Scraper continues but doesn't return the data to stash.

**To Reproduce**

1. Open a performer edit view
2. Click on "Scrape with"
3. Choose a python scraper like IAFD
4. See Terminal windows open and close until one stays open and stash keeps showing the loading spinner.
5. Close the Terminal Window to see error

**Expected behavior**
There should be one or less terminal windows opening and the scraper should actually finish. 

**Screenshots**  
Terminal windows with keep open configured:  
![image](https://user-images.githubusercontent.com/96064475/152633719-9842ad8b-2e59-4aab-b432-1557c54aff1e.png)

Process tree when waiting for input:  
![image](https://user-images.githubusercontent.com/96064475/152634076-6eb16aef-39e4-45f5-97e3-f82714279785.png)

**Stash Version: (from Settings -> About):** v0.12.0-40-gc857e301

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 97.0b9

**Additional context**  
This error occurs with regdardless of how I start stash. I tried it with just doubleclicking, per Windows terminal (powershell) and with git bash.

I also tried using a different Python version (tested on 3.9.9, 3.10.1, 3.10.2). I'm using pyenv-win to manage my python version so maybe that's the problem but it did work before.

**Comment by kermieisinthehouse** [comment]
Somebody reported having this issue with python installed through scoop. How is python installed?

**Comment by DefinitelyNotSpicy** [comment]
Python is installed through [pyenv-win](https://pyenv-win.github.io/pyenv-win/) which does use a shim afaik.  
Is there a way to tell stash which python executable to use?

**Comment by kermieisinthehouse** [comment]
Not currently, but we might have to look at implementing that, since this probably affects more people.

**Comment by DefinitelyNotSpicy** [comment]
I just tested it with the full path to python in the IAFD.yml (C:\Users\<username>\.pyenv\pyenv-win\versions\3.10.2\python3.exe). That fixes it. The python in my PATH points to "C:\Users\<username>\.pyenv\pyenv-win\shims\python3". So it's some problem with the shim.

**Comment by kermieisinthehouse** [comment]
Gotcha. This might just be a recommendation to users to change their PATH or use a python install that we identify as 'good'

**Comment by DefinitelyNotSpicy** [comment]
If someone else has the same problem on Windows:

I'm now using this powershell two-liner to start stash so I don't have to change my global path:

```powershell
$env:Path = "C:\Users\<username>\.pyenv\pyenv-win\versions\3.10.2\;" + $env:Path
.\stash-win-nightly.exe
```
Just save as .ps1 and execute with powershell
