### ISSUE TITLE
[Bug Report] Version information is different by platform

### ISSUE THREAD

**Issue by kermieisinthehouse** [stashapp/stash#2292]
Reported by @Still34 
The version information is quoted on windows, and Linux seems to miss a new update being available (or windows reports it incorrectly, unclear)

Linux:
![unknown-2](https://user-images.githubusercontent.com/84814418/152661002-0aff0c10-5362-4fea-badb-b41299784d94.png)

Windows:
![unknown-1](https://user-images.githubusercontent.com/84814418/152661010-5bba3982-4b08-47ab-85ae-44b885f38f0b.png)

**Comment by WithoutPants** [comment]
Using the latest dev build, it's looking ok on Windows:

![image](https://user-images.githubusercontent.com/53250216/154202719-5345dc7c-9a3e-4c1d-8ca9-b7710033140c.png)

Which browser is this in?

**Comment by Still34** [comment]
Firefox, latest nightly, though it's been this way for me for a while.

**Comment by WithoutPants** [comment]
Tested using Firefox 97 on Windows. Same result as above.

**Comment by Still34** [comment]
![image](https://user-images.githubusercontent.com/5843208/154273017-bfd3ae3d-db1c-4b0d-948e-970684dcae37.png)
Repro on latest Edge and Firefox Nightly still. This probably means it's something on the server-side. The bin is built using `make generate; make ui; make build`.

**Comment by WithoutPants** [comment]
Please try to reproduce using the latest development binary. The build hash and time is generated and baked into the UI at build time.

```
export VITE_APP_DATE="2022-02-17 09:56:26" ; \        
export VITE_APP_GITHASH=7b1523cc ; \
export VITE_APP_STASH_VERSION=v0.12.0-25-g7b1523cc ; \
cd ui/v2.5 && yarn build
yarn run v1.22.15
$ vite build
```

That your seeing this suggests to me that it's something specific to your development environment.

**Comment by Still34** [comment]
Yup,  all normal in the build bin. I will have to investigate  what's going on at build time then

**Comment by Still34** [comment]
Chucking this down to something to do with the build of `make` I have on Windows; using MingW will probably fix it.

**Comment by WithoutPants** [comment]
Closing as environment issue.
