### ISSUE TITLE
[Feature] extend filtering options for galleries

### ISSUE THREAD

**Issue by tolotos68** [stashapp/stash#2300]
**Is your feature request related to a problem? Please describe.**
The process of linking a gallery to a scene might be quite straightforward, but it's quite annoying, that every gallery has to be picked by hand and scraped with "CopyFromScene". What makes things worse is that there's no way to filter those galleries which have already been linked to a scene, but don't have their metadata set.

**Describe the solution you'd like**

1. There's a filter "IsMissing". Please add a new filtering option „exits“
2. Add the field „scene“ in the filtering options.

This would allow a filter like "IsMissing tags AND Exists scene"

**Describe alternatives you've considered**
An alternative would be a "NOT" operator for any selected filter which would lead to the same result, but might even be more flexible.
The field „scene“ would still be needed.

**Additional context**
none

**Comment by DogmaDragon** [comment]
Already possible. Go to the Galleries tab and run these 2 filters.
![image](https://user-images.githubusercontent.com/103123951/220922608-3db91253-22ec-4ea2-a077-94b67538442e.png)
