### ISSUE TITLE
[Bug Report] Moving Stash from Synology GUI docker to docker-compose file; existing config file prevents "start" via docker-compose

### ISSUE THREAD

**Issue by eggplantsplz** [stashapp/stash#2306]
**Describe the bug**
Moving Stash from Synology GUI Docker to docker-compose file. Everything is "working" but I get this one issue on container start preventing it from booting. Must have something to do with the config file:

```
using config file: /root/.stash/config.yml   
panic: error initializing configuration: missing the following mandatory settings: generated
goroutine 1 [running]:
github.com/stashapp/stash/pkg/manager.Initialize.func1()
	github.com/stashapp/stash/pkg/manager/manager.go:99 +0x5a8
sync.(*Once).doSlow(0xc0000001a0, 0x441245)
	sync/once.go:68 +0xd2
sync.(*Once).Do(...)
	sync/once.go:59
github.com/stashapp/stash/pkg/manager.Initialize()
	github.com/stashapp/stash/pkg/manager/manager.go:64 +0x31
main.main()
	github.com/stashapp/stash/main.go:26 +0x2e
```

Of note - if I archive the existing config file in /root/.stash/, Stash starts just fine but I will have to create a new config file. Unsure if tihs new config file will be able to connect seamlessly with my existing database, generated content, metadata (like 600gb+... would like to preserve if possible).

**Stash Version: (from Settings -> About):**
LATEST

**Additional context**

**Comment by kermieisinthehouse** [comment]
Have you changed the container's path to generated, away from what it had previously expected? Have you changed the value of the STASH_GENERATED env var recently? 

You should figure out what path you are presenting your generated volume as container-side, and pass that in STASH_GENERATED.

For example:
```
environment:
   - STASH_GENERATED=/generated/
   - ...
  volumes:
   - ...
   - stash-generated:/generated
```

**Comment by eggplantsplz** [comment]
ugh lol. so stupid. forgot the environment split is with a "=", had colons instead. works! thanks.
