### ISSUE TITLE
[Bug Report] Desktop Integration for Windows System Tray Icon

### ISSUE THREAD

**Issue by QxxxGit** [stashapp/stash#2307]
After quitting Stash on the Desktop Integration for Windows, the icon will not disappear from the system tray until hovered. I've talked with @kermieisinthehouse who dev'd the integration and his research suggested it's a common Windows-related issue. Developers typically hide the icon on shutdown manually to get around this.

Since it's such a small issue and the app does actually shutdown, I don't think it's necessary to hold up the integration or v0.13's release because of this.

**Comment by UncleRoger33** [comment]
This is a bug from year **2005** and Microsoft tagged it as `Won't Fix` 😭


![Microsoft_Connect](https://user-images.githubusercontent.com/66418211/154013992-b838b132-621c-4aad-b2bc-5e1e2db3b904.png)

That page is long gone, but you can read the full discussion via Internet Archive's Wayback Machine --> https://web.archive.org/web/20130916003004/http://connect.microsoft.com/VisualStudio/feedback/details/98317/notify-icon-doesnt-go-away-when-your-program-closes

@kermieisinthehouse I've found some workarounds (7-8 years old) from my ancient bookmarks based on "Microsoft Mark - the program manager"s suggestion, so i don't know these'll help or not. 

From [stackoverflow](https://stackoverflow.com/questions/10980029/notify-icon-stays-in-system-tray-on-application-close):
```
private void frmMain_FormClosed(object sender, FormClosedEventArgs e)
{
    ntfyIcon.Icon = null;
    ntfyIcon.Dispose();
    System.Windows.Forms.Application.DoEvents();
}
```  
Same discussion and some suggestions on [Windows Dev Center](https://social.msdn.microsoft.com/Forums/windows/en-US/73c33537-c5d7-4cff-9faa-0a6a0d4a65b4/notifyicon-icon-still-visible-after-closing-form) and one from [Visual Studio forum](https://social.msdn.microsoft.com/Forums/vstudio/en-US/7aa5ed01-8fdc-41d8-83e0-8368b25bc5bc/system-tray-icon-does-not-disappear):

> The workaround is to explicitly call `NotifyIcon.Hide()` in the `FormClosing` event.

**Comment by WithoutPants** [comment]
@kermieisinthehouse I have an apparent solution to this, but it requires a modification to the `systray` library.

In `systray`, `systray_windows.go`, in `quit()`:
```
func quit() {
	const (
		WM_ENDSESSION = 0x0016
		WM_CLOSE      = 0x0010
	)

	pPostMessage.Call(
		uintptr(wt.window),
		WM_ENDSESSION,
		0,
		0,
	)

	pPostMessage.Call(
		uintptr(wt.window),
		WM_CLOSE,
		0,
		0,
	)
}
```

In the stash code: `systray_nonlinux.go`, in `systrayInitialize`:
```
			case <-quitStashButton.ClickedCh:
				systray.Quit()
				shutdownHandler.Shutdown(0)
			}
```

This appeared to fix the issue when selecting `quit` from the dropdown menu. It won't remove the icon if stash exits using another method.
