### ISSUE TITLE
[Feature] Allow Image/Gallery Lightbox settings to persist

### ISSUE THREAD

**Issue by ALonelyJuicebox** [stashapp/stash#2311]
When viewing certain images in a slideshow (Manga for example), it's ideal to set up the lightbox with certain settings.
Unfortunately, there's no way to have these settings persist, forcing the user to set up those settings every time you click into a new slideshow. Not ideal! 🙂

This feature request is to add a checkbox form option to have the settings persist.

**Current State:**
![currentstate](https://user-images.githubusercontent.com/76471868/153562585-67cac341-77ff-4e20-b3f9-487bb9a252ff.JPG)

**Requested State:**
![new_](https://user-images.githubusercontent.com/76471868/153562599-36c44158-f28a-41a9-b39d-5cef0bf0d2a9.JPG)

Thanks!

**Comment by WithoutPants** [comment]
$50 bounty placed.
