### ISSUE TITLE
[Bug Report] Inconsistent details panels

### ISSUE THREAD

**Issue by QxxxGit** [stashapp/stash#2316]
So I just realized the details panel is inconsistent across the app and I think there's room for improvement.

* Scenes -> the metadata (details, tags, dates, ratings, etc.) is below the performers. In other areas (galleries, images) this is reversed.
* Tags on galleries and images are below the metadata whereas they're above on scenes.

I don't have any instances of scenes with many performers, but it seems the metadata would be pushed down requiring users to scroll to see it. IMO this should be moved to the top to be more in-line with other areas of the app anyways.

Maybe a parent react component to keep this metadata in order would help the 2nd bullet point? i.e. `<DetailsMetadata />` would contain the dates, tags, and rating in a consistent order across the app.

**Comment by DampToast** [comment]
For scenes, you are saying the metadata is below the performers?  I looked at a scene with 1 performer and the metadata was above the performer and also a scene with 11 performers and it was still above.  If you're seeing the metadata below the performers, what browser and screen resolution are you using?  Maybe a screenshot would help understand?

I won't have any galleries or images loaded until tomorrow probably but will see what I can see then for what you're describing.

**Comment by QxxxGit** [comment]
Oh gosh, big brain moment for me. I forgot about CSS changes I added from someone else. Apologies -- closing!
