### ISSUE TITLE
[RFC] Can't access Stash from Nginx reverse proxy

### ISSUE THREAD

**Issue by DarkFighterLuke** [stashapp/stash#2333]
### Scope
I want to access Stash from my Nginx reverse proxy.
Reading Stash logs I saw that access from an unauthorized proxy was blocked, but after adding it to the whitelist, all I get is this:
![immagine](https://user-images.githubusercontent.com/31162436/154769172-1c4fda44-cb0c-4a95-96a8-7a70039fcd88.png)

## Reference Reading
This is what I followed https://github.com/stashapp/stash/wiki/Reverse-proxy.

**Comment by DarkFighterLuke** [comment]
I noticed that the problem is here:
![immagine](https://user-images.githubusercontent.com/31162436/154805720-7de07aec-ec8b-4300-b1c4-2fd21d35c6fc.png)

Stash continues searching resources at the root `/` and not at the `/multimedia/porn` endpoint.
Is there something I am missing?

**Comment by DarkFighterLuke** [comment]
I (partially) solved using X-Forwarded-Prefix proxy header and setting it to my custom location `/multimedia/porn`.
I can now reach the stash ui, but I am stuck at the circle progress indicator saying "Loading"...

**Comment by kermieisinthehouse** [comment]
This is a known working nginx config:

```
location ^~ /stash {
            set $upstream_app 127.0.0.1;
            set $upstream_port 9999;
            set $upstream_proto http;
            proxy_pass $upstream_proto://$upstream_app:$upstream_port;
            proxy_set_header X-Forwarded-Prefix /stash;
            proxy_set_header Host $http_host;
            rewrite ^/stash-test/(.*)$ /$1 break;
        }
```

**Comment by DarkFighterLuke** [comment]
Thank you, you solved my problem.

**Comment by DarkFighterLuke** [comment]
> This is a known working nginx config:
> 
> ```
> location ^~ /stash {
>             set $upstream_app 127.0.0.1;
>             set $upstream_port 9999;
>             set $upstream_proto http;
>             proxy_pass $upstream_proto://$upstream_app:$upstream_port;
>             proxy_set_header X-Forwarded-Prefix /stash;
>             proxy_set_header Host $http_host;
>             rewrite ^/stash-test/(.*)$ /$1 break;
>         }
> ```

I noticed that I was unable to play videos due to a stream error.
The problem was on Content-Security-Policy and I solved adding `proxy_hide_header Content-Security-Policy` to your configuration.
