### ISSUE TITLE
[Bug Report] Database schema version does not match required schema version after Update/Pull

### ISSUE THREAD

**Issue by hendrikma** [stashapp/stash#2338]
**Describe the bug**
On Synology NAS got 0.10. running since several months. Today I considered updating via the Synology GUI to the latest version. Now I geht this error: _Database schema version 28 does not match required schema version 29. _ Stash is not showing up anymore in my browser. If i switch back to 0.10.0 everything is working fine. How does the migration-process work? Did not find anything in the Wiki :/
I have got no reverse proxy or whatsoever installed.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem please ensure that your screenshots are SFW or at least appropriately censored.

**Stash Version: (from Settings -> About):**
Version:	v0.10.0
Hash:	f4b78387
Created:	2021-10-24 21:51:44

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chromium/Brave
 - Version: 1.35.100 Chromium: 98.0.4758.87
 
**Log:**

> INFO[2022-02-21 15:41:03] using config file: /root/.stash/config.yml   
WARN[2022-02-21 15:41:03] could not empty Tmp directory: open /generated/tmp: no such file or directory 
WARN[2022-02-21 15:41:03] Database schema version 28 does not match required schema version 29. 
stash version: v0.12.0 (fb864a6e - Official Build) - 2021-12-28 23:26:19
INFO[2022-02-21 15:41:04] Version: (fb864a6e) is already the latest released. 
INFO[2022-02-21 15:41:04] stash is listening on 0.0.0.0:9999           

How do i troubleshoot this problem?

**Comment by hendrikma** [comment]
As I wrote: Stash is not showing up in the browser :/ So there is no option to migrate

**Comment by InfiniteTF** [comment]
You're trying to access it on `http://<your-ip>:9999` and you just get a blank page?

**Comment by hendrikma** [comment]
I get a `ERR_CONNECTION_REFUSED`. So there is no response on that port

**Comment by WithoutPants** [comment]
This issue that you're having is unrelated to the migration. As noted above, the migration process occurs once you navigate to the webpage. The warning just indicates that the migration is necessary. 

The fact that it's logging `stash is listening on 0.0.0.0:9999` indicates that at least stash thinks it's initialised correctly, and it should be responding on port 9999. I don't know why it is not, nor why it is not responding only when 0.12 is installed.

**Comment by hendrikma** [comment]
I just fixed it by setting up the container in a docker-compose-file instead of setting it up via the Synology-GUI. Dont know where the error came from. Now the migration dialog showed up and the migration was succesfull.
