### ISSUE TITLE
[Security Enhancement] If the applications authentication/admin account is not established we should block any changes to the stash's source files.

### ISSUE THREAD

**Issue by Leopere** [stashapp/stash#234]
I wonder if we should consider disabling filesystem modifications via stash if the app is set to run without admin credentials.  I'm okay with people using Stash in a Passwordless mode, but we should consider locking it down by default and then allow people to "void their warranty" as they please if they please.

**Comment by WithoutPants** [comment]
I'm not really keen on dictating how end users use the system. If they want to be able to modify the file system without credentials, it's on their own heads. For the record, I don't have a password set on mine.

**Comment by Leopere** [comment]
I just mostly want to discourage other people from getting upset that we
let a random passerby gain direct access to someone's filesystem via Stash
and give them the ability to start deleting whatever more than anything.

**Comment by WithoutPants** [comment]
From discord:

> **all_hail_canada** Today at 11:49 AM
> also, just in relation to issue #234 - I run my instance behind a reverse proxy and only listening on localhost. As such, I wouldn't want to be locked down from FS modifications even without admin credentials

**Comment by Leopere** [comment]
I would agree with @all_hail_Canada on this one however the security flow should be such that you're almost immediately confronted with the choice to establish admin credentials and if they refuse the option to let them see a disclaimer that anyone with access to their app can make changes to their filesystem and even potentially destroy their entire collection with no easy path to reversion.

**Comment by WithoutPants** [comment]
With the public IP authentication restrictions implemented recently, I don't think this is necessary.
