### ISSUE TITLE
[RFC] Anonymous performers

### ISSUE THREAD

**Issue by WithoutPants** [stashapp/stash#235]
A large part of my collection is amateur stuff. For many of the videos there are no known names or details of the performers - and I wouldn't want to store that information anyway. However, without a performer entry, there is no way to find other scenes featuring the same performers. I'm looking for ideas about how to solve this.

Without a name, its not really reasonable to add these performers to the database, and in my opinion would pollute the performers list with anonymous names, so I don't think that idea is feasible.

One way might be to find other ways to link videos. For example, a collection or playlist might suffice to link videos together with a meaningful name. I've also toyed with the idea of managing direct links between scenes with some sort of description on each side of the relationship.

**Comment by echo6ix** [comment]
A. Perceptual identification with AI that displays "similar content" or "similar performers"

B. Your idea of linking through [playlists/collections](https://github.com/stashapp/stash/issues/115#issuecomment-559706125), which for some reason I've decided to call channels. It's basically like how foobar2000 or iTunes organizes playlists, with the ability of nesting them into folders, or with have "smart" playlists.

In your use-case, if your amateur content at least contains the amateur performer name or some kind of unique identifier specific to the file name/path of their scenes the concept of channels would work like this:

```
Channels
├── Amateurs {folder}
│   ├── Camgirl Amy {Smart playlist}
│   ├── Creampie Cathy {Smart playlist}
│   └── Hotwife Jane {Smart playlist}

```
Where,

`Amateurs` is the name of the folder the end-user has given any amateur content they want to organize.

`Camgirl Amy` is the name of a "smart playlist" given by the end-user which uses [query syntax](https://github.com/stashapp/stash/issues/185) to specify all of the amateur performers scenes based on unique filename matches common to all her scenes, such as `(filename CONTAINS "amateurs/*camgirl.amy*")`.

When Stash displays a scene or a scene card, it could also display the name of all the channels that it is associated with (where it currently displays the studio name).

**Comment by jeremymeyers** [comment]
Is this a thing that performer tags has addressed?

**Comment by WithoutPants** [comment]
I think Groups now covers this use-case to my satisfaction.
