### ISSUE TITLE
[Feature] Set as Performer Image from Tagged Image

### ISSUE THREAD

**Issue by Still34** [stashapp/stash#2354]
**Is your feature request related to a problem? Please describe.**
Setting performer image can be a bit tedious sometimes if the stash instance is not a local one, as the user would have to either copy, paste, then supply the URL to the image, or download the image before going to the performer edit page by hand.

**Describe the solution you'd like**
For images tagged with performer(s), add an option to set the image as the performer's cover art. When more than one performers are tagged, prompt the user to choose the performer to apply the front cover on.

**Describe alternatives you've considered**
None.

**Comment by slabking** [comment]
I think this is the same idea as #872.

**Comment by Still34** [comment]
Closing as dupe. Thanks.
