### ISSUE TITLE
[Bug Report] Generated thumbnail is only saved if clicking on "Save" afterwards

### ISSUE THREAD

**Issue by GammelSami** [stashapp/stash#2358]
**Describe the bug**

**To Reproduce**
1. Pause a scene
2. Click on 3 dots -> "Generate thumbnail from current"
3. Refresh page
4. See still the old thumbnail

**Expected behavior**
4. See new generated thumbnail

**Workaround**
1. Click "Generate thumbnail from current"
2. Open "Edit" tab
3. Change some text to enable "Save" button
4. Click "Save"

**Stash Version:**
v0.12.0

**Desktop:**
 - OS: Windows 10 21H2
 - Firefox 97.0.1

**Comment by Belleyy** [comment]
I try it, and it work. I am on the dev version (v0.12.0-76) so maybe it's already fixed.
Maybe you didn't wait too long to see the image ? 
I think FFMPEG is used to get the image so if you do something on your computer; it could lead to slower process ?

**Comment by GammelSami** [comment]
I waited like 8 seconds. When I use the workaround I can refresh 1 sec after I hit Save and it works.
Avg CPU usage on my server is 4%. A view months ago it worked like it should.
Hopefully arleady fixed. 🤞

**Comment by GammelSami** [comment]
Well, now it works as intendet.
Not reproducable anymore.
