### ISSUE TITLE
Use justified layout for wall

### ISSUE THREAD

**Issue by StashAppDev** [stashapp/stash#238]
#218 has been reverted by ddae45f2b4f0b7efc46c470b6c36481fd2c3de06

A couple issues with the original PR:

1) Broken zoom animations
2) Should be user configurable

**Comment by StashAppDev** [comment]
ca2680a86d5d39863ad9aba02d09708900a6b89a

I just made this change.  I think this addresses the issue while also making the changes in #218 unnecessary.  Thoughts?

**Comment by WithoutPants** [comment]
Perfect! I'm happy with this.

**Comment by StashAppDev** [comment]
Cool.  In that case I’ll close this issue.  Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
