### ISSUE TITLE
[Bug Report] Thumbnail in video player doesn't get replaced after saving a new thumbnail

### ISSUE THREAD

**Issue by kronkels** [stashapp/stash#2382]
**Describe the bug**
The thumbnail in the video player does not get updated once you press the 'Save' button after uploading / scraping a new thumbnail.

**To Reproduce**
1. Navigate to a scene.
2. Upload or use the scraper to supply the scene with a new thumbnail.
3. Press the 'Save' button
4. The new thumbnail will not be visible in the video player until you refresh the page.

**Expected behavior**
The new thumbnail should be visible in the video player after hitting the 'Save' button.

**Stash Version: 0.13**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Google Chrome
 - Version: 99

**Comment by kronkels** [comment]
Very similar issue: #2227

**Comment by DingDongSoLong4** [comment]
Fixed in #3120.
