### ISSUE TITLE
[Feature] Add the option to not update performer images to the batch updater

### ISSUE THREAD

**Issue by kronkels** [stashapp/stash#2383]
**Is your feature request related to a problem?**
All the performer images I have chosen are hand picked, but the batch updater simply replaces the images with the first image from the stash-box instance. I would like to receive all the updates, except the new image.

**Describe the solution you'd like**
Add a checkbox on the "Batch Update Performers" modal that appears after selecting "Refresh tagged performers" that will prevent the batch updater from replacing the performer images.

**Comment by SilentSpartan** [comment]
This already exists. While in the tagged view look for an option that says “Show Configuration”. After clicking that, click Edit Excluded Fields and choose from many options, including images.

**Comment by kronkels** [comment]
Oh great! I totally missed that. Maybe we could make it more noticable?

**Comment by feederbox826** [comment]
resolved
