### ISSUE TITLE
[Bug Report] starting stash from crontab does not find config.yml

### ISSUE THREAD

**Issue by mmaslen** [stashapp/stash#2385]
**Describe the bug**
starting stash from crontab or as a .service does not find config.yml despite being referred to explicitly via a startup .sh script

**To Reproduce**
1. stash.sh

#!/bin/bash
/root/stash/stash-linux --nobrowser --config ~/stash/config.yml

if i run this from linux command line then the application starts normally:

NFO[2022-03-14 11:22:23] using config file: /root/stash/config.yml    
stash version: v0.13.0-4-ge4d6d3b0 (e4d6d3b0 - Official Build) - 2022-03-10 22:43:38
INFO[2022-03-14 11:22:23] stash is listening on 0.0.0.0:9999           
INFO[2022-03-14 11:22:23] stash is running at http://localhost:9999/   
INFO[2022-03-14 11:22:23] Version: (e4d6d3b0) is already the latest released. 

if i run the same .sh from crontab -e or as .service, the config and metadata appears as a fresh install

**Expected behavior**

application starts normally using the referred to config.yml

**Stash Version: (from Settings -> About):**
v0.13.0-4-ge4d6d3b0

**Desktop (please complete the following information):**
 - Device: Linux
 - OS: Linux 5.13.19-4-pve

**Additional context**
Running the app in a LXC container on proxmox

**Comment by kermieisinthehouse** [comment]
It's probably the `~` character. This is your home folder, not necessarily systemd's or the cron user's home folder. Try using an absolute path.

**Comment by mmaslen** [comment]
It doesnt work with an absolute path either - the user i am in this container is 'root'

So I also tried this as my script:
/root/stash/stash-linux --nobrowser --config /root/stash/config.yml

same result as above

**Comment by mmaslen** [comment]
this is the log file 

22-03-15 06:14:03
Info    
Retrieved latest hash: e4d6d3b0
2022-03-15 06:13:49
Info    
Version: (e4d6d3b0) is already the latest released.
2022-03-15 06:13:48
Info    
stash is running at http://localhost:9999/
2022-03-15 06:13:48
Info    
stash is listening on 0.0.0.0:9999
2022-03-15 06:13:48
Warning 
could not empty Tmp directory: open generated/tmp: no such file or directory
2022-03-15 06:13:48
Warning 
could not empty Downloads directory: open generated/download_stage: no such file or directory
2022-03-15 06:13:48
Warning 
could not create directory for Interactive Heatmaps: mkdir generated/interactive_heatmaps: no such file or directory
2022-03-15 06:13:48
Warning 
could not create directory for Downloads: mkdir generated/download_stage: no such file or directory
2022-03-15 06:13:48
Warning 
could not create directory for Transcodes: mkdir generated/transcodes: no such file or directory
2022-03-15 06:13:48
Warning 
could not create directory for Markers: mkdir generated/markers: no such file or directory
2022-03-15 06:13:48
Warning 
could not create directory for VTT: mkdir generated/vtt: no such file or directory
2022-03-15 06:13:48
Warning 
could not create directory for Screenshots: mkdir generated/screenshots: no such file or directory
2022-03-15 06:13:48
Info    
using config file: /root/stash/config.yml

**Comment by mmaslen** [comment]
my 'generated' folder is in /root/stash

**Comment by bnkai** [comment]
Check the config.yml and make sure the path for `generated` is also absolute and not relative.

**Comment by mmaslen** [comment]
root@stash:~/stash# more config.yml |grep gen
  generate_task:
    scangenerateimagepreviews: false
    scangeneratephashes: false
    scangeneratepreviews: true
    scangeneratesprites: true
    scangeneratethumbnails: true
generated: generated

should I modify the last line?

**Comment by bnkai** [comment]
Yes `generated: /root/stash/generated` ?

**Comment by bnkai** [comment]
Open the `config.yml` and check all paths. All should be absolute including the `scrapers_path`, `downloads` ,`metadata` ....

**Comment by mmaslen** [comment]
checked - all working now - thank you all, appreciate your assistance
