### ISSUE TITLE
Continuous  Scroll for Gallery Images

### ISSUE THREAD

**Issue by Bobothetech** [stashapp/stash#2389]
When viewing image collection the only way to see the next/pervious image is by clicking the proper side of the screen. If you keep scrolling to the bottom of the page it will just keep going into nothing. The major issue is that if you click on the wrong part of the screen it backs you out of the picture view and you have to change the settings back to how you had it before.

It would be nice to have an option to scroll to the bottom of the image and then loop to the top of the next. Similar to CDisplayEX or the Webtoon mode in Komga. As well the ability to set this as the default view mode.

Being able to resume from the last page you were on would also be nice.

**Comment by ALonelyJuicebox** [comment]
Just a note-- your feature request for settings persistence can be correlated to an issue I have a bounty for #2311

**Comment by WithoutPants** [comment]
$20 bounty placed

**Comment by ghost** [comment]
Add option to disable this? I find it really annoying and confusing
