### ISSUE TITLE
[Feature] Extend Performer Gender Filter

### ISSUE THREAD

**Issue by stg-annon** [stashapp/stash#2394]
**Is your feature request related to a problem? Please describe.**
The current gender performer filter lacks things like `includes`, `excludes`, `is_null`, and `is_not_null` currently it is not possible to filter where the gender 

**Describe the solution you'd like**
Extend the performer filter to allow for things like `is_null` without having to use the deprecated `is_missing` filter as well as the ability to do exclude filters on the gender attribute

**Comment by stg-annon** [comment]
after looking at it for a bit it seems most of the work to do this is on the backed API as the current performer_filter seems to only care about the gender value and is only supported as as singular value and not a list/array of values, for example a user might want to use the following filter
```json
"performer_filter": {
    "gender":{
      "modifier": "EXCLUDES",
      "value": ["MALE", "FEMALE"]
    }
}
```

something like the following seems like it would be needed for the above example to work

```go
func genderCriterionHandler(genders *models.MultiCriterionInput) criterionHandlerFunc {
	return func(f *filterBuilder) {
		switch genders.Modifier {
		case models.CriterionModifierIsNull:
			f.addWhere(fmt.Sprintf("performers.gender IS NULL"))
		case models.CriterionModifierNotNull:
			f.addWhere(fmt.Sprintf("performers.gender NOT NULL"))
		default:
			value := "'" + strings.Join(genders.Value, "', '") + "'"
			f.addWhere(fmt.Sprintf("performers.gender IN (%s)", value))
		}
	}
}
```

**Comment by SpedNSFW** [comment]
This is dearly needed. As you've mentioned, we need the ability to filter performers that are missing a gender, but not just that, we need the ability to filter by multiple genders at once. If I want to search all "feminine" performers, I need two searches; one filtering females and another for transgender females. There should be a way to filter multiple.
