### ISSUE TITLE
[Bug Report] Scene tagger does not select the best match

### ISSUE THREAD

**Issue by kronkels** [stashapp/stash#2398]
**Describe the bug**
The scene tagger does not automatically select the best match for the scene. In case there is a scene in the stash-box instance with fewer fingerprint matches (a scene with incorrect fingerprints), stash seems to prefer that one instead of the scene that matches 100%.

**To Reproduce**
1. Navigate to the "Scenes" tab.
2. Open the scene tagger view.
3. Scrape a scene that has the same fingerprints assigned to multiple scenes in stash-box.
4. Most likely, it will match the wrong scene as shown in the screenshot below.

**Expected behavior**
The right scene should be selected (in focus).

**Stash Version: (from Settings -> About):** 0.13.1

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Google Chrome
 - Version: 99

![Schermafdruk_2022-03-19_17-17-33](https://user-images.githubusercontent.com/92669709/159129925-41c6fb24-5fea-4453-801d-bd86d137acf6.png)

**Comment by JackDawson94** [comment]
Quick summary of discord discussions on this topic.
We need to agree on the order of importance of parameters, current preference is:
1. # of matched durations
2. # of matched phashes


I can try to do this on the frontend, specifically in the Tagger screen. If it needs to be changed in the backend (for example to be used in Identifier), someone else should take over 😊

**Comment by JackDawson94** [comment]
Looked into the code a bit, this would require changing the graphql schema, currently the object we use to get the local scene data is `SlimSceneDataFragment` and this does not contain `duration` so there is no way to compare it.

Not familiar enough with Stash's codebase to touch things outside the UI. So will let someone else handle this bug for now.
I'll come back to it in a few weeks/months if it's not fixed, once I'm more familiar with the backend code.

**Comment by JackDawson94** [comment]
After looking into it some more, no changes needed to the gql so I did a few tests.

I'm not sure yet if we should use the raw number of matched durations / hashes or ratio.
Examples:
- Scene A is matched with 20 fingerprints out of 50
- Scene B is matched with 10 fingerprints out of 10

Which one is the best choice ??? (same problem for durations)
