### ISSUE TITLE
[Bug Report] #2356 Breaks Windows compilation

### ISSUE THREAD

**Issue by Still34** [stashapp/stash#2401]
**Describe the bug**
#2356 appears to introduce an invalid command for Windows platforms in the Makefile.

**To Reproduce**
1. Build with `make`
2. See error.

```
The syntax of the command is incorrect.
mingw32-make: *** [Makefile:149: touch-ui] Error 1
```

**Expected behavior**
Successful build.

**Screenshots**
If applicable, add screenshots to help explain your problem please ensure that your screenshots are SFW or at least appropriately censored.

**Stash Version: (from Settings -> About):**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by WithoutPants** [comment]
Missed this since I use git bash for my build environment. Should be fixed with the latest commit.
