### ISSUE TITLE
[Bug Report] Logs doesn't appear in the webUI when server started by double click on the exe

### ISSUE THREAD

**Issue by graphixillusion** [stashapp/stash#2412]
**Describe the bug**
Logs doesn't appear in the webUI --> Logs when the server is launched by double click the executable from file explorer (Windows)

**To Reproduce**
1. Double click on the executable from file explorer under Windows OS
2. Go to the webUI ---> Logs
3. Logs is empty

**Expected behavior**
The webUI ---> Logs section should show the log infos like when you start the server with the old way using command prompt

**Screenshots**
1. web-UI ---> Logs section (stash-win started from command prompt):
https://imgur.com/a/3kA6usk

2. web-UI ---> Logs section (stash-win started by double click in file explorer):
https://imgur.com/a/gEK4RiY

**Stash Version: (from Settings -> About):**
v0.13.1
Build hash:
2b5c5f20
Build time:
2022-03-16 00:13:23

I've tried the last development version too (v0.13.1-14-g228e8c9b) and this bug is still present

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2 v19044.1586 
 - Browser: Chrome
 - Version: 99.0.4844.82 64bit

**Comment by WithoutPants** [comment]
To me, this looks like the trace logging is filling the log cache, bumping the info logs. I found that if I open the browser directly from startup, then navigate directly to Settings -> Logs, the correct info logs appear. If I do anything else first - for example go to the scenes page - then to logs, the logs page is empty. Didn't matter if I ran it from command line or double-click.
