### ISSUE TITLE
[Bug Report] No Scene Previews since last few pre-release

### ISSUE THREAD

**Issue by ghfsa** [stashapp/stash#2423]
**Bug description**
Since the last few pre-releases I'm not able to view **Scene Previews** created by those versions. Preview generated by last stable version (v13.1) or before could be seen though.

**Stash Version: (any pre-releases after stable13.1):**

**Desktop:**
 - OS: Windows 8.1
 - Browser: Firefox
 - Version: 98.0.2

**Comment by WithoutPants** [comment]
Check the value of setting `Generated file naming hash`. In most cases this should be `oshash`, but there is a latent bug where this value gets changed. You will also need to verify that the preview files are correctly located in the `generated/screenshots` directory.

**Comment by ghfsa** [comment]
> Check the value of setting `Generated file naming hash`. ... verify that the preview files are correctly located in the `generated/screenshots` directory.

settings seem to be fine
![pan](https://user-images.githubusercontent.com/83634560/159882795-1600d533-efef-4376-9777-9313c159f08e.jpg)

**Comment by gatt70** [comment]
I upgraded recently and now scene previews aren't being generated for me either. The old ones still work fine. Here is a sample log:

`22-03-24 22:05:49
Warning 
[generator] failed generating scene preview, trying fallback
2022-03-24 22:05:49
Error   
ffmpeg error when running command <C:\Program Files\FFmpeg\bin\ffmpeg.exe -v error -f concat -i H:\Archive\stash\generated\tmp\files_602553099e848b7a.txt -y -c copy H:\Archive\stash\generated\screenshots\602553099e848b7a.mp4>: [concat @ 00000233edeae440] Impossible to open 'H:preview_602553099e848b7a_000.mp4'
H:\Archive\stash\generated\tmp\files_602553099e848b7a.txt: No such file or directory
2022-03-24 22:05:43
Info    
[generator] generating scene preview for \\path\filename.mp4`

**Comment by bnkai** [comment]
> I upgraded recently and now scene previews aren't being generated for me either. The old ones still work fine. Here is a sample log:
> 
> `22-03-24 22:05:49 Warning [generator] failed generating scene preview, trying fallback 2022-03-24 22:05:49 Error ffmpeg error when running command <C:\Program Files\FFmpeg\bin\ffmpeg.exe -v error -f concat -i H:\Archive\stash\generated\tmp\files_602553099e848b7a.txt -y -c copy H:\Archive\stash\generated\screenshots\602553099e848b7a.mp4>: [concat @ 00000233edeae440] Impossible to open 'H:preview_602553099e848b7a_000.mp4' H:\Archive\stash\generated\tmp\files_602553099e848b7a.txt: No such file or directory 2022-03-24 22:05:43 Info [generator] generating scene preview for \\path\filename.mp4`

Is `C:\Program Files\FFmpeg\bin\ffmpeg.exe` the ffmpeg you used before or not? There was a similar issue mentioned recently in  discord and it seems that for some reason the ffmpeg used is not the correct one. Can you double check either the folder that you run stash from or where you have the config.yml and see if you have both ffmpeg.exe and ffprobe.exe there? If you dont you can download from here <https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip> (that is where stash downloads the windows binaries from) and unzip the ffmpeg.exe and ffprobe.exe to the stash folder?

**Comment by WithoutPants** [comment]
Confirmed bug with preview generation code on Windows.
