### ISSUE TITLE
[Bug Report] macOS constant CPU use

### ISSUE THREAD

**Issue by MC1R-13** [stashapp/stash#2427]
macOS constant CPU use

Sometime after v0.13.0-5-g9e3d56b2 from March 16, stash constantly uses a lot more resources than usual.
There was nothing in the log, but when I opened the console, it generated close 500,000 of these in just over a minute:

```
34074	error		00:37:02.936631-0500	stash-macos-intel	nextEventMatchingMask should only be called from the Main Thread!

34074	error		00:37:02.936919-0500	stash-macos-intel	(
	0   CoreFoundation                   	0x00007fff2074b29b __exceptionPreprocess + 242
	1   libobjc.A.dylib                 	0x00007fff20484d92 objc_exception_throw + 48
	2   AppKit                        	0x00007fff22ed7116 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 4389
	3   AppKit                         	0x00007fff22ec8869 -[NSApplication run] + 586
	4   stash-macos-intel                	0x0000000004de4af5 nativeLoop + 53
	5   stash-macos-intel                	0x0000000004de3e3a _cgo_638c47e0eddf_Cfunc_nativeLoop + 26
	6   stash-macos-intel                	0x0000000004069d10 runtime.asmcgocall.abi0 + 112
)
```

I'm hoping someone knows what this means because I do not.

Stash Version: (from Settings -> About):
Anything after: v0.13.0-5-g9e3d56b2

Desktop (please complete the following information):
 - OS: Mac OS Big Sur 11.6.5 (Intel)
 - Browser: Safari
 - Version: 15.4

**Comment by WithoutPants** [comment]
Relevant links: 
* https://stackoverflow.com/questions/25361831/benefits-of-runtime-lockosthread-in-golang
* https://zchee.github.io/golang-wiki/LockOSThread/
* https://github.com/hybridgroup/gocv/issues/31

I don't know what `nativeLoop` is or why it's causing this. Would be good to get a verification from another macOS user.

**Comment by bnkai** [comment]
Nativeloop seems to be used from the systray code <https://github.com/getlantern/systray/issues/34> ,  not sure what can be done though.

**Comment by WithoutPants** [comment]
We have a forked version of `systray` maintained by @kermieisinthehouse. Calling `LockOSThread` might help perhaps?

**Comment by bnkai** [comment]
From a quick look it seems that the Onrun function from `systray` is using a nativeloop. Maybe add an init with the lock to the package and then check if the run function stays on the main thread as suggested from <https://zchee.github.io/golang-wiki/LockOSThread/>

**Comment by bnkai** [comment]
Scratch that. The library already does the init with kockosthread

**Comment by kermieisinthehouse** [comment]
The project refactor might've pushed the systray off the main thread. I'll investigate if that's the cause

**Comment by newadventure079** [comment]
FWIW, I'm on Monterey with an m1 chip and I dont see these issues

**Comment by MC1R-13** [comment]
That's not surprising, since you're using version 12, and this didn't start until after 13.

**Comment by newadventure079** [comment]
I tested it on version .13 also

**Comment by WithoutPants** [comment]
@MC1R-13 can you please test PR #2475 to see if it addresses the issue for you?

**Comment by MC1R-13** [comment]
All right, and as soon as I figure out how to build it, I will.

**Comment by WithoutPants** [comment]
See binaries here: https://github.com/stashapp/stash/actions/runs/2093097337

**Comment by MC1R-13** [comment]
Oh, nice!
Yes, it's back to using 0.0% cpu.
Thank you.
