### ISSUE TITLE
[Feature] [UI] Do not display tabs with 0 count pill badges

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#2432]
**Is your feature request related to a problem? Please describe.**
The Stash UI is becoming very busy with redundant/unnecessary UI elements. One such element is the performer tab badge (see image below) when the badge count reads 0.

![Screenshot 2022-03-27 155212](https://user-images.githubusercontent.com/37937507/160298292-d52c5daa-6e4d-4376-bebe-e84d7554df9b.png)

**Describe the solution you'd like**
Do not display the badge when the count is 0.

***Reasoning***
0 count = NULL = not displaying the badge. These are all relaying the same information to the user, except the latter reduces the amount of clutter on the UI. Your email client, SMS client, Discord client, etc. have visual indicator counters for every folder/contact/channel that has unread mail/messages, it doesn't show 0 beside each item that doesn't meet the unread criteria. the same principle applies here.

Pills/badges in general should not appear when their count is 0. Their purpose as a UI element is to notify the user of a >0 integer.

**Describe alternatives you've considered**
Give 0 count badges a unique class name so they can be hidden using CSS injection.

**Comment by WithoutPants** [comment]
I played around with implementing this and found the following:

Some tabs don't have a count to use (specifically `studios -> performers`). Leaving the badges off where the count is zero causes inconsistency with this tab - it suggests that there are no performers associated with a studio when we really just don't have the count. 

An alternative might be to omit a tab altogether if it has no content.

**Comment by echo6ix** [comment]
> An alternative might be to omit a tab altogether if it has no content.

@WithoutPants Yes. That's actually a great suggestion imo.

**Comment by DingDongSoLong4** [comment]
As mentioned in #2487 hiding the entire tab doesn't really work, but hiding the badges only is trivial after #3405:
```
.badge-pill[data-value="0"] {
  display: none;
}
```

Personally I would rather keep the zeros there, but since it would be easy to revert with custom CSS I don't really mind - and the change can easily be added to the list of custom CSS snippets in the wiki/docs.

**Comment by echo6ix** [comment]
Implemented with #3405
