### ISSUE TITLE
[Feature] Implement a server/client notification system to enhance plugin capability

### ISSUE THREAD

**Issue by ALonelyJuicebox** [stashapp/stash#2433]
Related to closed issue https://github.com/stashapp/stash/issues/1011 and the related PR https://github.com/stashapp/CommunityScripts/pull/1 for a plugin that copies marker tags to the associated scene, avoiding a need for a user to define the same tags on the marker and as well as on the scene itself.

The plugin works well, however after adding marker tags, the page _must_ be refreshed on the marker page prior to making any modifications on the edit tab before the tags will populate in the scene tag list.
This can lead to unintended UX where marker tags will never populate as scene tags.

Current Flow:
1. Define a marker on the Marker tab with a primary tag of < x >
2. Without refreshing the page, click on the Edit tab. Observe that no scene tags exist.
3. Add a scene tag of < y > and click on the Save button.
4. Refresh the page, observe that marker tag < x > is never populated as a scene tag.

This feature request is to correct this and provide a flow more similar to the below
1. Define a marker on the Marker tab with a primary tag of < x >
2. Without refreshing the page, click on the Edit Tab. Observe that the marker tags that were defined now also exist as scene tags

**Comment by WithoutPants** [comment]
$50 bounty added (28-Mar-2022)

**Comment by ALonelyJuicebox** [comment]
@WithoutPants I believe this is now fixed with https://github.com/stashapp/stash/pull/2502 ? 🙂
Safe to close?

**Comment by WithoutPants** [comment]
> @WithoutPants I believe this is now fixed with #2502 ? 🙂 Safe to close?

This is an unrelated issue and relates to a user-directed marker creation, and not one that is created via plugin. It will not address this particular issue.

**Comment by ALonelyJuicebox** [comment]
Ah OK.
The changes made _do_ seem to address the flow I outlined in my issue description above. I can now define a marker, head to the edit tab (without a refresh) and see the tag I just added.

But it sounds as though there are additional changes you'd like to make to the backend. No worries.

**Comment by WithoutPants** [comment]
That's weird. In any case, if this is no longer an issue for you, feel free to close it and redirect your bounty elsewhere.

**Comment by ALonelyJuicebox** [comment]
@WithoutPants I'll close, but please keep the bounty as work was done by you in order to resolve the issue. 🙂
