### ISSUE TITLE
[Bug Report] video.js doesn't properly fullscreen on mobile

### ISSUE THREAD

**Issue by hmahler2** [stashapp/stash#2438]
**Describe the bug**
video.js player doesn't enter full screen on mobile, instead it fills its frame. The header and footer of the mobile page still take up space.

**To Reproduce**
1. Go to any scene
2. Play video
3. Use fullscreen toggle

**Expected behavior**
For video.js to enter fullscreen when the button is pressed.

**Stash Version: (from Settings -> About):**
v0.13.1-30-gf3355f3d

**Smartphone (please complete the following information):**
 - Device: iPhone6
 - OS: iOS12.5.5
 - Browser firefox / chrome
 - Version 36 / 92

**Comment by WithoutPants** [comment]
This will need to be investigated by someone with an iPhone device. I can only verify that this issue doesn't appear on Android.

**Comment by Teda1** [comment]
Here is a video capturing the issue on iOS:
https://user-images.githubusercontent.com/72030708/160520836-ae8cc201-a6c0-4aca-9c37-6aee75f2dbf8.mp4

The content captured is SFW but feel free to take down the video after viewing.

**Comment by WithoutPants** [comment]
Looks to be related to this https://github.com/prateekrastogi/videojs-landscape-fullscreen/issues/16 (this a thoroughly unhelpful response). I suspect that we'll need to host the plugin internally and fix the issue. Unfortunately, I won't be able to do it since I don't have an iPhone device to test with.

**Comment by Teda1** [comment]
Maybe setting `iOS: false` is best for now. This makes it so that playing a video will always enter full-screen mode.

**Comment by Teda1** [comment]
We could also look into trying https://www.npmjs.com/package/videojs-mobile-ui
