### ISSUE TITLE
[Bug Report] video.js: Markers not on seekbar

### ISSUE THREAD

**Issue by QxxxGit** [stashapp/stash#2442]
The old player would display markers on the seekbar (line that you could hover and click to jump to the section). This is currently missing in the new video.js implementation.

**Comment by WithoutPants** [comment]
This will need a videojs plugin to work. 

https://github.com/spchuang/videojs-markers looks like does what we need, but is not currently maintained. Can try to use as-is or absorb into the source code so that we can fix any bugs.
