### ISSUE TITLE
[Bug Report] Video.js: sound always go back on.

### ISSUE THREAD

**Issue by Belleyy** [stashapp/stash#2446]
**Describe the bug**
If you mute the video, reload, the sound is back on. JWPlayer remember the sound between page.

**To Reproduce**
1. Go to a Scene
2. Click on Sound to mute
3. Reload page/ go to a other scene
4. Sound is back on

**Expected behavior**
Keep the sound status like JWPlayer did.

**Stash Version: (from Settings -> About):**
v0.13.1-32-gc4c62d25

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version 98.0

**Comment by stg-annon** [comment]
might need to implement something like this or use this as a plugin

https://github.com/theonion/videojs-persistvolume
