### ISSUE TITLE
Performer & Studio editing fields lose focus when switching apps or tabs

### ISSUE THREAD

**Issue by Cutters1982** [stashapp/stash#247]
Hi all

This has already been discussed on the Discord, but I wanted to make an issue for it.

When editing/adding a performer/studio and filling in the details, if you tab out and tab back in it loses focus, so you have to left-click on the field again, which is a bit of a nuisance particularly when you're adding a performer and filling out date of birth etc.

It doesn't seem to lose focus on the main scene editing section.

Would appreciate if someone could implement this fix asap because it slows down adding performers a fair bit

Cheers!

EDIT: Mentioned studio editing as well (as per WithoutPants post)

**Comment by WithoutPants** [comment]
This occurs in the studio edit page as well.

**Comment by WithoutPants** [comment]
This appears to be due to the `EditableText` Blueprint components. There is an `alwaysRenderInput` property (which requires an update to Blueprint) that when set appears to fix the issue, but it breaks the look of the fields. A more involved fix will be required.

**Comment by Cutters1982** [comment]
Okay, thank you mate!

**Comment by Cutters1982** [comment]
Thanks for fixing this :)
