### ISSUE TITLE
[Bug Report] Issues with video.js player and Hover on touch devices.

### ISSUE THREAD

**Issue by Teda1** [stashapp/stash#2476]
**Describe the bug**
The video.js player has several issues related to hover on touch devices. The hover effect persists when elements are no longer being touched and can really mess up the UI.

**To Reproduce**
Here is a video demonstrating the issue:

https://user-images.githubusercontent.com/72030708/161653790-56ea53b4-3aee-4da7-80ff-480fd3becbee.MP4

**Expected behavior**
I'm not sure yet how best to handle this. If we disable hover then it seems like we would lose the ability to preview timestamps. There may be a way to fix the hover issue while keeping the ability to preview timestamps.

**Comment by kyle-greenholt** [comment]
In the previous implementation a double-tap on the video player toggled the full screen status. It would be nice to see that behavior restored as well.
