### ISSUE TITLE
[Bug Report] Tagger Replaces Existing Performers

### ISSUE THREAD

**Issue by AdultSun** [stashapp/stash#2478]
**Describe the bug**
The Tagger view will replace the entire performers field, rather than merge with any existing performers for that scene. This has caused issues for a few users on Discord recently, including myself. For me, if I manually scrape a scene I'll add any missing performers as I see fit. If I later update that scene with the Tagger (I only use stash-box sources here), any existing performers that are missing from the Tagger's scrape will then be removed upon update. The only way to prevent this is to uncheck all listed performers in the Tagger, preventing it from updating the performer field at all.

**To Reproduce**
1. Add a new performer to a scene, missing from intended Tagger source
2. Go to the Tagger view and find a match for that scene
3. Leave at least one performer with a green checkmark
4. Save changes, and verify that the new performer from step 1 is now missing

**Expected behavior**
I imagine most users would expect the tagger to merge data by default when appropriate, rather than destructively replacing any data that was already there. At the very least, there should be an option to select merge vs. replace in a manner similar to how tags are handled in the Tagger.

**Stash Version: v0.13.1-56-g230d8f60 (from echo6ix's recent test)**

**Comment by WithoutPants** [comment]
The tagger should probably be improved at some point to allow finer control over performer settings. For now, I'll merge the performer lists.
