### ISSUE TITLE
[Feature] Tags for studios

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#2497]
**Is your feature request related to a problem? Please describe.**
Many studios create niche content or can be categorized into a specific genre. With any significant number of studios, there is no efficient way to single out studios by their genre/niche.

**Describe the solution you'd like**
Ability to add existing tags to studios.

Studio > Edit > Tags form field

**Additional context**
Proposed methods of implementation on the studio and tags page

##### STUDIO PAGE
Fairly straightforward implementation, similar to the scene page filter, tags could be searched via the filter on the studio page.

##### TAGS PAGE
Add a studio tab to a tag's page.

**Comment by fmwolf** [comment]
I agree it would be nice to be able to filter/group studios together by their specific niche.

**Comment by WithoutPants** [comment]
$40 bounty assigned (transaction #581474).
