### ISSUE TITLE
[Bug] Several scenes missing after scan

### ISSUE THREAD

**Issue by waxrip** [stashapp/stash#25]
After a scan several of the scenes end up missing in the database. 

The server is running on Ubuntu 16.04 and outputs a time stamp parse error for every scene that ends up missing.
```
error - parsing time ""2016-07-15 23:37:54"" as ""2006-01-02T15:04:05Z07:00"": cannot parse " 23:37:54"" as "T"
```

**Comment by StashAppDev** [comment]
Are you a user of the old Rails version and are you reusing the same sqlite database file?  If so, then you might want to try exporting from the rails version and then import the JSON into the Go version... there were some pretty major changes between the two versions.

If that's not the case then I think I'd need more logs.  I haven't actually tested the app under Ubuntu, so it might be something specific to that platform.  I'll try running it myself there soon.

**Comment by waxrip** [comment]
I am using the Go version with a fresh database. The logs I posted occurs
during iteration over the files in the search path. I can gladly provide
you better logs with some guidance.

**Comment by bnkai** [comment]
i can confirm from my own database (fresh database in debian)
just a couple  of my  6k+ files had the  problem though and they were old wmv files

the problem is that the creation_time tag from ffprobe is like this for example "2015-06-03 14:40:48"
and **json.Unmarshal(out, probeJSON)** in ffprobe.go errors out because it expects RFC3339 formatted creation_time 

i just commented out the file creation_time from the structs in ffmpeg/types.go and ffmpeg/ffprobe.go , as i don't care about this anyway and it bypassses the issue

**Comment by malcuk** [comment]
I've just noticed that during a scan it's not picking up .mkv files for me at all - will these be supported at some point?

**Comment by bnkai** [comment]
A more elegant solution i tried is creating a custom type json unmarshal for the creation_time
I added this code to _ffmpeg/types.go_ (needs strings , time)
```

  // custom time format json unmarshal
type TimeWrapper time.Time

func (w *TimeWrapper) UnmarshalJSON(data []byte) (err error) {
	var ct time.Time
	s := fmt.Sprintf("%s", data)
	s = strings.Trim(s, "\"")

	//custom format 1 - found in some old wmv files - example "2015-06-03 14:40:48"
	if ct, err := time.Parse("2006-01-02 15:04:05", s); err == nil {
	//	fmt.Println("creation time parsed ok as custom 1") //DEBUG
		*w = TimeWrapper(ct)
		return nil
	}

	//default  RFC3339
	if ct, err = time.Parse(time.RFC3339, s); err != nil {
		return err
	}
        //      fmt.Println("creation time parsed ok as RFC3339") //DEBUG
	*w = TimeWrapper(ct)
        return nil
}
```
and then changed the type of CreationTime in _ffmpeg/types.go ffmpeg/ffprobe.go_ from **time.Time** to **TimeWrapper**

it seems to work ok for me

**Comment by bnkai** [comment]
> I've just noticed that during a scan it's not picking up .mkv files for me at all - will these be supported at some point?

it imports by default zip,m4v,mp4,mov,wmv

if you can compile it you can add mkv,webm also

**Comment by caustico** [comment]
> > I've just noticed that during a scan it's not picking up .mkv files for me at all - will these be supported at some point?
> 
> it imports by default zip,m4v,mp4,mov,wmv
> 
> if you can compile it you can add mkv,webm also

I had the same problem the last week and imported other videos with format MKV, but some MKV files are not streameable with jwplayer. I think that is why it is not allowed to import that type of files.
MKV is a container format and the problem can be in the codecs the file use. Files MKV with H26x Video codec should can work but others format can have problem.

**Comment by StashAppDev** [comment]
@bnkai Thanks for that info, it really helped.  I just pushed a new build which should fix this.  Let me know if there are still issues.

**Comment by bnkai** [comment]
with the lastest commit everything seems ok now at least with my samples.
