### ISSUE TITLE
[Bug Report] Back button broken when using Saved Filters on the Gallery Tab

### ISSUE THREAD

**Issue by ALonelyJuicebox** [stashapp/stash#2505]
**To Reproduce**
1 - Go to the Galleries page. 
2 - Select a saved filter.
3 - Click on a Gallery.
4 - Press the back button on your browser
5 - Query on the Gallery page returns to nothing (not even the default saved filter!)

**Expected behavior**
Expected behavior is identical to how saved filters behave on the Markers/Scenes/Images page, where if you press the back button from a Marker/Scene/Image, you'll be properly returned to your previous query-- saved filter(s) intact.

**Stash Version:** 0.14.0 (Although this was present in the previous major release as well)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 100.0.4896.75

**Comment by WithoutPants** [comment]
$50 bounty added (29-Apr-2022)

**Comment by ALonelyJuicebox** [comment]
I didn't leave enough information to this bug report and made an assumption that this affected filters more widely than it does. Sorry!

**Specifically**, I was using the "path" filter, and the path I was defining had a hashtag "#" in it.
Example: `F:\2022\#Character` 

If you were to create a filter for this, you would get an URL something like this in your address bar  `http://localhost:9999/galleries?c={"type":"path","value":"#Character","modifier":"INCLUDES"}&sortby=created_at&sortdir=descyaddayaddayadda`

I really don't understand the details of how Stash works, but I do know that a hashtag in an URL is used for several things in web dev, from helping define page state status to page positioning. Because we don't use percent encoding and escape the hash character here as %23, I have a feeling it's causing an unintended result here.

Hopefully this makes more sense!
