### ISSUE TITLE
Stash appears to be missing a flag for the country Laos

### ISSUE THREAD

**Issue by Teda1** [stashapp/stash#2514]
**Describe the bug**
Performers with Laos specified as their country are missing a country flag.

**Expected behavior**
Laos should be included in the list of countries Stash is aware of.

**Screenshots**
![Screenshot 2022-04-16 113043](https://user-images.githubusercontent.com/72030708/163685441-af6aab4b-8db9-47a6-904c-69e965a611ad.jpg)
![Screenshot 2022-04-16 113112](https://user-images.githubusercontent.com/72030708/163685443-2363db67-bb7e-4968-bd41-872a0f657835.jpg)

**Stash Version: (from Settings -> About):**
v0.14.0

**Comment by Belleyy** [comment]
To be exact it need to have the short name of 'Laos'
If you write 'Lao People''s Democratic Republic', you will get the flag.

**Comment by Teda1** [comment]
Thanks for adding that additional info.
