### ISSUE TITLE
ForgiveMeFather scenes dosent have performers

### ISSUE THREAD

**Issue by Sourcers99** [stashapp/stash#2522]
Error on submit to stashbox

Submission failed
input: variable.input.performers must be defined 
please change performers field to optional

**Comment by HereIam80** [comment]
Have you tried the latest dev instance of stash?
[Link to the issue](https://github.com/stashapp/stash/pull/2515)

**Comment by Sourcers99** [comment]
No

**Comment by InfiniteTF** [comment]
This is fixed in the development version.
