### ISSUE TITLE
[Feature] Merge Metadata (like Tags, Markers etc) in Duplicate Checker Tool

### ISSUE THREAD

**Issue by d3f113** [stashapp/stash#2534]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I go through the Duplicate Checker and see, that a duplicate of a video with worse video quality has more meta data. This could be actors, tags, markers etc. So, I have to manually add all these information. Adding 10 tags and 4 actors is really frustrating, but adding 5 scene markers at the same position just doubles that frustration. So, I decide just to let it in my duplicate list, but because of that this list grows and grows and gets hard to use.

**Describe the solution you'd like**
A button like the delete button, which merges all information (scene markers, actors, tags etc) of the duplicates. This could be, that I press it on the video, where I like the tags and it copys the meta data to the other duplicated videos.
Or the other way around, that you click merge on the video, where you want the meta data and the merge screen appears. This could be harder, because there can be 10+ duplicates (so merging 10 videos at once or 10 videos after each other).

**Describe alternatives you've considered**
Doing it manually
Copying the database entry

**Additional context**
-

**Comment by stg-annon** [comment]
resolved in #3006

see https://github.com/stashapp/stash/pull/3006#issuecomment-1291208144
