### ISSUE TITLE
[Feature] Before navigating to the next image, delay navigation until additional scroll detected

### ISSUE THREAD

**Issue by ALonelyJuicebox** [stashapp/stash#2535]
Related to the fantastic PR by WithoutPants where mouse scrolling can be used to progress to the next image in the lightbox when the bottom of the page is reached. https://github.com/stashapp/stash/pull/2403

This is well implemented and a great addition! I should have provided this feedback during the dev testing of this PR.

When zoomed in a bit to an image, as you're navigating to the bottom of the image, it may not be obvious _when_ the bottom of the page has been reached. The problem is, this can result in accidental navigation to the next image. 

As a solution, when the bottom of the page is reached, prevent the user from scrolling down further (giving user feedback that the bottom of the image has been reached) THEN progress to the next image _after_ receiving `<x>` additional scroll down events from the user (indicating there's user intent to move on to the next image)

Not sure what `<x>` should be or if it should be user configurable but some sort of delay on when progression happens would be nice to see. 🙂 

This should be specifically for when there is room for the image to scroll (I don't think this makes sense for instances when the whole image is viewable).

Thanks! 🙏🏾

**Comment by WithoutPants** [comment]
$50 bounty added (29-Apr-2022)
