### ISSUE TITLE
[Bug Report] Reverse Proxy: The media could not be loaded.

### ISSUE THREAD

**Issue by Johnnybegood90** [stashapp/stash#2536]
**Describe the bug**
If I use stash through the local server ip, everything works fine. If I use the reverse proxy, I get the error The media could not be loaded, either because the server or network failed or because the format is not supported.

**To Reproduce**
Unknown

**Expected behavior**
The scene should be played.

**Screenshots**
Screenshots attached

**Stash Version: (from Settings -> About):**
0.14.

**Server**
 - OS: Debian 11.3
 - Reverse proxy on subdomain via Apache2 (anonymized vhost attached to this ticket)
 
**Desktop (please complete the following information):**
 - Tried on Windows 11, Debian 11 and Mint 21.
 - Tried on Chrome, Firefox, Edge and Opera

**Additional context**
Anonymized vhost and stash config file 
PS: The configuration file has been converted to txt because GitHub does not support yml files.
**It was working on previous version [v0.13.1](https://github.com/stashapp/stash/releases/tag/v0.13.1).**

The issue screenshot: https://www.nsfwupload.com/image/hPmQG NSFW LINK!

![Vhost](https://user-images.githubusercontent.com/22503727/165578886-4caed6b9-39b7-4ab2-98fd-1339d56b7314.png)
attached to this ticket
[Stash config.txt](https://github.com/stashapp/stash/files/8574819/Stash.config.txt)

**Comment by peolic** [comment]
I think the answers are here:
https://github.com/stashapp/stash/wiki/Authentication-Required-When-Accessing-Stash-From-the-Internet

**Comment by Johnnybegood90** [comment]
The authentification is already set...

**Comment by Johnnybegood90** [comment]
Errors from the browser console when I use ReverseProxy
![browser-errors](https://user-images.githubusercontent.com/22503727/165624131-1f3d1a72-a39c-48ac-a44b-b8c7fa78a0ed.png)

**Comment by JEckin** [comment]
Had the same issue. Change to Nginx and everything worked.

```
server {
    listen 80;
    listen [::]:80;

    server_name stash.home;
        client_max_body_size 0;
        location / {
           proxy_pass http://192.168.0.1:9999/;
           proxy_http_version 1.1;
           proxy_set_header Upgrade $http_upgrade;
           proxy_set_header Connection "Upgrade";
           proxy_set_header Host $http_host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For $remote_addr;
           proxy_set_header X-Forwarded-Port $server_port;
           proxy_set_header X-Forwarded-Proto $scheme;
    }

}
```

**Comment by WithoutPants** [comment]
The stash config is incorrect. `external_site` should be `external_host`. I have amended the wiki page which had the same error.

You may also want to add the following to enable the websockets connection:
```
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteCond %{HTTP:Connection} upgrade [NC]
RewriteRule ^/?(.*) "ws://192.168.0.21:9999/$1" [P,L]
```

**Comment by Johnnybegood90** [comment]
Still the same error...

**Comment by Johnnybegood90** [comment]
That worked great! Thank you!

**Comment by LastWishNSFW** [comment]
I have the same problem. I also use reverse proxy on subdomain via Apache2. These Errors also only appear on the subdomain. I already edited my Apache config like above, but I still get the same Errors. 
![Screenshot 2023-07-16 012459](https://github.com/stashapp/stash/assets/137116346/e00f38c6-d990-4c47-aed4-273f80765c00)

This is my Apache2 config:
![Screenshot 2023-07-16 013053](https://github.com/stashapp/stash/assets/137116346/b97514fb-958f-4339-a3b5-272631fc280a)

**Comment by DingDongSoLong4** [comment]
If you were using nginx I could be much more help, but from those browser logs that looks like an issue with the `Content-Security-Policy` header. It looks like you're setting `Content-Security-Policy` using Apache there - does removing that change anything? Stash sets its own (fairly lengthy) `Content-Security-Policy` header to make a bunch of things work properly.

**Comment by LastWishNSFW** [comment]
I added the `Content-Security-Policy` header because of my problems, but it doesn't seem to make any difference. 
I guess my websockets connection is not enabled like @WithoutPants said in his earlier reply, but I already changed my Apache config according to the docs. I can't really figure out what I'm doing wrong.

**Comment by WithoutPants** [comment]
> I added the `Content-Security-Policy` header because of my problems, but it doesn't seem to make any difference. 

Take out the content security policy stuff. It should give you at least a different error. 

> I guess my websockets connection is not enabled like @WithoutPants said in his earlier reply, but I already changed my Apache config according to the docs. I can't really figure out what I'm doing wrong.

Web socket issues only impact the task progress stuff being displayed properly - it wouldn't stop you accessing the system in general. I didn't see any web socket errors in your screenshot either.

**Comment by LastWishNSFW** [comment]
I added `external_host` to my config.yml and deleted the content security policy line from my apache config.
Now I can play videos. Thank you very much!
I still get the error `WebSocket connection to 'wss://mydomain.com/graphql' failed:` and task progress is not visible at all.

**Comment by WithoutPants** [comment]
Maybe try changing the `ws` rule to redirect to `wss`?

**Comment by LastWishNSFW** [comment]
No, it didn't change anything. I don't really get why it isn't working.

**Comment by LastWishNSFW** [comment]
I fixed it! Changed some things in my Apache config and its now working perfectly fine.
![Screenshot 2023-07-16 143654](https://github.com/stashapp/stash/assets/137116346/2a990d0a-c721-46e8-a511-0314558d6367)
