### ISSUE TITLE
Cannot import large file

### ISSUE THREAD

**Issue by aka-nsfw** [stashapp/stash#2541]
**Describe the bug**
I cannot import large file (~9k5 movies ~2GB) by using "Import from file" function.

**To Reproduce**
1. Go to 'Settings' -> 'Tasks' -> 'Metadata' -> 'Import from file'
2. Click on 'Import zip file' -> Select zip file
3. Click 'Import...'
4. Error: "Failed to fetch" (not any thing in Logs)

**Stash Version: (from Settings -> About): v0.14.0**

**Desktop:**
 - OS: Windows 10 21H2
 - Browser Chrome
 - Version 100.0.4896.127

**Comment by bnkai** [comment]
By default the max uploaded size limit is set to 1024 MB (1GB). If you want/need to import bigger files you need to edit the config.yml and add/edit the relevant setting (max_upload_size) as mentionend in the wiki <https://github.com/stashapp/stash/wiki/Advanced-Configuration-Options>

**Comment by aka-nsfw** [comment]
@bnkai Thank you. 👍
