### ISSUE TITLE
[Bug Report] Default performer filter isn't applied when browsing performers through the studio page

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#2573]
**Describe the bug**
(Not sure if this is a bug, not implemented, or intentional behavior.) The default performer filter is not applied when browsing performers through the studio page.

**To Reproduce**
1. Go to Performers
2. Create a filter, such as `Gender is Female`, and set as Default.
3. Go to Studios > Performers tab
4. The default filter is not applied

**Expected behavior**
Would it not be consistent to have the default filter apply to the performers tab in the studio subsection as well? That would be my expectation.

**Stash Version: (from Settings -> About): v0.14.0-26-g9ca38747

**Comment by WithoutPants** [comment]
The Default Filter in its current incarnation determines only what is displayed initially when the user clicks on the applicable top-level link - Scenes, Movies etc. I don't think it's expected or desired that whatever that initial view is is applied to sub-page views. For example, my current default filter for scenes is for rating > x, and sorted randomly. This would not be a useful filter to use in the sub-page views (this should be fed back to #2573 as well).
