### ISSUE TITLE
[Feature] Display Tag Description & Tag Image on hover

### ISSUE THREAD

**Issue by ALonelyJuicebox** [stashapp/stash#2575]
This is a UI focused feature request that elaborates further on https://github.com/stashapp/stash/issues/1444 (Add descriptions to tags)

Today, the images that can be added to tags are underutilized-- we currently only display them on the Tags page. 
With the request for Tag Descriptions already out as an open feature request, imo this is a great time to consider a new UI element here that would tie everything together.

I propose we display the description of the tag _as well as_ the associated tag image when hovering over an added tag tag (on the Details or Edit tab) or when hovering over a tag name in the tag dropdown form.

Below are some UI examples of what I'm thinking of...

**- Edit Tab, Tag Dropdown form** 
![StashIdeaForTagHover2](https://user-images.githubusercontent.com/76471868/167505141-07f57097-8311-4872-a31e-f213cd8b0642.png)

**- Edit Tab, On hover of an added Tag**
![StashIdeaForTagHover](https://user-images.githubusercontent.com/76471868/167505140-0ceb9c6c-da48-4de3-815c-e19a922d8a2b.png)

**- Details Tab, On hover of an added Tag**
![StashIdeaForTagHover3](https://user-images.githubusercontent.com/76471868/167505142-9f32fc7e-5fd5-4a68-be7f-982fd7de3020.png)

Thanks! 🙂

**Comment by echo6ix** [comment]
It certainly looks neat. Not sure if that would get annoying after a while in practice, but it looks neat.

Please consider adding a toggle in the interface settings to enable/disable if implemented.

**Comment by CosimoVestri** [comment]
Okay, I think this is a great idea. I've got SVG images for all of my tags.

@ALonelyJuicebox Question as to your mock-up: Are you envisioning separate images and icons, or are you using emoji as part of the tag names?

@echo6ix Adding settings for this sort of thing seems to be over complicating the interface to me. There's not really any existing instances where configuration settings for the user interface exist for features and components.

As such, I think hiding these items is something that somebody could do with custom CSS. Or not showing if no image is set.

**Comment by ALonelyJuicebox** [comment]
@CosimoVestri Nope, the emojis you see are live in my Stash today! 🙂
I use emoji's (and spaces) in my tag names in order to group the tags by category for _significantly_ easier manual tagging. I did a full write up on how it's accomplished in the UI channel on the Stash Discord on 5/9/2022 if you're interested.

To be clear for anyone else, this request is purely for the tag image/tag description display on hover as mentioned.

**Comment by WithoutPants** [comment]
$50 bounty placed (8-Jun-2022).

**Comment by Jigglyscruff** [comment]
Haha what’s the bounty for

**Comment by echo6ix** [comment]
> @echo6ix Adding settings for this sort of thing seems to be over complicating the interface to me. There's not really any existing instances where configuration settings for the user interface exist for features and components.

I disagree.

There already exists similar toggles in the interface settings for such things, such as `show [scene] scrubber`, `show studios as text`, and more.

It's quite simple to use and straight forward.

Settings > Interface
- Show tag tooltips [on/off toggle switch]
