### ISSUE TITLE
[Feature] Add Date Filter to Scene Filters

### ISSUE THREAD

**Issue by cytec** [stashapp/stash#2582]
**Is your feature request related to a problem? Please describe.**
Seems like there is  no filter for date.

**Describe the solution you'd like**
a filter option to filter for date set, not set, older and newer then given date

**Describe alternatives you've considered**
none

**Additional context**
since date is one of the requirements for submitting data to stashapp i'd like to save a filter wich contains all scenes that don't have a stashID but a date set (other requirements can be filtered already like performer, studio, link etc)

**Comment by ALonelyJuicebox** [comment]
Is this not available under Filter icon > "Is Missing" > "Date" ?

**Comment by cytec** [comment]
@ALonelyJuicebox it actually is, im using "is missing" already for another property... also i'd like to filter for dates before after a given date

**Comment by ALonelyJuicebox** [comment]
Ahh gotcha, yeah that makes sense. I agree that the filters need an overhaul, especially for use cases like this where you want to expand upon a filter in multiple ways. I know this was discussed in #2122

**Comment by bob123491234** [comment]
Completed in #2834.
