### ISSUE TITLE
[Bug Report] Plugin appear in Taskbar for small time

### ISSUE THREAD

**Issue by Belleyy** [stashapp/stash#2587]
**Describe the bug**
When stash use a plugin, it will open a window a split of second. It made the active windows lose focus for this time.
Stash opened inside a terminal on Windows10

**To Reproduce**
1. Click on a plugin
2. Look the taskbar or current window
3. See something happens (Appear in taskbar, browser window flick)

**Expected behavior**
Nothing, you don't notice anything.

**Video**

https://user-images.githubusercontent.com/23707269/168518199-4b0ecc06-1fab-41b1-8813-104e368d9f6b.mp4

**Stash Version: (from Settings -> About):**
v0.14.0-31-gdce45919
Build hash:
dce45919

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Firefox
 - Version 100

**Additional context**
I don't remember having this issue weeks ago so probably a recent PR did this.

**Comment by WithoutPants** [comment]
I'm not able to reproduce this so far, and the video doesn't seem related to the issue.

**Comment by Belleyy** [comment]
Fixed video (Sorry for that)

**Comment by WithoutPants** [comment]
Does this only happen during scanning? Which plugin is being triggered?

**Comment by Belleyy** [comment]
Plugin used in the video below:
[z_test.zip](https://github.com/stashapp/stash/files/8701514/z_test.zip)

(Stash in desktop mode)

https://user-images.githubusercontent.com/23707269/168632924-cf1f781d-e606-494d-b15d-5727691fd5fb.mp4

So for some reason removed `import` fix this issue ? 🤔

**Comment by Khukaan** [comment]
Just to add an extra datapoint which may or may not be relevant - I get the same sort of impact with a python based scraper (kodi.py)  used via Identify. The flicker for me is caused by a command prompt being opened and closed with the title of C:\Windows\py.exe

**Comment by WithoutPants** [comment]
> Plugin used in videos below: [z_test.zip](https://github.com/stashapp/stash/files/8701514/z_test.zip)

The issue is occurring here because of a call to `os.system('color')` in `log.py`. Removing that line or the import line fixes the issue.

This issue was likely introduced when we removed the `windowsgui` build flag from compilation. I'm not really keen to go back to using that build flag. [This stackoverflow answer](https://stackoverflow.com/a/7006424/695786) might help provide a way to execute system commands without spawning a console window.
