### ISSUE TITLE
[Bug Report] Scene Scrubber stops scrolling after creating or deleting markers

### ISSUE THREAD

**Issue by goldstar1x** [stashapp/stash#2600]
**Describe the bug**
When watching a scene, the scene scrubber usually auto-scrolls. The auto-scroll stops working when creating or deleting markers.

**To Reproduce**
1. Go to any scene page and start watching the scene
2. Create a marker
3. Observe the scrubber stops scrolling

**Expected behavior**
The scrubber should continue scrolling

**Stash Version: (from Settings -> About):**
v0.14.0-29-gea2fcd9d

**Desktop (please complete the following information):**
 - Browser: Tested on Chrome and Edge

**Comment by WithoutPants** [comment]
Confirmed. Also happens when editing scenes.
