### ISSUE TITLE
[Feature] Add Scene code

### ISSUE THREAD

**Issue by Foucoubou** [stashapp/stash#2607]
Hello,
would it be possible to add the scene code to the scene attributes and make it possible to populate / export  from/to stashdb

This would be very useful for studios, which have incremental code number for scene (especially czech studios).

**Comment by Teda1** [comment]
By scene code, I assume you are referring to the IDs studios associate with their scenes?

**Comment by Foucoubou** [comment]
> 
Yes

**Comment by echo6ix** [comment]
Yes 💯to this.

And studio codes is on the task list here #2359

**Comment by YurikaL** [comment]
Good news, everyone! Scene code is now added to Stash in #3051.

**Comment by DogmaDragon** [comment]
> @YurikaL @WithoutPants I see - still the flow from local stash -> stashdb is not yet working (the code, despite it is set up locally won't get pushed into the draft).

A new stash-box version wasn't released yet.

**Comment by YurikaL** [comment]
@Foucoubou My bad, I agree. I just don't pay attention to a mention of StashDB in issues, since it's not publicly accessible anyway. Is StashDB even a thing?

**Comment by AdultSun** [comment]
> Is StashDB even a thing?

@YurikaL This guide explains how to make a StashDB account, connect it to Stash, and start scraping:
https://guidelines.stashdb.org/docs/guide-to-scraping/

**Comment by YurikaL** [comment]
> [Get an invite code in the #stashdb-invites channel on Discord](https://guidelines.stashdb.org/docs/guide-to-scraping/#join-stashdb)

Exactly my point. Looking forward to public access!
