### ISSUE TITLE
[Bug Report] Existing Marker Previews will be ignored at regenerating although overriding is active

### ISSUE THREAD

**Issue by IAmKontrast** [stashapp/stash#2616]
**To Reproduce**
1. Create new marker
2. Choose time
3. Generate marker preview
4. Change the time of the marker
5. Generate marker previews again and turn on 'Overwrite existing generated files'

**Expected behavior**
New generated preview video should start at new timestamp. Click on it start the scene at the correct position but the video preview thumbnail is wrong.

**Stash Version: v0.15.0**

**Comment by WithoutPants** [comment]
I am unable to reproduce this. While the old preview video appeared initially, the new correctly generated video preview appeared after refreshing the page after the generate task completed.

**Comment by IAmKontrast** [comment]
Works as designed. You're right. Although Ctrl + F5 the cache still be used. Only open DevTools in Chrome with 'Disable cache' solved my problem. Thank you.
