### ISSUE TITLE
[Feature] Date information for Images like Scenes

### ISSUE THREAD

**Issue by IAmKontrast** [stashapp/stash#2617]
I would like to add 'date' information for images like for scenes. Currently it's only possible for galleries.

**Comment by ALonelyJuicebox** [comment]
I agree with you entirely, but this issue is a dupe of https://github.com/stashapp/stash/issues/2213 (which itself contains aspects of other similar issues 😅)

**Comment by IAmKontrast** [comment]
> I agree with you entirely, but this issue is a dupe of #2213 (which itself contains aspects of other similar issues 😅)

Damn. Sorry for the duplicate. I must have overlooked.
