### ISSUE TITLE
[Feature] Ability to set filtering criteria on home page

### ISSUE THREAD

**Issue by banananapisces** [stashapp/stash#2644]
**Is your feature request related to a problem? Please describe.**

At the moment the new landing/home page shows scenes sorted by date, in descending order, under the heading "Recently Released Scenes". 

**Describe the solution you'd like**

Since I sometimes add files that have an older date created I'd like the ability to set the home page to show "Recently Released Scenes" in descending order based on the modification date. This way I can always see what the newest added files to Stash are. 

**Describe alternatives you've considered**

An alternative would be to use a new default filter and set the Scenes tab as the home page. 

**Additional context**

None

**Comment by MrX292** [comment]
there is a pr #2592  to add the ability to customize recommendations on the homepage.

**Comment by banananapisces** [comment]
Thanks! I've subscribed to the PR and hope it gets merged soon.
