### ISSUE TITLE
[RFC] Human Action Recognition

### ISSUE THREAD

**Issue by rlleshi** [stashapp/stash#2646]
Hi guys, great project!

It was suggested on [this](https://www.reddit.com/r/learnmachinelearning/comments/v3yvam/deep_learning_classifier_for_sex_positions/) Reddit post, that using a (sex) position classifier would be an interesting feature for this project.

I basically build one with a self-generated, small dataset. You can check it out [here](https://github.com/rlleshi/phar). I imagine that you guys must have huge datasets that could be used to properly train these deep learning models. 

Let's discuss what can be expected out of these models!

**Comment by JediMaster25** [comment]
I would really like something like this, but the technology is not good enough to consider adding it to stash yet. The original repository could be turned into a [CommunityScript](https://github.com/stashapp/CommunityScripts) with an optional argument to pass the location of the stash database and work with that.

**Comment by rlleshi** [comment]
FYI: These models could yield much better results with a better dataset & some more effort.

**Comment by skier233** [comment]
Bumping on this. I feel it was dismissed too easily originally.

**Comment by DogmaDragon** [comment]
> I would really like something like this, but the technology is not good enough to consider adding it to stash yet. The original repository could be turned into a [CommunityScript](https://github.com/stashapp/CommunityScripts) with an optional argument to pass the location of the stash database and work with that.

I think so too, having a working plugin and building it up over time before making it part of the Stash is a great idea.
