### ISSUE TITLE
[Feature] Exclude samples

### ISSUE THREAD

**Issue by tritnaha** [stashapp/stash#266]
**Is your feature request related to a problem? Please describe.**
The ability to exclude samples (just like plex does) would be nice. Both on initial scanning and for already scanned libraries (ie, purge samples from db)

**Describe the solution you'd like**
Ability to drop all scanned samples from the DB via GUI, and for Stash not to include/scan samples.

**Describe alternatives you've considered**
None

**Comment by bnkai** [comment]
The scan part is almost there #253 
The drop part i think is relevant to issue #239

**Comment by WithoutPants** [comment]
@Leopere this good to close?

**Comment by Leopere** [comment]
Base functionality is ready but now a second PR #274 is coming along and #253 is completed.
