### ISSUE TITLE
[Bug Report] Error connecting to Handy: Handy firmware update required

### ISSUE THREAD

**Issue by Kyr4l** [stashapp/stash#2666]
**Describe the bug**
I can't connect a handy anymore since the latest update, stashapp refuses to connect to it, the latest firmware update is installed already

**To Reproduce**
go to settings, click interface, enter a handy connection key then connect, boom "Error connecting to Handy: Handy firmware update required"

**Expected behavior**
the handy should be connected

**Stash Version: (from Settings -> About):**
0.15.0

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version 101.0.1

**Comment by WithoutPants** [comment]
On the handyfeeling website, can you connect your Handy and print what the firmware version is? Stash was changed to require version 3.x.x.

On the handyfeeling website, this is what it shows for my device:
![image](https://user-images.githubusercontent.com/53250216/173482126-7bc96577-ef61-4935-99ab-ed6ea8142cc6.png)

**Comment by WithoutPants** [comment]
Can you confirm that it is version 3.2.3? I'm not sure why it's telling you to upgrade your firmware if it isn't, since that message comes from the Handy API.

**Comment by xioxin** [comment]
I can't update my handy due to network problems.
Maybe, Add an option to skip this version of the judgment
https://github.com/stashapp/stash/blob/dce4591911e4082c938172e69a0494846f34bc7b/ui/v2.5/src/hooks/Interactive/interactive.ts#L117-L119

**Comment by WithoutPants** [comment]
> I can't update my handy due to network problems. Maybe, Add an option to skip this version of the judgment
> 
> https://github.com/stashapp/stash/blob/dce4591911e4082c938172e69a0494846f34bc7b/ui/v2.5/src/hooks/Interactive/interactive.ts#L117-L119

The `updateRequired` status means that an update is required to actually use the Handy API, so skipping the check woudn't help.
