### ISSUE TITLE
Moving zipped galleries to new folder results in wrong image paths

### ISSUE THREAD

**Issue by sleetx** [stashapp/stash#2667]
Running into a bug with moving files.... I moved a bunch of gallery .zip's to a new folder and ran a scan in Stash... The stash galleries were updated to point to the correct location, but the individual images from the zip still point to the old location.

/path/new   << .zips moved here, Galleries correctly map to the new location
/path/old   << Images still retain their relationship to the gallery, but each image references the old location

So when I click on an affected image, the image that loads is blank, because it is trying to reference a nonexistent file path

**Comment by WithoutPants** [comment]
Fixed in #2611 

As a workaround, the following SQL will result in the zip being rescanned correctly when scan is subsequently run:

```
UPDATE galleries SET file_mod_time = '1970-01-01 00:00:00' WHERE path = '<full path to zip'>;
```
