### ISSUE TITLE
[Feature] Default filter for menu items

### ISSUE THREAD

**Issue by myalow** [stashapp/stash#2670]
**Is your feature request related to a problem? Please describe.**
When clicking on the scenes tab in the menu bar, I would, by default, like a random sort and have a tag filter pre-applied to remove VR videos from results by default. That way, when I'm on desktop, unless I'm seeking them out, I don't see VR videos in my feed. This could be applicable for other categories as well; for instance, I currently don't put male performers on my videos, as to not clutter up the performers tab. However, if I could have the performers tab default to filtering `exclude Male`, I wouldn't have to do this (and consequently, contributing to stashdb and other actions would be easier.)

**Describe the solution you'd like**
An option within stash settings to set default filters and sort orders per menu item.

**Describe alternatives you've considered**
Currently, I have bookmarks set up to exclude VR and sort by random. however, since its a bookmark, the random seed is the same every time, somewhat defeating the purpose.

**Additional context**
Ideally, each menu item should have its own unique "default filter". Each item should also have a default sort order.

**Comment by WithoutPants** [comment]
This is already supported. Set your filters/sort to what you want as the default, click on the bookmark button and select "Set as default".

![image](https://user-images.githubusercontent.com/53250216/173494108-f4d8a457-bc34-4b39-8bf9-5bac214de7e2.png)
