### ISSUE TITLE
[Feature] New homepage to use saved filter instead of "recent"

### ISSUE THREAD

**Issue by ukcuddlyguy** [stashapp/stash#2674]
**Is your feature request related to a problem? Please describe.**
After the new homepage has gone live (https://github.com/stashapp/stash/pull/2571) which I love, the "RECENTLY RELEASED SCENES" section doesn't seem to work well for me, i.e. it's not the most recently added scenes (release is a bit arbitrary). Even if it did, I would prefer to be able to customise this.

**Describe the solution you'd like**
The easiest customisation is to allow selection of a "Saved filter" from Scenes as the criteria for listing them. Then users can create whatever filtering, sort order, etc they wish.

**Describe alternatives you've considered**
That it could be feasible to just choose certain tags and a sort order, but that feels like re-inventing the wheel when saved filters already exist.

**Additional context**
![Screenshot 2022-06-15 at 15 06 41](https://user-images.githubusercontent.com/62703727/173847530-63242d64-1d16-4695-b67e-2e29d0a42c4c.png)

**Comment by Belleyy** [comment]
#2592 solve this

**Comment by MrX292** [comment]
was merged in #2592 to develop

**Comment by sleetx** [comment]
Yes, latest development release already has this functionality and it'll be in 0.16
