### ISSUE TITLE
[Bug Report] After adding new performer/tag/movie through scrape window, they disappear in the scrape window 

### ISSUE THREAD

**Issue by goldstar1x** [stashapp/stash#2691]
**Describe the bug**
When scraping a scene, if it scrapes a performer that doesn't exist, it'll add a + button with the performer name to give you an option to add the performer to the database. If I click the + button to add the performer, then the scrape window will not show performers anymore, and the scrape window will not be able to assign performers to the scene. The performer that is added does actually get added though. 

**To Reproduce**
1. Go to any scene with a performer that you don't have in your database
2. Click on Edit, and then Scrape with... choose a scraper that can scrape the scene correctly
3. Add the performer that doesn't exist using the + button 
4. Observe  the Performers section of the scrape window disappears

**Expected behavior**
Performers section should not disappear in the window, and the newly added performer should be added to the list of performers to be added to the scene. 

**Screenshots**
Before adding the performer:
![image](https://user-images.githubusercontent.com/65011124/175447615-89a58139-bc1b-4437-ab3a-8e0001730e69.png)

After adding the performer:
![image](https://user-images.githubusercontent.com/65011124/175448359-0b14f2cf-fbca-4306-b038-ec70fe8760c3.png)

**Stash Version: (from Settings -> About):**
v0.15.0-28-g63e1bbf3

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 102.0.5005.115

**Comment by goldstar1x** [comment]
found another detail about this bug, it only triggers if there is already another performer in the performer field before you try to add the new performer, so e.g:

Scene has 2 performers 
Performer 1 is already in the performer database
Performer 2 isn't in database yet 
Scrape scene 
Performer 1 is added to the performer fields
Performer 2 can be added with + button 
Add Performer 2 
Bug occurs. 

If both Performer 1 and Performer 2 aren't in the database, then when Performer 1 is added, the bug doesn't occur, but does when Performer 2 is added

**Comment by hmahler-2** [comment]
The same thing happens with tags and movies. Pressing OK results in the scene being "scraped" without tags, performers or movie. Pressing Cancel and retrying it a couple of times results in successful writing of the data to the scene record.

**Comment by goldstar1x** [comment]
ah really? ok I updated the title, thanks!

**Comment by TgSeed** [comment]
@goldstar1x @hmahler-2 The #2700 pull request has fixed it as far as i tested but would be great if you verify it too. to verify, you can download the fix in `Artifacts` section of [this page](https://github.com/stashapp/stash/runs/7062164596).

**Comment by hmahler-2** [comment]
Partial fix. When adding a performer (new or in database) to a scrape result, the green tick moves over to the old (blank) side rather than disappearing the box completely which is an improvement, maybe.

However it's still removing tags when scraping previously scraped scenes, etc.

**Comment by goldstar1x** [comment]
> Partial fix. When adding a performer (new or in database) to a scrape result, the green tick moves over to the old (blank) side rather than disappearing the box completely which is an improvement, maybe.

About the tick moving over to the existing side, rather than staying on the scraper side, this is a separate bug that I also noticed, I don't think that one is related to the attempted fix by @TgSeed

**Comment by TgSeed** [comment]
> Looks like WithoutPants has superceded @TgSeed's fix so I guess I don't need to test Tg's fix anymore?

Yeah thanks, he has fixed both issues.
