### ISSUE TITLE
[Feature] Filter with tags using include & exclude

### ISSUE THREAD

**Issue by JackDawson94** [stashapp/stash#2692]
**Is your feature request related to a problem? Please describe.**
Was discussed in Discord and seems many people find filtering with tags a bit frustrating right now. Tags are one of the most powerful features, but can only use one filter operator.
It's either **include** or **exclude** but can't combine the two. 

**Describe the solution you'd like**
I'd like to be able to filter tags (probably other types as well ? but mostly tags) with something like:
**include A & exclude B**

**Comment by xx790** [comment]
This is super frustrating, compared to booru/hydrus search queries.

I see no reason why available filter options are removed from the list when one instance is applied. They should be stackable.

I can manually craft an URL like
```http://localhost:9999/scenes?c=("type":"tags","value":("items":[("id":"6","label":"foo")],"depth":0),"modifier":"INCLUDES")&c=("type":"tags","value":("items":[("id":"8","label":"bar")],"depth":0),"modifier":"EXCLUDES")&perPage=1000&sortby=random_96764349```
but it doesn't seem to work - only one of `"type":"tags"` entries is applied while there should be no issue to apply them sequentially.

**Comment by WithoutPants** [comment]
This is due to the limitations of the existing graphql API. This can be done, but it requires refactoring of said API, which impacts both the backend code and the UI. It's not a single thing to fix.

**Comment by xx790** [comment]
Looks like someone outsmarted themselves
