### ISSUE TITLE
Sslforfree support

### ISSUE THREAD

**Issue by binarygeek119** [stashapp/stash#27]
I see you use a ssl Certificate in the stash Letsencrypt let's you use https://www.sslforfree.com if you use a domain to point to the stash right now I use noip to point to my stash be nice if you could make it easy to get a ssl Certificate for our url I can get it outside of the stash but other might not

**Comment by StashAppDev** [comment]
There are a couple of things we can do here.  We can allow the user to specify paths to their own certificate and key as a more advanced option.  Another option would be to get a domain and run a service like the one described [here](https://content.pivotal.io/blog/sslip-io-a-valid-ssl-certificate-for-every-ip-address).  That way anyone could use the ip address of their choice without having to generate a certificate.

**Comment by StashAppDev** [comment]
This should be possible now with [this change](https://github.com/stashapp/stash/commit/29a40c5bdd476587843f9946c0cc4807e00bee2c).  Once you have a certificate and key just place them in the appropriate place [as described here](https://github.com/stashapp/stash#ssl-https)
