### ISSUE TITLE
[Bug Report] 0% in tag name breaks tag's page

### ISSUE THREAD

**Issue by 7dJx1qP** [stashapp/stash#2711]
**Describe the bug**
Creating a tag with 0% in the name breaks the tag's details page preventing you from viewing/editing the tag.

**To Reproduce**
1. Create a tag named 0%
2. See error on next page
```
Something went wrong.
DetailsURIError: URI malformed
```
If you go back to the tags list you can see the tag, but if you click it you will get the same error.

**Expected behavior**
No error on the tag's details page so the tag can be viewed and edited.

**Stash Version: (from Settings -> About):**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome/Brave
 - Version: v0.15.0

**Comment by ALonelyJuicebox** [comment]
Related to https://github.com/stashapp/stash/pull/2552 which was designed for queries.
Special characters need to be properly encoded so URLs don't break.
