### ISSUE TITLE
Can't play media from Nginx reverse proxy

### ISSUE THREAD

**Issue by yed01** [stashapp/stash#2716]
When running stash through the server ip everything is working but if I use a reverse proxy I get the error "The media could not be loaded, either because the server or network failed or because the format is not supported."
Everything else is working except when I logout I'm landing on https://mydomain.com/login and not on https://mydomain.com/stash/login.
This is my nginx-config:

``` 
location ^~ /stash {
            set $upstream_app 127.0.0.1;
            set $upstream_port 9999;
            set $upstream_proto http;
            proxy_pass $upstream_proto://$upstream_app:$upstream_port;
            proxy_set_header X-Forwarded-Prefix /stash;
            proxy_set_header Host $http_host;
            rewrite ^/stash/(.*)$ /$1 break;
        }

**Comment by yed01** [comment]
Adding proxy_hide_header content-security-policy solved the media issue, but the logout problem is still there.

**Comment by yed01** [comment]
resolved

**Comment by billouetaudrey** [comment]
Hello, 

How to fix it on apache2 please ?

Thanks
