### ISSUE TITLE
[Feature] Ignore pictures from galleries in the images section

### ISSUE THREAD

**Issue by milkyshakes** [stashapp/stash#2727]
Many users, including me, have a mixture of gallery and non-gallery image content. Having every image in the same place makes it difficult to find non-gallery content as, typically, galleries contain copious amounts of pictures compared to the measly number of scavenged images downloaded from popular pornography websites such as Reddit or DuckDuckGo images.

Essentially, there should be a setting that allows you to disable showing any image that is part of a gallery in the images section.

A possible alternative could be to make the filters more prominent, for example the user could add tabs for each filter they make which would allow them to easily access grouped content.

**Comment by WithoutPants** [comment]
Can't this already be done by filtering on `Is Missing` -> `Galleries`?

**Comment by milkyshakes** [comment]
Yeah that works but I was wondering if it could be done by default. It seems rather inconvenient to always choose that filter

**Comment by milkyshakes** [comment]
Oh ok I'll do that then. Is there any chance that we might get custom tabs?

**Comment by JediMaster25** [comment]
It's a good idea. You should close this issue and open another to ask for it.
