### ISSUE TITLE
Make performer name mandatory

### ISSUE THREAD

**Issue by WithoutPants** [stashapp/stash#273]
Performer name is currently optional in the create performer graphql mutation. If performer name is not entered, then stash panics during the create performer routine. 

Performer name should be made mandatory and a helpful error message should be displayed if it is not entered.

**Comment by ueaslsef** [comment]
![image](https://user-images.githubusercontent.com/52797608/71445371-fb761000-2710-11ea-88aa-914fb1c3afa0.png)
Like this?

**Comment by Leopere** [comment]
Feel free to submit a pull request if you have tested your additional code just make sure to link it back to this issue.  I think this would be a valuable contribution to the codebase.
