### ISSUE TITLE
[Bug Report] Lightbox: Incorrect image displayed at first

### ISSUE THREAD

**Issue by QxxxGit** [stashapp/stash#2730]
Performer's detail page -> Images tab -> click an image that isn't the first image to open the lightbox. The first image will display. Closing the lightbox and trying to use it again works. Also, if you order the images by o-counter, the image changes when the o counter value is changed from the lightbox.

Using v0.16, confirmed with another user on Discord

**Comment by sleetx** [comment]
I've also noticed this bug when going straight to the Images page, not via Performer... Clicking on any image (for example, the 7th image in the view) opens the first image in the lightbox. This only seems to happen the first time an image is clicked in the view - later clicks open the correct image.
