### ISSUE TITLE
Files refactor bug reports

### ISSUE THREAD

**Issue by WithoutPants** [stashapp/stash#2737]
This is intended as a catch-all issue to report bugs with the `files-refactor` alpha branch.

Known issues are as follows:
* ~~import/export functionality is currently disabled. Needs further design.~~
* missing covers are not currently regenerated. Need to consider further, especially around scene cover redesign.
* ~~deleting galleries is currently slow.~~
* ~~`Don't include file extension as part of the title` scan flag is not supported.~~
* ~~`Set name, date, details from embedded file metadata` scan flag is not supported.~~
* ~~Draft submissions to stash-box currently give an `already in transaction` error.~~

Other notable changes:
* Object titles are now displayed as the file basename if the title is not explicitly set. The `Don't include file extension as part of the title` scan flag is no longer supported.
* `Set name, date, details from embedded file metadata` scan flag is no longer supported. This functionality may be implemented as a built-in scraper in the future.

Please report issues with the `files-refactor` build here.

**Comment by 7dJx1qP** [comment]
I got about a dozen of these errors while running my first full library scan post-migration:
```
level=error msg="updating files: executing `UPDATE `files` SET `basename`=?,`created_at`=?,`id`=?,`mod_time`=?,`parent_folder_id`=?,`size`=?,`updated_at`=?,`zip_file_id`=? WHERE (`files`.`id` = ?)` [[XXXXXXXXXX.avi 2022-08-04 09:36:28.7004594 -0400 -0400 672814 2022-06-30 09:30:11 -0400 -0400 8976 495341568 2022-08-04 09:36:28.7004594 -0400 -0400 <nil> 672814]]: database is locked"
```

And then a few of these errors:
```
level=error msg="error processing \"I:\\\\Sites\\\\XXXX\\\\images\\\\XXXX\\\\crop\\\\460x349\\\\nt\": creating folder \"I:\\\\Sites\\\\XXXX\\\\images\\\\XXXX\\\\crop\\\\460x349\\\\nt\": inserting into folders: executing `INSERT INTO `folders` (`created_at`, `mod_time`, `parent_folder_id`, `path`, `updated_at`, `zip_file_id`) VALUES (?, ?, ?, ?, ?, ?)` [[2022-08-04 10:47:06.7598688 -0400 EDT m=+5598.143112701 2021-05-09 14:02:00 -0400 EDT 43586 I:/Sites/XXXX/images/XXXX/crop/460x349/nt 2022-08-04 10:47:06.7598688 -0400 EDT m=+5598.143112701 <nil>]]: database is locked"
```

For context on my stash library size, the migration says it migrated 672809 files, db file size ~6GB, generated folder size ~200GB.

**Comment by 7dJx1qP** [comment]
Had an electrical power outtage midscan, but after starting the scan again it seems like it completed fine and I didn't get any database is locked errors.

One thing I've noticed is there's a significant performance regression on the scenes page load time. My stash is about ~100k scenes and on v1.16.1 it takes less than half a second to load a page size of 20. With the files-refactor it takes between 1.5-2 seconds to load a page size of 20. The difference is much more noticable when I try a page size of 1000. On v1.16.1 it takes about 4-5 seconds while on the files-refactor it's taking around 90 seconds.

The homepage, movies, and markers pages are similarly much slower. The Images, Galleries, Performers, Studios, and Tags pages load times seem the same.

**Comment by skier233** [comment]
I found a bug with the statistics Scenes duration stat that shows your total scenes durations. It appears to be querying the scenes table and summing the duration but the scenes table no longer has a duration column.

**Comment by ferengi82** [comment]
i tried the new experimental version and get the following error at the schema migration

An error occurred migrating the database to the latest schema version. The backup database file was automatically renamed to restore the database.
error performing migration: running post migrations for schema version 32: migrating files: UNIQUE constraint failed: files.parent_folder_id, files.basename

**Comment by djbtwothousandtwenty** [comment]
one of my filters for Galleries has broken. I've made different views, where i've got some paths on my nas systems that contain "favorited models" and some paths contain stuff that's fully unsorted or only sorted by studio. I filter those out with an exclude filter like:

path : excludes : \Studios\

as the path of the files is for example file://nasname/foldername/Studios/studioname/performername/somefile.zip

I did try /Studios/ as well, no difference.

This worked on 0.16.1. I'm running this on Windows with the shares on the NAS mounted via SMB

**Comment by djbtwothousandtwenty** [comment]
There's a bug in the Settings on the Tasks tab. On setting any of the settings for Library Scan, and hitting the Scan button, all settings for Library Scan get disabled.

**Comment by djbtwothousandtwenty** [comment]
> 

this has been fixed for me with #https://github.com/stashapp/stash/pull/2811

**Comment by djbtwothousandtwenty** [comment]
> I got about a dozen of these errors while running my first full library scan post-migration:
> 
> ```
> level=error msg="updating files: executing `UPDATE `files` SET `basename`=?,`created_at`=?,`id`=?,`mod_time`=?,`parent_folder_id`=?,`size`=?,`updated_at`=?,`zip_file_id`=? WHERE (`files`.`id` = ?)` [[XXXXXXXXXX.avi 2022-08-04 09:36:28.7004594 -0400 -0400 672814 2022-06-30 09:30:11 -0400 -0400 8976 495341568 2022-08-04 09:36:28.7004594 -0400 -0400 <nil> 672814]]: database is locked"
> ```
> 
> And then a few of these errors:
> 
> ```
> level=error msg="error processing \"I:\\\\Sites\\\\XXXX\\\\images\\\\XXXX\\\\crop\\\\460x349\\\\nt\": creating folder \"I:\\\\Sites\\\\XXXX\\\\images\\\\XXXX\\\\crop\\\\460x349\\\\nt\": inserting into folders: executing `INSERT INTO `folders` (`created_at`, `mod_time`, `parent_folder_id`, `path`, `updated_at`, `zip_file_id`) VALUES (?, ?, ?, ?, ?, ?)` [[2022-08-04 10:47:06.7598688 -0400 EDT m=+5598.143112701 2021-05-09 14:02:00 -0400 EDT 43586 I:/Sites/XXXX/images/XXXX/crop/460x349/nt 2022-08-04 10:47:06.7598688 -0400 EDT m=+5598.143112701 <nil>]]: database is locked"
> ```
> 
> For context on my stash library size, the migration says it migrated 672809 files, db file size ~6GB, generated folder size ~200GB.

i've got a few of these database locked errors as well during the first scan after db migration:

time="2022-08-08 18:34:01" level=error msg="updating files: executing `UPDATE `files` SET `basename`=?,`created_at`=?,`id`=?,`mod_time`=?,`parent_folder_id`=?,`size`=?,`updated_at`=?,`zip_file_id`=? WHERE (`files`.`id` = ?)` [[videoname.4k.mp4 2022-08-08 18:30:41.7705847 +0200 +0200 7095946 2022-08-08 08:19:25 +0200 +0200 91365 1892803057 2022-08-08 18:30:41.7705847 +0200 +0200 <nil> 7095946]]: database is locked"

**Comment by 7dJx1qP** [comment]
Tried the latest file-refactor release and still getting slow performance. Using the network tab to measure times now, on v1.16.1 with 1000 page size and random sort order I get graphql requests taking ~3s. On the files-refactor it's ~1.2min.

I looked through the logs with log level trace and it looks like the total logged SQL query time is neglible compared to the overall time taken and the slow performance is coming from something else.

**Comment by djbtwothousandtwenty** [comment]
> 

i see the same issue here. on 0.1.16 im able to rescan my full library within 8 hours, on the refactor version it's been going for over 2 days and is about 20% in. I don't want to complain about performance, but there's definitely a performance regression somewhere. I've tried to find if there were any slow queries being logged, but most, if not all db calls seem to be around 513.1µs. I've experimented with the thread count in settings, going between 0 and increments of 2 up to 20 to see if that makes a difference, my cpu is a 12 core (24 with hyperthreading), but that hardly seems to make a difference.

An observation is that only during scanning/thumbprinting of large videofiles, does the network adapter ever get fully taxed up to the 1gbit maximum, where with 0.16.1 that'd be happening regardless of whether it was processing video files or images. Processing just galleries consisting of jpg files (no zips) on 0.16.1 would get network speeds between 700mbit and 1000mbit on my environment. So far the initial scan has not reached the gallery zip files yet, so i still need to see if those speed up the process.

**Comment by djbtwothousandtwenty** [comment]
a Clean, empty db makes a world of difference. Comparing 0.16.0 to filesrefactor as below, with the same dataset (109gb of mixed video both sd, 1080p and 4k and image content without zips consisting of 23.713 files and 378 folders.) on the same hardware and with the exact same configuration: 

<html>
<body>
<google-sheets-html-origin>

version | clean/existing | First scan | Second scan | first scan difference | second scan difference | % first scan | % second scan
-- | -- | -- | -- | -- | -- | -- | --
v0.16.1-1-gcba0fddf | clean | 0:29:07 | 0:00:09 |   |   |   |  
files-refactor-release-1-g27007365 | clean | 0:59:33 | 0:00:40 | 0:30:26 | 0:00:31 | 51.11% | 77.50%


</body>
</html>

starting the scan over that same set on files-refactor with the full "production db", i can immediately see the speed in the log file dropping. when it finishes i'll update the table

**Comment by skier233** [comment]
I'm experiencing an issue where when I try to delete scenes, the source files are not deleted.

**Comment by MrX292** [comment]
some scene sort options do not work like File Size, Interactive and Interactive speed.
i get for
File Size:
```error finding IDs: running query: SELECT DISTINCT scenes.id FROM scenes ORDER BY cast(scenes.size as integer) DESC LIMIT 40 OFFSET 0 [[]]: error executing `SELECT DISTINCT scenes.id FROM scenes ORDER BY cast(scenes.size as integer) DESC LIMIT 40 OFFSET 0 ` [[]]: no such column: scenes.size```
Interactive:
```error finding IDs: running query: SELECT DISTINCT scenes.id FROM scenes ORDER BY scenes.interactive DESC LIMIT 40 OFFSET 0 [[]]: error executing `SELECT DISTINCT scenes.id FROM scenes ORDER BY scenes.interactive DESC LIMIT 40 OFFSET 0 ` [[]]: no such column: scenes.interactive```
Interactive speed:
```error finding IDs: running query: SELECT DISTINCT scenes.id FROM scenes ORDER BY scenes.interactive_speed DESC LIMIT 40 OFFSET 0 [[]]: error executing `SELECT DISTINCT scenes.id FROM scenes ORDER BY scenes.interactive_speed DESC LIMIT 40 OFFSET 0 ` [[]]: no such column: scenes.interactive_speed```

**Comment by djbtwothousandtwenty** [comment]
> a Clean, empty db makes a world of difference. Comparing 0.16.0 to filesrefactor as below, with the same dataset (109gb of mixed video both sd, 1080p and 4k and image content without zips consisting of 23.713 files and 378 folders.) on the same hardware and with the exact same configuration:
> 
> version	clean/existing	First scan	Second scan	first scan difference	second scan difference
> v0.16.1-1-gcba0fddf	clean	0:29:07	0:00:09	 	 
> v0.16.1-1-gcba0fddf	existing	0:30:32	0:00:11	0:01:25	0:00:02
> files-refactor-release-1-g27007365	clean	0:59:33	0:00:40	0:30:26	0:00:31
> files-refactor-release-1-g27007365	existing	1:21:56	1:30:10	0:52:49	1:30:01
> Edited: 4 runs over same content in 2 configurations (deleted db and with the existing "production db from 0.16.1).

think i might have solved this issue, ran an ANALYZE and PRAGMA OPTIMIZE command on my sqlite db while it was slowly chugging along, right after that the speed increased exponentially, back to 0.16.1 speeds (at least visually in the UI). Will leave it running and then see what's different in the db compared to the non analyzed / optimized versions.

**Comment by djbtwothousandtwenty** [comment]
> I'm experiencing an issue where when I try to delete scenes, the source files are not deleted.

i can not reproduce this on my environment, deleting scenes works fine for me. It seems to create a whateverthefilenamewas.mp4.delete file which i then find in my recycle bin on the nas.

**Comment by djbtwothousandtwenty** [comment]
> some scene sort options do not work like File Size, Interactive and Interactive speed. i get for File Size: `` error finding IDs: running query: SELECT DISTINCT scenes.id FROM scenes ORDER BY cast(scenes.size as integer) DESC LIMIT 40 OFFSET 0 [[]]: error executing `SELECT DISTINCT scenes.id FROM scenes ORDER BY cast(scenes.size as integer) DESC LIMIT 40 OFFSET 0 ` [[]]: no such column: scenes.size `` Interactive: `` error finding IDs: running query: SELECT DISTINCT scenes.id FROM scenes ORDER BY scenes.interactive DESC LIMIT 40 OFFSET 0 [[]]: error executing `SELECT DISTINCT scenes.id FROM scenes ORDER BY scenes.interactive DESC LIMIT 40 OFFSET 0 ` [[]]: no such column: scenes.interactive `` Interactive speed: `` error finding IDs: running query: SELECT DISTINCT scenes.id FROM scenes ORDER BY scenes.interactive_speed DESC LIMIT 40 OFFSET 0 [[]]: error executing `SELECT DISTINCT scenes.id FROM scenes ORDER BY scenes.interactive_speed DESC LIMIT 40 OFFSET 0 ` [[]]: no such column: scenes.interactive_speed ``

confirmed on my environment

**Comment by djbtwothousandtwenty** [comment]
i'm missing the "Duplicated (phash)" filter option on Images. Could be since all images do appear to have a fingerprint (Md5 based) which is not phash. Not sure if phash is in the cards for images and galleries. With galleries it could be interesting to first generate a one image mosaic of all images in the gallery so you end up with a similar object as with the scenes, and then run the phash logic over it to identify similar/very similar/exactly the same galleries based on content. guess that would only work on galleries that have the same image count and order, but it'd be a good start?

anyway, what i guess i'm saying is: i'm missing a filter to figure out which duplicate images i have.

**Comment by skier233** [comment]
> > I'm experiencing an issue where when I try to delete scenes, the source files are not deleted.
> 
> i can not reproduce this on my environment, deleting scenes works fine for me. It seems to create a whateverthefilenamewas.mp4.delete file which i then find in my recycle bin on the nas.

Hmm. On my system the file I was trying to delete is on a different drive than where stash is running from. Maybe this could be a factor?

**Comment by 7dJx1qP** [comment]
> > > I'm experiencing an issue where when I try to delete scenes, the source files are not deleted.
> > 
> > 
> > i can not reproduce this on my environment, deleting scenes works fine for me. It seems to create a whateverthefilenamewas.mp4.delete file which i then find in my recycle bin on the nas.
> 
> Hmm. On my system the file I was trying to delete is on a different drive than where stash is running from. Maybe this could be a factor?

Is the "Delete file (and funscript)" option selected when you delete?

**Comment by skier233** [comment]
Yea. And I tried it a few times and it seems to always have the same behavior.

**Comment by djbtwothousandtwenty** [comment]
small bug, the folder crawler finds folders which have an image that is within the excluded filenames list, but still adds a folder for it:

`Performerfoldername doesn't exist. Creating new folder entry...`

it should probably check whether the content that triggered the folder crawler to find the folder, was only a file that's not wanted in the db

**Comment by djbtwothousandtwenty** [comment]
on re-scanning zip galleries i mainly get these:

error processing "\\\\nas\\galleryfolder\\galleryfilename.zip": adding file to gallery: inserting into galleries_files: executing `INSERT INTO `galleries_files` (`gallery_id`, `primary`, `file_id`) VALUES (114849, 0, 7072240)` [[]]: UNIQUE constraint failed: galleries_files.gallery_id, galleries_files.file_id

**Comment by djbtwothousandtwenty** [comment]
on the performer page > Galleries view, sorting by Path (ascending or descending) does not change the sort order anymore

**Comment by djbtwothousandtwenty** [comment]
Using the clean task, on deleted scenes (deleted outside of stash)

2022-08-16 23:01:09
Error   
Error deleting folder "\\\\nas\\folder\\filename.1080p.MP4" from database: destroying folders: executing `DELETE FROM `folders` WHERE (`folders`.`id` IN (92216))` [[]]: FOREIGN KEY constraint failed

**Comment by djbtwothousandtwenty** [comment]
> Scan settings issue has been fixed for me with ##2811

i've found one more location where this still happens: if I set the generate options for Scan task all to ON, but do not hit the scan buttons, it seems to save the setting correctly. it resets those specific sliders to the OFF position immediately after hitting the Generate button though

**Comment by djbtwothousandtwenty** [comment]
the autotagger seems to increasingly take longer time over each set of 1000 items it processes:

SLOW SQL [302.7667ms]: SELECT DISTINCT images.id FROM images LEFT JOIN images_files ON images_files.image_id = images.id LEFT JOIN files ON images_files.file_id = files.id LEFT JOIN folders ON files.parent_folder_id = folders.id WHERE (((folders.path LIKE ? AND files.basename LIKE ?) OR (folders.path LIKE ?)) AND (images.organized = 0)) LIMIT 1000 OFFSET 594000 , args: [//nas/foldername % //nas/foldername/%]

^ that's after about 600000 images

**Comment by djbtwothousandtwenty** [comment]
Galleries no longer get tagged for me, no errors in the logs. Images inside the galleries do get tagged correctly, but not the folder based gallery.

**Comment by ferengi82** [comment]
the renamerOnUpdate doesn't work with this release, maybe there are other plugins that are affected.
https://github.com/stashapp/CommunityScripts/issues/73

**Comment by ferengi82** [comment]
when you try to submit a new performer to stash-box I got an error
```
Submission failed
already in transaction
```

**Comment by scruffynerf** [comment]
> the renamerOnUpdate doesn't work with this release, maybe there are other plugins that are affected. [stashapp/CommunityScripts#73](https://github.com/stashapp/CommunityScripts/issues/73)

Wouldn't be surprised, it does direct SQL.  This is why using GraphQL is safer.
Yes, renamerOnUpdate and other scrapers/plugins/scripts that use sqlite to talk directly will likely all break, and need to be rewritten.  That's expected, with a major rewrite like this.

**Comment by WithoutPants** [comment]
Thanks for the continued feedback. 

#2849 fixes the following reported issues:

* Fixed sql error when sorting on some file-based scene fields
* Fixed path sorting for folder-based galleries
* Fixed path filtering not working correctly for folder-based galleries
* Fixed autotag not applying to folder-based galleries
* Fixed transaction error when submitting performers to stash-box

> the autotagger seems to increasingly take longer time over each set of 1000 items it processes:

This is an issue with the existing system as well. It requires some performance tuning that I won't be addressing in the short term.





> on re-scanning zip galleries i mainly get these:
> 
> error processing "\\nas\galleryfolder\galleryfilename.zip": adding file to gallery: inserting into galleries_files: executing `INSERT INTO `galleries_files` (`gallery_id`, `primary`, `file_id`) VALUES (114849, 0, 7072240)` [[]]: UNIQUE constraint failed: galleries_files.gallery_id, galleries_files.file_id

> Using the clean task, on deleted scenes (deleted outside of stash)
> 
> 2022-08-16 23:01:09 Error Error deleting folder "\\nas\folder\filename.1080p.MP4" from database: destroying folders: executing `DELETE FROM `folders` WHERE (`folders`.`id` IN (92216))` [[]]: FOREIGN KEY constraint failed
> 
> this also occurs on zip files that no longer exist.

I haven't been able to reproduce these issues. I'll probably need a more specific scenario.

I also haven't been able to reproduce the file deletion issue.

**Comment by MrX292** [comment]
i cant use part of the scene path in Scene Filename Parser in the Filename Pattern like `X:\\Downloads\\p_v\\Studio\\{title}.{ext}` for Windows anymore. Which worked in v0.16.1-1-gcba0fddf

**Comment by djbtwothousandtwenty** [comment]
unfortunately, the issue with the cleaner not cleaning, remains. I can post a log file, but the main way i can reproduce this is by:

- adding a library path to a new "location" for stash. the folderstructure i think might not matter, but i'll get back to that. 
- let stash scan the contents, which consists of a folder, with a folder per performer, with the content in folders in that folder, so something like \\nasname\stashfoldername\models\performername\imagesetname.XXX.IMAGESET\ is what i used. it happens on zip files, scenes and images / folders alike, so im not sure the content type makes a difference. 
- i then go in file explorer, delete some of those folders, does not seem to matter if it's the imageset folder, the scene file, zip file or even a file within the zip, i could remove the models folder, or just the one performer folder, and the cleaner correctly identifies what's missing each and every time.
- run clean task

what i see in the logs is:

level=info msg="Folder not found. Marking to clean: "\\nasname\foldername\models\performername\imagesetname.XXX.IMAGESET""

followed after a few minutes by:

level=error msg="Error deleting folder "\\\\nasname\\foldername\\models\\performername\\imagesetname.XXX.IMAGESET" from database: destroying folders: executing DELETE FROM folders WHERE (folders.id IN (37762)) [[]]: FOREIGN KEY constraint failed"

there's a difference between the folder it mentions the first time while correctly noticing the folder is missing, and the second time while trying to remove it, but im not sure if that's just the way the logger prints the path, or if it's actually trying to delete that quoted path literally, because that's having a few too many \ characters
all of this on windows, with a smb share
all on my "production" db as well, that i copied over from 0.16.1, will see if i can reproduce the same issue with a fully clean new db as well

going to a scene in stash, and deleting it manually from stash, seems to result in a deletion, as in: the scene is no longer visible in the Scenes overview page as expected. However the cleaner still seems to know about it, and still tries to remove it, so i guess there's still a folder or path reference in the db for it
for gallery, this is exactly the same, going to look for imagesetname.XXX.IMAGESET yields no results in the galleries view
also no results for that gallery name in the images view
so it appears visually in stash, that there's no problem, except the cleaner still has a reference to it that it's not able to remove.

**Comment by WithoutPants** [comment]
The latest build changes the way that paths are stored in the `folders` table for Windows users. Windows users will need to re-migrate from the version 31 schema, or manually adjust the `path` column to user `\` instead of `/` as path separators.

This should address the filename parser regression and should fix autotagging on Windows systems. I'm hoping that this will also fix the cleaning issue reported, but please retest and let me know.

**Comment by WithoutPants** [comment]
The latest build should properly fix the clean issue reported above. It also re-introduces the import/export functionality.

**Comment by djbarney** [comment]
confirmed, clean task is working as it should again, thanks!

**Comment by djbtwothousandtwenty** [comment]
with the latest build files-refactor-release-1-g0aad77d7

have got 2 very similar (but not 100% identical) scene files, that i found with the scene duplicates finder. one file is higher resolution and comes in at 19mb, the other has a different name and is smaller, so i want to delete it. Hitting "delete" and selecting that i also want to delete the file itself + all generated stuff, i get an error. log only spits out:

`time="2022-09-01 12:31:14" level=error msg="relationship has not been loaded"`

got another new error in the log, unfortunately it does not say which tag or which image file it had issues with:

`time="2022-09-01 13:33:17" level=info msg="Autotagging images..."`
`time="2022-09-01 13:33:19" level=error msg="error tagging image performers for : error executing SELECT performers.* FROM performers  WHERE ignore_auto_tag = 0 AND () [[]]: near ")": syntax error"`

**Comment by skier233** [comment]
Trying to delete scenes that are currently open (even if paused) in the scene viewer yields the following error:
![Capture](https://user-images.githubusercontent.com/39396856/188158616-c77bf3b3-89cb-40d7-b539-3921390a5f52.PNG)

Instead, any processes holding the file should be terminated on deletion.

**Comment by DogmaDragon** [comment]
> Trying to delete scenes that are currently open (even if paused) in the scene viewer yields the following error: ![Capture](https://user-images.githubusercontent.com/39396856/188158616-c77bf3b3-89cb-40d7-b539-3921390a5f52.PNG)
> 
> Instead, any processes holding the file should be terminated on deletion.

Tested and it works in v0.16.1-8e222ae3.

**Comment by WithoutPants** [comment]
> Trying to delete scenes that are currently open (even if paused) in the scene viewer yields the following error: 
> Instead, any processes holding the file should be terminated on deletion.

I'm not able to reproduce this. Is this doing a direct stream or live transcoding?

**Comment by skier233** [comment]
> > Trying to delete scenes that are currently open (even if paused) in the scene viewer yields the following error:
> > Instead, any processes holding the file should be terminated on deletion.
> 
> I'm not able to reproduce this. Is this doing a direct stream or live transcoding?

@WithoutPants It's on direct stream with mp4 files (at least).

**Comment by WithoutPants** [comment]
> @WithoutPants It's on direct stream with mp4 files (at least). Maybe something to try would be having multiple stash tabs open too? I usually have one stash tab open with a list of scenes and individual stash tabs for each scene.

Still unable to reproduce. What's the exact steps to reproduce? Is `E:\` in the above screenshot on the local machine or over network?

**Comment by skier233** [comment]
> > @WithoutPants It's on direct stream with mp4 files (at least). Maybe something to try would be having multiple stash tabs open too? I usually have one stash tab open with a list of scenes and individual stash tabs for each scene.
> 
> Still unable to reproduce. What's the exact steps to reproduce? Is `E:\` in the above screenshot on the local machine or over network?

E: is on the local machine. The steps is basically just opening a tab for a scene and starting to play the scene and then delete. Make sure you are trying a full delete with both options selected. Also make sure the video plays for like 30 seconds or so before you try it. Im using brave browser though I doubt that matters.

**Comment by WithoutPants** [comment]
This is the procedure I've used to try to reproduce this:
- scan file and generate sprites and preview
- locate file in scenes page, open scene in new tab
- play scene for at least 30 seconds - I've also tried scrubbing around the scene randomly
- on the scene page, click on the Edit tab, then the Delete button
- tick both Delete File and Delete generated options and click the Delete button
- system indicates scene was deleted successfully and returns to scenes page
- verified file was removed from the filesystem

I assume you can remove scene files successfully if you do so without playing the scene (in the scene page and the scenes page)?

**Comment by skier233** [comment]
> This is the procedure I've used to try to reproduce this:
> 
> * scan file and generate sprites and preview
> * locate file in scenes page, open scene in new tab
> * play scene for at least 30 seconds - I've also tried scrubbing around the scene randomly
> * on the scene page, click on the Edit tab, then the Delete button
> * tick both Delete File and Delete generated options and click the Delete button
> * system indicates scene was deleted successfully and returns to scenes page
> * verified file was removed from the filesystem
> 
> I assume you can remove scene files successfully if you do so without playing the scene (in the scene page and the scenes page)?

Yea I can delete them no problem if I delete before playing the video.

**Comment by djbtwothousandtwenty** [comment]
i've also tried to reproduce the issue @skier233 reported, but so far i've not been able to either. This is with items scanned (and fully phash / preview generated) beforehand, deleting while playing stops the file and deletes it succesfully and returns me back to the scenes view. in my case using chrome, on windows 11, with the files mounted on a smb share on a nas. I can see that the delete action first renames the file to add ".delete" after the extension and then proceeds to delete it.

**Comment by djbtwothousandtwenty** [comment]
during the scan after re-migration for version files-refactor-release-1-gcfc8222b, it notices as gallery folder as not yet existing (it's one that got a bit of the path changed). it creates an empty gallery, with no files in it, even though the scan log indicates that it found all the files as pre-existing files based on thumbprint, knows both old path and new path and says it's updating the path for the image.

log entries:

galleryname.XXX.IMAGESET doesn't exist. Creating new folder entry...
Calculating fingerprints for galleryname.XXX.IMAGESET\001.jpg ..."
\\nas\folder\performers\oldperformername\galleryname.XXX.IMAGESET\001.jpg moved to \\nas\folder\performers\newperformername\galleryname.XXX.IMAGESET\001.jpg. Updating path..."

it does this calculating, "moved to" for all 119 files correctly

looking for that gallery through the galleries view, i've got the "old one" and the new empty one, with the old gallery info pointing to the old path: \\nas\folder\performers\oldperformername\galleryname.XXX.IMAGESET\, but it has all 119 images and the images are all loading correctly. The new empty gallery is pointing to the new location: \\nas\folder\performers\newperformername\galleryname.XXX.IMAGESET\

the individual images are only connected to the old gallery, and they have been correctly updated to reflect the new path. so i think there might be a bug with the gallery update statement, where it creates a new one, instead of updates the existing one to the new path like it does for the images. this specific gallery had no duplicates either as far as i'm aware

After re-migration, initial scan, clean and another scan, i've now got 45 empty galleries like this

**Comment by skier233** [comment]
> i've also tried to reproduce the issue @skier233 reported, but so far i've not been able to either. This is with items scanned (and fully phash / preview generated) beforehand, deleting while playing stops the file and deletes it succesfully and returns me back to the scenes view. in my case using chrome, on windows 11, with the files mounted on a smb share on a nas. I can see that the delete action first renames the file to add ".delete" after the extension and then proceeds to delete it.

I tested with chrome and verified the same behavior. Also, verified the behavior while on the latest version of the files-refactor branch. Not sure why you'll aren't able to repro when I see the error every time :/

**Comment by skier233** [comment]
@WithoutPants Aha! I've found what's different and why you aren't able to repro. It only occurs if stash is using an ssl key and running with https. When I disabled https then the issue went away!

**Comment by WithoutPants** [comment]
> @WithoutPants Aha! I've found what's different and why you aren't able to repro. It only occurs if stash is using an ssl key and running with https. When I disabled https then the issue went away!

Thank you, I have reproduced locally using https.

**Comment by WithoutPants** [comment]
`files-refactor` branch is now merged to `develop`. Thank you for the bug reports and testing.

**Comment by A-Random-Mf** [comment]
Sorry to reopen the issue but Keyword/comma filtering doesnt work properly in the latest dev build.
Ex) Path excludes: Various Files, kemono-dl
It used to exclude those directories from the search now it doesn’t. Path excludes: Various Files works and Path excludes: kemono-dl works but they don’t work together. OR AND both make no difference

**Comment by WithoutPants** [comment]
Please raise a new issue for further bugs.

**Comment by A-Random-Mf** [comment]
https://twitter.com/enclopez_/status/1569054279742427136?s=21
