### ISSUE TITLE
Stash states wrong resolution

### ISSUE THREAD

**Issue by insickin** [stashapp/stash#2751]
**Describe the bug**
When I import a 4K (3840x2160) video Stash sees it as a 720P video, the reason is that Namer picks up the embedded poster/cover art in the video file

**To Reproduce**
1. Go open a scene
2. Click on file info
3. See error

**Expected behavior**
That Stash reports the file as a 4K video

**Screenshots**
Stash:
https://media.discordapp.net/attachments/559159910550732809/998584986313703584/Stash.png
MediaInfo:
https://media.discordapp.net/attachments/559159910550732809/998585286172872775/MediaInfo.png?width=388&height=701

**Stash Version: (from Settings -> About):**
v0.16.0
Build hash:
351472f6

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[ffprobe.txt](https://github.com/stashapp/stash/files/9133667/ffprobe.txt)

We were discussing the problem on Discord:
https://discord.com/channels/559159668438728723/559159910550732809/998584952281108592

**Comment by scruffynerf** [comment]
You can make a problem video by using https://github.com/ThePornDatabase/namer to embed a video thumbnail into the metadata.
