### ISSUE TITLE
[Feature] Allow a user to set a default sorting option

### ISSUE THREAD

**Issue by johndoethemaster** [stashapp/stash#2753]
**Is your feature request related to a problem? Please describe.**
When loading up the site, the default sorting order is always by the date. It consistently requires extra steps for me to change to my preferred sorting option (random).

**Describe the solution you'd like**
Similar to how I can set a default filter, `I would really like to be able to set a default sorting option`. I believe this default should save both the sorting type (`e.g., random, date`, etc.) as well as order (e.g., ascending or descending). Additionally it would be fantastic if the number of results selected (e.g., 40, 60, 120, etc., was also saved).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by scruffynerf** [comment]
It does save the sort order.

**Comment by johndoethemaster** [comment]
So it does, sorry about that!! Saves it with the save default filter.
