### ISSUE TITLE
[RFC] Re-License to AGPL or Other for the sake of keeping this open source long term.

### ISSUE THREAD

**Issue by Leopere** [stashapp/stash#276]
Reply with a license and version we want and then contributors up to date will need to thumbs up to agree with a specific license all contributors must agree.

##  Long Form

If you wish to suggest and pitch your own license alternative you're welcomed to pitch one.  My suggestion is to drive Stash to be a forever FOSS project and to have a fully open source API where sustainability is possible and the governance model doesn't matter.  

If all tools are required to be open sourced and licensed under AGPL we can ensure that the API will forever be publicly available for the world despite any financial renumeration schema we adopt.

## Process Steps

- [ ] Collect thumbs ups on whatever licenses are proposed.
- [ ] Screenshot and upload into the git issue logs of all of the Thumbs Up's.
- [ ] Screenshot and upload into the git issue logs all of the contributors to date.
- [ ] Merge PR #277 

## Reference Reading

https://choosealicense.com/licenses/agpl-3.0/

**Comment by FleetingOrchard** [comment]
I have to admit, I'm not sure the thumbs up would be a viable way to show that a given contributor has relicenced their contributions to stash under the new, desired licence. It would probably be easier to simply ask each contributor for a short statement to the effect of relicencing their work.

But it's a good idea, and AGPL is a good pick.

**Comment by Leopere** [comment]
Realistically we just need some record of an agreement.   If anything we can commit the screenshots to the repository for one commit/PR or something then remove the file in subsequent builds just so that it's in the history.

**Comment by StashAppDev** [comment]
@friendlycrab @endqwerty @ExceptionalError @echo6ix @rudi123github @joyov @InfiniteTF 

Tagging every contributor who I haven't seen comment yet.  Do you folks mind commenting or adding a +1 with your approval / disapproval?

**Comment by endqwerty** [comment]
:+1:
Any changes now or in the future to the license or otherwise for any content which I have contributed to this project are approved by me.

**Comment by ExceptionalError** [comment]
I approve the change to AGPL.

**Comment by WithoutPants** [comment]
I approve the change to AGPL.

**Comment by WithoutPants** [comment]
Assuming that we're not retrospectively changing the license of existing code and the license change applies only once the PR is merged, I think we should set a deadline for objections and just go ahead otherwise.

**Comment by WithoutPants** [comment]
I also don't think screenshotting is necessary.

**Comment by Leopere** [comment]
@WithoutPants I agree with the screenshot being not necessary.  It was just a quick idea to solve the problem I'm indifferent so long as we get everyone on board who needs to be.

**Comment by joyov** [comment]
I approve the change to AGPL.

IMO taking a screenshot is a good idea since comments can be deleted. Maybe even ask some people to verify the screenshot is legit (after merging this).

**Comment by Leopere** [comment]
I'll probably include some kind of logs and screenshots in the license PR
and then remove the cruft in the subsequent commits so that it's
retrievable by digging into the commit history but doesn't bloat the repo.
Then we can just reference that commit if people really wanted the MIT
licensed version of this software to fork from.

**Comment by WithoutPants** [comment]
Closing this as the transition seems to be done.
