### ISSUE TITLE
[Feature] Ability to use symbolic links for videos

### ISSUE THREAD

**Issue by cambiph** [stashapp/stash#2760]
It would be nice to see if stash can correctly handle symbolic links. Because of torrenting and seeding, I have a specific directory structure. At the moment of writing, I need to copy my videos to a different folder. It would be excellent if I could just create symbolic links and stash would be able to pick them up.

I tested it with the current version of stash but the symbolic link does not get picked up (created with ln -s).

**Comment by MrX292** [comment]
symbolic links work for me on windows. can you describe the problem more?

**Comment by cambiph** [comment]
I created the symbolic link using `ln -s originalFile newFile` and it is showing as follows on my filesystem:
![2022-07-29 10_03_08-](https://user-images.githubusercontent.com/1628243/181713666-7476cc33-8a34-4047-abea-c35784d37ebc.png)

However, when I click 'Scan' in Stash settings, no new file is detected.

**Comment by 7dJx1qP** [comment]
What do you see in the scan logs (Settings -> Logs)? It's possible you have an exact duplicate file already in Stash, in which case it will skip the new file saying it's a duplicate.
Example:

```
Finished counting files. Total files to scan: 6, 1 new files found
newfile.mp4 already exists. Duplicate of original.mp4
Scan finished
```

If your log shows `0 new files found` then it's truly not being detected

**Comment by cambiph** [comment]
The log is showing the following:

`error scanning /data/Kiwi Sweet.mp4: lstat /data/Kiwi Sweet Gets Banged & Enjoys A Hard Cock Before Getting Facialized - Teen Tryouts Audition 11 - Remaster & AI Upscale 1080p (Request) [Epaminondas].mp4: no such file or directory`

I am using stash inside a Docker image. I assume that the volume mapping might be an issue or something?

**Comment by WithoutPants** [comment]
This does not look like a stash issue. Closing as stale in any case.
