### ISSUE TITLE
[Feature] Limiting CPU cores/threads during preview generation

### ISSUE THREAD

**Issue by Quinten0508** [stashapp/stash#2779]
**Is your feature request related to a problem? Please describe.**
Running Stash on my one and only desktop presents a problem: whenever preview generations are running, the CPU gets pinned at 100%. This makes the computer practically unusable, with constant system-wide stutters and slowdowns.

**Describe the solution you'd like**
In order to fix this it'd be a good idea to limit the amount of CPU threads/cores Stash can use at once for either specific tasks or all tasks. This way one could let Stash do its thing while not hindering the rest of the system.

**Describe alternatives you've considered**
- Windows presents the option to set process priority inside of Task Manager. I have tried using this but since new ffmpeg instances/threads are created constantly this would require the user to change process priorities for every single instance. Even if this was not the case, the user would have to re-do this after each system restart (or Stash restart for that matter).
- Leaving the hard work to dedicated GPUs may help CPU utilization but this moves the issue to the GPU. If the user wants to use the GPU while Stash it at work, we end up with the same problem again.

**Comment by scruffynerf** [comment]
already exists: see Settings / System / Parallel Scan/Generation
Set it to 1 or 2

**Comment by Quinten0508** [comment]
Whoops, missed that completely. I swear I looked through all of the settings a million times before posting... 
Will close the issue, sorry for wasting your time!
