### ISSUE TITLE
[Feature] Enhance the Duplicate Detection and Management

### ISSUE THREAD

**Issue by thedesi1** [stashapp/stash#2782]
Problem Statement:
Stash does a great job at managing duplicates using the PHASH, however PHASH does not work with many scenes that are released by different studios with added splash or intro. Stash also rejects the scenes that have exact OHASH, which is great but it wont let you find them unless you are looking in the logs. 

Solution I like to be implemented:
Setting -> Tools -> Scene Duplicate Checker - Should have following options
- Find duplicates by PHASH (already in place)
- Find duplicates by OHASH (even if its not imported, ability to see and delete without using other tools)
- Find duplicates by Stash_ID
- Find duplicates by File Names (similar to exact, high, medium maybe?)
- Find duplicates by TPDB_ID (this maybe deferred before 3rd party is implemented in stash/stash-box)

The last few options will also help identify incorrectly tagged releases. 

Alternative solutions to consider:
Write or enhance an existing Script or Plugin to achieve the same. 

Additional context:
Some of the discussions can be referred in the discord channel [here](https://discord.com/channels/559159668438728723/559399634318131210/995712431957475431)

**Comment by WithoutPants** [comment]
$50 bounty added (ref: 558137).

**Comment by thedesi1** [comment]
canceling after discussion with WithoutPants
