### ISSUE TITLE
[RFC] How run stash-macos-intel in Mac?

### ISSUE THREAD

**Issue by yiyishifei** [stashapp/stash#2785]
See title

**Comment by ALonelyJuicebox** [comment]
This isn't an RFC nor is it a feature request-- you'd be better served asking this question on either discord or on GitHub Discussions.

Running stash on macOS is straightforward.

Download the executable, navigate to the installation directory in Terminal (ex. `cd ~/Downloads` )
Then run the following command to allow the app to be run as an application `chmod +x ./stash-macos-intel`
Then you can double click on the executable in Finder to start it, or you can run the command `./stash-macos-intel`
Once it's up and running, navigate to localhost:9999 in a browser to use Stash.

**Comment by yiyishifei** [comment]
> This isn't an RFC nor is it a feature request-- you'd be better served asking this question on either discord or on GitHub Discussions.
> 
> Running stash on macOS is straightforward.
> 
> Download the executable, navigate to the installation directory in Terminal (ex. `cd ~/Downloads` ) Then run the following command to allow the app to be run as an application `chmod +x ./stash-macos-intel` Then you can double click on the executable in Finder to start it, or you can run the command `./stash-macos-intel` Once it's up and running, navigate to localhost:9999 in a browser to use Stash.

Thanks!
