### ISSUE TITLE
[Bug Report] Autoplay isn't preventing when selecting queue item

### ISSUE THREAD

**Issue by YurikaL** [stashapp/stash#2788]
**Describe the bug**
In Scene view, autoplay is performed when an item is manually selecting from queue, even if all related settings is disabled. There is always `autoplay=true` option in the URL after selecting a new scene.

**To Reproduce**
1. Go to Scenes
2. Set any filter that returns more than one scene
3. Open any scene
4. Click on Queue tab and select another scene
5. See autoplay even if related settings is disables

**Expected behavior**
Autoplay is prevented if related settings is disabled

**Screenshots**
<details><summary>Disabled autoplay settings.</summary>

![Scene player settings](https://user-images.githubusercontent.com/43180936/182030552-0bbc74f9-dda2-4535-8003-8ad3dc493285.png)

</details>

**Stash Version: (from Settings -> About):** v0.16.1

**Desktop (please complete the following information):**
 - OS: GNU/Linux
 - Browser: Firefox
 - Version: 94.0.2

**Additional context**
There is another issue about autoplay which is claimed as resolved: #1667
But it doesn't seem to cover manual scene selecting...

**Comment by WithoutPants** [comment]
I misread the original description in #1667 and didn't apply it to the queue.
