### ISSUE TITLE
[Feature] Add ability to regenerate thumbnails (or other generated files) for a specific video

### ISSUE THREAD

**Issue by victorhooi** [stashapp/stash#279]
**Is your feature request related to a problem? Please describe.**

Sometimes, the thumbnails for a video might be corrupted (e.g. video was being downloaded or transferred at the time).

**Describe the solution you'd like**

It would be useful to be able to re-generate the thumbnails (and other generated content) for a selected video on demand.

Possibly via a right-click menu, or maybe a button when you open the video.

**Describe alternatives you've considered**

I believe the current workaround is to lookup each video, find it's checksum, then find all matching checksums and other associated generated assets based on that checksum, then delete it, and re-run the "Generate" action again.

**Additional context**

**Comment by Leopere** [comment]
Please use the issue templates it helps us keep organized.

**Comment by victorhooi** [comment]
Aha - I just took out the headings from the template - but added them back in, and the current suggested workaround (still not sure how this works for clips).

**Comment by bnkai** [comment]
related to #376

**Comment by WithoutPants** [comment]
TODO: add operations for regenerating sprites, previews, markers and transcodes.
