### ISSUE TITLE
[Bug Report] Unexpected Order When Sorting by Scene Number

### ISSUE THREAD

**Issue by AdultSun** [stashapp/stash#2798]
**Describe the bug**
I'll attach multiple Movies to the same scene sometimes, but it causes problems with the default "Movie Scene Number" sorting within the Movie's page. Specifically, when I use different scene numbers for the different movies attached to a particular scene, it's unclear to me which of the two numbers it picks when sorting by "Movie Scene Number". I suspect it's preferring whichever movie was created first, giving it a lower internal ID in Stash.

For example, I made three movies: `Movie #1`, `Movie #2`, and simply `Movie`. The first two represent DVD releases, but those scenes are part of a longer storyline that includes scenes only released digitally. So, I made a third named `Movie` that includes all of the relevant scenes (including any that aren't on a DVD) and numbered them accordingly. Now, the pages for `Movie #1` and `Movie #2` show everything in order. But if I go to `Movie`, it's preferring the wrong scene numbers and everything's mixed up. It's showing me `Movie #1 - Scene 1`, `Movie #2 - Scene 1`, `Movie #1 - Scene 2`, `Movie #2 - Scene 2`, etc. Because I made `Movie` last, it has the highest internal ID number in Stash. I believe that's why it's ignored when determining the sort order.

**To Reproduce**
1. Create at least 2 movies.
2. Attach at least 2 scenes to both movies, but reverse the scene order.
3. Check how the scenes are sorted on each movie's page, I expect both will use the first movie's scene numbers.

**Expected behavior**
I'd want Stash to be able to tell that if I'm within Movie X's page, that I want it to sort by the scene numbers for Movie X instead of any other movies attached to the scene. If I want to sort by Movie Y's numbers instead, then I would be on Movie Y's page.

**Stash Version: v0.16.1-1-gcba0fddf**

**Comment by demitrix** [comment]
I've noticed this behavior as well.

**Comment by Lamda604** [comment]
ditto...would like to see this fixed too. thanks!
