### ISSUE TITLE
Possible to assign a Performer to a folder?

### ISSUE THREAD

**Issue by flowrex** [stashapp/stash#2799]
I was wondering whether it's possible to assign a Performer to a folder?

In my environment I have each performer setup on my drives in their own individual folders.

It would be really great if you could link a performer with a folder and view all their videos.

Is this possible or is it possibly coming as a new feature in the future?

**Comment by HereIam80** [comment]
Since there is no folder structure/view in stash you can't assign something to a specific folder.

However you can filter all your scenes by folder and select the result and assign tags, performers and studios to those scenes.

**Comment by maxmelano** [comment]
you can add performer and use AutoTag feature.

**Comment by WithoutPants** [comment]
As mentioned above there are ways of assigning performers to scenes in specific folders. The Auto Tag feature can be used to assign performers where the path includes the performer's name. There are no plans to assign performers to folders.
