### ISSUE TITLE
[Feature] Option to enable scanning of zero-length files

### ISSUE THREAD

**Issue by LamaGroseille** [stashapp/stash#2807]
**Is your feature request related to a problem? Please describe.**
There are scenes that I want to keep track of having had on my computer/having seen, but don't want to keep the whole video file. The way I do it now is creating a .txt file named after the video file, and then delete the video. However, Stash will skip those files when scanning the library.  

**Describe the solution you'd like**
A solution could be to add a toggle "Skip zero-length files" in the Scan task, defaulted to on. 

**Describe alternatives you've considered**
The alternative would probably be to keep the file on my hard drive.

**Comment by scruffynerf** [comment]
I believe the file refactor will allow things like this.  Right now, it wouldn't be.  Wait till the refactor goes live, and discuss more then.

**Comment by 7dJx1qP** [comment]
A hacky workaround is to enter some text in the text file. For the file to scan without errors, it needs to be above a certain size and it needs to be a multiple of 8. I've found that a file around 512B in size works. You can just enter 512 characters to get the required size. Each file will need to be different or it will be considered a dupe and won't get scanned in, but changing the first or last characters is enough. This process might be too annoying to do by hand, but it could be an idea for a script or plugin to generate such dummy files.

**Comment by LamaGroseille** [comment]
@7dJx1qP good to know, I might be able to write a small script to fill the txt files randomly until the refactor goes live. Thanks

**Comment by WithoutPants** [comment]
With the files refactor change separating the scene object from the file object, it will be possible in future to implement a way to add scenes _without_ files. I won't be adding functionality like this for what is a very niche use case.
