### ISSUE TITLE
[Bug Report] Auto-tagging does not run due to malformed JSON

### ISSUE THREAD

**Issue by tritnaha** [stashapp/stash#281]
**Describe the bug**
The latest build (e58088b) does not let me run the auto-tagging feature, logging only displays
`2019-12-20 09:43:57 Error    json: error calling MarshalJSON for type json.RawMessage: invalid character 'N' looking for beginning of value`

**To Reproduce**

- Go to tasks
- Select all checkboxes (Peformers/studios/tags)
- Press "Auto Tag"

**Expected behavior**
Auto-tagging to run and parse info from files.

**Desktop (please complete the following information):**
 - Tested OS: Ubuntu 19.10
 - Browsers: Via Windows 10
Google Chrome Version 78.0.3904.108 (64-bit)
Microsoft Edge 44.18362.449.0
Firefox Nightly 73.0a1 (2019-12-19)

**Comment by WithoutPants** [comment]
Can you verify that the request from the browser returns successfully? You should be able to see the graphql request in the Chrome development console Network tab.

Can you verify that you have Performers, Studios and/or tags for the Auto-tagger to run with?

Have you tried running the auto-tagger from a specific Performer/Studio/Tag? There is a button on the applicable details pages for each.

I have not yet been able to reproduce this, and inspection of the code hasn't uncovered where that particular log entry is from.

**Comment by thundergreen** [comment]
I have also this issue not being able to add Actors. This is in my logs when drying to create an Actor:

```2020-01-26 16:37:11 Error    runtime error: invalid memory address or nil pointer dereference
```

Also I get Network error by trying to add an actor by scrape

![image](https://user-images.githubusercontent.com/13320319/73137639-a2283600-405a-11ea-95f6-204f0c9dc979.png)


Do i have to add something special to configuration to get this run?

**Comment by bnkai** [comment]
Are you getting the same  auto-tagging error? If not you should open a new issue.

The error you describe when adding actors is usually when you don't enter the name of the actor. In your screenshot the `Name` part should be edited , you only entered an Alias not a name.

The scrape error means something is wrong with the network , either the scraper site or your own  network. Trying again should fix it.

**Comment by thundergreen** [comment]
I indeed did not fill in the name .now everything is working just fine
thanks ! Maybe error messages could be a bit more user friendly

bnkai <notifications@github.com> schrieb am Mo., 27. Jan. 2020, 10:01:

**Comment by WithoutPants** [comment]
@tritnaha are you still encountering this error?

**Comment by WithoutPants** [comment]
Closing pending new information.
