### ISSUE TITLE
[Bug Report] Generated paths don't get auto created

### ISSUE THREAD

**Issue by bnkai** [stashapp/stash#282]
After installing the generated paths don't get auto created resulting in ffmpeg errors.

- was reported through Discord channel  (for a linux dev build e58088b )
- not easy to reproduce

**Comment by Leopere** [comment]
If there can be an error log added it would be great but if not that's also likely fine we should be creating the directories regardless in my opinion.

**Comment by bnkai** [comment]
@Leopere the problem is that the specific directories get created fine for me and so i can't reproduce this , i just added it here though because once in a while someone says they have the same problem. 
AFAIK the only directories not auto created are the ones at the setup , where an error message is thrown.

**Comment by bnkai** [comment]
might be related to #335 , at least for the docker part.

**Comment by Leopere** [comment]
Closed by #335
