### ISSUE TITLE
[Bug Report] Error initializing configuration: missing settings: generated

### ISSUE THREAD

**Issue by JuddB** [stashapp/stash#2842]
**Describe the bug**
When attempting to launch stash-app I receive the prompt "Error:Panic error initializing configuration: missing the following mandatory settings: Generated." 

**To Reproduce**
Stash-win.exe -> Error

**Screenshots**
(https://user-images.githubusercontent.com/111692808/185794592-01d103c4-fd26-4c59-8ae4-5ee4959d3705.jpg)

Stash Version: [v0.16.1]

**Additional context**

In the config file, the generated line is blank between the qoutes.

Config.yml : 

dangerous_allow_public_without_auth: "false"
database: D:\Program Files (x86)\Stash\stash-go.sqlite
generated: ""
host: 0.0.0.0
jwt_secret_key: 5e1bb4d08996b258bdc7260e2cbca6568ca59aba7453812026b2fef37e39a1b7
nobrowser: true
notifications_enabled: true
parallel_tasks: 1
plugins_path: D:\Program Files (x86)\Stash\plugins
port: 9999
preview_audio: true
preview_exclude_end: "0"
preview_exclude_start: "0"
preview_segment_duration: 0.75
preview_segments: 12
scrapers_path: D:\Program Files (x86)\Stash\scrapers
security_tripwire_accessed_from_public_internet: ""
session_store_key: b01cd6ae83882229ac9813f16ed1a8a141e32ac8b0454130988808c6b7a777a7
show_one_time_moved_notification: true
sound_on_preview: false
theme_color: '#202b33'
write_image_thumbnails: true

**Comment by killarny** [comment]
What was the fix for this? I have the same problem after upgrading stash recently..

**Comment by JuddB** [comment]
> What was the fix for this? I have the same problem after upgrading stash recently..

From what I remember was that you just need to place the path of your "CONTENT" folder - the folder that contains your markers, thumbnails, and etc. For me it was, generated: "D:\Program Files (x86)\Stash\CONTENT". Hopefully this helps.
