### ISSUE TITLE
[Bug Report] Generate fails when Stash is installed in a folder containing spaces

### ISSUE THREAD

**Issue by JackDawson94** [stashapp/stash#2847]
**Describe the bug**
Generate fails when Stash is installed in a folder which contains spaces
Error is "cannot find folder [...]/generated/..."
Works normally if stash is in a folder without spaces in the name

**To Reproduce**
1. Install Stash (on windows) in a folder named "Test Folder"
2. Generate sprites, or video preview (anything that writes to the "generated" folder
3. See error in logs

**Expected behavior**
Files should be generated

**Screenshots**
If applicable, add screenshots to help explain your problem please ensure that your screenshots are SFW or at least appropriately censored.

**Stash Version: (from Settings -> About):**
v0.16.1-2-g10bc2c66

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by scruffynerf** [comment]
I don't believe Stash creates the folder.  You have to create it

**Comment by WithoutPants** [comment]
I'm unable to reproduce this. I created a stash folder `D:\dev\stash_data\with spaces` and created the `generated` folder under this. I also tried creating a `gen er ated` folder under it and set the generated path accordingly.

Can you please provide the value of the `generated` key in your `config.yml` file?

**Comment by WithoutPants** [comment]
Closing as not reproducible/inactive.
