### ISSUE TITLE
[Feature] Making stash "offline"

### ISSUE THREAD

**Issue by watermelonpinecone** [stashapp/stash#2848]
**Is your feature request related to a problem? Please describe.**
I don't like the idea of web services being scraped for NSFW information, nor receiving any specifics about what's stored in my library.

**Describe the solution you'd like**
I would like to be able to run stash an "offline" mode of sorts, where no scraping nor querying takes place.

**Describe alternatives you've considered**
I've gone through the code, issues, and PRs and not found any such functionality or similar request.

**Additional context**
I would add an additional config option for this.
I can see I would want to disable scrapers, probably by returning prematurely [here](https://github.com/stashapp/stash/blob/develop/pkg/scraper/cache.go#L101) with an empty `scrapers`.
Stashbox doesn't appear to operate until/unless config is supplied by the user.
Are there any other sources of external requests I should be looking into please?

Thank you!

**Comment by ALonelyJuicebox** [comment]
Simply do not add any scrapers to accomplish this goal. Stash has no native built in scrapers. Further, you have full ability to dictate how much access any application has to the internet using your OS's built in firewall. 

Windows for example
https://www.howtogeek.com/227093/how-to-block-an-application-from-accessing-the-internet-with-windows-firewall/

**Comment by 7dJx1qP** [comment]
> Thanks @ALonelyJuicebox. Would [freeones](https://github.com/stashapp/stash/blob/develop/pkg/scraper/freeones.go) not count as a built-in scraper? It appears to be unconditionally initialized [here](https://github.com/stashapp/stash/blob/develop/pkg/scraper/cache.go#L106).

The initialization is just loading a built in [freeones scraper config file](https://github.com/stashapp/stash/blob/c1f89611e2f2690265162b0e81c1594588f55494/pkg/scraper/freeones.go). AFAIK, no querying or scraping takes place. The config just specifies how a scrape/query would be parsed.

**Comment by cjemorton** [comment]
You could run it inside of a jail or a VM and then filter and use a firewall to block all traffic except to the machine your using to view it on.

**Comment by WithoutPants** [comment]
As mentioned above, the freeones scraper is only used if you explicitly scrape performers with it. I don't really see the value in disabling it. Closing as invalid - feel free to comment if I've missed something.
