### ISSUE TITLE
[Feature] A way to personalize stash's sorting

### ISSUE THREAD

**Issue by Vislow1337** [stashapp/stash#2859]
**Is your feature request related to a problem? Please describe.**
Stash has a lot of different ways to sort, but it seems to lack a way to save the sorting. What I'm talking about is when I go to Scenes for example the default sorting is "Date", which can be changed into different ways of sorting such as "Duration", "O-Counter", "Title", etc... which is nice, but upon switching to something else such as Images or Performers and then switching back to Scenes, Scenes itself will switch back to it's default "Date" instead of having saved what you switched the sorting to

**Describe the solution you'd like**
I have 2 different solutions, Solution 1: make Stash remember what you used to sort by instead of using default for Scenes, Performers, Images, etc..., or Solution 2: Have a setting to change the default sorting for Scenes, Performers, Images, etc...

**Comment by Wasylq** [comment]
Like the "Set as default" here?
![obraz](https://user-images.githubusercontent.com/105118424/187087418-fd83c987-e0a8-43fb-92b0-c383649e6975.png)

**Comment by Vislow1337** [comment]
so it does exist after all, just not where I expected it to, then the problem is already solved, thanks for the help
