### ISSUE TITLE
[Bug Report] Scene Tagger scrape returns deleted stashbox scenes

### ISSUE THREAD

**Issue by 7dJx1qP** [stashapp/stash#2867]
**Describe the bug**
Deleted stashbox scenes appear in the scrape match results when using the scene tagger to scrape a stashbox source with Scrape all or Scrape by fragment

**To Reproduce**
1. Go to Scene Tagger
2. Click on "Scrape by fragment" for a scene that has duplicate stashbox entries, one of which is deleted
3. See duplicate entries in match results, including deleted one.

**Expected behavior**
Only stashbox scenes that aren't deleted should be returned

**Stash Version: (from Settings -> About):**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version v0.16.1

**Additional context**
Deleted scenes are only returned when scraping. Using "Search" instead of scrape returns only the non-deleted scenes as expected

Here's a pair of stashdb scenes, one of which is deleted, that can be used as a test case:
https://stashdb.org/scenes/6df5a699-a4c3-476b-81d8-70477ad1ba17
https://stashdb.org/scenes/6b4cd19d-d52a-4a30-a2f5-949793db6e49
Another pair:
https://stashdb.org/scenes/497c8cb4-655b-47ad-af99-8da2266e4d36
https://stashdb.org/scenes/2b3fa512-5f3f-453f-bf58-7abcd5969b7c

**Comment by peolic** [comment]
This has been mentioned before, but I guess it was never reported on GH.
The underlying reason is users can submit fingerprints to deleted scenes, then they get matched and show up in the results.

**Comment by peolic** [comment]
Should be fixed now. ([stash-box v0.3.0](https://github.com/stashapp/stash-box/releases/tag/v0.3.0))

**Comment by Maista6969** [comment]
Can be closed
