### ISSUE TITLE
[RFC] Adhere to XDG_CONFIG_HOME specs

### ISSUE THREAD

**Issue by ueaslsef** [stashapp/stash#287]
# Adhere to XDG_CONFIG_HOME specs

*### Scope*

The [XDG Base Directory Spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html) wants special directories used for config, database, cache, etc. Do we want to respect this (at least on unix systems?)

> The XDG Base Directory Specification is based on the following concepts:
> 
> - There is a single base directory relative to which user-specific data files should be written. This directory is defined by the environment variable $XDG_DATA_HOME.
> - There is a single base directory relative to which user-specific configuration files should be written. This directory is defined by the environment variable $XDG_CONFIG_HOME.
> - There is a set of preference ordered base directories relative to which data files should be searched. This set of directories is defined by the environment variable $XDG_DATA_DIRS.
> - There is a set of preference ordered base directories relative to which configuration files should be searched. This set of directories is defined by the environment variable $XDG_CONFIG_DIRS.
> - There is a single base directory relative to which user-specific non-essential (cached) data should be written. This directory is defined by the environment variable $XDG_CACHE_HOME. 

I personally don't like my home director cluttered and following well established standards is something I like to persue. What are your thoughts on that?

## Reference Reading

(https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html

**Comment by Leopere** [comment]
Just hitting the summary it makes sense to me.

**Comment by bnkai** [comment]
The only difference would be to change the default  `~/.stash` fallback to `~/.config/stash`?
For now the first directory checked is the cwd and then the `$HOME/.stash` , so that multiple stash instances can run from a single user.If you wanted for example you wouldn't even need to have the `~/.stash` folder 
All the other directories are configured during the setup anyway so the user decides what he wants.

**Comment by ueaslsef** [comment]
Ok, let's bring the number of open issues down and close this.
