### ISSUE TITLE
"Add logical Criteria to tags" | "Add logical searchs"

### ISSUE THREAD

**Issue by caustico** [stashapp/stash#29]
When you use in Makers  "Add Criteria" and select Tags you can add several tags but not exists logical criteria:
It would be interesting "Add Logical Criteria".Example:
Show scene with "tag A" and " tag B"
Show scene with "tag A" or "tag B"
The same functionality for search it would be interesting too.

**Comment by StashAppDev** [comment]
This is something I'm working to add.  Once I finish the UI rewrite I can add support for this on the server side.
