### ISSUE TITLE
[Feature] Splooge button

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#291]
Provide a splooge button ala Pornganizer for scenes as an additional way to rate scenes, and let the end-user filter scenes based on splooge count eg. `splooge < 1` will ideally provide fresh scenes

**Describe the solution you'd like**
Each scene would have a splooge counter. When the scene's splooge button is pressed the counter will increment by 1.

**Additional context**
The basic UI of the splooge button can be `{splooge icon button} {visual counter} {bp3-icon-caret-down button}` in a `ButtonGroup`  where,

- **{splooge icon button}** is a splooge icon and button. The `tint` icon from [Blueprint](https://blueprintjs.com/docs/#icons) is the only suitable icon they have imo. Pressing the button increments the counter by 1.
- **{visual counter}** displays the number of splooges to the right of the `tint` icon on the splooge button.
- **{bp3-icon-caret-down button}** indicates a small dropdown menu (I think Blueprint calls this a popover wrapper?) that would let the user:
 -- `Decrement` the splooge counter by one for any accidental button presses
 -- `Reset` the splooge counter to 0

**Mockup concepts**

Scene cards

![Annotation 2019-12-25 205057](https://user-images.githubusercontent.com/37937507/71453267-5d0d9d00-2758-11ea-8c95-518a4ad1dec1.png)

**Comment by Leopere** [comment]
I get a laugh out of the concept, but I'd imagine just a heart or a star would suffice and be a bit more professional.  I'm indifferent if people follow my lead for "professionalism" here but just wanted to pitch my thoughts.

**Comment by WithoutPants** [comment]
I'd prefer not to call it "splooge" as well, not just for aesthetics, but also because it makes it a carbon copy of the feature in PGV. I agree with a heart or star. As a text/db field, times hearted might be sufficient.

**Comment by dotbanana** [comment]
I like the idea very much and i personally see no reason to not use "Splooge" or some other 'ordinary expression', because it exactly describes what this feature is for. A star or a heart are used in contemporary social media semiotics for other purposes -> For favorites and for likes.
And imo there is no need to be sensitive about the wording - this script is in the end for porn-organization and not for winning some coding contest or using it for the purpose of getting a job (or so do i assume/hope ^^).

**Comment by Leopere** [comment]
Sure, and you have a perspective on the matter, but I would return with something along the lines of just that, not everyone splooges per-say, and some may prefer something a bit more generic.

**Comment by echo6ix** [comment]
Everyone makes good points. How about calling it a **user-configurable custom counter**?

- Within `settings` let the user:
  - enable or disable the counter/button
  - define parameters of the counter/button, which would be:
    - the `name` of the counter/button
    - the `icon` from a filtered drop-down list of Blueprint's icons

**Comment by synack12** [comment]
Yep, I like this feature as well. Do not really care about what its called, splooge, heart or thumbs up.  If you can filter / sort on it that would be great.  I use it as a way to filter out content that I, um, have "used" and as a way to find scenes that are highly rated that I may have not watched (used).  ;)

**Comment by Leopere** [comment]
If we can do it without adding absurd quantities of technical debt, I would like @echo6ix 's permutation of this idea.

**Comment by Leopere** [comment]
It also would help if we had some kind of datavis panel in the admin side of the App.
