### ISSUE TITLE
[Bug Report] Error logged with latest develop release on scanning images

### ISSUE THREAD

**Issue by PsychoSid** [stashapp/stash#2912]
**Describe the bug**
Error logged with latest develop release on scanning images. Not sure if this is causing an issue or just "noise"

**To Reproduce**
Run "Scan"

**Expected behavior**
Scan reports no errors

**Error**
```
INFO[2022-09-15 07:40:37] /Users/Misc/Pics/OnlyFans/Scarlett Jones/20220914-How_are_you_today-2316x3088_a0080f04de31176a941ac328bc85c5cb.jpg doesn't exist. Creating new image...
ERRO[2022-09-15 07:40:37] Image.Create.Post [Default Data For Path]: returned error: TypeError: Cannot access member 'toLowerCase' of null
```

**Stash Version: (from Settings -> About):**
v0.16.1-47-g781a767f

**Comment by WithoutPants** [comment]
This is an error message from one of your plugins.
