### ISSUE TITLE
[Bug Report] Keyword Filtering Bug - Or And Comma

### ISSUE THREAD

**Issue by A-Random-Mf** [stashapp/stash#2916]
**Describe the bug**
 Keyword/modifierfiltering doesnt work properly in the latest dev build.
Ex) Path excludes: Various Files, kemono-dl
It used to exclude those directories from the search now it doesn’t. Path excludes: Various Files works and Path excludes: kemono-dl works but they don’t work together. OR AND both make no difference

**To Reproduce**
Try doing a multi keyword non regex search/filter
Nothing will show

**Expected behavior**
Properly filtered results returned

**Stash Version: (from Settings -> About):
v0.16.1-47-g781a767f

**Comment by A-Random-Mf** [comment]
The bug seems to be partially fixed. Multi word filters now return results but not the correct ones. Scenes that should be excluded by the filter are not. Regex filtering is also broken now

**Comment by WithoutPants** [comment]
Can you please give an example of filters and results (expected and actual) of what isn't working? I'm not able to reproduce.

**Comment by A-Random-Mf** [comment]
Forgive me. I was typing the regex wrong and regular exclude filter fixed itself after several restarts. Thanks. Everything seems to be fine

**Comment by A-Random-Mf** [comment]
> Can you please give an example of filters and results (expected and actual) of what isn't working? I'm not able to reproduce.

Sorry @WithoutPants this bug seems to be inconsistent in occurrence. ![](https://cdn.discordapp.com/attachments/559159910550732809/1021821181634031706/unknown.png)
![](https://cdn.discordapp.com/attachments/559159910550732809/1021821182015709294/unknown.png)
Nothing in that screenshot is supposed to show
http://the-url/scenes?c=(%22type%22:%22organized%22,%22value%22:%22false%22,%22modifier%22:%22EQUALS%22)&c=(%22type%22:%22path%22,%22value%22:%22Various%20Files,%20kemono-dl%22,%22modifier%22:%22EXCLUDES%22)&perPage=1000&sortby=created_at&sortdir=desc
Same with regex
![](https://cdn.discordapp.com/attachments/559159910550732809/1021822135292932106/unknown.png)
![](https://cdn.discordapp.com/attachments/559159910550732809/1021822135699783720/unknown.png)
http://the-url/scenes?c=(%22type%22:%22organized%22,%22value%22:%22false%22,%22modifier%22:%22EQUALS%22)&c=(%22type%22:%22path%22,%22value%22:%22%28Various%20Files%29%7C%28kemono-dl%29%22,%22modifier%22:%22NOT_MATCHES_REGEX%22)&perPage=1000&sortby=created_at&sortdir=desc

Ive tried
Various Files|kemono-dl
Various Files | kemono-dl
kemono-dl
-"kemono-dl" in the search bar also isnt working

**Comment by WithoutPants** [comment]
The delimiter used in `include` and `exclude` (both in the development version and in the last stable release) is whitespace. This means that when you use use a `Path excludes` value of `Various Files, kemono-dl`, it _should_ exclude paths containing: `Various`, `Files,` (note the comma), and `kemono-dl`.

I note that it is not currently possible to handle elements with whitespace in them (eg `Various Files`) when combined with other elements (ie `"Various Files" foobar`). **This can be raised separately**, but is not a regression on existing behaviour. When I tried `"Various Files" kemono-dl`, it didn't exclude the `komono-dl` files.

In my testing, `-kemono-dl` in the search bar excludes files containing that string successfully for me, as did `-"kemono-dl"`.

For me, `path not matches regex` with `(Various Files)|(kemono-dl)` successfully excluded files with `kemono-dl` in the name. I can't determine why we're getting different results.

**Comment by A-Random-Mf** [comment]
Damn. Thanks for the update
