### ISSUE TITLE
[Feature] Add a filter option to show all performers with no photo added

### ISSUE THREAD

**Issue by VonTittyslappen** [stashapp/stash#292]
Apologies if this is already covered under another request, but I think it would be beneficial to have a filter on the performers page to view all performers easily that do not have an image added

Cheers

**Comment by ueaslsef** [comment]
Need to check: Are the fallback images saved as real images into performer data or always freshly used? If they are saved, this would need to be checked.

**Comment by Leopere** [comment]
I think that this could be the beginning of a very useful feature once we start allowing for metadata submission to the StashBox API.  Show listings with missing metadata type {variable} dropdown or button or checkbox, not sure what to suggest here.

**Comment by WithoutPants** [comment]
This would not be easy to do currently, since the placeholder images are saved to the performer entry as normal images.

**Comment by bnkai** [comment]
Maybe instead add an extra reserved tag when the user doesn't supply an image ?

**Comment by Leopere** [comment]
Chalk this up to might not do for version 1 or should we consider doing some variant.

**Comment by WithoutPants** [comment]
Resolved by #722.
