### ISSUE TITLE
[Bug Report] Stash Throws ErrOverriddenConfig When Overriding Non-Overridden Config

### ISSUE THREAD

**Issue by jamey** [stashapp/stash#2924]
When overriding Scrapers path values at /settings?tab=system, editing the value of a path that is not overridden opens a popup "cannot set overridden value: metadata".  I am not editing Metadata, which **is** overridden at the docker layer via a helm chart.

Removing the overrides from the helm chart does not change this behvior; the popup still comes up.

This exception prevents the edit from saving.

**Comment by ripple7511** [comment]
+1, having the same problem

**Comment by WithoutPants** [comment]
I think this is addressed in the blobs pr. I noticed a typo while doing it. Scheduled for 0.19.

**Comment by WithoutPants** [comment]
Scratch that. Will squeeze it into 0.18.
