### ISSUE TITLE
[Bug Report] FFProbe permission denial when scanning

### ISSUE THREAD

**Issue by tech10g** [stashapp/stash#293]
On Mac Catalina running Chrome. My videos are stored on an external drive. Whenever I scan for videos each video produces the same error in logs, whereas I would expect that the videos would be loaded into stash. I have tried on both currently available builds (2019/12/27).
An example error is shown below:

2019-12-27 12:00:50 Error    FFProbe encountered an error with <[path of video]>.
Error JSON:

Error: fork/exec /Users/[user]/.stash/ffprobe: permission denied

**Comment by bnkai** [comment]
Are you sure ffprobe / ffmpeg is executable and has access to the files ?

**Comment by tech10g** [comment]
I'm unsure how to check if they have access to the files but both ffprobe and ffmpeg are executable.

**Comment by bnkai** [comment]
You can try opening a terminal and running the ffprobe  command that was printed in log/console manually,
Is the location ffprobe located correct?   ( ~/.stash/ffprobe )  ? Is stash running as `user` ? Are the file permissions of ffppeg / ffprobe and the media files ok ( a simple `ls -l` from the console is enough to check ) ?

**Comment by tech10g** [comment]
Using `ls -l`all of the files have similar outputs but I don't know what that means. An example is: `-rw-r--r--  1 [user]  staff  64727340 27 Dec 11:47 ffmpeg`.
I am unsure which command I should manually input, I cannot see any command in the log page in settings or in the terminal window.

**Comment by bnkai** [comment]
@tech10g if that is your ffmpeg binary then its not executable. You need to do `chmod +x ffmpeg` or `chmod 755 ffmpeg` and the same for ffprobe.

**Comment by Leopere** [comment]
This issue looks like an invalid bug and can be closed for now; it can be re-opened if it's not the issue.  Technically the conversation could be carried forward in the Discord if it's just a support issue.
