### ISSUE TITLE
[Feature] Differences with StashDB

### ISSUE THREAD

**Issue by SpedNSFW** [stashapp/stash#2930]
After matching your local scene with one on StashDB, there's not much reason to go back to it, but currently, a lot of scenes on StashDB aren't complete. They're missing tags, performers are missing, etc.

What I'd like to see in the future is some way of filtering out scenes with a Stash ID that no longer match StashDB, whether that's because you've made local changes or StashDB was updated, it shouldn't matter. This would then allow us to easily match them again and update our local scenes with updated data.
This should include scenes that have a Stash ID that doesn't match anything on StashDB (likely from a scene merge or removing a duplicate).

I'm thinking this might have to be a task or something that can be run and then the filter would apply to all those that had been checked at the time of this task being run. I'll let the specifics be worked out by whoever decides to implement this.

**Comment by wirbelsaeure** [comment]
https://github.com/stashapp/stash/discussions/2921

**Comment by SpedNSFW** [comment]
> #2921

Must have missed that while searching. Thanks.
