### ISSUE TITLE
[Feature] Custom 1-5 Star Rankings

### ISSUE THREAD

**Issue by sinner1989** [stashapp/stash#2937]
Add support for custom 1-5 star rankings on a performers page.
The text field should be free to be defined by the user, and searchable in the performer page.

In addition, there should be the ability of multiple of these created on each performers page, in addition to the basic "rating" functionality.

I added a bounty of $50 for this feature which can be found here: https://opencollective.com/user-ee3843cb

sinner89 on Discord for contact.

**Comment by WithoutPants** [comment]
Please note that bounties are supposed to be discussed with developers for feasibility _before_ submitting to the OpenCollective, per the Bounty tier description: 
![image](https://user-images.githubusercontent.com/53250216/191387959-91c12228-fd3c-4b5d-bbe1-a842fdaf0df3.png)

This is supposed to head off issues where a feature request is not a good fit, is not reasonable, or is unclear. In this case, I don't know exactly what is meant by your description.

**Comment by sinner1989** [comment]
> Please note that bounties are supposed to be discussed with developers for feasibility _before_ submitting to the OpenCollective, per the Bounty tier description: ![image](https://user-images.githubusercontent.com/53250216/191387959-91c12228-fd3c-4b5d-bbe1-a842fdaf0df3.png)
> 
> This is supposed to head off issues where a feature request is not a good fit, is not reasonable, or is unclear. In this case, I don't know exactly what is meant by your description.

I noticed that after the fact, my bad. If it isn't doable, it isn't doable. Happy to contribute regardless.

To clarify: Create custom 1-5 star ratings on a performers page. I.E. "Looks" and rate it 1-5.

The ability to have multiple ratings ones created with custom names on a profile page, and the ability to filter said custom ratings.

Let me know if this is not clear.

**Comment by sinner1989** [comment]
[https://ibb.co/kyNsp5m](url)

mspaint mockup of what I mean, for visual reference

**Comment by 7dJx1qP** [comment]
There's an existing feature request for custom performer fields: https://github.com/stashapp/stash/issues/885 and it looks like it would just need to have a "rating" data type to satisfy your request

**Comment by Foucoubou** [comment]
Hello,
Maybe little offtopic - but If I remember well, there was also request to make the rating scale configurable.
I was thinking about the solution and here I present my suggestion.

Lets think that the highest granulatity system would be 0-100
Then it would be best to store the data in this granularity in DB
And then just add conversion, which is pretty strightforward
0-5 star -> 0 20 40 60 80 100
0-5 half star -> 0 10 .... 90 100
0-10 star -> 0 10 .... 90 100
0-10 half-star -> 0 5 10 15 .... 100
0-100 - db data

Since the data are stored in the 0-100 if any user changes from one system to another - it is just a visualisation.

**Comment by MrX292** [comment]
> Hello, Maybe little offtopic - but If I remember well, there was also request to make the rating scale configurable. I was thinking about the solution and here I present my suggestion.
> 
> Lets think that the highest granulatity system would be 0-100 Then it would be best to store the data in this granularity in DB And then just add conversion, which is pretty strightforward 0-5 star -> 0 20 40 60 80 100 0-5 half star -> 0 10 .... 90 100 0-10 star -> 0 10 .... 90 100 0-10 half-star -> 0 5 10 15 .... 100 0-100 - db data
> 
> Since the data are stored in the 0-100 if any user changes from one system to another - it is just a visualisation.

PR #2830 is pretty much that

**Comment by sinner1989** [comment]
> There's an existing feature request for custom performer fields: #885 and it looks like it would just need to have a "rating" data type to satisfy your request

Correct, that sounds exactly like it.

**Comment by skier233** [comment]
> > Hello, Maybe little offtopic - but If I remember well, there was also request to make the rating scale configurable. I was thinking about the solution and here I present my suggestion.
> > Lets think that the highest granulatity system would be 0-100 Then it would be best to store the data in this granularity in DB And then just add conversion, which is pretty strightforward 0-5 star -> 0 20 40 60 80 100 0-5 half star -> 0 10 .... 90 100 0-10 star -> 0 10 .... 90 100 0-10 half-star -> 0 5 10 15 .... 100 0-100 - db data
> > Since the data are stored in the 0-100 if any user changes from one system to another - it is just a visualisation.
> 
> PR #2830 is pretty much that

Yes. My pr should be exactly that. Feel free to look it over or give any comments:
https://github.com/stashapp/stash/pull/2830

**Comment by WithoutPants** [comment]
Closing this as resolved by #2830.

@skier233 please submit an OpenCollective expense or indicate where you would like the funds to be transferred instead (stash project or issue).

**Comment by WithoutPants** [comment]
@skier233 can you also please post the invoice number or to me an Discord to confirm? Thanks
