### ISSUE TITLE
[Bug Report] Migrate page doesn't work with subfolder RP

### ISSUE THREAD

**Issue by rg9400** [stashapp/stash#2964]
**Describe the bug**
When reverse proxying Stash using subfolder (https://domain.com/stash), the migrate page is the only page that doesn't work. I just get a 404 page and have to locally access Stash, migrate the DB, then continue using Stash through reverse proxy. This is the only page that seems to fail in my configuration

**To Reproduce**
1. Set up an NGINX reverse proxy config as below for subfolder access
```nginx
location ^~ /stash {
    auth_request /auth-0;
    include /config/nginx/proxy.conf;
    set $theme_app stash;
    set $upstream_app stash;
    set $upstream_port 9999;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    proxy_set_header X-Forwarded-Prefix /stash;
    include /config/nginx/themes/themepark.conf;
    rewrite ^/stash/(.*)$ /$1 break;
}
```
2. Go to domain.com/stash, verify pages work as expected
3. Go to domain.com/stash/migrate, notice how this results in a 404

**Expected behavior**
Migrate page should load as per every other page through reverse proxy. Seems there is some type of issues with how the URL base is not being set or something (not sure)

**Stash Version: (from Settings -> About):** v0.16.1-74-gb8b62a36

**Comment by TopherIsSwell** [comment]
This also affects the "/setup" path for new installs. I suspect this is configured in `ui/v2.5/src/App.tsx`
![image](https://user-images.githubusercontent.com/22041949/193953578-f363f558-8ef2-404b-ab5b-ce79bdbc1bb1.png)
