### ISSUE TITLE
[Bug Report] DB Migration failed on performer_id

### ISSUE THREAD

**Issue by TorvaldUtne** [stashapp/stash#2967]
**Describe the bug**
Migration from 34 to 35 fails with the following error:

An error occurred migrating the database to the latest schema version. The backup database file was automatically renamed to restore the database.
error performing migration: UNIQUE constraint failed: performer_stash_ids_new.performer_id, performer_stash_ids_new.endpoint in line 0: -- add primary keys to association tables that are missing them
PRAGMA foreign_keys=OFF;

**Screenshots**
![2022-09-30 12_48_29-Stash - Organizr V2 — Mozilla Firefox](https://user-images.githubusercontent.com/78661304/193319298-9cc8c59d-32b9-4e37-b76c-4e41fc8b8504.png)

**Stash Version: (from Settings -> About):**
Can't get to the version page.  This is the docker container running on unraid

**Comment by skier233** [comment]
I am also getting an error going to migration 35 but with a different error:
An error occurred migrating the database to the latest schema version. The backup database file was automatically renamed to restore the database.
error performing migration: error in view scenes_query: no such table: main.performers_scenes in line 0: -- add primary keys to association tables that are missing them
PRAGMA foreign_keys=OFF;

**Comment by velzy00** [comment]
I'm getting a similar error when trying to migrate to 35:

```
An error occurred migrating the database to the latest schema version. The backup database file was automatically renamed to restore the database.
error performing migration: UNIQUE constraint failed: studio_stash_ids_new.studio_id, studio_stash_ids_new.endpoint in line 0: -- add primary keys to association tables that are missing them
PRAGMA foreign_keys=OFF;
```

**Comment by DingDongSoLong4** [comment]
I'm getting the same kind of error - the database is now enforcing that you only have one stash id per performer, studio or scene (for every stash-box endpoint). While ideally you don't want multiple stash ids for one thing, it can be useful if the stash-box has duplicate items which haven't been merged yet.

**Comment by TorvaldUtne** [comment]
Just updated and was able to migrate.  Leaving open for the others with issues.

**Comment by WithoutPants** [comment]
The performer and studio stash ids table migrations have been removed from the 35 schema migration, so this should now be resolved.
