### ISSUE TITLE
[Feature] Delete Individual File(s) Per Scene

### ISSUE THREAD

**Issue by anonuser69** [stashapp/stash#2972]
**Is your feature request related to a problem? Please describe.**
With the introduction of allowing multiple files per scene, scenes may end up with duplicate files.

**Describe the solution you'd like**
Under File Info, a button should be added per file to delete the individual file.

**Describe alternatives you've considered**
Deleting files manually from the server and running Clean Up is fine but an in-app solution would be nice.

**Additional context**
N/A

**Comment by WithoutPants** [comment]
This is included in pended PR #2790.
