### ISSUE TITLE
[Feature] If undefined, set Marker Title to be the same name as the Primary Tag

### ISSUE THREAD

**Issue by ALonelyJuicebox** [stashapp/stash#2986]
**Current State**
If a Marker is created without a title, the UI simply does not display anything above the timestamp, preventing the user from clicking on anything in order to navigate to the timestamp 
![yikes](https://user-images.githubusercontent.com/76471868/194690016-e14d6100-e113-4ac2-8771-f5ac0ba32a0d.JPG)

Conversely, this is how this Marker looks when a Marker Title _is_ defined
![yay](https://user-images.githubusercontent.com/76471868/194690135-9821ed25-27f6-4700-9714-bed20e9215b2.JPG)

**Desired State**
To solve this, I propose that in the event that a Marker does not receive a custom title from the user, just auto-define the title to be the same name as the Primary Tag. 

Thanks!

**Comment by kenetik** [comment]
Agreed this is a good FR that would be beneficial. 👍
