### ISSUE TITLE
Random Videos in the start page

### ISSUE THREAD

**Issue by orion164** [stashapp/stash#2991]
I noticed that when you log into Stash, you can customize what you can see at the beginning. However these filters always show the same results if you don't add content for a long time.

In addition to these filters, it would be nice to be able to view random contents of the chosen tag / studio / actor at each access

There is a very nice and similar feature in the scene display: It is possible to start random scenes and follow the queue. But that's not exactly the same.

Thanks for all your hard work, this application amazing!

**Comment by WeedLordVegeta420** [comment]
For the home landing page, this is already possible. 

Go to Scenes/Performers, create and save a custom filter ordered by Random. Then go to the home page, click the Customize button in the lower right-hand corner, and add your filter.

**Comment by orion164** [comment]
Hello @WeedLordVegeta420 and thanks for the reply.

I don't understand if it's a problem with my language. My version is 0.16.1.

When I try to create the filter selecting "Orderer" I can only put True and False. With False nothing changes, with True I don't see any results.

**Comment by WeedLordVegeta420** [comment]
I'm referring to the order by dropdown. Select Random and then save the filter.
![image](https://user-images.githubusercontent.com/81525421/194855375-f06feb9f-6773-46b5-be19-b47bd6dde35e.png)

![image](https://user-images.githubusercontent.com/81525421/194855666-6339dfda-1102-4dcd-b07b-489ac078435f.png)

After you do this, then you can go back to the home page, click Customize, and select that random filter as one of the filters being displayed.

**Comment by orion164** [comment]
Ohhhhh thanks. I didn't see that!

Sorry for the waste of time! Have fun :)
