### ISSUE TITLE
[Feature] Expand StashID filter to filter by endpoint

### ISSUE THREAD

**Issue by stg-annon** [stashapp/stash#2999]
**Is your feature request related to a problem? Please describe.**
With more endpoints becoming available users will likely want to filter items with StashIDs from a specific endpoint, currently this cannot be done.

**Describe the solution you'd like**
Add the ability to filter by stashbox endpoint for items with StashIDs

**Describe alternatives you've considered**
manually tagging items that have StashIDs from a given endpoint, this would not be ideal going forward

**Comment by Ch00nassid** [comment]
https://discord.com/channels/559159668438728723/559159931505213440/1029526174914842706
