### ISSUE TITLE
[Feature] Add SFW toggle

### ISSUE THREAD

**Issue by Kaelfurian** [stashapp/stash#3008]
It would be nice to have a SFW toggle similar to how TPDB implements it. 

You press the toggle and all images (video thumbnails, gallery images, performer images, etc.) become heavily blurred/censored.

This could be implemented as a CSS stylesheet toggle between two stylesheets (one SFW and one NSFW). (although perhaps something dynamic would be better)

**Comment by HijackHornet** [comment]
You can make a css snipset either as Custom CSS, or in a stylesheet in [Stylus](https://github.com/openstyles/stylus). The later allow you to toggle on and of in a single click

**Comment by Kaelfurian** [comment]
I currently do just that (albiet without using a web browser extension given the inherent security risk of attaching third-party extension to a private browsing experience - although Stylus looks currently safe but that can always change).

Would be nice to have it built into the web interface however without the need of third-party extensions, which is why I mooted the suggestion, it would be better to have it natively supported. Also could help pave the way for something like a light/dark mode too if that was ever desired (support for multiple stylesheets)

**Comment by Kaelfurian** [comment]
Also there are things like autoplay previews which you don't happening on a SFW mode - and I've not quite figured out how to stop that happening with just the CSS.

**Comment by HijackHornet** [comment]
https://github.com/stashapp/stash/wiki/Custom-CSS-snippets#blur-nsfw-images

**Comment by Stashing-fr** [comment]
I wanted to propose a solution with @import, but I am unable to make it work.

@import url('https://raw.githubusercontent.com/Stashing-fr/Stash-css-custom/main/Blur.css');

It might be handy to put multiple @import and comment out the @import to enable/disable.
Does anyone know how to fix this or explain why it doesn't work ?

**Comment by Kaelfurian** [comment]
A stash plugin with a button toggle (which is perfect. good to be able to toggle on/off as desired) has been released here: https://github.com/Belleyy/CommunityScripts/tree/pluginUI_SFWSwitch/plugins/SFW%20Switch which addresses this issue right now. Still would be nice to have something native but this does the trick.

**Comment by feederbox826** [comment]
Duplicate of #2022
