### ISSUE TITLE
[Feature] Add "Tag Description" to the "Is Missing" filter on the Tag Page

### ISSUE THREAD

**Issue by ALonelyJuicebox** [stashapp/stash#3010]
_Running Dev Build (v0.16.1-112-gbd44571a_

**Challenge**
Users now have the ability to define descriptions for their tags (🥳), however they aren't currently able to filter the Tag page by the tags that are missing descriptions. As folks start working through their tags and adding descriptions, it will be beneficial to be able to narrow down which tags have yet to be given a description.

**Proposed Solution:**
Add a "Tag Description" option to the "Is Missing" filter on the Tag page.
There's an existing filter for Tag Image, this feature would maintain existing parity.

**Example UX:**
![tagdesc](https://user-images.githubusercontent.com/76471868/196146012-79278063-7da1-4143-b660-f972b981e804.png)

Thanks! 🙏🏾

**Comment by stg-annon** [comment]
would #3011 resolve this? the is_null functionality would be equivalent to this.

**Comment by ALonelyJuicebox** [comment]
I want to say yes but...since there's already an "Is Missing" field and Tag Image is a part of it, I would thing a "is null" would be more confusing. I'm down with either implementation, I just think we need to be consistent with both. What do you think?

**Comment by stg-annon** [comment]
I believe there was mention at one point to replace the is missing filters with individual filters for those attributes not sure if that's still a thing, that PR is meant to add the same functionality that is available for scene details but as a byproduct does the same thing that "is missing" would do if you use it in a specific way

**Comment by WithoutPants** [comment]
The "Is Missing" criterion should be reserved for fields that do not have their own criterion (ie tag image). I think #3011 is sufficient for this.
