### ISSUE TITLE
[Bug Report] MarkerTagToScene plugin overwrites all Scene Tags

### ISSUE THREAD

**Issue by ALonelyJuicebox** [stashapp/stash#3013]
**General Description**
With the official Marker Tag To Scene plugin installed (https://github.com/stashapp/CommunityScripts/tree/main/plugins/markerTagToScene), if you add some scene tags to a scene, then add a marker tag, the marker tag you just added will remove any and all previously added scene tags for that scene, displacing it with the single marker tag you just added. 

This is a regression from 0.16 stable.

**Reproduction Steps**
1. With the MarkerTagToScene plugin installed, navigate to a Scene
2. Add a few Scene tags to the Scene and click Save.
3. Add a Marker with a Primary Marker tag. 
4. Observe that _both_ of the Scene tags you added earlier have now been overridden by the single Marker tag that the plugin added to the scene 😬

**Expected behavior**
The MarkerTagToScene plugin should take the Primary Marker Tag and **add** to the list of existing Scene Tags, but it should not overwrite or displace any Scene tags already present. 

**Screenshots**

![markerregression](https://user-images.githubusercontent.com/76471868/196292004-a785c1ea-5088-4f19-8b73-030a07b51023.png)

**Stash Version: (from Settings -> About):**
Dev Build v0.16.1-112-gbd44571a

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 104.0.5112.102

**Comment by WithoutPants** [comment]
This was caused by a combination of two bugs. The `gql.Do` function does not throw an error when the graphql query/mutation fails, so the plugin received no existing tags, so it does not include the existing tags in the scene update call. The graphql query was failing in this case because of the dataloader middleware not being loaded.
