### ISSUE TITLE
[Bug Report] 0.17 New translations are missing

### ISSUE THREAD

**Issue by coscosname** [stashapp/stash#3019]
**Describe the bug**
New translations are missing although they are in Weblate. Polish language on the screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/89737988/196704647-7ba3e262-e6c5-491c-b3f7-3369d5747d72.png)

**Stash Version: (from Settings -> About):**
0.17.0

**Comment by WithoutPants** [comment]
Fixed in 0.17.1.
