### ISSUE TITLE
[Enhancement] Capability of running Scene Filename Parser on certain folders

### ISSUE THREAD

**Issue by Cutters1982** [stashapp/stash#302]
Hi there

Happy New Years guys.

I would like to suggest an enhancement to the Scene Filename Parser where you can select what folders in your Archive that you wish to run it on, rather than it scanning everything every time, otherwise you keep having to untick stuff that you dont want it to rename.

This would be beneficial when adding a folder into your archive of stuff from a studio, you can then go into the filename parser and just tick that studio and carry out the title renaming

Regards

**Comment by Leopere** [comment]
My problem is there are various sources for various pieces of content and they all have their own structures by default so I can see something like this being reasonable at least if you could select and add regex patterns for the various subdirs.

**Comment by bnkai** [comment]
Should be covered by #327.
Feel free to reopen otherwise.
