### ISSUE TITLE
[Bug Report] [UI] Tagger modal window alias overflow is clipped

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#3028]
**Describe the bug**
When using the tagger modal window, if a performer has enough aliases, the list of aliases will be truncated

**To Reproduce**
Scrape any performer with a lot of aliases using the tagger module

**Expected behavior**
The end-user should be able to see the entire list of aliases

**Screenshots**
![image](https://user-images.githubusercontent.com/37937507/197119591-5d8d3a95-4d1c-4015-9ab6-e528e134f451.png)

**Stash Version: (from Settings -> About):**
v0.17.0-7-g33de28ce

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 106.0.1370.47

**Additional context**
The solution could be as simple as adding `overflow: scroll` CSS to the relevant alias row.

**Comment by WithoutPants** [comment]
It is intended that the alias list is truncated. It's not intended that the list is cut off like that. The correct behaviour is that only the first line is visible, and the rest are shown when hovering over the list.
