### ISSUE TITLE
[Feature] GetThumbnail resolution to low

### ISSUE THREAD

**Issue by PenDrag0n7** [stashapp/stash#303]
The resolution of gallerias thumbnails are a bit to low

100px shows up way too blur (365px would be nicer)
`imaging.Resize(srcImage, 100, 0, imaging.NearestNeighbor)`

**Comment by bnkai** [comment]
I wouldn't label that as a bug , maybe enhancement is better.
I thinks there is a tradeoff between how much scrolling you need to  do on the galleries page,  and the image size , quality of the thumbnails.
I suppose we could change that to 200 or 300 and maybe also the reisizer to lanczos or linear for a performance/quality aspect.
Anymore input is welcome though

**Comment by Leopere** [comment]
There are image optimization tools for this if we don't want to just simply restrict size.

**Comment by PenDrag0n7** [comment]
maybe an override in the yaml could work

**Comment by Leopere** [comment]
Sounds a bit feature creepy but it would be good if it was variable.

**Comment by quantumbeep** [comment]
Good thumbnails are a great thing to have for this use case (I use 400px in my main image manager). Since large images are expensive to scroll, perhaps it would make sense to favor pagination over large scrolling zones?

**Comment by Leopere** [comment]
Thumbnails will be super important I even see in a Version 2 feature-set where we use the metadata from the #334 O Counter helps determine screenshots from content to be used as the suggested thumbnail.

**Comment by bnkai** [comment]
Closing as #336 is merged.
