### ISSUE TITLE
[Bug Report] Migration failed: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by joyov** [stashapp/stash#3033]
**Describe the bug**
Database migration fails when migrating from schema version 31 to 36.

**To Reproduce**
1. Start new Stash version
2. Open Stash, click migrate
3. Wait

**Expected behavior**
Database migration should run without errors.

**Screenshots**
![](https://user-images.githubusercontent.com/56232119/197336009-07ba860f-9c52-4370-8fe0-10673556a98d.png)

**Stash Version: (from Settings -> About):**
v0.16.1-109-g5e194851

**Additional context**
Stash seems to be working, even though I got this migration error. Should I be worried?

**Comment by DingDongSoLong4** [comment]
Are you running stash behind a reverse proxy (nginx, apache, etc)?
Migrations can take very long (especially the one from schema 31 to 32) so the proxy can timeout which will cause an error like this. The migration will still continue though so the fact that it works now means nothing went wrong, and the logs should show that.

I would personally still consider this to be a bug though, it would be better if a migration worked more like a scan where the process is started/stopped asynchronously.

**Comment by joyov** [comment]
I restored the database, increased the timeout in the reverse proxy's config and run the migration again. It worked flawlessly this time, but took longer than the previous timeout value indeed. Thanks!
