### ISSUE TITLE
[Feature] Fingerprint gallery zip files like scenes

### ISSUE THREAD

**Issue by stg-annon** [stashapp/stash#3035]
### **Is your feature request related to a problem? Please describe.**
Stash tracks zip files by their paths instead of by fingerprints like it does with scenes, one of the best things about stash IMO is the reliance on hashing to rediscover moved files and how quick it can perform a scan with just OSHashes. When a zip file is scanned stash will currently calculate a checksum of each individual image inside the archive which can be quite slow, significantly increasing scan times.

### **Describe the solution you'd like**
When a zip file is scanned, we take a SHA-256 hash or alternative of the zip file itself with the option of hashing all the images inside on scan or via generate if the user wants to, as this can still be helpful for deduplication. This would make for faster scanning of zip files and help relocate any moved/renamed zip files 

### **Describe alternatives you've considered**
Keeping zip files in place on the file system and not moving them after the initial scan, the initial scan may take some time but after its done scan speed increases, this works but sometimes for the sake of organization the file path will change and need to be rescanned which causes all the images to be rehashed again

**Comment by WeedLordVegeta420** [comment]
Absolutely in favor of this. Eliminating unnecessary scans of unchanged zip files could speed up scanning a lot.

**Comment by DingDongSoLong4** [comment]
An MD5 fingerprint is actually already being stored for zip files, and if they are moved/renamed then it does use that to change the path of the zip file itself in the database. Already-existing zip files that haven't been moved are compared by modtime and then hash, and won't have any containing images rescanned.

What does happen though is that it rescans/rehashes all the containing images in addition to the zip file itself when it detects a move, which is unnecessary because an identical hash would mean that the images inside are identical.

**Comment by stg-annon** [comment]
> An MD5 fingerprint is actually already being stored for zip files

I believe this is an MD5 of the filename/path not of the file itself, but I may be wrong

**Comment by DingDongSoLong4** [comment]
No the fingerprint is of the actual file, renaming the file or the title of the gallery doesn't change it, and running md5sum on the file itself gives the same hash as shown in stash.

**Comment by stg-annon** [comment]
oh perfect just need to change the scan process a little bit then

**Comment by WithoutPants** [comment]
> What does happen though is that it rescans/rehashes all the containing images in addition to the zip file itself when it detects a move, which is unnecessary because an identical hash would mean that the images inside are identical.

The contents are rescanned because otherwise there is no way to rescan zip file contents. Moving or touching a zip file allows its contents to be rescanned in the event that an earlier scan didn't correctly populate the entirety of a zip file's contents.

**Comment by DingDongSoLong4** [comment]
Makes sense. The optimal solution would probably be to have some kind of way to rescan specific files from scratch (bypassing the modtime check) which would allow for the identical hash optimization, but that would probably be quite complex for very little benefit.

**Comment by WithoutPants** [comment]
Closing this as the premise seems based on a misunderstanding of the current implementation. Feel free to open another issue if you have a proposal to avoid rescanning moved zip file contents.
