### ISSUE TITLE
[Bug Report] Stash fails to import some files when they are symlinks or hardlinks

### ISSUE THREAD

**Issue by sodamouse** [stashapp/stash#3042]
**Describe the bug**
Stash fails to identify some files when they are symlinks or hardlinks.

```
22-10-24 13:43:06Error   error processing "filename.mp4": calculating fingerprint for file "filename.mp4": calculating oshash: oshash head: buffer is not a multiple of 8
```

**To Reproduce**
1. Have file be a symlink or hardlink
2. Try to import
3. Some times it fails

**Expected behavior**
Import should be successful

**Screenshots**
N/A

**Stash Version: (from Settings -> About): 
0.17.1

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser: Librewolf
 - Version: 105.0.3

**Additional context**
This is apparently a recurring bug that was solved before.

**Comment by WithoutPants** [comment]
I've been able to reproduce this for symlinks, _not_ for hard links.

**Comment by WithoutPants** [comment]
Related #2196.
