### ISSUE TITLE
[Bug Report] Migration 32 failed

### ISSUE THREAD

**Issue by sapp-py** [stashapp/stash#3059]
**Describe the bug**
Got the following error message by migrating from 31 to 36:
`An error occurred migrating the database to the latest schema version. The backup database file was automatically renamed to restore the database.
error performing migration: running post migrations for schema version 32: deleting placeholder folder: not deleting placeholder folder because it has 1 files
 `

**To Reproduce**
1. migrate from 31 to 36 

**Screenshots**
<img width="888" alt="Screenshot 2022-10-30 at 11 28 28" src="https://user-images.githubusercontent.com/117011181/198873936-7f4f037c-9e8c-40a6-a51a-5732ea195224.png">

**Desktop (please complete the following information):**
 - OS: stash on unraid (docker)
 - Browser chrome on macOS

**Comment by sapp-py** [comment]
Oh just saw the console printed the following:
```
INFO[2022-10-30 09:57:15] Running post-migration for schema version 32 
INFO[2022-10-30 09:57:15] Migrating folders                            
INFO[2022-10-30 09:57:16] Migrating 131420 files...                    
INFO[2022-10-30 09:57:26] Migrated 10000 files                         
INFO[2022-10-30 09:57:34] Migrated 20000 files                         
INFO[2022-10-30 09:57:43] Migrated 30000 files                         
INFO[2022-10-30 09:57:56] Migrated 40000 files                         
INFO[2022-10-30 09:58:04] Migrated 50000 files                         
INFO[2022-10-30 09:58:13] Migrated 60000 files                         
INFO[2022-10-30 09:58:22] Migrated 70000 files                         
INFO[2022-10-30 09:58:31] Migrated 80000 files                         
INFO[2022-10-30 09:58:40] Migrated 90000 files                         
INFO[2022-10-30 09:58:49] Migrated 100000 files                        
INFO[2022-10-30 09:58:58] Migrated 110000 files                        
INFO[2022-10-30 09:59:07] Migrated 120000 files                        
WARN[2022-10-30 09:59:15] Unable to migrate invalid path: data\tartube\Unsorted Videos\BoundHub - Lydia Vaughn in a Latex Straitjacket 1.jpg 
INFO[2022-10-30 09:59:17] Migrated 130000 files                        
INFO[2022-10-30 09:59:19] Finished migrating files                     
INFO[2022-10-30 09:59:20] Restoring backup database /root/.stash/stash-go.sqlite.31.20221030_095507 into /root/.stash/stash-go.sqlite
```

**Comment by WithoutPants** [comment]
That invalid path is preventing the migration. I'm not sure how you've got a path there with Windows path separators. There's two possible ways to fix. The easier way is probably to use the 0.16 version and delete the image corresponding to that path. The other way is to delete it manually via SQL.

**Comment by sapp-py** [comment]
I ran stash on windows before i put it on my unraid. Probably the path got in there, that time i ran it on windows.

Running image v0.16.1 and deleting that picture worked for me :)
Thank you
