### ISSUE TITLE
[Bug Report] Can't delete a scene that is playing

### ISSUE THREAD

**Issue by themese8** [stashapp/stash#3061]
**Describe the bug**

When trying to delete a scene that is playing, the grahql request hangs forever.
What I mean by playing, is that video player is loaded and has played, it can be either currently playing or paused for the bug to occur.

**To Reproduce**
1. Go to scene
2. Click play on video
4. Try to delete scene
5. Delete request hangs

**Expected behavior**
You should be able to delete a scene when the player is loaded and playing/paused

**Stash Version: (from Settings -> About):** 0.17.2

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Firefox
 - Version 106

**Additional context**
I think this bug was introduced in 0.17.2, it was working in 0.17.1

**Comment by WithoutPants** [comment]
I was _only_ able to reproduce this when browsing from Firefox. Issue isn't reproducible in Chrome.
