### ISSUE TITLE
[Bug Report] Duplicate Russian Federation entry in filter dropdown list

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#3063]
**Describe the bug**
The performer filter dropdown list contains a duplicate _Russian Federation_ entry when typing the string `rus`

**To Reproduce**
1. Go to *performers* from the main nav bar (localhost:9999/performers)
2. Click on the *Filter* icon
3. Filter by *Country* and *is* and type `rus`.
4. The dropdown list shows two Russian Federation entries, one entry with a flag, the other without.

**Expected behavior**
There should only be one Russian Federation entry

**Screenshots**
From step 3
![image](https://user-images.githubusercontent.com/37937507/199107993-dc15b1b0-1a4c-4658-80ef-d1fa066744b5.png)

When the rogue Russian Federation entry is applied to the filter there are no performers attached to it and the URL reads: `http://localhost:9999/performers?c=("type":"country","value":"rus","modifier":"EQUALS")&sortby=created_at&sortdir=desc`

**Stash Version: (from Settings -> About):**
v0.17.2-9-g270bc317

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge
 - Version 107.0.1418.26 (Official build) (64-bit)

**Comment by MrX292** [comment]
just did some tests. the filter seams to recognise [https://en.wikipedia.org/wiki/ISO_3166-1#Officially_assigned_code_elements ](https://en.wikipedia.org/wiki/ISO_3166-1#Officially_assigned_code_elements )alpha-2/alpha-3 codes` ru`/`rus` or `de`/`deu` so it breaks with alpha-3 codes since they are saved as alpha-2
