### ISSUE TITLE
[Feature] Display performer images in the select performers dropdown input forms

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#3076]
**Is your feature request related to a problem? Please describe.**
Between performers with the same name, similar name, or the sheer amount of them, and even if one uses a "disambiguation" with their performers, it becomes difficult to distinguish performers from one another just based on their name alone.

**Describe the solution you'd like**
Include their avatar/image beside their name in the dropdown input forms. Other database sites, such as IMDB have a similar feature (See image)

![image](https://user-images.githubusercontent.com/37937507/199927270-e473f3f2-b722-424a-bcb7-f98d0ccaada3.png)

![image](https://user-images.githubusercontent.com/37937507/199929886-d98252e5-c2fb-4df4-8cd1-abb82f7b2155.png)

**Additional context**
- Make the presentation of this element amenable to stylizing with custom CSS for those that wish to do so
  - This may include displaying/hiding supplemental details such as nationality, year of birth, aliases, gender, etc.

**Comment by PhuriousGeorge** [comment]
Just noting that this seems related to your prior request #2984

**Comment by echo6ix** [comment]
> Just noting that this seems related to your prior request #2984
Yes it does. They are very similar, but #2984 seems like an inferior implementation. I am going to close it. Thanks for bringing it to my attention.

**Comment by godysseus** [comment]
That would be great

**Comment by echo6ix** [comment]
Implemented with #4227

**Comment by DogmaDragon** [comment]
Just for the record, it's not implemented yet. It's an upcoming feature in v0.24.0.
