### ISSUE TITLE
[Feature] Change default sort

### ISSUE THREAD

**Issue by dumdum7** [stashapp/stash#3079]
**Is your feature request related to a problem? Please describe.**
I like to have the default sort on the Scenes page set to Random. When I go to a performer's page and click on the Scenes tab or on its <x> scenes button, the default scene sort is always by date. It's annoying since when I want to watch a performer's scenes, I don't want to see their oldest scenes but random scenes. I always end up changing the sort order.

**Describe the solution you'd like**
Introduce a setting to change the default sort.

**Describe alternatives you've considered**
Respect the default Scenes filter on the performer's scenes page.

**Comment by skier233** [comment]
The sorting is stored with a saved filter so if you set a saved filter as default that will accomplish the same thing.

**Comment by dumdum7** [comment]
> The sorting is stored with a saved filter so if you set a saved filter as default that will accomplish the same thing.

The saved filter (and hence the default sort) is not used when going to the Performers page, and clicking on this button:
![image](https://user-images.githubusercontent.com/95527094/200116094-0b2fa0e0-c11e-457d-84d9-58bd10ba25fe.png)
... or clicking on the performer and going to the Scenes tab:
![image](https://user-images.githubusercontent.com/95527094/200116155-8cd51d31-2bd4-40b9-a83b-9b31d7a96935.png)

**Comment by scyllaL** [comment]
I totally agree, that would be a great functionality!

But there is a workaround I use, which works okay for me:
If you create saved filters for your favorite Performers, you can but those saved filters on your landing page, so you always get a random listing. It's obviously not perfect, but I have set it up for Performers, Scenes, Images, Tags.

1. Create a saved filter (e.g. for Scenes of Performer A)
2. Go to Homepage (called "Stash" in navigation bar)
3. scroll to the very bottom, there is a button on the right hand side called "Customize"
4. There you can Add new Saved Filters and sort them accordingly

If you now go to your Homepage you see the first x Entries as per your defined filter and you can directly access the other entries by clicking on "View All" on the right side.
