### ISSUE TITLE
[Feature] Playlist Type Functionality.

### ISSUE THREAD

**Issue by synsyn93** [stashapp/stash#309]
**Describe the solution you'd like**
Filters and then being able to have what I guess is what I'd call a play list on your filters.  

So lets say you do a filter on all 5 star scenes, upon going to the scene player those scenes are in a playlist so you can basically go to next video, or use the random play function to randomly go through to another scene in said playlist.

I could see this being useful for many watch activity and also cataloging / tagging scenes.  Typical workflow would to set a filter on unwatched scenes of a performer.  Play random could then be used to randomly select scenes.  Conversely for cataloging / organizing you could set a filter and then roll through those videos adding tags / studios and what not.

**Comment by Leopere** [comment]
Isn't this already possible @WithoutPants or @bnkai I believe we recently merged this didn't we?  Related: #226 #226 #255

**Comment by synack12** [comment]
You can do the filter or search from the scenes tab, but when in the scene player you cannot go to the next scene or play random again. To do that you have to go back to the scenes tab then select another video or do play random again. It works just not very slick.  Hope that makes sense.

**Comment by Leopere** [comment]
Fair then we definitely need to expand on it.
