### ISSUE TITLE
[Bug Report] "too many SQL variables"

### ISSUE THREAD

**Issue by waffle2028** [stashapp/stash#3091]
**Describe the bug**
`too many SQL variables` error occurs when auto-tagging a lot of files(over 225k files)

**To Reproduce**
1. Create a new tag that will be applied to a lot of files when auto-tag (in my case, over 225k files)
2. Click on 'Auto Tag'
3. Wait until the operation ends

**Expected behavior**
Files should be auto-tagged with the new tag

**Screenshots**
![image](https://user-images.githubusercontent.com/92328274/200264494-8c349958-45b4-49d2-bdd5-c0696eff08bd.png)
`error auto-tagging tag 'twitter': processing images: error querying images with regex ... too many SQL variables` error occurs
The new tag is not applied to any files.

**Stash Version: (from Settings -> About):**
v0.17.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 107.0.5304.88

**Comment by zosky** [comment]
getting this too when asking the API to list half million images (using path regex & pageSize -1)
for now, I'm looping through 1k batches ... a few hundred times

if anything more can help, hollar
