### ISSUE TITLE
v0.17.2

### ISSUE THREAD

**Issue by seyma-si** [stashapp/stash#3092]
### Discussed in https://github.com/stashapp/stash/discussions/3048

<div type='discussions-op-text'>

<sup>Originally posted by **WithoutPants** October 25, 2022</sup>
# Release Notes
## v0.17.2 - 2022-10-25

Please view the release notes for 0.17.0 if you are upgrading from a version prior to 0.17.0.

### 🐛 Bug fixes
* Fix file rename detection on case-insensitive file systems. ([#3047](https://github.com/stashapp/stash/pull/3047))
* Fix size calculation for symlinks. ([#3046](https://github.com/stashapp/stash/pull/3046))
* Use file base name as title if title is empty in scraper operations. ([#3040](https://github.com/stashapp/stash/pull/3040))
* Fix error when submitting fingerprints from deleted scene. ([#3039](https://github.com/stashapp/stash/pull/3039))
* Fix moved zip file creating duplicate galleries. ([#3036](https://github.com/stashapp/stash/pull/3036))

<hr /><em>This discussion was created from the release <a href='https://github.com/stashapp/stash/releases/tag/v0.17.2'>v0.17.2</a>.</em></div>

**Comment by seyma-si** [comment]
> ### [#3048'de](https://github.com/stashapp/stash/discussions/3048) tartışıldı[](https://github.com/stashapp/stash/discussions/3048)
> İlk olarak **WithoutPants** tarafından 25 Ekim 2022 tarihinde gönderildi
> 
> # Sürüm notları
> ## v0.17.2 - 2022-10-25
> 0.17.0'dan önceki bir sürümden yükseltme yapıyorsanız, lütfen 0.17.0 sürüm notlarına bakın.
> 
> ### 🐛Hata düzeltmeleri
> * Büyük/küçük harfe duyarlı olmayan dosya sistemlerinde dosya yeniden adlandırma algılamasını düzeltin. ( [#3047](https://github.com/stashapp/stash/pull/3047) )
> * Sembolik bağlantılar için boyut hesaplamasını düzeltin. ( [#3046](https://github.com/stashapp/stash/pull/3046) )
> * Sıyırıcı işlemlerinde başlık boş ise dosya tabanı adını başlık olarak kullanın. ( [#3040](https://github.com/stashapp/stash/pull/3040) )
> * Silinen sahneden parmak izi gönderirken hatayı düzeltin. ( [#3039](https://github.com/stashapp/stash/pull/3039) )
> * Yinelenen galeriler oluşturan taşınan zip dosyasını düzeltin. ( [#3036](https://github.com/stashapp/stash/pull/3036) )
> 
> _Bu tartışma [v0.17.2](https://github.com/stashapp/stash/releases/tag/v0.17.2) sürümünden oluşturulmuştur ._

**Comment by WithoutPants** [comment]
I don't know what is going on here.
