### ISSUE TITLE
[Enhancement] Adding Boobpedia as a scraper (primarily for info on Fake/Natural breasts)

### ISSUE THREAD

**Issue by VonTittyslappen** [stashapp/stash#310]
Hello :)

I would like to suggest adding Boobpedia as a data scraper for the app as this seems to be a reliable source of information for whether a woman has natural or fake breasts, cup size, etc. I must confess I'm not much of a fan of Freeones.

Cheers

**Comment by Leopere** [comment]
We're mainly going to offer a number of officially supported scrapers then potentially an API and system for adding you own and then we might maintain a repository of community scrapers for people to use via the official StashApp GitHub Org.

**Comment by Cutters1982** [comment]
that's great thanks :)

**Comment by Leopere** [comment]
We're likely going to have a pluggable scraper interface for the App itself so this is likely not going to be officially supported by us but I will mark it as a wants list item.

**Comment by bnkai** [comment]
Since Boobpedia is included as a sample xpath scraper in #333 i am closing this.
