### ISSUE TITLE
[Bug Report] Organized Before Saving Reverts Changes

### ISSUE THREAD

**Issue by velzy00** [stashapp/stash#3109]
**Describe the bug**
I've noticed that if you make changes to the a scene's info and click the organized button before saving, the scene reverts back to the most recently saved data, which undoes any of the unsaved changes that were made. 

**To Reproduce**
1. Make edits to a scene
2. Click organized 
3. Watch all the unsaved edits go away

**Expected behavior**
I would expect that clicking the organized button changes the organized status but doesn't kill unsaved changes.

**Stash Version: (from Settings -> About):**
v0.17.2-25-ga2ca266c

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave
 - Version: v1.45.123

**Comment by WithoutPants** [comment]
I'm unable to reproduce this on my machine on Chrome or Brave browsers.

**Comment by velzy00** [comment]
Well this is weird. I experienced it twice when using Stash yesterday and the day before, but I just tried it again and it's working as expected. Sigh, sorry for the time waste.
