### ISSUE TITLE
[Feature] Multiple accounts and users

### ISSUE THREAD

**Issue by kevinnord** [stashapp/stash#3119]
**Is your feature request related to a problem? Please describe.**
When enabling security for remote access, you are asked to create a user and password. It would be nice to support multiple users with their own profile 

**Describe the solution you'd like**
Support multiple users with their own profile (favorites etc)

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by WithoutPants** [comment]
Duplicate of #12 and #2337.
