### ISSUE TITLE
[Feature] Optional end for markers to use them as clips

### ISSUE THREAD

**Issue by ghost** [stashapp/stash#3147]
Allow the option to give an end to markers to use them as clips for example in [this case](https://github.com/stashapp/stash/issues/2511#issuecomment-1318682305).

**Comment by BonerFide** [comment]
One of the other related improvements is for the start times (and eventually end) times to be more precise. A whole second often catches a weird transition or starts too late. Ideally frame by frame but even just adding milliseconds (could be an optional config) would help.

**Comment by d3f113** [comment]
FYI: #3530 has a 200$ bounty on that feature

**Comment by p0rnb0x** [comment]
this feature + inheriting marker tags to their parent scenes would be so awesome
