### ISSUE TITLE
[Feature] Generate gallery from scene

### ISSUE THREAD

**Issue by AbhishekJ06** [stashapp/stash#315]
Hi folks,
Could we add a feature to generate gallery from scene just like sprite, and marker in the generate content section in stash settings

**Comment by Leopere** [comment]
This could be a feature added in the future.  Is there any further context you can bring to the feature suggestion in case we do develop this before the 1.0

**Comment by rainchaser210** [comment]
Couple of ideas:
1. Allow user to set # of images to be pulled (perhaps within a range, say min 1 max 50)
2. Allow user to preview/delete images captured before gallery is saved
3. Allow user to select gallery main display image
4. Allow user to select Image quality / dimension options
5. Allow bulk operations with a way to select multiple scenes without needing to do all scenes

**Comment by Phasetime** [comment]
Can be closed, IMO out of scope of stash. There are other programs to accomplish this task.

**Comment by stg-annon** [comment]
I would agree with this being out of scope for stash, closing for now
