### ISSUE TITLE
100% CPU usage (on all cores) for several minutes just to show Gallery Page (/galleries)

### ISSUE THREAD

**Issue by elshanta** [stashapp/stash#3167]
Hi,

Over 30 inefficient/unindexed SQL queries are done each time you open Galleries pages (/galleries) or change the page. Many of them take several minutes to resolve. 

`IMAGES SIZE 196.4 GB`

`GALLERIES 2,644`

`IMAGES 228,920`

The trace log is attached here (truncated because of stashapp max log size).
[trace.log](https://github.com/stashapp/stash/files/10050810/trace.log)

**Comment by WithoutPants** [comment]
There's a known issue that sorting by path is slow due to the changes in the table structure. I'd suggest sorting by something else until it is addressed.

**Comment by WithoutPants** [comment]
Having taken a closer look at the logs, I can't determine what sorting was actually used. What sorting and page size are you querying with?

**Comment by elshanta** [comment]
Gallery view using random sort (http://127.0.0.1:9999/galleries?sortby=random_73739160) took more than 15 minutes to load.

There are 16 very SLOW queries even using random sort. Full trace log:
[trace_random.log](https://github.com/stashapp/stash/files/10057729/trace_random.log)

**Comment by WithoutPants** [comment]
What page size are you using for this?

**Comment by WithoutPants** [comment]
I wasn't able to fully reproduce this, but I've raised a PR to hopefully address the obvious performance issues.

**Comment by WithoutPants** [comment]
I've closed this as completed based on the PR being merged. Please retest with the `develop` build, or wait for the 0.18 release to retest. I can reopen if this is still not addressed.

**Comment by elshanta** [comment]
It is working great right now. Thank you master!
