### ISSUE TITLE
[Bug Report] Greater/Less Than filter fails to change from 0 on create

### ISSUE THREAD

**Issue by scruffynerf** [stashapp/stash#3175]
**Describe the bug**
If you pick a number with the Greater Than (or Less Than, perhaps others) filter type, it fails to save the value at first

**To Reproduce**

- Pick a filter with Greater Than option, say File Count
- Select Greater Than
- Select 1
- Save
- The filter displays a Greater than 0
- Edit the existing filter
- Change it to 1 (or whatever)
- Save
- It correctly has the right value now.  It's only on the initial creation

**Expected behavior**
Should work the first time.

**Screenshots**
<img width="390" alt="dialog" src="https://user-images.githubusercontent.com/21144471/203431382-eae38b2c-c12b-414d-ae64-2b0deac950b1.png">
<img width="179" alt="incorrect 0" src="https://user-images.githubusercontent.com/21144471/203431379-50880a55-59c6-42c8-b514-3ff154bfb09a.png">
<img width="155" alt="correct 1" src="https://user-images.githubusercontent.com/21144471/203431373-740fd4a7-d01b-468a-a206-e929484209d8.png">

**Stash Version: (from Settings -> About):**

v0.17.2
Build hash:
02c2ad3f

**Desktop (please complete the following information):**
Varied

**Additional context**
Problem was in < .17, including 0.16.1

**Comment by WithoutPants** [comment]
Reproduce only in Firefox, and only when using the buttons to increment the number. Could not reproduce in Chrome, and entering the value manually also resulted in the filter being applied correctly.
