### ISSUE TITLE
[Bug Report] Watch activity: Counter not increased when video loops

### ISSUE THREAD

**Issue by QxxxGit** [stashapp/stash#3185]
When the loop setting is turned on, the counter does not increase but the duration watched does.

I tested using a 14s scene, 5% setting of video watched to increment counter. The original counter was 4 with a duration of 1:15. I looped 3 times, the duration changed to 1:57 but the counter was only 5.

Confirmed with another user on Discord

**Comment by WithoutPants** [comment]
There wasn't a conscious design decision made around this. I feel that the watch count should only increase once per page visit, while the watch duration should increase based on the watch time.
