### ISSUE TITLE
ScenePlayer page loads selector data too early

### ISSUE THREAD

**Issue by cj12312021** [stashapp/stash#3190]
**Describe the bug**
When navigating to the ScenePlayer page, all the selector data gets loaded as a part of the page initialization process. For users with a large number of performers in their database, this yields noticeable hanging when interacting with the video player as that data gets loaded, see https://discord.com/channels/559159668438728723/559159910550732809/1045196529012576286 for an example.

**Expected behavior**
Before the recent changes made to this page, I believe that data was previously loaded only when interacting with the source selector on the edit tab. Ideally, the code should revert back to that behavior.

**Stash Version: (from Settings -> About):**
v0.17.2-61-g03cd9529

**Comment by WithoutPants** [comment]
This has slowly been improved. There is only the movie selector left that could potentially bring in a lot of data.
