### ISSUE TITLE
[Bug Report] Saved filter does not save restore object order (ASC/DESC) 

### ISSUE THREAD

**Issue by JanJastrow** [stashapp/stash#3193]
**Describe the bug**
`Saved filters` do not seem to store the selected order of files/scenes/performers
Tested with scenes and performers.

**To Reproduce**
1. Filter objects
2. Select object order contrary to your default order
3. Save
4. Reload page and load saved filter
5. Still in my default order

**Expected behavior**
Saved filters should also save the order of the displayed objects

**Stash Version: (from Settings -> About):**
Latest dev build

**Comment by Teda1** [comment]
Slight correction. SavedFilters do store the sort order. The sort order just isn't getting applied on the content page. However, it does get applied on the front page in the recommendation rows.

**Comment by WithoutPants** [comment]
I'm not able to reproduce this. I created saved filters sorting by `file count` ascending and descending. Both worked as expected when selecting them after reloading.

**Comment by Teda1** [comment]
This is only reproducible when applying a filter directly from the scenes page. For example, if the current filter on the page is already sorted in descending order. Applying a filter that was saved in ascending order will remain in descending order.

https://user-images.githubusercontent.com/72030708/204164478-cec696e1-0633-42d8-8500-28d62ccc39c2.mp4
