### ISSUE TITLE
[Feature] Prevent transcoding

### ISSUE THREAD

**Issue by seducingbits** [stashapp/stash#32]
I noticed that Stash is transcoding x265 files and saves a copy x264 of the files in the metadata folder.

I quit Stash because my SSD which contains the metadata folder quickly ran out of space.

It would be nice if the transcoding could be deactivated, with the cost of no support for x265 files.

**Comment by StashAppDev** [comment]
I agree.  I want to add options to provide more control over where these generated files get placed as well as what gets generated.  This is something I'm going to work on in the near term.

**Comment by bnkai** [comment]
I would second an option , maybe in the config file just to disable transcoding.
I just do a custom buid and comment it out manually. Screenshots and scene previews are ok for my x265 files.
