### ISSUE TITLE
[Bug Report] Seed for Random sort only set on server launch

### ISSUE THREAD

**Issue by quantumbeep** [stashapp/stash#321]
The seed for the Random sort is only set once, on server launch. 

**To Reproduce**
Use the Random scene sort mode. It will always return scenes in the same order for the life of the server process.

**Expected behavior**
The sort order is randomized every time the scene list is generated.

**Additional context**
From querybuilder_sql.go, it looks like randomSortFloat is set to a single random value outside of any function:

![image](https://user-images.githubusercontent.com/59296460/72485749-5a89ea80-37ce-11ea-8758-b2dc2a3bc4ab.png)

If it were set to a new random value inside of getSort(), perhaps it would work as expected.

**Comment by WithoutPants** [comment]
From Discord:

> Stash11/26/2019
> Yeah I know about that.  That’s kind of recent:  before it would randomly sort for each request, but the problem with that is you can see duplicates as you page through the result since it would use a new seed all the time.  I use the same seed at startup now just so the random sort can page properly.  The ideal fix would be to send a seed from the UI for the server to use for that request.  The UI could change the seed whenever the random sort type is changed.  Just not something I got around to changing

I like that the random order is deterministic, because it means I can go back and forward in the pages and to and from scenes knowing that the same results will be there. Changing the seed when random is selected would be a decent compromise in my opinion.
