### ISSUE TITLE
[Bug Report] whitelisted .avif file is no longer added to the stash at all

### ISSUE THREAD

**Issue by therandomguy42** [stashapp/stash#3211]
**Describe the bug**
In version v0.16.1 it was possible to add .avif as an allowed image extension and it was added to the stash with a library scan,
with version v0.17.2 it can still be added to the image extension list, but the file seems to be ignored when adding files to the stash

**To Reproduce**
1. Go to 'Settings'
2. Go to 'Library'
3. Go to 'Image Extensions'
4. Click on 'Edit'
5. Add 'avif' to the list
6. Click 'Confirm'
7. Add a '.avif' file to your images folder
8. Go to 'Tasks' 
9. Start a 'Library Scan' (With all checked)
10. Start 'Auto Tag' (With all checked)
11. Start 'Generate Content'  (With default setting)

**Expected behavior**
Since .avif is not supported it should still throw an Error with 'error reading image <path><filename>.avif: image: unknown format' or similar.
But it should be added to the stash library (Images & Gallery) and tagged.

**Stash Version: (from Settings -> About):**
v0.17.2 (02c2ad3f)
v0.20.2 ([e685f8](https://github.com/stashapp/stash/commit/e685f80e3dd2575e7458302dbe63693aca7acfb9))

**Desktop (please complete the following information):**
 - OS: Windows ( stash-win.exe )
 - Browser: Chrome
 - Version: 107

**Additional context**
.avif file created with https://squoosh.app/ and https://github.com/lovell/avif-cli
Still a problem in v0.18 / v0.19 / v0.20.2

**Comment by DogmaDragon** [comment]
Reproduced on https://github.com/stashapp/stash/commit/e9fa7d071e3587d393cedca735874214e06ff9d9.

**Comment by therandomguy42** [comment]
Solved with https://github.com/stashapp/stash/pull/3913
