### ISSUE TITLE
Deathdate gets set to 0001-01-01 instead of null when blanking

### ISSUE THREAD

**Issue by DampToast** [stashapp/stash#3222]
**Describe the bug**
If you accidentally set the death date of a performer, then blank it out, the filter 'death date is not null' returns that performer.

**To Reproduce**
1. Edit and save a death date for a performer.
2. Blank out the death date and save it for a performer.
3. Filter performers to 'death date is not null'.  They will show up.

**Expected behavior**
Performers with blank death dates should not show up in this filter.

**Stash Version: (from Settings -> About):**
v0.18.0-1-gd2395e57

**Additional context**
I checked GraphQL and it returns null for the deathdate of these performers but checking the database itself when you blank it out it gets set to '0001-01-01' instead of null.  I'm guessing the filter doesn't see '0001-01-01' as null, which it's not, but it also doesn't show '0001-01-01' in the UI which is confusing.

**Comment by WithoutPants** [comment]
This appears to apply to all date fields.
