### ISSUE TITLE
[Feature] Import disambiguated names on update to 0.19

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#3223]
**Is your feature request related to a problem? Please describe.**
If users already have a makeshift disambiguation field in their name field, it might be helpful to detect it, purge it, and add it to the new disambiguation field.

**Describe the solution you'd like**
- Detect disambiguated strings in the name field
  - Where we will assume a disambiguated string is any string in the name field between parentheses
  - If detected, purge this string from the name field
- Add the detected string to the new disambiguation field

**Comment by thismanyboyfriends** [comment]
Yep, lots of my performers have a disambiguation in parentheses already, this would be very useful. Could it be implemented as a plugin/scraper?
