### ISSUE TITLE
[Bug Report] Stash Url is not preserved after login needed

### ISSUE THREAD

**Issue by skier233** [stashapp/stash#3233]
**Describe the bug**
When using a specific url to stash and a login is required, the original url is not preserved

**To Reproduce**
1. Use a specific stash url
2. Login
3. See that the url stash takes you to is not the one you entered

**Expected behavior**
The url originally entered is redirected to after login

**Stash Version: (from Settings -> About):**
0.18

**Comment by bdbenim** [comment]
I also experience this. What I find is that any filters or sorting applied are lost. This is also evident from the login page URL, e.g. `http://{stash_instance}/login?returnURL=%2Fscenes` which has clearly lost the other parameters associated with filters/sorting/searches from the previous session.

My workaround for this is to login to stash in a new tab, then refresh the original tab.
