### ISSUE TITLE
[Bug Report] Front image of GammaEntertainment scenes cropped

### ISSUE THREAD

**Issue by whadup93** [stashapp/stash#3245]
**Describe the bug**
Front image of GammaEntertainment scenes is cropped at the top and bottom when scraping by URL

**To Reproduce**
1. Go to a GammeEntertainment Movie (e.g. EvilAngel)
2. Scrape with URL
3. Scraped front cover image is cropped

**Screenshots**
![image](https://user-images.githubusercontent.com/66875432/205944792-2bedb2a3-ab5b-4bba-ab2d-45adadc14810.png)

I am using the latest version of community scrapers.

Possible fix:
Add ``?format=webp`` suffix for .jpg URL.

**Comment by Teda1** [comment]
This issue was created in the wrong repo. Please create the issue in the [Community Scrapper](https://github.com/stashapp/CommunityScrapers).

**Comment by whadup93** [comment]
Oh, my bad. Sorry for not noticing.
