### ISSUE TITLE
[Bug Report] Adds wrong missing performer when scraping

### ISSUE THREAD

**Issue by DogmaDragon** [stashapp/stash#3248]
**Describe the bug**
When scraping a scene (only tested with scrapeByURL) and clicking + to add missing performers if you click to add anything but the first performer it adds the performer you clicked, but then removes the random one from the list and keeps the one you clicked to add (maybe it's not random, but I haven't found the pattern).

**To Reproduce**
1. Click scrapeByURL on a scene that has performers, not in your database.
2. Click + on any performer but the first one

**Expected behavior**
Correct performers are being added and removed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/103123951/206186675-442f7682-46e5-4a0b-8758-4579016542c6.png)![image](https://user-images.githubusercontent.com/103123951/206186719-a2b33696-30c4-41cf-bfdf-8f8b6901c9c8.png)

In the example, I clicked to add `Mirella Dias`, and it added it but removed `Maurinho` from the list, but still shows `Mirella Dias` as missing. 

**Stash Version: (from Settings -> About):**
v0.18.0-8a649f02

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi 5.5.2805.50

**Comment by xx790** [comment]
I also got this bug.
I think it also bugged for me when I clicked the first performer.
The situation: I want to add all new performers and click all of them in order. After clicking the first one from the left I already got this bug - have the first performer both in the list and as a + button, some other button removed.

Windows 10, Edge browser
