### ISSUE TITLE
[Bug Report] Bulk manual file generation doesn't work

### ISSUE THREAD

**Issue by desertwitch** [stashapp/stash#3254]
**Describe the bug**
When manually triggering a bulk/mass/batch file generation (i.e. marker previews, previews, scrubber sprites) the generation job always finishes instantly returning that zero files were generated, despite the fact that there are scenes without the required file (i.e a marker preview) in the database. There are no errors in the log and this problem occurs regardless of the state of the "Overwrite existing generated files" option.

**To Reproduce**
Tasks -> Generated Content -> Generate

**Expected behavior**
For the scenes missing the required files to be selected and those files to be generated by the manual generation job.

**Stash Version: (from Settings -> About):**
v0.18.0 / 8a649f02 (Docker)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 107.0.1.

**Additional context**
Just updated to v0.18.0, worked in previous version v0.17.2

**LOG:**
Info    Generate finished (1.553161084s)
Info    Generating 0 sprites 0 previews 0 image previews 0 markers 0 transcodes 0 phashes 0 heatmaps & speeds

**P.S. This also does not seem to work when triggering an individual generation for a single scene!**

**Comment by LeGrosFromage** [comment]
I do almost all my generations manually - I add the scene, get the metadata how I want then run the generation afterwards.  I've not had any issues with previews or scrubber sprites etc not being created (I don't use markers so can't speak to that).  Maybe check to see if permissions on the /generated folder are correct?

Also try restarting Docker (and Stash) - twice in the past week, when doing generations, my Docker has crashed and I've had to restart it all, although I'm inclined to think that's more an issue with Docker on my NAS than a Stash issue.

**Comment by desertwitch** [comment]
> I do almost all my generations manually - I add the scene, get the metadata how I want then run the generation afterwards. I've not had any issues with previews or scrubber sprites etc not being created (I don't use markers so can't speak to that). Maybe check to see if permissions on the /generated folder are correct?
> 
> Also try restarting Docker (and Stash) - twice in the past week, when doing generations, my Docker has crashed and I've had to restart it all, although I'm inclined to think that's more an issue with Docker on my NAS than a Stash issue.

Are you positive this works on v0.18.0 for you? Another user on Discord has also been running into this problem, no permissions or anything else has been changed since the upgrade to v0.18.0 and it's been working fine on the last stable version.

**Comment by LeGrosFromage** [comment]
I can 100% confirm it _does_ work (for me!) on a per-scene or multi-selection of scenes (run "Generate" from the ... menu when you have x number of scenes selected).  I have _not_ tried from Tasks across the whole library.

I have some scenes currently that are not in Stash, I will add them to the library and do a bulk generation to see what happens.

**Comment by LeGrosFromage** [comment]
Ok.  So I just added 10 scenes from an OF rip.  They scanned, got phashes, all that good stuff.  Hit Generate - and it's making them...

22-12-08 10:45:37
Info    
[generator] generating video preview for /StashMedia/_Temp/0gqmifou7gl0r8dja75sq_source.mp4
2022-12-08 10:45:36
Info    
[generator] generating sprite image for /StashMedia/_Temp/0gqmifou7gl0r8dja75sq_source.mp4
2022-12-08 10:45:36
Info    
[generator] generating sprite vtt for /StashMedia/_Temp/0gpjq9iypdqcp7gfwzqhj_source.mp4
2022-12-08 10:45:32
Info    
[generator] generating video preview for /StashMedia/_Temp/0gpjq9iypdqcp7gfwzqhj_source.mp4
2022-12-08 10:45:32
Info    
[generator] generating sprite vtt for /StashMedia/_Temp/0glsbsklvhxke33xsa0zh_source.mp4
2022-12-08 10:45:11
Info    
Generating 12 sprites 10 previews 0 image previews 0 markers 0 transcodes 2 phashes 2 heatmaps & speeds
2022-12-08 10:45:06
Info    
[generator] generating sprite image for /StashMedia/_Temp/0gpjq9iypdqcp7gfwzqhj_source.mp4
2022-12-08 10:45:06
Info    
[generator] generating sprite image for /StashMedia/_Temp/0glsbsklvhxke33xsa0zh_source.mp4
2022-12-08 10:45:06
Info    
[generator] generating video preview for /StashMedia/_Temp/0glsbsklvhxke33xsa0zh_source.mp4
2022-12-08 10:45:06
Info    
Generate started with 3 parallel tasks
2022-12-08 10:42:55
Info    
Scan finished (39.001805007s)
2022-12-08 10:42:49
Info    
[generator] generating phash sprite for /StashMedia/_Temp/0gs5bf39fl9m712p3aooc_source.mp4
2022-12-08 10:42:39
Info    
[generator] generating phash sprite for /StashMedia/_Temp/0gre5nv6bvvousvczjatw_source.mp4
2022-12-08 10:42:38
Info    
[generator] generating phash sprite for /StashMedia/_Temp/0gr8i7393q2gn0h94mkca_source.mp4
2022-12-08 10:42:37
Info    
[generator] generating phash sprite for /StashMedia/_Temp/0gqzz1970r80fr59vqwhc_source.mp4
2022-12-08 10:42:30
Info    
[generator] generating phash sprite for /StashMedia/_Temp/0gqv5txf9k5j0dih0sres_source.mp4
2022-12-08 10:42:29
Info    
[generator] generating phash sprite for /StashMedia/_Temp/0gqyr2uw4yld53tb52jin_source.mp4
2022-12-08 10:42:29
Info    
[generator] generating phash sprite for /StashMedia/_Temp/0gqsb7qnjhqfv5iwc1fw7_source.mp4
2022-12-08 10:42:22
Info    
Creating screenshot for /StashMedia/_Temp/0gs5bf39fl9m712p3aooc_source.mp4
2022-12-08 10:42:22
Info    
/StashMedia/_Temp/0gs5bf39fl9m712p3aooc_source.mp4 doesn't exist. Creating new scene...
2022-12-08 10:42:22
Info    
Calculating fingerprints for /StashMedia/_Temp/0gs5bf39fl9m712p3aooc_source.mp4 ...
2022-12-08 10:42:21
Info    
Creating screenshot for /StashMedia/_Temp/0gre5nv6bvvousvczjatw_source.mp4
2022-12-08 10:42:21
Info    
/StashMedia/_Temp/0gre5nv6bvvousvczjatw_source.mp4 doesn't exist. Creating new scene...
2022-12-08 10:42:21
Info    
Creating screenshot for /StashMedia/_Temp/0gqzz1970r80fr59vqwhc_source.mp4
2022-12-08 10:42:21
Info    
/StashMedia/_Temp/0gqzz1970r80fr59vqwhc_source.mp4 doesn't exist. Creating new scene...
2022-12-08 10:42:21
Info    
Creating screenshot for /StashMedia/_Temp/0gr8i7393q2gn0h94mkca_source.mp4
2022-12-08 10:42:21
Info    
/StashMedia/_Temp/0gr8i7393q2gn0h94mkca_source.mp4 doesn't exist. Creating new scene...
2022-12-08 10:42:21
Info    
Calculating fingerprints for /StashMedia/_Temp/0gre5nv6bvvousvczjatw_source.mp4 ...
2022-12-08 10:42:21
Info    
Calculating fingerprints for /StashMedia/_Temp/0gr8i7393q2gn0h94mkca_source.mp4 ...
2022-12-08 10:42:21
Info    
Calculating fingerprints for /StashMedia/_Temp/0gqzz1970r80fr59vqwhc_source.mp4 ...
2022-12-08 10:42:20
Info    
Creating screenshot for /StashMedia/_Temp/0gqsb7qnjhqfv5iwc1fw7_source.mp4
2022-12-08 10:42:20
Info    
/StashMedia/_Temp/0gqsb7qnjhqfv5iwc1fw7_source.mp4 doesn't exist. Creating new scene...
2022-12-08 10:42:20
Info    
Creating screenshot for /StashMedia/_Temp/0gqyr2uw4yld53tb52jin_source.mp4
2022-12-08 10:42:20
Info    
/StashMedia/_Temp/0gqyr2uw4yld53tb52jin_source.mp4 doesn't exist. Creating new scene...
2022-12-08 10:42:20
Info    
Creating screenshot for /StashMedia/_Temp/0gqv5txf9k5j0dih0sres_source.mp4

**Comment by desertwitch** [comment]
Thanks for getting back to this, and you're on v0.18.0 build hash 8a649f02?

**Comment by LeGrosFromage** [comment]
It just finished, all scenes have previews and scrubbers.  Sorry bro.  Probably not what you want to hear...!

Yes, current version:
Latest Version
Latest Version Build Hash:
8a649f02

**Comment by desertwitch** [comment]
> 

I'm glad it works for you, thanks for taking the time testing this, I'll try to dig more into why it doesn't work for me and the other user on Discord.

**Comment by LeGrosFromage** [comment]
Not a problem.  Feel free to holler if I can help in anyway.

**Comment by desertwitch** [comment]
Okay the award for the dumbest person goes out to me today, I always misunderstood marker preview generation as Stash **automatically** segmenting scenes (without existing markers) and **creating both markers and previews automatically**.

In fact I needed to manually create the markers first, after which the marker preview generation worked just fine for those manually created markers.

I need to create the markers, Stash doesn't do it for me, I'm an idiot - thanks a lot for your testing nevertheless.

**Comment by LeGrosFromage** [comment]
No problem.  I wish it did create markers at key points automatically!  Maybe that's a 0.19 feature ;-)
