### ISSUE TITLE
[Feature] Region-based Looping (a.k.a. A/B looping)

### ISSUE THREAD

**Issue by ratbastid-1** [stashapp/stash#3264]
While playing a video, enable the user to mark the start and end points of a region of the video. The player will then loop that region until stopped by the user.

**Comment by ratbastid-1** [comment]
That would be a way to do it, but I'm picturing something that doesn't have to leave behind an artifact like a Marker--it's just an ephemeral behavior of the player. 

mpv and its derivatives all do this.

**Comment by StashPowerUser** [comment]
I'd really like to see end time and looping for markers.

If you could use the simple mpv type approach to looping and then create a marker from that, it would be great as well.

**Comment by ratbastid-1** [comment]
Hey look, there's a plugin for it: https://github.com/phhu/videojs-abloop

**Comment by pjsentry** [comment]
> I'm picturing something that doesn't have to leave behind an artifact like a Marker--it's just an ephemeral behavior of the player.

A/B looper as an ephemeral feature of the video player can be a distinct, but related, feature from the "end" timestamp of the Marker. Selecting a marker with an end time would just pre-configure the video player. Having a/b loop be part of the Marker system gives it all the same niceties such as tagging, animated previews, global search, backups, etc.

With that said, the marker thumbnail would need a distinct way to distinguish itself from a typical bookmark-like marker.

**Comment by chickenwingavalanche** [comment]
I've started work toward this feature on my fork and would like to get this merged in for everyone 😄 

As an initial step, I've integrated the plugin suggested above, and added `l` as a keyboard shortcut to control it. There's a PR here: #3904
