### ISSUE TITLE
[Feature] Allow soft deletes of media (ignore on re-scan)

### ISSUE THREAD

**Issue by dietbepis** [stashapp/stash#3268]
**Is your feature request related to a problem? Please describe.**
I torrent the media I put in my stash through a private tracker and I have Stashapp scan my torrent client's /downloads folder to add new content. Since I want to seed for as long as possible to boost my seed ratio, I keep all my torrents active. If I have Stashapp scan /downloads, add a media file, and I delete that file from Stashapp, the media file gets re-added once I scan /downloads again. Even if I delete the file from my filesystem, my torrent client will automatically replace the deleted file once it notices it's not there.

**Describe the solution you'd like**
A sort of soft delete function would be great. For example, if I remove a media file from Stashapp, I would be able to keep the file on my filesystem and when I re-scan my /downloads folder, Stashapp ignores the filename that was soft-deleted.

**Describe alternatives you've considered**
I could keep two copies of my stash, but that seem overkill. I could delete the file from my filesystem, but I can't find a way to keep Deluge or qBittorrent from automatically re-downloading the file if the torrent is active.

**Comment by p0rnb0x** [comment]
Add the folder to "Excludes" not working?
Remove from Stash once n add folder to Excludes

**Comment by dietbepis** [comment]
I suppose that would work but it seems a little cumbersome to keep adding folders to be excluded when I want to delete something. Maybe adding a checkbox on the delete modal that says “Add containing folder to be excluded from re-scan” would be more elegant? I don’t mind working on this if so.

**Comment by elkorol** [comment]
I think, if a soft delete exclusion list, it should appear in Settings > Library but it would be preferable to be a separate exclusion list to video/image/gallery exclusion patterns, for sake of keeping regex exclusions separate from absolute file path exclusions

**Comment by dies-das-ananas** [comment]
Possible workaround: Assuming you are running your server on linux, you can simply make your stash location separate from your download location and hardlink your downloads (doing `cp -lr downloads\newporn stash\newporn`). This will not copy the files, so your stash will not be duplicated. If you delete one of the videos from stashapp, you will still have the other hardlink in the downloads directory pointing to the file and can continue seeding.

**Comment by dietbepis** [comment]
@dies-das-ananas I ended up adding a 'delete' tag and a default filter that excludes videos tagged with it. Your solution is probably better though. It might be useful to make that a built-in behavior (similar to how Radarr and Sonarr hardlink media files). Going to close this media request and
