### ISSUE TITLE
[Bug Report] Cannot create performer from search without changing name

### ISSUE THREAD

**Issue by bdbenim** [stashapp/stash#3270]
**Describe the bug**
When you search for a performer and then press the "new" button, stash auto-populates the name based on the search string. If this name, or any other field, is not altered, then the Save button is disabled. I ran into this bug today while creating placeholder performers today from a list of 200 videos I had just downloaded. I wanted to make sure that all performers existed before scanning them, so that their names could be scraped from the filenames and automatically added to each scene, so I wasn't concerned with filling in any of their information yet. If I searched for just part of their name and then added the rest on the "Create Performer" page, then everything worked fine. But if I searched for their full name and then only wanted to save that on the next page, I couldn't do so. I tried entering text into the name field and then removing it to trigger an event that would enable the button, but the button only became available as long as the contents of the field was different than how it had started. After removing the extra text, the button was disabled again.

**To Reproduce**
1. Go to "Performers" tab
2. Search for any string
3. Click "new" to go to the "Create Performer" form with the name filled in
4. Click "save" and nothing will happen

**Expected behavior**
Although this is an edge case, I expect the save button to be available as long as there is data to save, whether it was entered by the user or populated from a search.

**Stash Version: (from Settings -> About):**
v0.18.0
Build hash: 8a649f02

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 108.0.5359.73

**Comment by floydcg** [comment]
Same behavior for studio creation.

**Comment by DogmaDragon** [comment]
Can confirm the issue. Though it's really really edge case. I would think most people would choose at least gender in addition to name in which case the `Save` button becomes clickable.

**Comment by bdbenim** [comment]
Agreed that it's very edge case. I can't imagine there will be more than one or two times that this would ever happen to me again, because generally I'll add as much info as I can find for a performer and try to link them to stashdb. This was a very unique case where I had 100s of videos to scan and had to create a few dozen new performers, so I went with names only to clean up later.

It was also super easy to deal with after the first time it happened - I just left off at least one character while searching, and if the performer wasn't already there then I'd complete the name after clicking "new." So pretty minor all things considered.
