### ISSUE TITLE
[Feature] Configurable Dropdown object limit for forms

### ISSUE THREAD

**Issue by ALonelyJuicebox** [stashapp/stash#3277]
**Challenge:**
In a valid effort to improve performance, a 200 object limiter was placed on all dropdown forms in the 0.18 release.
To the credit of the devs, this _absolutely_ makes sense for the Studios and Performers dropdown forms. Lots of performers and studios out there, and users aren't often going to be hunting through those forms to find a studio/performer.

Things are different when it comes to Tags though. 
The 200 object limit is just a little bit too restrictive.

When it comes to Tags, I am constantly scrolling through that dropdown form and ensuring a video has been tagged with all the appropriate tags for that media. Based on comments on the Discord, I'm not alone in this thinking either.

**Proposed Solution:**
Add a configurable option under `Settings > Interface > Editing` to define the max object size of the dropdown.

**Proposed UX:**
![dropdownsettings](https://user-images.githubusercontent.com/76471868/207592405-50b0cd75-58c1-48da-9a16-2d7963128741.png)

**Comment by WithoutPants** [comment]
$50 bounty placed (contribution no. 626966)
