### ISSUE TITLE
Stash Setup Wizard

### ISSUE THREAD

**Issue by needsupport** [stashapp/stash#3294]
Oh no! Something went wrong!
Something went wrong while setting up your system. Here is the error we received:
error initializing the database: getting database schema version: unable to open database file: is a directory

Any idea how I can fix this?
Thanks

**Comment by YurikaL** [comment]
> error initializing the database: getting database schema version: unable to open database file: is a directory

Looks like you are pointing to a directory, not a file! Is there already a config file? Try setting `database:` option in the config to point to a file in a directory, even if that file doesn't exist yet, rather than to the directory itself.

**Comment by need4swede** [comment]
I had this issue. Had my db path set to a file and was still getting the error. I changed the port in the config file and it worked after a restart and using the new port.

**Comment by WithoutPants** [comment]
Closing as stale. Please open a discussion issue if this continues.
