### ISSUE TITLE
[Feature] Tab-oriented mode

### ISSUE THREAD

**Issue by Orthodox-531** [stashapp/stash#330]
I would like to be able to use the Stash UI in a tab-friendly way.
These are the things that would help (that I can think of):

- The clip viewer should launch in a new browser tab instead of the current one

- Deleting a clip should close the tab instead of returning to the Search view.

Since this is probably not what everyone wants, it may need to be an option.

**Comment by WithoutPants** [comment]
> The clip viewer should launch in a new browser tab instead of the current one

This can very easily be done by middle-clicking, ctrl-clicking on the scene (or shift-clicking to open in a new window).

Javascript can only close windows/tabs that were opened via a script (like for dialogs) - [see here](https://stackoverflow.com/questions/2076299/how-to-close-current-tab-in-a-browser-window). This would require changing all of the scene links to use javascript to open new windows instead.

This seems like a large change for what it likely a niche convenience issue. I don't think this is a feasible change.

**Comment by quantumbeep** [comment]
Your suggested method works fine in Chrome, but I think I'm seeing a quirk in Firefox: When I middle-click in the image thumbnail portion of a clip box, it launches a new tab, but also goes into pan-scroll mode (
![image](https://user-images.githubusercontent.com/59296460/73116000-da156900-3ef4-11ea-9dc0-ae6823edbea4.png)).

**Comment by Leopere** [comment]
I think you can turn that off with an `about:config` setting in firefox.  However, we should consider this it would be nice since due to an earlier PR you do lose your position in your search when you back button your way back to where you were.

**Comment by Leopere** [comment]
Also, it should absolutely be an option at least not necessarily a required setting, it should also be turned **off** by default.

**Comment by bnkai** [comment]
I always set `general.autoScroll` to false in my firefox but if you want to keep it ctrl-clicking still works as WithoutPants mentioned.

**Comment by Leopere** [comment]
I would be fine with considering this as a `wontfix` scenario to close the issue.
