### ISSUE TITLE
Error during scanning with a specific setup

### ISSUE THREAD

**Issue by HereIam80** [stashapp/stash#3304]
**Describe the bug**
There were multiple reports where during a scan the following error message appeared and no files were added:
`Error: exec: "ffprobe.exe": cannot run executable found relative to current directory`

Every time it was a new installation on windows and the users were just getting started.
Also ffprobe and ffmpeg were in the same folder as the stash-win.exe.
Stash was not located in it's default patch but on another drive, which was the same drive as the library (but a different folder).

The issue got resolved by either moving stash to it's default location or using the 0.17.0 version with the exact same setup so I believe this bug got introduced after that.

**To Reproduce**
I tried to recreate this issue to no avail.

**Stash Version: (from Settings -> About):**
0.18

**Additional context**
Here are the links to the three times I saw it reported and what got tried to resolve it:
https://discord.com/channels/559159668438728723/559159931505213440/1051590694940192849
https://discord.com/channels/559159668438728723/559159910550732809/1054405774274740234
https://discord.com/channels/559159668438728723/559159931505213440/1055782078077227088

**Comment by iljarogoff** [comment]
For me this only happened when having a new install with .18
I reinstalled with .17 and then scanning worked. I then upgraded existing installation with latest dev build and now scanning is working. It seems it only happens with a fresh install with .18

**Comment by Flashy78** [comment]
> 

Make sure you're installed in the default directory in Windows, so c:\Users\MYUSER\.stash\.
Or you could try what the person directly above you did to solve the issue.

**Comment by datadragon61** [comment]
> > 
> 
> Make sure you're installed in the default directory in Windows, so c:\Users\MYUSER.stash. Or you could try what the person directly above you did to solve the issue.

I have mentioned that I am using default paths and settings.
I don't know how he reinstalled with .17, I can only see the option to download the latest version which is .18 and even if installing .17 solves it it is still a bug.

I have opened the bug report to tell the developer about a bug or that's an intended behavior that users have to download it, try to setup, get this bug and then waste time to go look for version .17? 😆

**Comment by Flashy78** [comment]
@datadragon61 ok, sorry for trying to answer your question "What to do?".
If you want to draw attention to the original bug report submitted by HereIam80, add a thumbs up to it so it gets filtered up as an issue that multiple people are facing. Many many people have no problem running Stash on Windows, so it seems to be a unique bug that only a few people are encountering.
If you have any additional information beyond what the original but report described, please do contribute it to help with debugging.

**Comment by bnkai** [comment]
The main issue with this bug report is that i can not be  reproduced easily.
I tried reproducing in linux and windows(new vm setup using default options) but i couldnt.

The issue seems to be related to go 1.19 and more specifically to <https://pkg.go.dev/os/exec#hdr-Executables_in_the_current_directory>
- The `exec.LookPath` now doesnt return results if the executable eg `ffmpeg.exe` is in the cwd so in that case stash will try and download and save ffmpeg/ffprobe again. After it does that though eveything seems to work so i couldnt reproduce the error
- The `exec.Command` will produce a new error `cannot run executable found relative to current directory` if the command resolves to a reltative one and thus will fail. Nulling the error as mentioned in  <https://pkg.go.dev/os/exec#hdr-Executables_in_the_current_directory> `should` fix the isssue but again i couldnt reproduce to verify
The below is what should work for the command error
```diff
diff --git a/pkg/ffmpeg/downloader.go b/pkg/ffmpeg/downloader.go
index 304797f7..4f1a0ad4 100644
--- a/pkg/ffmpeg/downloader.go
+++ b/pkg/ffmpeg/downloader.go
@@ -3,6 +3,7 @@ package ffmpeg
 import (
 	"archive/zip"
 	"context"
+	"errors"
 	"fmt"
 	"io"
 	"net/http"
@@ -206,6 +207,10 @@ func getFFProbeFilename() string {
 // Checks if FFMPEG in the path has the correct flags
 func pathBinaryHasCorrectFlags() bool {
 	ffmpegPath, err := exec.LookPath("ffmpeg")
+	if errors.Is(err, exec.ErrDot) { // https://pkg.go.dev/os/exec#hdr-Executables_in_the_current_directory
+		logger.Warnf("%v", exec.ErrDot)
+		err = nil
+	}
 	if err != nil {
 		return false
 	}
@@ -232,6 +237,7 @@ func unzip(src, configDirectory string) error {
 			continue
 		}
 		filename := f.FileInfo().Name()
+
 		if filename != "ffprobe" && filename != "ffmpeg" && filename != "ffprobe.exe" && filename != "ffmpeg.exe" {
 			continue
 		}
diff --git a/pkg/ffmpeg/ffprobe.go b/pkg/ffmpeg/ffprobe.go
index d7bda62d..992ef43c 100644
--- a/pkg/ffmpeg/ffprobe.go
+++ b/pkg/ffmpeg/ffprobe.go
@@ -2,14 +2,16 @@ package ffmpeg
 
 import (
 	"encoding/json"
+	"errors"
 	"fmt"
 	"math"
 	"os"
+	"os/exec"
 	"strconv"
 	"strings"
 	"time"
 
-	"github.com/stashapp/stash/pkg/exec"
+	stashExec "github.com/stashapp/stash/pkg/exec"
 	"github.com/stashapp/stash/pkg/logger"
 )
 
@@ -78,9 +80,14 @@ type FFProbe string
 // NewVideoFile runs ffprobe on the given path and returns a VideoFile.
 func (f *FFProbe) NewVideoFile(videoPath string) (*VideoFile, error) {
 	args := []string{"-v", "quiet", "-print_format", "json", "-show_format", "-show_streams", "-show_error", videoPath}
-	cmd := exec.Command(string(*f), args...)
+	cmd := stashExec.Command(string(*f), args...)
 	out, err := cmd.Output()
 
+	if errors.Is(err, exec.ErrDot) { // https://pkg.go.dev/os/exec#hdr-Executables_in_the_current_directory
+		logger.Warnf("%v", exec.ErrDot)
+		err = nil
+	}
+
 	if err != nil {
 		return nil, fmt.Errorf("FFProbe encountered an error with <%s>.\nError JSON:\n%s\nError: %s", videoPath, string(out), err.Error())
 	}
@@ -97,7 +104,12 @@ func (f *FFProbe) NewVideoFile(videoPath string) (*VideoFile, error) {
 // Used when the frame count is missing or incorrect.
 func (f *FFProbe) GetReadFrameCount(path string) (int64, error) {
 	args := []string{"-v", "quiet", "-print_format", "json", "-count_frames", "-show_format", "-show_streams", "-show_error", path}
-	out, err := exec.Command(string(*f), args...).Output()
+	out, err := stashExec.Command(string(*f), args...).Output()
+
+	if errors.Is(err, exec.ErrDot) { // https://pkg.go.dev/os/exec#hdr-Executables_in_the_current_directory
+		logger.Warnf("%v", exec.ErrDot)
+		err = nil
+	}
 
 	if err != nil {
 		return 0, fmt.Errorf("FFProbe encountered an error with <%s>.\nError JSON:\n%s\nError: %s", path, string(out), err.Error())
```
If anyone can still reproduce the issue i can make a PR to test the above fix

**Comment by WithoutPants** [comment]
I'm able to reproduce this. It only occurred for me when the stash system was setup for the first time in the current working directory. Restarting stash and rescanning resolved the issue.
