### ISSUE TITLE
[Bug Report] Error when using tagger on Fileless scenes

### ISSUE THREAD

**Issue by Foucoubou** [stashapp/stash#3307]
When there is pushed button Scrape All and in the list is fileless scene
It throws error Cannot read properties of undefined (reading 'map')

I was thinking - it might be nice to upgrade the database model little bit and have also hashes on scene level (where there will be transfered from file and persist even if file gets deleted) + also scene duration, (from stashdb) which can be compared after that to file data (and somehow mark, that the file lenght differs.

**Comment by thismanyboyfriends** [comment]
Also been getting this issue. You can scrape scenes individually but not use the scrape all button.

**Comment by Foucoubou** [comment]
> Also been getting this issue. You can scrape scenes individually but not use the scrape all button.

Currently workaroundable by setting up filter :) but not much comfy :)

**Comment by Flashy78** [comment]
I was getting the javascript console error `v.data.scrapeMultiScenes[b] is undefined` when trying to Scrape All on a fileless scene.
