### ISSUE TITLE
[Bug Report] Can not scrape using URL on fileless scene creation

### ISSUE THREAD

**Issue by thismanyboyfriends** [stashapp/stash#3308]
**Describe the bug**
When creating a fileless scene, if you try to populate fields using a URL and the scrape from URL button on the right, then stash shows an error page.

**To Reproduce**
1. Go to Scenes
2. Click on "New" in the top right
3. Populate the URL field with a scrapeable URL, e.g. "https://www.manyvids.com/Video/2805677/Free-I-make-a-grilled-cheese-for-my-son/" (SFW) with the ManyVids scraper
4. Click the scrape button on the right in the URL field
5. Error screen appears

**Expected behavior**
Stash should scrape using the URL field and populate the scene fields

**Screenshots**
![image](https://user-images.githubusercontent.com/109775066/209543789-9e7253d2-9a93-43b6-817e-769316386aff.png)
<img width="1438" alt="Screenshot 2022-12-26 at 11 21 44" src="https://user-images.githubusercontent.com/109775066/209543863-199164a0-de2f-49ae-8718-0e6ecf1484e2.png">

**Stash Version: (from Settings -> About):**
v0.18.0
8a649f02
2022-11-30 01:28:00

**Desktop (please complete the following information):**
 - OS: MacOS 11.6.8 Big Sur
 - Browser: Brave 
 - Version: [Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (x86_64)](https://brave.com/latest/)

**Additional context**
Fileless scene creation seems quite buggy at the moment, I have come across a few pretty major bugs just by trying to scrape and submit things

**Comment by bnkai** [comment]
This should be fixed by <https://github.com/stashapp/stash/pull/3283>
You can either try latest develop build <https://github.com/stashapp/stash/releases/tag/latest_develop> or wait for 1.19

**Comment by WithoutPants** [comment]
Closing as completed.
