### ISSUE TITLE
[Feature] Search button

### ISSUE THREAD

**Issue by Orthodox-531** [stashapp/stash#331]
It would be great if I had a button (say, a magnifying glass inside the search text box) that I could click to execute a new search.

I understand the design of the UI, which is that new search is automatically performed when search criteria change. The reason the feature would be nice is because of my use case: I like to set the search to Random and execute a new search to get a new random selection of clips instead of scrolling.

Additionally, this makes it easier to navigate the library while a content import is in progress, since the results of a search will change without the underlying criteria changing.

**Comment by jeremymeyers** [comment]
I think a Dice button which would create a random selection of whatever the current display is based on current filters would be neat.

**Comment by kermieisinthehouse** [comment]
A re-randomize button has been implemented, and you can re-run a filter by just refreshing the page.
