### ISSUE TITLE
[Feature] Add favorite implementation to studios and tags

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#3313]
**Is your feature request related to a problem? Please describe.**
Stash currently lacks the ability to favorite a studio or a tag.

**Describe the solution you'd like**
Implement to favorite a studio or a tag ala performer favorites
- Grid views (tags, studios)
  - Show favorite icon
- Add favorite filter (for tags, studios)

**Comment by IntoTheBlackHole** [comment]
Can't believe that tags favorite feature doesn't exist.  
1000's of tags are messing up my stash. Favorite tags will help differentiate from automatically added tags.

**Comment by Dankonite** [comment]
Studios is already coming with the next update 
https://github.com/stashapp/stash/pull/4675
added tag favoriting myself, I got the db and the grid cards setup for it, just need to figure out adding a filter for it, but coming soon!
<img width="221" alt="image" src="https://github.com/stashapp/stash/assets/117317087/717f22f8-5888-4390-b877-71381583a3b8">
