### ISSUE TITLE
[Bug Report] Manual preview generation does not work

### ISSUE THREAD

**Issue by Written2001** [stashapp/stash#3314]
**Describe the bug**
When manually overwriting a scene preview on a scene that already has a preview either through the gui (Three dots > Generate > Previews)  or using GraphQL nothing is actually generated.

**Steps to reproduce the behavior in the gui:**
1. Take a scene that already has a preview 
2. Click on the three Dots  > Generate > Tick Previews > Tick Animated Preview Images > "Edit the Override Preview Generation Options"
3. Tick the "Overwrite existing generated files" switch
4. Click generate

**Steps to reproduce the behavior in the with the GraphQL Playground:**
1. Go to the GraphQL Playground
2. Fill in the request and the variables replace `sceneIDs` with a scene ID that already has a preview.
```
mutation MetadataGenerate($input: GenerateMetadataInput!) {
  metadataGenerate(input: $input)
}
```
```
{
  "input": {
    "sceneIDs": 4981,
    "previews": true,
    "previewOptions": {
      "previewSegments": 8,
      "previewSegmentDuration": 3,
      "previewPreset": "slow"
    },
    "overwrite": true
    }
}
```

**Expected behavior**
I would expect stash to generate a preview with the given variables (Segments, Duration etc.) and overwrite the existing scene preview.

**Logs**
Here is what is logged when sending the request through GraphQL. Nothing is generated and the scene preview is not overwritten/updated. 
```
22-12-27 22:17:45Info    Generate finished (3.07422ms)
2022-12-27 22:17:45Info    Generating 0 sprites 0 previews 0 image previews 0 markers 0 transcodes 0 phashes 0 heatmaps & speeds
2022-12-27 22:17:45Info    Generate started with 4 parallel tasks
```

**Stash Version: (from Settings -> About):**
```
v0.18.0
Build hash:
8a649f02
```

**Comment by bnkai** [comment]
Should be fixed by <https://github.com/stashapp/stash/pull/3256> ?
You can either try latest develop build <https://github.com/stashapp/stash/releases/tag/latest_develop> or wait for 0.19

**Comment by Written2001** [comment]
Thanks, I'll wait for 0.19 and report back.

**Comment by WithoutPants** [comment]
Closing as completed. Can reopen if the bug still exists in 0.19.
