### ISSUE TITLE
[Feature] Prompt for password before loading page

### ISSUE THREAD

**Issue by Moonlit5950** [stashapp/stash#3317]
**Is your feature request related to a problem? Please describe.**
Stash is great, but still missing an important feature: The Password Prompt to ensure unauthorized parties cannot access its contents.

**Describe the solution you'd like**
Prompt for a password (and username) in the style of the [Apache password prompt ](https://jslim.net/images/posts/2014-05-06-how-to-use-apache-htpasswd/password-prompt.png) before the DOM is sent to the browser. This ensures maximum privacy. Also, change the title of the webpage to something that does not suggest its contents. 

**Describe alternatives you've considered**
A password prompt using JavaScript. It would offer the ability for more styling, but should not suggest what the webpage is for. For example, make it in a style of a login page for a NAS or allow the user to use his own HTML and CSS and JS. 

**Additional context**
I don't want others to accidentally find the server (it has to stay public, so I can access it from other devices in my local network)

**Comment by DogmaDragon** [comment]
This is all it loads when not logged in. All the title say is `Login`. 
![image](https://user-images.githubusercontent.com/103123951/210020342-8d20f5ec-6509-4d07-b0bd-1b0e5e7f45d1.png)

Not sure what here "suggest its contents". 

Here is the loaded code for the page 
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <base href="%BASE_URL%">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Login</title>

    <link rel="stylesheet" href="login/login.css">
    <link rel="stylesheet" href="css">
</head>
<body class="login">

    <div class="dialog">
        <div class="card">
            <form action="login" method="POST">
                <div class="form-group">
                    <label for="username"><h6>Username</h6></label>
                    <input class="text-input form-control" id="username" name="username" type="text" placeholder="Username" />
                </div>
                <div class="form-group">
                    <label for="password"><h6>Password</h6></label>
                    <input class="text-input form-control" id="password" name="password" type="password" placeholder="Password" />
                </div>
                <div class="login-error">
                    
                </div>

                <input type="hidden" name="returnURL" value="/" />

                <div>
                    <input class="btn btn-primary" type="submit" value="Login">
                </div>
            </form>
        </div>
    </div>

</body>
</html>
```

**Comment by Moonlit5950** [comment]
The Favicon does not seem to change (tested on Firefox)

**Comment by hydrian** [comment]
Plain text is fine as long as you use HTTPS which should be used everywhere with the HTTP protocol. Especially since much of this content is very personal in nature.

**Comment by hydrian** [comment]
Also, who in there right mind would expose a stash installation to the public internet?  So much liability in doing that. I only see this as an internal service. If you want external access, use a VPN. Or maybe an authenticating web reverse proxy.

**Comment by stg-annon** [comment]
> Also, who in there right mind would expose a stash installation to the public internet? So much liability in doing that. I only see this as an internal service. If you want external access, use a VPN. Or maybe an authenticating web reverse proxy.

quite a few people actually, we had an issue with it in the past and built safeguards to protect such cases, lookup `security_tripwire_accessed_from_public_internet` in discord or the repo, convince is the enemy of security
