### ISSUE TITLE
[Feature] Remember position in the player

### ISSUE THREAD

**Issue by JediMaster25** [stashapp/stash#3337]
A setting to enable remembering the position in the player. So that when a scene is opened again it starts where it was last time.

**Comment by QxxxGit** [comment]
I have this functionality. Check your interface settings, under the `Scene Player` section. Make sure `Always start video from beginning` is off

**Comment by DogmaDragon** [comment]
This was added in v0.18 https://github.com/stashapp/stash/pull/3055
