### ISSUE TITLE
[Bug Report] Performer Card on Mobile Gallery

### ISSUE THREAD

**Issue by alucicrazy** [stashapp/stash#3365]
**Describe the bug**
The performer card stays behind the gallery images cards

**To Reproduce**
1. Create a Gallery with at least 2 performers
2. On a mobile device view that gallery
3. See error

**Expected behavior**
The performer card should stay at the top of the page.

**Screenshots**
![Screen Shot 2023-01-18 at 02 34 36](https://user-images.githubusercontent.com/122958864/213093052-70086736-b92a-4ae7-aca3-bad138b7568c.png)
![Screen Shot 2023-01-18 at 02 33 36](https://user-images.githubusercontent.com/122958864/213093073-37ad5154-01f3-45f8-a1be-a44d3f091ee9.png)

**Stash Version: (from Settings -> About):**
v0.18.0

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Browser: Firefox
 - Version: 108.0.2

**Smartphone (please complete the following information):**
 - Device: Galaxy S20
 - OS: Android 11
 - Browser: Firefox
 - Version: 108.2.0

**Comment by WithoutPants** [comment]
Unable to reproduce this on the latest dev version.

**Comment by WithoutPants** [comment]
I was unable to reproduce this in 0.18 either. Closing as stale.
