### ISSUE TITLE
[Feature] Configurable number of results per page by default

### ISSUE THREAD

**Issue by milkmandoor** [stashapp/stash#3375]
Is it currently possible to configure the server to serve an arbitrary number of results per page (instead of the harcoded value of 40 results) everywhere ? I haven't found anything about this in the documentation or in the readme.

**Comment by teogolang** [comment]
I would love to do that as well

**Comment by DogmaDragon** [comment]
![image](https://github.com/stashapp/stash/assets/103123951/91f8e5c7-a668-4b69-b3a4-73005c5cad5c)
And set as default. 

If you use GraphQL API then you can use `perPage: -1` for all or any random number.

**Comment by teogolang** [comment]
> ![image](https://user-images.githubusercontent.com/103123951/251846892-91f8e5c7-a668-4b69-b3a4-73005c5cad5c.png) And set as default.
> 
> If you use GraphQL API then you can use `perPage: -1` for all or any random number.

I love you

**Comment by DogmaDragon** [comment]
@HijackHornet could you create a new issue for it? It's not specific to per page results. It's more broad. Inside objects for Movies and Galleries don't have an option to set a default filter.
