### ISSUE TITLE
[Bug Report] Display gallery size

### ISSUE THREAD

**Issue by Plwwwww** [stashapp/stash#3386]
**Describe the bug**
i used to see gallery size next to number of images in a gallery 
but after i updated to v0.18.0 from v0.16.2 gallery size not showing anymore i don't know if its was removed in v0.18.0 or its a bug

**To Reproduce**
1. Go to any gallery
2. And look here
https://imgur.com/a/e2ej4E8

**Comment by DogmaDragon** [comment]
Can confirm the regression, 

On https://github.com/stashapp/stash/commit/8e222ae387c57c2e14b22d223f3a7d879e60599f
![image](https://user-images.githubusercontent.com/103123951/220344778-1c226ed5-4a75-4a33-818a-d360dbf9bbee.png)
On https://github.com/stashapp/stash/commit/e9fa7d071e3587d393cedca735874214e06ff9d9 ![image](https://user-images.githubusercontent.com/103123951/220345112-0cfceac1-2861-48f4-b239-854a0fb3b2f0.png)
