### ISSUE TITLE
Improved Play Counter (i.e. modify the scene's 'Last_Played Date' variable to store multiple plays rather than only the most recent)

### ISSUE THREAD

**Issue by randemgame** [stashapp/stash#3392]
While I really appreciate the work towards the Play Counter https://github.com/stashapp/stash/issues/633 that was developed here https://github.com/stashapp/stash/pull/3055, it is still missing some essential functionality that is available in other, far less developed organisers, and it's an issue that has prevented me from switching to Stash for several years now. I had already mentioned these issues in comments lost to those closed/merged issues, and I could not find any other related discussion on the topic here, so I'm finally writing up this request as best I can, as three very interconnected issues. 

**1: The Play Counter should be recording the multiple DATE's a scene is viewed**

The current implementation of the Play Counter does not seem to keep track of anything more than the singular date that a scene was last played. Adjusting this to record the multiple views of a video would allow for a _more accurate record of the user's historical play data_. This sort of functionality is especially valuable as more and more personal view history is gathered over the years, providing a cool timeline of information for the user, e.g. to see how their interests have developed over time or just to reminisce over what video was played on Valentine's Day a decade ago. All this info currently seems to be lost when a scene is re-watched and then just jumps to being the last played entry, removing any historical date information. I can think of two options for implementing this:

a) Ideally this history would be displayed when browsing Scenes in the order of 'Last Played At'. However, I realise that this would then require the same videos to be displayed multiple times in the view, which might be a problem to implement?

b) A separate, dedicated 'view history' part of the interface. This is the approach taken by Porn-Vault, but is entirely separate from the rest of the Scenes interface.

I would hope that this enhanced view history could then be one of the options to see on the Stash front page, but really more than anything I just need this multiple date history to be recorded in the database.

**2: The DATE of Plays should be visible to the user alongside the functionality to add/remove/edit the dates**

This was something requested in the original issue that has not yet been implemented: "On the Edit tab, the functionality to decrease or reset the count (of plays)". The ability to remove dates would have a use case if the user accidentally plays a scene or otherwise has a change of mind on what level of activity they want to track. The real need I see for this function is to _manually add dates when viewing scenes outside of Stash_. While I appreciate Stash is accessible on almost every device, there are still many instances where users may be viewing videos from their library outside of the interface and still want to keep track of the play data. I currently change the system clock in order to accurately record what time and date these views happened outside of other organisers, so the option to _freely edit the dates_ would be a great quality of life improvement.

With the ability to add, remove or edit the dates, I am really advocating more _manual control of the play data_, which I prefer over Stash's automated implementation. I think the 'Minimum Play Percent' method of tracking plays is useful, and could be used in combination with manual tracking, but I would still like an option to disable it whilst still 'Tracking Activity'. I'm sure there are a number of other users who prefer to take control of things manually.

**3: This multiple DATE information should be accessible via a plugin or scraper so that play data can be imported from other organisers**

I would really need that with any implementation of this functionality, that the multiple DATE data attached to a scene would be accessible in a way that I could import my historical view data. This is the last important piece of data keeping me tied to the other organisers, and I'm sure there are others in a similar situation. I have already simplified the data I have in the PGV4 database (which recorded both the date a scene was watched, and the date their equivalent 'O-counter' was used) into a JSON, importing the view history alone into Porn-Vault (which does not record O's), which is enough data for my needs. The lack of any date info on the O-Counter in Stash had been preventing me using the program, but I think it would be fine to remain a simple integer as long as the view data was being additionally recorded somewhere. 

I can no longer ignore how advanced and impressive Stash is, especially since gaining access to Stash-DB, and would _really_ like to switch to the software and hopefully contribute to the community. Please help myself and others escape the trappings of proprietary or abandoned organisers, by implementing this missing functionality and providing a way to rescue my data one last time.

**Comment by Stephan972** [comment]
@RandomName250  What other organisers are you using (or did you use) ?

**Comment by RandomName250** [comment]
> @RandomName250 What other organisers are you using (or did you use) ?

As mentioned above, Porn-Vault and PGV4

**Comment by Teda1** [comment]
I haven't spent much time in that code since the work got merged. At the moment, my plate is full with personal work and some other Stash work I've been investigating. I can try to circle back to this later.
