### ISSUE TITLE
[Bug Report] Scraper ThePornDB returns error message when pressing "Scrape All" or using "Search" function

### ISSUE THREAD

**Issue by leocordis27** [stashapp/stash#3394]
**Describe the bug**
Scraper ThePornDB returns error message when pressing "Scrape All" or using "Search" function

**To Reproduce**
I followed the scraping guidelines from https://guidelines.stashdb.org/docs/guide-to-scraping/ and managed to get the .yml files to my directory and add it to Stash scrapers.
But when I press the "Scrape All" and "Search" function with the new ThePornDB scraper, it returns the following error

ERROR
Get "https://api.metadataapi.net/scenes?parse=hustler-holly-michaels-in-boobzilla-4": dial tcp: lookup api.metadataapi.net on 103.94.168.168:53: no such host

**Expected behavior**
ThePornDB scraper will return the scenes just like using the Stashdb scrapers.

**Screenshots**
![image](https://user-images.githubusercontent.com/111774381/216755174-27fb2926-543b-489b-aa01-67e31c0de8d9.png)

**Stash Version: v0.18.0:**

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Brave
 - Version 1.47.186

**Additional context**
I run stash through Synology Docker. The StashDB scraper works fine.

**Comment by WithoutPants** [comment]
Is this still an issue? It sounds like it might be an external host issue.

**Comment by TwentySeven28** [comment]
> Is this still an issue? It sounds like it might be an external host issue.

I can confirm this is still occurring. The previous URL (https://metadataapi.net/movies) has changed. The plugin needs to be updated to point to the new URL (https://theporndb.net/). Can we modify the built in plugin ourselves?

**Comment by Maista6969** [comment]
> > Is this still an issue? It sounds like it might be an external host issue.
> 
> I can confirm this is still occurring. The previous URL (https://metadataapi.net/movies) has changed. The plugin needs to be updated to point to the new URL (https://theporndb.net/). Can we modify the built in plugin ourselves?

If you mean the old ThePornDB scraper it's been deprecated in favor of [using them as a stash-box endpoint](https://docs.stashapp.cc/beginner-guides/guide-to-scraping/#use-theporndb-endpoint). This endpoint will not serve their movies or JAV though, so for that we have separate scrapers in the Community feed (installable through the web interface in `Settings > Metadata Providers` in v0.24 and later)

Note that after installing these alternative movie/JAV scrapers you will still need to edit the scraper files on disk to add your own API keys since they do not have access to your stash-box configurations 🙂

**Comment by TwentySeven28** [comment]
> > > Is this still an issue? It sounds like it might be an external host issue.
> > 
> > 
> > I can confirm this is still occurring. The previous URL (https://metadataapi.net/movies) has changed. The plugin needs to be updated to point to the new URL (https://theporndb.net/). Can we modify the built in plugin ourselves?
> 
> If you mean the old ThePornDB scraper it's been deprecated in favor of [using them as a stash-box endpoint](https://docs.stashapp.cc/beginner-guides/guide-to-scraping/#use-theporndb-endpoint). This endpoint will not serve their movies or JAV though, so for that we have separate scrapers in the Community feed (installable through the web interface in `Settings > Metadata Providers` in v0.24 and later)
> 
> Note that after installing these alternative movie/JAV scrapers you will still need to edit the scraper files on disk to add your own API keys since they do not have access to your stash-box configurations 🙂

Thanks! So we should no longer use "ThePornDB" scraper? It remains an option in the UI when on the scene edit page, but it appears it cannot be removed.

**Comment by Maista6969** [comment]
> > > > Is this still an issue? It sounds like it might be an external host issue.
> > > 
> > > 
> > > I can confirm this is still occurring. The previous URL (https://metadataapi.net/movies) has changed. The plugin needs to be updated to point to the new URL (https://theporndb.net/). Can we modify the built in plugin ourselves?
> > 
> > 
> > If you mean the old ThePornDB scraper it's been deprecated in favor of [using them as a stash-box endpoint](https://docs.stashapp.cc/beginner-guides/guide-to-scraping/#use-theporndb-endpoint). This endpoint will not serve their movies or JAV though, so for that we have separate scrapers in the Community feed (installable through the web interface in `Settings > Metadata Providers` in v0.24 and later)
> > Note that after installing these alternative movie/JAV scrapers you will still need to edit the scraper files on disk to add your own API keys since they do not have access to your stash-box configurations 🙂
> 
> Thanks! So we should no longer use "ThePornDB" scraper? It remains an option in the UI when on the scene edit page, but it appears it cannot be removed.

Yes, any scrapers you had on disk from before v0.24 will need to be manually removed from your scrapers directory 🙂

![image1](https://github.com/stashapp/stash/assets/131594657/9a0c5995-e772-41b3-aa30-c59ddaff560b)
![image2](https://github.com/stashapp/stash/assets/131594657/c0d43ac8-c753-49f0-a405-8e69859ddb13)

If you look at the list of scrapers in the dropdown, the top ones are your configured stash-boxes: these can be configured or deleted at the top of `Settings > Metadata Providers`. The rest of the scrapers are whatever Stash has found in your scrapers directory on your harddrive and would need to be removed from there if you installed them manually.

**Comment by TwentySeven28** [comment]
Thank! For some reason I have ThePornDB as a scraper despite it not being configured in the Metadata Providers section. I haven't configured it manually either. It's no biggie though. I'll just remember not to use it.

![Screenshot 2024-04-21 at 14 51 10](https://github.com/stashapp/stash/assets/72940366/83387b3f-2b8e-4711-a36c-61b4932b5f72)
![Screenshot 2024-04-21 at 14 50 53](https://github.com/stashapp/stash/assets/72940366/5ba07661-c438-4a48-a598-cc05924bb608)
