### ISSUE TITLE
[Bug Report] Error when scraping from Brazzers

### ISSUE THREAD

**Issue by Volitude** [stashapp/stash#3395]
**Describe the bug**
When scraping a scene using the brazzers scraper you get the error shown. I've tried multiple different scenes, all the same error. It was working fine a week ago or so.

**To Reproduce**
1. Have a Brazzers scene 
2. Scrape using Brazzers .yml
3. See error

**Expected behavior**
The scrapper fetches metadata and populates fields.

**Screenshots**
![brazz 1](https://user-images.githubusercontent.com/16909174/216756760-1191b6e0-da4e-4dae-ba60-572f0baaa0f4.png)
![brazz 2](https://user-images.githubusercontent.com/16909174/216756875-7a02afef-8ef0-4fc0-9375-ec3042bb5dde.png)

**Stash Version: (from Settings -> About):** 0.18.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 22H2

**Comment by DogmaDragon** [comment]
Scraper issues are better served on https://github.com/stashapp/CommunityScrapers/issues/123. 

Try using https://github.com/stashapp/CommunityScrapers/pull/1240 (requires Python).
