### ISSUE TITLE
Add a task for auto assigning performers

### ISSUE THREAD

**Issue by iwiwdt** [stashapp/stash#34]
It would be very useful if it were possible to scan the files and if there is a performer full name in the file path, like in the file name or some directory further up, then the performer is very likely in the file.

**Comment by StashAppDev** [comment]
I actually had something like this in the old version which I never did commit.  Mine was a bit different though in that it would iterate through each performer and look for the performer name or aliases in the details, title, or path.  If it found a match then it would prompt the user if they'd like to attach that performer to that scene.

I do think this is a good idea, I just need to think through the implementation details.

**Comment by WithoutPants** [comment]
@Leopere can this be closed?

**Comment by Leopere** [comment]
Looks like it can be.
