### ISSUE TITLE
Custom Performer Fields

### ISSUE THREAD

**Issue by ovladuk** [stashapp/stash#3401]
is there a way to add custom fields to a performer page? like for social media usernames or other stuff. 

i saw something before about css i think? if someone know how to add fields with some code i would be greatfull!

**Comment by DogmaDragon** [comment]
Dupe of https://github.com/stashapp/stash/issues/885.

**Comment by Teda1** [comment]
Beat me to it. I'll go ahead and close this issue.

**Comment by ovladuk** [comment]
> Beat me to it. I'll go ahead and close this issue.

there's nothing in the other thread that really answers it though... what css code can i use to add more fields?

**Comment by DogmaDragon** [comment]
> > Beat me to it. I'll go ahead and close this issue.
> 
> there's nothing in the other thread that really answers it though... what css code can i use to add more fields?

CSS can't create new fields.
