### ISSUE TITLE
[RFC] Anonymous Metrics tracking with Matomo Transparency is Key

### ISSUE THREAD

**Issue by Leopere** [stashapp/stash#341]
My goal here is to see if we have any pain points in the app but also track usage if allowable by our following/userbase.  We would use Matomo[FormerlyPiwik] to track conversions from the sooner or later to be deployed `StashApp/website` to having an installed copy running somewhere.   Ideally, we would just want a ping from the app telling the Matomo metrics tracker the user's ephemeral anonymized fingerprint that we were successfully installed somewhere and then go back to no more tracking.  Then maybe if the user wants to help out they can manually turn on further metrics.

##  Long Form

Ideally, it would be nice since nobody wants to be published on the internet for being affiliated with this entire industry; we want to potentially know conversions from hitting the website getting the instructions to having a copy installed locally.  

However, in a perfect world when we manage to get things worked out to a point where everything is relatively stable we should have crash metrics potentially reported to a [Sentry](https://sentry.io/features/) install and also more page to page [Matomo](https://matomo.org/) metrics.  We will have to discuss what it would look like to reach a point of transparency and anonymity that would make our user base content long term with what we're doing.  I for one believe that this would be excellent to help us determine pain points in playback issues and User eXperience problems to help us develop the best app possible.

## Examples

![image](https://user-images.githubusercontent.com/1068374/73598921-dd6bae80-450b-11ea-87ac-e8853b973bb9.png)
Pictured above is a screenshot of tracking data affiliated with an anonymized fingerprint of an individual bouncing around on a project using the tracking methods suggested within this issue.  It has a fingerprint which is a short hash string that is associated with this user's session data.  This session data shows the user's browser, screen resolution, best guess device type stated to be an `Apple iPhone (1x)`, country of origin based on GeoIP data set matching showing `Frankfurt am Main, Germany` as the origin of the requests.  A goal was reached as the user found the installation instructions in their timeline during this visit.  

Other text shown in this screenshot includes the following verbatim:
```
Summary
Spent a total of 56s on the website, and viewed 5 pages in 1 visits.

Converted 1 Goals (1 Get started).

Each page took on average 0.151s to load for this visitor.

First visit
Saturday, February 1, 2020 - 0 days ago

from GitHub

Devices
1 visits from Smartphone devices: Apple iPhone (1x)

Location
1 visit from Frankfurt am Main, Germany Germany (show map)
```
The aforementioned was the content in the left pane of the screenshot of the Tracking Data and the right pane of the tracking data shows verbatim as follows:
```
Visit #1Saturday, February 1, 2020 15:07:06
 16 actions in 56s
3ohmyform.com/OhMyForm | OhMyForm is the best open source form solution for the web
/



ohmyform.com/Quick Start Installation of OhMyForm | OhMyForm
/docs/install/

Get started
ohmyform.com/Quick Start Installation of OhMyForm | OhMyForm
/docs/install/

There are no more visits for this visitor.
```

## Reference Reading

[Matomo Anonymize IP blocks](https://matomo.org/docs/privacy/#step-1-automatically-anonymize-visitor-ips)
[Matomo Privacy Settings](https://matomo.org/docs/privacy/)
[Sentry Sensitive Data Scrubber Documentation](https://docs.sentry.io/data-management/sensitive-data/)

**Comment by Leopere** [comment]
My preference is to call home as soon as possible to let us know before the user's fingerprint changes that they've managed to install the software after hitting the main websites which include the installation instructions.  Once the conversion is made I don't really think that we need to keep tracking.

However, there could be made an argument for User eXperience improvements and pain point reporting wherein we track crash analytics to help us learn where the application is failing to work correctly and on what platforms.  This level of analytics should absolutely be considered to be something that we ask permission for.

If we wish to be ultra-transparent we can potentially publish datasets upon request as is and then if there is specific data that might seem too private we can nuke all of our tracking data history from the database.

**Comment by Leopere** [comment]
This data will be collected exclusively under the pretense that all of the data gathered will not be sold given or shared with anyone other than direct project maintainers for the sole purpose of the betterment of the app itself.  Anyone caught selling said data would then be barred from accessing it.

The overall mantra here should be `don't be evil` since Google dropped the ball on that tagline we will pick it up here.

**Comment by Leopere** [comment]
Finally, I believe personally that this information is deeply sensitive despite our best possible efforts to anonymize this data it may be possible to de-anonymize the data and in the case of a data leak we may be best to approach this assuming that knowledge leaked from the contents of this metrics collection could lead to immediate threat to the safety of our individuals and should establish very public guidelines for responsible disclosure to our people.  Also establishing the fact that this entire dataset is 100% non-transferrable in its entirety for any reason.  If the project is acquired by anyone ever the data will need to be destroyed to the best of our abilities.

**Comment by WithoutPants** [comment]
I personally believe that given the sensitive nature of this app, and potential risk of abuse of this data, that the justification for implementing this must be detailed and necessary. You've outlined the _how_ in pretty extensive detail, but to my mind there is nothing sufficient about the _why_.

Seeing "if we have any pain points in the app but also track usage" is nowhere near enough justification for adding in any form of tracking, especially given that those metrics are likely going to be less useful to us than user reports on discord and Github issues.

Implementing something like this will require a non-trivial amount of effort to insure that it is done in a way that not only minimises any privacy risk, but also assures the userbase at large that their privacy is being respected. Once it is implemented, we then have the additional overhead of managing the server-side data, not only to protect it, but to also be transparent enough about it that it doesn't alienate the userbase. To me, these represent unacceptable risks, and I can't imagine the information we'd get from this that would justify such risks.

I don't consider myself especially privacy-conscious and this has me apprehensive. I think there would be plenty of users more paranoid (for lack of better descriptor) that would be very upset about the inclusion of such a thing.

**Comment by Leopere** [comment]
## Focusing on why:

Privacy by design, if we're recording our user's data we will be more likely to design features that respect user's privacy including log data which omits anything problematic.

Designed towards consent, in the discord conversation I diverged from this somewhat focusing on tracking metrics by default however I think that my mind has been changed on the matter.  I think that we should require that the user manually send a ping to the tracking system through a button press on the first load including acknowledgments of any TOS and EULAs we might be required by ethics or law to have our users agree to.

Tracking granularity could be added wherein it's just simple page to page usage or increasingly invasive crash analytics also ideally designed with the concept of privacy-first in mind.

We should potentially add these functions as an externally auditable library that is imported and easy to omit in builds in case someone wishes to build this entirely without tracking they could.  However, over time analytics of usage does effectively help design a better appliance for people in the end.

Finally, #342 can technically lower the steps required between a bug and a fix and potentially could even be offered to the user when a crash or failure in the functionality is detected within the code.  The feature proposal outlined in #342 is designed such that when the bug ages the log data decays and eventually is destroyed by the upstream provider.

One other thing we could do is potentially have a 4 party Warrant Canary.

**Comment by bnkai** [comment]
I never realy liked TOS or EULAS (for an app not a service). Every time i need to tick / check one i think something is fishy.
I think we need to keep things simple for the app at least so that we don't need that.
I can understand sending some details / info for bug fixing or debugging but i also am not fond of tracking.
Again all this is IMHO and for the app specific, for the API/site  part it would probably be more useful.
We could for example sent the version/os or anything else needed for statistics through the  scraper plugin when the user scrapes for data using the API ( provided ofcourse that the user is informed and agrees with  it)

**Comment by Leopere** [comment]
Well, I'm not thrilled about the idea of a TOS/EULA as they typically are so much as at least offering up a disclaimer.

Tracking wise it's non-personal and never going to collect without consent.  We can go the route of hosting a Sentry appliance somewhere for more bug related tracking but we should consider something.  I am definitely still open to suggestions.

The other thing we can also consider is changing how tracking is reported in releases versus dev versions.  Please also focus on my statements about focusing on tracking only for the purpose of increasing the quality of user interaction with the appliance itself and to know what is and isn't working.  We should make it very open that we will be destroying the data and making a public announcement if things change.

**Comment by Leopere** [comment]
https://developer.matomo.org/guides/tracking-api-clients pointing people at the libraries and sections of the code to build from the source entirely without tracking would also be possible and encouraged.

**Comment by Leopere** [comment]
One final thing that we should do is produce a report of API's that the default app will call home to.  Including any of our own.  This way if the app behaves differently from expected then it can be considered compromised in some way or another.  In fact, we should consider offering [little snitch rules](https://help.obdev.at/littlesnitch/intro-rule-groups) or [ufw profiles](https://askubuntu.com/a/488647) for the various OS's.

**Comment by kermieisinthehouse** [comment]
> One final thing that we should do is produce a report of API's that the default app will call home to. Including any of our own. This way if the app behaves differently from expected then it can be considered compromised in some way or another.

The front-end does this now through content security policy, but we should probably have a documentation page of every url we might touch by running Stash. A new scraper format if we ever change them should declare their URLs, too.

Closing this issue as the utility:controversy ratio is way off here, for an open source adult app, so chances of implementation are very low.
