### ISSUE TITLE
[Bug Report] Performers are not matched by alias when scraping / identifying

### ISSUE THREAD

**Issue by puc9** [stashapp/stash#3423]
**Describe the bug**
When scraping manually or running identify if a performer name is returned that matches an alias but not a performer then a new performer is created 

**To Reproduce**
Any scraping but especially from LP since they use a lot of names that are aliased in stashbox.

**Expected behavior**
A match should be done by performer name and if not found then by performer alias.
Clarifying what should happen when finding multiple matches is technically outside the scope of this bug but a few ideas:
- pick the first match
- add all matches and also a tag (BTW we need a separate set of tags like system tags or library management tags) so that the scene can be manually fixed afterwards. Organized should not be set in this scenario

**Stash Version: (from Settings -> About):**
Latest develop built locally

**Additional context**
I have tried to fix this myself but for the life of me I can't figure out where that matching happens. If someone knows and can point me to the code I can attempt a fix.

**Comment by gaytomi** [comment]
This seems like a big issue - what's the point of aliases if they don't tag to videos?

**Comment by Flashy78** [comment]
Scene tagger can now look for exact alias matching with #4182
