### ISSUE TITLE
[Bug Report] Create Tag overlay in scene editor has an error

### ISSUE THREAD

**Issue by SpedNSFW** [stashapp/stash#3427]
**Describe the bug**
Within a scene's edit interface, the option for creating a tag has an error in its overlay. This error comes from the backend in Go's `strconv` package.

**To Reproduce**
1. Go to any scene
2. Go to the edit tab
3. Within the tags, type something random (that doesn't exist as a tag)
4. Hover over the "Create tag" option and see the error.

**Expected behavior**
I'm not actually sure what should be displayed in the overlay, but it most certainly shouldn't be an error from the backend.

**Screenshots**
![image](https://user-images.githubusercontent.com/68614336/218310292-ed7714e4-e758-4b8c-bd20-5bdbbc12f304.png)

**Stash Version: (from Settings -> About):** v0.5.0-985-gd80ec1d7

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi
 - Version: 5.6.2867.62 (Stable channel) (64-bit)

**Comment by SpedNSFW** [comment]
It appears the backend is expecting an integer to be matched to a tag, so it can display that as the overlay. This makes sense for normal tags, but not for creating a new tag.

![image](https://user-images.githubusercontent.com/68614336/218310400-d0280619-fe80-4e0a-a145-7c0b3ff89971.png)

**Comment by DogmaDragon** [comment]
Reproduced on 7761ac19.
