### ISSUE TITLE
Not showing any scenes 

### ISSUE THREAD

**Issue by bobsutton124** [stashapp/stash#3430]
Whenever I scan my library, it only adds the images of the videos and galleries. The statistics shows 0 scenes even though I have lots of videos in each of my directories. I have added a metadata provider from stashdb and a scraper from ThePornDb. Also, I turned on the "Generate perceptual hashes" option. 
Can anyone please guide me on how to add the videos?

**Comment by DogmaDragon** [comment]
First, go to Settings > Logs and see if there are any errors. Run the scan task and check what the log says. 

Also check:
1. Go to Settings > Library and make sure the checkbox for Videos is checked. 
2. Go to Settings > Library and make sure the video extensions used for your files are listed under Video Extensions.

**Comment by bobsutton124** [comment]
Thanks for the suggestions. 
After I restarted the Stash app and did a re scan without changing any settings, it started to find the videos. It is still in the process of scanning the terabytes of videos and hopefully it will be able to identify them all.
