### ISSUE TITLE
Auto Save Scraped Scenes

### ISSUE THREAD

**Issue by bobsutton124** [stashapp/stash#3432]
Is there a way to auto save all the scenes that were scraped? There are many scenes and I would like them all to save without going one by one.

**Comment by DogmaDragon** [comment]
[Identify task](https://docs.stashapp.cc/in-app-manual/tasks/identify/) is the only way to automatically save the scraped metadata. 

There is a 3rd party userscript that lets you [save in bulk using Tagger](https://docs.stashapp.cc/add-ons/userscripts/#stash-batch-save). 

Also, these questions are better suited for [GitHub discussions](https://github.com/stashapp/stash/discussions).

**Comment by bobsutton124** [comment]
awesome thank you
