### ISSUE TITLE
[Bug Report] Deleting a file through Stash doesn't remove it from the database

### ISSUE THREAD

**Issue by SpedNSFW** [stashapp/stash#3437]
**Describe the bug**
When you delete a scene _and_ its matching file through Stash, only the scene is removed from the database. The file remains, and that causes issues with the duplicate checker, as both files still have rows in the `files_fingerprints` table (where I presume the duplicate checker is getting its information).

**To Reproduce**
1. Having two scenes with matching phashes
2. Within one of those scenes, click on the hamburger menu and select "Delete scene"
3. Within the modal, ensure "Delete file" is checked, and then delete.
4. The remaining scene will still show with the "Duplicated (phash)" filter enabled.

**Expected behavior**
Either the file and associated rows within `files_fingerprints` should be removed upon the file's deletion, or the file should have a `deleted_at` column which should get populated at the time of its deletion. The latter is a soft delete, though I don't know why we'd need it, it's an option. Soft deleted files can be excluded from the duplicate checker.

**Screenshots**
![image](https://user-images.githubusercontent.com/68614336/218749477-4b8247d3-be38-4d8d-9de9-5a22002cd211.png)

The file with id `143847` no longer exists.

**Stash Version: (from Settings -> About):** v0.5.0-1004-g8bd5f91e

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi
 - Version: 5.6.2867.62 (Stable channel) (64-bit)

**Comment by SpedNSFW** [comment]
I'm unsure if this should be submitted as a different report, but the duplicated phash filter also shouldn't match when all the files belong to a single scene.

**Comment by hphpanon** [comment]
@SpedNSFW You sure that Stash version is right? If it is, you're running a very old version. 0.19 just came out a couple days ago, for reference.

**Comment by SpedNSFW** [comment]
@hphpanon I think you misunderstand. I build my own Stash and that's the version string you get. That last part indicates it was built from commit 8bd5f91e. This is the same commit that 0.19 at.

**Comment by DingDongSoLong4** [comment]
The version is calculated with `git describe --tags`, which bases the number off of the latest tag on the branch.
@SpedNSFW If you fetch tags (which I'm fairly sure is the default) then the number will be more correct.

**Comment by WithoutPants** [comment]
I'm not able to reproduce this on the latest dev branch. When the delete file option is checked, then the applicable rows are deleted from `files` and `files_fingerprints` tables. 

Is the file present in the `files` table? Are you able to post the schema of your `files_fingerprints` table? If the file is removed from the `files` table it should be cascade deleting from the `files_fingerprints` table.

**Comment by SpedNSFW** [comment]
Huh, you're right. I must have deleted the scene file causing me issues before this got fixed. I thought I deleted it in the version I have listed in the issue but I guess not.

I'll have to fix the errant rows directly in the database.
