### ISSUE TITLE
[Feature] Serve custom pages

### ISSUE THREAD

**Issue by QxxxGit** [stashapp/stash#3443]
I think it would be really nice for plugins, userscripts, etc. to have a way to serve a custom page. For example, I'm wanting to create a userscript for a masonry grid view. At the moment I'm having to write a ton of boilerplate to adjust an existing page.

I recognize that this is a lot easier said than done, and there's tons of ways to go about this; but I think for now a single blank page (blank as in no body content, just has the Stash navigation bar) would be beneficial. i.e. `localhost:9999/customPage`

**Comment by stg-annon** [comment]
I believe there currently is a way to do this via the config file, its just not very well documented. I'll have to look into it again

**Comment by puc9** [comment]
`custom_served_folders`
in here: https://docs.stashapp.cc/advanced-tutorials/advanced-configuration-options/

**Comment by QxxxGit** [comment]
Apologies for the late response.

I'm aware of the custom served folders, but my request is different. I'm talking about the Stash UI having a template page that only includes the existing CSS and navigation, and that page would import/embed our custom page based on the address.

So for example in `config.yml` there could be a `custom_pages` array with key-value pairs to link the address to a page we want to serve.

```yaml
custom_pages:
    /mypage: /some/path/mypage.html
```

then when you visit `localhost:9999/mypage` it serves that page in the body of the existing UI underneath the navigation bar within `<div class="main container-fluid">`

**Comment by QxxxGit** [comment]
Closing as this is addressed in #4256:

`* supports registering page routes via PluginApi.register.route. (eg PluginApi.register.route("/plugin/test-react", TestPage);)`
