### ISSUE TITLE
Big performance dip for users with larger databases when tagging since the v0.19.0 release

### ISSUE THREAD

**Issue by Teda1** [stashapp/stash#3446]
**Describe the bug**
It's unclear what all was changed in the latest release, which is contributing to the poor performance I've been seeing. Before this update, despite my large database (https://discord.com/channels/559159668438728723/1032337264757448796/1072347283145904208), Tagging scenes was still reasonably fast. It would lag occasionally, but I could tag 60 scenes per page without many issues. Since this update, Stash will start to freeze after 2 or 3 scenes have been scrapped. Running an identify task in the background now makes browsing Stash a very sluggish experience. Playing videos or viewing galleries is no longer possible while the task is running. Before now, I have never experienced any issues when running the identify task. The only task that could impact performance before now was the Scan/Generate task which makes sense since that task would use all my CPU power during the generating process. Some investigation is needed to identify the root cause of this issue.

**Stash Version: v0.19.0

**Desktop (please complete the following information):**
 - OS: Linux (Unraid)
 - Version v0.19.0

**Comment by cloudstrife112** [comment]
same problem already here for weeks. when i want to tag a scene, it stays loading for 3/5 sec/ on the performers. I think because I see a loading on the performers tab.

**Comment by Teda1** [comment]
Resolved by https://github.com/stashapp/stash/pull/3452
