### ISSUE TITLE
[Bug Report] Unicode smileys crash ffmpeg/ffprobe

### ISSUE THREAD

**Issue by nginYthough** [stashapp/stash#3449]
**Describe the bug**
During the generation-task ffmpeg and ffprobe are not able to interact with files that have unicode-names, like p.e. emojis.

**To Reproduce**
1. Set up Stash in Docker (on Windows 10 WSL2)
2. Create library containing unicode-emojis in folder-/file-names
3. Start "Generate"-task (previews, scene scrubber sprites, marker previews, perceptual hashes)

**Expected behavior**
ffmpeg and ffprobe work normally and generate the requested files.

**Screenshots**
<img width="607" alt="Screenshot 2023-02-17 154719" src="https://user-images.githubusercontent.com/97574316/219707378-7b58a5ab-878b-4c4a-aa77-e3e85fa479c5.png">

**Stash Version: (from Settings -> About):** v0.19.0 (Docker, Windows 10 WSL2)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Any

**Additional context**
Might have to with WSL2 locales? Have not tested on Linux host yet.

**Comment by WithoutPants** [comment]
I am unable to reproduce this on bare metal versions on Windows and Linux. This appears to be something specific to your docker/WSL2 setup, and I doubt that there's anything I can do in the code to fix this.
