### ISSUE TITLE
[Feature] Studio Tagger with Image Support

### ISSUE THREAD

**Issue by Flashy78** [stashapp/stash#3460]
Currently in the scene tagger, if you create a new studio, it does not include the image from Stashbox, or the parent studio.
On the Studios page, there is no Tagger view like there is for Scenes and Performers.

I am currently working towards the following features:

**Scene Tagger - Create Studio Modal**
- [x] The image from Stashbox should be displayed and saved on studio create, as well as the parent studio information.
- [x] A checkbox that defaults to checked, allows the option of also creating the parent studio if the parent studio does not already exist
- [x] If the parent studio matches an existing studio by name, instead the option will be to add the Stash ID and update the image/data

**Studio Tagger**
This is a new view which has the exact same feature set as the current Performer Tagger.
- [x] Provide a tagger view with a search box populated with the studio name or Stash ID
- [x] On an exact match, pop up the tagger create studio modal from above
- [x] Batch Add Studio button with exact name matching required
   - [x] Add option to also create parent studio
- [x] Batch Update Studios button with the same functionality as the batch performer update
   - [x] Add option to also create/update parent studio

**Comment by timo95** [comment]
Also see #2626

**Comment by puc9** [comment]
Until this is implemented you could use the `Stash Studio Image And Parent On Create` plugin from https://github.com/7dJx1qP/stash-userscripts

The downside is that it needs a userscript to work.
(not affiliated with the repo in any way, I'm just a user)
