### ISSUE TITLE
[Documentation] Update demo video

### ISSUE THREAD

**Issue by WithoutPants** [stashapp/stash#347]
The video in the [README](https://github.com/stashapp/stash/blob/develop/README.md) is from the old rails version. We should create a new one that covers the same functionality as the old one, plus any relevant new functionality. We'll want a censored and uncensored version. Probably need some input from @StashAppDev for how he did that last time, and he'll also have to upload it to the stashappdev vimeo account.

**Comment by Leopere** [comment]
I would also like to add an installation video for console installs similar to the asciinema recording for [ohmyform.com](http://ohmyform.com/docs/install/)
![image](https://ohmyform.com/docs/kick-ascii/cast/dev-env-install.png) that links to [this playback](https://ohmyform.com/docs/kick-ascii/?cast=dev-env-install)

**Comment by WithoutPants** [comment]
New video was made by @Belleyy. If we want a separate installation video, we can raise a new issue for it.
