### ISSUE TITLE
[Bug Report] Handling large images crashes the server

### ISSUE THREAD

**Issue by Ksrx01** [stashapp/stash#3471]
**Describe the bug**
Scanning for new images in the 80-140MP range _without creating thumbnails in the process_,
causes the server to crash when these are later viewed in the Images or Gallery views.
The higher the image size the easier it's to trigger this bug and the less images are loaded before a crash occurs.
This doesn't seem to happen with smaller images.

**To Reproduce**

1. Place new images in the 80 to 140MP range (best if over 100MP) in your library directory
2. Perform a scan, _without the create thumbnails options_*, to add them
3. Open/filter a view (images/galleries) to display the newly added images
5. After a moment the frontend becomes unresponsive, the server has crashed

(_If thumbnails for those images were create at some point, no crash will occur_)

Frontend message when clicking on any thumbnail:
```
TypeError: error loading dynamically imported module
Lazy t@https://stash.local/assets/index.cfbc3cfa.js:114:6930 t@https://stash.local/assets/index.cfbc3cfa.js:114:8887 Suspense U4@https://stash.local/assets/index.cfbc3cfa.js:2572:5212 div cae@https://stash.local/assets/index.cfbc3cfa.js:2574:2317 Qoe@https://stash.local/assets/index.cfbc3cfa.js:2572:10463 CH@https://stash.local/assets/index.cfbc3cfa.js:153:46773 Suspense kH@https://stash.local/assets/index.cfbc3cfa.js:153:45317 soe@https://stash.local/assets/index.cfbc3cfa.js:2567:43972 t@https://stash.local/assets/index.cfbc3cfa.js:149:3813 U4@https://stash.local/assets/index.cfbc3cfa.js:2572:5212 gme@https://stash.local/assets/index.cfbc3cfa.js:2615:18469 UF@https://stash.local/assets/index.cfbc3cfa.js:85:2516 t@https://stash.local/assets/index.cfbc3cfa.js:114:3677 t@https://stash.local/assets/index.cfbc3cfa.js:114:9961
```
Last server log entries:
```
2023-02-22T12:32:29.739331045Z [31mERRO[0m[2023-02-22 12:32:29] image encoder error when running command </usr/bin/vips thumbnail_source [descriptor=0] .jpg[Q=70,strip] 640 --size down>:  
2023-02-22T12:32:29.739608694Z [31mERRO[0m[2023-02-22 12:32:29] error generating thumbnail for /library/folder/image.jpg: signal: killed 
2023-02-22T12:32:29.739649328Z [31mERRO[0m[2023-02-22 12:32:29] stderr:
```

**Expected behavior**
Images should load as usual.

**Stash Version: (from Settings -> About):**
0.19, 0.19.1 (probably earlier versions too)

**Additional context**
Since this crash doesn't occur during the scan process, I assume a simple memory related issue due to a large image is unlikely.
Maybe the scan generates thumbnails sequentially, while viewing galleries spawns several workers, which then causes memory issues?
~~As this appears to be a memory related issue, first thing that comes to mind are images being loaded entirely before being down scaled. I might be wrong, but IIRC there should be ways of passing image decoders a frame size, thus allocating much less memory and getting an image that's already of the required size.~~

**EDIT**: Added more, newly discovered context.

**Comment by ALonelyJuicebox** [comment]
Hmm...I grabbed a 80MP image of the sun from [here](https://www.esa.int/ESA_Multimedia/Images/2022/03/The_Sun_in_high_resolution) as well as a 150MP image of some rocks from  [here](https://www.imaging-resource.com/PRODS/phase-one-xf-100mp/Y-JG-IQ4-150MP-2488.HTM) and was not able to replicate this either in the image view nor in the gallery view. Works with no issue for me running Stash 0.18 via Chrome on Windows on a modern CPU with 32 GB of RAM. 

What specs did you experience this with?

Testing aside, are images that are _this_ big in scope for this project? You can shoot a 61MP image with a Sony A7R IV without a lens for $3,500. When you step up to medium format you're looking at $10,000-$50,000 cameras sans lenses. Are there really adult studios who are taking such high quality images of their performers? Are there customers who want photos with that much pixel density or should this be considered fairly edge case stuff?

Agreed that images could be scaled down in realtime but with images this big... the realtime experience really wouldn't be great while the user waits for the converted version. 

![bigsun](https://user-images.githubusercontent.com/76471868/221365099-a8ca5d46-3dd6-4fe6-9d98-802245e03e30.png)
![bigrock](https://user-images.githubusercontent.com/76471868/221365828-c6be54bd-7bb6-482d-b346-7f40931b1352.png)

**Comment by MrX292** [comment]
did a test and with all the images from [here](https://www.imaging-resource.com/PRODS/phase-one-xf-100mp/phase-one-xf-100mpGALLERY.HTM) using the original i am not able to reproduce this on windows.

can you maybe check the container resource usage while you are testing it.

or could a specific image be the one that crashes it?

**Comment by DingDongSoLong4** [comment]
The logs show that stash is using `vips` - could you try maybe removing/renaming  `/usr/bin/vips` to prevent stash using it? Does the crash still occur?

I can't reproduce it on mac with a bunch of images from [here](https://commons.wikimedia.org/wiki/Category:Large_images). Looking at it through htop I can see that stash spawns at most 6 vips processes on that system, with each one using peak 100M-200M of RAM, and stash itself with a peak memory usage of 1.5G. The process count is related to core count, so your Xeon will likely mean that stash spawns a lot more. Would you be able to use something like htop to look at RAM usage/processes when the crash occurs?

From what I can tell stash buffers the entire image into memory before running `vips`. Your likely high core count again probably means that the total memory usage will be rather high. I admit to not knowing too much about containers and that kind of thing, but is it possible that the container is being killed for memory usage despite the 90GB total RAM? Does the crash still occur when running stash outside of the container?
