### ISSUE TITLE
[Bug Report] The buttons in Performers Edit page incorrect location

### ISSUE THREAD

**Issue by aka-nsfw** [stashapp/stash#3472]
Hi team,

I found a minor bug for UI in Performers Edit page

![image](https://user-images.githubusercontent.com/93849402/220686803-baeda47e-06d5-426f-a2dc-8542a4b1912f.png)

Source code:
https://github.com/stashapp/stash/blob/2d528733ffd89e5adce6feba4085c41a116e0119/ui/v2.5/src/components/Performers/PerformerDetails/PerformerEditPanel.tsx#L1035-L1036

**Comment by DogmaDragon** [comment]
Can't reproduce on https://github.com/stashapp/stash/commit/e9fa7d071e3587d393cedca735874214e06ff9d9.

**Comment by DogmaDragon** [comment]
I see what you mean. 

As a side effect, it allows you to target the top and bottom one individually if you want to use custom CSS. 

Still can't reproduce both div being placed near each other as in the screenshot.

**Comment by DingDongSoLong4** [comment]
> ![image](https://user-images.githubusercontent.com/93849402/220948111-89f49c76-2154-44d5-9456-0f91b4649d7b.png)

In the styles pane on the right it looks like custom CSS is being used, does the issue persist when you disable that in settings? By its very nature I don't think custom CSS causing issues can really be considered a bug.

**Comment by DingDongSoLong4** [comment]
Oh I found the issue, you're using [this](https://docs.stashapp.cc/user-interface-ui/custom-css-snippets/#move-the-buttons-in-the-performers-edit-panel-to-the-top-instead-of-bottom) CSS snippet, which moves the edit buttons to the top. This snippet is no longer needed as the buttons are now already both at the top and bottom by default.
The problem should be fixed if you go into your custom CSS settings and remove the relevant lines.

**Comment by aka-nsfw** [comment]
> Oh I found the issue, you're using [this](https://docs.stashapp.cc/user-interface-ui/custom-css-snippets/#move-the-buttons-in-the-performers-edit-panel-to-the-top-instead-of-bottom) CSS snippet, which moves the edit buttons to the top. This snippet is no longer needed as the buttons are now already both at the top and bottom by default. The problem should be fixed if you go into your custom CSS settings and remove the relevant lines.

I got it. After removing custom CSS, the problem is gone.
Thank you for your help.
