### ISSUE TITLE
[Feature] Dealing with video orientation problem (en masse)

### ISSUE THREAD

**Issue by SomeRandomDreamer** [stashapp/stash#3479]
**Is your feature request related to a problem? Please describe.**
Some times I get vertical videos that's oriented horizontally. Every time I watch them, I have to use the filter to rotate them 90 degrees. I also have a very large number of them.

**Describe the solution you'd like**
One of it is the ability to save filters, as described here https://github.com/stashapp/stash/issues/1335 . However, I'm creating this issue for a more holistic solution as there maybe a large number of them, and there may be a need for a solution at the tile/list screen to mass rotate/reorient?

It's not a difficult problem, so I don't think I really need to provide concise solution, but let me know if otherwise.

**Comment by Flashy78** [comment]
Are you wanting Stash to run ffmpeg rotate on all of your videos and replace the files with rotated files?
https://www.baeldung.com/linux/ffmpeg-rotate-video

**Comment by SomeRandomDreamer** [comment]
@Flashy78 that can work too.
