### ISSUE TITLE
[Bug Report] Performer Tagger breaks with duplicate endpoints

### ISSUE THREAD

**Issue by Flashy78** [stashapp/stash#3483]
**Describe the bug**
If you have two accounts on the same Stash-box, their names and apikeys will be different, but their endpoints will match.
The performer tagger code is only looking at the endpoint value, which causes issues.

Minor bug probably not encountered by anyone.

**Comment by WithoutPants** [comment]
Can you please detail the specific problems that occur when in this scenario? "causes issues" isn't very useful.

It's not intended for stash to have multiple accounts to the same stash-box instance, but we can probably clean things up a little.

**Comment by Flashy78** [comment]
Apologies, this was initially to keep track for myself to go back and look at once I was done with the studio tagger.

The problem is that React will complain about multiple items in the stash-box instance select with the same key.
It then sets the endpoint in `ITaggerConfig` without tracking which stashbox index it was from. Later on in the tagger code it goes to match the `selectedEndpoint` with the index in `stashConfig?.general.stashBoxes`, and it always just matches the first one.

I had initially hoped I could just make the select list key unique, but fixing it would actually probably require changing `ITaggerConfig` to handle a stashbox object instead of just the `selectedEndpoint`, and all the related code around that. So I think it's probably best to just close this and continue with not supporting multiple accounts on the same stash-box.
