### ISSUE TITLE
[Bug Report] can not place a image in tags

### ISSUE THREAD

**Issue by TB-M** [stashapp/stash#3489]
**Describe the bug**
I can not place any image in tags, the save-button is disabled

**To Reproduce**
try to place a image in tags
<img width="637" alt="Screenshot 2023-02-26 at 01-23-46 White Man Tags Stash" src="https://user-images.githubusercontent.com/87576875/221385922-c43a680d-76a8-4d57-b21d-916abd5bdafc.png">

**Screenshots**
https://i.imgur.com/ROawrrQ.png

**Stash Version: 0.19.1

**Desktop (please complete the following information):**
 - OS: Win
 - Browser Firefox
 - Version 110.0 (64-Bit)

**Comment by DogmaDragon** [comment]
Reproduced on <https://github.com/stashapp/stash/commit/e9fa7d071e3587d393cedca735874214e06ff9d9>.

Tested with a local image, image from the URL, and Ctrl+V.

**Comment by MrX292** [comment]
seams to work if you change one of the other fields before saving

**Comment by TB-M** [comment]
> seams to work if you change one of the other fields before saving

confirm
