### ISSUE TITLE
Custom scene cover

### ISSUE THREAD

**Issue by StashAppDev** [stashapp/stash#35]
As discussed in discord:

> maybe 20% by default, but having the option in the UI to upload an image as well. what ive been doing is pulling the "cover art" image from  the torrent tracker site, and using that. useually is a image that came from a paysite gallery for the scene thats been perfectly croped and had sites logo added or somthing of the kind. looks better imho than just scrolling though random screenshots ( plus they tend to all look the same about 20% in on the same catagory of scene)

It would be nice to use a custom cover for a scene (like the official site image).  Right now Stash generates screenshot files at 20% into the video.  For this change this would act as a default, but we would also expand the scene model.  There would need to be a new BLOB cover image property in the database.  Stash should use this image if it exists, otherwise fall back to the screenshot.

**Comment by echo6ix** [comment]
I look forward to this feature. Also consider generating a custom scene cover/thumbnail from the a user defined time during the scene. Similar to how a marker is currently generated.

**Comment by rexii2300** [comment]
yep this would be fantastic!

**Comment by WithoutPants** [comment]
> I look forward to this feature. Also consider generating a custom scene cover/thumbnail from the a user defined time during the scene. Similar to how a marker is currently generated.

This is covered by #9 

> It would be nice to use a custom cover for a scene (like the official site image). Right now Stash generates screenshot files at 20% into the video. For this change this would act as a default, but we would also expand the scene model. There would need to be a new BLOB cover image property in the database. Stash should use this image if it exists, otherwise fall back to the screenshot.

Is there any reason we can't just replace the existing screenshot file with the submitted one? I'm not sure why we need to store a separate image in the database unless we're using the thumbnail image for something else.

**Comment by ueaslsef** [comment]
@Leopere this seems done, should we close it?

**Comment by bnkai** [comment]
should be closed when #376 is merged

**Comment by bnkai** [comment]
closing since #376 was merged
