### ISSUE TITLE
[RFC] Default Identify to skip items with multiple results

### ISSUE THREAD

**Issue by Flashy78** [stashapp/stash#3506]
The common refrain when people are told to use Identify is that it can have incorrect matches.
I suggest adding an option to Identify to skip items with multiple matches coming back, and defaulting this option to on.

It would log that multiple results were returned and so the item was not matched.
The user could also choose a tag to attach to these items so that they can be easily found later.

This wouldn't eliminate incorrect matches, but might stop many of them? Especially helpful with all of the short form content that doesn't work very well with phash and returns lots of matches. At the detriment that users may end up with many scenes not matched.

**Comment by bta820** [comment]
I think this is a good idea but it fails to address the bigger problem which is the mismatches themselves.  as long as there isnt a functional way to report/remove mismtached phashes then this is a stopgap at best.  ive got hundreds on scenes on my stash that are matched to one scene on stashdb thats wrong.  ive got none matched to two that are wrong.

**Comment by Flashy78** [comment]
That's a different problem. While this would help users apply a bandaid for that, it would also solve the different problem of re-releases with the same phashes which are both valid on StashDB where Identify will just randomly pick one and assign it. Or if someone submitted an incorrect phash to another scene, Identify will just pick one at random to match to.

Yes there is a problem of incorrect hashes on StashDB, but that's an issue for StashDB to deal with, not Stash.

**Comment by stg-annon** [comment]
I think a better solution might be to allow the user to define what is considered a "Match" for the task for example

	10 fingerprints by duration +/- 5 seconds
	5 by phash with distance < 2
	I also think standardization of the incorrect fingerprints from the spreadsheet would be of use here
	
A configuration option like this would allow for a user to confidently run an Identify task to get a bulk of scenes tagged without worry of mismatches leaving scenes that would otherwise need more scrutiny and would be more valuable in terms of fingerprint submissions in the first place

**Comment by Flashy78** [comment]
> I think a better solution might be to allow the user to define what is considered a "Match" for the task for example
> 
> ```
> 10 fingerprints by duration +/- 5 seconds
> 5 by phash with distance < 2
> I also think standardization of the incorrect fingerprints from the spreadsheet would be of use here
> ```
> 
> A configuration option like this would allow for a user to confidently run an Identify task to get a bulk of scenes tagged without worry of mismatches leaving scenes that would otherwise need more scrutiny and would be more valuable in terms of fingerprint submissions in the first place

I think that type of development could help with false matches, but it doesn't eliminate them, and requires the user to know how to tune their query.
I'm suggesting just a simple to implement option of not tagging when there is not an exact match.
