### ISSUE TITLE
[RFC] Add an extra "fast" hash/checksum for the scenes. Make MD5 scene calculation optional.

### ISSUE THREAD

**Issue by bnkai** [stashapp/stash#351]
Currently the checksum we use for metadata filenames, duplicate file detection is MD5. 
While it is well established / tested it has a main disadvantage like all checksums, we need to read the whole file to calculate it. 
I personally don't have any problem waiting for the scan and like the ability to verify the integrity of my collection that MD5 gives , but it was mentioned on discord that a lot people ( especially with remote hosted collections , gdrive etc...) want/need something faster.

##  Proposal

I propose we add the ability to generate an extra  hash that is easy to calculate, doesn't read the whole file and hopefully doesn't have any collisions. 
My main recommendation and the hash i tested is oshash.
This can be added as an extra to the scenes table and calculated by default since it's generation time is negligible. Users who want to could opt to use this as their main  instead of MD5.

## Points to Consider

- MD5 is now required as the `checksum` in scenes. If we add a `hash` we could make the `hash` required and MD5 checksum optional (as mentioned the time needed for the proposed oshash generation is negligible ) or even make the existence of 'hash' OR 'checksum' required.

- Checksum and hash should cooperate nicely. 
A user must be able to opt in / out without the need to rename files , all existing metadata should work without changes. 
One potential way to solve this is checking first for existence using the checksum (if it exists) first and then with the hash. Thankfully MD5 has a fixed length of 32 chars while oshash 16 so they don't clash if we use them for the filename. The drawback is that there will be mixed filenames (some 16 chars, some 32) for those that choose to opt out of MD5 and already have some metadata.

- Oshash is already used by opensubtitles and seems to be collision free for media files ( tested for my 12k scenes and also reported so from  discord)

- Oshash needs a minimum file size of 64kb to be calculated. Anything less will not be.
I don't think i have come across a video that small , even sample that i use in my media collections but i suppose we could fallback to MD5 if we want to on rare cases.

- Oshash is mainly tested against media files. It reads 64k from the end and start of the file.I don't know if it will work well with the galleries. Further investigation will be needed if we choose to implement that ( priority should be given to scenes given the limited use/size of a gallery compared to a scene )

## Benchmarks

Oshash reads in total 128kb from a file so it's very fast.
Tests were done in linux using md5sum and the go util i have in reference
The media files were located localy in a spinning hdd. 
The main bottleneck for md5 was the disk read speed. 
Oshash was run before MD5 to make sure caching wasn't favoring oshash.
I used a folder containing 127 files (51Gb in total)

```
time oshash *.*

real	0m5.476s
user	0m0.171s
sys	0m0.081s

time md5sum *.*

real	6m57.624s
user	2m27.387s
sys	0m22.549s
```

To give a perspective of the speedup:
During scanning of a new file we calculate the checksum, generate a screenshot, a thumbnail and interact with the database.
The time needed for an average scene (size ~1gb)

```
checksum (md5sum) 5.8s (depends on disk read, file size, file fragmentation)
ffmpeg screenshot 0.2s
ffmpeg thumbnail 0.2s

hash (oshash) 0.06s 

```

Time to oshash my whole stashed collection  (12k scenes ~ 3.8TB) using a batch script to get the paths from stash database  ~ 7 minutes

## Reference
[oshash](https://trac.opensubtitles.org/projects/opensubtitles/wiki/HashSourceCodes) The official page from opensubtitles
[oshash.go](https://gist.github.com/bnkai/a09e75f163932bb91996a75d4dddc9f3) A md5sum like cmd line implementation of oshash i made from the above

**Comment by Leopere** [comment]
oshash sounds like the best route for a fast hash.  I still insist that we should eventually focus on an eventual goal of having something that's fuzzy and capable of cross transcode recog eventually.

I'm 100% behind this decision of having oshash included.  I kind of feel oshash technically trumps md5 and could have a possibility to supersede md5 all around.
