### ISSUE TITLE
[Feature] Date picker UI for all Date fields

### ISSUE THREAD

**Issue by ALonelyJuicebox** [stashapp/stash#3512]
**Challenge** 
The current UI experience of having to manually enter the date into a Stash text field with no user feedback as to if the date is being entered properly nor any assistance in doing so isn't great.

![stashcurrentdate](https://user-images.githubusercontent.com/76471868/223393685-f5a3f3f6-5da0-4910-9da7-aaa5ba716660.png)

**Proposed Solution**
I propose we consider implementing a basic date picker and adding it to all date fields, including date entry on the Edit page of various objects (Scenes, Performers, Images) but also for Date selection with regards to Filters.

No backend code manipulation here, just something to help users select the Date they want on the client side. 

I am not biased towards building something out or just integrating something that exists already, but as an example here's one solution called Pikaday. It's both open source and available on GitHub
![pikadayy](https://user-images.githubusercontent.com/76471868/223394278-bb6e54b4-9043-4ff9-b93c-6107fcdc046f.png)

Demo page for what I'm talking about https://pikaday.com

**Comment by DogmaDragon** [comment]
I can see it being useful to a few people maybe, but it can easily be more annoying when it randomly selects a wrong date if you just start typing it manually or not actually letting you only enter a partial date.

**Comment by ALonelyJuicebox** [comment]
I think you misunderstand-- this isn't to replace the existing form, it's to enhance it.
I'd genuinely invite you to try the demo page I linked in the initial post. You can enter a text date just fine. You can also enter a partial date and it won't override anything. 

We can also customize it to follow along with the `YYYY-MM-DD` format we use in Stash.

What it DOES add is significant improvement over the simple text form and significantly more use friendly UX in line with any other platform that asks users to input a calendar date.

**Comment by DingDongSoLong4** [comment]
Since #3509 the date field is now properly validated and will give an error message for an invalid date. I do agree that a picker would be a nicer interface though, as long as the text input method still works.

**Comment by DogmaDragon** [comment]
> I think you misunderstand...this isn't to replace the existing form, it's to enhance it. I'd genuinely invite you to try the demo page I linked in the initial post. You can enter a text date just fine _and_ you can also enter a partial date and it won't override anything.

I was aware you weren't trying to replace it, I just don't think it improves it more than it creates more annoyance. 

Tried it. While it doesn't have the most common problem of the scroll wheel changing the date, it still uses arrow keys for navigation which is possible to misclick and get the wrong date. 

If you want to manually adjust the date it just deletes the whole section with backspace instead of just removing a single symbol. This leads to you having to scroll through the years month by month until your reach the year and month that fits your date or just typing the full date yourself like now.

**Comment by ALonelyJuicebox** [comment]
> I was aware you weren't trying to replace it, I just don't think it improves it more than it creates more annoyance.

Without running an actual poll I don't have the data to say this concretely for Stash's audience, but using other web based platforms as a reference, I'd argue that for the _average_ user, folks would prefer to use a UI over text entry.

One more thing--
Stash uses a date format of `YYYY-MM-DD`. For some crazy reason, the US uses the `MM-DD-YYYY` format, and many other countries use `DD-MM-YYYY`. If anything this UX would help facilitate less confusing date entry with accommodation for a myriad of date formats.

> Tried it. While it doesn't have the most common problem of the scroll wheel changing the date, it still uses arrow keys for navigation which is possible to misclick and get the wrong date.

I appreciate you giving it a shot. Two points here.
With a cursory look at the code it's trivial to remove arrow key navigation from this script.

As I mentioned, we don't have to go with this script in particular, this is just an example of what I'm looking for that's very close. Usually I have to rely on images in a GitHub issue to demonstrate the solution I'm looking for-- in this instance there's an actual bit of usable code with a functional demonstration. 

> If you want to manually adjust the date it just deletes the whole section with backspace instead of just removing a single symbol. This leads to you having to scroll through the years month by month until your reach the year and month that fits your date or just typing the full date yourself like now.

Like the arrow key navigation concern, this appears to be very easy to address by just removing `setdefaultvalue`

**Comment by DogmaDragon** [comment]
> Without running an actual poll I don't have the data to say this concretely for Stash's audience, but using other web based platforms as a reference, I'd argue that for the _average_ user, folks would prefer to use a UI over text entry.

Probably, but I would question how many people enter dates manually at all. With stash-box integration and a variety of community scrapers available, the whole problem Stash tries to solve is manual metadata ingestion. 

> One more thing-- Stash uses a date format of `YYYY-MM-DD`. For some crazy reason, the US uses the `MM-DD-YYYY` format, and many other countries use `DD-MM-YYYY`. If anything this UX would help facilitate less confusing date entry with accommodation for a myriad of date formats.

Again I would say scrapers solve this issue for the most part and the format is shown on the placeholder text on the input field. 

P.S. I like the dig at US stupidity just to be unique even if it doesn't make any sense. 

> > Tried it. While it doesn't have the most common problem of the scroll wheel changing the date, it still uses arrow keys for navigation which is possible to misclick and get the wrong date.
> 
> I appreciate you giving it a shot. Two points here. With a cursory look at the code it's trivial to remove arrow key navigation from this script.
> 
> As I mentioned, we don't have to go with this script in particular, this is just an example of what I'm looking for that's very close. Usually I have to rely on images in a GitHub issue to demonstrate the solution I'm looking for-- in this instance there's an actual bit of usable code with a functional demonstration.
> 
> > If you want to manually adjust the date it just deletes the whole section with backspace instead of just removing a single symbol. This leads to you having to scroll through the years month by month until your reach the year and month that fits your date or just typing the full date yourself like now.
> 
> Like the arrow key navigation concern, this appears to be very easy to address by just removing `setdefaultvalue`

That would address most of my concerns from a usability standpoint.

Thank you for taking the time to talk this out and come up with solutions.

**Comment by LeGrosFromage** [comment]
So my thoughts on some of the points raised:
I do enter dates.  For me, "date" is second only to "title".  Performers next then details.  Tags are a brutal last.  I consider date to be extremely important.  Not all scenes are scrapable, by any means, and I've had to do some real voodoo to get dates for some of the scenes I have - some are over 20 years old.

The age of some of my scenes also speaks to another point that was mentioned - having a date picker is fine, if it's a _recent_ scene.  If I'm trying to pick a date from, say, 2013, do I need to click back through every month until I get to 2013?  Please no.  Keep a manual entry available, or at least have a drop-down for years (and probably month, too).

As for formats, how about a "user region" option in Settings where you set the locale you're in, then the date formats accordingly - just like the OS's do?

**Comment by ALonelyJuicebox** [comment]
Really appreciate everyone's feedback on this so far, thank you! 🙂

> > Without running an actual poll I don't have the data to say this concretely for Stash's audience, but using other web based platforms as a reference, I'd argue that for the _average_ user, folks would prefer to use a UI over text entry.
> 
> Probably, but I would question how many people enter dates manually at all. With stash-box integration and a variety of community scrapers available, the whole problem Stash tries to solve is manual metadata ingestion.

You raise an good point here-- I totally forgot to mention this use case, I'll edit the issue.

I agree that your average user may not likely perform Date entry on the Edit page of a scene. 
But to your point with your average user being a consumer of data, another use case where this feature would make a lot of sense is for the Date fields when defining a filter. 

![datefilter](https://user-images.githubusercontent.com/76471868/223779711-2f99d6ac-988f-4daf-8f96-c3946c3792a0.png)

> > One more thing-- Stash uses a date format of `YYYY-MM-DD`. For some crazy reason, the US uses the `MM-DD-YYYY` format, and many other countries use `DD-MM-YYYY`. If anything this UX would help facilitate less confusing date entry with accommodation for a myriad of date formats.
> 
> Again I would say scrapers solve this issue for the most part and the format is shown on the placeholder text on the input field.
> 
> P.S. I like the dig at US stupidity just to be unique even if it doesn't make any sense.
> 
Yeah, as an American...MM-DD-YYYY truly is an awful format. 
It's up there with our wacky desire to measure things outside of metric units

> That would address most of my concerns from a usability standpoint.
> Thank you for taking the time to talk this out and come up with solutions.

Again, appreciate the feedback. 🙏🏿

> The age of some of my scenes also speaks to another point that was mentioned - having a date picker is fine, if it's a _recent_ scene. If I'm trying to pick a date from, say, 2013, do I need to click back through every month until I get to 2013? Please no. Keep a manual entry available, or at least have a drop-down for years (and probably month, too).

I would invite you to try out that demo page as well-- that implementation allows you to enter a date manually, and features a dropdown for both years and months. It sounds like it would align with your request.

> As for formats, how about a "user region" option in Settings where you set the locale you're in, then the date formats accordingly - just like the OS's do?

Not necessarily a bad idea by any means, but in the interest of keeping things on task, perhaps out of scope for this issue?

**Comment by LeGrosFromage** [comment]
> > The age of some of my scenes also speaks to another point that was mentioned - having a date picker is fine, if it's a _recent_ scene. If I'm trying to pick a date from, say, 2013, do I need to click back through every month until I get to 2013? Please no. Keep a manual entry available, or at least have a drop-down for years (and probably month, too).
> 
> I would invite you to try out that demo page as well-- that implementation allows you to enter a date manually, and features a dropdown for both years and months. It sounds like it would align with your request.

Yes, I haven't tried the site, but if those features are available then it sounds like a workable solution to me.

 
> > As for formats, how about a "user region" option in Settings where you set the locale you're in, then the date formats accordingly - just like the OS's do?
> 
> Not necessarily a bad idea by any means, but in the interest of keeping things on task, perhaps out of scope for this issue?

Agreed, it was just a nugget to think about in the overall scheme of things.

**Comment by Stashing-fr** [comment]
Alternatively, is it possible to implement it with custom JS/CSS or plugin ?

**Comment by ALonelyJuicebox** [comment]
> Alternatively, is it possible to implement it with custom JS/CSS or plugin ?

Potentially, but for something that I see as a net positive for an average user I'd like to see it implemented into Stash itself.
As it stands we have a _lot_ of plugins that probably should be integrated into core Stash due to their UX benefit. 

Users shouldn't have to install a plugin to use a date picker when they want to filter between two dates.

**Comment by WithoutPants** [comment]
Agreed. A date picker is pretty basic UX improvement. It shouldn't be _required_ to use a picker, but it is definitely worth adding. I see this as a pretty uncontroversial idea. 

The way I would design it would be to add a button to the date field - similar to the scene URL field - to open the date picker. We _could_ add more features to the manual editing part like highlighting the parts of the date and navigating between the parts with the arrow keys and adjusting the values with the up/down keys, but these are all iterations and improvements on the idea and don't necessarily need to go into the initial implementation. Using this approach should improve workflows where choosing a date from a picker is desirable while not impacting the user experience for those who prefer to enter it manually.
