### ISSUE TITLE
[Feature] Make height and weight fields floats instead of ints

### ISSUE THREAD

**Issue by SpedNSFW** [stashapp/stash#3517]
**Is your feature request related to a problem? Please describe.**
Title should be self-explanatory. Give us access to more precise measurements. Most American performers measure themselves in feet and inches like the silly people they are. They don't convert to centimetres exactly 99% of the time. For example, 6"4' is 193.04cm but since we can only enter 193, this is displayed as 6"3'.

**Describe the solution you'd like**
Change the data types to floats, from integers.

**Additional context**
The height field on stash-box should also be changed to a float.

**Comment by LeGrosFromage** [comment]
Or how about being able to enter feet and inches?

**Comment by SpedNSFW** [comment]
> Or how about being able to enter feet and inches?

To do that, you'd have to have a toggle or make it a string. Both of which impede filtering. Also, why on Earth would you want less accurate measurements?

**Comment by LeGrosFromage** [comment]
How is entering someone's height as 5 feet 10 inches, 5 feet 8 inches, 6 feet 5 inches, less accurate?
You have 2 number-only fields - one for feet, one for inches.  From there, it shouldn't be too hard to filter for a certain height or in a range of heights.

Also, some people (like me) probably don't really care for height measurements - kinda irrelevant for me - so precision isn't really required.

**Comment by DogmaDragon** [comment]
> How is entering someone's height as 5 feet 10 inches, 5 feet 8 inches, 6 feet 5 inches, less accurate? You have 2 number-only fields - one for feet, one for inches. From there, it shouldn't be too hard to filter for a certain height or in a range of heights.

1 cm = 0.3937007874 in
1 in =  2.54 cm

So centimeter is a lot more granular than an inch hence more accurate. 

> They don't convert to centimetres exactly 99% of the time. For example, 6"4' is 193.04cm but since we can only enter 193, this is displayed as 6"3'.

I'm pretty sure it's rounding to the Nearest Integer. 4 is less than 5 and 0 is less than 5, hence 193 instead of 194. And 193.04 is closer to 193 than 194. 

Again centimeter is a lot more granular than an inch hence more accurate.

**Comment by DingDongSoLong4** [comment]
Storing heights as centimeters just makes more sense - splitting them into two fields for feet/inches makes everything more complicated. Storing floats is of course possible, but in my opinion the extra precision is unnecessary.

I think the real bug here is that the conversion from cm to imperial is always rounding down, which should be quite easy to fix.

**Comment by SpedNSFW** [comment]
> Storing floats is of course possible, but in my opinion the extra precision is unnecessary.

I want the extra precision. Changing a datatype in the database just requires a mutation. If you don't want to use floats, you don't have to, but don't say it's unnecessary just because you don't want it.

**Comment by WithoutPants** [comment]
Extra precision _is_ unnecessary. The example you describe in the original description isn't an argument for more precision, it's an argument for entering imperial units (which is a valid request, see #3105 ), and, like DingDongSoLong4 mentioned, converting correctly between systems.

> For example, 6"4' is 193.04cm but since we can only enter 193, this is displayed as 6"3'.

Height does not need to be more precise than centimeters, and converting the data type to be a float introduces further issues related to floating point errors. As an aside, this particular scenario can very easily be worked around by entering `194`.

There _is_ a case to be made for more precision weight values, though I suspect that in a majority of cases it's not necessary. In that case, there wouldn't be much benefit in more precision than a single decimal. A floating point data type would not be the correct approach there either.

I consider #3519 to be the acceptable solution to this issue. If there is a case to be made for more precise weight values, then that can be opened as a separate issue.
