### ISSUE TITLE
[RFC] Does the platform work with performers under 18?

### ISSUE THREAD

**Issue by uyhalim** [stashapp/stash#3518]
Does the platform work with performers under 18? I see that it can automatically guess actor names.

**Comment by WeedLordVegeta420** [comment]
Well, this is certainly a very suspicious question.

**Comment by uyhalim** [comment]
> Well, this is certainly a very suspicious question.

It's hypothetical.

**Comment by WeedLordVegeta420** [comment]
LMAO. OK, bud. I mean, there's nothing that prevents it, but I'm sure you got added to a list just by asking a creepy question like this.

**Comment by uyhalim** [comment]
> There's not currently any built-in AI driven functionality, but I can assure that if/when that does get added and if there's a central repository of training data, there's no way people will be adding illegal underaged performers to that set of AI training data.

You should make it decentralized so anything is possible

**Comment by WeedLordVegeta420** [comment]
OK. I'm done replying here. I should've never engaged with this, but your "hypothetical" is getting creepier and creepier.

**Comment by DogmaDragon** [comment]
Stash is not a platform. It's software for organizing _your own collection_.
