### ISSUE TITLE
[Bug Report] Docker Compiler container won't be up to date before travis builds things. [Edge Case]

### ISSUE THREAD

**Issue by Leopere** [stashapp/stash#352]
**Describe the bug**
This container https://github.com/stashapp/stash/tree/develop/docker/compiler if it ever has to be updated in order for a build to complete we're going to have to manually re-issue a Travis build signal for this commit.  Ideally, the compiler container will rarely need updating however it's not impossible.  This could be remedied by replacing https://github.com/stashapp/stash/blob/f87117b0d6997e1c887f00a00654133c0dbbe8cf/.travis.yml#L23 and its contents of `- docker pull stashapp/compiler:develop` to be a `- docker build` it will increase Travis build time but it will make sure that we never hit this edge case.

**To Reproduce**
1. Push a build that needs an updated Compiler before DockerHub has updated the Compiler container.

**Expected behavior**
Every build is run on the latest code including compiler containers.

**Comment by WithoutPants** [comment]
I'm not convinced that covering this corner case is worth the extra build time from building the docker container every single build.

**Comment by Leopere** [comment]
For the most part, it's just something that should be noted.
