### ISSUE TITLE
[Bug Report] Bulk Update of Performers with goal of having multiple stashbox stashids

### ISSUE THREAD

**Issue by scruffynerf** [stashapp/stash#3547]
**Describe the bug**
If you want to use 2 stashboxs, despite manual scraping against each stashbox working with a performer, bulk scraping doesn't work as expected.  Either it ignores the stashbox it doesn't have an entry for yet (if you have 2 configured stashbox endpoints, but performer only has 1 stashbox stashid), OR it replaces the existing stashbox id with the new stashbox IF you remove one of the endpoints from your config (so it has a stale stashid, no endpoint to match, and no stashid for the current valid endpoint)

**To Reproduce**
Performer tab, Tagger, bulk updates.

If you select "Untagged", if your performers have tags for Stashbox A, but not for Stashbox B, despite B being the current set endpoint in the config, it shows Zero (ie all performers have _a_ tag, from Stashbox A.)  Updates do not work, it won't add Stashbox B stashids to the performers.

if you remove A from your current stash config entirely:
If you select "Untagged", if your performers have tags for Stashbox A, but not for Stashbox B, despite B being the current set endpoint in the config, it shows Zero.  Updates _do_ work, but it removes the stashID from Stashbox A, and replaces it with StashBox B stashid.

**Expected behavior**
Ideally, Untagged should show a count of performers missing an id _from_ the current selected Endpoint (in the config on that page)
Selecting and running Untagged should add Stashbox B stashids (assuming that's selected), and leave Stashbox A ids intact and functional.

**Stash Version: (from Settings -> About):**
v0.19.1-62-ge2b52a4b

**Comment by WithoutPants** [comment]
> Ideally, Untagged should show a count of performers missing an id from the current selected Endpoint (in the config on that page)

This is a feature request and should be made as a separate issue. I'm only scoping this to fix the incorrect behaviour.
