### ISSUE TITLE
[Feature] Custom Filter Order

### ISSUE THREAD

**Issue by yoshnopa** [stashapp/stash#3549]
I like the new UI Filter very much and think it's the right way to go.
However, one problem that isn't solved by this structure is the amount of possible filters that are still presented when you are trying to add a filter.
Although an alphabetical order is a good way for categorically searching a certain way to filter, it falls short in terms of sorting by the actual relevance of a certain filter. 
For example, filtering by a studio, performer or tag is very likely the most prevalent feature presented here, while filtering by checksum is at the very least a very rare occasion. Still, checksum is one of the first options present, while you have to search for the others for a bit.

There are some solutions for that:
- For example, you could customize the order in the settings.
- You could also favorite certain filters, which are then pinned at the top and maybe separated by a small divider.
- You could also hardcode a more convenient order, however I think that is very subjective so I would recommend one of the other two options to provide more flexibility.

I would personally lean towards the second solution. It's probably the easiest to implement, relatively intuitive without making the settings more bloated and still provides an easier way to access the more common filters.

**Comment by DingDongSoLong4** [comment]
I very much agree, and I would also go for the second option. 

Customising the order is possible but will be a lot more difficult to implement and like you said the majority of the time only a handful of the options will be used. I don't think it's really worth it.

Hardcoding a different order is definitely a bad idea in my opinion - trying to find an obscure filter for that one time you need it would be a massive pain if they weren't in alphabetical order.
