### ISSUE TITLE
[Bug Report] Movie creation from Scene Scraper

### ISSUE THREAD

**Issue by SirCumAlot1988** [stashapp/stash#3551]
**Describe the bug**
When developing [this](https://github.com/stashapp/CommunityScrapers/pull/1291) scraper, I came accross the following issues, which are all related to scraping movie scenes (i.e. a single scene of a movie - for instance Scene 2 of the movie Kendra's Obsession from Blacked):

1. If you scrape a scene and then create a movie from the Scene Scrape Results dialog, the message "Could not find movie to remove" appears (see screenshot attached). Nevertheless the movie is created.  This worked properly in Stash v18.0.

2. I tried to implement a scene scraper, which passes all the metadata of the corresponding movie (Duration, Date, Studio Director, URL, Synopsis, Front and Back Cover) to Stash. This is how my JSON would look like (I removed performers, tags and synopsis to simplify it)

`{"title": "Kendras Obsession: Scene 02", "url": "https://straight.aebn.com/straight/movies/218523/kendras-obsession+2", "date": "2017-05-10", "director": "Greg Lansky", "studio": {"name": "Blacked"}, "performers": [ ], "movies": [{"front_image": "<Movie Front Image>", "back_image": "<Movie Back Image>", "name": "Kendras Obsession", "duration": "02:35:47", "date": "2017-05-10", "studio": {"name": "Blacked"}, "director": "Greg Lansky", "url": "https://straight.aebn.com/straight/movies/218523/kendras-obsession+2", "synopsis": ""}], "tags": [], "details": "", "image": "< Scene Thumbnail>"}
`

Now if the movie does not exist and I create it from the Scene Scrape Results dialog the movie is created and contains all that information, but for some reason the Studio as well as front and back cover are missing. I used exactly the same JSON layout for the movie scraper and here everythings works as expected. This would be my JSON for a movie scraper:

`{"front_image": "<Front Image>", "back_image": "<Back Image>", "name": "Kendras Obsession", "duration": "02:35:47", "date": "2017-05-10", "studio": {"name": "Blacked"}, "director": "Greg Lansky", "url": "https://straight.aebn.com/straight/movies/218523/kendras-obsession", "synopsis": ""}
`

Side remark: The studio doesn't work in both cases (Movie and Scene scraper), if it does not exist. So, it is not possible to create a new studio here.

3. As far as I can see it is not possible for a scene scraper to set the Movie Scene Nr, right? Would be nice to have this functionality :-)

**To Reproduce**
1. Choose a movie, which does not yet exist in your library
2. Go to Scenes and select a scene
3. Enter a URL of a site where the scene scraper supports scraping of movies (e.g. adultfilmindex or adultdvdempire)
4. Enter the URL and hit the scrape button
5. In the Scene Scrape Results dialog click on the missing movie to create it
6. For the second bug you need to use my scraper and check the results in the movies section. Note that I have currently disabled the scraping of movie back and front cover for the scene scraper, since it slows down the scraper and doesn't work anyhow. However, you can easily enable it by changing decode_cover in line 399 of AEBN.py to true.

**Expected behavior**
1. The error message should not appear and the movie should disappear from the list of missing movies
2. Studio as well as front and back cover should be passed to the new movie. Studio should also be passed, if it does not exist yet and a new one should be created in this case.
3. An option to set the Movie Scene Nr via the JSON would be awesome

**Screenshots**
![Could not find movie to remove](https://user-images.githubusercontent.com/98083850/225680004-48ebd049-c2cb-4300-ba17-e2682797dbbe.png)

**Stash Version: v0.19.1

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Firefox 
 - Version 110.0.1

**Comment by Lux-Hue** [comment]
I'm having the same issue here as well. Additionally, I would like to add that when running "Scrape All" in the scenes tab, no movies are created at all (no dialog or anything), as opposed to Studios which can be created in that view.

**Comment by Maista6969** [comment]
Part 1 of this was fixed in #3633, part 2 was fixed in #4147

The issue brought up by @Lux-Hue should be a part of unifying the scraping interfaces in "Scrape With..." and Tagger view brought up in #4239 

This can be closed
