### ISSUE TITLE
[Feature] Title from folder name + re-title using folder name

### ISSUE THREAD

**Issue by whateva-009** [stashapp/stash#3554]
**Is your feature request related to a problem? Please describe.**
A lot of my videos are stored in a folder with descriptive name but as simply numbered file within that folder due to the source. This results in tons of videos with same non descriptive title like "01".

**Describe the solution you'd like**
It would be great if there is a way to mass re**TITLE**(not rename) these scenes using their path/foldername + filename
Maybe filename parser could be modifed to filepath parser?

OR

**Describe alternatives you've considered**
Create a bulk movie creater task where it would auto generate movies using folder name as title and numbering in filenames as order of the scenes.

**Additional context**
![image](https://user-images.githubusercontent.com/128103011/225774463-4ffda5ef-b830-4139-8c58-4f0e1b3277bb.png)

**Comment by Phasetime** [comment]
As a workaround Filename Parser can already do what you want: 
![image](https://user-images.githubusercontent.com/87231024/225987605-8bf013a2-a498-491b-a3e6-6c006cb8b25f.png)
As an example for the scene under the path `Z:\AnalVids.Com\[AnalVids] Marley Brinx, Kyaa Chimera - AX003.mp4` it's new title gets mapped to `AnalVids Com\[AnalVids] Marley Brinx, Kyaa Chimera - AX003` with the pattern `Z:\\{title}.{ext}`.
