### ISSUE TITLE
[Bug Report] migrate away from dockerhub?

### ISSUE THREAD

**Issue by a9c05ae0** [stashapp/stash#3558]
**Describe the bug**

[dockerhub plans to remove some accounts](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/) (see also: https://blog.alexellis.io/docker-is-deleting-open-source-images/). Maybe stash's image will be removed from dockerhub, and if it is going to be, it would be wise to host stash container image elsewhere (the most straightforward place would be github's own builtin registry, ghcr.io).

**Comment by stg-annon** [comment]
[Github Packages Reference](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-docker-registry)

[Discord Discussion](https://discord.com/channels/559159668438728723/645283324071247911/1085371791905673228)

**Comment by a9c05ae0** [comment]
> Discord Discussion

I'm sorry but I don't have a discord account, can you post an excerpt or a summary of that discussion?

**Comment by Flashy78** [comment]
Summary was folks were made aware of the issue, the option of migrating to ghcr.io and they will wait and see if things change before spending the time to migrate.

**Comment by Leopere** [comment]
seems like hearsay We will consider a mirror, but I think I’m happy leaving it on DH.

**Comment by DogmaDragon** [comment]
> seems like hearsay We will consider a mirror, but I think I’m happy leaving it on DH.

It was the case, but they sunset the changes after backlash.
