### ISSUE TITLE
[Feature] Generate Tag by Folder/Subfolder

### ISSUE THREAD

**Issue by ravetam** [stashapp/stash#356]
Some of us already has some form of organized folder structure. It would be nice to be able to autogenerate tags based on the folder name. So basically, it would generate a tag for each parent folder the video file is located until the root of the stash folder.

For example

/AV/Tania Swank/Tania.Swank.XXX.1080p.MP4
Should have `AV`, `Tania Swank` Tag 

/VR/Cleo Vixen/Cleo.Vixen.Toys.XXX.VR.1080p.MP4
Should have `VR`, `Cleo Vixen` Tag 

/VR/Cleo Vixen/Cleo.Vixen.Toys.XXX.VR.1080p/Cleo.Vixen.Toys.XXX.VR.1080p.MP4
Should have `VR`, `Cleo Vixen` Tag. `Cleo.Vixen.Toys.XXX.VR.1080p` tag can be excluded since there's only one video in the folder

**Comment by WithoutPants** [comment]
I personally think this is probably niche enough that it belongs in a separate external script, rather than core functionality.

**Comment by Leopere** [comment]
I realize we're headed towards a future with the API but it would be nice if we had a few more efficient on routes for metadata.  It would be fine to mark this as `wontfix` or perhaps a new tag of `maybe someday` and close it unless further feedback is warranted.
