### ISSUE TITLE
[Feature] Select all but biggest duplicate files for deletion

### ISSUE THREAD

**Issue by minicoz** [stashapp/stash#3561]
**Is your feature request related to a problem? Please describe.**
When using the sceneDuplicateChecker tool, it would be fantastic to be able to select all the smallest files within a duplicate group to quickly delete all but the largest video file.

**Describe the solution you'd like**
Have an option to selected all but the biggest video file in each subgroup on the page by scene count.

**Describe alternatives you've considered**
The czkawka duplicate file app has a similar feature but does not have a phash algorithm that stash does.

**Comment by Lamda604** [comment]
I'd like to suggest some nuances to this. With newer codecs, smaller files aren't always lower quality. Higher resolution files with lower bitrate could be better quality than smaller files. Audio bitrate and compression add another dimension to file size. Options to allow match/prefer codec(s) and also compare/prefer resolution and audio bitrate/encoding would make this feature more useful.

(Of course some AI tool that can compare the file image and audio qualities and keep the best copy would be best, but I digress with my pie-in-the-sky dreaming :P )

**Comment by Flashy78** [comment]
This looks to have been fixed by #4006 and can be closed.

**Comment by scruffynerf** [comment]
FYI, my video split screen viewer Userscript was just for such as discussed above where the largest isn't always the best video quality.

**Comment by DogmaDragon** [comment]
Implemented 
![image](https://github.com/stashapp/stash/assets/103123951/f8a581cd-9757-4567-8e7e-16094d24f852)
