### ISSUE TITLE
Default Performer Male and Transgendered Silhouette Images 

### ISSUE THREAD

**Issue by Lamda604** [stashapp/stash#3584]
**Is your feature request related to a problem? Please describe.**
I've always noticed that for female performers there's a variety of cool randomly selected silhouette images when creating a performer (or maybe a female image is always selected default) but be stock images for male and male transgender performers seems to be a bit lacking. I went ahead and grabbed some vector silhouettes from free sites and created some matching some matching images.

**Describe the solution you'd like**
Would someone be able to incorporate these images into Stash App and apply the same random logic for image selection that is available for female performers to the remaining genders?

Thanks
![Male Silhouette 1](https://user-images.githubusercontent.com/81937940/227049374-a6b6775d-dc48-4503-a2a4-4f708d7c3e26.png)
![Male Silhouette 2](https://user-images.githubusercontent.com/81937940/227049376-6cd04c55-01f8-488b-b168-35c9a5e0ff4f.png)
![Male Silhouette 3](https://user-images.githubusercontent.com/81937940/227049378-e945dfa8-255c-4b9c-a6dd-247f56bb7d72.png)
![Male Silhouette 4](https://user-images.githubusercontent.com/81937940/227049380-27b762ab-0595-4285-9650-3b03a2e596df.png)
![Male Silhouette 5](https://user-images.githubusercontent.com/81937940/227049382-9a67ef22-8d8b-4413-99d9-120a81e8497a.png)
![Male Silhouette 6](https://user-images.githubusercontent.com/81937940/227049384-b9c99e85-57ed-4c13-8f15-b4c488315b31.png)

**Comment by WithoutPants** [comment]
Thanks for providing these. Definitely can incorporate them. Can you verify that these are permissable for us to use? Can you provide the URLs to the originals so that we can verify?

**Comment by Lamda604** [comment]
Yes, here are the links and thanks so much!

Male Silhouette 1
https://freesvg.org/1528398040

Male Silhouette 2
https://freesvg.org/male-pose-silhouette

Male Silhouette 3
https://freesvg.org/bald-man-walking-in-a-suit-silhouette-vector-image

Male Silhouette 4
https://freesvg.org/man-silhouette-vector-clip-art

Male Silhouette 5
https://pixabay.com/vectors/man-walking-confident-silhouette-2759950/

Male Silhouette 6
https://freesvg.org/1538857953
