### ISSUE TITLE
Missing tray icon.

### ISSUE THREAD

**Issue by Giger22** [stashapp/stash#3585]
**Describe the bug**
No tray icon on Artix Linux 6.2.6. I have to use task manager to close application.

**To Reproduce**
1. Run stash binary.
2. No tray icon.

**Expected behavior**
Tray icon with option to quit.

**Stash Version: (from Settings -> About):**
v0.19.1

**Desktop (please complete the following information):**
 - OS: Artix Linux 6.2.6, KDE Plasma 5.27.3
 - Browser: Chromium
 - Version: Version 111.0.5563.64 (Official Build, ungoogled-chromium) Artix Linux (64-bit)

**Comment by WithoutPants** [comment]
Is this a regression? I don't remember us adding a tray icon to linux.

**Comment by Giger22** [comment]
I did not know that it was not added on linux. I had used windows version before. Anyway it is tiresome to close app through task manager/htop.

**Comment by MikeLund** [comment]
If I don't misunderstand, I can assume you're new to using Linux? Stash, just like most other applications that don't have a directly connected GUI (headless) don't usually care much/have anything to do with the desktop environment's window manager. I can assume you're starting the the stash-linux binary by clicking on it in your file browser? It'd ideally be your DE/WM's job to ensure some sort of console stays actively shown, and I don't see that as being stash developer's scope to do much about it.

FWIW, there's no tray icon on Windows either, just that it has an icon on the exe file. The only difference is that Windows keeps stash running in cmd.exe, so you can easily close that window, thus terminating the program.

To make it easier for you to kill it, I would recommend you invoke stash via a new terminal (`cd` to the directory, `chmod +x stash-linux` if not already executable, and then `./stash-linux`), then you can more easily kill it if desired by pressing ctrl+C.

**Comment by bnkai** [comment]
@Giger22  From the original PR
>This is not available on Linux because the relevant 
libraries do not support static linking, and we distribute static 
executables- it is otherwise functional when dynamically linked

For more details (https://github.com/stashapp/stash/pull/2073)

**Comment by Giger22** [comment]
I created work around in python.
https://github.com/Giger22/Stash-tray-icon-Linux/blob/main/README.md
