### ISSUE TITLE
[Bug Report] Mobile UI doesn’t load when using authentication (IOS)

### ISSUE THREAD

**Issue by pierre-delecto** [stashapp/stash#361]
As of c99ba68 (and in prior builds), when using a password, the UI doesn't load on iPhone--either via Safari or Chrome.   No authentication input pops up, and no error is shown.  Page just loads as a blank white screen.  Problem persists when requesting "desktop site." Removing authentication allows UI to load.

Tried to inline auth info (using http://username:password@StashIP:Port), no change.

Using HTTP (not HTTPS).  Need to test whether problem persists w/ HTTPs.

iPhone 7, IOS 13.3.1, latest safari/chrome.

**Comment by bnkai** [comment]
On android using the native or chrome browser everything seems fine. (  the auth pop-up is shown when a password is present). So probably something IOS specific.

**Comment by pierre-delecto** [comment]
Incognito/Private gives same results.  Tried with Firefox too, same issue.

Is there a way to access web server logs directly?  Stash log doesn't show anything interesting.  I'm running a docker container if that's relevant.

**Comment by WithoutPants** [comment]
From Discord:

> Infinite03/23/2020
> It's a general safari issue. Safari refuses to prompt for authentication unless the webpage is loaded over https.

**Comment by pierre-delecto** [comment]
Infinite's comment is odd--my issue persists on Firefox and Chrome for IOS.  It also persists when I use HTTPS rather than HTTP.  Maybe there are two separate problems?
