### ISSUE TITLE
[Feature] convert video to X265 to save space

### ISSUE THREAD

**Issue by Eliam077** [stashapp/stash#3614]
hi, 

what about a system to convert and  delete original files  ?

i have a lot of X264, MPG, ... in various resolution.
so i would like to have a system to convert all files in X265 720P by exemple and remove all originals files to save space :)

**Comment by SpedNSFW** [comment]
This should probably be handled by a plugin.

**Comment by Eliam077** [comment]
i'm not able to write this plugin so i hope some do it one day :)

**Comment by DogmaDragon** [comment]
It's not very optimal solution. Re-encoding changes the file hash so it removes one of the parameters that Stash tracks and if you then change the filename, Stash can't track it anymore. 

Using something like Handbrake or just ffmpeg and then importing them to Stash would be the better workflow. 🤷

**Comment by stg-annon** [comment]
existing tools like Tdarr would be good for this but as @DogmaDragon says re-encoding changes the hash which is a core part of Stashes file management as well as goes against one of the core tenants of the software which is that it does not change or alter your files

My personal approach would be to use something like Tdarr to do this and have a plugin act as a middleware that would be able to migrate the "old" scene files to the new ones by either changing the paths of the file in the DB to the new ones so the hash is updated on a new scan or to scan then merge the scenes and promote the new file to the primary file to keep created_at dates and other metadata without needing to re scrape/tag

I don't see this as a feature that will be added to Stash so I'm going to close this issue, feel free to open a similar one in the [CommunityScripts ](https://github.com/stashapp/CommunityScripts) repo someone may be able to assist with a plugin

**Comment by JediMaster25** [comment]
Related to [CommunityScripts/issues/163](https://github.com/stashapp/CommunityScripts/issues/163)
