### ISSUE TITLE
[Bug Report] Scene scraper is favoring null values from scraped data

### ISSUE THREAD

**Issue by hphpanon** [stashapp/stash#3618]
**Describe the bug**
The Scraper UI is auto-selecting null/empty values over the default. I noticed this while running into a scraper that has newly become mostly broken. Basically, the scraper UI is treating null/empty values as though they are preferred, even when a value is already defined.  As best I can tell, these null values do not override existing values, but it's buggy-appearing behavior and seemingly a regression from previous versions of Stash.

**To Reproduce**
1. Load a scene with a URL (either pre-saved or one you can paste into the URL field)
2. Click the scrape button next to the URL
3. See empty values (commonly the Stash ID) be listed with the Scraped "value" 

**Expected behavior**
Values that come back null shouldn't be prioritized over existing values, nor should they be shown when both the original and the scraped value are null.

**Screenshots**

![image](https://user-images.githubusercontent.com/102124543/228696516-87aefd1a-ba7a-40b8-adb7-2aa0cf076121.png)
![image](https://user-images.githubusercontent.com/102124543/228696584-6d1a960f-961d-41e7-b9c0-f6ea4cbf0b38.png)

**Stash Version: (from Settings -> About):**

v0.20.0 (build hash `cb8fc378`)

**Desktop (please complete the following information):**
 - OS: Windows 11 (22621.1485)
 - Edge 111.0.1681.54 and Firefox 111.0.1

**Additional context**
I included the screenshot of the response preview to demonstrate that the `director`, `studio.stored_id`, and `details` values in the response payload were all `null`. ~~I couldn't find anything listed in the changelog for 0.20 that would fit this behavior so it doesn't seem intentional, but maybe I missed it.~~ Looking through the closed PRs and I noticed #3509 (and perhaps just as relevant #3569).

**Comment by hphpanon** [comment]
Also, this appears to affect Performer Scraping, too.
![image](https://user-images.githubusercontent.com/102124543/228699276-bee30419-462a-47a8-b124-1b666e8c35f7.png)

**Comment by DogmaDragon** [comment]
Reproduced on <https://github.com/stashapp/stash/commit/cb8fc3788a3a5268409a7bcd7683904b19a01295>.

**Comment by DingDongSoLong4** [comment]
I will fiercely defend my honour in #3509 and instead bring the loyalty of #3565 into question.

On a serious note though, my one-line change in #3621 reverts it to v0.19.1 behaviour, where scraped fields that are null are simply not shown.

I think only hiding scraped null/empty values if the current value is also null would likely become a bit annoying, especially on performer scrapers where a scraper returns many empty values, but maybe it is something others would find useful.
