### ISSUE TITLE
[Feature] Add support for custom post-processing scripts on new items

### ISSUE THREAD

**Issue by pierre-delecto** [stashapp/stash#362]
I would like to be able to process newly added scenes.  My scenes come in with a defined naming structure, but current solutions do not easily update the scene based on the naming structure.  For example, the scene filename parser works well, but there is no easy way to limit it to new items.  Parsing would preferably happen automatically for new scenes.

I would propose supporting custom scripts to be executed against newly added scenes.  This would allow custom processing, such as adding a data, title, performers, etc.  By passing in a scene_id (and perhaps an auth token for graphQL), most processing could be automated.  This model works well for other projects like nzbget/sabnzbd.

An alternative would be to try to build post-processing directly into stash.  By allowing custom scripts, extensibility is improved.

**Comment by bnkai** [comment]
One way could be by adding system tags and then making the autoparser only work on them.
For example after scanning all scenes should get marked with a system defined tag (e.g. system_new ).
If the scene is manually updated this tag would then be removed. Autoparser could then check scenes with this tag only and remove it after it process them.
That way we could also have a system_locked tag that makes the scenes editable only manually by the user and not by autoparser or say the clean task or the tag/performer/studio auto tagger  or any non-interactive ( automated) action.

**Comment by pierre-delecto** [comment]
I like the idea of allowing the scene file parser work specifically with new files.  Even with that though, adding data would still requires manual intervention (manual scan, manual file parse).  There would preferably be a way to automate parsing when new files are detected.

**Comment by ChaosTherum** [comment]
I could definitely use something along these lines it would make importing youtube-dl files super easy just pull the metadata that youtube-dl saves alongside the file.

**Comment by WithoutPants** [comment]
Resolved by #1452.
