### ISSUE TITLE
[Bug Report] Thumbnails for videos are no longer generating during mass generate/scan tasks

### ISSUE THREAD

**Issue by singularity098** [stashapp/stash#3624]
**Describe the bug**
New content added to the collection after the recent update does not have thumbnails generated when a library scan/generate task is performed.

**To Reproduce**
1. Add new content to collection.
2. Go to Tasks -> Library -> Scan.
3. Check content in the library.  There is no content thumbnail, just a generic placeholder.
4. You can now click on the content and select ... -> Generate default thumbnail, then navigate back and you will see the thumbnail.  But it never generates anymore from the mass scan/generate tasks.

**Expected behavior**
Thumbnails should be generated as they always have been.

**Stash Version: (from Settings -> About):**
v0.20.1

**Desktop (please complete the following information):**
 - OS: Unraid
 - Browser Firefox
 - Version 110.0.1

**Additional context**
I'm sure that this has something to do with the new blob storage that I'm reading about here, but I'm a little bit baffled that this hasn't been written up as a bug already.  I even completely wiped out my docker appdata for this application and started from nothing thinking that this was a problem with blob migration, but the problem still exists.

**Comment by MrX292** [comment]
It is a new option that did not exist in the older version

**Comment by singularity098** [comment]
I see.  Thanks for the info!

Closing issue now...
