### ISSUE TITLE
[Feature] Enable Casting on JW Player

### ISSUE THREAD

**Issue by LinuxGod2020** [stashapp/stash#363]
I would like it if we could enable Casting in JW Player this would allow you to cast video from Stash to Chromecast.

Here is the support article for this feature: https://support.jwplayer.com/articles/how-to-enable-casting-and-airplay

**Comment by Leopere** [comment]
I updated the issue to match a bit closer to the template we provided for feature requests.

**Comment by InfiniteTF** [comment]
For anyone wondering about this, casting is already enabled in JWPlayer. However, casting in Chrome only works on https websites, this is a Chrome limitation and nothing we can change. To enable https for your stash instance, please follow the instructions here: https://github.com/stashapp/stash#ssl-https

**Comment by doctorevil252525** [comment]
@InfiniteTF I have SSL enabled (you can see the padlock icon in the URL bar) but still don't see the chromecast icon. I can right click the page and cast the chrome tab, but it's not the same

![image](https://user-images.githubusercontent.com/71797034/94083364-f1348f80-fdd0-11ea-8f23-f49f2ce2f8f3.png)

**Comment by bnkai** [comment]
JW Player is not used anymore. Closing
