### ISSUE TITLE
[Feature] Add Class Names to Rating System Control

### ISSUE THREAD

**Issue by elkorol** [stashapp/stash#3634]
**Describe the solution you'd like**
Currently there is no way to know which rating system is being used from the DOM, either decimal or stars and or with which precision rating. Having class names added to the rating system, which would change depending upon which mode and precision is being used, would allow for easier user script development regarding the rating system. 

**Describe alternatives you've considered**

I've considered just adding a variable that the user would set themselves in the user script but having it being able to automatically know through class names would be preferable.

**Comment by WithoutPants** [comment]
Note that the system class names are already present: `rating-stars` and `rating-number`. Only precision is not currently included.
