### ISSUE TITLE
[Bug Report] Bulk editing performer's country (i.e. changing California to United States of America) ends up in a weird state

### ISSUE THREAD

**Issue by Kaelfurian** [stashapp/stash#3642]
**Describe the bug**
Bulk editing of a group of performers from the performer page does not correctly use the drop down of available known countries and when inputting in United States of America (for example), it ends up saving this value [United States of America] (and not 🇺🇸 United States of America) so it is not possible to filter for it making them difficult to locate again.

In short, the bulk editor does not correctly set the country.

**To Reproduce**
1. Search for a group of performers that have an incorrect country set (i.e. California)
2. Click on 'Select All'
3. Press the Edit button
4. Change country to United States of America
5. Press save.
6. Locate one of the edited performers and note that it is not set to 🇺🇸 United States of America but United States of America.

**Expected behavior**
Either 🇺🇸 United States of America should be selectable or inputting in United States of America should map to 🇺🇸 United States of America.

**Screenshots**
![image](https://user-images.githubusercontent.com/67079089/230124985-4a5a1bf6-091d-441e-9439-02fce562274c.png)
This will be set but the flag will not appear next to the performer name nor will it appear under any searches for 🇺🇸 United States of America.

**Workaround**
You can reset it back to the correct  🇺🇸 United States of America instead of just United States of America by changing the value on the performer's page. (not possible with the bulk editor)

**Stash Version: (from Settings -> About):**
v0.20.1

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version 111.0.1

**Comment by MrX292** [comment]
they are saved as [iso ALPHA-2 codes](https://www.iban.com/country-codes) in the database, so right now you would need to use `us` for United States of America for it to work correctly.

**Comment by Kaelfurian** [comment]
Thank you! That workaround is perfect, using `us` in the bulk editor works!
