### ISSUE TITLE
[Question] Is there a way to automatically use an image that is in the same directory as a scene for the cover image?

### ISSUE THREAD

**Issue by nothing2obvi** [stashapp/stash#3644]
# [Question] Is there a way to automatically use an image that is in the same directory as a scene for the cover image?

## Scope
I have some scenes that are in folders with their cover art already in the folder. Is there a way to make Stash automatically use this image as the cover photo? If it needs to have a certain title, I can adjust accordingly. Or if there's a way to customize it so it uses the image that says "-landscape.jpg" or "-poster.jpg" that would be great.

## Examples
![Screen Shot 2023-04-05 at 12 35 52 PM](https://user-images.githubusercontent.com/85228035/230186350-66adc062-5caa-4679-9e99-1e16ea5fa111.png)

**Comment by ALonelyJuicebox** [comment]
This is supported natively, pretty sure it was a feature added in the 0.20 release. Supports regex too, so you can also force it to use the image that says "landscape" or however youve configured things. Check settings to define this.

**Comment by DogmaDragon** [comment]
> This is supported natively, pretty sure it was a feature added in the 0.20 release. Supports regex too, so you can also force it to use the image that says "landscape" or however youve configured things. Check settings to define this.

I'm pretty sure that's gallery only feature not scenes.  not scenes.

**Comment by ALonelyJuicebox** [comment]
@DogmaDragon Derp you are correct. Bad reading comprehension on my end.

**Comment by nothing2obvi** [comment]
@Belleyy: Ahh. Didn't see that. I'll try it out. Thank you very much.

Thanks to everyone else here, too. I'll close this issue.
