### ISSUE TITLE
[UI/UX] Player touch controls UI regressions

### ISSUE THREAD

**Issue by dumdum7** [stashapp/stash#3649]
**Is your feature request related to a problem? Please describe.**
I mainly use Stash on mobile, specifically on an Android phone and an iPad, very rarely on desktop. There were several UI/UX regressions introduced in 0.18.0 with #3120.
The problems stem from badly implemented touch controls in the newly added [videojs-mobile-ui](https://github.com/mister-ben/videojs-mobile-ui) dependency:
* The play button is decoupled from the control bar. There were previously only two states for the control bar and buttons: both visible or both invisible. Now, there are three:
    * control bar visible, play button visible
    * control bar visible, play button invisible
    * control bar invisible, play button invisible
      This is is a weird and annoying design choice that none of the mobile video players use: Chrome for Android, Firefox for Android, Chrome for iOS, Safari for iOS, native and web YouTube player.
* The play button has its own animation you have to wait for, making it harder to quickly pause a video.
* The play button has a way too tall clickable area, making accidental plays/pauses very likely, especially when playing a vertical video on mobile.
* The control bar now pops up on touchstart events as well, which is annoying for devices with touch screens because of the increased probability of accidental touches.
* The double tap to seek feature gets triggered not just on click events, but also on touchstart events, making accidental seeks more likely.

**Describe the solution you'd like**
I suggest disabling videojs-mobile-ui's touch controls and reverting to using big-buttons. I understand we lose the double tap to seek feature by doing this, however I'd argue that we don't lose much on the UI/UX front. The big seek buttons are just as convenient, if not more, because you don't have to tap so many times. The only advantage double tap to seek has over them is the ability to seek without covering up the video with the control bar and play buttons. However, videojs-mobile-ui's implementation doesn't even do that correctly as it causes the control bar to pop up anyway.

**Describe alternatives you've considered**
Contributing to videojs-mobile-ui to fix the issues there.

**Additional context**
![play button too big clickable area](https://user-images.githubusercontent.com/95527094/230716697-8085209c-8a21-48c1-a8bd-b34a7a959844.png)

https://user-images.githubusercontent.com/95527094/230716699-e7791dd0-06de-4821-8e52-5ccd3e7f0c4a.mp4

https://user-images.githubusercontent.com/95527094/230716702-aca44d2c-8d6b-4a38-8d6a-860261850fda.mp4

**Comment by DingDongSoLong4** [comment]
I had noticed your comment on #3120, but ended up forgetting to follow up. I very much agree with all these issues.

I've figured out some CSS overrides to solve the first three issues in #3652 without removing double tap to seek. Would you be able to test them and see whether they work for you? Like I mentioned there, I don't mind whether we use the videojs-mobile-ui touch controls or the old big-buttons, but in the long term I think a custom plugin to support both and fix all the other issues would be best.

**Comment by dumdum7** [comment]
Thanks for the feedback! Those are some clever CSS tricks which do indeed fix the first three issues. However besides the last two issues there's one more I forgot to mention that isn't fixed by #3652: 
* You cannot hide the control bar and play button once it's visible by clicking, instead, you have to wait for it to close itself.

I think ditching videojs-mobile-ui touch controls for big-buttons is a good solution for now that fixes all the issues. At least until we have a better implementation of double tap to seek available.

**Comment by DingDongSoLong4** [comment]
I agree, that's probably the best solution for now then.
