### ISSUE TITLE
[Bug Report] sceneUpdate mutation nulls rating/studio/performer/tag fields when those values aren't passed

### ISSUE THREAD

**Issue by pierre-delecto** [stashapp/stash#365]
**Describe the bug**
Not sure if this is a bug or feature request, but it appears that the sceneUpdate mutation nulls rating/studio/performer/tag fields when those values aren't passed in the mutation.  It seems like those fields should be unaffected in that scenario.

**To Reproduce**
Steps to reproduce the behavior (warning, might lose data for a scene):
1. Find a scene with values for at least one of the rating, studio, performer, or tag fields.  Note the Scene ID (number in the URL)
2. Go to the graphql playground, and submit a sceneUpdate mutation without passing the relevant field.
Example mutation: 
```
mutation sceneUpdate($input:SceneUpdateInput!) {
  sceneUpdate(input: $input){
    id
  }
}
```
Query variables: `{ "input": {"id": <SCENE_ID>}}`

3. Check the scene (e.g., via UI).  Values for rating, studio, performer, and tag fields are now null.  Does not appear to null title, details, URL, date, or cover image.  Gallery is untested.

**Expected behavior**
Expect that values not passed to sceneUpdate wouldn't be nulled.

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser chrome

**Other notes**
performerUpdate mutation appears to work as expected, and does not null unpassed fields.

**Comment by tarzanboy76** [comment]
I just want to reiterate that this has been my experience too...

If modifying the sceneUpdate mutation isn't viable, is it possible to create new mutations for some of the individual items associated with a scene?  eg, scenePerformersUpdate, sceneTagsUpdate, sceneStudioUpate, etc.

**Comment by WithoutPants** [comment]
This has been addressed.
