### ISSUE TITLE
Find Missing phashes for scenes

### ISSUE THREAD

**Issue by Ashkaan** [stashapp/stash#3658]
When searching for duplicates, I get a message that says:

**"Missing phashes for 5 scenes. Please run the phash generation task."**

I've run the generation task, but there are 5 files that do not seem to generate.  How can I figure out which files those are?

**Comment by Flashy78** [comment]
Filter for `PHash is null`.

**Comment by Ashkaan** [comment]
Sadly, it comes up empty:

<img width="856" alt="image" src="https://user-images.githubusercontent.com/5667978/231559109-09c8692c-e5d8-4c7a-a27d-7f2cab2c8395.png">

**Comment by Ashkaan** [comment]
Oops, didn't mean to close.

**Comment by Flashy78** [comment]
Run a generate and look in the logs for any errors.
You can also join Discord to get more in depth help.

**Comment by Ashkaan** [comment]
Ok, thank you!
