### ISSUE TITLE
Subtitles do not display when video is fullscreen on iOS

### ISSUE THREAD

**Issue by org0ne** [stashapp/stash#3666]
Previous version v0.19.1 would display subtitles when the video was playing fullscreen, but the latest v0.20.2 only displays subtitles when the video is windowed.

**Comment by NodudeWasTaken** [comment]
This is caused by this line https://github.com/stashapp/stash/blob/0069c48e7e9298936dc5494865d0a4f674d6b29a/ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx#L278
If we set it to true it works.
We can either detect safari or just permanently set it to true.
