### ISSUE TITLE
[Bug Report] Live transcoding of a WMV restarts several times before playing on iOS

### ISSUE THREAD

**Issue by d3f113** [stashapp/stash#3670]
**Describe the bug**
Stash app is running on docker in a synology. When starting a WMV on the iPad, stashapp starts to live transcode the file. It takes some time while the screen is black. Than the thumbnail is showing in the video screen and the following error message on top of it:
„This media could not be loaded either because the server or network failed or because the format is not supported“
After a split second, both disappear and the screen is black again. After a few seconds the same happens again. This happens 5x and then the file gets started.
Because of this, it takes quite a while till the file is playing

**To Reproduce**
1. Go to a WMV file on iPad
2. start it and wait

**Expected behavior**
Instead of the error message, the file should play directly

**Screenshots**
It is impossible to make a screenshot of the error message, since it is just there for max 0.5sec

**Stash Version: (from Settings -> About):**
20.2

**iPad (please complete the following information):**
 - OS: iOS
 - Browser safari

**Comment by DingDongSoLong4** [comment]
This happens because Safari on iOS only supports HLS transcoding and not MP4 or WEBM transcoding. Because MP4 and WEBM are first in the list though, the player tries each of them first before getting to HLS.

#3507 should fix this.
