### ISSUE TITLE
[Bug Report] Gallery clean delete if zip extracted

### ISSUE THREAD

**Issue by HijackHornet** [stashapp/stash#3671]
**Describe the bug**
If a gallery has been created using a zip and you extract that zip, images will be considered moved from the zip to a folder and remapped correctly. However performing a clean will still delete the gallery as it consider the gallery to have no more files once the zip deleted, even though all images are still attached to it.

**To Reproduce**
1. Import a zip gallery
2. Extract it somewhere an delete the zip
3. Trigger a scan
4. See the migration has worked
5. Perform a clean task
6. The gallery is now deleted (problematic)

**Stash Version: (from Settings -> About):**
20.1

**Comment by HijackHornet** [comment]
After further investigation, the issue come from the fact a zip based gallery cannot be mixed with loose files. So on zip deletion, the gallery becomes file less and failed to switch to a file based gallery. Not sure if resolving this is more of a bug or a feature.

**Comment by xWTF** [comment]
IMO the gallery is created from a zip file, is immutable, and have a path association, so it should be deleted when the zip file is gone, this is the correct behaviour.
Creation of gallery that includes loose files, mutable and not associated with a file should be done manually, you may add a simple plugin to do that.

My practice is to create a new gallery with all files from the zip, add cover & metadata & whatever into it and add a logical tag (in my case `hidden:zip`) to the original zip gallery. Finally, use a default filter to exclude those hidden tags and you have a clean gallery view.

**Comment by HijackHornet** [comment]
The fact is it's hard to import proper galleries that are not zipped.
It's often easier to import a zip file and then uncompress it than importing losefile and then finding them and manually add them to a gallery.

**Comment by xWTF** [comment]
> The fact is it's hard to import proper galleries that are not zipped.

Yes, all you get from built-in scan is scattered images with no title nor organization. I'd suggest you to create a plugin and organize & tag them as you wish, which is much more flexible.
The RPC interface works (kind of) and grants you the ability to receive image creation event in any language, then you can call back to the stash instance with gql codegen and whatever library you like to organize stuffs :)
