### ISSUE TITLE
[Bug Report] BaseURL is set to reverse proxy IP, not web client's

### ISSUE THREAD

**Issue by twotobinary** [stashapp/stash#368]
**Describe the bug**
I'm using stash on my Kubernetes cluster with Istio mTLS enabled and [Pomerium](https://www.pomerium.io/) as my SSO provider which acts as a reverse proxy so this results in following access:
1. `https://<external stash domain>`
2. Istio routes to pomerium service within kubernetes cluster -> `pomerium-proxy.namespace.svc.cluster.local:443`
3. Pomerium routes to stash service -> `stash.namespace.svc.cluster.local:9999`
4. Pomerium sets baseURL to `stash.namespace.svc.cluster.local:9999` when it should be my external stash domain.

**To Reproduce**
Access stash from a reverse proxy and the host will be improperly set at [BaseURLMiddleware](https://github.com/stashapp/stash/blob/cd9c6e998ef7b51295f48963222d36c60ca52040/pkg/api/server.go#L299).

It would be nice if we can override this value with some configuration value such as `external_host: https://external.host.com`

**Expected behavior**
I expect to see my base URL set to the address my client is accessing stash from.

As a workaround, I can still stream all files as long as I manually set the domain to the external domain.

**Comment by WithoutPants** [comment]
Closed via #369
