### ISSUE TITLE
[Feature] Manual Control Over Watch Activity

### ISSUE THREAD

**Issue by AdultSun** [stashapp/stash#3680]
**Is your feature request related to a problem? Please describe.**
Currently, all watch activity metrics are tracked automatically. You can turn tracking on/off and adjust the watch percentage for the play counter, but everything else is handled automatically. There is no easy way to manually modify any of these metrics.

The current monitoring method is imperfect. I would like to manually input watch history that pre-dated the feature, but there is no way to do that in the UI. I would also like to track plays over DLNA, but those are not monitored currently and, again, I cannot manually track those plays within Stash either.

**Describe the solution you'd like**
Users should be able to manually modify or reset the last viewed date, play counter, play duration, and progress tracker. These values should be exposed to the edit panel where they can be changed or reset as needed.

I will also create a separate issue for DLNA tracking.

**Describe alternatives you've considered**
I guess I could edit the database directly but that's asking too much of the average user.

**Comment by Herpes3000** [comment]
Another vote for being able to edit play history stuff manually. There's so many use cases when I'm watching stuff outside of Stash. I went into more detail in this request https://github.com/stashapp/stash/issues/3392
