### ISSUE TITLE
Compile for ARM / Raspberry PI

### ISSUE THREAD

**Issue by StashAppDev** [stashapp/stash#37]
This has been requested.

**Comment by ExceptionalError** [comment]
Couldn't this be done with docker?
https://hub.docker.com/_/golang

**Comment by Leopere** [comment]
So there are two options that could be explored here, I have a compiler container and runner container on another project and it uses some magic but I have no idea how to do it via CI/CD at this current moment.  Not like it can't just don't think I've been down that path.

The other thing that could be explored by @StashAppDev is something called GoReleaser which it seems is trending in with a lot of devs for releasing for multiple architectures.

**Comment by bnkai** [comment]
closing as we now have binary releases for raspi.
