### ISSUE TITLE
[Bug Report] Sorting does not work on queryScenes when input tags INCLUDE_ALL modifier is used

### ISSUE THREAD

**Issue by hc60396** [stashapp/stash#3709]
**To Reproduce**
run query 
`query($queryScenesInput: SceneQueryInput!) {
   queryScenes(input: $queryScenesInput) {
      scenes {
        release_date
        }
      }
    }
  }
}`

with input
` {
    "queryScenesInput": {
    "sort": "DATE",
    "direction": "DESC",
    "tags": {
      "modifier": "INCLUDES_ALL",
      "value": ["e0bfd548-a226-4d76-a939-07b67c10c656", "df9cd431-cd72-4455-8797-9a67a5b8ce45"],
    }
  }
}`

**Expected behavior**
Sorting should work. I tested this with other sorting options such as title and the query always returned results in the same order

**Comment by MrX292** [comment]
could be misunderstanding, but aren't you querying stash-box?
so it should be a stash-box issue not stash

**Comment by hc60396** [comment]
I didn't know that the stashdb.org graphql implementation was separate. I haven't setup a local stash yet, but I will in a few days and will reopen this issue if it's not working there, thanks
