### ISSUE TITLE
[Feature] Set end time for markers

### ISSUE THREAD

**Issue by p0rnb0x** [stashapp/stash#3723]
**Is your feature request related to a problem? Please describe.**
markers right now are just timestamps, playing a marker keeps playing all of the video after that.
imo it would be nice to have an end time for markers, so the player either stops or loops after the end time.

**Describe the solution you'd like**
Just like start time markers should also have end time.

**Describe alternatives you've considered**
no alternative as of now

**Additional context**
related to #3264 but that is about looping on the front end.
this feature request is about adding and end time to the markers schema.

**Comment by DogmaDragon** [comment]
Dupe https://github.com/stashapp/stash/issues/3147

**Comment by p0rnb0x** [comment]
Thx, sorry didn't notice that issue
