### ISSUE TITLE
[Bug Report] Gallery incorrect sorting of duplicates

### ISSUE THREAD

**Issue by Mann0815** [stashapp/stash#3726]
I have some galleries. When I add new ones, duplicates are detected. However, these are wrong. The order of affected galleries no longer works. 

- Can I turn off duplicate detection for images? 
- Or is it possible to change the order of the images in the gallery manually?

**Stash Version: (from Settings -> About):**
v0.20.2
Hash des Builds:
e685f80e

**Comment by WithoutPants** [comment]
There's not enough information to determine if this is a bug. What is meant by "these are wrong" and "the order of affected galleries no longer works"?

Please provide a detailed instructions on how to reproduce the issue and the expected behaviour, as per the bug issue template.
