### ISSUE TITLE
[Bug Report] Japansese voiced consonant mark bug

### ISSUE THREAD

**Issue by suzuhiroruri** [stashapp/stash#3727]
**Describe the bug**
Japansese voiced consonant mark is not imported property.
example:
・"が" is Japanese one word, but stash app import as two words as "か" and "゛".
・"ぱ" is Japanese one word, but stash app import as two words as "は" and "゜".

**To Reproduce**
1. Import video file which has name Japansese voiced consonant mark.

**Expected behavior**

**Stash Version: (from Settings -> About):**
Voiced consonant mark is imported as one word.

**Desktop (please complete the following information):**
 - mac OS

**Comment by Releck** [comment]
Tried to reproduce this with a file named `がぎぐげご.mp4` and couldn't. Each character is correctly imported with no separate characters for dakutens.

Tested on 0069c48

**Comment by suzuhiroruri** [comment]
This file is separated characters for dakutens.
https://github.com/stashapp/stash/assets/1904259/990e1959-87ca-4921-b7b5-1d8e58a2281e

**Comment by Releck** [comment]
Can you please copy the filename with `岬あずさ` here. I suspect that somewhere along the line dakutens are manifesting as unicode control characters and you actually have `岬あずさ` (different character on the す) in your filename. More information about your system locale would help. I'm not convinced this is a stash bug.

**Comment by suzuhiroruri** [comment]
岬あずさ

**Comment by suzuhiroruri** [comment]
Sorry, I made mistake.
https://github.com/stashapp/stash/issues/3727#issuecomment-1547115845
is imported filename.

These are filename:
```
OKS-128 岬あずさ 濡れてテカってピッタリ密着 神スク水 可愛い女子のスクール水着姿をじっとりと堪能！着替え盗撮から始まり貧乳から巨乳にパイパン、ハミ毛、ジョリワキ等のフェチ接写やローションソーププレイやスク水ぶっかけ等を完全着衣で楽しむAV
```

```
岬あずさ
```

**Comment by suzuhiroruri** [comment]
Thanks, I understand that.
However I'm bothered, when I search dakuten word, becourse search dakuten words are not same as imported words. 
For example, file name has ```岬あずさ``` is not same word with search word ```岬あずさ```.

**Comment by suzuhirokakaku** [comment]
This is mac OS problem.
https://ja.stackoverflow.com/questions/35232/mac%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B-%E6%BF%81%E7%82%B9%E3%81%AE%EF%BC%91%E6%96%87%E5%AD%97%E6%89%B1%E3%81%84-%EF%BC%92%E6%96%87%E5%AD%97%E6%89%B1%E3%81%84%E3%82%92%E7%9B%B4%E3%81%99%E6%96%B9%E6%B3%95
