### ISSUE TITLE
[Bug Report] Possibly outdated chromedp causes unmarshaling error when scraping with CDP (unknown PrivateNetworkRequestPolicy value)

### ISSUE THREAD

**Issue by devnsfw** [stashapp/stash#3733]
**Describe the bug**
Can't use CDP with some scrapers on macOS

**To Reproduce**
1. Run Stash on macOS
2. Add a scene by URL with a scraper that uses CDP (such as Brazzers or Kink)
3. A red banner with an error appears briefly complaining about not being able to process OuterHTML
4. In the log, several instances of `ERROR: could not unmarshal event: unknown PrivateNetworkRequestPolicy value` are logged

**Expected behavior**
The scenes can be parsed normally and no extraneous messages are added to the log

**Stash Version: (from Settings -> About):** 0.20.2 (build hash e685f80e)

**Desktop (please complete the following information):**
 - OS: macOS 12.5.1
 - Browser: Firefox Developer Edition
 - Version: 114.0b3

**Smartphone (please complete the following information):**
No smartphone involved

**Additional context**
Tried with CDP based on Brave, Chromium and Chrome (all newest versions)
After looking up the error message, it appears that is related to old chromedp not being able to handle a new value for the PrivateNetworkRequestPolicy, but these changes appear to be at least 8 months old. And not seeing this issue being reported here before makes me suspect it is the Mac build of Stash which is made with an outdated version of chromedp. It could be that it is cross compiled and this part is not properly tested by the people preparing the builds.

**Comment by jeremymeyers** [comment]
Seeing this on Windows with 0.21.0 and chromedp headless Chrome/114.0.5735.134"

Attempting to do a scrape on a brazzers URL leads to this error and this redbox:

<img width="355" alt="Screenshot 2023-06-25 233950" src="https://github.com/stashapp/stash/assets/3514095/63d81a73-88dd-4d4c-a9b3-b1a272b3184a">

**Comment by DefinitelyNotSpicy** [comment]
It seems stash is just using a chromedp version that's too old.
This [comment](https://github.com/chromedp/chromedp/issues/797#issuecomment-1029706456) says we need at least `v0.7.7` but [Stash](https://github.com/stashapp/stash/blob/65fa81b6be3975245db36a2bbccdc6413deb7819/go.mod#L9C33-L9C34) is using `v0.7.3`.

It is a bit weird that the issue isn't more widely reported here. Maybe it only happens under certain circumstances?

**Comment by devnsfw** [comment]
yeah, it's possible that only certain content triggers it, or that some users decide that this technical stuff is too complex already and they'll just wait until they can pull from stashdb.

**Comment by DingDongSoLong4** [comment]
@its-josh4 Would you be able to update chromedp in #4107 to fix this issue? Just a bump to v0.7.8 seems like it would do the job, although the latest v0.9.2 would of course be the best if you're willing to make any necessary changes.

**Comment by its-josh4** [comment]
> @its-josh4 Would you be able to update chromedp in #4107 to fix this issue? Just a bump to v0.7.8 seems like it would do the job, although the latest v0.9.2 would of course be the best if you're willing to make any necessary changes.

@DingDongSoLong4 done
