### ISSUE TITLE
[Bug Report] Website and docsite are down

### ISSUE THREAD

**Issue by felmorn** [stashapp/stash#3745]
**Describe the bug**
https://docs.stashapp.cc/ -- DNS address could not be found. 

**To Reproduce**
1. Go to https://docs.stashapp.cc/
2. See error

**Expected behavior**
A functional website

**Screenshots**
![image](https://github.com/stashapp/stash/assets/134106398/2b8a0f79-9125-49f3-a5b5-f2b63fc44962)

**Stash Version: (from Settings -> About):**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave / Chrome
 - Version: v1.51.118

**Comment by DogmaDragon** [comment]
Known. It's propagating now, but that can take up to 48 hours. 

> DNS propagation is the time it takes updates to DNS records to be in full effect across all servers on the internet. Changes don't take effect instantaneously because nameservers store domain record information in their cache for a certain amount of time before refreshing.

You can check your DNS resolver status here <https://dnschecker.org>.
