### ISSUE TITLE
[Bug Report] Changing results number in Filename Parser resets regex

### ISSUE THREAD

**Issue by malconfig** [stashapp/stash#375]
**Describe the bug**
If you change parser recipe to something other than default `{title}.{ext}`, and then want to select to show more results per page, the parser recipe/regex resets to `{title}.{ext}` so you have to change parser recipe to the one you wanted again.

**To Reproduce**
1. Go to `0.0.0.0:9999/sceneFilenameParser` (or relevant domain you serve it at) in build f87117b
2. Select another parser recipe from the drop-down menu, almost at the bottom of the page.
3. Now try changing the number of hits per page to something else.
4. The parser recipe will reset to `{title}.{ext}`

**Expected behaviour**
That the number of results per page would change, but the parser recipe would stay the same.

**Screenshots**
If applicable, add screenshots to help explain your problem please ensure that your screenshots are SFW or at least appropriately censored.

[8 sec video showing the issue in action](https://i.imgur.com/xIPSBSh.mp4)

**Desktop (please complete the following information):**
 - OS: Windows 10 & Elementary OS 5.1 Hera
 - Browser Firefox & Epiphany
 - Version 73 & Web 3.28.6

**Additional context**
None.

**Comment by WithoutPants** [comment]
This is fixed in the v2.5 UI.
