### ISSUE TITLE
[Feature] Gallery UpdatedAt should be changed on image add/delete

### ISSUE THREAD

**Issue by rg9400** [stashapp/stash#3759]
**Is your feature request related to a problem? Please describe.**
Currently there is no sorting criteria to see the galleries with recently changed children images

**Describe the solution you'd like**
The Updated At sorting criteria seems to fit what users would expect when trying to sort galleries with recent changes. So the DB date for UpdatedAt should be changed when images are added/deleted and not only when metadata is changed.

Logic may apply to other parent objects with children being added/removed, but my specific usecase is for Galleries

**Describe alternatives you've considered**
You can navigate to recently added images, and from there, click on the gallery. But you may have 100 images added to a single gallery, and then you cannot find the next updated gallery without scrolling through all of them. This also does not handle cases where images were *deleted* from the gallery.

**Comment by WithoutPants** [comment]
$10 bounty assigned (txn no. 658250)

**Comment by rg9400** [comment]
@WithoutPants as mentioned in Discord, this doesn't seem to be working. Sharing pictures of my DB. Version is `94450da8`, which should have this PR added I believe.

Images table showing an image added on the 31st
![image](https://github.com/stashapp/stash/assets/39887349/62cd4f52-cfd5-4800-96d8-941c995df9bc)

Gallery tab showing the last UpdatedAt was on the 24th
![image](https://github.com/stashapp/stash/assets/39887349/19d1762a-e3bc-43e3-a328-9a75fd73f5c3)

![image](https://github.com/stashapp/stash/assets/39887349/3fd76bc2-9df7-44c8-adb3-58044641bd46)

**Comment by rg9400** [comment]
This is fully working now
