### ISSUE TITLE
[Bug Report] Path Sorting is incorrectly giving priority to digits

### ISSUE THREAD

**Issue by rg9400** [stashapp/stash#3760]
**Describe the bug**
When sorting by path, ideally, characters are sorted via the order listed here: https://en.wikipedia.org/wiki/List_of_Unicode_characters#Latin_script . This means that `(` or `!` should come before any digits. However, per my testing, digits come first, then these characters, then special characters.

**To Reproduce**
1. Create files such as `!test` and `(test)` and `1test` and `test`
2. Sort by path
3. Note that `1test` is highest on the list, followed by `!test` and `(test)` and then `test`

**Expected behavior**
Order should be `!test` > `(test)` > `1test` > `test`

**Stash Version: (from Settings -> About):** v0.20.2-53-g124adb3f

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] docker (hotio)

**Additional context**

**Comment by Flashy78** [comment]
It looks like the library being used for natural sorting (so that 2 comes before 03), sorts numbers ahead of punctuation.
https://github.com/fvbommel/sortorder/tree/main/casefolded

One option is to remove the natural number sorting feature, and just go back to using the default SQLite sorting.

**Comment by rg9400** [comment]
> It looks like the library being used for natural sorting (so that 2 comes before 03), sorts numbers ahead of punctuation. https://github.com/fvbommel/sortorder/tree/main/casefolded
> 
> One option is to remove the natural number sorting feature, and just go back to using the default SQLite sorting.

Well, my personal preference is to do this, but I guess it's a larger decision. I assumed there would be widely available and sane sorting algos that handle both cases.

**Comment by WithoutPants** [comment]
$10 bounty added (txn no. 659259)

**Comment by WithoutPants** [comment]
Relevant issues: #942, #943, #1362.

I'd consider removing the feature to be a regression based on the original issues above. I think that this is a bug in the third-party library. We can submit a bug/PR to the third-party library and potentially use a built-in sorting algorithm in the meantime.
