### ISSUE TITLE
[Feature] Add manual transcoding for scenes

### ISSUE THREAD

**Issue by gaytomi** [stashapp/stash#3785]
**Is your feature request related to a problem? Please describe.**
Sometimes, though Stash thinks it can play a video, it actually plays back choppy. Pulling the video and transcoding it with Handbreak/etc solves it - but it's a pain.

**Describe the solution you'd like**
Since Stash can detect unsupported media and automatically transcode it, it would be ideal if an option to manually trigger this was available on a scene's page.

**Comment by feederbox826** [comment]
This can be accomplished through the generate -> Transcodes dropdown
