### ISSUE TITLE
[Bug Report] internal error: multiple rows returned for single scene id 6XX

### ISSUE THREAD

**Issue by Phizulation** [stashapp/stash#3789]
Opened Stash today and came across errors like this. Scenes basically won't load but when I go to studios, I can play most of the videos in there, however not every studio works. Random studios display an error of "scene id6XX" and has a different number depending on the studio.

Running Stash on an Unraid Server, and nothing changed as far as im aware.

**Comment by WithoutPants** [comment]
This is likely a database issue. I won't be able to reproduce without a copy of your database. You could try anonymising the database and making a copy available.
