### ISSUE TITLE
[Feature/RFC] Break out Scenes in Movies

### ISSUE THREAD

**Issue by gaytomi** [stashapp/stash#3797]
When including a movie file consisting of more than one scene, there's no good way to break them down into their scenes. You can use Markers - but they don't appear in the Scenes and you can't include Actors in Markers. You can create a Movie, but you can't view the file from the Movie interface, and then you have to scrub through to it find a given scene. 

**Describe the solution you'd like**
It would be amazing if there were a way to create a "Scene Marker" (name to be figured out..). A Scene Marker would use a timestamp from an existing Scene (a 2 hour movie, for instance) but otherwise appear as a Scene in the UI. When creating a Scene Marker, Stash could even link it to the Movie. 

**Describe alternatives you've considered**
An alternative would be to mark a file as a Movie instead of a Scene and include the ability to view the full file in the Movie interface. Then this file would not appear in the Scenes at all - and from the Movie UI we could create Scenes from timecodes. Those would appear in the Scenes interface. 

**Bounty**
I contributed `Contribution #660850` with this or a similar feature in mind.

**Comment by xx790** [comment]
#3530

**Comment by gaytomi** [comment]
@xx790 perfect - that's ideal. We can close this and put my bounty towards the original issue since it has more discussion already. Thank you! 🎉

**Comment by WithoutPants** [comment]
@gaytomi Bounties are supposed to be confirmed with the development team before submitting, as noted in the OpenCollective tier:

> our contribution to this tier will be passed on directly (minus processing fees) to contributors that implement the issue of your choice. **Please confirm with the StashApp team on GitHub or Discord before proceeding.** Bounties are paid out at the discretion of the maintainers. Please include the Github issue number in your contribution message. Please note that posting a bounty is not a guarantee that the feature will be implemented.

In this instance, this feature is something that I'm planning on including, but it may not necessarily be entirely consistent with your requirements, hence why we like to discuss and plan these before assigning bounties on them. I will assign the bounty on the issue indicated.

**Comment by gaytomi** [comment]
@WithoutPants I totally get it. I don't mind, so long as something generally aligned with this ticket is created, it'll be great. It's a pain having a 2 hour video made up of scenes that you have to bookmark (and therefore lack the actors in them, etc etc etc). Sorry for the bounty mix up, really, just put it towards the general fund.

**Comment by WithoutPants** [comment]
> Sorry for the bounty mix up, really, just put it towards the general fund.

All good mate :) It's just something that's happened a few times now. It's a systemic problem that we need to address.
