### ISSUE TITLE
[Feature] Dynamically update details tab badge counters to reflect changes by filters

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#3814]
**Is your feature request related to a problem? Please describe.**
I use the details tab sections of pages quite often, and while it serves its purpose, there is a particular aspect of the UI that is very awkward and requires improvement which will enhance overall user experience. The issue is the static counter badges do not accurately reflect the content associated with the tabs when there are filters applied (which change the amount of items associated to said tabs).

For example, if I make a default filter to show subsidiary studios on studio pages. In this scenario I click on a primary studio that has 0 scenes and 0 performers. However, this studio has subsidiary studios with a total of 10 scenes and 10 performers. The badge counters will still read 0 respectively although clicking either tab will show 10 scenes and 10 performers.

This is a disparity in the number of items that the UI is communicating to the user and the number of items that is actually contained within that tab. When a badge indicates a specific number, users naturally expect to find that corresponding number of items within the tab. Consequently, this means the badge counters can be misleading. While I understand that the counts may be intended to be associated directly with unfiltered content, it still creates confusion when a badge suggests one thing, but the actual content differs.

**Describe the solution you'd like**
To enhance clarity and accuracy of the badges I would suggest the counter badges get updated each time a filter is applied. More over, I think it would be ideal if there was a visual cue to indicate the count badges have been affected by the filter. The most obvious way to do this is to change the badge text color from white to bright cyan (bright cyan is the color of the filter badge)

![image](https://github.com/stashapp/stash/assets/37937507/a62beffc-0c84-4946-af30-e306e4604dfb)

The number `2` on the image counter changed from the base reading. It's color is the same as the filter badge color to visually indicate the correlation.

**Comment by DogmaDragon** [comment]
I like the first suggestion. I would probably also update the current badges to match the one used on the filter button if they were to affect one another.

> I think it would be ideal if there was a visual cue to indicate the count badges have been affected by the filter. The most obvious way to do this is to change the badge text color from white to bright cyan (bright cyan is the color of the filter badge)

This might too be distracting in my eyes.

**Comment by DingDongSoLong4** [comment]
Currently, default filters are only applied to the top level pages (`/scenes`, `/images`, etc), so the only thing that would affect how many items are displayed when you first click on a tab is whether "show subsidiary tags/studios" is enabled. I agree that the counter should reflect this - you expect to see that number of items when you click the tab.

However, I don't think it is necessary to dynamically change the number in the tab as the filter changes - this information is already displayed below the pagination. Perhaps the counter should be hidden when the tab is selected to avoid confusion?

**Comment by echo6ix** [comment]
> However, I don't think it is necessary to dynamically change the number in the tab as the filter changes - this information is already displayed below the pagination. Perhaps the counter should be hidden when the tab is selected to avoid confusion?

@DingDongSoLong4 The reason I suggested dynamically changing the badge counters -- and for clarity by dynamic I mean as a filter changes each tab's badge counters are recalculated to reflect any changes -- there typically are multiple tabs with badges other than the actively selected tab. On all other tabs that are not the active tab, any info below the pagination is inaccessible to the user until they navigate to these respective tabs, and this circles back to _"I agree that the counter should reflect this - you expect to see that number of items when you click the tab."_

I am probably getting ahead of myself here, but if refining the badge counter behavior is an area of interest, I would strongly suggest hiding the badge on any tab that has a content count of 0. Having a badge counter that reads 0 is a super redundant visual cue and conveys no more information to the user than not having the badge at all. The 0 count badge comes at the cost of losing visual clarity of the other the badges which have counts > 0.

This is par for the course with badge counters (and even many treeview lists that show item counts beside their nodes), for example an unread email app badge counter. It does not appear when the unread emails are zero. It appears when the count of unread emails is greater than 0.

**Comment by echo6ix** [comment]
@DingDongSoLong4 This was a misunderstanding on my part. I assumed some filters that were universal (such as date) persisted and were applied to other tabs, as the subsidiary studio filter does. Problem solved.
