### ISSUE TITLE
[Bug Report] Performance Issue when Adding Performer in Scene Tagger

### ISSUE THREAD

**Issue by kermieisinthehouse** [stashapp/stash#3815]
When creating a performer from the scene tagger, the API hit to create the record is performed quickly, but then the UI hangs for several seconds after the success notification is displayed. It seems that some function is eating up the main thread and any other UI interactions also hang while this is happening.

It is probably related to updating the performer dropdowns present on every scene in the page.

**Comment by WithoutPants** [comment]
$50 bounty added (partial from `#663172`)

**Comment by i-am-at0m** [comment]
Not sure if it's related, but if the scrape has multiple results, and you select one other than the first one and then add a performer or site, when it comes back it reselects the first one.
