### ISSUE TITLE
Error: Panic: error initializing...

### ISSUE THREAD

**Issue by rablinz** [stashapp/stash#3827]
**To Reproduce**
Click on 'stash-win.exe'
Receive 'Error: Panic: error initializing configuration: mising the following mandatory settings: generated'

**Expected behavior**
installation

**Stash Version: (from Settings -> About):**
v0.21.0

**Desktop (please complete the following information):**
Windows 10

**Comment by WithoutPants** [comment]
This indicates an empty or corrupted `config.yml` file. 

Please check for a `config.yml` file in either the current working directory where the exe is located, or in `C:\Users\<username>\.stash`

You may also get more information if you run stash-win.exe from the command prompt.
