### ISSUE TITLE
[Bug Report] [UI] Overwrite existing filter confirmation modal displays under the saved filter list

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#3830]
**Describe the bug**
When overwriting an existing filter, a modal prompts the user for confirmation. However this modal appears under the filter dialog window and the buttons are obstructed.

**To Reproduce**
1. Go to scenes
2. Overwrite an existing filter

**Expected behavior**
The confirmation modal should be the top dialog window

**Screenshots**
![image](https://github.com/stashapp/stash/assets/37937507/550b9785-79b4-4401-ab21-7123ce4e012c)

**Stash Version: (from Settings -> About):**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 114.0.5735.110

**Comment by WithoutPants** [comment]
I'm not able to reproduce this on the latest dev build.

**Comment by echo6ix** [comment]
Confirmed. This is fixed now on one of today's latest builds (v0.24.3-44-g440c261f).
