### ISSUE TITLE
[Feature] Adding Backup Documentation to Wiki

### ISSUE THREAD

**Issue by Maxklos** [stashapp/stash#3832]
**Is your feature request related to a problem? Please describe.**

I was searching for a automatic way to create a backup for my database. The wiki and docs didn't touch this topic, they just provided a broad picture on how to use the API. I can't make a pull request for the wiki, so I think this is the best way to add it.

**Describe the solution you'd like**

Please add the following section to the wiki to the API Section. This way other don't have to search long and far for a way to do backups.

---------------

### Create Backup

Request:  `HTTP-POST`

    mutation { backupDatabase(input: {download: false})}

_Example using curl_

    curl -X POST -H "Content-Type: application/json" --data '{ "query": "mutation {backupDatabase(input: {download: false})}" }' localhost:9999/graphql

If `download:` is `true` the created backup is returned and not stored locally.

---------------

**Comment by DogmaDragon** [comment]
Thank you. 

The wiki should be considered deprecated. The documentation was moved to https://docs.stashapp.cc and is hosted on <https://github.com/stashapp/Stash-Docs>. Future issues/pull requests for documentation should be made against that repo.

I added the requested section <https://docs.stashapp.cc/networking/api/#create-backup>.
