### ISSUE TITLE
Hitting "Play Next" Endlessly

### ISSUE THREAD

**Issue by WithoutPants** [stashapp/stash#3834]
### Discussed in https://github.com/stashapp/stash/discussions/3833

<div type='discussions-op-text'>

<sup>Originally posted by **hepheastus** June 17, 2023</sup>
I've been trying to figure out how to hit next endlessly.
Right now, I can only hit next 40 times before I have to either hit shuffle in the queue log or go back to scenes (which I have defaulted to random) and click the first scene.  I have even tried to hit the bottom down arrow button in the queue list or even making my default scene show 1000 files instead of 40 and it still defaults to 40.

I just wanna keep hitting next forever.</div>

**Comment by Sassy0P** [comment]
As it's also a problem I encountered, I I tried to fix it. 

So I've local branch that solve this problem, but I need to get rid of some quirks. 

I'll try to make a draft later.
