### ISSUE TITLE
[Bug Report] socket error when opening stash

### ISSUE THREAD

**Issue by TheLn2** [stashapp/stash#3838]
**Describe the bug**

When launching stash, I've got this error
---------------------------
Stash - Fatal Error
---------------------------
Error: listen tcp 0.0.0.0:9999: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
---------------------------

and after this, my browser only show this:

I was using [v0.20.2] but [v0.21.0] didn't work either.

**To Reproduce**
click on stash-win.Exe

**Stash Version: (from Settings -> About):**
[v0.20.2] but [v0.21.0] didn't work either.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Firefox

**Additional context**
the program was working 15 days ago.

**Comment by DingDongSoLong4** [comment]
Do you perhaps have another instance of stash running in the background? Can you open Task Manager, go to the details tab, and see if `stash-win.exe` is in the list? If so, right click on it and "End Task" to close it, then try running stash again.

**Comment by TheLn2** [comment]
thx, but no other instance are running.

**Comment by MrX292** [comment]
try running `netstat -na|findstr 9999` in cmd

**Comment by TheLn2** [comment]
Thx, just rebooting have solved this issue :-)
