### ISSUE TITLE
Add the ability to re-generate a markers thumbnail/preview

### ISSUE THREAD

**Issue by JanikR95** [stashapp/stash#385]
I created a marker and after the thumbnail/preview was generated I realized the timestamp was wrong.
Changed the timestamp, but couldn't re-generate the thumbnail.

At the moment you have to delete the preview file manually.

**Comment by WithoutPants** [comment]
It is actually possible. If you regenerate the markers, it will regenerate the marker for the new timestamp. However, the old previews are left behind.
