### ISSUE TITLE
[Feature] Veracrypt container support

### ISSUE THREAD

**Issue by LinuxTux193** [stashapp/stash#3858]
**Is your feature request related to a problem? Please describe.**
no, it isn't
**Describe the solution you'd like**
Encrypt the directory with a veracrypt container, so when navigating the files in the system there isn't porn
**Describe alternatives you've considered**
mounting the veracrypt container before starting stash, not so pratical
**Additional context**

**Comment by DingDongSoLong4** [comment]
Given the username, I'm going to go out on a limb and assume you're using Linux - in which case I think this should be achievable with a shell script.

Something like this should work:
```bash
#!/bin/bash

onexit () {
    umount /mnt/totally_not_porn  # unmount command here
}

mount /mnt/totally_not_porn  # mount command here

trap onexit EXIT  # run "onexit" on shell exit, even if quitting with CTRL-C (SIGINT)

stash  # or path to stash binary if not on PATH
```
Then use `chmod +x` to make it executable, and optionally place it on your PATH (`~/.local/bin` is a good place) if you want to be able to run it from anywhere. Then running the script should run your mount command, run stash, and after stash exits, run your unmount command.

**Comment by LinuxTux193** [comment]
Thanks

**Comment by DingDongSoLong4** [comment]
Closing as the issue can be solved with a shell script.
