### ISSUE TITLE
[Feature] Add more Sorting Options / More Information.

### ISSUE THREAD

**Issue by synsyn93** [stashapp/stash#386]
I see some other features similar to this so if this is duplicate data feel free to link it to an existing feature request.

**More sorting options to include:**

**Performers Page:**
Give Number of Performers at the top of page.
Example:  Performers Total: 425.
When searching update count.   
Search = Kendra:  Result would be 2 Performers:  (Kendra Spade , Kendra Lust). Count = 2.

**When Sorting add / updates:**
1.  Markers Total - Show total Markers under Performer name on card as you do with the scene count. 
2. Height - (update / change) Show height in on Performer Card in Inches or cm's (maybe toggle 
between cm/inches in settings)
3. O Counts Total -  Show Total O counts under performer name (as you do with scene count).

**Scene Page: ( These are thoughts, some date/time stamps would need to be introduced.)**

Give Total number of Scenes at the top: Update as sorts or filters are added.

1. Added Date / Created Date -  Options - Last 7,14,21,30 Days, etc..
2. O counts by date if possible - (Guessing a time stamp would need to be added to o-counts so may be difficult - how do you fill in previous data?)
3. Markers by date - See above..

*Studios Page** (Basically same as Performers page outlined above)
Give Number of Studios at the top of page, when searching update count.
Example:  Studios Total: 425.  

**When Sorting add / updates:**
1.  Markers Total - Show total Markers under Studio name on card as you do with the scene count. 
2. O Counts Total -  Show Total O counts under studio name (as you do with scene count).
3. Scenes added to Studio - Sort by date = Options - Last 7,14,21,30 Days, etc..

**Tags Page:** 
Most of the above functionality exist here.  Could do a search or sorting function here to sort through tags rather than scrolling through the entire list.

**Additional context**
The landing page under stash has some of the stats already, it would be nice to have these on the actual pages as well.  You could then also summarize some of the statistics mentioned above onto the stash "landing" page.  For example you could list on the landing page: Top 25 Performers by Scene Count, O-Count, Markers.   Scenes added in last 7 days.  Markers created in last 7 Days. Total O Counts, things like that.  Make the landing page kind of a summary of cool statistics that may be of interest.

**Comment by rainchaser210** [comment]
Performer page add: Ability to resize thumbnails like on Scenes page

All pages add: Ability to change page without scrolling to bottom

**Comment by hyde231** [comment]
I like that idea of more statistics and thought of the following:
On the welcome/stash tab there could be some charts on performer age with average and median marked, maybe some distribution graphs on height, measurements, hair color, country, this kind of stuff...  all linked to the respective filter setting in the scenes tab

**Comment by seducingbits** [comment]
For the scenes page:  
Sort by studio. If the sorting is stable the scenes of the same studio would be sorted as before or maybe by a sensible default like date.

**Comment by DogmaDragon** [comment]
Mostly implemented. The one thing missing is relative date filters, but they have their own issue https://github.com/stashapp/stash/issues/5010.
