### ISSUE TITLE
[Feature] Increase Log File Size

### ISSUE THREAD

**Issue by milkmandoor** [stashapp/stash#3868]
**Is your feature request related to a problem? Please describe.**
The log file size seems to be capped at around 67MB and this makes us lose all logs prior to that limit, which thwart monitoring of our app.

**Describe the solution you'd like**
Please allow for a configurable max size for logs instead of a hard coded limit, and also allow for unlimited log size. This is up to the administrator to make sure it won't use all their filesystem storage.

**Comment by MrX292** [comment]
how are you running stash?
i don't think there is a limit.

**Comment by DogmaDragon** [comment]
There is no limit set for logfile. Mine is `140MB` right now and I seen people who have it in GBs.

**Comment by milkmandoor** [comment]
Yep, I was mistaken, I must have lost earlier logs from something of my doing.

All good ! I'm closing this
