### ISSUE TITLE
[Bug Report] Terrible Performance With videojs-vr in Linux Firefox

### ISSUE THREAD

**Issue by johnnyporn88** [stashapp/stash#3872]
**Describe the bug**
Framerate of VR video is terrible. Almost slide-show quality.
There are no problems with frame rate when playing VR videos normally.

Problem is particularly egregious with hevc/aac files.
It still occurs with h264/aac files, but is less severe.

**To Reproduce**
Open scene that has hevc video/aac audio codec.
Play scene in VR 360 mode.
Experience slide show.

**Expected behavior**
For the player to run the video with the original file's frame rate.

**Stash Version**: v0.21.0

**Desktop (please complete the following information):**
 - OS: Linux (Pop! OS 22.04 LTS, 64-bit, GNOME 42.5)
 - Browser: Firefox v114
 - Hardware: AMD Ryzen 7 3700X, Nvidia RTX 2080 Ti, 32 GB RAM

**Comment by MrX292** [comment]
Firefox does not support [hevc](https://caniuse.com/hevc) so it needs to live transcode the file for your browser to play it.
can you try another browser.

**Comment by Maista6969** [comment]
This can probably be closed
