### ISSUE TITLE
[Feature] Break movie with only one file into scenes

### ISSUE THREAD

**Issue by alucicrazy** [stashapp/stash#3873]
**Is your feature request related to a problem? Please describe.**
I have some movies that have only one file, but i'd like if there was some way to divide them into scenes

**Describe the solution you'd like**
either manually setting the starting point and end point of a scene 

**Describe alternatives you've considered**
 get the slices info from some database

**Additional context**
This is mostly for JAVs

**Comment by echo6ix** [comment]
This is a duplicate of #3530 #260 #779
