### ISSUE TITLE
[Feature] [Scraper Development] Add scraper object fields for newly added performer fields

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#3888]
**Is your feature request related to a problem? Please describe.**
Recently new performer fields were added (circumcized, penis length), but to my knowledge there are no corresponding object fields for scraper development.

**Describe the solution you'd like**
Add object fields: `Circumcized` _(boolean)_; `PenisLength`

**Comment by DogmaDragon** [comment]
They already exists. 
`PenisLength` allows numbers.
`Circumcized` only allows enums `cut` and `uncut`, everything else will result in NULL.

I need to update the documentation.

**Comment by echo6ix** [comment]
> They already exist. `PenisLength` allows numbers. `Circumcized` only allows enums `cut` and `uncut`, everything else will result in NULL.
> 
> I need to update the documentation.

Ok, good to know. Thanks
