### ISSUE TITLE
[Bug Report] Random sort not working as expected

### ISSUE THREAD

**Issue by egon6969** [stashapp/stash#392]
**Describe the bug**
The random sorting option sorts scenes randomly but shows old behavior of always returning same order. It seems that the random seed from the URL is not used.

**To Reproduce**
1. Go to 'Scenes'
2. Select 'random' sorting
3. Select different sorting
4. Reselect 'random' sorting

**Expected behavior**
Different order on reselecting random. 

**Desktop (please complete the following information):**
 - OS: Docker container on linux
 - Browser: chrome and firefox
 - Version: b3fab3c

**Comment by WithoutPants** [comment]
Confirmed. Suspect this is related to the ListHook changes to fix other bugs.
