### ISSUE TITLE
[Bug Report] Filter query extremely slow

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#3932]
**Describe the bug**
Filtering studios using the criteria `Gallery count is less than 1` & `Scene count is less than 1` & `Image count is less than 1` causes the page to hang on the "Loading" spinner.

The same happens if we replace the filters with:
- GALLERY COUNT is 0
- IMAGE COUNT is 0
- SCENE COUNT is 0

**Edit**: It does return results eventually but the query takes well over a minute. Meanwhile the results for the following are almost instantaneous:
- GALLERY COUNT is 0 & SCENE COUNT is 0 ✔️(almost instant results)
- IMAGE COUNT is 0 & SCENE COUNT is 0 ✔️ (almost instant results)
- GALLERY COUNT is 0 & IMAGE COUNT is 0 ✔️ (almost instant results)
- GALLERY COUNT is 0 & SCENE COUNT is 0 & IMAGE COUNT is 0 ❌ (results take over a minute to return)

**To Reproduce**
1. Go to _Studios_ page
2. Open the filter dialog and add the following filters
   - GALLERY COUNT is LESS THAN 1
   - SCENE COUNT is LESS THAN 1
   - IMAGE COUNT is LESS THAN 1

**Expected behavior**
The page should either display studio cards that match the criteria or return a blank page if nothing matches the query. If this is an erroneous filter query perhaps it should return an error message to the user.

**Screenshots**
![image](https://github.com/stashapp/stash/assets/37937507/93ca787b-916d-4477-bd20-0ee191bf85bb)

**Stash Version: (from Settings -> About):**
- v0.21.0-34-g7c226fe2
- Ubuntu

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 114.0.5735.199 (Official Build) (64-bit)

**Additional context**
My library size

Studio count|Image count|Gallery count|Scene count
---|---|---|---|
699|23,590|414|4,919

CPU: `Intel(R) Core(TM) i5-6200U CPU`

On Discord some are able to reproduce this, and some not: https://discord.com/channels/559159668438728723/559159910550732809/1132060140632277054

**Comment by echo6ix** [comment]
It takes over a minute but this query actually does return results.

I thought perhaps this was due to old hardware, because my CPU is `Intel(R) Core(TM) i5-6200U CPU`, but another user has much higher specs with the same issue https://discord.com/channels/559159668438728723/559159910550732809/1132088606991851661

**Comment by DingDongSoLong4** [comment]
On my database, the query takes about 5-10 seconds, and my library size is

Studio count | Image count | Gallery count | Scene count
-- | -- | -- | --
187 | 2,599,031 | 18,725 | 25,715

(95% of the galleries and scenes have linked studios, but none of the images do)

The offending SQL query is this: 
```sql
SELECT DISTINCT studios.id FROM studios LEFT JOIN scenes ON scenes.studio_id = studios.id LEFT JOIN images ON images.studio_id = studios.id LEFT JOIN galleries ON galleries.studio_id = studios.id GROUP BY studios.id  HAVING ((count(distinct scenes.id) < 1) AND (count(distinct images.id) < 1) AND (count(distinct galleries.id) < 1)) ORDER BY studios.name  ASC, COALESCE(studios.name, studios.id) ASC LIMIT 40 OFFSET 0;
```
which takes around 2-3 seconds on my database.

Would you be able to run the following query in a database console of some kind (DB Browser for SQLite, or just the `sqlite3` CLI) and post the results?
```sql
EXPLAIN QUERY PLAN SELECT DISTINCT studios.id FROM studios LEFT JOIN scenes ON scenes.studio_id = studios.id LEFT JOIN images ON images.studio_id = studios.id LEFT JOIN galleries ON galleries.studio_id = studios.id GROUP BY studios.id  HAVING ((count(distinct scenes.id) < 1) AND (count(distinct images.id) < 1) AND (count(distinct galleries.id) < 1)) ORDER BY studios.name  ASC, COALESCE(studios.name, studios.id) ASC LIMIT 40 OFFSET 0;
```
That should tell us whether SQLite is using indexes (fast) or scanning the tables sequentially (slow).

**Comment by echo6ix** [comment]
@DingDongSoLong4 This was the result of the query

![image](https://github.com/stashapp/stash/assets/37937507/70356edf-663a-4001-825b-cf35ddabadfb)

```
Execution finished without errors.
Result: 6 rows returned in 11ms
At line 1:
EXPLAIN QUERY PLAN SELECT DISTINCT studios.id FROM studios LEFT JOIN scenes ON scenes.studio_id = studios.id LEFT JOIN images ON images.studio_id = studios.id LEFT JOIN galleries ON galleries.studio_id = studios.id GROUP BY studios.id  HAVING ((count(distinct scenes.id) < 1) AND (count(distinct images.id) < 1) AND (count(distinct galleries.id) < 1)) ORDER BY studios.name  ASC, COALESCE(studios.name, studios.id) ASC LIMIT 40 OFFSET 0;
```

**Comment by echo6ix** [comment]
> The offending SQL query is this:
> ```SELECT DISTINCT studios.id FROM studios LEFT JOIN scenes ON scenes.studio_id = studios.id LEFT JOIN images ON images.studio_id = studios.id LEFT JOIN galleries ON galleries.studio_id = studios.id GROUP BY studios.id  HAVING ((count(distinct scenes.id) < 1) AND (count(distinct images.id) < 1) AND (count(distinct galleries.id) < 1)) ORDER BY studios.name  ASC, COALESCE(studios.name, studios.id) ASC LIMIT 40 OFFSET 0;```

I decided to try this on a local copy of my database using DB Browser. It's been **nine** minutes and counting and the process is still busy reading rows

**Comment by echo6ix** [comment]
I think I have confirmed the issue as you alluded to on Discord. After removing the studio_id from the 21,141 images the slow query result is now instantaneous. 

But isn't it still abnormal that having two conditions in the Stash query `IMAGE COUNT is 0 & SCENE COUNT is 0` or `IMAGE COUNT is 0 & GALLERY COUNT is 0` return instant results yet adding a third condition  `IMAGE COUNT is 0 & SCENE COUNT is 0 & GALLERY COUNT is 0` causes it run for 1m22s?

**Comment by Flashy78** [comment]
> But isn't it still abnormal that having two conditions in the Stash query `IMAGE COUNT is 0 & SCENE COUNT is 0` or `IMAGE COUNT is 0 & GALLERY COUNT is 0` return instant results yet adding a third condition `IMAGE COUNT is 0 & SCENE COUNT is 0 & GALLERY COUNT is 0` causes it run for 1m22s?

It's not unexpected, the more filters you add to an SQL query, the more complex it gets.

Try removing the `DISTINCT` at the start. Or try removing the `ORDER BY studios.name  ASC, COALESCE(studios.name, studios.id) ASC` at the end.
