### ISSUE TITLE
[Feature] add partial/selective scan and partial/selective clean to integration API

### ISSUE THREAD

**Issue by i-am-at0m** [stashapp/stash#3934]
**Is your feature request related to a problem? Please describe.**
When whisparr for example adds or upgrades a scene, the only option is for it to trigger a full library scan, instead of a scan of the subfolder where it dropped the file. Additionally, when it upgrades, the old file doesn't go away in stash until a manual clean is executed. 

**Describe the solution you'd like**
Add those options to the API so that they can be integrated into whisparr

**Describe alternatives you've considered**
I feel this needs to be built into Stash at this point

**Additional context**
Sonarr does this with Plex and it seems to work pretty well

**Comment by MrX292** [comment]
you can give both the scan and clean a path
```
mutation MyMutation {
  metadataScan(input: {paths: ""})
  metadataClean(input: {dryRun: false, paths: ""})
}
```
so is that not already in stash?

**Comment by Maista6969** [comment]
This can be closed
