### ISSUE TITLE
[Bug Report] Syntax error when movies have a # symbol in the name

### ISSUE THREAD

**Issue by malcuk** [stashapp/stash#394]
**Describe the bug**
When a movie has a # in the name, clicking on "Scenes" then causes a syntax error. 
`Something went wrong.
Details
SyntaxError: Unexpected end of JSON input`

**To Reproduce**
1. Create a movie with a # in the name
2. Add a scene to this movie
3. Click on "Scenes" for this movie

**Expected behavior**
Behavior should mirror movies without a # symbol

**Desktop (please complete the following information):**
 - Windows 10
 - Opera 67.0.3575.53

**Comment by WithoutPants** [comment]
Verified that this occurs with movies, but also with tags, performers and studios. This is occurring because the `#` symbol is not encoded when generating the URL for the query, which results in the URL query parsing to incorrectly cut the search parameter at the wrong point.
