### ISSUE TITLE
[Bug Report] Unnecessary fingerprinting files inside a zip on move or rename

### ISSUE THREAD

**Issue by peresabcod** [stashapp/stash#3947]
**Describe the bug**
When you move or rename an already indexed zip file gallery, the scan task checks the fingerprint of the zip file and every single file inside it, even if the zip fingerprint matches the already registered.

**To Reproduce**
Scan a folder with several zip files
Rename the folder or the zip files
Scan again

**Expected behavior**
Seems unnecessary and very time consuming to open and check every image file considering that if the fingerprint for the zip hasn't changed, the files inside remain the same. Moving large amount of files makes the scanning process takes a long time.
It just needs to update the path of the images once it has verified that the zip fingerprint match, and only check every file if it doesn't

**Stash Version: (from Settings -> About):**
v0.21.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by WithoutPants** [comment]
This appears to be fixes as of [eb67f7f](https://github.com/stashapp/stash/commit/eb67f7f4d60ee86b15fad62200af1f7d3087761e)
