### ISSUE TITLE
StashApp crashes on Windows when network adapter / connection changes

### ISSUE THREAD

**Issue by CorvusSan** [stashapp/stash#3952]
**Describe the bug**
When the windows laptop I run StashApp on changes WiFi network or its wired Ethernet adapter gets turned on/off, StashApp tends to crash shortly thereafter.

**To Reproduce**
Configure StashApp to work against a network-mapped drive.
1. Start StashApp with a live Ethernet connection, open StashApp page in browser
2. Disable the Ethernet adapter
3. Refresh the browser page/tab that has StashApp open
4. StashApp crashes and browser displays error message

**Expected behavior**
No crash on temporary change of network status.

**Screenshots**
None

**Stash Version: (from Settings -> About):**
v0.21.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version: 1.56.11 Chromium: 115.0.5790.102 (Official Build) (64-bit)

**Comment by WithoutPants** [comment]
By `StashApp crashes`, do you mean the application crashes and must be restarted? What browser error message are you getting? What address are you using to access stash in the browser?

**Comment by CorvusSan** [comment]
Right, the app terminates and needs to be restarted. The browser error message is a generic "server not responding"/"timeout" message. I'm accessing the app via the alias localhost:port, e.g. http://localhost:9998 
If there is a way I can turn on diagnostic logging that will survive after the app terminates, I could try that and provide those logs to you.
But I'm not sure this issue is important/frequent enough that it warrants too much effort. I mostly just wanted to report it for awareness. I can live with it, no problem.

**Comment by WithoutPants** [comment]
If you run stash from the command line terminal, you should be able to see the error message that gets displayed when it panics.

**Comment by CorvusSan** [comment]
Hmm. I would need to change the close behavior of the terminal then. I've set my terminal app as the new modern Terminal that lets you use different command processors under the covers (cmd, powershell, others). Let me see if I can figure that out.

**Comment by CorvusSan** [comment]
Interesting. Two different codes for two different instances (I run two instances, each with its own port [9999 and 9998]):
[process exited with code 3221225477 (0xc0000005)]
[process exited with code 3221225478 (0xc0000006)]

**Comment by WithoutPants** [comment]
That's weird. It should be outputting a stack trace if it's panicking.

**Comment by CorvusSan** [comment]
Even on Windows? Do I need to turn on special logging in some way for that?

**Comment by WithoutPants** [comment]
Nope. When stash (or any go executable) panics, it outputs the stack trace to stderr (or possibly stdout). Can you just run it from `cmd`?

**Comment by CorvusSan** [comment]
Even when I run it directly from cmd, all I get when the scenario triggers is a return to the command prompt.
![image](https://github.com/stashapp/stash/assets/140566445/6ec17755-017d-45c4-a8c9-935a96bfcfd6)

**Comment by DingDongSoLong4** [comment]
I am unable to reproduce this on a desktop by either unplugging the Ethernet cable or disabling the adapter in network settings. `localhost` connections should continue working irrespective of whether the machine is actually connected to the internet or an external network. I don't have access to a Windows laptop so I can't test it there.

Would you be able to run stash in a different folder and create a new config file from scratch? Just to make sure some setting isn't causing the issue.

Your `Y:` drive there isn't perhaps a network-attached drive of some kind?

**Comment by CorvusSan** [comment]
Yes, the Y: drive is network mapped. I mentioned it in the steps to reproduce, but perhaps not as clearly as I could. And maybe we're back to my suspicion that this is not worth pursuing further. It's a bit of an edge case, I think.

**Comment by DingDongSoLong4** [comment]
Oh my bad, I missed that. I would have to assume that is the reason.

I have to add this warning though - you should only be storing content on the network drive (your actual videos/images and generated content like screenshots/preview videos). If you are storing your database (the `stash-go.sqlite` file) on a network drive you are running a fairly significant risk of corrupting your stash metadata. Stash uses SQLite which was not designed to operate over a network.

Stash shouldn't outright crash if content becomes inaccessible (due to a network drive temporarily not working after a network connection change). However, if you're storing the database, config file or the stash executable itself on the network drive, any crash definitely wouldn't be considered a bug.

**Comment by CorvusSan** [comment]
Thank you! I will make some changes, because I am doing what you're mentioning. I need to fix that, but it should be as simple as moving the stash folders from the network drive back to a local drive.

I'll close this report now.

**Comment by CorvusSan** [comment]
There's no need to look into this further.

**Comment by DingDongSoLong4** [comment]
I will just say that if your database was on the network drive, I would highly recommend running the `PRAGMA integrity_check;` and `PRAGMA foreign_key_check;` SQL statements after copying your database to a local drive, to check if any corruption did indeed occur (the first should return "ok" and the second should return nothing). The easiest way to do that would be to open your database in a program like [DB Browser for SQLite](https://sqlitebrowser.org/) and run those two statements separately using the "Execute SQL" tab.

If there is corruption I would be able to assist with recovery on Discord, or better yet if you have a recent backup then restoring from that would be easier.

**Comment by CorvusSan** [comment]
Thanks! Both those commands indicate my database is still healthy.
