### ISSUE TITLE
[Feature] Add BBBH as link type

### ISSUE THREAD

**Issue by gaytomi** [stashapp/stash#3956]
[#BBBH](https://bbbh.com/pornstars) has lots of info on gay porn stars, it would be nice to have it as an official link type.

**Comment by DogmaDragon** [comment]
Unrelated to Stash. 

StashDB manages site requests through a [speadsheet](https://docs.google.com/spreadsheets/d/1xELptjVmapvUX4g0CervfKLMXSYihxkWPkjlM-QqZEg/edit#gid=0).
