### ISSUE TITLE
[Bug Report] Scene Overview, Scrap All doesn’t save tags

### ISSUE THREAD

**Issue by d3f113** [stashapp/stash#3959]
**Describe the bug**
Scraping doesn’t add existing tags to scenes, just tags which aren’t existing in the database. Already existing tags, which are not assigned to the scene, don’t show up

**To Reproduce**
1. Go to Scenes
2. Click on the most right view button (Tagger)
3. Click on Scrap all (StashDb configured and selected on the left)
4. Look at one video, which was scrapped and should have a tag

Works with autotagging as well

**Expected behavior**
Show existing tags from stashdb

**Stash Version: (from Settings -> About):**
v0.21.0

**Desktop (please complete the following information):**
 - OS: iOS (iPad)
 - Browser safari

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: iPadOS 16.4.1
 - Browser safari

**Comment by Flashy78** [comment]
What are you tag settings in your Tagger configuration? Haven't heard anyone else with this issue, and it would be a big one.

**Comment by d3f113** [comment]
You mean in the auto tagger settings? Everything is activated.
Btw tagging works, if I do it in the detail view (in a scene) but not in the list view where all scenes are

**Comment by Phasetime** [comment]
I can't seem to reproduce the behavior on v0.21.0-66-g3ea233dc. 
Have you checked this checkbox? If not only non-existing tags will be shown in the tagger view. 
![image](https://github.com/stashapp/stash/assets/87231024/cf0ca38a-5b5d-4b9a-9670-260ff4f14169)

**Comment by d3f113** [comment]
Yes, that was the problem. Sorry.
I was confused because if u do the scrapping in the details, it adds tags automatically. On that listview you need to make the setting in that views
