### ISSUE TITLE
[Feature] Add rating stars for images; Add sort by rating for images

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#3960]
**Is your feature request related to a problem? Please describe.**
There is no method to rate images. This will come in handy if users want to sort their performer images based on their favorites. This will come in handy now that the performer dashboard is rightfully reducing the size of the performer image.

**Describe the solution you'd like**
- Add ability to rate images using rating stars
- Add ability to sort images by rating

**Comment by WithoutPants** [comment]
I don't quite understand this. There's already a sort option for rating in the images page and we can already rate images.

**Comment by echo6ix** [comment]
> I don't quite understand this. There's already a sort option for rating in the images page and we can already rate images.

Welp, turns out I had a really old custom CSS I copied from Discord which was hiding the rating stars on images for some reason 🙃

Then I just assumed no rating stars = no way to sort images based on ratings.
