### ISSUE TITLE
Identity checkboxes don't work

### ISSUE THREAD

**Issue by KinkCastle** [stashapp/stash#3992]
**Describe the bug**

Toggling checkboxes in the Identity Dialog/Modal don't work.

**To Reproduce**
1. Go to Settings
2. Go to Tasks
3. Click on "Identitfy"
4. Edit any Field option with a checkbox (Studio, Performers, Tags)
5. Enable the Checkbox
6. Save the Setting via the green check icon

**Expected behavior**
The red "X" should be changed to an (i assume) green check icon.
If you click directly on another field option edit button the icon will be displayed as checked.

Regardless: The settings weren't applied in my current test (i have not tested every possible combination)

**Screenshots**

Confirming via check:

![chrome-capture-2023-7-2](https://github.com/stashapp/stash/assets/141179453/9e149eff-a290-4dfa-8c94-63f6c60defcb)

Just switch to the next option (but doesn't work anyway):

![chrome-capture-2023-7-2 (2)](https://github.com/stashapp/stash/assets/141179453/6858cd4a-a867-4ecd-a610-14a9efa4aa6d)

**Stash Version: (from Settings -> About):**

v0.21.0

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 115.0.5790.110

**Comment by MrX292** [comment]
If you change the strategy also then it will save.
You can change t back after.
