### ISSUE TITLE
[RFC] Ability to reset "Play Duration"

### ISSUE THREAD

**Issue by LeGrosFromage** [stashapp/stash#3997]
*### Scope*
Looking for a way to reset the Play Duration of a scene back to 0:00.  I realize there's no way in the UX currently to do this, so I'm willing to edit the database **at-my-own-risk** if someone can provide the SQL statement and/or the correct place to look in the database.

Or, if this is the worst idea in the history of Stash ideas, please say so also.

Basically I'm very anal about how my scene page and scene cards look, and having a little blue bar on some cards where I've played the first few seconds so I can have a good frame to generate the default thumbnail from, is annoying.  I know I could just skip them to the end and let them play out but a batch way to clear all the durations, to me, would be useful.

Thanks!

**Comment by Maista6969** [comment]
>[!WARNING]
> This is irreversible

Sure, if you're comfortable with the commandline will set the play duration for ALL scenes to 0:
```bash
$ sqlite3 stash-go.sqlite 'UPDATE scenes SET play_duration = 0'
```
Replace `stash-go.sqlite` with the path to your own database

If you don't have `sqlite3` installed and you're on a develop build that has the new SQL query features, you can go to your local `/playground` endpoint and run this to accomplish the same thing
```graphql
mutation {
  execSQL(sql: "UPDATE scenes SET play_duration = 0") {
    rows_affected
  }
}
```

**Comment by LeGrosFromage** [comment]
Perfect, thank you... I'll make a backup of the database and give it a try.  I'm not on a dev branch.

I did a quick filter of "Play Duration !=0" and I have 297 clips that have some play time, so this will be much easier than manually setting them.

Thanks!!!

**Comment by MrX292** [comment]
Can you try force refreshing your browser.

**Comment by LeGrosFromage** [comment]
No difference... and just to be sure I opened Stash in another browser also, bars are still there.

**Comment by DingDongSoLong4** [comment]
The blue bar is from the `resume_time` column, and there's the `last_played_at` column as well.
This SQL query should reset both:
```sql
UPDATE scenes SET resume_time = 0.0, last_played_at = NULL;
```

**Comment by LeGrosFromage** [comment]
That got it, thank you...!

I seem to recall some discussion a while ago about having UX elements to be able to reset/modify those values, did anything come of that?  I wouldn't call it high priority but I can't imagine it would be tremendous effort to implement.

Anyway, thanks all for the help!

**Comment by DingDongSoLong4** [comment]
I think you might be referring to #3922, which is on the v0.23.0 milestone.
