### ISSUE TITLE
[Bug Report] Unable to Save changes to marker in specific situations

### ISSUE THREAD

**Issue by GoldstarZV** [stashapp/stash#3999]
**Describe the bug**
In specific situations, when making changes to a marker, the save button does not enable and so it becomes impossible to save changes to markers. 

The specific situation where this happens is on markers that were created via stash-vr/heresphere, however, it exposes a deeper issue with how marker `seconds` works. The reason that this is happening is because stash-vr/heresphere saves marker `seconds` as a float value, so values can be saved as `482.123`. However, the stash web UI seems to enforce `seconds` value to be int. So when making changes to a marker created in stash-vr/heresphere, the UI does not allow you to save the marker. 

There is a workaround - simply change the time by either manually editing to something else, and then back again to the desired time, or press Up or Down to increment/decrement the time from the UI, and the marker will be fixed

**To Reproduce**
Steps to reproduce the behavior - you can simple create markers through stash-vr/heresphere, however, you can also reproduce the bug manually without VR:

1. Open up stash database file
2. Go into the scene_markers table
3. modify one of your scene_markers seconds field, ordinarily it would be something like 680.0 - change this to something like 680.123 so it doesn't end in .0
4. Write changes
5. Go into stash ui on your browser, navigate to the marker that you just modified
6. Try to add secondary tags/change the name/anything OTHER than changing the time
7. Observe that the Save button is greyed out and you cannot save your changes

**Expected behavior**
The save button should enable itself when changes are made 

**Stash Version: (from Settings -> About):**
v0.21.0-66-g3ea233dc
Build hash: 3ea233dc

**Additional context**
[Discord thread discussion here](https://discord.com/channels/559159668438728723/1136182936807415869)

**Comment by WithoutPants** [comment]
The marker generation code truncates the float value to int, but otherwise using floats seems to be the correct way to go. We name markers based on the truncated value. This bug can be addressed in the UI without requiring any larger underlying changes.
