### ISSUE TITLE
[Bug Report] why doesn't parallel=21 show in the UI?

### ISSUE THREAD

**Issue by sleaze** [stashapp/stash#4021]
Hi,

My server has 46 CPUs, and I set parallel to 21, but it still seems that only a single (or on rare cases, 3) metadata computation jobs are unning at a time.

https://imgur.com/a/0vjInll

What am I missing?

**Comment by DingDongSoLong4** [comment]
Stash only does one job at time, irrespective of the parallel setting. That setting controls the "sub-tasks" when scanning or generating - it means that Stash will be able to generate content for 21 different files simultaneously _within one Generate (or Scan) task_.

You should be able to scroll down a bit in the Task Queue and see that there are multiple "Generating sprites/preview/etc" lines each with a different file.

If you haven't already, you should probably also experiment with the exact parallel number. The generate sub-tasks use `ffmpeg` to do the actual generating, which is already a multithreaded program - so you might be able to max even a 46-core CPU with fewer parallel tasks. If this is the case then fewer tasks will also likely run faster, but definitely verify that with a real-time measurement.

**Comment by sleaze** [comment]
Dear @DingDongSoLong4,

Thank you so much for the quick reply!  This is very informative, I will adjust my API script to submit multiple scene IDs for generation in a single task and see what happens.

Thanks again!

**Comment by sleaze** [comment]
Batching multiple scenes in a job has resolved the performance conundrum.

As a soft request: it would be great if these details were documented and explained in the UI blurb.

Thanks again!

**Comment by DingDongSoLong4** [comment]
Yeah the setting really isn't explained at all in the UI, could definitely do with some improvement there.
