### ISSUE TITLE
[Bug Report] In scenes (haven't checked others), clearing a filter sometimes bring up the filter selection

### ISSUE THREAD

**Issue by twist3dimages** [stashapp/stash#4027]
**Describe the bug**
![image](https://github.com/stashapp/stash/assets/33134502/8688791b-06d0-41d4-97d9-21746b3f1836)
That is my default filter, A lot of the time I click the X and it brings up this menu instead 
![image](https://github.com/stashapp/stash/assets/33134502/b9f78d9b-ef26-446e-9b35-66e6ec75152f)

**To Reproduce**
1. Make sure the filter is applied
2. Click on X
3. Edit filter windows appear
**Expected behavior**
I want the filter to be removed
**Screenshots**
See "Describe the bug"

**Stash Version: (from Settings -> About):**
v0.21.0-79-g2bb04a62
^ It has been doing it for a while though
**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version It's done in every version

**Additional context**
I tried to reproduce it again but didn't have much luck. It may be similar to this issue https://github.com/stashapp/stash/issues/4003

**Comment by twist3dimages** [comment]
I think making the font size bigger especially with bigger monitors would help

**Comment by WithoutPants** [comment]
I suspect that you are clicking the space between the `x` button and the right edge of the badge, which is the same as clicking the body of the badge. I have a simple fix for this to change the click area of the `x` to extend to the right edge of the badge.
