### ISSUE TITLE
[Feature] Scene order within movie

### ISSUE THREAD

**Issue by brokje** [stashapp/stash#403]
Describe the bug
While already putting in the scene order, when you open the movie it is not order on scene number

To Reproduce

Go to 'movies'
Click on 'the movie'
Expected behavior
Order of the scenes

Desktop (please complete the following information):*

OS: Unraid
Browser Chrome
Version v0.1.1-54-g1a6374f

**Comment by Cutters1982** [comment]
I'll add this into the existing issue covering multiple bugs/suggested improvements for the new Movie section:-

https://github.com/stashapp/stash/issues/398

Suggest this issue is perhaps closed, will let you know once I've updated

**Comment by bnkai** [comment]
Added to the relevant issue and closed.
