### ISSUE TITLE
[Bug Report] Always same videos at RECENTLY RELEASED SCENES

### ISSUE THREAD

**Issue by chainnnnn** [stashapp/stash#4048]
On the home page at RECENTLY RELEASED SCENES the same videos are always shown.
I think these are the first ones I added to the library.

RECENTLY ADDED STUDIOS and RECENTLY ADDED PERFORMERS work fine.

**Comment by Maista6969** [comment]
Are you confusing "Recently released scenes" with "Recently added scenes"? Both of these work fine on my system, one shows the scenes sorted by their release date (so the first one is from 2023-08-20) and the other one shows scenes sorted by when I added them to my Stash (so the first one is 2018-09-18)

**Comment by DingDongSoLong4** [comment]
The Recently released scenes tab sorts scenes by their "Date" field - on a scene page, under the Edit tab, it's the 4th field there. If none of your scenes have a date, then it will fall back to sorting by the internal scene ID (the number in the URL when you click on a scene), which means that the scene with the lowest ID (the first one you added) will come first.

You probably want Recently added scenes.

**Comment by chainnnnn** [comment]
Got it! Thank you very much for your help
