### ISSUE TITLE
[Feature] Subtitles in Playback

### ISSUE THREAD

**Issue by peppy6582** [stashapp/stash#4050]
**Is your feature request related to a problem? Please describe.**
There is currently no way to play subtitles while playing back scenes

**Describe the solution you'd like**
A setting option to allow subtitles

**Describe alternatives you've considered**
Using subtitle burn-in

**Comment by Teda1** [comment]
Caption/Subtitle support has been available since version 0.15.0 of Stash. What version are you running?

**Comment by Teda1** [comment]
I'm closing this issue for now since no clarification has been provided about how this feature request differs from the caption/subtitle support added in https://github.com/stashapp/stash/pull/2462. Feel free to reopen this issue with more information if you feel this request differs.
