### ISSUE TITLE
[Feature] Finding scenes by exact name match with ""

### ISSUE THREAD

**Issue by m1048576** [stashapp/stash#4055]
**Is your feature request related to a problem? Please describe.**
Use "" to find scenes by exact name match

**Describe the solution you'd like**
Searching "Big Secret" (with quotation marks) I'd like to get exactly Big Secret scene (not Big Secret and Big Secret 2).

**Comment by scruffynerf** [comment]
then use the Title filter, and not the general filter, and enter Big Secret and select Title IS (which means exactly)

**Comment by m1048576** [comment]
In this situation, this would help solve the gap of the lack of the necessary scene
![Screenshot 2023-10-07 211232](https://github.com/stashapp/stash/assets/143030099/a820b8e9-fc2d-44ca-83a6-923aa2196c76)
