### ISSUE TITLE
[Feature] Scrape data for galleries from scene

### ISSUE THREAD

**Issue by Alice83Git** [stashapp/stash#4056]
**Is your feature request related to a problem? Please describe.**
I have a lot of scenes that have a zip with a gallery associated. The scene is automatically scrapped from StashDb, but the gallery doesn't, and the scrapper for that site don't scrape galleries (for example kink.com).

**Describe the solution you'd like**
Add a button next to Scenes when editing a gallery. When a scene is set and the button is pressed, it get the data from the scene and adds it to the gallery.

**Describe alternatives you've considered**
Manually edit the galleries but it takes too long.

**Comment by LeGrosFromage** [comment]
Go into Galleries
Click on the actual gallery
Edit
Scrape With --> Copy from Scene

Done.

**Comment by Alice83Git** [comment]
Oh, sorry, I didn't notice there was a custom scrapper for that. Thanks!
