### ISSUE TITLE
[Bug Report] Video cropped when full screen on Safari MacOS

### ISSUE THREAD

**Issue by zhgwn** [stashapp/stash#4058]
**Describe the bug**
On Safari (I tested on Firefox and it's good), when a video has dimensions of 1920 × 1080, when going full screen, the right part of the video goes is cropped out of the screen, because the video is enlarged to fill the screen vertically. My screen doesn't have the dimensions matching the video, so the horizontal part on the right is cropped.

**To Reproduce**
1. Get a 1920 × 1080 video
2. Open it fullscreen on Safari
3. You should see the issue, as below (you can compare the watermark at the bottom to the next screenshot):
  <img width="1512" alt="Capture d’écran 2023-08-26 à 03 01 59" src="https://github.com/stashapp/stash/assets/130610452/8ef418eb-4c10-415b-8fef-4daaf05dbecf">

**Expected behavior**
The video should be adapted horizontally, and not getting cropped on the sides, as below, for QuickTime Player:

<img width="1512" alt="Capture d’écran 2023-08-26 à 03 11 23" src="https://github.com/stashapp/stash/assets/130610452/f16bdfaf-4389-4a3c-bd4f-e053381ee8f6">

**Screenshots**
Here is another screenshot of the stash player when not in fullscreen, where it is alright:
<img width="1064" alt="Capture d’écran 2023-08-26 à 03 05 38" src="https://github.com/stashapp/stash/assets/130610452/1766346c-fe40-4620-a29e-4cf12ada0634">

**Stash Version: v0.22.1**

**Desktop (please complete the following information):**
 - OS: MacOS 13.5.1
 - Browser: Safari
 - Version: Version 16.6 (18615.3.12.11.2)

**Comment by NodudeWasTaken** [comment]
I cannot reproduce this using Safari 16.6
