### ISSUE TITLE
[Feature] Autotags based on subfolders

### ISSUE THREAD

**Issue by 1voldermort** [stashapp/stash#407]
**Is your feature request related to a problem? Please describe.**
I can't get the file parser or autotag feature to tag based on my existing folder structure

**Describe the solution you'd like**
An option to parse the path name of the directory as a tag, for example, a file inside /Users/stash/content/tag1/video1.mp4 will have a tag1 whereas /Users/content/tag2/video2.mp4 will have tag2

In some cases the path is recursive and should just list both tags for example
/Users/content/tag3/tag4/video.mp4

**Comment by bnkai** [comment]
doesn't autotag search the whole path already? the tag1 and tag2 examples should work fine , provided you have tag1 and tag2 createdbefore autotagging

**Comment by woodgen** [comment]
I came here to report the same issue and then I retested it. It indeed already works, the auto tagging already takes the full path under consideration, not only the file name. This can be closed imho.
