### ISSUE TITLE
[Bug Report] Issue when filtering by Studio and if missing URL

### ISSUE THREAD

**Issue by LeGrosFromage** [stashapp/stash#4073]
**Describe the bug**
Filtering scenes by Studio works, however the adding a "Is Missing: URL" to the filter results in error.

**To Reproduce**
Select a Studio
Display scenes
On the filter button, add "Is Missing: URL:
See failure

**Expected behavior**
All scenes from chosen studio that do not have a URL associated

**Screenshots**
![image](https://github.com/stashapp/stash/assets/97702146/9e460415-6aab-440e-aef8-27c3cb5d1e42)

Now add the Is Missing: URL...
![image](https://github.com/stashapp/stash/assets/97702146/3183141d-b3fa-4c6e-8ac1-64f1620d42f7)

(Same thing happens with other studios)

**Stash Version: (from Settings -> About):**
v0.22.1
Build hash:
113f0b7d

**Desktop (please complete the following information):**
 - OS: Linux, Mac
 - Browser: Vivaldi, Firefox
 - Version: Latest Vivaldi (6.1.3035.302) Latest Firefox (117)

**Smartphone (please complete the following information):**
NA

**Comment by DingDongSoLong4** [comment]
This has come up before, and is a bug introduced by #3852.

That filter should be removed/deprecated anyway - the `URL is null` filter does the same job and works correctly.

**Comment by LeGrosFromage** [comment]
Fair enough.  Hadn't realised it had been mentioned before.    Never thought to use the Null option - my mind just goes to url is missing, not that url is null.  But point taken.

Thanks for the info!
