### ISSUE TITLE
[Bug Report] Migration failed trying to update database schema 49

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#4076]
**Describe the bug**
Updated Stash to latest develop build. Migration to schema 49 fails.

_An error occurred migrating the database to the latest schema version. The backup database file was automatically renamed to restore the database.
error performing migration: running post migrations for schema version 49: failed to get object filter for saved filter 32: failed to adjust criterion value for "height_cm": strconv.ParseInt: parsing "": invalid syntax_

**To Reproduce**
1. Execute Stash  v0.22.1-15-gc364346a - Official Build - 2023-09-01 00:55:45
2. Database migration fails

**Stash Version: (from Settings -> About):**
v0.22.1-15-gc364346a - Official Build - 2023-09-01 00:55:45

**Comment by yoshnopa** [comment]
I think I know the issue. Do you have a saved filter including height is null or height is not null?

**Comment by yoshnopa** [comment]
Very likely this commit will fix it, would you kindly test the binary?
https://github.com/stashapp/stash/actions/runs/6046955457?pr=4078

**Comment by ghfsa** [comment]
> Very likely this commit will fix it, would you kindly test the binary? https://github.com/stashapp/stash/actions/runs/6046955457?pr=4078

Hi!, different user here. This doesn't fix the failed migration for me.
The message I get is:

>error performing migration: running post migrations for schema version 49: failed to get object filter for saved filter 58: failed to adjust criterion value for "duration": could not recognize format of value 3600

**Comment by yoshnopa** [comment]
Similar reason for while this slipped through, but different error, thanks for making me aware. I think I can add the fix to the commit.

**Comment by yoshnopa** [comment]
This one may solve your problems @ghfsa 
https://github.com/stashapp/stash/actions/runs/6047891288?pr=4078

**Comment by ghfsa** [comment]
> Similar reason for while this slipped through, but different error, thanks for making me aware. I think I can add the fix to the commit.
> 
> Edit: Cannot replicate it myself, but I will make the fix anyway as there is no real issue with this being redundant, and it may very well be the solution.

The pre-release just before your's had '`hh:mm:ss`' (filter hint) for filter duration, wheres this latest has '`duration`' in seconds.

Could it be the reason? Also I think `hh:mm:ss` is better?

**Comment by yoshnopa** [comment]
That part was not done by me, but it may be due to the inconsistency with other values. The refactor aimed at streamlining different formats, so that the possible parameters are more consistent. 
Whether this format may be less useful may be something to discuss in discord I think.

However, I don't think it was the reason, as the error was in regard to the migration, which is only related to the database, and as you've retrieved, the value there was already 3600.

**Comment by MC1R-13** [comment]
I just got a similar error for an old filter with 'height excludes feet'

`error performing migration: running post migrations for schema version 49: failed to get object filter for saved filter 1: failed to adjust criterion value for \"height_cm\": strconv.ParseInt: parsing \"feet\": invalid syntax"`

Deleting the filter fixed it.
