### ISSUE TITLE
[RFC] Implementing optimal methods of rating items

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#4082]
### Scope
The scope of this proposal is meant to provide suggestions to mitigate the laborious process of rating items. This will include rating items from the (1) details pages (where a details page is defined as _localhost:9999/scenes/n; localhost:9999/images/n; localhost:9999/galleries/n_), and (2) the cards grid view.

The proposed mechanism should be extensible, that is it won't be relegated to one use but can accommodate multiple features, and the mechanism will not add clutter to the UI, but rather help to reduce clutter.

##  Long Form
Efficiently rating items can be a laborious process. We can implement two mechanisms to improve the process:

### Mechanism 1: Interactive rating stars on details pages

Performer and movies details pages already have interactive rating stars. These pages do not require the user to navigate to the edit tab to modify a rating. The other ratings pages (scenes, images, galleries, etc) can be updated to reflect the interactive rating stars behavior.

_There may already be a feature request for this or it may be on the roadmap but I may have missed it._

### Mechanism 2: Overflow menu on each card on grid view pages

Presently it is not possible to rate an object (scene, movie, performer, image, gallery, etc) from the grid view pages. The user must navigate to the details pages which is a four-step process, not including navigating back out to the grid view page.

To streamline and optimize this process we alter the UI in the following way:

1. Replace the grid card checkbox with an overflow menu (universally an icon with three vertical dots)
2. Add grid card exclusive items to the overflow menu:
    - Select/Unslect (the incument checkbox functionality)
    - Ratings sub-menu
    - Any other relevant requested features, now or in the future, such as
      - Favorite/unfavorite
      - Organize/unorganize
      - Delete

**How does it function?**

- User hovers over the grid view item
- User clicks overflow menu icon to reveal a standard context menu of options
- Context menu can contain nested menu for items with multiple options, such as a rating menu

**Advantages**

Minimizes clutter: The proposed mechanism integrates seamlessly into the existing card grid view UI without introducing more visual buttons, and provides a mechanism to add more grid card related features without incurring more buttons.

Minimal alteration to existing functionality: Existing behavior of the checkbox remains the same only introducing an additional click to access it within the overflow menu. The behavior of selecting/unselecting additional cards (clicking anywhere on the card image) would remain the same.

Extensible: This solution is designed within an intuitive framework that accommodates current and future features accessible from the grid view card.

## Examples

_Hovering over the card reveals the overflow menu icon_
![Screenshot 2023-09-02 190632](https://github.com/stashapp/stash/assets/37937507/93657cf5-5f64-47a6-8ddc-f36e42f0178b)

_Clicking the overflow button reveals the options, including the nested ratings menu_
![image](https://github.com/stashapp/stash/assets/37937507/d7733b11-7787-4b1e-b27f-a27e9a1fc4dd)

**Comment by DingDongSoLong4** [comment]
I'd have to say I don't like the overflow menu on the cards. It makes it much more difficult to select multiple cards, and you don't get nice visual feedback on which cards are selected and which aren't. The double dropdown to change the rating is also quite clunky imo. At that point, just clicking the card to open the object page and rating it from there (using Mechanism 1, which I 100% agree with) is easier and faster.

I know you don't like adding more buttons, but I honestly think that if you really want to add a rating control to the card, only way is to add an interactive star control (like what is on the performer or movie details pages) to the card itself. Perhaps it could only be shown at larger zoom settings, to avoid clutter.

For the other features that could go in the dropdown:
- Favorite/unfavorite: this is only available on performers, and there's already a heart "button" that does this.
- Organize/unorganize: valid, and it's a good fit for a dropdown. Although I'm not sure how common the use-case of wanting to mark a single scene as organized/unorganized directly from the card is.
- Delete: definitely the most useful to be able to do from the card, and also fits with the dropdown. It would then be the same number of clicks as selecting a single card and clicking the delete button at the top though, only without having to scroll to the top.

If we could put the dropdown menu in the top right corner that would be the best, but the Studio link is already there. Any other corners of the card would probably look strange with a dropdown menu in them, but I can't say for certain.

I think first prioritizing Mechanism 1 is most important, and then we can reevaluate and see whether changing the rating directly from the card is necessary.

**Comment by echo6ix** [comment]
@DingDongSoLong4 

> I know you don't like adding more buttons, but I honestly think that if you really want to add a rating control to the card, only way is to add an interactive star control (like what is on the performer or movie details pages) to the card itself

That's a feasible option. I don't think interactive rating stars on the ***bottom left*** of a grid card would look bad.

When hovering over a card there are three areas that are already occupied:
1. Top left
Globally used for checkbox selection
2. Top right
Scene grid cards (studio hotlink)
Performer grid cards (favorite button, country hotlink)
3. Center
Image grid cards (full screen image button)

_Scene grid card - not much going on when hovering other than the checkbox_
![image](https://github.com/stashapp/stash/assets/37937507/d3c6e989-3df1-424c-ba63-85c9f46b99f7)

_Performer grid card (using custom css) - not much going on here when hovering other than the top of the card_
![image](https://github.com/stashapp/stash/assets/37937507/7695d937-7ad5-434b-a15a-70e83c466da5)

---

> If we could put the dropdown menu in the top right corner that would be the best, but the Studio link is already there. Any other corners of the card would probably look strange with a dropdown menu in them, but I can't say for certain.

I agree. Though another option is:
- Move the select/unselect checkbox to the *bottom left*
- Put overflow menu in the *top left*

---

> For the other features that could go in the dropdown [...] Favorite/unfavorite: this is only available on performers

Agreed, it's redundant for performers, but a handful of people have requested a favorite/unfavorite option for scenes (maybe even for images, idk). It was meant as an example that these features would start to crowd the grid cards but could all neatly be consolidated in an overflow menu.

**Comment by echo6ix** [comment]
### Mobile view

One aspect I forgot to consider is the mobile UI. While related to the topic it veers into a broader issue.

Accessing the select/unselect checkbox on mobile is very clunky. It requires a bit of long-press on the desired grid card, but in my experience this is a struggle. Sometimes it will cause the browser context menu to appear, and sometimes trying to summon the checkbox results in an inadvertent navigation to the scene details page. People interact with a finger differently than a mouse, which I think makes the hidden checkbox less intuitive for mobile views.

Therefore if the checkbox is clunky on mobile, it follows that interactive rating stars and an overflow menu would suffer from the same issues.

Possible solution: For mobile view only, an always viewable overflow menu icon on cards. But where to locate on the card? There should definitely be a consistent location between mobile and desktop views.

- Bottom left. An unutilized area for all cards, but it's an awkward placement.
- Top left. A conventional placement, but comes at the expense of the rating banner. The rating banner would require relocation, but where?
  - Rating banner moves to the bottom-left, and maybe gets a bit of a facelift (refer to rating-banner presentation on my Bill Gates screenshot and imagine it relocated to the bottom-left)

**Comment by echo6ix** [comment]
Fleshing out possible contents of a global card overflow menu

- Select/Unselect
- Set as organized/Unset organized _(applicable to scenes, images, and gallery cards)_
- Favorite/Unfavorite _(applicable to performer cards)_
- Metadata submenu flyout
  - _Populates item metadata into a flyout submenu for quick access_
  - _Items could be clicked for quick navigation_
  - _Metadata fields would differ based on type of card (scene, image, gallery, movie, performer, etc)
- Rate submenu flyout _(applicable to images, scenes, performers)_
- Edit
  - _Quick navigation to details edit tab_
- Delete

![image](https://github.com/stashapp/stash/assets/37937507/7f4b2946-b1c6-4dd9-9464-5b344b0a4baf)

#### Objections
The metadata submenu has redundant elements

#### Answer
Yes, but it affords people the ability to hide similar card elements with custom css, yet maintain access to the info with zero visual load to the cards

**Comment by echo6ix** [comment]
@DingDongSoLong4 

> I'd have to say I don't like the overflow menu on the cards. It makes it much more difficult to select multiple cards

It's true adding the select option to an overflow menu increases the initial click by one, however selecting subsequent cards would remain the same because you can currently click anywhere on the card.

For desktop browsers the use keyboard combos can be explored (regardless of an overflow menu), such `CTRL+LEFT CURSOR` and `CTRL+RIGHT CURSOR` to optimize multiple card selections.

> and you don't get nice visual feedback on which cards are selected and which aren't

This can be addressed the same way file managers do and mobile apps do it. Highlighting selected cards with a distinct border color

![image](https://github.com/stashapp/stash/assets/37937507/764b44ff-e0d6-4b89-a703-b42b252eea6c)

**Comment by QxxxGit** [comment]
For what it's worth, I think the tools we have now work okay for rating media. Maybe some folks can find some use.

For images, I apply a filter for `rating is null`, open an image in the lightbox, rate it, and it automatically goes to the next image. It's super quick. No extra hovering or clicking. This works for grid or wall view.

For scenes, I enable the queue, then rate and save. Once the video ends, the next begins and I rate it. It's not laborious in my opinion. For me personally, it makes sense to only rate something after just watching it.

**Comment by echo6ix** [comment]
>  feels weird rating something without actually viewing it, but I'm sure others do just that.

I agree, I think rating a scene from the grid page would be rare. But per the scope I was shooting for a global implementation of all grid cards views including images, performers, scenes, tags, studios, etc. Some obviously don't have rating capability now but they could in the future.

> I do think the overflow menu looks a bit weird on the left, overflow buttons just feel more suited to the right imo, but unless we move the studio logo that is basically the only option.

Agreed.

> Overflow menus are usually for actions, not for displaying data. I think the only item under metadata in your mockup that fits an overflow menu is the StashID button - I can see why you'd want to go directly to a scene's page on StashDB, for example. We'd just need to remember to take into account the fact that one scene can have multiple StashIDs.

This is me coming from a world of specific niche apps where the context menu is king. You may very well be correct that using an overflow menu like that is unorthodox. 

> what if you have your rating system set to decimal instead of stars?

I've never used the alternate rating system. I assumed it only introduced half stars, making it a total of ten possible digits. But now that I look it can use tenths.

I guess the last point ultimately blows the overflow menu option out of the water for ratings. 😅

I appreciate the discussion though, it was fun brainstorming, receiving feedback, and addressing it. Thank you.

**Comment by DingDongSoLong4** [comment]
> Toggle Organized status
Delete scene
Edit scene

I think these three actions are probably the ones that make the most sense to go into a dropdown menu, along with favorite (where that applies). Personally I would probably only use "Delete", but the others are definitely useful.

For mobile devices, I think we've basically solved that - add "Select" as a dropdown option, replace the checkbox with the three dots, and make sure it is always shown (ie without needing a hover) on mobile. The cards can be highlighted as discussed to indicate selection, and after one selection is made then just clicking/tapping another card will also select it.

On desktop, the three dots would only show on hover, and right-clicking can also bring up the menu.

This is all just for convenience, but I agree it would definitely be useful.

**Comment by LeGrosFromage** [comment]
If there's a workable UX to the mobile issue, great - less hurdles before implementation are good thing :-)  I hardly use Stash on a mobile device so my thoughts just go with being in a browser on a desktop.

Can I also offer a thought here about the 3-dots menu?  I agree with an earlier comment that the 3-dots does seem to flow better when it's in the top-right corner of a card, but as pointed out that clashes with the studio name.  Now personally I don't care for having the studio name on the scene card - I've clicked it by accident far too many times when just trying to open a scene - so, would there be a huge pushback from the userbase to remove the studio from the scene card?   Or would a fair compromise to be moving studio to the top middle?

(Apologies for morphing this discussion from ratings to context menus - not my intention, I just find conversations like this quite fascinating.)

**Comment by DingDongSoLong4** [comment]
I think moving the studio to the top middle would be even more strange than having dots on the left - if we move the studio it would have to go either in the top left or way down below, in the card body itself. Moving it down does mean that the cards will have to be made bigger though.

I don't think removing the studio entirely will go down well - it's fairly important info and I definitely think it needs to be shown on the card somewhere.
