### ISSUE TITLE
[Bug Report] Can't filter by rating anymore

### ISSUE THREAD

**Issue by Strichcod3** [stashapp/stash#4095]
**Describe the bug**
The filter by rating is broken since one of the last updates.

**To Reproduce**
Open Scenes page and select filter "rating"/"Wertung"/"rating100":
?c=("type":"rating100","value":("value":1),"modifier":"EQUALS")&sortby=path
I've tried several filter settings like "equals 1" or smaller than 2, but the collection is empty or shows all scenes although there are scenes with a rating of 1.

**Expected behavior**
Like before, the filter ?c=("type":"rating100","value":("value":1),"modifier":"EQUALS")&sortby=path should only show scenes with a rating of 1
**Screenshots**
If applicable, add screenshots to help explain your problem please ensure that your screenshots are SFW or at least appropriately censored.

**Stash Version: v0.22.1-18-g50c4ac98

**Desktop (please complete the following information):**
 - OS: Stash in docker, browsers on Windows 10
 - Browser Firefox, Chrome
 - Version both up to date.

**Comment by DingDongSoLong4** [comment]
This should be fixed by #4090.
