### ISSUE TITLE
[Feature] Producer and Studio

### ISSUE THREAD

**Issue by brokje** [stashapp/stash#410]
**Is your feature request related to a problem? Please describe.**
What I miss is the Producer, e.g. brazzers or naughty america in combination with the studio e.g. Dirty Masseur and My First Sex Teacher

**Describe the solution you'd like**
Extra Tab with Producer

**Comment by seducingbits** [comment]
Is this solved with the parent/child relationship of studios?

**Comment by brokje** [comment]
Yeah almost! Geest :). Only in movies is missing, brazzers, and a Day with a p0rnstar
