### ISSUE TITLE
[Bug Report] HEVC videos play/transcode, but won't generate previews or sprites

### ISSUE THREAD

**Issue by cpm761** [stashapp/stash#4124]
**Describe the bug**
While most video files will generate sprites/previews/etc when scanned, they won't generate for my HEVC videos. I've created these videos using HandBrake and playback/transcoding through stash works fine. Interestingly other HEVC videos I didn't transcode this way myself will generate. Logs are reporting PPS/SPS/VPS errors, is there a fix for this or a way to edit my video files without transcoding all of them again?

**To Reproduce**
Tasks - Generate in a library with affected videos
Tasks completes but thumbnail is still empty
Log shows this error -
023-09-14 13:58:31Info    scanning 1 paths
2023-09-14 13:41:33Info    Generate finished (2.355971458s)
2023-09-14 13:41:33Error   command stderr: [hevc @ 0x5606f7b10500] VPS 0 does not exist
[hevc @ 0x5606f7b10500] SPS 0 does not exist.
[hevc @ 0x5606f7b4c5c0] VPS 0 does not exist
[hevc @ 0x5606f7b4c5c0] SPS 0 does not exist.
[hevc @ 0x5606f7b4c5c0] PPS id out of range: 0
[hevc @ 0x5606f7b54c40] PPS id out of range: 0
[hevc @ 0x5606f7bf0bc0] PPS id out of range: 0
[hevc @ 0x5606f7ce6a80] PPS id out of range: 0
Error while decoding stream #0:0: Invalid data found when processing input
[hevc @ 0x5606f7c370c0] PPS id out of range: 0
Error while decoding stream #0:0: Invalid data found when processing input
[hevc @ 0x5606f7b4c5c0] PPS id out of range: 0
Error while decoding stream #0:0: Invalid data found when processing input
[hevc @ 0x5606f7b54c40] PPS id out of range: 0
(repeats for hundreds of lines)

**Expected behavior**
previews/sprites should generate correctly

**Stash Version: (from Settings -> About):**
0.22.0

**Comment by cpm761** [comment]
Just found this in the logs too - 
Error generating screenshot: error running ffmpeg command <-v error -y -ss 299.37600000000003 -i (my input).mp4 -frames:v 1 -q:v 2 -f image2 (my output).jpg>: exit status 69

I took the same ffmpeg file from the stash directory and ran the same command on the same video outside of stash and it generated a thumbnail fine, so it doesn't seem to be an ffmpeg bug.

**Comment by DingDongSoLong4** [comment]
@cpm761 Are you using the same `ffmpeg` as stash is using - is there an ffmpeg binary in your config file directory? Are you on Windows or Linux?

**Comment by cpm761** [comment]
@DingDongSoLong4 Yeah, using the same ffmpeg that stash comes with but I also tried different random versions too, also running on Linux.

**Comment by cpm761** [comment]
Installed stash on a different newer Linux system and the logs show the exact same error, but sometimes it will generate the hover preview, sometimes not. Neither will generate the preview cover/thumbnail. Running the error'd command outside of stash will generate them.

**Comment by DingDongSoLong4** [comment]
@cpm761 Would you be able to transcode and share a video that exhibits this behaviour? Any short sample video is fine, something like [these](https://file-examples.com/index.php/sample-video-files/sample-mp4-files/) perhaps.

The easiest would be to share the file on the Discord server, but here on Github is also fine.

**Comment by cpm761** [comment]
@DingDongSoLong4 Here's a test file, encoded the with the same settings as the other videos and gives the same errors.

https://github.com/stashapp/stash/assets/133815390/7c42eaa8-cfbe-4c02-9bda-3aa4a82d1882

**Comment by DingDongSoLong4** [comment]
If you run `ffprobe test.mp4`, what is the output? If I run that using ffprobe version 6.0, it gives me `VPS/SPS 0 does not exist` errors.

**Comment by cpm761** [comment]
Got both of the same results here. I'm aware those errors occur (not sure why) but they play back fine. When running those scripts above outside of stash with the same ffmpeg file, those errors pop up too but it still produces an output file anyway. So it seems like ffmpeg standalone is catching these errors but continues anyway, but stash catches the error and fails outright?

**Comment by cpm761** [comment]
The 2 scripts that fail in stash still output these valid files outside of it. They still report;
[hevc @ 000002746737c280] VPS 0 does not exist
[hevc @ 000002746737c280] SPS 0 does not exist.
but give an output anyway, so I think they're non-fatal?

https://github.com/stashapp/stash/assets/133815390/9a2dcb5b-ade1-4fd0-9c38-d0bd28682556

![output](https://github.com/stashapp/stash/assets/133815390/368c2a1c-0931-4497-9be3-98bec88c02f3)

**Comment by DingDongSoLong4** [comment]
When I run `ffmpeg -v error -y -ss 104.74000000000001 -i test.mp4 -ss 20 -t 0.75 -max_muxing_queue_size 102 4 -c:v libx264 -vf scale=640:-2 -pix_fmt yuv420p -profile:v high -level 4.2 -preset slow -crf 21 -threads 4 -strict -2 -an output.mp4`, it does produce an output file, but it's a broken 261 byte file. `ffmpeg -v error -y -ss 299.37600000000003 -i test.mp4 -frames:v 1 -q:v 2 -f image2 output.jpg` doesn't produce any output file at all.

I'm trying to figure out what the error actually means, and the only lead I can find so far is https://github.com/shaka-project/shaka-packager/issues/297.

Video players in general try their best to ignore errors and continue playing - they will only fail/crash when the file is really broken. `ffmpeg` will usually error earlier, which I think is sensible in this case - you usually don't want to generate using files which are broken.

**Comment by DingDongSoLong4** [comment]
Can you post the output of `ffmpeg`?

**Comment by cpm761** [comment]
My 2 scripts read a bit differently to yours, I used;
/home/deck/Downloads/ffmpeg -i /home/deck/Downloads/test.mp4 -ss 20 -t 0.75 -max_muxing_queue_size 1024 -c:v libx264 -vf scale=640:-2 -pix_fmt yuv420p -profile:v high -level 4.2 -preset slow -crf 21 -threads 4 -strict -2 -an /home/deck/Downloads/output.mp4
/home/deck/Downloads/ffmpeg -i /home/deck/Downloads/test.mp4 -frames:v 1 -q:v 2 -f image2 /home/deck/Downloads/output.jpg

Here's my result with working output. 

(deck@steamdeck ~)$ /home/deck/Downloads/ffmpeg -i /home/deck/Downloads/test.mp4 -ss 20 -t 0.75 -max_muxing_queue_size 1024 -c:v libx264 -vf scale=640:-2 -pix_fmt yuv420p -profile:v high -level 4.2 -preset slow -crf 21 -threads 4 -strict -2 -an /home/deck/Downloads/output.mp4

/home/deck/Downloads/ffmpeg -i /home/deck/Downloads/test.mp4 -frames:v 1 -q:v 2 -f image2 /home/deck/Downloads/output.jpg
ffmpeg version 4.2.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[hevc @ 0x688a340] VPS 0 does not exist
[hevc @ 0x688a340] SPS 0 does not exist.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/deck/Downloads/test.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 512
    compatible_brands: mp42iso2mp41
    creation_time   : 2023-09-14T19:46:05.000000Z
    encoder         : HandBrake 1.5.1 2022011000
  Duration: 00:01:26.05, start: 0.000000, bitrate: 231 kb/s
    Stream #0:0(und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709/reserved/bt709), 648x648 [SAR 1:1 DAR 1:1], 188 kb/s, 30 fps, 30 tbr, 90k tbn, 30 tbc (default)
    Metadata:
      creation_time   : 2023-09-14T19:46:05.000000Z
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 36 kb/s (default)
    Metadata:
      creation_time   : 2023-09-14T19:46:05.000000Z
      handler_name    : Mono
[hevc @ 0x6891140] VPS 0 does not exist
[hevc @ 0x6891140] SPS 0 does not exist.
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x688e740] using SAR=1/1
[libx264 @ 0x688e740] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x688e740] profile Progressive High, level 4.2, 4:2:0, 8-bit
[libx264 @ 0x688e740] 264 - core 157 r2969 d4099dd - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=5 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=8 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=2 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=4 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=3 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=50 rc=crf mbtree=1 crf=21.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/home/deck/Downloads/output.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 512
    compatible_brands: mp42iso2mp41
    encoder         : Lavf58.29.100
    Stream #0:0(und): Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 640x640 [SAR 1:1 DAR 1:1], q=-1--1, 30 fps, 15360 tbn, 30 tbc (default)
    Metadata:
      creation_time   : 2023-09-14T19:46:05.000000Z
      handler_name    : VideoHandler
      encoder         : Lavc58.54.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
frame=   23 fps=0.0 q=-1.0 Lsize=      14kB time=00:00:00.66 bitrate= 169.0kbits/s speed=0.867x
video:13kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 8.641309%
[libx264 @ 0x688e740] frame I:1     Avg QP:18.60  size:  7917
[libx264 @ 0x688e740] frame P:7     Avg QP:18.77  size:   405
[libx264 @ 0x688e740] frame B:15    Avg QP:18.03  size:   101
[libx264 @ 0x688e740] consecutive B-frames: 13.0%  0.0%  0.0% 87.0%
[libx264 @ 0x688e740] mb I  I16..4:  7.9% 73.7% 18.4%
[libx264 @ 0x688e740] mb P  I16..4:  0.3%  0.3%  0.2%  P16..4:  2.6%  0.7%  0.2%  0.0%  0.0%    skip:95.7%
[libx264 @ 0x688e740] mb B  I16..4:  0.1%  0.1%  0.0%  B16..8:  1.6%  0.2%  0.0%  direct: 0.0%  skip:98.0%  L0:46.1% L1:47.9% BI: 6.1%
[libx264 @ 0x688e740] 8x8 transform intra:71.2% inter:13.6%
[libx264 @ 0x688e740] direct mvs  spatial:80.0% temporal:20.0%
[libx264 @ 0x688e740] coded y,uvDC,uvAC intra: 11.3% 0.0% 0.0% inter: 0.2% 0.0% 0.0%
[libx264 @ 0x688e740] i16 v,h,dc,p: 44% 45% 11%  0%
[libx264 @ 0x688e740] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 78%  6% 15%  0%  0%  0%  0%  0%  0%
[libx264 @ 0x688e740] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 44% 18% 16%  5%  4%  4%  3%  3%  2%
[libx264 @ 0x688e740] i8c dc,h,v,p: 100%  0%  0%  0%
[libx264 @ 0x688e740] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x688e740] ref P L0: 86.7%  2.4%  9.1%  1.5%  0.3%
[libx264 @ 0x688e740] ref B L0: 71.6% 20.8%  5.9%  1.7%
[libx264 @ 0x688e740] ref B L1: 97.2%  2.8%
[libx264 @ 0x688e740] kb/s:128.06
ffmpeg version 4.2.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[hevc @ 0x6b571c0] VPS 0 does not exist
[hevc @ 0x6b571c0] SPS 0 does not exist.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/deck/Downloads/test.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 512
    compatible_brands: mp42iso2mp41
    creation_time   : 2023-09-14T19:46:05.000000Z
    encoder         : HandBrake 1.5.1 2022011000
  Duration: 00:01:26.05, start: 0.000000, bitrate: 231 kb/s
    Stream #0:0(und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709/reserved/bt709), 648x648 [SAR 1:1 DAR 1:1], 188 kb/s, 30 fps, 30 tbr, 90k tbn, 30 tbc (default)
    Metadata:
      creation_time   : 2023-09-14T19:46:05.000000Z
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 36 kb/s (default)
    Metadata:
      creation_time   : 2023-09-14T19:46:05.000000Z
      handler_name    : Mono
[hevc @ 0x6b731c0] VPS 0 does not exist
[hevc @ 0x6b731c0] SPS 0 does not exist.
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> mjpeg (native))
Press [q] to stop, [?] for help
[swscaler @ 0x6dca080] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to '/home/deck/Downloads/output.jpg':
  Metadata:
    major_brand     : mp42
    minor_version   : 512
    compatible_brands: mp42iso2mp41
    encoder         : Lavf58.29.100
    Stream #0:0(und): Video: mjpeg, yuvj420p(pc), 648x648 [SAR 1:1 DAR 1:1], q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      creation_time   : 2023-09-14T19:46:05.000000Z
      handler_name    : VideoHandler
      encoder         : Lavc58.54.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
frame=    1 fps=0.0 q=2.0 Lsize=N/A time=00:00:00.03 bitrate=N/A speed=2.04x
video:6kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

**Comment by DingDongSoLong4** [comment]
Okay yes that does work for me now, but you've removed the `-ss 104.74000000000001` which is what seeks to a specific time in the input video. If you run _exactly_ this: `/home/deck/Downloads/ffmpeg -y -ss 104.74000000000001 -i /home/deck/Downloads/test.mp4 -ss 20 -t 0.75 -max_muxing_queue_size 102 4 -c:v libx264 -vf scale=640:-2 -pix_fmt yuv420p -profile:v high -level 4.2 -preset slow -crf 21 -threads 4 -strict -2 -an /home/deck/Downloads/output.mp4`, does it give an output?

**Comment by DingDongSoLong4** [comment]
Basically there's something wrong with your encoder, and it's generating broken files. I'm not too knowledgeable on that kind of thing, so I can't really help with fixing that, but I don't think it's something that Stash is able to work around. Unfortunately that means you'll probably need to re-encode all the problematic files.

**Comment by cpm761** [comment]
Woah, I've just hit a bit of a solution! I'm not sure how to implement it though. The problem seems to be the -ss flag running _before_ the -i flag. Here's a before/after - 
/home/deck/Downloads/ffmpeg -y -ss 60 -i /home/deck/Downloads/test.mp4 -ss 20 -t 0.75 -max_muxing_queue_size 102 -c:v libx264 -vf scale=640:-2 -pix_fmt yuv420p -profile:v high -level 4.2 -preset slow -crf 21 -threads 4 -strict -2 -an /home/deck/Downloads/output.mp4 **Not working**

/home/deck/Downloads/ffmpeg -y -i /home/deck/Downloads/test.mp4 -ss 60 -ss 20 -t 0.75 -max_muxing_queue_size 102 -c:v libx264 -vf scale=640:-2 -pix_fmt yuv420p -profile:v high -level 4.2 -preset slow -crf 21 -threads 4 -strict -2 -an /home/deck/Downloads/output.mp4 **Working**

/home/deck/Downloads/ffmpeg -y -ss 20 -i /home/deck/Downloads/test.mp4 -frames:v 1 -q:v 2 -f image2 /home/deck/Downloads/output.jpg **Not working**

/home/deck/Downloads/ffmpeg -y -i /home/deck/Downloads/test.mp4 -ss 20 -frames:v 1 -q:v 2 -f image2 /home/deck/Downloads/output.jpg **Working**

Would you mind testing this yourself?

**Comment by DingDongSoLong4** [comment]
In ffmpeg, the order of the flags makes a difference. If you put `-ss` after the input file, then it will seek through the entire input file, frame by frame, until it gets to where it needs to be. If `-ss` is before the input file, then it seeks using keyframes, which is significantly faster. There's an explanation from the ffmpeg docs [here](https://trac.ffmpeg.org/wiki/Seeking).

Stash already does a combination of fast/slow seek for previews if any error occurs during the initial attempt, which only uses fast seek. This happened here, which is why there is an `-ss` before and after the `-i`.

We could change this to only use slow seek, which would fix your issue, but it's going to make generation a whole lot slower. The reason why this was added is because ffmpeg doesn't seem to fast seek accurately with AVI/WMV files, and using a combination prevents artifacts in the output. @WithoutPants would have to weigh in here, but I don't think it is worth the speed sacrifice just to be able to process videos which are broken anyway.

I'm assuming that you either aren't able to or aren't willing to re-encode the videos - because the best solution is to fix the problem at the source and stop your encoder from generating broken files. If you're happy to build stash yourself, I can send through a change here which would use only slow seeking, which then should generate successfully.

**Comment by cpm761** [comment]
Aw, I thought I figured it out lol. But thanks for finally narrowing it down! I should be able to build it with your fix. The speed sacrifice might still outweigh weeks worth of re-encodes, plus I can wait since I have stash running on a NAS. If you could implement it I'd greatly appreciate it, thank you so much for the assistance so far!

**Comment by cpm761** [comment]
Another idea - I could live without animated previews but thumbnails are a must. If slow seeking has to be used, could a thumbnail be generated early on?

**Comment by DingDongSoLong4** [comment]
Alright the attached change will make it so that it will always use slow seeking for previews, screenshots and sprites:
```diff
diff --git a/pkg/ffmpeg/transcoder/screenshot.go b/pkg/ffmpeg/transcoder/screenshot.go
index a1ddef6b6..ddd9c02e6 100644
--- a/pkg/ffmpeg/transcoder/screenshot.go
+++ b/pkg/ffmpeg/transcoder/screenshot.go
@@ -56,9 +56,9 @@ func ScreenshotTime(input string, t float64, options ScreenshotOptions) ffmpeg.A
 	var args ffmpeg.Args
 	args = args.LogLevel(options.Verbosity)
 	args = args.Overwrite()
-	args = args.Seek(t)
 
 	args = args.Input(input)
+	args = args.Seek(t)
 	args = args.VideoFrames(1)
 
 	if options.Quality > 0 {
diff --git a/pkg/ffmpeg/transcoder/transcode.go b/pkg/ffmpeg/transcoder/transcode.go
index 3a2d6a554..cb1586e5d 100644
--- a/pkg/ffmpeg/transcoder/transcode.go
+++ b/pkg/ffmpeg/transcoder/transcode.go
@@ -37,31 +37,6 @@ func (o *TranscodeOptions) setDefaults() {
 func Transcode(input string, options TranscodeOptions) ffmpeg.Args {
 	options.setDefaults()
 
-	// TODO - this should probably be generalised and applied to all operations. Need to verify impact on phash algorithm.
-	const fallbackMinSlowSeek = 20.0
-
-	var fastSeek float64
-	var slowSeek float64
-
-	if !options.SlowSeek {
-		fastSeek = options.StartTime
-		slowSeek = 0
-	} else {
-		// In slowseek mode, try a combination of fast/slow seek instead of just fastseek
-		// Commonly with avi/wmv ffmpeg doesn't seem to always predict the right start point to begin decoding when
-		// using fast seek. If you force ffmpeg to decode more, it avoids the "blocky green artifact" issue.
-		if options.StartTime > fallbackMinSlowSeek {
-			// Handle seeks longer than fallbackMinSlowSeek with fast/slow seeks
-			// Allow for at least fallbackMinSlowSeek seconds of slow seek
-			fastSeek = options.StartTime - fallbackMinSlowSeek
-			slowSeek = fallbackMinSlowSeek
-		} else {
-			// Handle seeks shorter than fallbackMinSlowSeek with only slow seeks.
-			slowSeek = options.StartTime
-			fastSeek = 0
-		}
-	}
-
 	var args ffmpeg.Args
 	args = args.LogLevel(options.Verbosity).Overwrite()
 	args = append(args, options.ExtraInputArgs...)
@@ -70,15 +45,9 @@ func Transcode(input string, options TranscodeOptions) ffmpeg.Args {
 		args = args.XError()
 	}
 
-	if fastSeek > 0 {
-		args = args.Seek(fastSeek)
-	}
-
 	args = args.Input(input)
 
-	if slowSeek > 0 {
-		args = args.Seek(slowSeek)
-	}
+	args = args.Seek(options.StartTime)
 
 	if options.Duration > 0 {
 		args = args.Duration(options.Duration)
```

(in other words, only use this for the broken files, and go back to normal stash afterwards)

To apply the changes: 
- clone the stash repository
- switch to the version v0.22.0 tag by using `git switch --detach v0.22.0`
- copy those changes to a file called `changes.diff` inside the repository
- and then run `git apply changes.diff` to apply the changes
- then build using `make`

I haven't tested this myself, so test it on a single file first and see if everything worked correctly before using it on multiple files.

**Comment by cpm761** [comment]
Thank you! I'll give it a go tomorrow.

**Comment by cpm761** [comment]
It works now! But definitely slower as you said. I'll still take that over no generations at all. Thanks for looking into it for me!

**Comment by ninevolt04621** [comment]
@DingDongSoLong4 apologies for bringing this up a year later, but i just wanted to add some relevant context. PPS/SPS/VPS errors are quite common when recording streaming video, e.g. when a keyframe is not the first data received, and not strictly indicative of a broken encoder. while i agree that the best course of action in this case would be to fix these videos before indexing them in stash, there are situations in which this may not be feasible, and the current build of stash leaves such videos watchable but e.g. missing cover images.

in my own testing, this issue is largely resolved by changing the `-v error` ffmpeg parameter to `-v fatal`. this is because ffmpeg is often capable of generating the requested outputs, but non-fatal errors (e.g. PPS/SPS/VPS errors) cause it to return a non-zero return code, which in turn seems to prevent stash from actually using the temporary output files generated by ffmpeg. in my opinion, `-v fatal` makes stash more capable in its handling of imperfect video files and shouldn't meaningfully impact generation performance.

is the ffmpeg loglevel [for generate tasks] configurable somewhere? it looks hardcoded to ffmpeg.LogLevelError in [at least one section of code](https://github.com/stashapp/stash/blob/ae1841efb02ecf2fb02e842e10e089cb57db914a/pkg/ffmpeg/transcoder/image.go#L25), but i'm not familiar with this codebase and don't know if that's relevant in this context.
