### ISSUE TITLE
[Bug Report] Airplay does not work when using SSL/Https

### ISSUE THREAD

**Issue by skier233** [stashapp/stash#4145]
**Describe the bug**
Airplay doesn't work when stash is running with https/ssl

**To Reproduce**
1. run stash with ssl
2. see that airplay doesnt work

**Expected behavior**
Airplay should work with ssl enabled

**Screenshots**

**Stash Version: (from Settings -> About):v0.22.1

**Smartphone (please complete the following information):**
 - Device: Iphone 12
 - OS: latest
 - Browser safari
 - Version latest

**Additional context**

**Comment by devloch** [comment]
Are you using a 'real' trusted certificate for your server? (e.g. you're connecting to Stash using a hostname of example.com, where your server uses a certificate for example.com issued by Lets Encrypt or another publicly trusted CA).

If you're using a self signed certificate, you need to follow some manual steps to trust it https://support.apple.com/en-us/HT204477 , and the URL you're using to access stash needs to also match what is in the self signed certificate.

If you've already done all that, my apologies, it's just important clarification.

**Comment by skier233** [comment]
Yes. It’s using a letsencrypt “real” cert.
