### ISSUE TITLE
[Feature] Disable Tags Option List View and/or Truncated Tags 

### ISSUE THREAD

**Issue by C-BoT-AU** [stashapp/stash#4164]
**Is your feature request related to a problem? Please describe.**
Tags take up too many lines in the list view, especially given some studios/scrapers pull 20+ tags, while some pull none.

**Describe the solution you'd like**
Ideally, a switch in settings to either:
A. Remove tags from the list view completely (good temporary measure while sorting)
B. Only list first 3/4 tags. 
C. Wordwrap and then Truncate to only xx characters/tags that would fit in the box leaving the same height as the video.
    i) Further enhancements could then be a page onlyy or Global "Sort Tags by:" Alphabetical or Scene Count - so that the tags you use the most are easily accessible.

**Describe alternatives you've considered**
Option A would be a 'quick fix' while I believe B may require larger code changes.

**Additional context**
Below image is a example of the issue making it harder to sort/scroll/search:
![ListView](https://github.com/stashapp/stash/assets/109268182/4f297b23-24b8-4f73-9470-647095e6b5f0)

**Comment by 8ullyMaguire** [comment]
If tags were truncated I'd prefer if they were sorted by [view count](https://github.com/stashapp/stash/issues/4172) rather of alphabetically or by scene count. Having a "show more" button to show all the tags would also be nice.
