### ISSUE TITLE
[Feature] Customisable Columns in List View

### ISSUE THREAD

**Issue by C-BoT-AU** [stashapp/stash#4165]
**Is your feature request related to a problem? Please describe.**
Especially during scan and import, I always cross check the filename/path with what the scraper has detected before tagging for rename. It would be ideal to do this from the Scene List View page rather than using multiple pages.

**Describe the solution you'd like**
1. The ability to enable/disable all current columns in list view:
Preview Image | Title | Rating | Duration | Tags | Performers | Studio | Movies | Galleries
(Tags raised with alternative enhancement option (Wordwrapping) in #4164)

2. Additional Columns through a fork of commit #4112/Request #2948
-Filename (excluding full path)
-Parent Folder 

Further Enhancement:
Resort Columns by draggable list in Settings window
Resort Columns by drag/drop in List View

**Describe alternatives you've considered**
With only minimal CSS/JS/HTML knowledge, the only easy option I can see would be to enable/disable in the settings menu, similar to what is proposed for the path in commit  #4112

**Additional context**
Being able to compare the current Path/Parent Folder/Filename with the detected Scene Name/Performer/Studio in a single page will allow for quick highlighting of potential miss-matches to be fixed manually, and the bulk then being tagged/flagged as sorted to then be renamed. Unfortunately during a bulk scan some were incorrectly labelled and I now have no idea what they should have been as the original filenames are gone and I haven't yet been able to match the hash.

**Comment by echo6ix** [comment]
Similar to https://github.com/stashapp/stash/issues/517

**Comment by C-BoT-AU** [comment]
> Similar to #517
Similar, But more simplified (minimal new features, just layout options/changes). All editing would still be done inside the Scene Page/Edit Tab.
#517 would be the next step(s) after this. Full overhaul to allow easier editing from within the list.
