### ISSUE TITLE
[Feature] Trim leading and trailing white space from strings

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#4181]
**Is your feature request related to a problem? Please describe.**
I unknowingly created a performer with leading white space and it effected the data integrity as the performer name wasn't getting sorted properly. I think it's just good practice to sanitize all user and scraper submitted strings by removing any leading and trailing white space. 

**Describe the solution you'd like**
Trim leading and trailing white space from _all strings_ entered by a user or entered through scraping (assuming it doesn't already for scraping).

https://pkg.go.dev/strings#TrimSpace

**Comment by xantror** [comment]
Maybe a toggle `Trim whitespace before sorting/filtering`.

Have yet to see this, but some sites might potentially support usernames with leading/trailing spaces, which would make it hard to input the "correct" names/aliases were all whitespace to be trimmed from strings indiscriminately.

**Comment by Ronnie711** [comment]
#3262 

Linking duplicate ....

**Comment by echo6ix** [comment]
Closing because duplicate.
