### ISSUE TITLE
[Feature] Add option to Generate thumbnails for image files

### ISSUE THREAD

**Issue by JoeShymoe** [stashapp/stash#4189]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to change image thumbnails after they are initially scanned. 

**Describe the solution you'd like**
Stash has options under the Generate heading to do similar things for a number of other options. It would be useful if image thumbnails was added to that list.

**Describe alternatives you've considered**
Delete the images from stash and rescan them.

**Comment by xantror** [comment]
Implementing this will also help people who did not choose to generate image thumbnails during scan but do want to generate them later.

Currently, when they are generated during a scan, it respects the `Number of parallel task for scan/generation` setting. 

When they are generated automatically while browsing, stash currently tries to generate thumbnails for all images on the page at the same time, which might lead to stash crashing due to OOM when there are many large images (I've had stash crash due to this).

**Comment by Dark-Obsidian** [comment]
+1

From the above, I am taking it that stash doesn't generate a new thumbnail when it detects an ohash change (i.e. the image has changed)?... If not then yes, this would be good to add.

**Comment by elshanta** [comment]
I have the same issue here. I scanned thousands of image galleries without `Generate previews for image clips` option and now it is imposible to rescan them to generate missing image thumbnails:

<img width="1197" alt="Captura de Pantalla 2023-10-20 a la(s) 12 58 00" src="https://github.com/stashapp/stash/assets/118694722/a2a23785-03fa-4d36-96b4-5729e49cb5da">

**Comment by elshanta** [comment]
Please consider both folder galleries and zip galleries 🙏

**Comment by DogmaDragon** [comment]
@elshanta please make a separate issue. Tailored issues allow for faster development.

**Comment by elshanta** [comment]
> > Please consider both folder galleries and zip galleries 🙏
> 
> Kinda OT and I don't want to sound presumptuous, but I switched a rather extensive library from folder to zips. If you don't access those folders by means other than Stash, it has a number of advantages that shouldn't be discarded, especially from a storage point of view.

thanks for the recommendation.

**Comment by elshanta** [comment]
Any kind soul who can start this on the backlog please 🙏 Should be a quick fix.

**Comment by elshanta** [comment]
This was partially solved but there are still some cases where galleries have empty thumbnails.
<img width="1920" alt="Captura de pantalla 2024-06-22 a la(s) 15 38 47" src="https://github.com/stashapp/stash/assets/118694722/65b52771-5b32-480e-913c-b01f22142c91">
