### ISSUE TITLE
[Bug Report] Hovering scene cover in tagger view without generated previews

### ISSUE THREAD

**Issue by xantror** [stashapp/stash#4190]
**Describe the bug**
When hovering on a scene cover in tagger view, it "blanks" the cover image when preview is not generated.

**To Reproduce**
1. Go to scene tagger
3. Hover on the scene cover for a scene where preview is not generated
4. Image goes blank

404 message appears in console, although this is also the case for grid view when preview does not exist: 
`HTTP load failed with status 404. Load of media resource <scheme>://<stash-url>/scene/<scene-id>/preview failed.`

**Expected behavior**
Expect hovering on the cover in tagger view to have the same behavior as grid view: hovering on the image should not "blank" the image if preview for that scene is not generated.

**Screenshots**

![38457238905728345](https://github.com/stashapp/stash/assets/69341873/6d7860af-9316-4717-8276-7d8a1e9d7a6c)

**Stash Version: v0.23.0 (eca2f9b9)**

**Desktop:**
 - OS: Windows 11 (22H2)
 - Browser: Firefox (118.0.1)

**Additional context**
I think that either some logic needs to be put in place to disable trying to load preview if it is not generated or at minimum handle it like in grid view where the cover image does not get "blanked".

Would also be nice if #4022 could be integrated into tagger view.

**Comment by dogwithakeyboard** [comment]
This should be fixed by #5507.
