### ISSUE TITLE
[Bug Report] Play Count filter does not work.

### ISSUE THREAD

**Issue by gianalbertochini** [stashapp/stash#4204]
**Describe the bug**
I'm using stash v0.23.1 on Linux and i noticed that if I want sort or filter by Play Count this function fails and stash shows no scenes. Problems happens even if i try to sort by Play Count in this case scenes are not sorted.  

**To Reproduce**
1. Go to 'Scenes'
2. Click on 'Edit filter'
3. Add the filter Play Count
4. Set the filter as "Greater than" 0
5. Click on apply

**Expected behavior**
The correct behavior it should be that stas will display all the scenes that have been played before at least one time. But no scenes are displayed 

**Screenshots**
![image](https://github.com/stashapp/stash/assets/87758911/ec50d4a3-98b1-4f0a-af65-b08921018148)

![image](https://github.com/stashapp/stash/assets/87758911/8b88a263-ef5a-41f3-9594-9ffcea791136)

**Stash Version: (from Settings -> About):**
v0.23.1

**Desktop (please complete the following information):**
 - OS: linux Ubuntu
 - Browser chrome

**Comment by DingDongSoLong4** [comment]
Do you have "Track Activity" (Settings > Interface > Scene Player) enabled? The Play Count on a scene is only incremented if this is enabled.

If Track Activity is enabled, but the filter still doesn't work: go to a scene you have watched before, and open the "File Info" tab. Do you see a non-zero Play Count there?

**Comment by gianalbertochini** [comment]
You are right. Sorry is not a bug. I close the bug report
