### ISSUE TITLE
[Bug Report] No images loading for scenes

### ISSUE THREAD

**Issue by 232344235342** [stashapp/stash#4205]
Hi everyone, I'm having an issue with Stash where none of the clips have cover art/images, and no previews or scrub images. 
This has been the case since I installed the app.
I've put screenshots below of my settings. 
I would love some advice on how I can hopefully fix the issue.

ENV:
- Windows 10
- Chrome
- v0.23.0
Build hash:
eca2f9b9

![r](https://github.com/stashapp/stash/assets/91131243/f4c407b9-15cd-4f2a-94e9-9d42ab83597e)
![1](https://github.com/stashapp/stash/assets/91131243/e2cb5f97-8a80-4087-ac34-4f64bff3c971)
![2](https://github.com/stashapp/stash/assets/91131243/278c7763-4be0-4647-abf3-19928708e8dd)

**Comment by xantror** [comment]
Do you see any errors in the logs when generating covers etc?

**Comment by 232344235342** [comment]
Thank you, looks like there was an issue with the drive, changed drives and its working now I think
