### ISSUE TITLE
Error thrown when attempting to hide unmatched scrape or save scraped item

### ISSUE THREAD

**Issue by floydcg** [stashapp/stash#4210]
On the latest dev build, 789de2d5, if you scrape scenes and attempt to hide any unmatched scenes, it will throw an error of:

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

Same error is thrown when saving a scraped item. Going back to the previous dev build restores functionallity.

**Comment by DingDongSoLong4** [comment]
I can't reproduce this - it sounds to me like a userscript or plugin error. Do you use either of those, and if so does the error still occur if you disable all userscripts and plugins?
