### ISSUE TITLE
[Bug Report] Some scene images are not showing

### ISSUE THREAD

**Issue by gianalbertochini** [stashapp/stash#4211]
**Describe the bug**
When I try to show over 700 SCENES in one page (usually i show 1000) I get the last X scenes of the page without preview fixed image. 

Basically the app does not show the fixed image of the last X scenes of the page but when I hover the image the "dinamyc preview" works.

When the scenes number is below around 600-700 the problem disapear and all works good

**To Reproduce**
1. Go to 'scenes'
2. Select the number of scenes at value about 1000
3. Wait the page reloading compleatley
4. Scroll down to the end of page
5. See that you don't see the previews
6. Hover a scene and you see that the previous start to works

**Expected behavior**
I expect that all the previous scenes are be showned

**Screenshots**
![Screenshot 2023-10-16 184759](https://github.com/stashapp/stash/assets/87758911/12c97e6d-2a7e-4e4e-9fa7-00b2b2f210a2)

![Screenshot 2023-10-16 185550](https://github.com/stashapp/stash/assets/87758911/a9532be7-f58d-4dc9-a8e7-b91cae3900a6)

![ezgif-2-8450c5c751](https://github.com/stashapp/stash/assets/87758911/4ec65ce4-ab86-4031-b0d0-f1678278decb)

**Stash Version: **
v0.23.1  FOR LINUX

**Desktop: **
 - OS: Windows 11
 - Chrome and edge

**Comment by DingDongSoLong4** [comment]
I'm unable to reproduce this. If you open the browser devtools (hit F12 on your keyboard) and go to the Console tab, do you see any network errors? If you go to the network tab and reload the page, are any of the network requests returning errors?

**Comment by gianalbertochini** [comment]
It give me this errors a lot

![image](https://github.com/stashapp/stash/assets/87758911/63083df4-5ded-493c-8ced-16ab83fdd4ec)

I used chrome I tried in edge but the problem persist

I used firefox and all worked good

**Comment by gianalbertochini** [comment]
Ah yes ive tried to clear the cache too and cookies

**Comment by gianalbertochini** [comment]
And disabled all extensions :)

**Comment by WithoutPants** [comment]
`ERR_INSUFFICIENT_RESOURCES` means that Chrome is trying to do too many requests at once. I'm not sure what the solution is.
