### ISSUE TITLE
[Bug Report] Tagger used with multiple StashBoxes will lose Performer StashIDs

### ISSUE THREAD

**Issue by scruffynerf** [stashapp/stash#4212]
If you use Performer Tagger, and scrape a performer, and the matched performer already exists with other StashIDs from other stashboxes, hitting the save will cause the loss of the other existing StashIDs, and only the new one is saved.

**To Reproduce**
Scrape a Performer using StashBox B, and if the Performer already has a StashID from Stashbox A...
It will match, and allow you to save the new StashID.
It then loses any existing StashIDs, and only keeps the new one.

**Expected behavior**
It should keep any existing stashids as well as add the new one.

**Stash Version: (from Settings -> About):**
Existed for a while, including up to v.23.1

Confirmed by multiple people.

Corrected by me, as I misunderstood the latest report.  
I know @DingDongSoLong4 fixed the scene tagger issues in https://github.com/stashapp/stash/pull/4092
and pointed to this other similar issue as long standing (https://discord.com/channels/559159668438728723/559159910550732809/1152724118299496570)

**Comment by DingDongSoLong4** [comment]
This also happens in the Performer Tagger (not the _bulk_ performer tagger), when updating an existing performer.

A relevant bit of code:
https://github.com/stashapp/stash/blob/0b7dcbe8997965d874cd27d9b7ab2cb2473f3d52/ui/v2.5/src/components/Tagger/PerformerModal.tsx#L171-L176
