### ISSUE TITLE
[Feature] Add `FFmpeg location` option to Settings > System

### ISSUE THREAD

**Issue by Dark-Obsidian** [stashapp/stash#4218]
**Is your feature request related to a problem? Please describe.**
- Not a _problem_, however not-optimised behaviour...
- I noticed when first running stash-win that it started to download `FFmpeg.exe` to it's current folder
- I wanted to stop this as I already have `FFmpeg.exe`, `FFprobe.exe`, `FFplay.exe` on my computer in a shared folder

**Describe the solution you'd like**
- Add a menu option called `FFmpeg location` where the user can specify the path to `FFmpeg.exe`
- Suggestion location: `Settings > System` in either the `Transcoding` or `Application Paths` sections
- NB: If stash uses other binaries (e.g. `FFprobe.exe`) the option could be used to set a path to a folder rather than specific .exe
- If set, stash would use this path instead of downloading it's own copy of the exe's

**Describe alternatives you've considered**
- What I have done myself for the time-being is...
- Delete any FFmpeg.exe files from the stash folder, then...
- Create symbolic links for FFmpeg.exe in stash's directory that point the copy of FFmpeg in my shared folder

**Comment by DogmaDragon** [comment]
Stash should already check for `FFmpeg` in PATH and only download it if the version from `PATH` lacks some flags that Stash uses or doesn't find it in `PATH`.

**Comment by Dark-Obsidian** [comment]
Hi @DogmaDragon - thanks for the info!...

Ah, well my case may be slightly different...
- I have `FFmpeg.cmd` in my `%PATH%`
- NOTE: `.cmd` not `.exe`
- `FFmpeg.cmd` [1] calls `FFmpeg.exe`, [2] passes some standard params (e.g. hide banner) and [3] passes-thru everything that it was passed

```cmd
FFmpeg.cmd
----------
"D:\PortableApps\FFmpeg\FFmpeg.exe" ^
-hide_banner -loglevel warning -stats -y ^
%*

So...
> FFmpeg -i "D:\Downloads\input.mp4" -t 00:00:05 "D:\Downloads\output.mp4"
= "D:\PortableApps\FFmpeg\FFmpeg.exe" -hide_banner -loglevel warning -stats -y -i "D:\Downloads\input.mp4" -t 00:00:05 "D:\Downloads\output.mp4"
```

***

### Summary
- If stash already checks the `%PATH%` then I agree the benefit of this change is diminished
- I still think that a `FFmpeg location` option _could_ be useful for situations like mine, or also where the user may be less technical and doesn't know how to add FFmpeg to their `%PATH%` etc
- Will leave it up to you guys to decide whether you want to:
   - Keep this in the backlog as a low priority request ("will look to implement this at some point"), or
   - Close this out (i.e. "will not implement")
