### ISSUE TITLE
[Feature] bulk delete option

### ISSUE THREAD

**Issue by binarygeek119** [stashapp/stash#423]
I like a bulk delete option in multi select maybe add a switch to enable destructive mode in setting so it doesn't show up unless you want to use bulk delete
maybe have it time out aswell

**Comment by ueaslsef** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/52797608/77974091-aafce880-72e5-11ea-97c1-8e8b084daa98.png)

**Comment by WithoutPants** [comment]
Closing as duplicate of #239.
