### ISSUE TITLE
[Feature] Add plugins_path to Application Paths

### ISSUE THREAD

**Issue by stg-annon** [stashapp/stash#4230]
### **Is your feature request related to a problem? Please describe.**
`plugins_path` has to be set directly in the config file, this is different from most of the other path configurations that can be set in the UI

### **Describe the solution you'd like**
add a UI config for `plugins_path` under `Settings > System > Application Paths`

**Comment by scruffynerf** [comment]
bump.  @WithoutPants  given the changes to Plugins, this probably should be in v24.
