### ISSUE TITLE
Add Tagging Functionality to Galleries

### ISSUE THREAD

**Issue by yoshnopa** [stashapp/stash#424]
For now, Galleries are pretty simple. To give them a more prominent place in the organization in stash, the most important thing would be to give it actual values to edit and search for, like a name, a rating, and most important, tags. With the option of tags, most things can be done alone, so this should be a priority when implementing such options. However implementing a similar structure as for scenes would probably be the cleanest and most consistent solution, with the advantage of reusing the ui elements.

**Comment by seducingbits** [comment]
I think mostly the same items would be relevant as for a scene:

* Studio
* Performer
* Date
* Title
* Description
* Tags
* O-Counter

When a gallery is linked to a video scene some of these fields could be autopopulated.

On the performers and studio page could be a new tab "Galleries" which lists all galleries for that performer/studio.

**Comment by yoshnopa** [comment]
with the image functionality and the restructuring of galleries, this issue is solved from my point of view. Thanks!
