### ISSUE TITLE
[Feature] Add a scene specs overlay span class for scene duration

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#4240]
**Is your feature request related to a problem? Please describe.**
The scene grid view spec overlay `span` tags all have their own class except for the scene duration. This makes it difficult style the duration.

**Describe the solution you'd like**
Following the convention of the other span classes, create a span class for the scene duration, such as `overlay-duration`.

```css
<div class="scene-specs-overlay">
   <span class="overlay-filesize extra-scene-info"></span>
   <span class="overlay-resolution"></span>
   /* class for scene duration */
   <span class="overlay-duration"></span>
</div>
```

**Comment by elkorol** [comment]
I added that in this [pr](https://github.com/stashapp/stash/pull/4224)
