### ISSUE TITLE
[Feature] UI Plugin dependency loading

### ISSUE THREAD

**Issue by feederbox826** [stashapp/stash#4241]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
In replacing userscripts with ui plugins, script libraries and CSS imports have to be downloaded alongside plugins and injected into the `/javascript` and `/css` files

alongside CSP allowed domains, additional properties for imported scripts (corresponding to [CSP: script-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src)) and imported stylesheets ([CSP:style-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src)) can be added, and injected as `<style>` and `<script>` blocks 

**Describe alternatives you've considered**
Currently the files are being downloaded unminfied and stored in the plugin's repo but this leaves room for malicious actors uploading minified, modified code.

**Additional context**
Originally discussed in Userscript -> JS plugin port thread [on discord](https://discord.com/channels/559159668438728723/1166478676532142081)
original CSP PR #2108

**Comment by feederbox826** [comment]
closed in #4256

**Comment by DogmaDragon** [comment]
I'm pretty sure it was addressed in https://github.com/stashapp/stash/pull/4260.
