### ISSUE TITLE
[Feature] Set Image Gallery Thumbnail from one of the existing gallery images

### ISSUE THREAD

**Issue by elshanta** [stashapp/stash#4254]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to change the main Image Gallery thumbnail.

**Describe the solution you'd like**
It would be great to have the option to select the new gallery thumbnail from one of the existing images inside the gallery.

**Comment by peresabcod** [comment]
+1
Except those that already have a custom cover, sometimes the first image of a gallery does not represent it in any way (i.e. a barn, a mountain, a random shot in the street, only one performer when there are several, etc..)
