### ISSUE TITLE
[RFC] Utilize OS Sandboxing

### ISSUE THREAD

**Issue by ikmckenz** [stashapp/stash#4292]
## Scope
Integrating OS-level sandboxing could help harden Stash without performance impact. I don't run a public facing instance, but I also don't 100% trust all traffic on my local network. Why should Stash have access to my ssh keys, or any files on my computer other than what it needs? Certainly advanced users can utilize chroot/jail's on Unix systems with proper setup, but it would be much easier if the functionality was just built into the binary itself. I envision an entry into the config file "sandbox" which is by default set to false until the functionality is well tested, and manually setting it to true enables sandboxing that occurs after initialization (once all file-system paths are known), but before the handlers begin processing requests. I think this could potentially be non-trivial work, so I wanted commentary from the community before writing it myself. The sandboxing could be accomplished with Landlock on Linux, and pledge(2) and unveil(2) on OpenBSD, with more research needed to identify alternatives for other operating systems. Alternatives to a simple binary on/off sandboxing could also include a more restrictive read-only mode, although I'm not 100% sure about the feasibility of this. 

## Examples
I have created a pull request (https://github.com/stashapp/stash/pull/4291) for the `phasher` binary that implements OS sandboxing on Linux (with Landlock) and OpenBSD (with pledge(2) and unveil(2)) as a simple example of what the code might look like. The sandboxing code for `stash` would necessarily be more complicated, but function similarly (sandboxing is called after initialization, but before serious work begins). 

## Reference Reading
https://docs.kernel.org/userspace-api/landlock.html
https://man.openbsd.org/pledge.2
https://man.openbsd.org/unveil.2

**Comment by WithoutPants** [comment]
This seems like a lot of work and additional complexity to accomplish something that security-minded users can already do using the aforementioned chroot/jails. I'm not aware of a significant demand for this functionality.

**Comment by DingDongSoLong4** [comment]
Relevant issue: #3809

Distributing a Flatpak would definitely be a good idea, both for sandboxing and for the exposure on e.g. Flathub, but they are Linux-only so wouldn't help on OpenBSD.

**Comment by scruffynerf** [comment]
And as mentioned in Discord, anyone needing this sort of security can use Docker now as well.

**Comment by its-josh4** [comment]
My .02: I too would recommend using Docker in this case which offers isolation for not just filesystem access, but also networking and IPC.

This feature can add significant overhead in terms of support. It also works on few systems, most notably requiring kernel 5.13+ on Linux (which means it won't work on still-supported and popular distros like Ubuntu 20.04, Debian 10/11, RHEL 8 and derivatives...)

**Comment by joewood9364** [comment]
> Another idea is to consider a flatpak version. Flatpak gives the benefits of sandboxing. It also provides an opportunity to publish the app on large repositories like Flathub, which would increase interest in the stash project.
> 
> https://docs.flatpak.org/en/latest/basic-concepts.html https://opensource.com/article/19/10/how-build-flatpak-packaging

+1 for a Flatpak on Flathub!
