### ISSUE TITLE
[Bug Report] iOS crashing

### ISSUE THREAD

**Issue by Phizulation** [stashapp/stash#4303]
Whenever I try to access Stash from my iphone, whether on Safari, or Brave, I can log onto the main page, but when I click on Scenes it loads the first one and then when I try to scroll everything locks up. If I close the browser and try to get on again its unresponsive. 

Restarted phone multiple times, tried on another phone, still same errors. I also tried it behind a reverse proxy or going right to the source on my home network. Using an iPhone 15 on latest firmware, but this has been an issue on my old iPhone 13 as well. 

**Expected behavior**
I expect the site to load like normal or any other streaming site. 

**Stash Version: (from Settings -> About):**

v0.23.1
Build hash:
479e7163

**Desktop (please complete the following information):**
 - iOS 

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Plus

**Comment by ALonelyJuicebox** [comment]
Is the _page_ unresponsive or is the browser unresponsive?

How many thumbnails are you loading on the scenes page? 
For context, setting the thumbnails per page to 120 on an iPhone 14 Pro running Safari on iOS 17.1.1 works just fine with no lag other than the initial page load.

**Comment by Phizulation** [comment]
I think that was it, I had it set to 500 and it was trying to load it all. Works so far when I set it to 60, and I'll keep trying to up it. 

Thank you!
