### ISSUE TITLE
[Feature] Allow custom default scene sorting

### ISSUE THREAD

**Issue by squall4977** [stashapp/stash#4308]
**Is your feature request related to a problem? Please describe.**
I don't care about "Date" as a sort option.  It's not a problem, just a preference.

**Describe the solution you'd like**
I would appreciate if there was a user profile option that allowed selecting the default scene sort option.  "Random" for example.

**Describe alternatives you've considered**
My preference would be to log into the stash app, select scenes, and automatically see a random selection.

**Additional context**
The semi-permanent selection should probably be somewhere in the options.

**Comment by DingDongSoLong4** [comment]
@squall4977 This is already possible, using a default filter - they save the search, sorting and view options in addition to the normal filters.

So in your case, to set a random sort as default:

1. Open the scenes tab
2. Set the sort order to Random
3. Click the Saved Filters button (the bookmark icon)
4. Click "Set as default"

The next time you open the scenes tab, it will open with a random selection.
