### ISSUE TITLE
Metadata full export crashes on galleries

### ISSUE THREAD

**Issue by kyuu840** [stashapp/stash#4310]
**Describe the bug**
Exporting metadata via the _Tasks > Metadata > Full export_ causes a panic when the process gets to the galleries (files, images and scenes export just fine, as far as I can tell). This happens on my main database (200k+ images) and on a brand-new test environment with only 300 images. Maybe this is because galleries now have URLs instead of just one URL? I did not investigate this, but every time there's a new Stash version I do a full export, and in v0.22 everything exported just fine.

**To Reproduce**
1. Create new Stash database with a few images
2. Enable _Create galleries from folders containing images_
3. Scan library, to have at least 1 gallery in the database
4. Export metadata via _Tasks > Metadata > Full export_

**Expected behavior**
JSON files would appear under `<metadata_dir>/galleries`

**Stash Version: (from Settings -> About):**
v0.23.1
Build hash: `479e7163`
Build time: `2023-10-14 00:26:46`

**Desktop (please complete the following information):**
 - OS: reproduced on both Windows 11, and Unraid Docker 20.10.24

**Additional context**
Logs:

```
INFO[2023-11-26 18:43:05] [images] export complete in 156.1677ms. 24 workers used.
TRAC[2023-11-26 18:43:05] SQL [0s]: SELECT `galleries`.*, `galleries_files`.`file_id` AS `primary_file_id`, `folders`.`path` AS `primary_file_folder_path`, `files`.`basename` AS `primary_file_basename`, `gallery_folder`.`path` AS `folder_path` FROM `galleries` LEFT JOIN `galleries_files` ON ((`galleries_files`.`gallery_id` = `galleries`.`id`) AND (`galleries_files`.`primary` = 1)) LEFT JOIN `files` ON (`files`.`id` = `galleries_files`.`file_id`) LEFT JOIN `folders` ON (`folders`.`id` = `files`.`parent_folder_id`) LEFT JOIN `folders` AS `gallery_folder` ON (`gallery_folder`.`id` = `galleries`.`folder_id`), args: []
INFO[2023-11-26 18:43:05] [galleries] exporting
TRAC[2023-11-26 18:43:05] SQL [0s]: SELECT file_id, `primary` from galleries_files WHERE gallery_id = ?, args: [1]

panic: list has not been loaded

goroutine 7031 [running]:
github.com/stashapp/stash/pkg/models.RelatedStrings.mustLoaded(...)
        github.com/stashapp/stash/pkg/models/relationships.go:444
github.com/stashapp/stash/pkg/models.RelatedStrings.List(...)
        github.com/stashapp/stash/pkg/models/relationships.go:450
github.com/stashapp/stash/pkg/gallery.ToBasicJSON(0xc000e56780)
        github.com/stashapp/stash/pkg/gallery/export.go:17 +0x3df
github.com/stashapp/stash/internal/manager.exportGallery({0x28b1660, 0xc000c0a210}, 0xc000c6f740?, 0x28a2c80?, {{0x28b4b20, 0xc000220000}, {0x28bb008, 0xc00058e0f0}, {0x28b7380, 0xc00058e120}, ...}, ...)
        github.com/stashapp/stash/internal/manager/task_export.go:777 +0x3e5
created by github.com/stashapp/stash/internal/manager.(*ExportTask).ExportGalleries
        github.com/stashapp/stash/internal/manager/task_export.go:743 +0x265
```

**Comment by DogmaDragon** [comment]
Reproduced on 479e7163.
