### ISSUE TITLE
[Feature] Disable automatic session invalidation/logout

### ISSUE THREAD

**Issue by StashPowerUser** [stashapp/stash#4312]
**Is your feature request related to a problem? Please describe.**
I use a dedicated browser for stash and would like to avoid having to log in every startup.

**Describe the solution you'd like**

I'd like an option to make sessions permanent until the password is changed or I manually logout

**Describe alternatives you've considered**
I've tried setting session length to 0, and to 172800 seconds but if I go more than a few hours with the browser closed it still requires me to log in on restart.

I might be doing something wrong?

**Additional context**

I'm using ungoogled-chromium on Mac.  The session persists if the browser is only closed for a couple of hours, but overnight it seems to always log me out.

**Comment by DingDongSoLong4** [comment]
Have you restarted Stash after changing the session length? A change only takes effect after a restart. This has come up in Discord before, and this was the cause.

Your login status is stored as a cookie in the browser (called `session`), and the "Maximum Session Age" setting simply controls the cookie's `Expires` property. If you're using incognito mode, or if your browser is clearing its cookies for whatever other reason, then this cookie will not be sent and you will be prompted to log in again.

Also, to have a "permanent" session, you want to set the max session age to a very large number, like for example `31536000` for 365 days. Setting it to 0 will make the cookie a "Session" cookie (a different kind of session), which means that the browser will automatically delete it when the browser exists - i.e. not want you want.

**Comment by StashPowerUser** [comment]
No, I didn't realize a restart is required since the value was editable in the Security settings UI and made no mention of requiring a restart.

Can confirm that things work as expected after restarting.  Thanks!
