### ISSUE TITLE
[Bug Report] Scene Filename Parser, No Save Button

### ISSUE THREAD

**Issue by wild9k** [stashapp/stash#4314]
**Describe the bug**
There is no save button on the Scene Filename Parser Screen. Tried adding - and + the the whitespace field and can't find a way to save the new value

**To Reproduce**
Go to Settings
Tools
Scene Filename Parser

Stash Version: 0.23.1 in Docker Image on Unraid 6.12.4

**Comment by DogmaDragon** [comment]
You need to click `Find` when the pattern is set and then there will be `Apply` button at the bottom. 
![image](https://github.com/stashapp/stash/assets/103123951/357d925e-be7f-44e1-82bb-da676d3cbcdc)
