### ISSUE TITLE
invite code

### ISSUE THREAD

**Issue by 6Fv** [stashapp/stash#4316]
I don't have discord. Can someone that does send me an invite key? Thanks

**Comment by DogmaDragon** [comment]
Unrelated to Stash. 

We also have Matrix if you prefer it over Discord. See https://docs.stashapp.cc/matrix/

**Comment by DingDongSoLong4** [comment]
You don't need an invite key to join Discord itself. To join the Stash Discord server specifically, use https://discord.gg/2TsNFKt, which is also linked in the README.
