### ISSUE TITLE
[Bug Report] FFMPEG burning CPU when watching high quality VR

### ISSUE THREAD

**Issue by zhgwn** [stashapp/stash#4317]
**Describe the bug**
I have a very heavy VR video that weights 13gb, that is 6K and 50 min long. When trying to watch it after having clicked on the VR Headset logo and put on 360, FFMPEG starts to take a lot of my CPU, the video is loading 2 seconds in 20 seconds, and the air vent starts making noise, which is happens very rarely on latest Macs with apple chips. If I switch the quality to something like 240p, it's ok. As soon as I put mp4, it instantly starts to take all the CPU.

**To Reproduce**
1. Get a heavy VR video, in high quality.
2. Set the VR tag, click on the headset, and start playing
3. It should start loading very very slowly, and FFMPEg should slowly take your CPU in hostage.

**Expected behavior**
It should load smoothly.

**Screenshots**
<img width="390" alt="Capture d’écran 2023-11-27 à 14 14 52" src="https://github.com/stashapp/stash/assets/130610452/9c68c739-c0cf-4091-9aeb-7c9dd817b5ed">

**Stash Version: (from Settings -> About):**
v0.23.1

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Any browser

**Additional context**
This might come from the fact I'm on a M2 Pro Mac, but I doubt it ...

**Comment by michal-repo** [comment]
Try with **direct stream** option in quality. ffmpeg starts if you choose different quality, it converts file on the fly.

**Comment by zhgwn** [comment]
> Try with **direct stream** option in quality. ffmpeg starts if you choose different quality, it converts file on the fly.

Direct stream is the default setting and it's the one that makes ffmpeg burn my cpu. Is there maybe a way to pre-generate the video that will be rendered in VR, instead of on the fly ?

**Comment by michal-repo** [comment]
maybe it's codec fault (not supported by browser)? Firefox generally have issues (at least on windows) with videos that are over 4000 pixels wide, try with safari or chrome

**Comment by zhgwn** [comment]
It was that, firefox and safari were both having issues, chrome is fine !
