### ISSUE TITLE
[Feature] Block content on StashDB.org website by tags, studios, stars, gender...

### ISSUE THREAD

**Issue by wilsonwilsonlg** [stashapp/stash#4327]
**Is your feature request related to a problem? Please describe.**
Context: When searching on scenes at the StashDB website, you are able to filter content by tag that it's ok for a very precise search, but you are not allowed to block content when searching making difficult to do a more generalized search, discarding content that you are sure is not related to what you are looking for.

**Describe the solution you'd like**
Would be nice to be able block content by tags, studios, stars, gender or date periods.

**Describe alternatives you've considered**
Make this filters permanent from the user profile settings, but I get this could contribute in a bigger database size for the website.

**Comment by DingDongSoLong4** [comment]
Please make stash-box related bug reports or feature requests over on the stash-box repo: https://github.com/stashapp/stash-box/issues.
