### ISSUE TITLE
[Feature] Autocomplete behaviour improvement for short[ish] item searches

### ISSUE THREAD

**Issue by BonerFide** [stashapp/stash#4342]
**Is your feature request related to a problem? Please describe.**
When using the tagger fields, the autocomplete sorts only alphabetically. This is pretty standard and most of the time this is fine as you can just 'type more' to get a better match. The issue is with long lists and short words that are contained within other words. If you are looking to tag with say: "Test", you can type "Test".

You might get a list that is: 

"contest"
"cutest"
"detest"
"incontestable"
"latest"
"protest"
"test"
"tested"
"testing"

Because you're looking for "test" to add, it means you have to key down or scroll down what can be a considerable way. If you just tab out after typing "test" it will complete with whatever is alphabetically first in the list, if you click out, it won't add anything.

**Describe the solution you'd like**
If the search term matches an item in the list *exactly*, it should appear as the first item in the list. Typing "test[space]" should probably not match "test" since you might be deliberately looking for a two word item. All the other items can still appear after that item as per the current order as you may still want to auto-complete a longer item.

**Describe alternatives you've considered**
- You could have a special key that means 'and that's all' eg you search for "test\" I think that's less ideal because it requires the user to know to use that key. 
- You could type ""test"" but that requires thinking ahead of time.
- You could use regex, eg "^test$" but that requires probably more effort and user thought than desired for something like tags you want to go through very quickly. 
- You could make tabbing out put in exactly that tag/key (if it exists) unless you key down to select a different item instead of selecting the first. Might work, but might create extra keystrokes for all other circumstances.

**Additional context**
For longer distinct items this isn't really a problem because you can just 'keep typing' the tag until you only have one item (or very few) in the list. But say, try tagging a performer who is listed only as 'Ana' and it quickly becomes tedious with strictly alphabetical auto complete sorting, you can't type any more to clarify, so you just have to key down/scroll. The same goes for tags that are part of another tag. You are always having to scroll/key down if your shorter tag is the second part of a more specific longer tag/s.

**Comment by DingDongSoLong4** [comment]
How about prioritising all items that _start_ with the input? Using your example, that would then give 

"test"
"tested"
"testing"
"contest"
"cutest"
"detest"
"incontestable"
"latest"
"protest"

for a search of "test".

This has the advantage of then giving exactly those same results for a search of just "te" (or "t" for that matter), which would save time if "test" was what you actually wanted.

**Comment by BonerFide** [comment]
That should work a lot better than current also. But it does have a slight disadvantage if you're say looking by a second word. Eg, if you had 

"anne test"
"ben test"
"charlie test"
"test alpha"
"test beta"
"test gamma"
"test epsilon"

If we reorder that upon typing  'test' with a priority for starts with we end up with
"test alpha"
"test beta"
"test gamma"
"test epsilon"
"anne test"
"ben test"
"charlie test"

If you type 'test' but are looking for 'charlie test' you can't type further characters to narrow the results further without keying back to the start of the input (home/end don't work) and typing 'charlie test' in full, or scrolling past all the 'starts with' options to find it. Where as if you typed 'test' and wanted 'test epsilon' you could just type another 2 characters and be done. 

So your option is a few keystrokes faster in probably a majority of circumstances, but longer 'worst case'. 

I could go either way really. At least starts with makes more sense than randomly ripping it out of the middle of a word which is likely to be the least likely. Probably if making priorities the lowest priority ought be [letter][searchterm] below both [startswith]search term and [space]search term. Starts to get more complicated than a simple re-order or exception though.

**Comment by DingDongSoLong4** [comment]
What would be the best is a "relevance" rating, but that is certainly too complicated.

In your example there, you could just type "test c", or "test charlie", and those would actually return just "charlie test". At least if you're using the performer input that is, because that filters on the server-side which actually doesn't care about the order of words. The tags input does the filtering client-side, which just filters by checking if the entire input is contained in the tag name, and so order does matter.

Making all the inputs do server-side filtering is a planned feature, so eventually this order-independent filtering should be everywhere as well.

How about a simpler order of "ends with query", then "starts with query", and then everything else? The ordering shouldn't be too complicated, otherwise people could get confused - the advantage of alphabetical order is that it's obvious what the ordering is.

**Comment by BonerFide** [comment]
Kind of regardless of anything else I think the exact match should be first no matter what, because that specific situation there's no more you can type to clarify. Any other improvement is just a plus. 

Having exactly the thing you typed, half way down a long list, is not ideal. Otherwise alphabetical is, as you say, obvious if you do have to scroll down to find the thing you're looking for.

**Comment by DingDongSoLong4** [comment]
Yes I agree - my initial "just prioritise starts with" automatically puts an exact match first because of the alphabetical ordering, but I missed that "ends with" being first wouldn't. So it would then be "exact match", "ends with", "starts with", then everything else.
