### ISSUE TITLE
[Bug Report] Can't use auto-tag scraper without tags

### ISSUE THREAD

**Issue by daddie888** [stashapp/stash#4359]
**Describe the bug**
When you want to scrape scenes with auto-tag but without importing tags, only performers and studios it doesn't work.
The configuration jumps back to all three of them, manually editing the config yaml file doesn't work either.

**To Reproduce**
1. Go to settings/tasks/auto-tag
2. Click on tagsto disable scraping for tags
3. Got to scenes/source autotag/scrape all/hide unmatched scenes
4. Sceneshave tags scraped and scenes with only tags scraped are shown

**Expected behavior**
Only scrape the scenes with performer and studio info, being able to hide unmatched scenes (with only tags)

**Screenshots**
Configuration is done (after some tries, it kept jumping back), server restarted
![image](https://github.com/stashapp/stash/assets/1726378/294220d8-21b0-4e5d-8105-98776837f256)

The tag should nog have been scraped and the scene should have been hidden
![image](https://github.com/stashapp/stash/assets/1726378/09ed36a1-5645-4428-8399-852eda6f9a28)

**Stash Version: (from Settings -> About):**
v0.23.1
Build hash:
479e7163

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 120.0.6099.71 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
Not tested on smartphone

**Additional context**
I have a lot of edited scenes which Phash are not  in the databases so I have to rely on autotagging a lot.
I like to work with a limited set of tags.

**Comment by DogmaDragon** [comment]
Uncheck `Set Tags` in Tagger configuration.
 ![image](https://github.com/stashapp/stash/assets/103123951/800a0e23-6f4f-45ab-93dd-9d949bf7b314)

**Comment by WithoutPants** [comment]
The auto tag task options are unrelated to the auto tag scraper behaviour. As noted, tags can be ignored in the tagger settings.
