### ISSUE TITLE
[Feature] Add "Missing Gender" filter to performer section

### ISSUE THREAD

**Issue by VonTittyslappen** [stashapp/stash#436]
I believe that it would be very beneficial for there to be a filter where you can view all performers that are missing a gender within the performers section

Cheers

**Comment by bnkai** [comment]
the "Is Missing" filter would be useful to double check for missing gender, url , birthdate, ethnicity ....

**Comment by Cutters1982** [comment]
Yep, definitely! :)

**Comment by Anon247** [comment]
I'll work on this one
