### ISSUE TITLE
[Bug Report] Stats Page not working anymore

### ISSUE THREAD

**Issue by Tscherno** [stashapp/stash#4389]
**Describe the bug**
The GQL query for the stats page

```
{"operationName":"Stats","variables":{},"query":"query Stats {\n  stats {\n    scene_count\n    scenes_size\n    scenes_duration\n    image_count\n    images_size\n    gallery_count\n    performer_count\n    studio_count\n    movie_count\n    tag_count\n    total_o_count\n    total_play_duration\n    total_play_count\n    scenes_played\n    __typename\n  }\n}"}
```

returns 
> sql: Scan error on column index 0, name "SUM(`files`.`size`)": converting NULL to float64 is unsupported

**To Reproduce**
1. Goto stats page

**Expected behavior**
Shows the stats

**Stash Version: (from Settings -> About):**
v0.23.1-86-gd2589763

**Additional context**
Not sure when it worked last time.

**Comment by Tscherno** [comment]
Probably caused by
```
SELECT SUM(`files`.`size`) FROM `images` INNER JOIN `images_files` ON (`images`.`id` = `images_files`.`image_id`) INNER JOIN `files` ON (`images_files`.`file_id` = `files`.`id`)
```

returning NULL for my DB. I have no images at all.

Guess same if no Scenes exist at all. IFNULL(..., 0) could fix it?

**Comment by DingDongSoLong4** [comment]
Thanks for the bug report, you're indeed correct as to the cause. This should now be fixed.
