### ISSUE TITLE
[Bug Report] Can't open with external player app on Android (Firefox, Chrome)

### ISSUE THREAD

**Issue by kyuu840** [stashapp/stash#4401]
**Describe the bug**
The external player button does not work on Firefox for Android 120 and 121, nor on Chrome 120. The button's link has protocol `http`, so Firefox and Chrome just open it itself instead of using the external apps. I tried manually forcing it to protocol `intent` and then it works as intended. See workaround at the bottom of the issue.

I can see the code that creates this button, here: https://github.com/stashapp/stash/blob/82cbeff9b534722645e591d486314b6cd914c25f/ui/v2.5/src/components/Scenes/SceneDetails/ExternalPlayerButton.tsx#L35

and it looks straightforward enough, but the fact is that the button ends up with protocol `http`. I'm not sure if this is a bug in Stash, or a new behavior of Firefox/Chrome when it comes to `intent` links.

The protocol is also wrongly `http` when using Firefox on Windows, with Responsive Design mode to simulate a smartphone and fake the User-agent.

When using Samsung Internet browser on Android, the bug does not happen, and the link has protocol `intent` as it should be, and external players work.

**To Reproduce**
1. Open a scene page in Firefox for Android
2. Press the "Open in external player" button
3. Depending on the scene file, either Firefox will play the video by itself, or try to download it.

**Expected behavior**
Firefox should ask which external app to use (VLC, MX Player, ...).

**Stash Version: (from Settings -> About):**
v0.24.0 (`3e9bd850`) and v0.23.1

**Desktop:**
- Unraid Docker

**Smartphone:**
 - OS: Android 13
 - Browsers: Firefox 121.0 and 120.0; Chrome 120
 - User-agent: `Mozilla/5.0 (Android 13; Mobile; rv:120.0) Gecko/120.0 Firefox/120.0` (I didn't try playing around with Chrome's User-agent)

**Workaround**
- Go to Settings > Interface > Custom Javascript
- Enable it, and add the following code. It's ugly, but it works, and it enabled Firefox to recognize the link as an external app link for me.

```javascript
// Find button with title "Open in external player", get its "a" child, and set its href protocol from http:// to intent://
function fixButton() {
    var button = document.querySelector('button[title="Open in external player"]');
    if (button) {
        var buttonA = button.querySelector('a');
        var extAppLink = buttonA.href;
        var intentLink = extAppLink.replace('http://', 'intent://');
        buttonA.href = intentLink;
    }
}

// Call it 1 second after page load
setTimeout(fixButton, 1000);
```

**Comment by DoctorD1501** [comment]
I'm also having the same issue with "Open in external player" being broken on iPad. Same sort of problem, where the protocol is set as http instead of 'vlc-x-callback'.

I should note there is some general buggyness with this button appearing on firefox on iOS, even when requesting the mobile site. I tested using Safari as the button will not show on firefox on iOS no matter what I try.

**Comment by WithoutPants** [comment]
This looks to be due to the specification of the `URL` - see https://stackoverflow.com/a/77154615

It's a bit bonkers. I'm not sure why this is occurring now, but we'll have to do a bit of a hack to fix it.
