### ISSUE TITLE
[Bug Report] Identify with folder selection fails

### ISSUE THREAD

**Issue by timo95** [stashapp/stash#4407]
**Describe the bug**
Any Identify task with a folder filter finishes without identifying any scene.

**To Reproduce**
1. Go to Tasks
2. Click Identify
3. Select a subfolder with scenes
4. Select any working scraper (e.g. StashDB)
5. Identify runs, doesn't find any scenes and finishes without scraping

**Expected behavior**
Identify runs on all scenes in the selected folder

**Stash Version: (from Settings -> About):**
0.24.1 and 0.23.1

**Comment by DingDongSoLong4** [comment]
I'm unable to reproduce this. In the progress bar for the Identify task, do you get "Identifying <path>" messages, or does the task just instantly finish?

**Comment by timo95** [comment]
Now I feel dumb. It happened because every scene in the folder was "Organized"...
