### ISSUE TITLE
[Feature] Check for Plugin/Scraper updates should show only those with updates

### ISSUE THREAD

**Issue by Ronnie711** [stashapp/stash#4410]
**Is your feature request related to a problem? Please describe.**

Currently when checking for updates it shows all installed and you have scroll the whole list to see which scrapers have updates available.

**Describe the solution you'd like**

When checking for updates I'd like it show either only those with updates or a 'No updates available' message.

**Comment by UltraHKR** [comment]
There's also the fact that the UI is not usable right now, if one loads all community scrapers it's really easy to miss an updated plugin... (or conversely it's hard to see updated scrappers)

This should also be extended to the plugins, which I believe share the same issue to a lesser extent...

**Comment by Maista6969** [comment]
I think scrapers with updates should flow to the top of the list in `Installed Scrapers` and be hidden from the list of `Available Scrapers`, and that a button to update just that scraper should appear in same row as the plugin/scraper

Before:
![installed-before](https://github.com/stashapp/stash/assets/131594657/a3dc620d-deb3-4132-be17-4b17f755e75e)

After:
![installed-after](https://github.com/stashapp/stash/assets/131594657/b24643ab-45ec-48bc-8ce3-41f2491fd39c)

**Comment by Tetrax-10** [comment]
Good idea, I have created [Auto select updatable plugins and scrapers](https://github.com/Tetrax-10/stash-stuffs?tab=readme-ov-file#1auto-select-updatable-plugins) to update manually or using [Auto update plugins and scrapers](https://github.com/Tetrax-10/stash-stuffs/tree/main/Plugins/AutoUpdatePluginsAndScrapers) for people who don't want to worry about updates, it just auto update on website startup.
