### ISSUE TITLE
[Bug Report] Adding Performer from Scene Tagger Fails

### ISSUE THREAD

**Issue by bdbenim** [stashapp/stash#4437]
**Describe the bug**
When scraping a scene from stash-box in the scene tagger view, the user is prompted to add missing performers with their data pre-filled from stash-box. If a performer being added has an alias matching their primary name, adding them to the user's stash instance will fail.

**To Reproduce**
1. Go to the scene tagger view and select a stash-box instance as the source
2. Choose a scene which exists in stash-box and for which not all performers are in the local database (if necessary, delete a performer or their Stash ID for testing)
3. Click on 'Scrape by fragment'
4. For the missing performer, click 'Create' and then 'Save'
5. If the performer has an alias matching their primary name, an error message will be displayed

**Expected behavior**
The duplicate alias should be ignored and the performer added as normal. Alternatively, details should be editable in the "Create Performer" modal, which would allow the user to manually delete the bad data.

**Screenshots**
![image](https://github.com/stashapp/stash/assets/97994155/648cfd86-6ffa-4711-a846-25520882ab31)

**Stash Version: (from Settings -> About):**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 0.24.1

**Comment by Maista6969** [comment]
Just had a related issue pop up with performers who have duplicate aliases on StashDB

StashDB considers different casings of the same name to be unique aliases, see for example [Syren De Mer](https://stashdb.org/performers/aac10eea-51c0-4574-8336-8f0a4de587a5) who has both "Syren DeMer" and "Syren Demer". Should Stash follow this pattern as well, or should we deduplicate these aliases when adding new performers? If so, which one to pick? 😅
