### ISSUE TITLE
[Feature] Mixed Media Library

### ISSUE THREAD

**Issue by ThatDeltaGuy** [stashapp/stash#4449]
**Is your feature request related to a problem? Please describe.**
I have several collections that are both video and image (inc. gifs) but currently there's no way to keep these separate, They'd be split into images or scenes.

**Describe the solution you'd like**
A third type of 'library', one that keeps videos in the same 'galleries' as images but doesn't try to add them as scenes

**Describe alternatives you've considered**
There's not really any alternatives within stash, the only viable alternative I've found outside of stash is PiGallery2. Plex used to work, but they've gutted the image features.

**Comment by yoshnopa** [comment]
I have implemented a feature that introduces "Clips", meaning that videos are treated as image loops, much like gifs. Those videos will then be showing up in the image section and should also be working in galleries (although I didn't try that specifically, there is no support for scanning them in .cbz-files though). They will also have an animated preview image, that has to be generated seperately (see Generate previews for image clips in the library scan options or the generate options). They work in the image carousel as well as in the details page.
This can be achieved in two ways:
Either turn off the videos in the library you want to be interpreted as images and clips, or remove the media extensions you want to treat as images/clips as from the video extensions and add it to the image extensions. You have to remove them from your library before rescanning, there is no function to treat them differently on rescan.
You can also look into the help section under Images and Galleries.
Does that cover your request?

**Comment by ThatDeltaGuy** [comment]
Yep, there's a little checkbox for 'Scan Video Extensions as Image Clip' that must have been added relatively recently

**Comment by anthonynogales** [comment]
Could you consider adjusting the behavior so that if a video file is located in a folder containing a .forcegallery file, it is automatically excluded from the Scenes category and instead treated as a clip? This would, I feel, streamline the process of organizing galleries, allowing specific videos to be treated as image loops without manually altering file extensions or disabling video support for the entire library.
