### ISSUE TITLE
[Feature] Notes taking and last checked

### ISSUE THREAD

**Issue by MrGlasspoole** [stashapp/stash#4452]
1. Notes taking
It would be nice there would be a way to make notes on scenes, movies, galleries and performers.
A field where you can put in your own notes.
Then a filter to show everything that has a note.

2. Last Checked
A field for last checked would be nice.
Lets say you want to check if there is new stuff from a performer but you don't want to check every 3 weeks.
If you have a date you can say: "oh its been a year since I last checked, so lets check if there's something new"
Or you have the DVD and there is no Blue-ray out yet and you want to check from time to time.

**Comment by WithoutPants** [comment]
I believe this is a niche use case and should therefore be considered as a plugin idea instead of core functionality.

**Comment by MrGlasspoole** [comment]
I wonder it's a niche?
I miss this also in Kodi and Jellyfin.

I have Excel tables for all Kind of stuff just because of this.
Lets say you have a certain version of a movie, do other not have the need to remember why the have this version?
Lets say you have the DVD in 4:3 or the Blu-ray from a certain label because the others are 16:9 and the heads or feeds are cut off.

**Comment by AdultSun** [comment]
Niche isn't to say it isn't useful, just that it wouldn't be considered as core functionality for Stash. We're currently working on a draft of both a mission statement and roadmap that should better detail what is considered core functionality, so keep an eye out for that. A big part of recent development efforts is to improve on plugin integration to make it easier to make these kinds of tools as plugins.
