### ISSUE TITLE
[Bug Report] Tag name not displaying spaces

### ISSUE THREAD

**Issue by QxxxGit** [stashapp/stash#4455]
When using a saved filter, the spaces aren't displaying for this specific tag. I'm not sure what's causing this, it doesnt happen with other tags. Any ideas?

Steps:
* Use a saved filter, open the edit filter dialog, expand the tags section.

Occurs in the latest version. I'm also using Firefox on Ubuntu.
![Screenshot from 2024-01-12 20-37-06](https://github.com/stashapp/stash/assets/71350626/04cfcec4-f76f-4129-be8d-3b17ba1ab896)
![Screenshot from 2024-01-12 21-01-59](https://github.com/stashapp/stash/assets/71350626/a62c7a23-653f-40e5-8213-11780c5a0931)
![Screenshot from 2024-01-12 21-03-55](https://github.com/stashapp/stash/assets/71350626/b1895ff0-e50c-4455-8b79-66c771e4300f)

**Comment by WithoutPants** [comment]
If you create a new saved filter with the same criteria (built from a fresh query) can you reproduce the issue?

**Comment by QxxxGit** [comment]
Doing that didn't reproduce the issue. Maybe there were changes to the filter encoding the queries at some point, and this filter is a leftover from a bug fix?

**Comment by WithoutPants** [comment]
Yeah, I'm pretty sure it's a migration issue. Unless it's a widespread issue it might not be worth tracking down, especially since there's a workaround.
