### ISSUE TITLE
[Feature] Allow multiple Data18 entries on stashdb server

### ISSUE THREAD

**Issue by UltraHKR** [stashapp/stash#4460]
**Describe the problem**
The stashdb server is unable to save *multiple* Data18 entries... I hit this limitation

**Describe the solution you'd like**
Allow multiple entries like a local stash instance. 

**Describe alternatives you've considered**
Spam the comment box with metadata, when submitting scenes...

**Comment by WithoutPants** [comment]
This is out of scope for this repo. Please raise in the [stash-box](https://github.com/stashapp/stash-box) repo.
