### ISSUE TITLE
Cannot submit performer to any stash-box

### ISSUE THREAD

**Issue by shanty-chits** [stashapp/stash#4464]
**Describe the bug**
I am not able to submit performers to any stash-box (StashDB, FansDB) from the Performers screen.

**To Reproduce**
1. Go to a performer
2. Click on "Submit to Stash-Box"
3. Select appropriate stash-box (all have edit privileges)
4. Dialog says "Submission successful," and there is no error in the terminal, but the edit does not appear on the site (pending or completed)

**Screenshots**
<img width="497" alt="Screenshot 2024-01-16 at 7 24 43 PM" src="https://github.com/stashapp/stash/assets/92681442/9d46832b-4db1-49f9-a4b9-35ab3782de4a">

**Stash Version: (from Settings -> About):**
v0.24.3

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari

**Comment by DogmaDragon** [comment]
It goes to the Drafts page, where you need to review the submission, check for missing details or add extra, and then click Submit. Drafts button is displayed in the menu bar on stash-box sites.
`https://stashdb.org/drafts`
`https://fansdb.cc/drafts`
