### ISSUE TITLE
Studio Tagger removes stashbox id from the non scraped stashbox

### ISSUE THREAD

**Issue by floydcg** [stashapp/stash#4491]
Running the latest develop, and it seems that using the scene tagger will over-write the stashID that is currently listed there, for example, if I run it against the stashdb instance, and an existing entry is there (such as from TPDB) it will remove that entry and replace it with the scraped entry. if you do the opposite such as scrape the studio from TPDB, the stashdb entry will be replaced. seems like this is something that recently changed as I've been able to scrape studios from different DBs in the past.

**Comment by hypstu** [comment]
I'm also seeing this. I wanted to help update studio urls and images for parity across stashdb and porndb and this bug breaks the ability to do that quickly.
