### ISSUE TITLE
[Feature] Image Polygonal Annotations for Machine Learning Labeling/Training

### ISSUE THREAD

**Issue by HybrisF** [stashapp/stash#4507]
**Is your feature request related to a problem? Please describe.**
I think the whole project could benefit if images and galleries have the functionality, to label objects directly inside of the web image view and store them logistically.

**Describe the solution you'd like**
When viewing an image, a separate mode could be activated to draw COCO conform polygons on an overlay canvas of the image and assign labels to them. In addition to the work for the marking of objects in the already processed photos, the markings could be used for the training of data models in the backend to process photos that have not yet been viewed. For the time being, however, my enquiry only relates to the possibility of marking objects in a similar way to the tool [LabelMe](https://github.com/labelmeai/labelme).

**Describe alternatives you've considered**
Of course this can be performed offline with the mentioned tool, but having all in one place could be an advantage. As I said, the labels drawn by a user, are also great data for e.g. search hits.

**Comment by WithoutPants** [comment]
This sounds out of scope of the main function of stash, and likely serving a niche group of users. It is potentially something more suited to a plugin.
