### ISSUE TITLE
[Bug Report] Upgrading to new authentication from old causes ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by rushing-pixel** [stashapp/stash#451]
**Describe the bug**
If upgrading to the latest develop changes from old, when i try to access stash i get ERR_TOO_MANY_REDIRECTS. its either `/login?returnURL=%2Fmigrate` or just straight `/migrate` that it gets redirected to and stuck on. 

**To Reproduce**
1. Have running stash prior to new auth #440 
2. Pull new changes and rebuild and start stash
3. Try to access stash and get ERR_TOO_MANY_REDIRECTS
4. Clear cookies and other stuff
5. Try to access stash and get ERR_TOO_MANY_REDIRECTS

**Expected behavior**
Expected behaviour is /migrate or /login I believe.

**Desktop (please complete the following information):**
 - OS: Linux running stash and Windows 10 accessing stash
 - Browser: Chrome 80.0.3987.163

**Additional context**
It is currently running behind a traefik reverse proxy, if relevant.

**Comment by WithoutPants** [comment]
Thanks for the report. A workaround should be to clear the credentials settings manually in the config.yml file, then you should be able to access your stash page to migrate it, then you can reset the credentials.

**Comment by rushing-pixel** [comment]
Thanks. that worked for now, feel free to close this or keep it open until the pull request is done!
