### ISSUE TITLE
[Feature] Tag Mistake in Duplicate Scenes

### ISSUE THREAD

**Issue by Blabss0** [stashapp/stash#4516]
**Is your feature request related to a problem? Please describe.**
At times, using the "Duplicate Scenes" tool can be challenging when numerous false positives are identified.

**Describe the solution you'd like**
It would be helpful to have a "Mistake" button, allowing users to hide scenes that were mistakenly identified as duplicates the next time the tool is used.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by feederbox826** [comment]
duplicate of https://github.com/stashapp/stash/issues/1656
