### ISSUE TITLE
[Bug Report] Video files smaller than 1kb in .disc format are not recognized

### ISSUE THREAD

**Issue by kimiincn** [stashapp/stash#4522]
I was using TMM to create files in the format .disc, and when I imported these >1kb files into the library for scanning, I found that the system didn't recognize them, but these files are recognized in clients like emby.

I'm not sure if I'm doing something wrong or if it's unsupported. Hope to get a reply :)

**Comment by HereIam80** [comment]
I don't really know what TMM is and I am also unfamiliar with a .disc file format.
Stash only scans in media like video and image files. You can find the supported file types under settings => library.

![image](https://github.com/stashapp/stash/assets/31324543/06a2088a-7d82-476d-a3cc-ebae6be20a7a)

**Comment by kimiincn** [comment]
I'm sorry, the TMM I mentioned earlier is “tinymediamanerge”, and “.disc” files is a movie file format created by tinymediamanager. I tried to change the filename format to ".mp4" and it is still not readable and recognizable because the file size is only a few dozen bytes, I'm not sure if there's a file size limit and it's being filtered out and that's why it's not being readable, but they are readable in emby.

**Comment by HereIam80** [comment]
I don't think "disc" is a proper video file format. Especially if it is just a few kb in or less in size. It is properly just stored metadata that emby can read and just renaming the file doesn't change the contents of the file.
You have to give stash the actual video files.

**Comment by WithoutPants** [comment]
This is unsupported. Stash only ingests media files like mp4/mkv/wmv/etc.
