### ISSUE TITLE
[Feature] Bypassing government censorship when scraping

### ISSUE THREAD

**Issue by Student-Jasons** [stashapp/stash#4531]
**Is your feature request related to a problem? Please describe.**
Scraping takes an excessive amount of time and the plugin doesn't work properly more than 80% of the time.

**Describe the solution you'd like**
We checked the cause and found that the sites being scraped were blocked by the South Korean government.
The problem was caused by DPI, which is typically solved by using GOODBYEDPI (open source and CLI-based).

**Describe alternatives you've considered**
I hope this is possible, but if not, I think you can work around it by letting me use it through a proxy, using a proxy from a different country, or having the proxy share traffic with the DPI blocker.

**Additional context**
Thank you for reading this long post and I admire the fact that you are open-sourcing your project, making a positive impact on open-source Saint-Germain, and doing it for free and without any compensation. I don't speak English very well, so this post is written in a translator and may be difficult to read.
If you need any further information, please write back.
For your information, the goodbyedpi option I use (and most of the time I see it working on my site) is goodbyedpi.exe -5.

**Comment by NodudeWasTaken** [comment]
This should already be possible given https://github.com/stashapp/stash/pull/3284

**Comment by Student-Jasons** [comment]
Thank you for your response. We'll close the issue.
