### ISSUE TITLE
[Bug Report] error 401 from theporndb for movies and for jav

### ISSUE THREAD

**Issue by Testacda** [stashapp/stash#4545]
**Describe the bug**
Unable to scrape data with theporndb movies and theporndb jav source
`ERRO[2024-02-11 09:40:44] scrapeSingleScene: input: scrapeSingleScene scraper ThePornDBMovies: http error 401:Unauthorized
`**To Reproduce**
1. go to any video
2. go to edit
3. click scrape with theporndb for movies

**Expected behavior**
Should change the metadata of the file but it just shows a 401 error

**Screenshots**
![image](https://github.com/stashapp/stash/assets/80134190/1ca6be57-675b-420d-8903-a7222feaa7e2)

**Stash Version: (from Settings -> About):**
v0.24.3-32-g9981574e

**Desktop (please complete the following information):**
 - OS: windows
 - Browser tried arc browser and crhome
 - Version arc: v0.8.0.6716 | chrome: Version 119.0.6045.160 (Official Build) (32-bit)

**Additional context**
I just downloaded stash and ran the exe, scanned a library, and tried to get metadata but it showed that error.

**Comment by Maista6969** [comment]
This does not belong in the Stash repo but the [CommunityScrapers](https://github.com/stashapp/CommunityScrapers) repo

These scrapers require an API key, please open the scraper files (`ThePornDBMovies.yml` and `ThePornDBJAV.yml`) in a text editor and scroll to the bottom, there are instructions there for how to get an API from TPDB

**Comment by Testacda** [comment]
Oh ok, thanks.
