### ISSUE TITLE
Page filters no longer sticking after page refresh

### ISSUE THREAD

**Issue by floydcg** [stashapp/stash#4554]
Just loaded the latest develop build and it appears that if you apply a filter, such as : is missing > Performer, if you refresh the page the filter is no longer applied, I went back to v0.24.3-30-ga16f3da3 (the last build I had before updating to v0.24.3-38-gdad4ab6a and the filter sticks on refresh.

**Comment by floydcg** [comment]
Also wanted to add that the URL has the correct filter in it, (&c=("type":"is_missing","value":"performers","modifier":"EQUALS")&sortby=date)
but the filter isn't applied to the view unless you go and reload the filter by hand

**Comment by WithoutPants** [comment]
I'm unable to reproduce this on `v0.24.3-44-g440c261f5`.

Steps I tried:
1. Open scenes page
2. Edit filter -> missing performer
3. Verified only scenes missing performers were shown
4. Refreshed the page
5. Verified same filter was applied

**Comment by floydcg** [comment]
Looks like whatever was causing it might have been fixed then it a this build, on the previous one mentioned, I tried 3 different browers and all were the same. I'll go ahead and close this

**Comment by floydcg** [comment]
Triggered it a different way, added a filter for stashid, put in the URL of TPDB which gave results missing that stashbox id, refreshed page and it returns all records with all the filters gone this time.

**Comment by floydcg** [comment]
userscripts/userscript plugins also seem to be broken on studios at least. Rolling back to v0.24.3-30-ga16f3da3 gives me this : 
![image](https://github.com/stashapp/stash/assets/56641623/946d904a-346d-4ad7-bb1b-a74b08fa56bf)

but if I update to v0.24.3-44-g440c261f5
![image](https://github.com/stashapp/stash/assets/56641623/adcc39c1-40ec-4ac0-a111-281395e2b703)
looks to be related to the URL missing the the filtered values

**Comment by WithoutPants** [comment]
Can you please provide specific step by step instructions on how to reproduce this? I'm still unable to reproduce with the new instructions provided.

**Comment by floydcg** [comment]
All I've had to do is apply a filter, so if I go to a studio with say 344 entries and add the filter stashid is null, which it will return the results of is null so say 13 entries. If you then reload the page via browser refresh, the filter will be gone and 344 scenes will be returned again. I've disabled all plugins, all custom CSS and tried Firefox edge and chrome (Firefox was never used previously) and all of them remove the the filters and return all results. The URL also always stays to the studio ID number now without any filter following it. The reason for the refresh in my case was sometime the colorizer plugin won't apply or the search all/save all buttons won't be there. If I go back to the last older dev build I have, it works fine. Going past this build, no amount of refresh will get these to show up and the filters drop off.

**Comment by WithoutPants** [comment]
Ok, I've managed to reproduce this.

For reference, these are the steps to reproduce - in future, please write steps like the following:
1. Open the studio detail page for a random studio
2. In the Scenes tab, add more filter criteria - for example, filter by stash id is null
3. The URL remains the same as it was `/studios/xx` and is not updated to include the filter string.

Long form instructions are prone to misunderstanding or incomprehension.

This is almost certainly introduced by #4538.

**Comment by floydcg** [comment]
My apologies, I'll try and follow that template in the future.
