### ISSUE TITLE
[Bug Report] Some images have the wrong proportions on image wall

### ISSUE THREAD

**Issue by onlyhooops** [stashapp/stash#4555]
**Describe the bug**
I use Synology NAS 923+ and deploy Stash via Docker.

When adding large image files (photos taken with a DSLR camera, for example) using Stash, the thumbnails displayed in image wall mode do not have the correct proportions.

**Expected behavior**
It seems that "stash" is unable to generate thumbnails with correct proportions for specific image files or is unable to display thumbnails correctly in the photo wall view.

**Screenshots**
<img width="1628" alt="22222" src="https://github.com/stashapp/stash/assets/34241608/45658104-2290-4109-b85f-0f83210203ab">
<img width="731" alt="111" src="https://github.com/stashapp/stash/assets/34241608/ad78b859-2c2c-46ee-ac76-409a6a37ea9e">
**photo metadata**
[exiftool.txt](https://github.com/stashapp/stash/files/14268019/exiftool.txt)

**Comment by onlyhooops** [comment]
original file
https://1drv.ms/f/s!AjxMVkG84JkZgfJ5n8tP-fdEbtd-oQ?e=HwbQsn

**Comment by onlyhooops** [comment]
My tests have revealed that whether running Stash on Docker, or directly on Linux, macOS, or Windows, the thumbnail aspect ratios are incorrect in the photo wall mode when adding photos taken with Nikon DSLR cameras. There is no such issue with photos from other brands like Canon or Sony (though the testing might not have been exhaustive).

**Comment by onlyhooops** [comment]
I would greatly appreciate it if the developers could address and resolve this bug.

**Comment by SheWantsTheD-pastes** [comment]
The proportion seems to be correct, but with the wrong `width` and `height` ascribed by the backend. 
With the ID 5868 mapped to one of the sample images, the following query:
```graphql
query {
  findImage(id: 5868) {
    ... on Image {
      id
      visual_files {
        ... on ImageFile {
          path
          height
        	width
        }
      }
    }
  }
}
```
returns the following value:
```json
{
  "data": {
    "findImage": {
      "id": "5868",
      "visual_files": [
        {
          "path": "D:\\Backups\\DSC_0052.jpg",
          "height": 5504,
          "width": 8256
        }
      ]
    }
  }
}
```

I suspect this has to do with the non-zero orientation in the EXIF matadata:
```
Exif Image Width                : 8256
Exif Image Height               : 5504
...
Orientation                     : Rotate 270 CW
```

**Comment by SheWantsTheD-pastes** [comment]
This seems to happen for other kinds of images, as well. In particular, I'm noticing a lot of animated webps in particular reporting (via the same graphql query) a height and width of 0, leading to react-photo-gallery using their native width, and filling the row's height -- making for some very awkward-ly stretched images.

**Comment by SheWantsTheD-pastes** [comment]
possibly duplicated in #4738
