### ISSUE TITLE
[Bug Report] Sub-Tags not fitted to screen resolution

### ISSUE THREAD

**Issue by SirCumAlot1988** [stashapp/stash#4559]
**Describe the bug**
Sub-Tags are not displayed properly, If their number exceeds a certain amount. You have to zoom out to see all of them.

**To Reproduce**
1. Create a new Tag
2. Create a large number of sub-tags
3. Look at the tag created under step nr 1 in the tag view. You will not see all sub-tags as long as you do not zoom out.

**Expected behavior**
Tags should be fitted to the screen resolution. If the number is too big, a new line should be created.

**Screenshots**
![Screenshot 01](https://github.com/stashapp/stash/assets/98083850/f23878e2-455f-4e42-aa3e-2adf616fa807)
![Screenshot 02](https://github.com/stashapp/stash/assets/98083850/deb023c2-2cae-430d-ba3f-909078d4ad91)

**Stash Version: (from Settings -> About):**
v0.24.3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Tested with Firefox (122.0.) and Chrome (121.0.6167.185)

**Comment by oikmeg** [comment]
I see this issue as well. If you click the arrow (supposedly to minimize) then the sub-tags properly wrap.
