### ISSUE TITLE
[Bug Report] Movie schema issues

### ISSUE THREAD

**Issue by WithoutPants** [stashapp/stash#456]
From #398:

The scene -> movie relationship table has a unique index on movie id and scene index, meaning that you cannot assign the same movie id/scene index combination to more than one scene. I think this unique constraint should be between movie id and scene id, not the scene index.

Movie name should be not null.

Duration and rating should be numeric.

**Comment by bnkai** [comment]
From 398 points 6,7  adding two extra fields producer ( probably plain string) and studio (fk) is it relevant for now or only bug fixes?

**Comment by WithoutPants** [comment]
Seems like a good time to do it.
