### ISSUE TITLE
[Bug Report] Scene Edit Panel Scrape From URL dialog tag select box popover in alignment with tag select

### ISSUE THREAD

**Issue by elkorol** [stashapp/stash#4577]
**Describe the bug**
On the scene edit panel, scraper from url. Once it returns the results. If you have tag popups on hover enabled. 

For example clicking on the tag select, if you move the mouse down a popover appears in alignment with the tag list, so if you move the mouse back up you can't get to the entries further up the list that are now hidden by the tag popover without taking the mouse away from the list first.

**Expected behavior**
I think the popovers should render to the side of the tag list. Which I can fix and make a pr but I'm unsure if WP wants to migrate the new way the performer select renders images within the select list for any tag select list. So I am making this issue before doing any changes to see where the direction is heading at.

**Stash Version: (from Settings -> About):**
v0.24.3

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 121.0.6167.185 (Official Build) (64-bit)

**Comment by WithoutPants** [comment]
I had issues rendering the images next to the tag names, and I think there's limited utility in the tag images in the select box (compared to performers at least).
