### ISSUE TITLE
[Bug Report] BMP images are displayed as <video>

### ISSUE THREAD

**Issue by Sketch6307** [stashapp/stash#4583]
**Describe the bug**
BMP images are displayed as <video> instead of <img>. (They are detected as images though, i.e. the URL is /image/###### and they are shown in the Images views)

`<video loop="" autoplay="" controls="" class="m-sm-auto no-gutter image-image" alt="*.bmp" src="http://localhost:9999/image/160413/image?t=1705371309" style="width: 100%; height: 100%;"></video>`

**To Reproduce**
1. Download a BMP
2. Open it
3. See a broken video player

**Expected behavior**
1. Download a BMP
2. Open it
3. See the BMP

**Screenshots**
https://i.imgur.com/vt7jIfT.png

**Stash Version: (from Settings -> About):**
0.24.3

**Desktop (please complete the following information):**
Firefox, Chrome

**Additional context**
Everyone loves thoroughly redundant bug reporting formats

**Comment by WithoutPants** [comment]
`.bmp` isn't a supported format for display in the browser. I wouldn't expect the file to display at all in the browser, _but_ it shouldn't be trying to display it as a video either.
