### ISSUE TITLE
[Bug Report] Can't set parallel task for scan/generation to 0

### ISSUE THREAD

**Issue by apgrc** [stashapp/stash#4590]
**Describe the bug**
"Confirm" button disabled when selecting `0` on "Number of parallel task for scan/generation".

**To Reproduce**
1. Go to `Settings > System > Parallel Scan/Generation`
2. Click on `Edit` of `Number of parallel task for scan/generation`
3. Set value to `0`
4. Confirm button is disabled.

**Expected behavior**
The input help says:

> Set to 0 for auto-detection. 

The button to confirm should be enabled when the input is 0.

**Screenshots**
If applicable, add screenshots to help explain your problem please ensure that your screenshots are SFW or at least appropriately censored.

![Screenshot_20240218_201525](https://github.com/stashapp/stash/assets/43510217/daa66fc8-624b-4e40-b349-c21ebfbe3b68)

**Stash Version: (from Settings -> About):**

![Screenshot_20240218_201716](https://github.com/stashapp/stash/assets/43510217/0fd450d6-61c6-400c-9d3d-02d25e6be384)

**Comment by WithoutPants** [comment]
Fixed in dev build
