### ISSUE TITLE
[Bug Report] Error when scraping performer with duplicate alias

### ISSUE THREAD

**Issue by Maista6969** [stashapp/stash#4596]
**Describe the bug**
A user on Discord [reported an issue](https://discord.com/channels/559159668438728723/559159931505213440/1209234970896236654) when scraping a performer from PMVStash and getting an error message about duplicate aliases. After going through their performers and aliases to make sure they didn't have a local duplicate we narrowed it down to that particular performer having duplicate aliases on the stash-box itself: `MyCherryCrush` and `Mycherrycrush`

I do not have an account on PMVStash and I wasn't able to find a performer on StashDB with a duplicate alias, but over on FansDB [Brandi Braids](https://fansdb.cc/performers/4d02fc23-75ca-4c8a-804c-b492b2a8d808) currently has the same kind of duplicate alias: `BrandiBraids` and `brandibraids`

edit: Brandi Braids has had her duplicate alias removed

**To Reproduce**
I believe the original issue occurred when scraping a performer as part of a scene, but it also occurs when you try to add the performer directly:

1. Go to Performers page
2. Switch to Tagger view and configure it to use FansDB as the source
3. Click "Batch Add Performers"
4. Search for "Brandi Braids" and select the only performer that comes up

No performer is created and no error is displayed, but the logs output `Failed to create performer Brandi Braids: performer contains duplicate alias 'brandibraids'`

**Expected behavior**
Just like creating a performer who has an alias that's the same as their own name, I expect the duplicate alias to be dropped and the performer to be created. This was fixed in #4443 

**Stash Version: (from Settings -> About):**
v0.24.3-46-g6fb1c41a

**Comment by BugGeeker** [comment]
I'm a Chinese, and sorry about my english.
Performers in my stash is named to  Japanese or Chinese, just like 三上悠亜 or 三上悠亚, I can find 'Yua Mikami' on stashdb，and '三上悠亚' is an alise on stashdb, when I save the scrape result, it will be failed.
Why not automatic remove the duplicate alise when using 'tagger'?
![image](https://github.com/stashapp/stash/assets/35688923/6a10844e-8c7f-4dc5-83ea-0854e631305c)

**Comment by Maista6969** [comment]
This still happens on the latest develop build, after #4801 

Go to Performer Tagger view, select Batch Add Performers with StashDB as the source and fill in "[AK Gingersnaps](https://stashdb.org/performers/06a306f0-b217-48c6-8de0-c5872da38799)" and you'll get this error message in the logs:
```
ERRO[2024-05-03 14:50:47] Failed to create performer AK Gingersnaps: performer contains duplicate alias 'AKGingersnaps'
```

She has the alias "AKGINGERSNAPS" as well as "AKGingersnaps"
