### ISSUE TITLE
Mass tagging videos in folder

### ISSUE THREAD

**Issue by commynota** [stashapp/stash#46]
A mass tagging feature would be really nice. For example I have all videos from a single performer in one folder, it would be nice to tag every video in that folder to that performer at once. There are requests for ML tagging and tagging from the file name, but this is way easier I guess. This would just need a folder selection and then every video in that folder gets the tag. Maybe still merge this issue with the similar ones. Keep up the good work, love it so far.

**Comment by WithoutPants** [comment]
Does #92 cover this sufficiently?

**Comment by Leopere** [comment]
I would say it does, for the most part, we're eventually going to expand on the tagging system but for 1.0 where #92 takes us, it sounds sufficiently addressed.

**Comment by bnkai** [comment]
Using the name of the folder in the scenes search input and using #92 to select all and tag / add performer i also think it covers that. Closing , feel free to  reopen if you think it doesn't.

**Comment by WithoutPants** [comment]
@Leopere why was the invalid label added to this?

**Comment by Leopere** [comment]
@WithoutPants it was the closest to a duplicate label we had.
