### ISSUE TITLE
[Bug Report] .forcegallery only works if present on initial scan

### ISSUE THREAD

**Issue by BonerFide** [stashapp/stash#4611]
If you have already scanned in a folder with images, and you later add a .forcegallery file to it, it will not create a gallery.

**To Reproduce**
1. Create a folder with a number of images
2. Scan the folder
3. Add a .forcegallery file into the folder
4. Scan the folder
5. Gallery is not created!
6. If you remove the folder from that path, clean the parent to prune the images, then put it back with the .forcegallery file in it when you scan the files back in again, the gallery is created. 

**Expected behavior**
1. Create a folder with a number of images
2. Scan the folder
3. Add a .forcegallery file into the folder
4. Scan the folder
5. Gallery should be created from images in that folder if not already present

**Stash Version: (from Settings -> About):**
v0.24.3

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 121.0.6167.187

**Additional Context**
This still doesn't work if you move the folder or rename it as a re-scan just updates the paths. You MUST clean all the images out and scan them back in to get the .forcegallery to work. Can be a problem if you have images and videos in a folder where the videos have metadata, or the images themselves already have metadata you don't want to clean and re-add.

**Comment by WithoutPants** [comment]
This defeats a big part of the utility of this feature. I'll aim to get a fix in this release.

**Comment by QxxxGit** [comment]
I've ran into this as well a few times. The scan *will* pick up `.forcegallery` if an entirely new image is scanned in the folder

i.e.

* Scan folder with images
* Add .forcegallery to folder and rescan (gallery not created)
* Add new image to folder and rescan (gallery created)

@WithoutPants feel free to ping me in Discord for testing
