### ISSUE TITLE
[Feature] Add last_played_at to filters

### ISSUE THREAD

**Issue by indigocalifornia** [stashapp/stash#4659]
**Is your feature request related to a problem? Please describe.**
Feature request

**Describe the solution you'd like**
To be able to filter scenes which are have been played last later/earlier/etc compared to value

**Describe alternatives you've considered**
Sorting by Last played at

**Additional context**
Adding last_played_at to filters would allow soring by a different metric, e.g. Play count

**Comment by WithoutPants** [comment]
Closed by #4829
