### ISSUE TITLE
[Bug Report] Date Sorting Options Don't Work As Expected

### ISSUE THREAD

**Issue by lots0logs** [stashapp/stash#466]
**Describe the bug**
TBH not sure if this is a bug or just the way it's intended to work currently. I'm trying to sort scenes by the modified dates of the video files themselves. There are three options for sorting by date but none of them appear to do what I want. Am I missing something?

**To Reproduce**
1. Click Scenes
2. Change the sort to one of the date sort types.

**Expected behavior**
Scenes sorted by the modified date of the file from the filesystem, not of the scene's entry in the database. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 81

**Comment by bnkai** [comment]
This is the intended usage not a bug.
In the DB we have a date field that optionally gets the date  tag if available  during scaning ( usually not useful ). That is not the file date. This date is supposed to reflect the scene date.
Thus as you mentioned the sort you  want is not supported.

**Comment by lots0logs** [comment]
Can't we just edit this issue?
