### ISSUE TITLE
[Bug Report] Subfolders dont get indexed

### ISSUE THREAD

**Issue by michaelxxl2** [stashapp/stash#468]
[Bug Report] Subfolders dont get indexed

Is this a bug or a feature?

**Comment by bnkai** [comment]
What do you mean don't get indexed? They get scanned fine afaik. Can you provide an example/sample ?

**Comment by VonTittyslappen** [comment]
Please can you elaborate?

**Comment by WithoutPants** [comment]
Closed pending further information.
