### ISSUE TITLE
[Feature] Allow Sorting Scenes By Last Modified Date Of Video File

### ISSUE THREAD

**Issue by lots0logs** [stashapp/stash#469]
**Is your feature request related to a problem? Please describe.**
I want to sort scenes by the modified dates of the video files themselves so that they appear in order from added most recently to least recently. There are three options for sorting by date but none of them appear to do what I want.

**Describe the solution you'd like**
It should be possible to sort by the last modified date of the file on the filesystem.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bikkmakk86** [comment]
In the meantime you can set the value of `created_at` to the last modification time of scene file with this python script:

```python
import sqlite3
import os
import datetime

DB_PATH = "d:/downloads/_temp/stash-go.sqlite"
TIMEZONE_DELTA = datetime.timedelta(hours=1)

with sqlite3.connect(DB_PATH) as db:
    c = db.cursor()
    c.execute("SELECT id, path FROM scenes")
    for row in c:
        print(f'{row[1]}: {datetime.datetime.fromtimestamp(os.path.getmtime(row[1]))}')
        db.execute("UPDATE scenes SET created_at = ? WHERE id = ?", (datetime.datetime.fromtimestamp(os.path.getmtime(row[1]), datetime.timezone(TIMEZONE_DELTA)).isoformat(), row[0]))
    db.commit()
```

Don't forget to set the constants appropriately and to do a backup first.
