### ISSUE TITLE
[Bug Report] At Least, Movies, Performers, Studios and Tags - Not honouring Sort Name Ascending with numbers

### ISSUE THREAD

**Issue by elkorol** [stashapp/stash#4695]
**Describe the bug**
There seems to be a bug with numerical name sorting. I don't know how far it goes.

**To Reproduce**
1. Go to Movies, Performers, Studios or Tags (It may be in other areas too)
2. Create two objects for example 1 with the name "2" and the other with "18"
3. Return to the object type main page and sort by name ascending. 
4. See that 2 will appear before 18

**Expected behavior**
Should honour numerical sorting

**Stash Version: (from Settings -> About):**
v0.25.1 - Build hash: bf7cb78d
**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: Version 122.0.6261.129 (Official Build) (64-bit)

**Comment by elkorol** [comment]
It's the same at least in the movies select for a scene edit

**Comment by WithoutPants** [comment]
This is called natural sort, and is like this by design so the `Big Butts #123` appears after `Big Butts #2`. Introduced in #943.
