### ISSUE TITLE
[Bug Report] When sorting scenes by O-Counter, loads indefinitely.

### ISSUE THREAD

**Issue by imgbrg33** [stashapp/stash#4696]
**Describe the bug**
When I sort my scenes my O-Counter, whether it be ascending or descending, stashapp loads indefinitely. This didn't happen before I updated to the most recent update.

**To Reproduce**
1. Go to Scenes
2. Click on Sort By O-Counter
3. See error

**Expected behavior**
Shows my scenes sorted by O-Counter count, whether it be ascending or descending.

**Stash Version: (from Settings -> About): v0.25.1

**Desktop (please complete the following information):**
 -Browser: Microsoft Edge

**Comment by WithoutPants** [comment]
I'm unable to reproduce this. Are you able to check if the `graphql` request is returning the scenes in the browser dev window? Are there any other console error messages?

**Comment by feederbox826** [comment]
IIRC this was later attributed to a missing O-Counter index on the database. The solution is to add an index manually with SQL

```sql
CREATE INDEX `index_scenes_view_dates` ON `scenes_view_dates` (`scene_id`);
CREATE INDEX `index_scenes_o_dates` ON `scenes_o_dates` (`scene_id`);
```
[discord](https://discord.com/channels/559159668438728723/559159910550732809/1257881084746797096)

**Comment by Gykes** [comment]
> I'm unable to reproduce this. Are you able to check if the `graphql` request is returning the scenes in the browser dev window? Are there any other console error messages?

Were you able to fix this? Based on the discord link it seems like you found a solution back in February sometime.
