### ISSUE TITLE
[Bug Report] hwaccel not supported on AMD APU due to failing check

### ISSUE THREAD

**Issue by Jglrz** [stashapp/stash#4701]
ffmpeg hwaccel `h264_vaapi` tests fail with AMD APU on Linux (tested in Docker) because `stash/pkg/ffmpeg/codec_hardware.go` tests scaling with `videoFilter = videoFilter.ScaleDimensions(-2, 160)`, which results in `scale=%v:%v` at `scale=224:160`, but the driver requires minimum width to be at least 256px.

```
[h264_vaapi @ 0x56569028cf80] Driver does not support some wanted packed headers (wanted 0xd, found 0x1).
[h264_vaapi @ 0x56569028cf80] Hardware does not support encoding at size 224x160 (constraints: width 256-4096 height 128-2304).
```

**Comment by WithoutPants** [comment]
Fixed by #4765
