### ISSUE TITLE
Accessing Stash v0.25.1 using safari from iPad Air (1st Generation released 2013) iOS 12.5.5 returns blank page

### ISSUE THREAD

**Issue by leocordis27** [stashapp/stash#4712]
**Describe the bug**
Accessing Stash using safari from iPad Air (1st Generation released 2013) iOS 12.5.5 returns blank page.
I use Portainer to auto update Stash. My iPad can still display Stash until the last version (0.24.3) but since the 0.5.5 update, it only show blank screen. I can still access Kavita using desktop or iPhone 11.

**Expected behavior**
Opening Stash using my iPad will show home screen as usual

**Stash Version: v0.25.1**

**Smartphone (please complete the following information):**
 -Device: iPad Air 1st Generation (released 2013)
 - OS: 12.5.5
 - Browser Safari
 - Version

**Additional context**
I also have similar problem with Kavita but the dev has fixed it. Maybe it is due to similar problem as well?
Here's the link to the Kavita issue thread that I raised.
[https://github.com/Kareadita/Kavita/issues/1458](https://github.com/Kareadita/Kavita/issues/1458)

**Comment by DogmaDragon** [comment]
Could you check if develop build works? [stashapp/stash:development](https://hub.docker.com/layers/stashapp/stash/development/images/sha256-8ba7375145423619b364f94360edff8ea754f4708401ac00c7bb9e1f06bccf1b?context=explore)
Make a backup of your database. https://docs.stashapp.cc/beginner-guides/backup-and-restore-database/

A change in https://github.com/stashapp/stash/pull/4631 should improve ES6 support in the next release.

**Comment by WithoutPants** [comment]
#4361 is to do with backend plugin javascript support, not frontend so not relevant to this issue.

Unfortunately, debugging to determine what has broken the UI for ipad devices is next to impossible afaik without access to desktop ios device, which I do not have. This issue has been reported before, but I was not able to determine which change broke the UI using a spare ipad I happened to have.
