### ISSUE TITLE
[Feature] Encode marker snippets as video

### ISSUE THREAD

**Issue by InfiniteTF** [stashapp/stash#472]
Currently all marker snippets are encoded as webp. This has multiple drawbacks, specifically that the size is rather large, and that it's impossible to stop them from animating. Encoding the snippets as mp4 instead would likely save a lot of space, at the possible cost of some encoding time, and also allow for disabling animation. MP4 is also more compatible than webp, which is not supported on IOS/Safari.

For a benchmark of ways to encode animations:
https://corydowdy.com/blog/apng-vs-webp-vs-gif

> There's a reason Gyfcat (webm or MP4) and Imgur (gifv) serve videos for their "GIFS". They are faster and typically smaller. The end user can also stop these from playing which could keep lower powered machine's fans from spinning :) or let them actually use the page.

**Comment by bnkai** [comment]
Snippets are already available as mp4 , the get generated anyway.
Would it be better to generate a single jpg screenshot for the marker ( start of marker ) instead of webp and mimic the scenes page ( play on hover over) ?
