### ISSUE TITLE
[Feature] Gallery Grid View & Cover Picture

### ISSUE THREAD

**Issue by f1delio** [stashapp/stash#473]
Currently, the gallery only shows a list view and automatically selected cover image.

**Grid View** would show more galleries at the same time making it easier to choose and navigate.

**Cover Image**
Instead of implementing something complex, I have a proposal for this simple solution in pseudo-code:

IF zip file.contains (image called "cover.jpg") THEN
use it as a cover image for gallery.
ELSE
do the thing it is doing now.
END IF

This way users could easily make a cover image for the gallery by just renaming one image.

**Comment by WithoutPants** [comment]
Implemented via #622
