### ISSUE TITLE
[Bug Report] Extra click necessary when using tagger

### ISSUE THREAD

**Issue by Tscherno** [stashapp/stash#4734]
**Describe the bug**
When using tagger and matches are found, normally the first one / best match is "pre selected". With the last Update the behaviour changed. Now even the only match needs to be clicked to be shown and be able to save it.

**To Reproduce**
1. Use tagger
2. Scrape
3. Get results

**Expected behavior**
Should work like before. First/best match should be loaded directly without interaction.

**Screenshots**
![grafik](https://github.com/stashapp/stash/assets/5594674/d89b0ae8-e578-45e6-9c9b-804f3e2d7beb)
![grafik](https://github.com/stashapp/stash/assets/5594674/464efd8a-cda7-4f22-9fc3-c8f4f974b64f)

**Stash Version: (from Settings -> About):**
v0.25.1-14-g034fd440

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 123.0.6312.60 

**Additional context**
Probably linked to https://github.com/stashapp/stash/pull/4715

**Comment by floydcg** [comment]
I was actually going to report this myself. I am also seeing the same thing
