### ISSUE TITLE
[Bug Report] Image clips with rotation metadata display incorrectly in wall view and lightbox

### ISSUE THREAD

**Issue by jtjb07** [stashapp/stash#4738]
**Describe the bug**
In wall view and lightbox, image clips with rotation metadata will be correctly rotated, but their new height and width are not accounted for. E.g. 1920x1080 -> rotated 90 degrees -> 1080x1920

In wall view, this leads to gaps being created around the image clip's preview because Stash is using the unrotated height and width.
![example1](https://github.com/stashapp/stash/assets/146701633/85519719-655e-4686-a069-8876f39e0d9f)

In lightbox, this leads to image clips being zoomed in when opened, again because the wrong height and width are being used. (edit 2024-01-01 - the same problem appears in the fullscreen slideshow view)
![example2](https://github.com/stashapp/stash/assets/146701633/6647390a-ae6e-46b6-8bd1-d4adb3b98a45)

Here is an example file:
https://github.com/stashapp/stash/assets/146701633/8bd7253d-e710-448e-99a3-7a7792cf4f50

**To Reproduce**
- Import example file into Stash
- View the file with other images in the Image Tab in Wall View
- While in wall view, open the image in the lightbox view

**Stash Version:**
0.25.1

**Desktop:**
Windows 10
Chrome 123.0.6312.86

**Comment by zhyu** [comment]
It seems it's related to how the image metadata is extracted and parsed:
* Stash calls `ffprobe` to extract the image metadata including height, weight, and rotate
* `ffprobe` does not seem to read the `Orientation` tag of EXIF data to produce the `rotate` metadata
