### ISSUE TITLE
[Bug Report] Saved filter can't be set as default on Image views

### ISSUE THREAD

**Issue by akerkat** [stashapp/stash#4754]
**Describe the bug**
Currently on in Image view(Image menu, specific galleries, performers gallery) already or newly created filters can't be set as default. It works in all other areas but not on image level. 

**To Reproduce**
1. Go to Image or Gallery->Image or Performer-> Images
2. Create new filter rule or use already existing filter
3. There is no Set as default button so any filter can't be set as default. 

**Expected behavior**
User should be able to set default filter on image level. 

**Screenshots**
No set as a default button:
![Screenshot_3](https://github.com/stashapp/stash/assets/153182305/967e0175-256a-454c-b1b8-0869fa16f189)

**Stash Version: (from Settings -> About):v0.25.1

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome, Firefox, Edge
 - Version: Newest version for 11.04.24

**Comment by WithoutPants** [comment]
Resolved by #4962
