### ISSUE TITLE
Make DLNA port configurable

### ISSUE THREAD

**Issue by Conkuist** [stashapp/stash#4760]
**Is your feature request related to a problem? Please describe.**
XBVR DLNA Server can't run at the same time as Stash DLNA Server because both use the same port 1338

**Describe the solution you'd like**
Do not use the default port or make the port configurable
https://github.com/stashapp/stash/blob/develop/internal/dlna/service.go#L141

**Describe alternatives you've considered**
I tried to figure out how to change it myself inside the docker container but was unable to get it done.

**Additional context**
I run XBVR and Stash in Docker

**Comment by Conkuist** [comment]
DLNA only works when the network mode is set to host. This is true for XBVR and Stash. Both use the same port and none of them offer a way to change it. Which is the reason why I made the request to make it configurable.

**Comment by ipedrazas** [comment]
I've created a PR https://github.com/stashapp/stash/pull/4836 to enable the DLNA port conf from the `config.yml` file
