### ISSUE TITLE
[Bug Report] Queue is broken: showing incorrect scenes

### ISSUE THREAD

**Issue by QxxxGit** [stashapp/stash#4780]
On the latest develop, the queue only works when navigating from the root `/scenes` page. When navigation to a scene from a performer page, or studio page, etc. the queue breaks: the queue list shows incorrect scenes, and clicking the next button doesn't work due to this incorrect list.

Bug confirmed with another user in Discord

**Comment by cj12312021** [comment]
https://github.com/stashapp/stash/pull/4705 appears to be the source of this issue.
