### ISSUE TITLE
[Bug Report] Rating Star Precision Not Working Properly

### ISSUE THREAD

**Issue by Cyb3rN3xus** [stashapp/stash#4782]
**Describe the bug**
When selecting the "Rating Star Precision" option as "Half" in the settings, the rating stars in the scene view do not allow selecting half-star ratings, except for 3.5 stars. Moving the mouse over the stars only allows selecting full-star ratings.

**To Reproduce**
1. Go to Settings -> Interface -> Editing.
2. Set the "Rating Star Precision" option to "Half".
3. Open any scene.
4. Try to rate the scene by moving the mouse over the rating stars.
5. See that only full-star ratings are selectable, except for 3.5 stars.

**Expected behavior**
When the "Rating Star Precision" option is set to "Half," moving the mouse over the rating stars should allow selecting both full-star and half-star ratings.

**Stash Version: v0.25.1**

**Desktop:**
- OS: Manjaro Linux 23.1.4
- Browser: Firefox
- Version: 125.0.2 (64-bit)

**Comment by DogmaDragon** [comment]
It works a bit unintuitively. You need to click on the star again to change it to a half star.
