### ISSUE TITLE
[Bug Report] Videos not autoplay on mobile devices

### ISSUE THREAD

**Issue by hjs937** [stashapp/stash#4788]
**Describe the bug**
On my phone/pad when clicking on a video or clicking the next/previous button it doesn't autoplay but keeps loading and I have to pause it and then click the play button again for it to play. The autoplay works fine on my PC though. Never changed any default settings.

**Stash Version: (from Settings -> About):**
v0.25.1

**Smartphone (please complete the following information):**
 - Device: iPhone11/iPad10
 - OS: iOS17.4.1
 - Browser: Chrome v124.0.6367.88, safari

**Comment by themorajr** [comment]
Same, it need to press pause and play again, so annoying

**Comment by WithoutPants** [comment]
I've only been able to reproduce this when the Handy is configured. Do you have this enabled by any chance? Do you get the same behaviour on PC?

A quick test on my Android seemed to autoplay ok if the Handy wasn't enabled.

**Comment by hjs937** [comment]
> I've only been able to reproduce this when the Handy is configured. Do you have this enabled by any chance? Do you get the same behaviour on PC?
> 
> A quick test on my Android seemed to autoplay ok if the Handy wasn't enabled.

No, handy serve funscripts directly is disabled. 
Autoplay is ok on PC

**Comment by themorajr** [comment]
> I've only been able to reproduce this when the Handy is configured. Do you have this enabled by any chance? Do you get the same behaviour on PC?
> 
> A quick test on my Android seemed to autoplay ok if the Handy wasn't enabled.

I tested it, and it works fine on Android phones and tablets (Huawei, Samsung, Xiaomi). 
The only issue arises on Apple devices. 
I believe there's something wrong with the code that is not compatible with WebKit.

**Comment by NodudeWasTaken** [comment]
I only encountered this when trying to play from the queue.
From what i can tell it reloads the sceneplayer some 3 times and fails to autoplay.
From network activity i can see that it at no point does it try to fetch the newly selected scene's video.

**Comment by asanka-chanaka** [comment]
Nothing plays on iPhone (15 Pro Max ios 17.5.1).

**Comment by NodudeWasTaken** [comment]
Funny fact, i can no longer reproduce this, i suspect this line from Safari 17.6 (https://developer.apple.com/documentation/safari-release-notes/safari-17_6-release-notes)
"Fixed firing loadeddata events for <audio> and <video> on page load. (124079735) (FB13675360)"
