### ISSUE TITLE
[Feature] Upload Image From URL

### ISSUE THREAD

**Issue by halorrr** [stashapp/stash#479]
**Is your feature request related to a problem? Please describe.**
It creates a few extra steps for each image I add for a performer or studio having to download the image to my computer and then upload it to stash.

**Describe the solution you'd like**
It would be a lot easier if images could be added through the direct image URL from any website.

**Describe alternatives you've considered**
There isn't really a current alternative to this.

**Additional context**
N/A

**Comment by WithoutPants** [comment]
One alternative is to copy the website image to clipboard and use Ctrl-V to paste the image in the create/edit studio/performer page. This existing functionality probably needs to be more intuitive and obvious.

**Comment by halorrr** [comment]
That works great! And yes it would be nice if that was a more obvious functionality

**Comment by bnkai** [comment]
When doing a copy / paste the image is saved as PNG in the database. It is worth mentioning that too.

**Comment by WithoutPants** [comment]
$10 bounty posted by `Inkognito`.
