### ISSUE TITLE
[Feature] Tag inheritance

### ISSUE THREAD

**Issue by miltuss** [stashapp/stash#4794]
Hello, I would like the content (videos, images, etc.) to automatically inherit certain specific tags assigned to the content performer.  Would it be possible to add a feature that allows certain tags to be inherited from performers or studios?

**Comment by stg-annon** [comment]
as @echo6ix said this appears to be answered in the linked issue, the `performer tags` filter for scenes might be of interest to you

**Comment by miltuss** [comment]
> Already requested (or something similar) and closed #88
> 
> > don't intend on adding this to the core functionality. This should be possible using plugins.

No plugin allows you to do that!
