### ISSUE TITLE
[Feature] Support for audio files for stash

### ISSUE THREAD

**Issue by miltuss** [stashapp/stash#4795]
Hello, I have several audio files that I would like to integrate into performers in stash, but stash does not support audio files.  Is it possible to add support for audio files in stash?

**Comment by echo6ix** [comment]
Duplicate and related request of https://github.com/stashapp/stash/issues/1258 https://github.com/stashapp/stash/issues/11 

After 4-5 years of accumulated feature requests, it's most likely you can find what you're thinking of in some variation by querying first.
