### ISSUE TITLE
[Bug Report] macOS repeatedly prompts: "Stash" would like to access files on a removable volume.

### ISSUE THREAD

**Issue by 8fl99iadt80u2ihx7pik** [stashapp/stash#4796]
**Describe the bug**
I am running Stash on macOS Sonoma 14.4.1 and storing my media on an external hard drive. Every single time that Stash attempts to play a video stored on this drive, macOS pops up a prompt with the message "'Stash' would like to access files on a removable volume." I have already granted Stash "Full Disk Access" but this apparently does not include external hard drives.

In System Settings > Privacy & Security > Files and Folders, I see Stash listed with the "Full Disk Access" permission. Other apps in this screen are listed with the "Removable Volumes" permission but I don't believe Stash has ever requested that permission, and there is no way to manually grant it without the app requesting it.

**To Reproduce**
1. Add media stored on an external hard drive to your library.
2. Play that media in Stash.
3. See the prompt: "'Stash' would like to access files on a removable volume."

**Expected behavior**
Ideally, Stash would request the "Removable Volumes" permission when the content stored on an external hard drive is added to the library. The user could approve, and macOS would stop repeatedly asking the user after that.

**Screenshots**
n/a

**Stash Version: (from Settings -> About):**

v0.25.1

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.4.1
 - Browser: Chrome 124.0.6367.92 (Official Build) (arm64)

**Comment by WithoutPants** [comment]
As far as I know, there's nothing we can do within stash to stop this message from appearing. stash does not explicitly request any permissions; all disk access is done at a low level, and the stash code has no knowledge/access to the macos permission infrastructure. 

See also: 
https://iboysoft.com/howto/allow-access-to-removable-volumes-mac.html
https://forum.makemkv.com/forum/viewtopic.php?t=25455
