### ISSUE TITLE
[Bug Report] iOS home screen icon not set

### ISSUE THREAD

**Issue by honeybeaver** [stashapp/stash#4802]
**Describe the bug**
On macOS there's a nice icon for the web app, but not on iOS. 

**To Reproduce**
1. Navigate to instance on iOS device
2. Tap share icon
3. Tap add to home screen

Note, no icon.

**Expected behavior**
1. Navigate to instance on iOS device
2. Tap share icon
3. Tap add to home screen

There's an icon like macOS for add to dock. 

**Screenshots**
Icon on macOS and iOS should have something similar
<img width="66" src="https://github.com/stashapp/stash/assets/84999906/16d4e114-6472-41ef-bfd2-32e70a4aa75f">

On iOS, it's just an icon with an S. 

**Stash Version: (from Settings -> About):** v0.25.1

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - Browser [e.g. chrome, safari] Safari
 - Version [e.g. 22] iOS 17.4

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 
 - OS: [e.g. iOS8.1] iOS 17.4
 - Browser [e.g. stock browser, safari] Safari 
 - Version [e.g. 22] iOS 17.4

**Additional context**

**Comment by JanJastrow** [comment]
Can't reproduce on latest iOS & Stash Dev-build.
Works as expected.
![image](https://github.com/stashapp/stash/assets/2591991/af59541b-b269-4e74-a93f-607ad26cdded)

**Comment by honeybeaver** [comment]
Thanks. Seems like it was an issue of using Private Browsing on iOS.
