### ISSUE TITLE
Tags get reset on every scene save on latest dev build

### ISSUE THREAD

**Issue by floydcg** [stashapp/stash#4812]
When trying to do a batch save, tags appear to reload everytime you save a scene, wiping out any tags you set on any scene after the top most scene. 

Steps to reproduce this:

Open Scene Tagger
Scrape a few scenes from StashDB.
Scenes will load with their tags that are present on stashdb. Add a new tag to scene, (Blonde for example)
Add Tag to 2nd scene below the 1st one. (Blonde again in this example.) 
Click save on the 1st scene. 
... will appear on the next scene tagger box (like its parsing results)
2nd Scene will reload all scraped tags but added tag will no longer be added.

**Comment by WithoutPants** [comment]
I haven't been able to reliably reproduce this yet. Can you provide an example with stashdb stash ids of two scenes where you can reproduce this issue.

**Comment by floydcg** [comment]
My apologies, It looks like it might be a glitch with one of the plugins I have loaded. I'm reenabling them one by one to see which one makes it happen.
