### ISSUE TITLE
[Bug Report] ffmpeg & ffprobe not used if libwebp support is not available

### ISSUE THREAD

**Issue by honeybeaver** [stashapp/stash#4814]
**Describe the bug**

On the current development build (v0.25.1-26-g22d14fd8), with the changes to ffmpeg & ffprobe handling (https://github.com/stashapp/stash/pull/4688 ?), stash does not use ffmpeg & ffprobe available in $PATH, if libwebp support is not available. Prior builds did, and on Apple Silicon, builds from Homebrew and MacPorts are not compiled with libwebp support. Builds from https://evermeet.cx/ffmpeg/ are not native Apple Silicon builds either, and they also do not appear to have libwebp support either. Scanning and other key functions are non functional due to this, as Stash behaves as if there is no ffmpeg & ffprobe available. Users should not need to do a custom compile of ffmpeg & ffprobe.

**To Reproduce**
1. Update to [v0.25.1-26-g22d14fd8](https://github.com/stashapp/stash/releases/tag/latest_develop) on an Apple Silicon machine
2. Run scan (which fails with error missing ffmpeg and/or ffprobe)
3. Or, manually enter ffmpeg & ffprobe paths (which are not accepted with error: invalid ffmpeg path: ffmpeg is missing libwebp support)

**Expected behavior**
Stash runs like prior builds using ffmpeg without libwebp support. 

**Screenshots**
n/a

**Stash Version: (from Settings -> About):** 0.25.1-26-g22d14fd8

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS 14.4.1, Apple Silicon
 - Browser [e.g. chrome, safari] any browser
 - Version [e.g. 22] any browaer 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] n/a
 - OS: [e.g. iOS8.1] n/a
 - Browser [e.g. stock browser, safari] n/a
 - Version [e.g. 22] n/a

**Additional context**
n/a

**Comment by DogmaDragon** [comment]
> Builds from [evermeet.cx/ffmpeg](https://evermeet.cx/ffmpeg/) are not native Apple Silicon builds either, and they also do not appear to have libwebp support either.

![image](https://github.com/stashapp/stash/assets/103123951/177a3de6-06cc-4744-b788-ef7699595a0f)

As far as I know, Stash always checked for libwebp when validating ffmpeg and if it was missing it would just download it. https://github.com/stashapp/stash/commit/7086109d7879b64529578e3e16dcafbb8b57e842#diff-be23a0fd57a96d1c4b6d5f97fb3ad1081382d068f3e0c73cffea90a36c36fd00L212-L227 

Now it asks you to download, instead of doing that without express permission.

**Comment by WithoutPants** [comment]
Thanks for the report of this regression. #4852 should address this issue.
