### ISSUE TITLE
[Feature] GraphQL support for Identify and Auto Tag tasks

### ISSUE THREAD

**Issue by joewood9364** [stashapp/stash#4818]
Looking at #74 and the docs I can now scan automatically at system startup (should this be an option in the GUI?) which is really handy.

Would it be possible to do the identify and auto tag tasks via the API as well?
I've already setup the default identify task to my liking via GUI so just passing the command to execute this via API is left I think?

**Comment by bob123491234** [comment]
Identify and auto tag can already be triggered via the API in the same manner as the scan example you linked to. You can go to [stash IP]:9999/playground to view the GraphQL documentation, and if you open the Network tab of Developer Tools you can see the requests the GUI is sending.

**Comment by stg-annon** [comment]
anything you can do from the UI can also be done via GQL if you want an example look in the `Network` tab of your browsers developer tools to see what the front end is sending to the back end.
