### ISSUE TITLE
(Feature Request) Compilations

### ISSUE THREAD

**Issue by dumbstuffok** [stashapp/stash#4819]
### Compilations

Currently Stash contemplates:

1. Scenes
2. Movies
3. Markers
4. Galleries
5. Images
6. Performers
7. Studios
8. Tags

I am proposing Compilations as a 9th option. This feature would allow for custom compilations that could be created and saved based off of all of the above mentioned elements. **A compilation could be made up of any number and mixture of Scenes, Movies, Markers, Galleries, Images, Performers, Studios and Tags**. It would be arranged in an order sort of like a playlist. But you could for example create a compilation that would be made up of a marker from a scene and another chapter from another scene. When the compilation plays that first marker it skips to the next marker from the next scene instead of playing the entire scene. This way if you have a bunch of markers setup on all of you movies, then you could just watch a custom compilation of those specific markers. Again this could include any mix of markers, then maybe a performer, then maybe a gallery, then maybe a tag, then maybe a studio, etc.
I would imagine this would be editable along with an ability to give the compilation a title, description and maybe assign an image to it. Again, maybe this could be in the form of a list of these items (Scenes, Markers, Performers, etc.) that can be rearranged if desired. Also it would be great to have the option to add an element (Performer, Scene, Tag, Marker, etc.) to a new compilation or existing compilation from the context menu of those said items.

Anyways, just a thought. Thank you!

**Comment by stg-annon** [comment]
what you describe seems to be more along the lines of a full fledged editing software with the ability to edit all those different things together, I would think this is well out of scope of just organizing media

I know of one plugin that can accomplish something like this called [clip-mash](https://github.com/soundchaser128/clip-mash) I would think you would want to look at that or an actual full fledged editing software as most of the things you describe are not really simple things to combine together

for now I am going to close this as not planned as beyond a playlist of markers I don't see how someone would implement a playlist of **Performers**, **Tags** or **Studios**. Perhaps a future update to the playlist feature or a plugin will accomplish what you are looking for.

**Comment by dumbstuffok** [comment]
@stg-annon I'm a UI/UX designer. I can see it in my head. Maybe if I created a mockup in Figma I might be able to communicate my idea better.
