### ISSUE TITLE
[Bug Report] Scene Duplicate Checker Error

### ISSUE THREAD

**Issue by hackerlicious** [stashapp/stash#4828]
**Describe the bug**
When attempting to use the Scene Duplicate Checker, if the Search Accuracy is set to anything other than `Exact` then an error is returned ("Error: Error searching for duplicates."). No error appears in the log and it appears like the calculation process continues in the background because the CPU is maxed out for a few minutes and, eventually, the TRACE log shows a number of queries that indicate that the duplicates were found, even though they do not appear in the UI: 
`SQL [660ns]: SELECT scenes.*, scenes_files.file_id AS primary_file_id, folders.path AS primary_file_folder_path, files.basename AS primary_file_basename, fingerprint_md5.fingerprint AS primary_file_checksum, fingerprint_oshash.fingerprint AS primary_file_oshash FROM scenes LEFT JOIN scenes_files ON ((scenes_files.scene_id = scenes.id) AND (scenes_files.primary = ?)) LEFT JOIN files ON (files.id = scenes_files.file_id) LEFT JOIN folders ON (folders.id = files.parent_folder_id) LEFT JOIN files_fingerprints AS fingerprint_md5 ON ((fingerprint_md5.file_id = scenes_files.file_id) AND (fingerprint_md5.type = ?)) LEFT JOIN files_fingerprints AS fingerprint_oshash ON ((fingerprint_oshash.file_id = scenes_files.file_id) AND (fingerprint_oshash.type = ?)) WHERE (scenes.id IN (?, ?)), args: [1 md5 oshash 75633 178924]`

**To Reproduce**
1. Go to Scene Duplicate Checker
2. Change the Search Accuracy from `Exact` to `High`

**Expected behavior**
The duplicates are displayed

**Stash Version: (from Settings -> About):**
v0.25.1
Build hash:
bf7cb78d
Build time:
2024-03-13 03:30:08

**Additional context**
Server running in Docker using the stashapp/stash:latest image and the default docker-compose.yml.

**Comment by WithoutPants** [comment]
It appears that the Scene Duplicate Checker page does not currently output the details of any error that it encounters. To help decipher the problem, can you try the following:
- open the DevTools window - on Chrome the shortcut for this is F12
- in the DevTools window, go to the `Network` tab
- reproduce the error via the steps in your description
- find the `graphql` request in the `Network` tab in the DevTools window. The correct request will have `FindDuplicateScenes` in the Request Payload. The Preview and Response tabs should give you the error that is returned.

**Comment by LeGrosFromage** [comment]
FWIW, this might just be local to the OP - the scene checker seems to work ok for me, regardless of that the Search Accuracy is set to:
![image](https://github.com/stashapp/stash/assets/97702146/a5b6a4f6-1fa9-48a1-81ec-3d6e9a8b8555)

Changing the Duration has no effect on search results either.

**Comment by hackerlicious** [comment]
Thanks for the suggestion to look at the response to the GraphQL request. I did that and there was no response but that led me to notice that the request had timed out, so, as @LeGrosFromage suggested, this was a local issue due to a 60s timeout in my reverse proxy. I updated the timeout and it is working now.
