### ISSUE TITLE
[Bug Report] Autotagger doesnt find matches between square brackets

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#483]
**Describe the bug**
The autotagger does not find matches -- such as performer name -- when the matching string in the filename is between square brackets, `[ ]`.

**To Reproduce**
1. Create a performer name, `Jane Doe`.
2. Create an mp4 for the Stash video library, `Scene.2020-04-19.[Jane Doe].mp4`
3. Scan library for new file.
4. Click autotag.

**Expected behavior**
The new scene should be tagged with the performer name `Jane Doe`. 

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 18.04
 - Browser Chrome
 - Version 81

**Additional context**
Didn't test Autotagger for _studio_ or _tag_ string matches in square brackets.

**Comment by navyseai** [comment]
also have a ',' near the name seems to ignore the tag example 'name,'

**Comment by velzy00** [comment]
Similarly, I find it doesn't tag words with a # in front of them. These are typically tags that could translate well into stash.
