### ISSUE TITLE
[Bug Report] Custom Locales not working

### ISSUE THREAD

**Issue by KleinerSource** [stashapp/stash#4841]
**Describe the bug**
Custom Locales not working

**To Reproduce**
interface- Custom localization  - Custom localization enabled - enable

**Expected behavior**
add custom locales content to Custom localization
reload pages

**Screenshots**

![image](https://github.com/stashapp/stash/assets/920875/6ea7ae7f-3876-4ad4-a467-8269acb40771)

**Stash Version: (from Settings -> About):**
v0.25.1
Build hash:
bf7cb78d

Build time:
2024-03-13 03:30:08

**Desktop (please complete the following information):**
 - OS: [e.g. Win11]
 - Browser [e.g. chrome, edge]

**Comment by QxxxGit** [comment]
From my testing:

```json
{
    "performer": "Tester",
    "performers": "Testers"
}
```

I can see instances of `Performers` (plural) changing (nav bar, scene filters) but the singular `Performer` would not change in the scene filters or scene page etc.

**Comment by WithoutPants** [comment]
> From my testing:
> 
> {
>     "performer": "Tester",
>     "performers": "Testers"
> }
> I can see instances of `Performers` (plural) changing (nav bar, scene filters) but the singular `Performer` would not change in the scene filters or scene page etc.

Scene page uses `countables.performers` which explains why you didn't see the change there.

@KleinerSource can you please attach the custom localization string you used in your settings? I think the most likely culprit is that the JSON is malformed. You can check for this yourself by opening the browser dev tools and looking at the console output.

**Comment by KleinerSource** [comment]
![image](https://github.com/stashapp/stash/assets/920875/adfade13-c420-4f8a-bcaa-d9f5c950f1af)
![image](https://github.com/stashapp/stash/assets/920875/1c01dbcf-4914-4a60-8d2e-2ca3c48c56b7)

NO json error

**Comment by WithoutPants** [comment]
`SyntaxError: Expected ',' or '}' after property value in JSON at position 16730 (line 471 column 7)`

This is an error in your custom localisation string.

**Comment by KleinerSource** [comment]
I have adjusted the JSON and resolved the issue. Thank you for your help
