### ISSUE TITLE
[Feature] Auto scraped movies, scenes & performers

### ISSUE THREAD

**Issue by whitty-username** [stashapp/stash#485]
**Is your feature request related to a problem? Please describe.**
Using community scrapers available in stashapp/CommunityScrapers is an excellent start, but currently limited to individual sites (with several exceptions) and the current process is slow to scrape data for each scene / movie / performer. 

**Describe the solution you'd like**
Automated scrape and manual review (to confirm accurate match) of scenes based on existing metadata such as filename, scene title, performer, etc. Scrape could use multiple sources chiefly large scale VOD / content aggregators or sites like IAFD rather than going for individual smaller sites. 

**Describe alternatives you've considered**
With the current scraping options adding the two below mentioned VOD Content aggregators as a source would eliminate the need for many scrapers for individual sites. Scrape from these should include the ability to scrape scene, performer and movies (assuming scraping for movies is implemented).

**Additional context**
VOD Content Aggregators:
https://www.hotmovies.com/ - 210,000+ full-length adult videos
https://www.aebn.net - 100,000+ movies and scenes

**Comment by bnkai** [comment]
The endgoal is to use a stash-box server as a main scraper which will also utilise hashes or checksums to identify scenes with better accuracy and less false positives. That is still a wip but if you want you can have a look at  the relevant  [PR](https://github.com/stashapp/stash/pull/454). If you have a look i thing it covers everything that you mentioned and even more...
