### ISSUE TITLE
[Feature] add documentation related to the "serve funscripts directly" option

### ISSUE THREAD

**Issue by Kyr4l** [stashapp/stash#4850]
the current option, explain very vaguely what it does, but doesn't tell anything else, especially about how it actually works, or what is needs to function properly.

i've been trying to get this option to work, but there is absolutely zero documentation related to it.

**Comment by WithoutPants** [comment]
To the best of my knowledge it doesn't require much more than the Handy being on the same network and that setting being enabled.

This is the existing documentation:
`When enabled, funscripts will be served directly from Stash to your Handy device without using the third party Handy server. Requires that Stash be accessible from your Handy device.`

The only thing I can see that could cause people to get stuck is that if you have credentials enabled on the server then you need to have the api key generated. I can add that to the documentation.

What issue are you running into?

**Comment by Kyr4l** [comment]
well from my experience this feature has never worked, the device is  on `172.16.1.10/16` and the server is on `172.16.0.220/16` (these are example IPs)
 as soon as the feature is enabled, stash says that the device cannot be reached. even tho both devices are on the same network, and the devices can reach each other.
maybe that feature requires an extra port opened, some other implementations actually do that, but they state which port is used.
i do have credentials enabled on the server too,

**Comment by WithoutPants** [comment]
> i do have credentials enabled on the server too,

Have you generated an API key in stash?

**Comment by Kyr4l** [comment]
> > i do have credentials enabled on the server too,
> 
> Have you generated an API key in stash?

i just did it and yes it works now, didn't know i needed an API key to be generated to use this feature.
may i recommend adding this requirement somewhere in the UI ? i can do a PR if needed
