### ISSUE TITLE
Stash will not recognise Python install/path

### ISSUE THREAD

**Issue by Sandylz** [stashapp/stash#4856]
Stash will not be able to resolve python even when being pointed directly to the executable, as a result any plugins using python will not work.

**To Reproduce**
1. Intall a plugin that uses python e.g. The Porn DB Markers
2. Go into Settings -> System -> Application Paths -> Python Executable Path
3. Enter the path to the python executable
4. Attempt to use the plugin e.g. Sync markers with The Porn DB
5. The plugin will not work and an error message will appear in the log like this: 
Error running plugin task: error running plugin: exec: "C:\\Users\\<user>\\.stash\\plugins\\community\\TPDBMarkers\\python": file does not exist
6. If plugins are not reloaded the path in the error message will start multiplying e.g. 
error running plugin: exec: "C:\\Users\\<user>\\.stash\\plugins\\community\\TPDBMarkers\\pythonC:\\Users\\<user>\\.stash\\plugins\\community\\TPDBMarkers\\pythonC:\\Users\\<user>\\.stash\\plugins\\community\\TPDBMarkers\\python": file does not exist

**Expected behavior**
Expected behaviour is that the plugin will function correctly.

**Screenshots**
![image](https://github.com/stashapp/stash/assets/170304157/fbc99ff9-d1a6-4c00-b2e5-5bf80348ec6e)

**Stash Version:**
v0.25.1

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 125.0.6422.60

**Additional context**
This bug persisted across multiple seperate systems, but couldn't be reproduced by other users who had the exact same settings. It also stops the warning message that should appear if the path to the python exe ends on a folder.

**Comment by feederbox826** [comment]
After some debugging and testing with the user, it seems to only exhibit this behaviour on the **first** install, after closing and re-opening the stash.exe it seems to have picked up the custom python path - which was missing the telltale trace log

`using configured python path: ...`

My assumption is that the default startup config.yml is locked on first install which means that python_path is not being read

**Comment by Sandylz** [comment]
This bug should be resolved by restarting Stash and running: pip install stashapp-tools  in command prompt.

**Comment by feederbox826** [comment]
Will re-open in a new issue as it's still a bug to be addressed :/
