### ISSUE TITLE
[Feature] Performers page enhancement

### ISSUE THREAD

**Issue by clemondo** [stashapp/stash#486]
**Is your feature request related to a problem? Please describe.**
The performers sorting is nice and clean but lacks important searchable physical features and tags

**Describe the solution you'd like**
Being able to add performer details like hair colour, breast size, and allowing tagging of physical features would help filter performers. 

**Additional context**
This concept links up with #124 (performer profile page UI enhancements), #120 (performer tags), #118 (side panel alphabetical  performer list)

**Comment by ChaosTherum** [comment]
I think a possible solution would be allow dynamic fields as well as tags. Since those would be very different things. I'm thinking the scraper would look something like this.

`
performer:
  SomeDynamicField:
    FieldName: 'some field name'
    Selector: selector
`

**Comment by bnkai** [comment]
Most issues raised here seem now completed... If not a new updated issue can be opened.
