### ISSUE TITLE
[Feature] Add ability to filter by tags using not

### ISSUE THREAD

**Issue by ts7125** [stashapp/stash#4862]
**Is your feature request related to a problem? Please describe.**

It would be great to be able to filter using tags that are not included. That way you could filter out scenes that are scenes that have something you don't want

ie Scenes tagged with [VR] tag would not show up if your looking for non VR scenes

**Describe the solution you'd like**
![image](https://github.com/stashapp/stash/assets/170476205/80b3155b-3867-4e62-a2d9-a420a16b2e2c)

There would be a is not included option and not all included option

**Describe alternatives you've considered**
I have been using a alternate tag for non VR things but I think this would be a great help for people wanting better filter options

**Comment by bob123491234** [comment]
Tags can be excluded by clicking the minus button at the right side of the tag list. 
![exclude](https://github.com/stashapp/stash/assets/54259225/e3fcb680-19bd-4d66-9465-d2089fea8451)
