### ISSUE TITLE
[Bug Report] Using domain in external_host causing data not to load when using local ip address

### ISSUE THREAD

**Issue by ts7125** [stashapp/stash#4863]
**Describe the bug**
If the app is using a domain name, that domain must be set in the config variable `external_host` in order to access the content in the website. However if you connect directly to the app using the server address on local network you are unable to fetch the content

**To Reproduce**
1. add an `external_host` in config
2. restart app
3. go to app using server ip and port
4. log in

**Expected behavior**
The app should display all images and be able to watch videos

**Actual behavior**
The app cannot display images and cannot play videos

**Screenshots**
![image](https://github.com/stashapp/stash/assets/170476205/766795c2-1709-4432-b182-ddb5a882f545)

![image](https://github.com/stashapp/stash/assets/170476205/61641701-345b-43b0-b061-175454133b26)

**Stash Version: (from Settings -> About):**
v0.25.1

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 124.0.6367.210

**Additional context**
I am using an apache proxy to host the site externally

**Comment by feederbox826** [comment]
`external_host` overrides all paths to be prefixed with that external host, being able to see any media with it enabled would be a bug - I would recommend instead [properly configuring apache2 for a reverse proxy](https://docs.stashapp.cc/networking/reverse-proxy/#apache)

**Comment by ts7125** [comment]
I am using the reverse proxy with apache. If i dont use the external_host, the blob and stream calls fail due to blocked:csp when using ssl
