### ISSUE TITLE
Performers page does not remember last tab when going back in browser

### ISSUE THREAD

**Issue by victorhooi** [stashapp/stash#487]
**Is your feature request related to a problem? Please describe.**
When navigating from the "Scenes" tab for a performer, Stash does not remember the last selected tab.

For example:

1. Navigate to Performers.
2. Click on the Scenes tab.
3. Click on a scene to open it.
4. Navigate back in your web browser.

Expected behaviour - you should be taken back to the scenes tab, on Performers.

Actual behaviour - you are taken back to the default home page for that performer.

**Describe the solution you'd like**
When you navigate away from the Performers page, then page - it should remember the last scene.

**Describe alternatives you've considered**

N/A

**Comment by WithoutPants** [comment]
Fixed.
