### ISSUE TITLE
[Bug Report] Notification does not dissapear (When shown)

### ISSUE THREAD

**Issue by phhemberg** [stashapp/stash#4876]
**Describe the bug**
When doing a update or deletion of a scene there is a green box showing notification. fx: Deleted Scene or Updated Scene. This messag does not dissapear at all. And i can not be closed with clicking X.

**To Reproduce**
1. Pick any screen to update or delete
2. Make a change og delete
3. Save (if changed)
4. Green infobox appears but can not be closed (or close automatic).

**Expected behavior**
I expect it to dissapear after a few seconds. Or at least to be able to close it manually

**Screenshots**
![image](https://github.com/stashapp/stash/assets/30298982/39a8798b-277a-4a2e-a3d0-07f5290f42bc)

**Stash Version: (from Settings -> About):**
v0.25.1

**Desktop:**
 - OS: Linux Mint 21
 - Browser: Chrome 
 - Version: 125.0.6422.76

**Additional context**
My locales are currently DK language. But the bug is still there if i change it to english language.

I actually also tried to disable notification. Still same issue. 

From chrome;
![image](https://github.com/stashapp/stash/assets/30298982/7bb18394-1f78-47a1-8610-84fe4c90a733)

![image](https://github.com/stashapp/stash/assets/30298982/8d5610bd-64c9-4305-a014-ee52580b5eee)

Workarround: Reload page F5. The box dissapears

**Comment by DogmaDragon** [comment]
I couldn't reproduce on https://github.com/stashapp/stash/commit/bf7cb78d6df30df9fcce0d6a194e9424b495ebb7 (latest release) or https://github.com/stashapp/stash/commit/bf0e0f22104037aabc8942db9d9eea219b93877d (latest develop).

It disappears automatically after 3 seconds, and clicking `x` allows me to disable it manually. 

Tested on Windows 10, Vivaldi 6.7.3329.35 (Chromium 124.0.6367.236).

--- 
[Failed to get subsystem status for purpose](https://stackoverflow.com/questions/76683323/content-script-js95-failed-to-get-subsystem-status-for-purpose) error might be caused by an add-on, I would try disabling them to see if the issue persists.

**Comment by phhemberg** [comment]
Hallo,

Well i tested it too on different versions. (Chromium, Chrome, Microsoft Edge) all for linux and some of them with no add-ons at all..... Still same issue. I know...... all of these browsers are similar to each other. I will try out vivaldi (Don't know if it's chrome based too). I will let you know how the testing goes. Otherwise i can test on another Linux distro.

**Comment by phhemberg** [comment]
Sorry to bug you again.... Just tried vivaldi... Same issue.. Can it be a JAVA thing? I'm on this version:

~$ java --version
openjdk 11.0.23 2024-04-16
**OpenJDK Runtime Environment (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1)**
OpenJDK 64-Bit Server VM (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1, mixed mode, sharing

**Comment by phhemberg** [comment]
FOUND the issue.

It was a Theme problem :-( on this theme: https://docs.stashapp.cc/user-interface-ui/themes/pulsar/ . Now i just have to find out what causes the problem. Thank you for all your work - and for a nice application.

**Comment by DogmaDragon** [comment]
@phhemberg try removing:
```css
.toast-container {
    left: 74%;
    top: 1rem;
}
```

**Comment by phhemberg** [comment]
Thank you - The above fixed the issue.

So this is not a bug in the application it self. I guess this can be closed then.

Have a nice day.

**Comment by jotipel889** [comment]
> @phhemberg try removing:
> 
> ```css
> .toast-container {
>     left: 74%;
>     top: 1rem;
> }
> ```

This worked perfectly. Thank you!
