### ISSUE TITLE
[Feature] Add PerformerDetailsPanel to PluginAPI.components

### ISSUE THREAD

**Issue by Valkyr-JS** [stashapp/stash#4880]
I've been working on a plugin and I believe I need a component to be added to the list of available components that can be patched via the plugin API. I've attached a screenshot of where I'm looking to add my own UI component. I believe it's in between `PerformerDetailsPanel` and `DetailsEditNavbar`.

I'm not looking to replace the existing details panel, rather add a new component directly beneath it. My understanding is that will happen with using `PluginApi.patch.after("PerformerDetailsPanel", ...)` once the `PerformerDetailsPanel` component has been added to the list. If so, can the `PerformerDetailsPanel` component be added?

Apologies if I've misunderstood how this should work!

![placement](https://github.com/stashapp/stash/assets/154020147/8ea6b756-2ac9-4212-b256-26adc67f07fc)

**Comment by S3L3CT3DLoves** [comment]
I have a UI plugin that works by adding a tab to the Scene page as well... I never found a Plugin feature to add such a UI, so I ended up building it from scratch in JS.
Would love to see a real "Add tab to this list of tabs" or "Add text to this"  plugin type

**Comment by WithoutPants** [comment]
In future, please add these requests to #4510
