### ISSUE TITLE
[Feature] Subtitle Support

### ISSUE THREAD

**Issue by MystifyingShadow** [stashapp/stash#495]
**Describe the solution you'd like**
AdultTime has been adding subtitles to their newest videos, It would be nice if the Stash player supported them.

**Additional context**
AdulTime subtitles are in the .vtt format.

**Comment by laymn** [comment]
+1. 
I want there is a way to play a scene with seperate srt subtitles.

**Comment by icedstick** [comment]
+1
For .mkv subtitle compatibility as well.
