### ISSUE TITLE
[Bug Report] BangBros Scrape Requires AyloAPI

### ISSUE THREAD

**Issue by jeremymeyers** [stashapp/stash#4960]
**Describe the bug**
Scraping BangBros (and possibly others) now requires the AyloAPI provider, which isn't added to existing Stash installs where the Brazzers scraper already exists

**To Reproduce**
1. Update to current version 0.26.1
2. Click the scrape button on a scene with a Brazzers URL

Error appears in log:
DEBU[2024-06-11 14:44:30] Scraper script <C:\Python311\python.exe BangBros.py scene-by-url> started
ERRO[2024-06-11 14:44:30] [Scrape / BangBros] Traceback (most recent call last):
ERRO[2024-06-11 14:44:30] [Scrape / BangBros]   File "M:\stash-tools\CommunityScrapers\scrapers\community\BangBros\BangBros.py", line 7, in <module>
ERRO[2024-06-11 14:44:30] [Scrape / BangBros]     from AyloAPI.scrape import (
ERRO[2024-06-11 14:44:30] [Scrape / BangBros] ModuleNotFoundError: No module named 'AyloAPI'
ERRO[2024-06-11 14:44:30] could not unmarshal json from script output: EOF
ERRO[2024-06-11 14:44:30] scrapeSceneURL: input: scrapeSceneURL could not unmarshal json from script output: EOF
DEBU[2024-06-11 14:44:30] scrapeSceneURL: {"url":"https://bangbros.com/video115771/the-ass-on-dayna-vendetta-is-insane"}

**Expected behavior**
Scraping happens as expected, or an error message detailing the need for an additional scraper to be installed.

**Additional context**
I know adding dependencies would be a lot of work, so maybe the scrapers could have a description field like the plugins do now?

**Comment by feederbox826** [comment]
This should already be installed with the v24 installer flow. How are you installing it?

https://github.com/stashapp/CommunityScrapers/blob/master/scrapers/BangBros/BangBros.yml#L2

**Comment by jeremymeyers** [comment]
Downloaded latest version from the button on the "About" page, replaced existing stash-win.exe with downloaded version, run app (upgrades database)

**Comment by feederbox826** [comment]
Sorry. I mean how are you installing the scraper?

**Comment by WithoutPants** [comment]
As noted above, this should be addressed by installing the scraper via the scraper management interface.
