### ISSUE TITLE
[Feature] Bulk Tag Editing

### ISSUE THREAD

**Issue by UncertainMongoose** [stashapp/stash#4977]
### Is your feature request related to a problem? Please describe.
Selecting multiple tags in the `/Tags` page doesn't allow the user to assign parent tags or sub-tags to multiple Tags at the same time. There is no bulk edit menu like there is for the `/Performers` and `/Scenes` pages.

---

### Describe the solution you'd like
The same bulk edit functionality as the Performer and Scene pages.

---

### Additional context

The edit button present on the performers page:
<img width="1460" alt="Screenshot 2024-06-16 at 10 33 23 AM" src="https://github.com/stashapp/stash/assets/140642754/210c2c4c-7119-4705-8b74-90bafbc12b41">

Edit button missing from the Tags page
<img width="1460" alt="Screenshot 2024-06-16 at 10 30 38 AM" src="https://github.com/stashapp/stash/assets/140642754/1e02cc07-35df-4173-a79e-5e3af267f041">

**Comment by WithoutPants** [comment]
Already resolved by #4925 in the develop build.
