### ISSUE TITLE
[Feature] Play Count button should be hidden if 'Enable Scene Play history' is disabled

### ISSUE THREAD

**Issue by IAmKontrast** [stashapp/stash#4979]
I have disabled the feature 'Enable Scene Play history'. Therefore the new Play Count button from #4714 should not be visible.
Tried to hide it with css but unfortunately this also hide the O Count. Any idea?

**Comment by WithoutPants** [comment]
`Enable play history` needs better wording. Enabling it means that the play count will be incremented when a scene is played (in accordance with the minimum play percent setting). The Play Count button allows for manually incrementing the play count for users that don't want it to be done automatically.

**Comment by IAmKontrast** [comment]
> Looks like both counters use the same class names, so it needs some trickier CSS. Try this:
> 
> ```
> span.scene-toolbar-group > span:nth-child(2) > div.count-button {
>     display: none;
> }  
> ```

Works like a charm! Thank you!

**Comment by IAmKontrast** [comment]
> `Enable play history` needs better wording. Enabling it means that the play count will be incremented when a scene is played (in accordance with the minimum play percent setting). The Play Count button allows for manually incrementing the play count for users that don't want it to be done automatically.

Renaming (adding words like automatic or auto-increment) would make it definitely more obvious. Also merging `Enable Scene Play history` and `Minimum Play Percent` to a single settings row would help.
