### ISSUE TITLE
[Bug Report] Performers not being ordered by name inside of scene

### ISSUE THREAD

**Issue by MystifyingShadow** [stashapp/stash#498]
**Describe the bug**
The performers are not being ordered by name inside of the scene detail and preview box.

**To Reproduce**
1. Create two performers, the first one with a Z and the first with a A.
2. Click on a scene with those two performers.
3. Click on Performers.
4. The Performers are ordered by Id and not the Name.

**Expected behavior**
The performers should be ordered by name

**Comment by julien0221** [comment]
I just tried to reproduce this behaviour and it looks now it works all good.

**Comment by peolic** [comment]
This is not resolved yet.
The performers are in the order in which they are inserted into the `performers_scenes` table.
