### ISSUE TITLE
[Feature] Generate subtitles

### ISSUE THREAD

**Issue by dumdum7** [stashapp/stash#4983]
**Is your feature request related to a problem? Please describe.**
I have to generate subtitles manually every time I add a new scene.

**Describe the solution you'd like**
Stash could automatically generate subtitles as part of the Generate task. It would use a speech to text model like whisper.

**Describe alternatives you've considered**
I currently manually run whisper-standalone-win over all my Stash library directories with the following command: `faster-whisper-xxl.exe "D:\stash\library" --language=en --model=large-v3 --batch_recursive --skip -pp`

**Additional context**
https://github.com/openai/whisper
https://github.com/SYSTRAN/faster-whisper
https://github.com/Purfview/whisper-standalone-win

**Comment by WithoutPants** [comment]
This is better suited for a plugin or external script.
