### ISSUE TITLE
[Feature] Subtitle scrubber

### ISSUE THREAD

**Issue by dumdum7** [stashapp/stash#4984]
**Is your feature request related to a problem? Please describe.**
I want to jump to a part of the video where the performer says something.

**Describe the solution you'd like**
Sort of like what Google Recorder has where the transcription is displayed and you can click on a word to jump to the time when the word was said. It could probably be located where the scrubber is.

**Describe alternatives you've considered**
I can't think of any alternatives.

**Additional context**
https://static1.makeuseofimages.com/wordpress/wp-content/uploads/2023/08/google-recorder-app-transcription-page.jpg

**Comment by WithoutPants** [comment]
This is not something I'd consider for the core application, and is better suited for a plugin.
