### ISSUE TITLE
[Feature] Order scenes inside of movie by scene order

### ISSUE THREAD

**Issue by MystifyingShadow** [stashapp/stash#499]
**Describe the solution you'd like**
An option do sort by scene order inside of the movie page.
Maybe it should even be the default sorting.

**Comment by VonTittyslappen** [comment]
Hi there

This has already been requested via the following issue:-

https://github.com/stashapp/stash/issues/398

Cheers :)

**Comment by bnkai** [comment]
Already mentioned in #398. Closing.
