### ISSUE TITLE
[Enhancement] Tag thumbnails

### ISSUE THREAD

**Issue by StashAppDev** [stashapp/stash#5]
https://github.com/stashapp/StashServer/issues/32

**Comment by echo6ix** [comment]
fwiw i made a concept for tag thumbnails

![Untitled-1](https://user-images.githubusercontent.com/37937507/57185711-66cb5300-6e9e-11e9-9888-bbe77422acbd.png)

**Comment by echo6ix** [comment]
A better interface concept #108 for the tag list thumbnail view.

![tag list grid view](https://user-images.githubusercontent.com/37937507/64059941-bcd1ae00-cb93-11e9-9350-a71982e62802.png)

- Stock tag icon for tag thumbnails missing cover image is from https://fontawesome.com/icons/tag?style=solid
- The edit icon for each card is from here https://fontawesome.com/icons/edit?style=solid
- Each card is in a container called `.bp3-card`. I think it would be interesting to _very subtly_ lighten the colour of the `.bp3-card` container when the mouse hovers over the container.

#### What does the edit icon do?
- On the mouseover event of a card, an [edit icon](https://fontawesome.com/icons/edit?style=solid) appears on the bottom right of the card (i may have used a colour thats too dark in the concept).
- The icon is an indicator that you can click it to edit tag details
- On the mouseover/hover of the actual icon, the icon should turn a lighter colour
- The reason for directing the user to a page that edits the tag is that I'm assuming there will be more to edit than just the tag name. Such as, tag cover image/thumbnail; tag deletion, rename tag; assign tag aliases (aka subtags from the roadmap).

#### What do the scenes and marker buttons do?
The `scenes` or `markers` button will determine what the user will ultimately see when clicking a tag card. If `scenes` is depressed, as represented in the concept, then the user is set to view scenes when clicking a tag, and vice-versa with `markers`.
