### ISSUE TITLE
[Feature] Compatible with python installed by microsoft store

### ISSUE THREAD

**Issue by DDXDB** [stashapp/stash#5025]
python installed through Microsoft Story does not write %PATH%, but global calls can be made using python.

**Comment by feederbox826** [comment]
It can be used, the path to python just has to be manually specified by the user

**Comment by DDXDB** [comment]
> It can be used, the path to python just has to be manually specified by the user

What I mean is to use it without manually writing %PATH%. Just like any other CLI program.

**Comment by DogmaDragon** [comment]
Go to **Settings** > **System** and under Applications Paths header set **Python Executable Path** if you don't want to use environmental variable PATH.
