### ISSUE TITLE
[Feature] Add scene descriptions to Is Missing filters

### ISSUE THREAD

**Issue by halorrr** [stashapp/stash#503]
**Is your feature request related to a problem? Please describe.**
In adding media I find myself often looking to find media that does not have a description attached to it.

**Describe the solution you'd like**
 It would be very useful to have descriptions included as an option in the Is Missing filter.

**Describe alternatives you've considered**
I tried modifying the URL query in case it was hidden to have `{"type":"isMissing","value":"description","modifier":"EQUALS"}` but no such luck. The process has been very manual to find the missing descriptions.

**Additional context**
N/A

**Comment by bnkai** [comment]
The database field for "description" is "details".
Switch to `{"type":"isMissing","value":"details","modifier":"EQUALS"}` and it should work
