### ISSUE TITLE
[Feature] Persist video filters

### ISSUE THREAD

**Issue by elshanta** [stashapp/stash#5049]
**Is your feature request related to a problem? Please describe.**
Video filters are great but are not persistent.

**Describe the solution you'd like**
It would be great to store preset filters for specific video.

**Additional context**
<img width="431" alt="Captura de pantalla 2024-07-05 a la(s) 19 51 54" src="https://github.com/stashapp/stash/assets/118694722/f06fb693-98de-4d4b-a6cc-aca7829073e9">

**Comment by DogmaDragon** [comment]
Duplicate of https://github.com/stashapp/stash/issues/4345.
