### ISSUE TITLE
[Feature] Opening Edit tab when Scene is not organized

### ISSUE THREAD

**Issue by IAmKontrast** [stashapp/stash#5052]
Almost every time I need to go to the Edit tab opening a not organized Scene.

**Solution 1 (easiest):**
Opening Edit tab every time for not organized scenes.

**Solution 2:**
Opening Edit tab every time for not organized scenes. Opt-in or opt-out this feature in the settings.

**Solution 3:**
Make the startup tab configurable. (Example: Opening 'File info' tab for every scene every time)

**Solution 4 (best / most flexible):**
Make the startup tab configurable. Opt-in or opt-out this feature for not organized scenes.

Opening different tabs already implemented by @yoshnopa in #4032. This should help a lot.

**Comment by feederbox826** [comment]
implemented with a plugin https://github.com/feederbox826/plugins/tree/main/plugins/edit-unorganized

startup tab is customizable and can be triggered even if scene is organized

**Comment by IAmKontrast** [comment]
@feederbox826 AWESOME! Works like a charm! Thank you very much, particularly for the quickness and solution 4!

You could add the information (outside the yaml file) that CommunityScriptsUILibrary is required and can be installed from the official CommunityScripts source.

And don't forget to update your readme with the new plugin. 😉
