### ISSUE TITLE
Issue: 'Show Male Performers' Setting Not Retained Across Sessions

### ISSUE THREAD

**Issue by gitbork** [stashapp/stash#5065]
**Description:**

The 'Show Male Performers' setting in the scraping configuration should persist across application restarts, page reloads, and different browser sessions. Currently, this setting does not remain enabled when loading the application in a new session (e.g., in a different browser) or after a server/application reload.

**Steps to Reproduce:**

1. Enable the 'Show Male Performers' setting in the scraping configuration.
2. Reload the page, restart the application, or open the application in a different browser session.
3. Observe that the 'Show Male Performers' setting is not retained.

**Expected Behavior:**

The 'Show Male Performers' setting should remain enabled across sessions and after application restarts.

**Actual Behavior:**

The 'Show Male Performers' setting does not stay enabled when reloading the application or starting a new browser session.

**Screenshot:**

![image](https://github.com/stashapp/stash/assets/26959898/f1d5a034-d940-4d3f-9d63-9a982b098b7b)

**Additional Notes:**

It can be frustrating to have to re-enable this setting repeatedly, especially when other settings retain the user's preferences. Initially, I wondered if this behavior was intentional, but I quickly realized it was likely an oversight. Given the dedication and quality of the development team, I'm confident this issue will be addressed in a future update.

Thank you for the fantastic app! As a queer user, my partner and I greatly appreciate your ongoing efforts and commitment to inclusivity.

**Comment by DogmaDragon** [comment]
Related to https://github.com/stashapp/stash/issues/3210, https://github.com/stashapp/stash/issues/4982

Do you have cookies enabled? It should persist through reloads and restarts. Only deleting browser cookies/storage, using a different browser or using incognito mode should reset them. 

Tagger config is stored in [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) on your browser. But it's on the [roadmap at 40 position](https://github.com/orgs/stashapp/projects/5) to improve it.
