### ISSUE TITLE
[Feature] url links in details

### ISSUE THREAD

**Issue by p0rnb0x** [stashapp/stash#5083]
**Is your feature request related to a problem? Please describe.**

Links in details not highlighted and not clickable.
i keep more links like manyvids, fansly, onlyfans in details.

**Describe the solution you'd like**

Pls support links in details. at least performer details

**Describe alternatives you've considered**

copy paste links in new tab. not very convenient to do

**Comment by bob123491234** [comment]
The next version of Stash will allow for multiple URLs to be added to performers, similar to how multiple URLs can be added to scenes currently.

**Comment by DogmaDragon** [comment]
Duplciate of https://github.com/stashapp/stash/issues/1868
