### ISSUE TITLE
[RFC] Using UI settings in pluginName.yml

### ISSUE THREAD

**Issue by David-Maisonave** [stashapp/stash#5086]
### Description
- How does a plugin get settings values for fields created using *.yml file (via python)?
- Is there a way to set default value?

### Scope
I've created a plugin [RenameFile](https://github.com/David-Maisonave/Axter-Stash/tree/main/plugins/RenameFile), and I've added UI settings via the renamefile.xml.
![PluginSettingsField](https://github.com/user-attachments/assets/0536ac54-ebd5-43ac-bdd0-e3613c120cdb)

But I haven't found any example Python code that is able to read the settings.  I also did a SqLite database dump, to see if I could find the values I set, and it was no where in the dump.

**Where are these settings being stored, and how can I read the values using Python?**
I did find some example code in JavaScript [VideoScrollWheel.js](https://github.com/stashapp/CommunityScripts/blob/main/plugins/VideoScrollWheel/VideoScrollWheel.js).
`const v25Settings = await csLib.getConfiguration("videoScrollWheel", {}); // getConfiguration is from cs-ui-lib.js`
However, I'm not sure how to convert that to Python.

**Also, is there a way to set these UI variables to a default value?**

FYI:
I'm aware the current common method for user settings is to have the user modify a pluginName_settings.py file, but I prefer to give the user a GUI option if possible.

**Comment by bob123491234** [comment]
Settings set from the UI can be accessed using the `configuration` graphql query. You can look at [Timestamp Trade](https://github.com/stashapp/CommunityScripts/blob/ccd6312087597491b51c4d7933da8dad19435e46/plugins/timestampTrade/timestampTrade.py#L756) to see an existing Python implementation of it. Default values are set within the .py file in this example.

**Comment by David-Maisonave** [comment]
Thank you very much. It was easy to figure out with the [Timestamp Trade](https://github.com/stashapp/CommunityScripts/blob/ccd6312087597491b51c4d7933da8dad19435e46/plugins/timestampTrade/timestampTrade.py#L756) code.
