### ISSUE TITLE
[Feature] Option to associate an O-Event with specific performers in a scene

### ISSUE THREAD

**Issue by jtjb07** [stashapp/stash#5093]
**Is your feature request related to a problem? Please describe.**
With media such as JAV, edited content and compilations, using the O-count button can lead to incrementing the O-count value for a large number of performers, when it may be preferable to increase the O-count for only a select group of these performers. This is most pronounced in the case of JAV - because an entire JAV movie is treated as a single scene on StashDB, a viewer might only view a specific scene of the movie, and thus would want to only increment the O-count for the performer in that scene. Currently, using the O-button for this type of content can lead to many "fake" O-event counts for performers.

**Describe the solution you'd like**
Add a drop-down option allowing the user to select a specific performer to associate with the O-Event. Otherwise, if the user clicks the O-count button, then all of the performers receive an O-Event like normal.

![ex1](https://github.com/user-attachments/assets/b74e5410-9f4c-47d7-a19c-b16ecf303e77)

![ex2](https://github.com/user-attachments/assets/4f0445ee-3bab-4a23-a6eb-e7dd6fd32197)

**Comment by stg-annon** [comment]
an alternative solution could potentially be to create a marker at the timestamp when the o-count is selected as an option, and also add performers to markers

**Comment by WithoutPants** [comment]
This would be better addressed by splitting large videos into smaller scenes, which is a separate, larger planned feature. This is far more granularity for the o-count concept than I'm comfortable adding.
