### ISSUE TITLE
[Bug Report] groups not added in bulk scene update

### ISSUE THREAD

**Issue by Tweeticoats** [stashapp/stash#5095]
**Describe the bug**
In the latest dev release performing a bulk update of a scene to add the selected scenes to a group no longer works after the change of movies to groups.

**To Reproduce**
1. go to the scenes list page
2. click the check box to select one or more scenes 
3. click the hamburger aka 3 dots button
4. click the edit button
5. in the groups section select a group to add
6. clck apply

**Expected behavior**
looks like the query is called but the scenes are not added to the group

**Comment by DogmaDragon** [comment]
Reproduced on v0.26.2 f79677ba.

**Comment by WithoutPants** [comment]
Duplicate of #5078
