### ISSUE TITLE
[Bug Report] Firefox has no tag box in tagger view

### ISSUE THREAD

**Issue by feederbox826** [stashapp/stash#5116]
**Describe the bug**
Firefox is missing a tag selection/ addition box in tagger view

**To Reproduce**
1. Open stash in firefox
2. Switch to tagger view
3. Scrape scene

**Expected behavior**
Tagger box is present like it is on Chrome

**Screenshots**
![firefox_LqdpUSHEC5](https://github.com/user-attachments/assets/090d01b0-03de-4ef5-825d-a1558c2d7cbb)

**Stash Version: (from Settings -> About):**
v0.26.0/ v0.26.2-57-gc79f299d

**Desktop (please complete the following information):**
 - OS: W10 Pro 22H2
 - Browser Firefox
 - Version 128.0.3

**Smartphone (please complete the following information):**
N/A

**Additional context**
I've disabled everything I could, clean docker instance, no plugins etc... Absolutely just befuddled

**Comment by Maista6969** [comment]
Is "Set tags" enabled in the Tagger configuration?
![bilde](https://github.com/user-attachments/assets/4b81652b-e3ed-4bda-bc1c-28468d75fa1b)

**Comment by feederbox826** [comment]
Argh. that was it. I didn't expect my chrome instance to carry over localstorage
