### ISSUE TITLE
[Feature] Short Form Title (50 chars or less.)

### ISSUE THREAD

**Issue by brokje** [stashapp/stash#512]
**Describe the solution you'd like**
Now you can choose the studio, which is awesome! But it would be even more awesome if you go to studios and see scenes and movies and when you press it you will the scenes and movies.

**Comment by bnkai** [comment]
Can you edit the title ? Also i can't understand  what issue you are referring to. Did your post got cut ?

**Comment by WithoutPants** [comment]
Closing pending further information.
