### ISSUE TITLE
[Bug Report] Rounding errors in performer weight field

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#5120]
**Describe the bug**
Entering a weight with any decimal value will _often_--not always--yield rounding errors and an incorrect weight value.

**To Reproduce**
1. Go to a performer entry
2. Click on `edit`
3. Enter the value `10.8` and save profile
4. Weight returned is `8`

I should note this seems difficult to reproduce consistently. But attempting different decimal values each time is the quickest way to reproduce the bug.

**Expected behavior**
Either to round up the nearest ones or truncate the decimals altogether?

**Stash Version: (from Settings -> About):**
v0.26.2-58-gc8d4dacf

**Comment by echo6ix** [comment]
After more testing I don't think this is a Stash problem, but a Stash plugin problem. When I disabled all plugins I cannot reproduce any errors.

I'll leave it up to the admin if they think they should close this issue as: not a Stash bug, but a Stash plugin bug

**Comment by WithoutPants** [comment]
Unable to reproduce. Weight is stored as an integer, and is truncated automatically in the UI.
