### ISSUE TITLE
❓[RFC] Stash executable binary for each OS

### ISSUE THREAD

**Issue by David-Maisonave** [stashapp/stash#5134]
# Executable binary for each OS
What is the executable binary for each OS?

I need a list of the Stash executable binary for each OS.
I need it for the following plugin code, which checks to see if Stash is running, and if exception is thrown, it starts the executable.
``` python
try:
	result = stash.stash_version()
except:
	pass
	stash.Trace("Failed to get response from Stash.")
	if platform.system() == "Darwin": # Mac OS
		args = [f"{pathlib.Path(stash.PLUGINS_PATH).resolve().parent}{os.sep}stash"]
	elif platform.system() == "Linux":
		args = [f"{pathlib.Path(stash.PLUGINS_PATH).resolve().parent}{os.sep}stash-linux"]
	else:
		args = [f"{pathlib.Path(stash.PLUGINS_PATH).resolve().parent}{os.sep}stash-win.exe"]
	if 'command' in task and task['command'] != "":
		cmd = task['command'].replace("<stash_path>", f"{pathlib.Path(stash.PLUGINS_PATH).resolve().parent}{os.sep}")
		args = [cmd]
	result = f"Execute process PID = {stash.ExecuteProcess(args)}"
```

I have a Windows setup, so I'm sure what's the executable for Windows, but I'm not sure about the other OS.
I downloaded the compressed files for stash-macos and stash-linux, but it wasn't clear to me what were the binaries.

I appreciate any help.
Thanks

**Comment by DogmaDragon** [comment]
You can see the pre-built binaries Stash offers in the release page https://github.com/stashapp/stash/releases/tag/v0.26.2

**Comment by David-Maisonave** [comment]
> You can see the pre-built binaries Stash offers in the release page https://github.com/stashapp/stash/releases/tag/v0.26.2

I did that, but as I said in my post, it's not clear to me what are the binaries.

**Comment by David-Maisonave** [comment]
Here's an example of MacOS downloadable file decompressed:
<img width="299" alt="MacOS" src="https://github.com/user-attachments/assets/331163ad-b3d4-4efd-a4aa-8c809a13c8b6">

**Comment by DogmaDragon** [comment]
Each of them (except stash-ui) are the executable binaries. They are just packaged apps, just like Windows one.

**Comment by David-Maisonave** [comment]
> Each of them (except stash-ui) are the executable binaries. They are packaged apps, just like Windows one.

Thank you very much.
