### ISSUE TITLE
[Bug Report] The directories mounted via rclone cannot be read within a Docker container.

### ISSUE THREAD

**Issue by wsndshx** [stashapp/stash#5137]
**Describe the bug**

I've set up a Container (CT) in Proxmox VE (PVE) and installed Docker and Rclone within it. I also installed Stash in Docker. When I tried to add content from OneDrive into Stash, the process of mounting OneDrive using Rclone was successful. However, I encountered issues when trying to import the mounted directory into Stash and read the video files inside.

It seems that Stash is unable to read the content I've mounted; it behaves as if it's an empty directory. However, when I list the contents of the directory through the command line in the terminal, I can access everything normally.

**To Reproduce**

1. Set up the mount for the Stash container: `/root/stash/data:/data`.
2. Use the command `rclone mount OneDrive_H: /root/stash/data/onedrive_H --allow-other --allow-non-empty --vfs-cache-mode writes -daemon` to mount the directory.
3. In the Stash control panel, add the path for the repository: `/data/onedrive_H`.
4. Initiate a scan.
5. The task finishes quickly, and the Stash interface remains empty.

**Expected behavior**
Stash should correctly identify all the videos within my folder.

**Screenshots**
directory mounting situation: 
![directory mounting situation](https://github.com/user-attachments/assets/f100663f-e795-4ece-a8b5-ba8607a95017)

contents listed in the terminal:
![contents listed in the terminal](https://github.com/user-attachments/assets/26adf2e9-05e1-4edf-b3e1-6a5eac8d9402)

Stash the library:
![Stash the library](https://github.com/user-attachments/assets/0944c41b-f725-4fc5-b651-22c376d30cde)

Stash is unable to access the content within the directory:
![Stash is unable to access the content within the directory](https://github.com/user-attachments/assets/f048ab76-3651-45be-b7f6-bac938bb1a12)

**Stash Version: (from Settings -> About):** v0.26.2
![Stash Version](https://github.com/user-attachments/assets/4e9ce884-4d92-4998-b76c-ce1dad246b6d)

**Desktop:**
 - OS: Windows
 - Browser: Microsoft Edge
 - Version: 127.0.2651.105

**Additional context**
- The template used for CT containers in PVE is `alpine-3.18-default.`
- rclone version v1.62.2-DEV.

**Comment by feederbox826** [comment]
Can you try running the command **within** the docker container? It looks like you're runing the commands on the host side, while docker seems to [have](https://superuser.com/a/1374808) [issues](https://stackoverflow.com/a/49021109) [with](https://stackoverflow.com/a/53632103) FUSE mounts

**Comment by wsndshx** [comment]
> Can you try running the command **within** the docker container? It looks like you're runing the commands on the host side, while docker seems to [have](https://superuser.com/a/1374808) [issues](https://stackoverflow.com/a/49021109) [with](https://stackoverflow.com/a/53632103) FUSE mounts

This is great! Based on the information from the link you provided, I added the following content to the end of my `docker-compose.yml` file:

```yml
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
```

After doing this, Stash can now successfully access the content in my OneDrive. Everything is working fine so far.
