### ISSUE TITLE
[Bug Report] Parent tags are not added directly to media

### ISSUE THREAD

**Issue by lIIIIllIllllllIl** [stashapp/stash#5138]
**Describe the bug**
When adding a child tag to media, the parent tag is not directly added in any capacity. The parent is only tied to the media loosely by filter functions elsewhere in the UI.

**To Reproduce**
1. Create tags [Apple] and [Fruit]
2. Associate [Fruit] as parent tag of [Apple]
3. Media File -> Edit -> Tags -> Add [Apple] -> Save -> Details
4. Observe nowhere on this page does it signify that this media involves [Fruit]. 

**Justification**
To the user, the tagging looks incomplete and bare, as this video should be tagged with [Apple] and [Fruit]. To be complete, the user manually adds the tag of [Fruit] to the video. Doing so should be already done by Stash.

When using filters, one can search [Fruit] and receive media tagged with [Apple], if they have the toggle checked. However no where on the returned media would it show the media involves [Fruit], when in reality the presence of [Apple] should signify that it does. Therefore logically one would expect tagging [Apple] should automatically tag [Fruit], as if the user included both.

**Suggested Implementation**
When [Apple] is tagged to a piece of media, [Fruit] should not populate in the edit box until the user clicks 'Save'. This prevents unintuitive user experiences where the user tags [Helicopter] and suddenly [Auto] [Flying Machine] [Aircraft] [Machine] all populate the edit box unexpectedly.

**Expected behavior**
Adding tag [Apple] to a media file should automatically add tag [Fruit]. Parent tags should be tied to the child tag directly. Therefore if [Apple] is present on the tags of piece of media, [Fruit] must be by definition of the parent-child relationship.

**Stash Version: (from Settings -> About):**
v0.26.2

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox
 - v128.0.2 (64-Bit)

**Comment by feederbox826** [comment]
Stash does not edit the file, all tags are saved locally in the stash database. This is not a bug as this is not an intended feature.

**Comment by DogmaDragon** [comment]
Not a bug, but there are several suggestions for improving the system. https://github.com/stashapp/stash/issues/3693, https://github.com/stashapp/stash/issues/3281, https://github.com/stashapp/stash/issues/3400
