### ISSUE TITLE
[Bug Report] Stash server as scraper not working

### ISSUE THREAD

**Issue by laynlownc** [stashapp/stash#5143]
**Describe the bug**
I added a 2nd stash instance as a scraper following the [documentation](https://docs.stashapp.cc/in-app-manual/scraping/scraperdevelopment/#stash) and it errors with or with out a username and password set.  If I set it up with my username and password I get "non-200 OK status code: 401 Unauthorized body"  If I set it up without a username and PW I get "on-200 OK status code: 422 Unprocessable Entity body"

**To Reproduce**
1. configure stash scraper per documentation
2. Attempt to identify scene using  stash scraper
3. Check logs

**Expected behavior**
I would have expected it to attempt to identify the scene using the metadata from the other instance

**Stash Version: (from Settings -> About):**
v0.26.2 on both. 
**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [chrome]
 - Version [Version 127.0.6533.119]

**Comment by laynlownc** [comment]
To try and help I have done some more troubleshooting. Right now I suspect its related to models not being updated. I have 2 instances set up, one I use just to rename my old collection that is poorly organized, and the 2nd is the one I use for my main collection. Some of the metadata i am manually adding and would like to be abel to move it to my main instance after the files are renamed and moved. 

Here is the full error when I don't try to use a username and password. 
 non-200 OK status code: 
422 Unprocessable Entity body: "{ "errors ":[{ "message ": "Variable  "$c " of type  "SceneHashInput " used in position expecting type  "SceneHashInput! ". ", "locations ":[{ "line ":1, "column ":49}], "extensions ":{ "code ": "GRAPHQL_VALIDATION_FAILED "}},{ "message ": "Cannot query field  "file " on type  "Scene ". Did you mean  "files " or  "title "? ", "locations ":[{ "line ":1, "column ":79}], "extensions ":{ "code ": "GRAPHQL_VALIDATION_FAILED "}},{ "message ": "Cannot query field  "height " on type  "Performer ". Did you mean  "weight " or  "height_cm "? ", "locations ":[{ "line ":1, "column ":265}], "extensions ":{ "code ": "GRAPHQL_VALIDATION_FAILED "}},{ "message ": "Cannot query field  "aliases " on type  "Performer ". ", "locations ":[{ "line ":1, "column ":352}], "extensions ":{ "code ": "GRAPHQL_VALIDATION_FAILED "}}], "data ":null}"
								
								
								
I went a tried to scrape a preformer, and was able to get a name returened, but I get this when I click on the name to import them and import the data 2nd instance. 								
error while fragment scraping with scraper RenameInstance: non-200 OK status code: 422 Unprocessable Entity body: "{ "errors ":[{ "message ": "Cannot query field  "height " on type  "Performer ". Did you mean  "weight " or  "height_cm "? ", "locations ":[{ "line ":1, "column ":109}], "extensions ":{ "code ": "GRAPHQL_VALIDATION_FAILED "}},{ "message ": "Cannot query field  "aliases " on type  "Performer ". ", "locations ":[{ "line ":1, "column ":196}], "extensions ":{ "code ": "GRAPHQL_VALIDATION_FAILED "}}], "data ":null}"

**Comment by Valkyr-JS** [comment]
Just to add that I appear to get the exact same errors. I'm guessing but it looks like it hasn't been updated to use the current graphql schema.

For performers
```
error while fragment scraping with scraper AddFriends meta: non-200 OK status code: 422 Unprocessable Entity body: "{\"errors\":[{\"message\":\"Cannot query field \\\"height\\\" on type \\\"Performer\\\". Did you mean \\\"weight\\\" or \\\"height_cm\\\"?\",\"locations\":[{\"line\":1,\"column\":109}],\"extensions\":{\"code\":\"GRAPHQL_VALIDATION_FAILED\"}},{\"message\":\"Cannot query field \\\"aliases\\\" on type \\\"Performer\\\".\",\"locations\":[{\"line\":1,\"column\":196}],\"extensions\":{\"code\":\"GRAPHQL_VALIDATION_FAILED\"}}],\"data\":null}"
```
For scenes
```
scraper AddFriends meta: non-200 OK status code: 422 Unprocessable Entity body: "{\"errors\":[{\"message\":\"Variable \\\"$c\\\" of type \\\"SceneHashInput\\\" used in position expecting type \\\"SceneHashInput!\\\".\",\"locations\":[{\"line\":1,\"column\":49}],\"extensions\":{\"code\":\"GRAPHQL_VALIDATION_FAILED\"}},{\"message\":\"Cannot query field \\\"file\\\" on type \\\"Scene\\\". Did you mean \\\"files\\\" or \\\"title\\\"?\",\"locations\":[{\"line\":1,\"column\":79}],\"extensions\":{\"code\":\"GRAPHQL_VALIDATION_FAILED\"}},{\"message\":\"Cannot query field \\\"height\\\" on type \\\"Performer\\\". Did you mean \\\"weight\\\" or \\\"height_cm\\\"?\",\"locations\":[{\"line\":1,\"column\":265}],\"extensions\":{\"code\":\"GRAPHQL_VALIDATION_FAILED\"}},{\"message\":\"Cannot query field \\\"aliases\\\" on type \\\"Performer\\\".\",\"locations\":[{\"line\":1,\"column\":352}],\"extensions\":{\"code\":\"GRAPHQL_VALIDATION_FAILED\"}}],\"data\":null}"
```
