### ISSUE TITLE
DLNA not working

### ISSUE THREAD

**Issue by justaguyinaz** [stashapp/stash#5148]
### Discussed in https://github.com/stashapp/stash/discussions/5140

<div type='discussions-op-text'>

<sup>Originally posted by **justaguyinaz** August 19, 2024</sup>
I installed on my Synology via Docker and the app works great. I can enable DLNA and see the server on a client, but get errors when trying to access it. One error shows "Start tag expected, '>' not found". It seems to be working for actually broadcasting its availability, but beyond that, nothing. Any ideas?</div>

**Comment by WithoutPants** [comment]
Refer to discussion.
