### ISSUE TITLE
[Feature] Add shuffle to photo galleries

### ISSUE THREAD

**Issue by Privitude** [stashapp/stash#5164]
Simple idea. I'm sure many of us have large galleries of images for certain categories/models/fetishes etc. We can already use Stash to view them full-screen with auto-advance. It would be awesome to be able to do this in random order.

**Comment by DogmaDragon** [comment]
You can already sort images in a gallery as random. It will be reflected in the lightbox view. 
![image](https://github.com/user-attachments/assets/2e58c67a-a9ac-43b6-a2c5-a190a5828bb0)
