### ISSUE TITLE
[Bug Report] ffmpeg does not work from path with spaces

### ISSUE THREAD

**Issue by MinasukiHikimuna** [stashapp/stash#5173]
Some parts of the bug report are not precise as I am opening this on behalf of a Discord user at the request of WithoutPants. The main gist of the issue is present. The original discussion can be found at: https://discord.com/channels/559159668438728723/559159931505213440/1277893370320257078

**Describe the bug**
A user in Discord has ffmpeg set to path `C:\Apps and Programs\ffmpeg-2024-08-26\bin\ffmpeg.exe`. This caused the following error log:
```
[transcode] error generating DASH manifest: FFProbe encountered an error with <\NAS\Studios\Example Studio\Example File.mp4>.
Error JSON:
{
    "error": {
        "code": -22,
        "string": "Invalid argument"
    }
}
```

Path can't be found due to spaces not being wrapped in quotes. 

**Expected behavior**
Stash should put quotes around ffmpeg path in Application Paths.

**Comment by WithoutPants** [comment]
I'm not able to reproduce this. Setting ffmpeg path to one containing spaces had no issues for me on my Windows 10 system. I'm not sure why changing the ffmpeg path fixed the issue for this user, but it doesn't seem to be related to having spaces in the ffmpeg path.
