### ISSUE TITLE
[Feature] Include markdown in docker image

### ISSUE THREAD

**Issue by Jakan-Kink** [stashapp/stash#5174]
**Is your feature request related to a problem? Please describe.**
As part of a feature request we worked on in Fanscrape we added markdown handling to clean the titles. However the way we implemented it requires the python module markdown.

**Describe the solution you'd like**
Add the python module markdown to the docker image, so that way users don’t need to go into the docker container and add it manually every release.

**Describe alternatives you've considered**
As mentioned in solution, the user could install markdown manually but that gets cumbersome each stash update.

**Comment by DogmaDragon** [comment]
There are no plans to add any new modules to the official Docker image. There is a project https://github.com/stashapp/stash/issues/4300 to overhaul the current image to move module installation to the entry scripts, as just increasing the image size is not practical and far from ideal.

**Comment by feederbox826** [comment]
override your pip install directory, and it will persist

**Comment by feederbox826** [comment]
also why not just regex for `**` instead of addng an entire library?

**Comment by Jakan-Kink** [comment]
Yea, I’ll just update the readme to point to the venv / python path instructions
