### ISSUE TITLE
Add stream link to scene web page

### ISSUE THREAD

**Issue by rudi123github** [stashapp/stash#52]
Feature reqest: Add stream link to scene page. Some media formats cannot be played by the JW player. However, the stream URLs play perfectly in a media player such as VLC and mpv. If the scene page has a link to the stream, the video can easily be opened in a media player. At the moment, it is too complicated to get the stream URL (e.g. http://127.0.0.1:8080/scene/49/stream.mp4) out of stash to view a vid that is not supported by JW player.

**Comment by rudi123github** [comment]
I created a pull request for this.

**Comment by WithoutPants** [comment]
This looks like it can be closed. @Leopere

**Comment by Leopere** [comment]
Fixed by #65

**Comment by Leopere** [comment]
Closed by #65 and resolves #62
