### ISSUE TITLE
Video Player Resize Ability

### ISSUE THREAD

**Issue by beot110** [stashapp/stash#520]
It would be great to add the ability of resizing the video player, I have an ultrawide screen  (3440×1440 ), when playing a video in non fullscreen, the player's height is greater then the screen's.

![1](https://user-images.githubusercontent.com/64889043/81146485-10956200-8f81-11ea-9fca-44bccb7030a1.png)
![2](https://user-images.githubusercontent.com/64889043/81146489-11c68f00-8f81-11ea-970e-2155b66f4a35.png)

Suggestions:
*Set the video player size in settings.
*Resize it by mouse when playing.
*Or make the video player size relative to the screen height and not width.

**Comment by WithoutPants** [comment]
Closing since I believe this is addressed by #562 . Please reopen if that is not the case.
