### ISSUE TITLE
[Feature] Let user change a video's audio pitch

### ISSUE THREAD

**Issue by GammelSami** [stashapp/stash#5201]
**Is your feature request related to a problem? Please describe.**
This will allow the user to temporarily fix messed up audio tracks or let them enjoy higher/deeper voices.

**Describe the solution you'd like**
A "Pitch" slider in the "Filters" tab.

**Comment by WithoutPants** [comment]
This is not really something we can do very easily. Video filters apply a filter across the display of the video frame. Changing audio pitch isn't something supported by video.js and is fundamentally quite different from video filtering. This is something for an external system or plugin.
