### ISSUE TITLE
[Feature] Configurable Live Transcode Encoder & Output

### ISSUE THREAD

**Issue by whitty-username** [stashapp/stash#521]
**Is your feature request related to a problem? Please describe.**
Live transcoding is very CPU intensive and most modern computers include some form of hardware accelerated encoding.

**Describe the solution you'd like**
The ability to select preferred hardware accelerated encoder and output type for FFmpeg to use. At the moment (I think) its hardcoded and not configurable by the user via the GUI or config file. 

For Example: 
Configurable live transcode encoder (including support for HW Accelerated encoders)
- VideoToolbox
- VAAPI
- Etc...

Configurable live transcode encoder output type
- H.264
- H.265/HEVC
- VP9
- Etc...

**Comment by bnkai** [comment]
For the hardware encoding part #305 is already present and i have already answered there.
For the live transcoder only 2 options are possible ( h264 in mkv , need to actually check that) and vp9 in webm. We need the codec/format to be compatible with  jwplayer and thus the browser.

**Comment by whitty-username** [comment]
Closing issue as resolved largely by #609
