### ISSUE TITLE
[RFC] stash url localhost:9999 should instead be localhost:6969

### ISSUE THREAD

**Issue by RayyanNafees** [stashapp/stash#5227]

**Comment by feederbox826** [comment]
[Whisparr also uses 6969](https://github.com/Whisparr/Whisparr/blob/a85a59122bd91cd75718ff4fbe4cf2df3a800687/src/NzbDrone.Host/Startup.cs#L151)

**Comment by WithoutPants** [comment]
This port can be changed in the `config.yml` file. As mentioned this 6969 is used by another app in a similar domain. I see no upside to changing the default port and a bunch of downsides.
