### ISSUE TITLE
[Bug Report] Preview scrubber broken on Firefox

### ISSUE THREAD

**Issue by dogwithakeyboard** [stashapp/stash#5231]
The gallery and scene card preview scrubber is not functional in Firefox. No issues in Edge which is the other browser on this machine. Hovering the mouse over the scrubber area throws an `Uncaught ReferenceError: TouchEvent is not defined` error in the console.

**Stash Version:**
Latest develop ca970b97

**Desktop:**
 - OS: Win10
 - Browser Firefox
 - Version 130.0

**Comment by DogmaDragon** [comment]
I suspect it's related to https://github.com/stashapp/stash/pull/5183. 

@yoshnopa could you take a look?
