### ISSUE TITLE
[Bug Report] Modal footers getting clipped

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#5232]
**Describe the bug**
This has been a legacy cosmetic bug where the bottom (footer) of a modal tends will overflow past the bottom of the viewport, rather than adjusting to the height of the viewport with the proper margin padding.

This specifically happens to the Edit Filter modal on any page it's available.

**To Reproduce**
1. Resolution should be 1920x1080 and scaling set at 125% _(this is the Windows default scaling for the laptop screen size and resolution)_
2. Go to any page where the edit filter button is available, such as the scenes grid view page
3. Click the edit filter button to bring up the modal
4. Add at least one filter criteria, such as `Is Missing title`. This will increase the height of the modal, moving it well past the bottom viewport

**Expected behavior**
The modal should be rendered completely contained within the viewport. Bottom margin padding should be preventing the modal from being flush with or overflowing past the bottom of the viewport.

**Screenshots**
![sid](https://github.com/user-attachments/assets/c2b2e242-2044-40c5-b640-37c48e462602)

![image](https://github.com/user-attachments/assets/bbe20cff-8b39-4ec1-b332-b636e29579e9)

**Stash Version: (from Settings -> About):**
v0.26.2-112-g0a982966

_Note: This is not a recent cosmetic bug. It has been rendering this way for as long as I can remember._

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Additional context**
I'm not sure if there are other modals within Stash that I have missed where this occurs.

**Comment by Gykes** [comment]
Okay, so based on  your Discord message I thought you were going somewhere different with this. 

I don't get this bug on 1080p or 4K. Will continue to convo in Discord and report back final results.

**Comment by echo6ix** [comment]
Apparently, I am able to correct the behavior with custom CSS adding `max-height: 90vh;` to the existing:

```css
@media (min-width: 576px) {
    .modal-dialog {
        max-height: 90vh;
    }
```
I'd still consider this a bug though, but I'll leave it to your discretion

**Comment by WithoutPants** [comment]
Alternatively, just adjust the height of the window to see the effect.

**Comment by echo6ix** [comment]
Other modals that are plagued by the same issue are:
- Identify
- Selective Clean

Looking at style guides for modals, I see this in common:
- Typically used to display focused dialog interaction (confirmations, file selectors, notifications, etc)
- Height is dynamic adjusting to the size of the content body
- Scales to the size of the screen
- Avoid modals that scroll vertically past the viewport or that go full screen

There seems like some exceptions, such as print preview type modals. Anyway I bring that up because it looks like the Identify modal kinda breaks the mold. Perhaps consider changing the Identify modal into a dedicate page ala the scene tools.

**Comment by WithoutPants** [comment]
Agree that Identify doesn't really conform to the style guide, but a redesign of that should be raised as a separate issue.
