### ISSUE TITLE
[Bug Report] Unexpected scroll to top when clicking page-count button.

### ISSUE THREAD

**Issue by cj12312021** [stashapp/stash#5239]
**Describe the bug**
Clicking the `page-count` (not the `drop-down`) button in the pagination (I use the bottom pagination) on the main list page, not the secondary lists, forces me back to the top of the page before I can input the page number I want to jump to.

**To Reproduce**
1. Go to Scene Page
2. Ensure the list has sufficient number of items to cause overflow on the page
3. Scroll down to the bottom pagination 
4. Click the `page-count` button (not the `drop-down`)
5.. Watch the page scroll to the top before you are able to provide a page number

**Expected behavior**
`page-count` button should stay in focus after clicking.

**Stash Version: (from Settings -> About):**
v0.26.2-112-g0a982966+

**Comment by DogmaDragon** [comment]
Reproduced on ba83da19.
