### ISSUE TITLE
[Feature] Automatic Looping For Short Videos

### ISSUE THREAD

**Issue by halorrr** [stashapp/stash#524]
**Is your feature request related to a problem? Please describe.**
When I have short webm files downloaded from sites like reddit, 4chan, etc. It would be nice to be able to have the video automatically loop.

**Describe the solution you'd like**
My ideal situation would be to have a config option to autoloop videos if their they are short (under a minute, but maybe have the breakpoint configurable)

**Describe alternatives you've considered**
Not sure on alternatives.

**Additional context**
N/A

**Comment by WithoutPants** [comment]
Already implemented. See `Settings -> Interface -> Maximum Loop Duration`
