### ISSUE TITLE
[Feature] Add lookalikes to performer profiles

### ISSUE THREAD

**Issue by miltuss** [stashapp/stash#5256]
Hello, it's not currently possible to link lookalikes together in Stash. 

It would be very interesting to add a feature that would make it possible to link performers who look alike, who resemble Hollywood stars, or others... The notion of look-alikes is quite common in the porn world.

https://www.imdb.com/list/ls033660121/

![Sélection_534](https://github.com/user-attachments/assets/0e5be2dd-96d7-431f-a8df-529103272a31)

Lookalike photos or performer cards should be visible on the profile. I could see this feature looking like the illustration below, with the possibility of adding other performers from the editing interface or from the main profile interface.

![Sélection_527](https://github.com/user-attachments/assets/82b8caa9-8585-4786-bba4-f05150b2b83f)

We could imagine a drop-down menu on the actresses page, showing images of look-alikes if available, and to avoid overloading not overload profile information.

**Comment by cj12312021** [comment]
I’m pretty sure these images still violate Githubs terms and conditions. Best to blur the whole performer images to leave as much to the imagination as possible.

**Comment by echo6ix** [comment]
Very niche FR. Could definitely fit within custom performer fields https://github.com/stashapp/stash/issues/885 (and following that, a plugin could add tab specific presentation).

**Comment by WithoutPants** [comment]
This is not something that I'd consider for core stash functionality. This is more suited for a plugin.
