### ISSUE TITLE
[Feature] Hide images associated with galleries in the image tab

### ISSUE THREAD

**Issue by miltuss** [stashapp/stash#5286]
Images that are already part of a gallery or multiple galleries should be hidden in the Images tab. There is no point displaying them in the Images tab if they are already organized in galleries. It would be good to hide them by default and give those who want to return to the old method the possibility of activating it in the settings.

**Comment by Gykes** [comment]
Imo, the point of the images tab is to list ALL images regardless of if they are currently in a gallery. We don't hide scenes from the scenes tab that are part of a movie/group.  So why do that for images?

Could potentially be a good plugin idea.

**Comment by StashManRon** [comment]
This is currently possible using a filter.

Filter by 'Galleries is Null' & then it's possible to save the filter & apply as default if desired.

**Comment by WithoutPants** [comment]
As noted, this is already possible via default filters.
