### ISSUE TITLE
Image external links as thumbnail

### ISSUE THREAD

**Issue by xeleven11** [stashapp/stash#529]
I'm trying to find something that can store external image or video in localhost as links scattered from the web. So whenever I load it from my desktop only a minimum of data will be stored in local drive. I'm not sure what this is exactly called. Anyway I just want to make some kind of porn tube for myself only. It doesn't have to include external video links for viewing as I'm interested in organizing pornstar images. I don't think stash has this feature though. I don't know if there is even an specific porn app for this or any other web image organizer.

**Comment by kermieisinthehouse** [comment]
This is unlikely to be implemented, this has privacy implications with the external servers, and Stash is designed to organize local content
