### ISSUE TITLE
[Bug Report] Docker build using old ffprobe 4.2.1

### ISSUE THREAD

**Issue by UltraHKR** [stashapp/stash#5291]
**Describe the bug**
Docker build using old ffprobe 4.2.1

**To Reproduce**
1. Setup Stashapp for x86-64 using docker-compose
2. Using to stashapp/stash:latest
3. Check the logs, at first "boot"
NOTE: This was an upgrade, but it shouldn't matter, if its new or upgraded install.

**Expected behavior**
The docker image should use the proper ffprobe release for new stashapp build

**Stash Version: [v0.27.0]**

**Additional context**
INFO[2024-09-23 00:56:48] using config file: /root/.stash/config.yml
WARN[2024-09-23 00:56:49] database schema version 58 does not match required schema version 67
WARN[2024-09-23 00:56:49] FFProbe version 4.2.1 detected, but 5.x or later is required
INFO[2024-09-23 00:56:49] [InitHWSupport] Supported HW codecs [0]:
INFO[2024-09-23 00:56:49] stash version: v0.27.0 (c45ae068) - Official Build - 2024-09-23 03:04:17
INFO[2024-09-23 00:56:49] stash is listening on 0.0.0.0:9999
INFO[2024-09-23 00:56:49] stash is running at http://localhost:9999/
INFO[2024-09-23 00:56:50] Version v0.27.0 (c45ae068) is already the latest released

**Comment by feederbox826** [comment]
```
❯ docker run -it stashapp/stash:latest ffprobe
ffprobe version 6.1.1 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 13.2.1 (Alpine 13.2.1_git20240309) 20240309
```

your logs do not reflect the older version of ffprobe, it is likely that you have a local ffprobe/ffmpeg binary in `/root/.stash/ffprobe` that is being prioritized

**Comment by UltraHKR** [comment]
My guess is that at some point in time I clicked the "download ffmpeg" due to whatever reason and it stayed on the "/root/.local" path...

**Comment by feederbox826** [comment]
I think a warning would be helpful, but avoiding the ffmpeg altogether might be detrimental if people prefer running their own versions
