### ISSUE TITLE
[RFC] UX of multiple URLs on performers and groups

### ISSUE THREAD

**Issue by xx790** [stashapp/stash#5292]
### Scope
URL(s) icon behavior on performers and groups can be annoying - you can't know what happens before you click it. And it hides everything until interaction.

##  Long Form

Prior to 0.27 update:
I have to keep all links as plain text. But I see all of them without interaction.

After 0.27 update:
all links are hidden under 🔗 icon.
Clicking icon can lead to two outcomes:

- open the link in a new tab - better than in the same tab but still disruptive;
- show a menu with all links if there are more than one.

Icon does not differ in two situations and does nothing on hover.
The only way to distinguish what will happen is to notice how the browser shows the link destination at the bottom of the screen (may differ in different browsers) and in tooltip (appears with a delay).

This requires extra effort to see what is there and can lead to surprising behavior. Not good for UX.
And there is no way to tell what will happen on mobile, afaik.

Various changes that can be made:

- show clickable URLs list in expanded view, along with tags, description, etc.;
- make the 🔗 icon interact on hover;
- make the 🔗 icon behave the same way regardless of the number of URLs - show the menu even with one link.

Ways to see the link even if it is the single one will be handy when accessed from mobile.

**Comment by Gykes** [comment]
So, I'm not quite sure what you mean by this to be honest... maybe I just haven't gotten enough sleep. 

`make the 🔗 icon behave the same way regardless of the number of URLs - show the menu even with one link.`: I agree with this one, I can talk to WP and see what he thinks.

`make the 🔗 icon interact on hover;`: I'm not sure what you mean with this honestly. I think anything that brings up a dropbox of any kind should be a click, not a hover.

`show clickable URLs list in expanded view, along with tags, description, etc.;`: define expanded view? If you add a URL to a performer it doesn't have a description section to add to the dropdown box the URL would have to be descriptive enough unless we add a new field for it.

Once again, sorry for the dumb questions but I want to make sure I understand before I start any code and can present it to WP in a way that makes sense to everyone. Personally I think adding in the dropdown box regardless of how many URLs would solve the main problem, which I assume, is you don't know how many links you have until you click and by then it's possibly too late. That could be solved pretty easily with some minor changes.

**Comment by xx790** [comment]
`make the 🔗 icon interact on hover`

When the button will always show the menu on click, the click itself becomes unnecessary friction.
If there is no other way to see the links, I'd prefer to have as little friction as possible.

Obviously, this will have to be working on mobile still, where there is no pointer. This is a common problem and is solvable by showing the menu when either of two conditions met: there is hover within the element or focus within the element.

<br/>

`show clickable URLs list in expanded view, along with tags, description, etc."`
Here is a mockup:

![image](https://github.com/user-attachments/assets/5b304d6b-0388-4223-95e0-8bfd017de806)

**Comment by Gykes** [comment]
So, I agree with your mindset on the links situation but if someone has 50 links in there then it is going to get messy very quicky. Having a dropdown should be mandatory if links > X, which is how it is now but it should probably be displayed better. I still disagree with hover tho. Perhaps adding an arrow next to the image if there is going to be a dropdown from the click and no arrow if there will be no dropdown. This could potentially still be confusing to new user and maybe just making the box mandatory would be better.

 The mockup has the same potential issue, in my opinion anyway, that I described above. If a user has 10,20, blah blah links then the page will become just a list of URls and be ugly.

**Comment by xx790** [comment]
> going to get messy very quicky

I (user) have certain priorities:

1. things that are significant for me (example here - things that I input myself. Respect user data);
2. things that take up space and have no use for me - are nuisances (example - most of the fields on the performer edit page);
3. things that look polished.

Later entry in this list should not be considered as a priority over earlier.
There is the principle "Form follows function".
If a feature serves a function for me, you can't "prettify" it by complicating/obstructing the access to that feature.

Previous behavior: I had all links in the description.
Is the long description considered messy? Wasn't the expand/collapse toggle put there exactly to address the situation when there are too many details? I see neither other measures to deal with long description, nor the need for such measures.
If I have too long description or too many links - I can collapse them already to get to the scenes and other content.

The way I personally fill information - I don't have much use for the description text, same as most other fields. So, after I move the links, I will have empty descriptions most of the time. The list of links itself tells me something I care about.

Alternative to having the links section in the expanded details view would be allowing Markdown in the description or any other way to linkify the description.
That way I wouldn't care about multiple URL fields support and have something that actually displays the information the way I care about it.
(Now sure if there is an issue for that specifically. #5083 was closed as a duplicate of #1868, which was always about URL field(s).)

50 links seems a bit of an exaggeration. The most I have is 24 links, the closest second is 8 links, others are less than 6, mostly 2-3.
At the numbers above 20, hiding the links is not what would help to handle them. It would rather need a way to group them in some way. For that, linkified description would be more helpful without requiring extra complexity.
