### ISSUE TITLE
[Request] Ability to search & filter via performer details

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#53]
Add the ability to search and filter through performer details such as alias, ethnicity, eye color, country, etc.

**Comment by yoshnopa** [comment]
Also, it may be interesting to add custom values to this search function, like 'small', 'big/medium/small x' and so on. 
Those values could then be automatically added to videos they perform in.

**Comment by echo6ix** [comment]
> Also, it may be interesting to add custom values to this search function, like 'small', 'big/medium/small x' and so on.
> Those values could then be automatically added to videos they perform in.

If I understand you correctly, do you mean having global custom fields for performers?

So the PERFORMERS table in database would have like 3 to 5 extra columns, CUSTOMFIELD1, CUSTOMFIELD2, CUSTOMFIELD3, which is then accessible via searching. Since they're custom fields the user would have the ability to define (rename) them somewhere in the settings page:

Eg.

```
Custom Performer Fields
----------------------------
User defined custom fields for performers.

[ x ]  CUSTOMFIELD1: Gender
[   ]  CUSTOMFIELD2: _______________________________
[   ]  CUSTOMFIELD3: _______________________________
_
```

**Comment by yoshnopa** [comment]
This would be a possible implementation of what I was saying, yes, but I think it would be easier for exporting/importing as well as the database management to just provide one extra database value allowing comma seperated tags (or a list of some sort) in some way... The UI may present that the way you proposed, I think that would be the way to go with minimal interference of the rest of the system.

As for the automatic adding, a scene with an asian (as given in ethnicity) performer would automatically be tagged 'asian', but also get the tags from the custom row, like blonde/brunette, small etc.
