### ISSUE TITLE
[Info] incomplete entry on alternativeto.net site

### ISSUE THREAD

**Issue by GETandSELECT** [stashapp/stash#530]
Hi

thank you for this app

On alternativeto.net (good ranking in search engines) there is an entry about stash, but very incomplete and well hidden.

https://alternativeto.net/software/stash-1/

Feel free to complete the article. But generally you can find this super app very badly with a search engine, we have to advertise.

**Comment by DogmaDragon** [comment]
Could be closed. It was updated with the relevant information. 
<https://alternativeto.net/software/stash-1/about/>
