### ISSUE TITLE
[Bug Report] Stash 0.27.0 won't start on Windows...

### ISSUE THREAD

**Issue by Stephan972** [stashapp/stash#5301]
**Describe the bug**
When lauchnig stash under windows 7, a error message is shown and stash refuses to start.

**To Reproduce**
1. Launch stash-win.exe from command line, by double clicking on it or via link
2. See error message on screen

**Expected behavior**
A successfull start and browing my collection as usual.

**Screenshots**
If applicable, add screenshots to help explain your problem please ensure that your screenshots are SFW or at least appropriately censored.

**Stash Version: (from Settings -> About):**
0.27.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: N/A
 - Version: Windows 7

**Smartphone (please complete the following information):**
N/A

**Additional context**
0.26.0 starts smoothly.
Here is the complete error message :

<code>
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall(0x36f4a8)
        runtime/sys_windows_amd64.s:75 +0x7a fp=0x36f430 sp=0x36f410 pc=0x13fb3b81a
rax     0x0
rbx     0x142dddf18
rcx     0x142e68088
rdx     0x20
rdi     0x7fffffdd000
rsi     0x36f628
rbp     0x36f570
rsp     0x36f408
r8      0x0
r9      0x36f698
r10     0xfa2e8
r11     0xc000004000
r12     0x36f678
r13     0x0
r14     0x142ddcd80
r15     0x3
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

**Comment by feederbox826** [comment]
https://github.com/stashapp/stash/pull/4822#issuecomment-2163957150

side effect of updating golang https://tip.golang.org/doc/go1.21#windows
