### ISSUE TITLE
[Feature] List Image Dimensions on Scraper Results

### ISSUE THREAD

**Issue by aeterno57** [stashapp/stash#5307]
**Is your feature request related to a problem? Please describe.**
It's more a minor quality of life improvement; when scraping and presented with two versions of the same cover image, it'd be useful to compare their dimensions at a glance rather than either blindly accepting one or the other, or right-clicking and opening both in a new tab to compare. 

**Describe the solution you'd like**
Output the ```naturalWidth``` and ```naturalHeight``` of images in the scrape results modal and tagger views (possibly performer scrape results as well for consistency) underneath the image, allowing users to make an informed choice about which to keep when presented with two versions of the same image.

**Describe alternatives you've considered**
N/A; there's need for anything fancy here.

**Additional context**
N/A.

**Comment by StashManRon** [comment]
There's a plugin 'stashdb-fullimg' available from https://github.com/feederbox826/plugins which should cover this

**Comment by feederbox826** [comment]
That plugin fetches the full resolution images from stashDB. If you want resolution, `tagger-image-res` from the same repo does what you want
