### ISSUE TITLE
[RFC] Nginx Reverse Proxy Configuration

### ISSUE THREAD

**Issue by halorrr** [stashapp/stash#532]
### Scope
Looking for advice on the recommended nginx config to resolve an odd error I noticed in my stash logs.

##  Long Form
I've been running stash using docker on my unraid server and love it. I have it behind a reverse proxy using letencrypt. The app works perfectly but I noticed in the logs, whenever I'm connected via the reverse proxy a 422 error is being spammed at /graphql. I'm wondering if anyone has any recommendations on how I can look at resolving this in my configuration, and what effects this error might actually have?

## Examples
![download](https://user-images.githubusercontent.com/1358708/81520099-4768d080-9311-11ea-8f2b-5322cb5c1ff5.jpg)

My current proxy config:
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name stash.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /login;

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app stash;
        set $upstream_port 9999;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
}
```

**Comment by bnkai** [comment]
Have you setup all the headers needed as mentioned in https://github.com/stashapp/stash/pull/134  or in the [wiki](https://github.com/stashapp/stash/wiki/Reverse-proxy) ?

**Comment by halorrr** [comment]
Yes, sorry I should have included the main proxy conf for all services as well:

```
## Version 2018/05/31 - Changelog: https://github.com/linuxserver/docker-letsencrypt/commits/master/root/defaults/proxy.conf

client_max_body_size 10m;
client_body_buffer_size 128k;

#Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

# Advanced Proxy Config
send_timeout 5m;
proxy_read_timeout 300;
proxy_send_timeout 300;
proxy_connect_timeout 300;

# Basic Proxy Config
proxy_set_header Host $host:$server_port;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
#proxy_cookie_path / "/; HTTPOnly; Secure"; # enable at your own risk, may break certain apps
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 32 4k;
```


So looking at the wiki:
` proxy_pass http://127.0.0.1:9999;` < this is set via `proxy_pass $upstream_proto://$upstream_app:$upstream_port;` in my stash conf (this works out essentially to `http://stash.mydomain.com:9999`)

`proxy_set_header Host $host;` < I have this slightly different in the main conf with `proxy_set_header Host $host:$server_port;` I tested and dropping the `:$server_port` doesn't correct the issue

`proxy_set_header X-Real-IP $remote_addr;` < this is set in the main conf
proxy_set_header X-Forwarded-For $remote_addr; < mine is slightly different in the main conf with `$proxy_add_x_forwarded_for` but i tried switching it to `$remote_addr` and it did not resolve the issue.

`proxy_set_header X-Forwarded-Port $server_port;` < This wasn't anywhere for me (from what I can tell) but adding it in did not resolve the issue.

`proxy_set_header X-Forwarded-Proto $scheme;` in the main conf mine is explicitly set to https, but switching it to `$scheme` didn't resolve the issue either.


So far I've only found one thing that is actually effected by this error, when I access stash through my reverse proxy the loading bar for tasks doesn't update without a page refresh. (Guessing what is being blocked in that 422 error is looking for page updates)

**Comment by halorrr** [comment]
Also noticed the main conf was pretty old so I deleted it and had the app generate a new one, which also did not resolve the issue. Here is the updated main one though:
```
## Version 2019/10/23 - Changelog: https://github.com/linuxserver/docker-letsencrypt/commits/master/root/defaults/proxy.conf

client_body_buffer_size 128k;

#Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

# Advanced Proxy Config
send_timeout 5m;
proxy_read_timeout 240;
proxy_send_timeout 240;
proxy_connect_timeout 240;

# TLS 1.3 early data
proxy_set_header Early-Data $ssl_early_data;

# Basic Proxy Config
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
#proxy_cookie_path / "/; HTTPOnly; Secure"; # enable at your own risk, may break certain apps
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 32 4k;
proxy_headers_hash_bucket_size 128;
proxy_headers_hash_max_size 1024;
```

**Comment by WithoutPants** [comment]
That would be the websocket connection, which affects the loading bar as you've noticed, and the logging subscription (logging won't update on the Log page until reloaded).

**Comment by halorrr** [comment]
Hmmm any idea what special options I might need to add to get the websocket connection to work?

**Comment by all-hail-canada** [comment]
> 
> 
> Hmmm any idea what special options I might need to add to get the websocket connection to work?

You need to have:

`proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";`

**Comment by halorrr** [comment]
That was the trick! I experimented with turning the different lines on and off to see what effected it. The map block outside the server block wasn't needed. 

This:
`proxy_http_version 1.1;` is already in the default config for the letencrypt 

In the default proxy config there was this line:
`#proxy_set_header Connection "";` Changing it to `proxy_set_header Connection "upgrade";` and adding `proxy_set_header Upgrade $http_upgrade;` to the file fixed the error.

**Comment by halorrr** [comment]
I've updated the wiki with this information.
