### ISSUE TITLE
[Bug Reappearance] Extra click necessary when using tagger (Issue #4734)

### ISSUE THREAD

**Issue by DedTV** [stashapp/stash#5333]
The bug reported in Issue [#4734](https://github.com/stashapp/stash/issues/4734) and previously fixed in [#4770](https://github.com/stashapp/stash/pull/4770) has returned in v0.27.

**Comment by DogmaDragon** [comment]
Can't reproduce on https://github.com/stashapp/stash/commit/c45ae068fc5cd9bd355e92363bc3b89289b7d35f (latest release).

**Comment by WithoutPants** [comment]
Also not able to reproduce. Please provide steps to reproduce.

**Comment by DedTV** [comment]
No longer occurs as of build gf82e2476. The top result expands as expected.
