### ISSUE TITLE
[Bug Report] Unknown criterion parameter name: movies

### ISSUE THREAD

**Issue by MoonlitTriss** [stashapp/stash#5339]
**Describe the bug**
Sorry if this is a stupid question but i dont get how i can fix it.
When i connect to the stash server, the Frontpage gives me the following error.
`Something went wrong.`
`Error: Unknown criterion parameter name: movies`
I get where the error comes from since before the Update i had the movies shown on the Frontpage but i dont get how i can remove it since the Frontpage doesnt load up.

**Expected behavior**
Frontpage is being shown.

**Screenshots**
![Screenshot 2024-10-03 201603](https://github.com/user-attachments/assets/7e65d3e8-0e78-4f4d-be8e-1f4585fbce42)

**Stash Version: (from Settings -> About):**
v0.27.0

**Comment by DogmaDragon** [comment]
Your frontpage filters are stored in the `config.yml` file. If you open it, you can search for:

```yaml
frontPageContent:
```

and then remove the movie related filter.

**Comment by MoonlitTriss** [comment]
Alright that worked. Thanks for the quick help

**Comment by WithoutPants** [comment]
Reopened as this is an unresolved bug.
