### ISSUE TITLE
[Bug Report] STASH_CONFIG_FILE is ignored on setup

### ISSUE THREAD

**Issue by feederbox826** [stashapp/stash#5344]
**Describe the bug**
When the configuration file path is specified but invalid, it is ignored and created at `$HOME/.stash/config.yml` since the configuration file does not exist and will always be invalid and is not used, hence the path ignored

**To Reproduce**
1. Set the environment variable `STASH_CONFIG_FILE`
2. Set the environment variable `HOME`
3. Start stash setup wizard
4. Instead of creating at `STASH_CONFIG_FILE`, config file is created at `$HOME/.stash/config.yml`

**Expected behavior**
Since a STASH_CONFIG_FILE override is provided, follow it for ConfigLocation

**Screenshots**
https://github.com/stashapp/stash/blob/3e4515e62abd90c66de5466828553dabeb1f6e90/internal/manager/manager.go#L189-L191

**Stash Version: (from Settings -> About):**
v0.27.0-14-g3e4515e6 (3e4515e6)

**Additional context**
Not sure if it is intentional as a failsafe but short of overwriting HOME and symlinking .stash, it appears on the wrong path

**Comment by WithoutPants** [comment]
I am unable to reproduce this on the develop branch:

```
:~/dev/stash/instances/fresh$ STASH_CONFIG_FILE=config.foo.yml stash
WARN[2024-10-07 10:22:45] config file config.foo.yml not found. Assuming new system... 
```

![Image](https://github.com/user-attachments/assets/6c7fd754-7b90-4d83-bc85-7a31ae63fb1c)

**Comment by feederbox826** [comment]
Couldn't repro with the docker container I was trying to debug
