### ISSUE TITLE
Disable Scene Details from the wall view

### ISSUE THREAD

**Issue by nathanstreetx** [stashapp/stash#5346]
New to using this app, so not sure if this has already been created, but I couldn't find it in settings. I would like the option not show the scene description on the scene wall and performer wall (See screenshots). If this could just be a toggle in the settings that switched off the details display across scenes and movies that would be great

How it currently looks
![1](https://github.com/user-attachments/assets/ba0ee2e0-c21d-47d5-8f4e-54d78bdcf774)

How I would like it to look
![2](https://github.com/user-attachments/assets/7396d4cb-32c5-4b1d-aa13-57e16bc2d88f)

FYI - I know I can achieve this by removing the details from the scenes themselves, but I don't want to do that, I still want the detail description when I open the scenes, just not on the wall.

**Comment by bob123491234** [comment]
This can be accomplished by adding `.scene-card__description { display: none }` to the custom CSS (Settings > Interface > Custom CSS). Be sure to enable custom CSS and refresh the page after applying it.

**Comment by cj12312021** [comment]
Stash enables custom CSS to allow users to tweak issues like this in their own Stash instance. The CSS provided by @bob123491234 should make the requested change. For further help with CSS, you can reach out in the Discord [#theming](https://discordapp.com/channels/559159668438728723/1196910630460985544) channel.

**Comment by nathanstreetx** [comment]
Thanks @bob123491234 , that worked perfectly. Is there a way to get the same setting for Movies (Groups)?

**Comment by bob123491234** [comment]
@nathanstreetx Yes, just add a line with `.group-card__description { display: none }`. It can be done for galleries and images as well with `.gallery-card__description { display: none }` and `.image-card__description { display: none }`.

**Comment by nathanstreetx** [comment]
Thanks @bob123491234
