### ISSUE TITLE
[Bug Report] In Multi-select mode, clicking thumbnail adds item twice

### ISSUE THREAD

**Issue by mrrogg** [stashapp/stash#5365]
**Describe the bug**
When selecting multiple items (performers, scenes, etc), clicking on the portrait for subsequent items selects that item twice.  This is indicated when attempting to delete the selection, where you notice those items are listed twice.  Alternatively, clicking on the checkbox precisely does not add duplicate.

**To Reproduce**
1. Go to 'Performers'
2. Click on the top left checkbox
3. Click another performer by clicking the portrait thumbnail
4. Click another performer by clicking the checkbox directly
5. Click the delete icon
6. Notice that the ones clicked via thumbnail are in the list twice

I confirmed this happens with the following lists (the only ones I have with data): Scenes, Galleries, Images, Performers, Studios, Tags

**Expected behavior**
I expect the selection behavior to only add the item once

**Screenshots**
<img width="361" alt="Screenshot 2024-10-11 at 11 00 43 AM" src="https://github.com/user-attachments/assets/e43cc4c6-44b2-4f98-8377-ea60d47d333c">

**Stash Version: (from Settings -> About):**
v0.27.1
Build hash: ad00bee3

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS Sequoia 15.0.1
 - Browser [e.g. chrome, safari]: Firefox
 - Version [e.g. 22]: Firefox 131

**Comment by feederbox826** [comment]
This was reported and apparently fixed in 27.1, run an optimize database task to clean up any debis in your DB, update and see if it is fixed

**Comment by mrrogg** [comment]
I ran an Optimize Database task, attempted to update (running via docker), docker down, docker pull, docker up, and the issue persists for me.
