### ISSUE TITLE
[Bug Report] Freeones Scraper Broken

### ISSUE THREAD

**Issue by halorrr** [stashapp/stash#537]
**Describe the bug**
It look like Freeones made some big updates to their site and broke the freeones scraper. Attempting to scrape any performer right now is throwing this error: `Error: GraphQL error: No matches found in`

**To Reproduce**
1. Go to 'Performers
2. Click on New
3. Click on Scrape With... and choose Freeones
3. Type a Performer name and selected the suggested match
4. Click Scrape

**Expected behavior**
Expected behaviour would be for the performers information to be scraped.

**Screenshots**
![download-1](https://user-images.githubusercontent.com/1358708/81733257-b94f3000-945f-11ea-880f-035940c49fd6.jpg)

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - Browser Google Chrome
 - Version Version 81.0.4044.138

**Additional context**
With this update the performer URLs have changed as well, currently it looks like the old redirects to the new, but it would be nice if we got a task to bulk update the old URLs to get the new ones (maybe following the current redirect).
 
For example using Abella Danger the old URL is:
https://www.freeones.com/html/a_links/bio_Abella_Danger.php
And the new url is:
https://www.freeones.com/abella-danger/profile

**Comment by bnkai** [comment]
Was also mentioned in discord, for now switching to the NewFreeones xpath scraper is recommended.
