### ISSUE TITLE
Performers Page - Navigation

### ISSUE THREAD

**Issue by nathanstreetx** [stashapp/stash#5370]
The ability to navigate the performers page by letter rather than page number. This could be a toggle you could switch on in settings to change from numbered pages to letters. The pages would be split via letter and each performer would be organised by the first letter of their name.

**Comment by feederbox826** [comment]
available as a userscript https://github.com/elkorol/Stash-App-Script-Alphabet-Selector

**Comment by nathanstreetx** [comment]
@feederbox826 thanks for the response, unfortunately I was unable to get this to work. I'm not very good with scripting, so it is probably on my end. I may just have to wait until they, hopefully, make this a feature. I would figure being able to split the performers page by letter would be a useful feature ¯\_(ツ)_/¯

**Comment by nathanstreetx** [comment]
Finally figured this one out. The script needed to be modified, replacing the URL for the '@require' with https://raw.githubusercontent.com/7dJx1qP/stash-userscripts/master/src\StashUserscriptLibrary.js
