### ISSUE TITLE
[Feature] Auto Tag From Details

### ISSUE THREAD

**Issue by meanjoep92** [stashapp/stash#5387]
Hey folks, sorry if this has been done before but is there a way to have Auto Tagging based on details of a scene or image? I know it tags based off file path, but just wanted to see if there was another way. Thanks.

**Comment by DogmaDragon** [comment]
Sorry, misread the issue initially.

**Comment by DogmaDragon** [comment]
Duplicate of https://github.com/stashapp/stash/issues/5387
