### ISSUE TITLE
[Feature] Preserve Sorting Criterion for Scenes etc

### ISSUE THREAD

**Issue by NormanPriv** [stashapp/stash#5392]
**Is your feature request related to a problem? Please describe.**
Every time the page for Scenes / Performers is opened, the sorting criterion goes back to the first one. So, for Scenes, it is always sorted by Date when opened.

**Describe the solution you'd like**
Remember the last choice of sorting criterion and descending/ascending order.

**Describe alternatives you've considered**
If it's not set as preserving the last setting, it would be good to at least have the option to set a user-defined default choice.

**Additional context**
I frequently need to change the sorting criterion from "date" to something else.

**Comment by DogmaDragon** [comment]
You already can set a new default filter. All the options in the toolbar are part of the filters and can be saved, including sorting. 
![image](https://github.com/user-attachments/assets/3828bf86-b6de-4e65-ad18-105ba1d727f5)
