### ISSUE TITLE
[Bug Report] After v0.27.2 upgrade, stashapi fails

### ISSUE THREAD

**Issue by David-Maisonave** [stashapp/stash#5413]
**Describe the bug**
After upgrading Stash to version v0.27.2, all my python plugin's task fail with the following error:
```
Error   [Plugin / DupFileManager] ModuleNotFoundError: No module named 'stashapi'
Error   [Plugin / DupFileManager]     from stashapi.stashapp import StashInterface
```

If I run a python script by itself which refers stashapi.stashapp, it works with no errors.

**To Reproduce**
1. Include the following line on the top of any plugin which has a task.
`from stashapi.stashapp import StashInterface`
2. Run the plugin task.
3. Review the logs [http://localhost:9999/settings?tab=logs](http://localhost:9999/settings?tab=logs)

**Expected behavior**
Should not produce error when referring to stashapi.
This was working before the upgrade.

**Stash Version: (from Settings -> About):**
**v0.27.2**
Build hash:
76648fee
Build time:
2024-10-15 22:17:23

I've also tried upgrading to the latest stashapp-tools.
pip show stashapp-tools
Name: stashapp-tools
Version: **0.2.55**

But got the same results.

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [chrome and firefox]
 - Version [0.27.2]

**Comment by Maista6969** [comment]
You have multiple Python installations on your machine and Stash is using the wrong one: you'll need to figure out which is the correct Python and either uninstall the wrong one or set the Python path explicitly in `Settings > System > Application paths`

**Comment by David-Maisonave** [comment]
> You have multiple Python installations on your machine and Stash is using the wrong one:

Thanks!
You're right. I do have multiple Python installations. I ran the following Powershell command, and it does show multiple Python installations.
`Get-ChildItem -Path C:\ -Filter site.py -Recurse -ErrorAction SilentlyContinue -Force`

However, I would like to know why this issue was triggered after the v0.27.2 upgrade.  I never had this issue before the upgrade.
Moreover, when I do a **'where python'** DOS command it list the following path:
`C:\Users\MyUserName\AppData\Local\Microsoft\WindowsApps\python.exe`

I then changed my plugin script to only include the following code, which forces the 'where python' results to go to the stash logging, because of **file=sys.stderr** :
```
import os, sys
print(os.popen("where python").read(), file=sys.stderr)
```

Running a task with the above script produced the following logging:
```
[Plugin / DupFileManager] C:\Users\admin3\AppData\Local\Microsoft\WindowsApps\python.exe
[Plugin / DupFileManager] C:\Users\david\AppData\Local\Programs\Python\Python310\python.exe
```

I've never seen the **where** command produce two different binaries.

I'm pretty sure that you're correct in stating that setting **Settings->System->[Application Paths]->[Python Executable Path]** would address the problem, but I would like to know what is triggering this issue, and I want to make sure I'm not just covering up a potential bigger issue.

**Comment by Maista6969** [comment]
Are you perhaps launching the Stash executable as administrator to avoid the lingering command prompt window? That would affect the path resolution, I believe... the only other thing I can think of is that this release is built on Go version 1.22 which [did include some changes to os and os/exec](https://tip.golang.org/doc/go1.22#minor_library_changes)

**Comment by David-Maisonave** [comment]
> Are you perhaps launching the Stash executable as administrator to avoid the lingering command prompt window?

I'm starting stash using Task Scheduler, and it's being started with user account "admin3", which is the python binary path I get on the DOS prompt, and it's the first path listed when running the plugin task.
The below link indicates that the first path listed by the where clause is the path which should be used.
[https://stackoverflow.com/questions/72307674/which-executable-is-run-by-dos-cmd-if-multiple-results-are-returned-by-where](https://stackoverflow.com/questions/72307674/which-executable-is-run-by-dos-cmd-if-multiple-results-are-returned-by-where)

I just rebooted the machine, it the issue seems to have disappeared. (I forgot one of the main debugging 101 rules!!!)

Thanks for your help [Maista6969](https://github.com/Maista6969).
