### ISSUE TITLE
[Feature] Web App password autofill on iOS. 

### ISSUE THREAD

**Issue by crazyp** [stashapp/stash#5421]
Using the web app on iOS is a great idea to not have to build a native app and so far it seem to work pretty good. However when trying to sign in with passwords enabled is kind of a pain since the built in passwords saving in iOS won’t prompt for a saved password  or allow you to manually select one by long pressing the dialog box and selecting autofill and then password. When visiting the server using safari normally you can long pressing the dialog box and selecting autofill autofill

**Comment by DogmaDragon** [comment]
That's Apple issue. Their PWA support is mixed at best.

From a quick search, deleting and re-creating PWA shortcut can make it sometimes work, but not always. See https://old.reddit.com/r/ipad/comments/1ajio4k/password_autofill_not_working_on_pwa/

**Comment by crazyp** [comment]
Thanks for the info. I thought it might be an apple thing. Maybe some kind of passcode system so it’s easier to login
