### ISSUE TITLE
[Feature] Make Tag Scraping Case-Insensitive

### ISSUE THREAD

**Issue by halorrr** [stashapp/stash#543]
**Is your feature request related to a problem? Please describe.**
I'm working on building some community scrapers, and while doing so stumbled upon the fact that when we scrape tags, they will not be matched unless the case matches. So if my tags list contains `Brunette`, but the scene tags I scrape are listed as `brunette`, no match is made.

**Describe the solution you'd like**
I'm like the tag scrapping matches to be case insensitive. I can't think of any positives to having them be case sensitive.

**Describe alternatives you've considered**
There is always manual entry, but that defeats the purpose of scraping.

**Additional context**
N/A

**Comment by bnkai** [comment]
During scraping i think apart from tags, performer and studio search should also be case insensitive.
