### ISSUE TITLE
Rename 'Fake Tits' field to just 'Tits'

### ISSUE THREAD

**Issue by nathanstreetx** [stashapp/stash#5435]
Can we rename the performer field of 'Fake Tits' to just 'Tits', it doesn't make sense to have fake in the title if the performers breasts are natural, and if they are fake, then having it in the title is redundant (See below).

![image](https://github.com/user-attachments/assets/8be1e300-0286-4db0-abc5-90e3a7119d9a)

**Comment by ariv-x** [comment]
That makes values like "yes" or "no" kind of comical.

Actually, why not just make it a boolean?

**Comment by Valkyr-JS** [comment]
You can do this already using custom localisation settings.

Settings > Interface > Custom localisation. Enable it, then click Edit and paste this in; `{ "fake_tits": "Tits" }`

You'll probably need to refresh the page before you see any change. If youy want to change anything else, you can see the full list at https://github.com/stashapp/stash/blob/develop/ui/v2.5/src/locales/en-GB.json

**Comment by nathanstreetx** [comment]
@Valkyr-JS thanks for this! This is actually gonna help me with a few things I've been wanting to update :)

**Comment by LeGrosFromage** [comment]
Personally I think "Natural Breasts" "Yes/No" would be the best way, or "Breast Enhancements" "Yes/No".

I like to keep it somewhat classy - "tits" is a bit tacky to use in a UI and for the men, it says "Penis", not "dick" or "cock".

**Comment by randemgame** [comment]
> I like to keep it somewhat classy - "tits" is a bit tacky to use in a UI and for the men, it says "Penis", not "dick" or "cock".

or "dong"
