### ISSUE TITLE
[Feature] Exclude Tags

### ISSUE THREAD

**Issue by Houseoftaurus** [stashapp/stash#5439]
**Is your feature request related to a problem? Please describe.**
many of the filter elements have an exclude feature, however when attempting to filter by tag I noticed that there is no exclude feature associated with this task

**Describe the solution you'd like**
I believe it would be beneficial not just to myself but to many users to have an exclude option added to the tag filter so that we can exclude videos that may have a one or more particular tags

**Describe alternatives you've considered**
the only alternatives are the null options which don't work well considering it's a  no data option

**Comment by stg-annon** [comment]
see #4537
