### ISSUE TITLE
[Bug Report] Error querying performers: database or disk is full

### ISSUE THREAD

**Issue by navyseai** [stashapp/stash#544]
**Describe the bug**
Since about 4 commits ago i start getting this message 
Error querying performers: database or disk is full
and now it seems auto tag is no longer working for performers

**To Reproduce**
1. Go to Settings
2. Click on Tasks
3. Select Performers on auto tag
4. Click auto tag

**Expected behavior**
Should be able to tag performers on videos

**Screenshots**
[Screenshot](https://ibb.co/1ZDMNrx)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version v0.1.1-148-gd74a303

**Comment by bnkai** [comment]
Aside from the obvious check for free disk/temp space [this](https://stackoverflow.com/questions/5274202/sqlite3-database-or-disk-is-full-the-database-disk-image-is-malformed) seems to imply that either some hardware error may exist ( disk ) or something happened while the db was active. You can try  the steps mentioned there ( make a dump / copy / clone  using the sqlite binary and use the new db  ).

**Comment by navyseai** [comment]
Suddenly the issue seems to have vanish. I suspect the error message might be misinducing. Maybe the file was locked or something. what i can tell is that i had free space and i could add tags manually.
