### ISSUE TITLE
[Bug Report] Popups for bulk edit are drawn behind the curtain

### ISSUE THREAD

**Issue by Padawan00123** [stashapp/stash#5467]
**Describe the bug**
When attempting to bulk-edit images, the dropdown is rendered behind the dialog box and curtain, making it impossible to click-to-select values.  

**To Reproduce**
1. Go to a page that allows bulk editing (Images, Scenes, etc...)
2. Click "..." and choose "Select All"
3. Choose the pencil for edit.
4. Choose the dropdown at the right of a field. In my example, I used tags.  You will note my tags ("Athleticwear" and "Bikini") are at the bottom of the window - you cannot interact with them at all.

**Expected behavior**
I expect to be able to click and select a tag in the dropdown.   

**Screenshots**
<img width="520" alt="SCR-20241109-jufq" src="https://github.com/user-attachments/assets/617f2df1-5cb4-4486-a26e-7e84d3d646f5">

**Stash Version: (from Settings -> About):** 

**Desktop (please complete the following information):**
I have tested this on MacOS: 
* Firefox 134.0a1 (2024-11-08) (64-bit) "Nightly"
* Chrome 130.0.6723.117 (Official Build) (x86_64)
* Safari Version 18.1 (20619.2.8.11.9)

**Comment by xeezuleef** [comment]
@Padawan00123 do you have any themes enabled?

I had the same problem, but disabling the Plex theme fixed it.

**Comment by Padawan00123** [comment]
@xeezuleef Yes, I had the Plex theme enabled.  Removing it fixed the issue.
