### ISSUE TITLE
[Feature] Add an option to the scan task to only look for new files in the directory specified, but not sub-directories.

### ISSUE THREAD

**Issue by rawbeastly** [stashapp/stash#5501]
**Is your feature request related to a problem? Please describe.**
My problem is trying to do quick scans for new content and wanting scans to complete faster.

**Describe the solution you'd like**
Add an option to the scan task to only look for new files in the directory specified, but not sub-directories.

**Comment by DogmaDragon** [comment]
You can use selective scan to specify directory. https://docs.stashapp.cc/getting-started/first-steps/#initiating-scan
