### ISSUE TITLE
[Bug Report] Scene filter has two "groups" options

### ISSUE THREAD

**Issue by peppercucumber** [stashapp/stash#5504]
**Describe the bug**
There is duplicate "Groups" option in Scene filter. Top one functions normally, but if you click on bottom one it doesn't open, instead top one opens.

**To Reproduce**
1. Go to 'Scenes'
2. Click on 'filter'
3. There are two 'Groups' options

**Expected behavior**
There should only be one 'Group' option

**Screenshots**
![Scenes_Stash](https://github.com/user-attachments/assets/5f683d9f-db83-4b7f-9304-0981b1e3b2bf)

**Stash Version: (from Settings -> About):**
v0.27.2

**Comment by DogmaDragon** [comment]
Reproduced on https://github.com/stashapp/stash/commit/76648fee66bce1356dbce2de5871205f68f6f3f0.
