### ISSUE TITLE
[Feature] Allow Scraper To Overwrite Data

### ISSUE THREAD

**Issue by halorrr** [stashapp/stash#551]
**Is your feature request related to a problem? Please describe.**
Currently when using scene scrapers if there is already data in a field (like the title or description) it is not overwritten with scraped data.

This means, ever if the existing title and description is just the mess pulled from the file like `Lubed.18.04.14.Kimmy.Granger.Every.Last.Drop.XXX.1080p.MP4-KTR` for example, it does not get updated.

**Describe the solution you'd like**
I'd like the scraper to overwrite the existing data. If we are worried about some people preferring the opposite, maybe this will need a config toggle. Personally I'd always want it to overwrite as long as the scraper didn't return a blank result.

**Describe alternatives you've considered**
Currently my work around is to manually delete the data from those fields before scraping the scene data, but this adds extra tedium to the process.

**Additional context**
N/A

**Comment by bnkai** [comment]
The current behavior is intended so that a user can control what he/she wants updated and whatnot. A clean all fields button should be enough to cover this case and more easily implementable.

**Comment by halorrr** [comment]
Hmmm, with a clean all fields button though, you might end up deleting fields that the scraper doesn't actually have data for. I would only want the scraper to overwrite if it found data directly from the source for that field.

Maybe If anything for scene scrapers have two buttons come up with a recognized URL is put in. One to scrape without overwriting, and one to scrape and overwrite. That way we could take both preferences into account and keep avoid increasing the amount of clicks.
