### ISSUE TITLE
[Feature] Individual file re-scan button/option in scene page at file info tab

### ISSUE THREAD

**Issue by RokkGL** [stashapp/stash#553]
**Is your feature request related to a problem? Please describe.**
When you want to update/overwrite already added and tagged video with a higher quality video file, it isn't as straightforward as it could be. After you overwrite old video file with new, the file info remains the same. Scan skips updated file.

**Describe the solution you'd like**
I suggest to add button/option for individual file re-scanning in scene page at file info tab, that file info(Checksum) would be updated with the new information after using said option.

**Comment by bnkai** [comment]
The more proper solution would be to add file as is (no renaming the old file), scan it as a new file ( might get better generated preview, screenshot, ... if the original quality is higher ) and then make a feature ( copy scraped data from existing scene) that copies the scraped metadata from the old file.
Then you could delete the old file and hit clean.

**Comment by WithoutPants** [comment]
Handling re-encodes of the same file should be considered as part of a larger redesign of the object-file relationship. In the short-term, adding a rescan button for individual scenes should be fairly simple and can be done as part of #886
