### ISSUE TITLE
[Bug Report] Short Form Subject (50 Chars or less)

### ISSUE THREAD

**Issue by sandnaps2000** [stashapp/stash#5568]
Describe the bug
When trying to batch select edit information on the scenes page, the drop down menu doesn't list the performers, tags, studios, etc. But when clicking on the tags button, a list appears to popup but behind the edit menu. 

To Reproduce

    Go Scenes Page
    Click on the Three dots
    Select All Scenes
    Click on Edit/Pencil Icon
    Click on one of the various drop down (Performers, Studios, Groups, etc) 
    
Expected behavior
List of studios, or performers etc should drop down.

Stash Version: (from Settings -> About):
v0.27.2

Desktop (please complete the following information):

    OS: Linux/Windows
    Browser Firefox/Edge/Chrome
    Version Latest of all

![image](https://github.com/user-attachments/assets/75536f9c-ad0a-4b3c-b59c-35f439a2d1b1)

**Comment by DogmaDragon** [comment]
Theme issue. See https://github.com/stashapp/stash/issues/5467
