### ISSUE TITLE
[Feature] Male performers

### ISSUE THREAD

**Issue by yoshnopa** [stashapp/stash#56]
There seems to be no useful way to add male performers of any kind. They shouldn't have things like 'Fake Tits', and stating sex would make it relatively easy to sort performers.

**Comment by StashAppDev** [comment]
The current performers is mostly based off of the fields found on Freeones.  I'd say this is more of a longer term goal, but something I want to address.

**Comment by Leopere** [comment]
Support for this wasn't intentionally missed but it was for the 0.1.0 version release however there's really no excusable reason why this would not be something that would be on the roadmap for 0.2.0 so I've added it.  We've been designing the metadata schema to accommodate for extensible meta tags so this should be reasonably trivial to expand towards.

**Comment by WithoutPants** [comment]
Implemented via #371. Closing as addressed.
