### ISSUE TITLE
[Bug Report] crash on startup when theres no internet

### ISSUE THREAD

**Issue by lantraj** [stashapp/stash#561]
**Describe the bug**
if you have no internet connection, the version check at startup crashes the application

**To Reproduce**
1. disconnect your internet connection (on the device that has stashapp installed)
2. run stashapp

**Expected behavior**
Stashapp should problably warn about the failed version check and then proced as usual

**Desktop:**
 - OS: Pop_os (Ubuntu derivative)
 - Browser: _didn't use_

**Comment by WithoutPants** [comment]
Which version are you running?

**Comment by lantraj** [comment]
Version:	v0.0.0-alpha_dev-5-gc99ba68
Build hash:	c99ba68
Build time:	2020-02-08 04:03:57

**Comment by bnkai** [comment]
I think the issue was fixed with this PR <https://github.com/stashapp/stash/pull/374> . Your dev version is really old (in terms of commits since that time) , you should probable get the latest.

**Comment by lantraj** [comment]
yep, issue not present on stable release v0.1.1, all good
