### ISSUE TITLE
[RFC] Page navigation on top

### ISSUE THREAD

**Issue by Cromseth** [stashapp/stash#568]
If you are navigation at "multi-pages" (when there are many items) the nav-controls (First-Previous-Next-Last) are just at the bottom of the page. I think that should be at the top too. Now you have to scroll to bottom if you want to change page, and till you are there you can't even know in what page you are. Its the same for scenes, performers,... all indexed items. Maybe adding that at top is possible?

Sorry for my english.

**Comment by bnkai** [comment]
I always wanted to mention this. It's woth is shown even more as you increase the scenes  / page.
