### ISSUE TITLE
[Feature] Extract Post-Processing Option

### ISSUE THREAD

**Issue by halorrr** [stashapp/stash#573]
**Is your feature request related to a problem? Please describe.**
Currently I'm trying to get performers extracted in a scraper for 21sextury. They are in a JS script. When I'm honing in on a single target like a URL it is easy to do with with regex, once I get what I need into capture groups I wrap either end with `.+` and call it a day. Pulling multiple targets out is way harder when you need to get rid of the non-matched text still and don't know how many capture groups there will be every time.

**Describe the solution you'd like**
I'd like to have an extract post-processing option that instead of working to replace data, pulls out all the capture groups.

Something that might look like:

```
selector: //script[contains(text(), '@type":"Person"')]/text()
extract: (?:Person","name":")([\w\s]+)
```

Ideal state is that an array of all the capture groups is extracted, so that for example in the case of performers, stash can then try to match all the extracted performers.

**Describe alternatives you've considered**
There are some possible work arounds that can be done with the current replace functions but they require multiple replaces and are prone to edge cases.

**Comment by halorrr** [comment]
Another post-processing method that would be useful would be a method to split a string.

Again coming back to the times in which data needs to be scraped from JS, even using the replace function multiple times over to clean the data into a more usable list example: `"Tag1","Tag2","Tag3","Tag4","Tag5"`, stash expects multiple strings, not a single string, and won't read all the tags contained in the string.

**Comment by WithoutPants** [comment]
Should now be possible using regex replace directives.
