### ISSUE TITLE
[Bug Report] Switching from portrait to landscape while fullscreen on mobile results in picture in picture mode

### ISSUE THREAD

**Issue by Wannabestraight** [stashapp/stash#575]
**Describe the bug**
When you switch from portrait to landscape while having fullscreen active on mobile, it switches to displaying the video in a picture in picture format rather then staying fullscreen.

You are then required to close the fullscreen (and on samsung internet browser close the entire video) and re-enter fullscreen (while in landscape mode) to properly enable it

**To Reproduce**
1. Go to a scene on mobile
2. Click on fullscreen while in portrait mode
3. rotate phone so it switches to landscape mode

**Expected behavior**
When switching from portrait to fullscreen the video should stay in fullscreen, there should be a separate button for picture in picture or it should be removed completely on mobile.

**Stash Version:**
v0.1.1-163-gccd7573

**Smartphone:**
 - Device: Samsung Galaxy S10+ and Samsung Galaxy note 9
 - OS: Android 10
 - Browser Chrome, Samsung internet
 - Version 81.0.4044.138 and 11.22.1.3

**Comment by WithoutPants** [comment]
Will need to test this against the #562 PR. Might be addressed there.
