### ISSUE TITLE
[Feature] Add gallery icon in scene list

### ISSUE THREAD

**Issue by Cromseth** [stashapp/stash#577]
Now we have an icon for "performers" and "tags". I think it would be interesting also add an icon if a "gallery" is attached. So it would be easily and obvious which scene has (or not) an attached gallery. It could just show (hover) the gallery name, the gallery images count or something like that (to keep the homogenic "hover" behavior with the other icons.

**Comment by WithoutPants** [comment]
This has now been implemented.
