### ISSUE TITLE
[Feature] Feature To Scrape Dynamic xPaths

### ISSUE THREAD

**Issue by halorrr** [stashapp/stash#578]
**Is your feature request related to a problem? Please describe.**
As I work down the list of remaining sites not yet supported by the community scrapers, I'm finding sites that are more and more challenging to scrape from due to content being loaded dynamically on the page load via scripts. 

It is one thing when the content is still in a script and can be extracted via regex, it is becoming a whole other issue though when the content isn't present at all in the source file.

Take Bang.com as an example with this [scene](https://www.bang.com/video/XjBOA1os6n2ZOGyz/tiny-teena-holds-her-tits-together-as-her-boyfriend-fucks-the-hole). Almost all the content on the page is loaded in via scripts. Some content like the title, description, scene image can luckily be scraped from the meta fields. However all other fields like Studio, Movie, Performers, Tags, and Date are not present in the source code.

On that example page you can see the Performer is `Eva Elfie` but if you search for `Eva Elfie` in the source code, the name isn't present even once. Making it impossible currently to scrape.

**Describe the solution you'd like**
I don't have enough understanding of the backend to know how to resolve this, but I'd like to be able to scrape the page from what it looks like after the page scripts have been loaded. Googling with my limited understanding I think Selenium is supposed to help with this?

**Describe alternatives you've considered**
Alternative would be to manually grab the data instead of scraping it.

**Comment by bnkai** [comment]
I don't know how easy will be  (and even if it's worth it to) add selenium support directly to stash.
 However you can always use the script feature instead of xpaths to run a python script that uses selenium to do the scraping. 
The wiki has a relative old example of a python script used for scraping. Adjusting that to use selenium should be possible.

**Comment by WithoutPants** [comment]
@bnkai is this resolved by #625 ?
