### ISSUE TITLE
[Feature] Show logo if studio has one, otherwise text

### ISSUE THREAD

**Issue by seducingbits** [stashapp/stash#583]
**Is your feature request related to a problem? Please describe.**
I got about 50% of the studios with a logo. So I want to deactivate the option "Scene List" > "Show Studios as text". But when I do that, scenes for the other half of the studios won't show any studio information at all.

**Describe the solution you'd like**
Remove the option. Show a logo when the studio has a logo, otherwise show text.

**Describe alternatives you've considered**
Convert the checkbox into a dropdown with the options:
* Logo if present, otherwise text [Default for new users?]
* Only show logo
* Show studio as text
* Don't show studio information

**Comment by echo6ix** [comment]
This is a solid suggestion imo.

**Comment by seducingbits** [comment]
Done with #965 :) Thanks!
