### ISSUE TITLE
[Feature] the current Raspberry build is only 32-bit, please provide a build for 64-bit images

### ISSUE THREAD

**Issue by GETandSELECT** [stashapp/stash#585]
The [Ubuntu image is 64-bit](https://ubuntu.com/download/raspberry-pi). Thank you very much.

```
$ file stash
stash: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, for GNU/Linux 3.2.0, Go BuildID=i1FSHpCNTZ_KpdKf6WzO/wPsfSQrcKjopjAi_8qDM/G2i86PG6zMzbxCddoyW4/vt3BX7ksv3NmGcp-ypN5, BuildID[sha1]=4379e8240db765dfb52d70cba2af4a0bf90b526c, not stripped
$ uname -a
Linux ubuntu 5.4.0-1011-raspi #11-Ubuntu SMP Fri May 8 07:43:33 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by bnkai** [comment]
We use cross  compiling to make the binaries so the ubuntu image is not needed anyway.
`GOOS=linux GOARCH=arm GOARM=5 CC=arm-linux-gnueabi-gcc` something like this is used for the raspi build. 
I guess ` GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc` could be used for a 64bit binary
Doesn't the 32bit run in your case ?

**Comment by GETandSELECT** [comment]
> The official Raspbian OS has not yet been updated for a 64-bit device. 32-bit software can run on a 64-bit system (but not vice versa). I use Ubuntu which is 64-bit.

Strange, but the 32-bit bin doesn't run on my system.

`arm64` is correct.

**Comment by bnkai** [comment]
@GETandSELECT i made a test build but have no way to try that
can you try https://easyupload.io/k1q1j3 ?
md5
`ea3c7d6dba468b6eb42cdc308c0dcf81  stash-arm64`

**Comment by GETandSELECT** [comment]
it's working fine. Thank you very much

**Comment by bobbynails** [comment]
> @GETandSELECT i made a test build but have no way to try that
> can you try https://easyupload.io/k1q1j3 ?
> md5
> `ea3c7d6dba468b6eb42cdc308c0dcf81 stash-arm64`

could you reupload this?

**Comment by bnkai** [comment]
Do you need latest dev or master ?
I'll compile a new build over the weekend.

**Comment by bnkai** [comment]
Latest dev static builds for arm. 
armv6 https://gofile.io/d/z0eMDZ
arm64 https://gofile.io/d/WaTSss
@GETandSELECT can you also try the specific armv6 build (32 bits) with your ubuntu ?

**Comment by GETandSELECT** [comment]
it's working fine on `Ubuntu 20.04 LTS (GNU/Linux 5.4.0-1012-raspi aarch64)`.
Thanks @bnkai

**Comment by brumouta** [comment]
Hi, I'm trying to run stash on an odroid c2 running debian, but the actual release isn't compatible as it is not arm64.
I've tried compiling myself but I had a lot of errors as I don't know too much about the go environment.
Can I please have a release for arm64? The link in the comment above isn't working anymore.
@bnkai

**Comment by bnkai** [comment]
Latest dev static builds for armv6,arm64

https://gofile.io/d/YvldWh

md5s
414a0060b008d3dfb7e9bf0cd257c345  stash-dev-arm64
a2499e31619f6cd2456a1b9e6e4bc1e0  stash-dev-armv6

@brumouta can you try the specific 32bit version also (stash-dev-armv6) and report along with the os version ( uname -a) ?

**Comment by GETandSELECT** [comment]
I receive 500 for gofile.io

```
curl -i https://gofile.io/
HTTP/2 500 
content-security-policy: default-src 'none'
content-type: text/html; charset=utf-8
date: Fri, 14 Aug 2020 08:18:21 GMT
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
x-powered-by: Express
x-xss-protection: 1; mode=block
content-length: 213

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: EPROTONOSUPPORT: protocol not supported, stat &#39;/usr/src/app/index.html&#39;</pre>
</body>
</html>
```

**Comment by brumouta** [comment]
> Latest dev static builds for armv6,arm64
> 
> https://gofile.io/d/YvldWh
> 
> md5s
> 414a0060b008d3dfb7e9bf0cd257c345 stash-dev-arm64
> a2499e31619f6cd2456a1b9e6e4bc1e0 stash-dev-armv6
> 
> @brumouta can you try the specific 32bit version also (stash-dev-armv6) and report along with the os version ( uname -a) ?

Thanks, but I'm not able to download the file. I think gofile is down or something.

**Comment by brumouta** [comment]
I was able to test it now and both versions work.

uname -a
Linux DietPi 3.16.85+ #1 SMP PREEMPT Tue Jun 30 19:02:35 CEST 2020 aarch64 GNU/Linux

**Comment by Tweeticoats** [comment]
Stash is designed to be compiled using x86_64 linux containers.
If you have windows with build 2004 and configure wsl2 and install docker and ubuntu you should be able to build it from there.

First thing you need to do is set up a compiler docker container (assuming the pull request has not been merged).
git clone https://github.com/stashapp/stash.git
cd stash
git fetch origin pull/737/head:737
git merge 737
cd docker/compiler
make
if you don't have make installed run the following instead:
docker build --no-cache -t stashapp/compiler:3 -t stashapp/compiler:latest .

You then need to launch this container and use this to pre-compile and install dependencies and then build the binaries.
Start the container, install revive, install packr, yarn install in the ui directory, make generate, make ui, make build.
You would launch the container and run these commands inside the container to set things up for compiling.
docker run --rm --mount type=bind,source="$(pwd)",target=/stash -w /stash -i -t stashappdev/compiler:latest /bin/bash

The way I do this is by using the following shell script to start the container and run these commands to pre-compile everything, save as build.sh and run.
> echo "==== starting container ===="
> docker run --name=stash-build -d --mount type=bind,source=`pwd`,target=/stash -w /stash   stashapp/compiler:latest /bin/sleep infinity
> echo "==== install revive     ===="
> docker exec -w /stash stash-build go get github.com/mgechev/revive
> echo "==== install packr      ===="
> docker exec -w /stash stash-build go get github.com/gobuffalo/packr/v2/packr2
> echo "==== yarn install       ===="
> docker exec -w /stash/ui/v2.5 stash-build yarn install --frozen-lockfile
> echo "==== make generate      ===="
> docker exec -w /stash stash-build make generate
> echo "==== make ui            ===="
> docker exec -w /stash stash-build make ui
> echo "==== make build         ===="
> docker stop stash-build
> docker rm stash-build

You now need to run the cross compiler and build the binaries run the following:
./scripts/cross-compile.sh
binaries should now be in dist
