### ISSUE TITLE
[Feature] Convert Feet/Inches to CM when scraping

### ISSUE THREAD

**Issue by halorrr** [stashapp/stash#587]
**Is your feature request related to a problem? Please describe.**
Currently when creating a performer scraper, if the site doesn't include the height in cm ([example site](https://vrcosplayx.com/cosplaygirl/liyasilver/)), the height data becomes useless since stash expects the height in cm.

**Describe the solution you'd like**
Similar to how we work with multiple date formats, it would be useful to have a heightParse post-processing option.

**Describe alternatives you've considered**
Doesn't seem any way aside from manual to handle this currently.

**Additional context**
A quick Google search turned up this which may be helpful:
https://stackoverflow.com/questions/44091338/convert-feet-and-inches-to-centimeters-in-go

**Comment by bnkai** [comment]
For the date we use time.Parse that is already available in go.
Making an equivalent would be too complicated imho.
Its way easier to just use a separator eg like concat does to separate the feet from the inches. 
`5'3` or `5ft3` ...
In some cases inches are missing so that should be taken into account.

**Comment by halorrr** [comment]
@bnkai but I thought the db expects the height to be in cm? So concating doesn't really do much here?

**Comment by bnkai** [comment]
I meant **like** concat, instead of parsing the 5'3 or 5ft3 or whatever just use the `'` or the `ft` as separator and get the feet,inches that we then can convert to cm. It will have more usage limitations but it will be easier to implement.

**Comment by woodgen** [comment]
I propose a solution for this in #711
