### ISSUE TITLE
[Feature] Setup page improvement

### ISSUE THREAD

**Issue by UncleRoger33** [stashapp/stash#593]
_First of all, sorry if this issue was mentioned before.  I just created an account to give some feedback and i have basic knowledge about GitHub . Also i've read almost all open issues, but couldn't find any similar issue._

**Is your feature request related to a problem? Please describe.**
 As we all know at the very first access to StashApp, the setup page welcomes you. 

I followed the tips and filled those textboxes like this:

![image](https://user-images.githubusercontent.com/66418211/83751733-fd54df80-a66f-11ea-9ea5-369e106cf260.png)

At this time i had a "stash" folder but none of subfolders:

![image](https://user-images.githubusercontent.com/66418211/83751977-6ccacf00-a670-11ea-8b22-23720e898249.png)

When i clicked "Submit", i got this error:

![image](https://user-images.githubusercontent.com/66418211/83752069-8ff57e80-a670-11ea-95d7-750f6ffd09d6.png)
 

**Describe the solution you'd like**
**Describe alternatives you've considered**

Two possible solutions as seen in this screenshot:

![image](https://user-images.githubusercontent.com/66418211/83752827-d39cb800-a671-11ea-8a05-4ea486b32947.png)

Thanks in advance.

**Additional context**
Kudos to all developers and contributers working on this app. StashApp is going to fill the huge gap in this genre.

**Comment by bnkai** [comment]
#540 is already available and covers what is mentioned here. User feedback is always appreciated though.
