### ISSUE TITLE
[Feature] option to move files to folders based on studio

### ISSUE THREAD

**Issue by navyseai** [stashapp/stash#596]
**Is your feature request related to a problem? Please describe.**
Sometimes files and folders can be a mess. we can end up having 2 folders for the same studio or performer   

**c**:\myFolder\[studio1]movie.avi
**d**:\fav\myFolder\studio1(2)\movie2.avi
 
**Describe the solution you'd like**
It would be nice to have an optional feature similar to [musicBrainz Picard ](https://picard.musicbrainz.org/)where tagging the musics actually move the files and organize them into folders something like

c:\myFolder\studio\performer\movie.avi
c:\myFolder\studio\performer2\movie2.avi

or

c:\myFolder\performer\movie.avi
c:\myFolder\performer\movie2.avi

or

c:\myFolder\studio\movie.avi
c:\myFolder\studio\movie2.avi

I also believe this could might help optimizing the scrapper

**Describe alternatives you've considered**
as last resource it would be nice to be able to rename a file based on the tags
many times I seem to have problems with the scrappers or re-tagging after we specifically removed a tag and performing a new scan over the collection. The tag is re-added

**Comment by bnkai** [comment]
Closing this as <https://github.com/stashapp/CommunityScripts/tree/main/plugins/renamerOnUpdate>  seems to cover everything mentioned.
