### ISSUE TITLE
[Feature] Update path field via SceneUpdate

### ISSUE THREAD

**Issue by bugs181** [stashapp/stash#601]
**Is your feature request related to a problem? Please describe.**
Being able to update the path field via `SceneUpdate` would allow third party utils to move the files around and update the media item without having to rescan files and re-add metadata.

Further investigation appears that the graphql `SceneUpdate` is part of `query` in the JSON. So adding `path` field to `SceneUpdateInput` would most likely allow us to use it.

**Describe the solution you'd like**
I'm new to how grapql works but I believe adding the path field to [line 15](https://github.com/stashapp/stash/blob/d886012d742beb558b96f401b23240323baf7ac4/graphql/documents/mutations/scene.graphql#L15) would be required.

**Describe alternatives you've considered**
The only alternative I could think of would be to create a new exposed API that would allow updating whatever info we wanted.

**Additional context**
This feature would be used in a future tool that I'm developing to auto-download files and add them to StashApp.

**Comment by ConstantMoo** [comment]
Hi there, I'd also greatly appreciate having the `path` field available in `sceneUpdate` for my third party tool.

Since I'm pretty much clueless in Graphql and Golang, I naively tried to poke around `SceneUpdateInput` in `\graphql\schema\types\scene.graphql` and `sceneUpdate()` in `\pkg\api\resolver_mutation_scene.go`  but got compilation errors that I couldn't understand:

```
func (r *mutationResolver) sceneUpdate(input models.SceneUpdateInput, translator changesetTranslator, repo models.Repository) (*models.Scene, error) {
[...]

	updatedScene.Title = translator.nullString(input.Title, "title")
	updatedScene.Details = translator.nullString(input.Details, "details")
	updatedScene.URL = translator.nullString(input.URL, "url")
	updatedScene.Date = translator.sqliteDate(input.Date, "date")
[...]
//attempt to add path field
	updatedScene.Path = translator.nullString(input.Path, "path")
```

```
input SceneUpdateInput {
  clientMutationId: String
  id: ID!
  title: String
  details: String
  url: String
  date: String
  rating: Int
  organized: Boolean
  studio_id: ID
  gallery_ids: [ID!]
  performer_ids: [ID!]
  movies: [SceneMovieInput!]
  tag_ids: [ID!]
  """This should be a URL or a base64 encoded data URL"""
  cover_image: String
  stash_ids: [StashIDInput!]
//attempt to add path field
  path: String
}
```

Error:
```
go generate -mod=vendor
validation failed: packages.Load: /mnt/g/dev/stash/pkg/api/resolver_mutation_scene.go:109:22: cannot use translator.nullString(input.Path, "path") (value of type *sql.NullString) as *string value in assignment
exit status 1
main.go:1: running "go": exit status 1
make: *** [Makefile:109: generate] Error 1
```
I'm obviously not doing something right, so any help is welcome!

**Comment by stg-annon** [comment]
If you are looking to interact with GQL it is a web API so the GoLang code wont help you much I would start at `http://localhost:9999/playground` as that might help you get a feel for how the GQL api works, alternatively take a look in your browsers dev tools in the **Network** tab for graphql requests and you can take a peak at how the app is using the api via the headers and responses


If you are looking to update the path the best way to do that IMO is just to rescan, oshash is the identifier hash for all the scene files, and it is really quick so it will auto associate and update the path, if you really want to manipulate the path for some reason the other way of doing it is directly via the sqlite db, if you need an example take a look at the [renamerOnUpdate](https://github.com/stashapp/CommunityScripts/tree/main/plugins/renamerOnUpdate) plugin which uses this method to update the path after modifying the file name so as not to need to rescan.


If you were to be able to edit the path via the API, I would argue for checks on the new path before updating it. A couple of checks could be, that the path exists and that the oshash of the file at the new path matches the stored hash for the scene.

**Comment by bnkai** [comment]
Closing. More info in #1692
