### ISSUE TITLE
[Feature] CommunityScraper Management/Sync Within Stash UI

### ISSUE THREAD

**Issue by halorrr** [stashapp/stash#623]
**Is your feature request related to a problem? Please describe.**
Keeping community scrapers up to date requires you knowing they are broken, and finding new ones that might be added requires knowing what is added. 

**Describe the solution you'd like**
A UI section that can be used to download and update community scrapers. In my head I envision this panel as allowing you to pick and choose scrapers to sync or just sync all.

**Describe alternatives you've considered**
The alternatives are the good old manual way that there is now.

**Additional context**
N/A

**Comment by WithoutPants** [comment]
Design discussion in #2244

**Comment by WithoutPants** [comment]
$100 bounty placed (contribution no. 603385)

**Comment by WithoutPants** [comment]
$207 bounty added ([contribution #695434](https://opencollective.com/stashapp/contributions/695434))

Total bounty $307.
