### ISSUE TITLE
[Feature] Play Counter

### ISSUE THREAD

**Issue by velzy00** [stashapp/stash#633]
**Is your feature request related to a problem? Please describe.**
I'd love for Stash to track the play count for scenes, so I can get a better sense of what's getting watched and what isn't. 

**Describe the solution you'd like**
I would suggest presenting the play counter next to the o_counter in the Details tab of the Scene page and on the Scene card. On the Edit tab, the functionality to decrease or reset the count would work the same as the o_counter. Instead of manually tracking this count though, Stash would automatically track every time someone plays a scene. Hit play on a scene and the count goes up.

If we wanted to get fancy, there could also be a setting for the minimum play duration required for a play to be counted, but that may be more complex than is.

**Describe alternatives you've considered**
I think the the o_counter is the best model for the to be presented. This could also be shown as a section in the details tab, with the playcount and last play date/time show but that the o_counter style seems cleaner. 

**Additional context**
It can be hard to keep track of so many scenes, particularly when continuously adding new more. Having access to more data to use in pruning the collection is so helpful for making decisions to manage the size of the collection.

**Comment by honeybeaver** [comment]
+1 and would be nice to also track play history, and less important, play progress in videos. Thanks.

**Comment by kermieisinthehouse** [comment]
Good idea but please make this togglable. I often reference videos to tag them / compare duplicates and it would easily pollute the counters.

**Comment by Caleripo** [comment]
Also tracking how many times a scene was played would enable really useful features in the future. 
For example you could filter by the most watched scene, display trending scenes, etc.

**Comment by Stephan972** [comment]
IMO, this feature should appear in a porn theater rather than a porn organizer. The theater would count plays , views or build other analytics the organizer could consume later.

**Comment by 0xb0af** [comment]
> IMO, this feature should appear in a porn theater rather than a porn organizer. The theater would count plays , views or build other analytics the organizer could consume later.

This makes sense in theory but how would it actually map to the current architecture of Stash (being both an organizer, and a player, and backed by a single database)? 

Having a play count would also enable filtering by watched/unwatched (play_counter > 0)

**Comment by WeedLordVegeta420** [comment]
While number of times played is a decent metric, the better metric for porn in my opinion is minutes/seconds watched. Unlike a standard TV show of film, there's less of expectation with porn that when you click play, you're going to actually watch it all the way through to the end without skipping ahead/back.

I have used other porn organizers in the past that did track time watched per video, and I did like having that. With time watched per video being tracked, you can then query to get time watched per performer, tag, studio, etc. making it easy to see your most/least watched in each of those groupings.

**Comment by magicswarmingswarm** [comment]
+1 To this. Think it would be an incredible valuable feature to add. Second Weedlordvegeta420's suggestion of a minutes/second watched counter as well if that could be implemented on the side (although I would guess that is harder). Happy to contribute to a bounty for this - if it's too much for me individually would be cool to do a collective bounty as I feel lots of people really want this feature

**Comment by WithoutPants** [comment]
Here's my proposed design:

- schema change to add view count to scene
- filter/sort options for scene view count
- two new settings: minimum view time for scene counter, and enable/disable scene counter
- in the scene player UI, increment view count by 1 when the minimum view time is exceeded

A minutes watched metric can be a separate feature. For the purposes of this issue, I'm sticking to the view counter concept.

**Comment by magicswarmingswarm** [comment]
> Here's my proposed design:
> 
> * schema change to add view count to scene
> * filter/sort options for scene view count
> * two new settings: minimum view time for scene counter, and enable/disable scene counter
> * in the scene player UI, increment view count by 1 when the minimum view time is exceeded
> 
> A minutes watched metric can be a separate feature. For the purposes of this issue, I'm sticking to the view counter concept.

When could this hypnothetically be implemented, sounds great!

**Comment by WeedLordVegeta420** [comment]
> When could this hypnothetically be implemented, sounds great!

Been a bit busy, but I have gotten as far as data schema updates and config options for the time watched metric. However, I should probably open a separate Issue to track that since it seems like that is @WithoutPants's preference.

I'm new to this codebase so I'm still figuring it all out, but hopefully I can have something ready for a pull request on that front in the next couple of weeks.

**Comment by Stephan972** [comment]
@kermieisinthehouse 
If you had one tool for referencing videos to tag them / comparing duplicates and another for watching them and building counters around the videos, there would be no need for a toggable button.

Imagine the user going back and forth in an option menu just to preserve the counters and don't "pollute" them. Sooner or later counters become irrevelant. The user doesn't notice, doesn't remember (or gets bothered that) its  maintenance actions impact the counters. 

Stash can't tell either what type of actions the user is performing : delightful video watching or serious video organizing.

**Comment by magicswarmingswarm** [comment]
It could also be a togglable feature so you could turn it off in settings?

**Comment by WeedLordVegeta420** [comment]
![image](https://user-images.githubusercontent.com/81525421/184564254-c751ca7c-dcc0-48fc-bd6d-1a825c19c6e1.png)

I've gone ahead and added in both the play count along with time played and last date played, and I have it mostly working with respect to recording the data. I know that @WithoutPants mentioned splitting out the play count and the time tracking to a separate issue, but it just makes sense to do them together since it's similar related data.

I still need to do the interface work (display info on Scene detail tab, filter/sort, etc.) and code cleanup, but it's looking good for me to have a pull request soonish.

**Comment by sleetx** [comment]
I'm in agreement with Kermie and WithoutPants that this should either be a togglable feature, or something with a "minimum view time" option before it starts tracking data. 

Or both. We don't want the editing or managing scenes from the scene page to pollute the "view" data.

There needs to be a few test scenarios for the "play count"/"time played" if the user is skipping around the timeline. For example: someone opens a 30 minute video, watches the first 5 minutes, then skips to watch the last 5 minutes. That should be considered 10 minutes played - excluding the skipped time, but including the 5 minutes after the skip happens. And it should be considered one total view.

**Comment by WeedLordVegeta420** [comment]
@sleetx 

Currently these are the settings that I've added:
![image](https://user-images.githubusercontent.com/81525421/184575013-02cd6a0f-ad98-45ed-a798-8d87fb8f6d87.png)

**Comment by magicswarmingswarm** [comment]
That's great! Would there then be a way for scenes to be 'ranked' by this data (e.g. in the area where you display scenes ascending or descending by title, date, plays etc.). Additionally would there be a way as well to then have this data displayed in aggregate somewhere? Perhaps on the 'statistics' page?

**Comment by WeedLordVegeta420** [comment]
> That's great! Would there then be a way for scenes to be 'ranked' by this data (e.g. in the area where you display scenes ascending or descending by title, date, plays etc.). Additionally would there be a way as well to then have this data displayed in aggregate somewhere? Perhaps on the 'statistics' page?

I'm going to add in sort/filter options before I submit the pull request. A separate stats summary page is beyond the scope of what I plan to do for now.

**Comment by QxxxGit** [comment]
@WeedLordVegeta420

Food for thought: I have many clips that are really short -- some are even 5s. Long videos I'd want 15 seconds to increment the counter but this wouldn't increment the smaller clips. What are your thoughts on some sort of percentage-based either-or option here?

So like we can configure a minimum of either X seconds watched OR 25% watched, whichever is lowest.

**Comment by WeedLordVegeta420** [comment]
> Food for thought: I have many clips that are really short -- some are even 5s. Long videos I'd want 15 seconds to increment the counter but this wouldn't increment the smaller clips. What are your thoughts on some sort of percentage-based either-or option here?

Thanks for calling out this scenario. It hadn't come to mind.

The simplest implementation seems like it would just be to make the "watched" threshold the lesser of the configured value and the video's full length. The issue there would be if you skip ahead a couple of seconds in your very short video, you would hit the end before it counts as "watched". Unless you played more of the video by looping back to the start or jumping to somewhere in the middle, you would lose that data.

I like your suggestion of having a percentage option and taking the lesser of the min watch time (seconds) and min watch time (percentage of video full length). That does seem like it would give you the most accurate data.

**Comment by Stephan972** [comment]
> @sleetx
> 
> Currently these are the settings that I've added. I need to edit the description to indicate these relate to all play/time tracking (wrote it when I was initially only going to do time tracking and not play count), but the intent should be evident: ![image](https://user-images.githubusercontent.com/81525421/184575013-02cd6a0f-ad98-45ed-a798-8d87fb8f6d87.png)

Would be nice to have some global easy access to this settings while managing videos.

**Comment by RandomName250** [comment]
Great to hear that this feature is being worked on as it is the one main thing that has prevented me using Stash - having a view history is essential for me! But I am just confused about how complex it has to be in regards to tracking the length a scene has been played within Stash for it to be registered as data. All I have been looking for is a way to mark a scene as played and for that date info (such as last_date_played) to be recorded in Stash (enabling the scenes to then be sorted by date last viewed). The o-counter would work but that does not include any date info so this could work as an alternative. For scenes that are watched outside of Stash on different devices, I still would love the option to mark them as watched in Stash at a later date (which I have had to do while changing the system date in other programs). I would also like to import data to stash from another program that includes history in a date format. So, I'm basically hoping that this feature could be used in this kind of manual mode in addition to the automated way.

**Comment by WeedLordVegeta420** [comment]
@RandomName250 The basic concept isn't that complex, but this idea just hadn't gotten much traction until recently. I decided to hold off on completing this until after release v.017 and the code base stabilizes a bit more, but I'll put in the pull request for this feature after that.

**Comment by magicswarmingswarm** [comment]
Still really keen on this - any indication how far until 0.17 is released?

**Comment by WithoutPants** [comment]
> Still really keen on this - any indication how far until 0.17 is released?

Aiming for this month.

**Comment by c-0ne** [comment]
Is there a date for next release with this feature?

**Comment by WeedLordVegeta420** [comment]
> Is there a date for next release with this feature?

Sorry. I can't give an exact date, but now that the codebase has stabilized, I will likely pick this development back up soon.

**Comment by magicswarmingswarm** [comment]
0.17 is out, keen to have a look at how this feature could look

**Comment by WeedLordVegeta420** [comment]
@magicswarmingswarm I should have time to work on it this weekend. Your patience is appreciated.

**Comment by Teda1** [comment]
@WeedLordVegeta420 I'm currently working on adding support for tracking watch activity, enabling Stash to remember the duration users left a scene at, as well as tracking recently completed scenes and recently watched scenes.

![Screenshot 2022-10-25 210553](https://user-images.githubusercontent.com/72030708/197917679-0fa70418-13fd-484f-9271-899aa01faaea.png)

I'm thinking I could add a watch time tracker with the changes I have so far assuming you haven't already made progress on your end.

**Comment by WeedLordVegeta420** [comment]
@Teda1 You can pretty much see the progress that I had made in the posts above, but I haven't done the work to refactor it all after the merge of the `file-refactor` code. If you're already at a point where you can easily add it onto what you have, go for it.

**Comment by Teda1** [comment]
My mistake. I missed the progress shot you posted earlier in this issue. Reading on, I see that the watch time tracker I planned differs from the play counter design WP proposed. I’ll go ahead and leave that work out of my branch. Some of the work I’ve done may benefit you when you continue this work.

**Comment by WeedLordVegeta420** [comment]
Sounds good. I'll try to integrate my changes along with your updates since I'm sure there will be some overlap.

**Comment by Teda1** [comment]
I've put out the pull request to track watch activity. I am open to working on this feature next if you want to free up some time. If I were doing this work, I would track the total time a scene has been played. I would also include an option for users to sort scenes by watch time and enable users to filter scenes by watch time, similar to the duration filter that already exists. This approach differs slightly from the design WP proposed in that it tracks time played rather than view count. I don't see any harm in tracking both, though.

**Comment by WeedLordVegeta420** [comment]
@Teda1 If you can easily add that to your existing PR, that would be fine with me. That was originally all I was going to do as well, but then I added on the "play counter" tracking to try to meet the original request. That was basically just accomplished by incrementing a counter once the watch time passed a settings defined minimum watch time during a single session.

Long story short though, I think just having the time tracking in there is a good first step. If there's a lot of demand for the incrementing "play counter", I'd be happy to tackle adding that on.

**Comment by WeedLordVegeta420** [comment]
Thanks for picking this up. I'd intended to do my refactoring after 0.17 hit but haven't had time the past couple of weeks.

**Comment by Teda1** [comment]
No problem!

**Comment by xx790** [comment]
Minimum watched play time could be in % - that would address the issue for short videos.
