### ISSUE TITLE
[Feature] Multiple performers same name

### ISSUE THREAD

**Issue by Tweeticoats** [stashapp/stash#638]
**Is your feature request related to a problem? Please describe.**
Unfortunately names are not unique and there are occasionally people that perform under the same name as another performer.
This can happen when someone uses a more generic name earlier in their career and change it later as well as people in different countries picking the same name.
It would be nice to support adding the same name twice and having some way to disambiguate between the two names.
In my collection I have Trillium (USA performer) and Trillium (girlsoutwest).

**Describe the solution you'd like**
In my collection I have added Trillium (girlsoutwest) to add the second performer with that name.
If there was some standard way of indicating this as a duplicate such as adding a dash, underscore, #2 to the name etc.
eg. Trillium #2, Trillium - website, Trillium (website).
This disambiguation should work on artist names as well as alias strings.

When the auto tagger job runs it should prioritise a website alias if it matches before processing the more generic name.
So if I have a site in their name or in their alias string it should add that performer instead of the exact match of the name.

**Alternate solution**
Adding a studio to the performer page might be a better way of dealing with this.
If in the performers profile page there was a way of selecting a list of studio associated with the performer.
When the auto tag job it would select that performer with a higher priority than similar names.

**Comment by bnkai** [comment]
Related to https://github.com/stashapp/stash/issues/422

**Comment by stg-annon** [comment]
would this be resolved by #3113?

**Comment by SpedNSFW** [comment]
I believe stg-annon is correct, disambiguation resolves this. I already have multiple performers with the same name.
This can probably be closed now.
