### ISSUE TITLE
[Feature] Toggle selection by clicking the cover image when selecting multiple items

### ISSUE THREAD

**Issue by seducingbits** [stashapp/stash#639]
**Is your feature request related to a problem? Please describe.**
Selecting multiple scenes is a pretty nerve wracking experience. When you miss the checkbox and accidently click the cover image you are leaving the page and are losing your selection. Therefore when selecting multiple scenes you have to work pretty slow and aim correctly.

**Describe the solution you'd like**
Plex solves this problem pretty great. After having selected the first item the complete cover image becomes the click target to toggle the selection. Also clicking and dragging over multiple items toggles selection for all items which are hovered for fast selection.

**Describe alternatives you've considered**
Making the checkboxes bigger?

**Comment by WithoutPants** [comment]
These are good suggestions. I'll get something into this release.
