### ISSUE TITLE
[Feature] Scene selection in list view

### ISSUE THREAD

**Issue by seducingbits** [stashapp/stash#640]
**Is your feature request related to a problem? Please describe.**
Scene selection is great for quickly editing multiple files. Right now this is only possible in grid view.

**Describe the solution you'd like**
Add a selection checkbox in list view. Either as it's own column or over the cover image like in grid view.

**Additional context**
This is probably covered with #517. But that's a pretty big overhaul while my proposal is should be less work while still adding a lot of value.

**Comment by WithoutPants** [comment]
Resolved by #1642.
