### ISSUE TITLE
[Bug] Remember the thumbnail size

### ISSUE THREAD

**Issue by seducingbits** [stashapp/stash#648]
**Describe the bug**
Always when a page gets (re)loaded the thumbnail size slider is set to 2 from 4 while all other display settings (mode: grid/wall/list, filter, searchquery) are restored.

**To Reproduce**
1. Go to scenes page, set the slider to 4 from 4
2. Reload page
3. Slider is back to 2 from 4

**Expected behavior**
Slider stays at 4 from 4

**Stash Version: (from Settings -> About):**
v0.2.1-25-gf1c544a

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: firefox
 - Version 77.0.1 (64-Bit)

**Additional context**
No really sure if bug or expected behaviour. For me it more feels like a bug since all other settings are remembered.
It's also applicable to the zoom slider for the galleries tab.
Studio and performer page too but there, the other elements aren't saved either.

**Comment by WithoutPants** [comment]
Resolved with #1636.
