### ISSUE TITLE
[Feature] StashApp on DockerHub

### ISSUE THREAD

**Issue by merqwury** [stashapp/stash#649]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
I would love to be able to use Docker Hub to get my image for Docker, etc, rather than having to build it every time, create a container, etc.

**Describe alternatives you've considered**
N/A

**Additional context**
Signing up and hooking into GitHub for automation is easily provided in Docker Hub - This should be a 5 minute process, and Docker Hub allows 1 free project on a public GitHub repo.

**Comment by HereIam80** [comment]
Do you meansomething like this:
![grafik](https://user-images.githubusercontent.com/31324543/86513976-be50b000-be0e-11ea-9a1c-9fdfc6109ac0.png)
If not, I am sorry and I don't know what I am talking about.

**Comment by WithoutPants** [comment]
Doesn't this have everything you need? 
https://hub.docker.com/r/stashapp/stash/tags
