### ISSUE TITLE
Move from JW Player to open-source video.js?

### ISSUE THREAD

**Issue by victorhooi** [stashapp/stash#659]
What do you think of replacing JW Player with the opensource project video.js?

It's open-source, under very active development ([Github repo](https://github.com/videojs/video.js
)), and the licensing is much more permissive.

@WithoutPants mentioned before one issue was the theming (i.e. out of the box, video.js did not look as good as JWPlayer before), however, I checked and they now offer four themes out of the box - they don't look that bad?

https://videojs.com/fantasy

Thoughts?

**Comment by whyboris** [comment]
I'm really curious about _JW Player_ - it seems to be [not free](https://www.jwplayer.com/pricing/), so how is _stash_ able to use it? 😅  

Is it because _stash_ is free rather than commercial?

**Comment by InfiniteTF** [comment]
> I'm really curious about _JW Player_ - it seems to be [not free](https://www.jwplayer.com/pricing/), so how is _stash_ able to use it? 😅
> 
> Is it because _stash_ is free rather than commercial?

[jwplayer is CC-BY-NC-SA](https://github.com/jwplayer/jwplayer/blob/master/LICENSE), so we can distribute/remix it for non-commercial purposes.

I agree we should ditch jwplayer though, both because of the restrictive license, but also because it lacks a lot of features and extensibility.

**Comment by stg-annon** [comment]
another benefit of videojs appears to be the ability to support VR content  

https://github.com/videojs/videojs-vr

**Comment by victorhooi** [comment]
Ah - that's definitely a win.

For the Devs - Is there any effort/interest in trying out video.js with stash?

**Comment by WithoutPants** [comment]
Yes, definitely. I've looked at transitioning to videojs before (pretty sure I still have the branch). It's not a simple thing, but definitely something I want to move to. Not sure what the timeframe will be yet.
