### ISSUE TITLE
[Feature] Tag grid view enhancements (delete button, image cropper)

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#660]
Re: #641

1. Add a button to delete an existing image. There's currently no way to remove a tag image.
2. When uploading an image, add a crop feature while the image is being uploaded, [such as this](https://vuejsexamples.com/tag/crop/), at a set aspect ratio, such as 1:1 or 4:3, so all images are the same aspect ratio. This will make the tag images look so much better if they all share the same aspect ratio.

(Side note: the image cropper idea should probably also be extended to actors image and scene image uploads).

**Comment by WithoutPants** [comment]
Not sure I can commit to the image cropper, but the delete image thing should be added.
