### ISSUE TITLE
[Bug Report] Tag Delete Not Working Correctly

### ISSUE THREAD

**Issue by velzy00** [stashapp/stash#662]
**Describe the bug**
I find that I have to reload after deleting a tag to no longer see the tag on the tags page. Seems likely to be a cache issue.

When viewing the tag page in list view, the delete button does not appear to be working at all. When clicked, the tag does not delete and the page doesn't change. Upon refresh the tag is still there.

**To Reproduce**
1. Go to the tags page
2. Open a tag
3. Delete the tag
4. Tags page loads with the deleted tag still visible (& can be clicked to load the tag edit screen)
5. Refresh the page
6. Deleted tag is now gone

**Expected behavior**
After deleting a tag, the tags page should load with that tag no longer present.

**Stash Version: v0.2.1-28-gf578424

**Desktop (please complete the following information):**
 - OS: macos
 - Browser Brave 
 - Version 1.10.97

**Comment by WithoutPants** [comment]
Related to #166
