### ISSUE TITLE
Saving performers with the same image

### ISSUE THREAD

**Issue by DDC12** [stashapp/stash#67]
When saving performers with the same image you get a unique constraint error. I presume because you build a checksum using only the image.

Seeing as I do not have an image for every performer I'm adding, I reuse a generic "female shape"-image for ~95% of the performers. At least until I care to spend time on actually adding an image for them.

To work around this I removed the unique key from the database and now it works fine. Though having to add an image to even be able to save it is kind of a hassle. Maybe use just the performer's name for the checksum? It's something that should be unique anyway.

**Comment by bnkai** [comment]
I think images for performers are used the same as for studios #58 
Thus by removing the constraint and using the same image you'll get unpredictable results with the export/import functions.
I do agree though that a generic image is convenient and maybe generating the checksum from the name could be unique enough
