### ISSUE TITLE
Scan problem

### ISSUE THREAD

**Issue by smalldickman** [stashapp/stash#676]
I run stash on openwrt+docker，everything works fine,.but when I Scan , there was a problem,there are 89 videos(.mp4) in the (media:data)folder, and only 54 of them can be displayed in the scene after scanning. I tried to reinstall, change the movie name to be short&simple, and move those video to the root directory of the Scan location, or create a category directory in the root directory, and the scan  result is always only 54 display.
This is my mount configuration：

STASH_STASH=/data/
STASH_METADATA=/metadata/
STASH_CACHE=/cache/
STASH_GENERATED=/generated/

/00storage/stash/config:/root/.stash
/00storage/media:/data
/00storage/stash/metadata:/metadata
/00storage/stash/cache:/cache
/00storage/stash/generated:/generated

 hard disk space is very ample

![54](https://user-images.githubusercontent.com/31898637/87842992-40e37000-c8e3-11ea-9054-3839e96856c6.JPG)
..........................
![media](https://user-images.githubusercontent.com/31898637/87843031-8869fc00-c8e3-11ea-9999-eafbf512e367.JPG)
..........................
![91](https://user-images.githubusercontent.com/31898637/87843059-bcddb800-c8e3-11ea-9bbf-23d6b0af7630.JPG)
.........................
![parser](https://user-images.githubusercontent.com/31898637/87843089-15ad5080-c8e4-11ea-846b-598715422509.JPG)
.........................
![Scan](https://user-images.githubusercontent.com/31898637/87843140-99ffd380-c8e4-11ea-81bd-3c29a493a895.JPG)

**Comment by WithoutPants** [comment]
Please include the version that you are running.

You'll want to check the logs first to see if the files are being ignored because they are duplicates of other files in your directory.

You will also want to find out which files are being ignored, so we can diagnose further. There was a recent commit that fixed it so that files with uppercased extensions (ie `MP4`) were not being included, so if you have an old version then it may not include that commit.

**Comment by smalldickman** [comment]
> 请包括您正在运行的版本。
> 
> 您需要首先检查日志，以查看文件是否被忽略，因为它们是目录中其他文件的副本。
> 
> 您还将希望找出哪些文件被忽略，以便我们进一步诊断。最近有一次提交对其进行了修复，以确保`MP4`不包括带有大写扩展名（即）的文件，因此，如果您使用的是旧版本，则可能不包含该提交。

Thank you very much for your response
this is the version number: v0.2.1
![ver](https://user-images.githubusercontent.com/31898637/87843323-2ced3d80-c8e6-11ea-9518-5ec03a0c40f2.JPG)
I'll change the extension now and try again

**Comment by smalldickman** [comment]
> Please include the version that you are running.
> 
> You'll want to check the logs first to see if the files are being ignored because they are duplicates of other files in your directory.
> 
> You will also want to find out which files are being ignored, so we can diagnose further. There was a recent commit that fixed it so that files with uppercased extensions (ie `MP4`) were not being included, so if you have an old version then it may not include that commit.

The reason is in the extensions, it can be identified now, thank you very much for your advice...
