### ISSUE TITLE
[Request] Auto assign a tag to newly added scenes

### ISSUE THREAD

**Issue by DDC12** [stashapp/stash#68]
At the moment it's kind of hard to find scenes you haven't "finished" organizing yet. I now add scenes in batches just so I can order by date created and then carefully organize each scene, adding the studio last, using that as a marker to know up to where I've organized everything.

Is it possible to automatically add a tag to new items so you can just search for that tag. This way you can complete a scene by simply adding all the data and removing that tag.

**Comment by GernBlanston12** [comment]
How do you remove the tag, as it is? There might need to be a skip between the rock and the far shore...

**Comment by Ch00nassid** [comment]
I'd like to bring attention back to this request.  I have been recently very active in the Stash community, I have imported my entire personal collection from my own SQL server.  While i was reviewing my content, I thought about the same thing as DDC12 mention in his original most.

I was finding it very difficult to weed through the 12000 scenes that I have currently to determine what i would considered "organized" or "reviewed" -- (If we want, we can even categorize this as "Stashed" or "stashed away" ... playing off the title of the main application...)

For now, I am creating complex filters that would accomplish this task (to an extent).  I just wish i had an indicator for myself that said something like "you have fully reviewed this video and deemed it *stashed* away"

**My personal suggestion:**  Create another field within the Scenes table, labeled "organized" or "stashed" to indicate that this file is considered COMPLETELY REVIEWED by the user of stash.

I understand that this may need users to complete an export and import of their current data for the schema change but I think this might help add an additional view for scenes that are considered complete

**Comment by Leopere** [comment]
I like the idea of letting StashApp once it's tagging system has fully matured offer to tag for you; however, we need to take baby steps where we don't destroy vast swaths of archival data.  There will be no perfect; however, we want to have some degree of certainty before we consider auto-tagging/renaming, etc. without the user's intervention.

**Comment by Leopere** [comment]
I believe this has somewhat matured to be possible given the correct directory structure has it not?  Closing until otherwise determined as incomplete.
