### ISSUE TITLE
[Feature] make "Scene number" field writeable.

### ISSUE THREAD

**Issue by schneckenschnabel** [stashapp/stash#683]
As of now when you assign a Clip to a Movie, the Scene number counter "only" goes to 10.
But there are cases when that is not enough, so it would be great if we could just write a number in there.

**Comment by VonTittyslappen** [comment]
Completely agree, I flagged this up before with my Movie section enhancement suggestions. I mean, there are some movies that have up to 18-20 scenes on them (Suck It Dry and Shut Up And Blow Me series for example). Should be a text field rather than a drop down.
