### ISSUE TITLE
[Bug Report] Broken Marker Seeking

### ISSUE THREAD

**Issue by JoeSmithStarkers** [stashapp/stash#687]
After clicking on a marker preview, the video player fails to seek. (The progress bar shows the seek but video actual starts at the start).

Example of the player url:
http://host/scenes/53309?t=1558

** Additional Context ** 
Happens with all markers
mp4 (h264+aac) video
no ffmpeg tasks running while playing.

**To Reproduce**
1. Goto Markers
2. Click a marker

**Expected behavior**
The player will seek to the marker and begin playing.

** Actual Behaviour **
The player doesn't seek to the marker and begins playing from the start. 

Following on: Clicking on the marker causes the player to seek, but the whole progress bar is messed up. The progress bar indicates being at the end, the time progress display, say bigger number (current timecode) over a small number (duration), eg 56:11 / 27:46. 

**Stash Version: (from Settings -> About):**
My branch is up to this: (I don't believe my modification would be affecting this issue).
commit c327a98ecbd6783c924bf052eb090b9fa7fc372d (upstream/develop)
Date:   Fri Jul 24 10:45:48 2020 +1000

**Desktop (please complete the following information):**
Stash on linux amd64 server.
Browser on OSX 10.15.4 Chrome (Version 84.0.4147.89)
Also checked on Firefox.

**Comment by HereIam80** [comment]
While most of the marker issues are gone, navigating from the "Markers" page still doesn't work for me in Version: | v0.2.1-43-g278be33 / Build hash: | 278be33.

For example the timestamp in the address http://localhost:9998/scenes/2993?t=835 doesn't work.

**Comment by WithoutPants** [comment]
I'm finding that _most_ of the time it works, but there must be a race condition somewhere where sometimes it just doesn't work. Seems to be a jwplayer related wrinkle, and its a mongrel to debug.

**Comment by HereIam80** [comment]
The problem seems to be browser specific. It works flawlessly on chrome and firefox but doesn't work at all on edge, wich I recently used.

**Comment by WithoutPants** [comment]
Well that's somewhat of a relief, since I just tested the latest fix against Edge and it appears to work. Fingers crossed.
