### ISSUE TITLE
Multi edit overwrites previous tags

### ISSUE THREAD

**Issue by EZarnosky** [stashapp/stash#692]
**Describe the bug**
When adding tags for multiple scenes the it strips all previous tags from scene.

**To Reproduce**
1. Add a few tags to a scene & save
2. Select multiple scenes (including one just tagged)
3. Add different tags to the scenes & save
4. View scene details from step 1. All previous tags are gone

**Expected behavior**
New tags to be appended to the scene with existing tags (or at least present and option to not overwrite previous tags)

**Environment and Browser**
 - Docker Container stashapp/stash:development-x86_64
 - Browser Chrome 84.0.4147.89 on Windows 10

**Comment by EZarnosky** [comment]
It appears to do this with Performers as well

**Comment by bnkai** [comment]
You can change the behavior by clicking the buttons
![edit](https://user-images.githubusercontent.com/48220860/88714121-fce33d00-d124-11ea-93cc-c87aaceedda3.png)
default is `set` , you probably want the `+ (add)` one

**Comment by EZarnosky** [comment]
Ah, didn't realize that was there, thanks.
