### ISSUE TITLE
[Task] Document JSON spec

### ISSUE THREAD

**Issue by StashAppDev** [stashapp/stash#7]
https://github.com/stashapp/StashServer/issues/34

https://json-schema.org/

**Comment by yoshnopa** [comment]
I took care of that, only thing untested (and therefore maybe not entirely extensive) is the gallery function, of which I have none.

**Comment by yoshnopa** [comment]
Tried them as well with a dummy file, there are no jsons created at all of this kind, added it to the documentation.
This issue can be closed.

**Comment by WithoutPants** [comment]
Looks like a duplicate of #138
