### ISSUE TITLE
freeones scrape error fatal crash

### ISSUE THREAD

**Issue by DDC12** [stashapp/stash#70]
Sometimes (1 in 100-200 scrapes it turns out) Stash completely crashes. I ran stash in a console and now see that the last log message is:
"Get https://www.freeones.com/suggestions.php?q=a&t=1: dial tcp: lookup www.freeones.com: no such host"

I assume something went wrong with the HTTP GET, probably a DDOS protection firing, which in turn crashes Stash.

EDIT: It seems that the suggestions page only returns anything when the search string is at least 3 characters long, so not loading suggestions unless the string is at least 3 characters long could be a nice addition to handling the error.

**Comment by ueaslsef** [comment]
@DDC12 does this issue still occur in the current version?

**Comment by DDC12** [comment]
@ueaslsef I have not done as many scrapes because I have already added the majority of the data, but none of the ones I have done in the last few months have caused the crash. In fact it now even works when using an alias instead of the specific name on freeones, something that didn't work before.
