### ISSUE TITLE
[Feature] Change video preview back to original cover when mouse leaves scene

### ISSUE THREAD

**Issue by HereIam80** [stashapp/stash#701]
Recently I generated all the video previews for all my scenes. The only thing that bothers me is that the video just stops when you leave the scene with your mouse. I would like to have the originally assigned cover displayed again when I leave the scene card with my mouse.

**Comment by WithoutPants** [comment]
Duplicate of #576

**Comment by HereIam80** [comment]
Man you are fast ... didn't see the original issue.
