### ISSUE TITLE
[Bug Report] Scrapers dir can't be a symlink

### ISSUE THREAD

**Issue by woodgen** [stashapp/stash#706]
**Describe the bug**

stash is unable to load scrapers if the `scrapers` dir is a symlink. There is no error in the log. Scrapers just don't load.

```
$ ls -al .stash/scrapers
lrwxrwxrwx 1 user user 59 Aug  1 13:32 .stash/scrapers -> /home/user/code/CommunityScrapers/scrapers/
```

`ls .stash/scrapers` returns correclty the target scrapers dir content, so the symlink works.

It would be great for this to work, so i.e. the `scrapers` folder from the `CommunityScrapers` git repo could be symlinked and used with version control.

**To Reproduce**
1. replace `~/.stash/scrapers` with a symlink
2. Reload scrapers.
3. No profit.

**Expected behavior**
stash should find the scrapers.

**Stash Version: (from Settings -> About):**
git master b465c36fc78aa454af2d8dcdc6e03779efbcc420

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Chromium 84.0.4147.105

**Comment by peolic** [comment]
as a workaround I believe you can directly set the scrapers path on `config.yml`:
```yml
scrapers_path: /home/user/code/CommunityScrapers/scrapers/
```

**Comment by bnkai** [comment]
For the loadscrapers function filepath.Walk is usedwhich doesnt follow symlinks by design ( to make sure no loop is created )
If we switch to facebook symwalk instead the issue is resolved, the user just has to make sure though that he doesn't create a loop using symlinks. 
All that needs to be changed is
```diff
diff --git a/pkg/scraper/scrapers.go b/pkg/scraper/scrapers.go
index 864c09a..1aa94c5 100644
--- a/pkg/scraper/scrapers.go
+++ b/pkg/scraper/scrapers.go
@@ -9,6 +9,8 @@ import (
 
        "github.com/stashapp/stash/pkg/logger"
        "github.com/stashapp/stash/pkg/models"
+
+       "github.com/facebookgo/symwalk"
 )
 
 // GlobalConfig contains the global scraper options.
@@ -58,7 +60,7 @@ func loadScrapers(path string) ([]config, error) {
 
        logger.Debugf("Reading scraper configs from %s", path)
        scraperFiles := []string{}
-       err := filepath.Walk(path, func(fp string, f os.FileInfo, err error) error {
+       err := symwalk.Walk(path, func(fp string, f os.FileInfo, err error) error {
                if filepath.Ext(fp) == ".yml" {
                        scraperFiles = append(scraperFiles, fp)
                }
```
and a `go mod vendor`

**Comment by woodgen** [comment]
@bnkai Thanks for the patch. Tested it and it works like a charm.
I would welcome this patch to land.

@peolic The config approach is a valid solution as well. I will use it if @bnkai decides to not push this patch.
