### ISSUE TITLE
[Bug Report] oshash collisions preventing migration

### ISSUE THREAD

**Issue by roypoel** [stashapp/stash#708]
**Describe the bug**
While migrating to oshashes, I followed the instructions.  First I scanned my library. Then I had trouble saving after unselecting the MD5 hash checkbox. I got the helpful Graphql error that there were null entries in the oshash column of the scenes table.  That was true.  There were about 4 scenes that had null values for the oshash column.  I believe these remained unpopulated because of non-unique values in that column.  

From my logs:
time="2020-08-06T11:35:50-04:00" level=info msg="Calculating oshash for existing file [redacted] ..."
time="2020-08-06T11:35:50-04:00" level=error msg="UNIQUE constraint failed: scenes.oshash"

It's strange because the md5 hashes for the collisions must be different, because I tried looking up what file they must have been colliding with by md5 and didn't find a match.

To work around this, I appended a bit of text to the offending files and performed a new scan to generate new values for the null oshash values that would no longer collide.  

Example: > echo "foo" >> colliding_file.mp4

Then I was able to perform the configuration save, and then do the migration.

**To Reproduce**
1. Scan Library
2. Unselect "Calculate md5 for videos"
3. Scroll to bottom and hit save.
4. See graphql error that prevents save because of null values.

**Expected behavior**
Either no oshash collisions, or else a way to disambiguate two distinct files files that might have the same value.  Alternatively, maybe show a list of scenes that have null values, so they user can easily locate/delete or modify them.

**Stash Version: (from Settings -> About):**
Version: | v0.2.1-50-g5992ff8
-- | --
Build hash: | 5992ff8
Build time: | 2020-08-06 01:28:23

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser firefox

**Additional context**
I suspect that the collisions might be from incomplete or damaged files.  Maybe Incompletely torrented files missing their final chunk might cause the final bits of the file to be identical.  Then combined with a similar video file type header, you end up with matching hashes for different files.

Thank you very much for this project.  It is everything I've always dreamed of having for curating my collection.

**Comment by WithoutPants** [comment]
This can happen if you have duplicate files with a small amount of byte difference (such as corruption). If you retest with the latest version, it should log what the colliding files are. I had one instance of duplicate files with different MD5 - it turned out that they were a copy of the same file, but one had a small ~80 byte corruption. I removed this scene from stash and rescanned, and it fixed the issue for me (the removed scene was detected as a duplicate and not re-added to stash).

**Comment by roypoel** [comment]
Great! Thanks for your quick reply. I suppose this works as expected.  The tradeoff of hashing speed is that the results are a bit more 'brittle'.

**Comment by WithoutPants** [comment]
I'm going to close this as apparent expected behaviour. If you come across files that have colliding oshashes that you believe shouldn't do, please let me know.
