### ISSUE TITLE
[Feature] Split and merge scenes.

### ISSUE THREAD

**Issue by woodgen** [stashapp/stash#724]
**Is your feature request related to a problem? Please describe.**
Many releases are whole movies in one file or even worse, split across discs. This means that there are multiple scenes per file and sometimes a scene can be across files.

**Describe the solution you'd like**
stash should utilize ffmpeg to merge and split scenes.
Ideally without reencoding, so remuxing and keeping the same container if possible.
Appending scenes should only work for same codec, container and resolution.

From the UI side I would keep it extremely simple and add 2 options in the menu where the thumbnail generation is:
"Split scene at current time"
"Append scene"

This will trigger a popup that asks if the original files and metadata should be kept with an option to delete it. Which will also delete the source data and database entries.

From the ffmpeg side contcatenate and copy can be used.
https://trac.ffmpeg.org/wiki/Concatenate#samecodec
https://ffmpeg.org/ffmpeg.html#Stream-copy
https://stackoverflow.com/questions/5651654/ffmpeg-how-to-split-video-efficiently

**Comment by bnkai** [comment]
Imo stash shouldn't split/merge media files. A more elegant solution would be playlists. https://github.com/stashapp/stash/issues/226 should cover this case.
Also while splitting is relatively easy , concat isn't. Apart from the codec/container/resolution one has to check for framerate also. In some cases concat can also produce audio sync issues with or without reencoding and a manual check of the concatenated file will probably be required.

**Comment by woodgen** [comment]
Not sure how playlists will solve the problem with multiple scenes per file, but "custom scenes" seems to be very similar to splitting scenes, where new video files are created.

**Comment by GronsoBitburg** [comment]
I see that in the last couple of releases that an split and merge feature has been added. I cannot find out how to split those scenes apart in stash. I only seem to be able to merge already split scenes, or split those that I have personally merged.

Do we know if I am missing a feature where we can virtually split a movie into scenes? My Library would be in a better state being able to split those movies into scenes and have the appropriate metadata attached for each.

**Comment by stg-annon** [comment]
> I cannot find out how to split those scenes apart in stash.

If you have a scene with multiple files associated with it you can "split" them by selecting any file that is not the primary file and clicking the split button on it.

This concept only applies to individual files not single files that may consist of multiple scenes, which is something that is planned to be supported later

**Comment by xx790** [comment]
> not single files that may consist of multiple scenes, which is something that is planned to be supported later

What issue should I subscribe to in order to track that feature?

**Comment by stg-annon** [comment]
@xx790 
> What issue should I subscribe to in order to track that feature?

This issue is likely a good one to track for that specific feature, it has been discussed alongside a marker refactor and required the files refactor before it could be implemented

**Comment by xx790** [comment]
Right,

I'm definitely looking for a way to logically define multiple scenes in a single file without touching the source file and also still having the access to the source file as a whole. I think there are multiple opened issues that talk about it in different words.

Having a nice way to combine multiple files into a single scene - I can see some not so common use cases, so it's probably nice as a part of the universal solution, albeit not as relevant for me.

Can't 👍 this issue because of the way original post is worded (I'm not voting for recoding so would prefer to see issues that reflect actual plans).

Playlists mentioned above - definitely interested to have a more permanent alternative to queue, so subscribed the linked issue as well.

**Comment by stg-annon** [comment]
a more specific title for this issue might be

`ability to split single file into multiple scenes`

the implantation would most likely allow the creation of multiple scenes from segments of a single file without actually needing to modify the file itself which would be ideal

**Comment by firrets** [comment]
@xx790 
> I think there are multiple opened issues that talk about it in different words.

Can you list some issue IDs? I'm searching and I can't find any. This one is the closest to what I'm looking for: support for multiple scenes on a single source file (e.g. full length feature)

**Comment by stg-annon** [comment]
might be worth creating an issue specifically for what we are describing here as opposed to keeping this one, which kind of describes two separate issues of "splitting" and "merging" the merging aspect can be accomplished via playlists as **bnkai** says or grouping into movies so I think we could close out this issue linking to a new one that better describes the splitting a single file feature
