### ISSUE TITLE
Cannot save any performers

### ISSUE THREAD

**Issue by dotbanana** [stashapp/stash#73]
I have a fresh new setup of stash in a dedicated vm. Everything worked so far. I let it create previews and it shows and plays my collection. But when i am trying to add a performer (with or without scrape) i get: "Error: Network error: Response not successful: Received status code 422"    

The log shows:  
"POST http://localhost:9999/graphql HTTP/1.1" from 127.0.0.1:57880 - 422 97B in 364.418µs

**Comment by Latschenharry** [comment]
If you add a picture to the performer you should be able to save it.

**Comment by dotbanana** [comment]
That did it thanks
