### ISSUE TITLE
[Feature] Saved queries

### ISSUE THREAD

**Issue by WithoutPants** [stashapp/stash#730]
**Is your feature request related to a problem? Please describe.**
It should be possible to save frequently used queries.

**Describe the solution you'd like**
Having set query parameters for a given page, it should be possible to save the query parameters. These saved queries should then be easily accessible from a dropdown menu or something. It should be possible to set a saved query as a default query for a list page, such that if no existing query is in memory, it will use the saved query as the default.

**Describe alternatives you've considered**
It is possible to use bookmarks to save queries, but this is not a very discreet solution.

**Comment by bnkai** [comment]
What if we create a local (as in stored in stash db) bookmarks section ? The user hits a `save` button and then he selects a title , all current queries should be saved as a new bookmark. The `default` query is a little more tricky though. Can't this be added to the configuration with the limitation though one for each section ? (scenes,performers,...)

**Comment by WithoutPants** [comment]
I think saved queries would be better as a per-type (scenes, performers, etc) concept rather than a general bookmark concept.

For database design, I think a single `saved_query` table or something would suffice, containing the query type, name, query details, and a default flag. I think default queries belong in the database alongside the saved queries rather than a configuration value.
