### ISSUE TITLE
[Feature] Mouse hover delay

### ISSUE THREAD

**Issue by ciaron88** [stashapp/stash#734]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when quickly moving my mouse over the screen and all the videos instantly start showing the previews. Most of the time I am going to a video in the middle/end and this is the only one I want to see the preview and I want all the other videos to stay on the thumbnails.

**Describe the solution you'd like**
Have a customizable delay on how long you have to hover over a video before it starts showing the preview

**Comment by peolic** [comment]
Another solution is restoring the scene cover image when the mouse isn't hovering over the video (currently disabled in code).

https://github.com/stashapp/stash/blob/e3ea3ea85e5f551ee36668d441c925e2c848b4c4/ui/v2.5/src/components/Scenes/SceneCard.tsx#L23-L25

https://github.com/stashapp/stash/blob/e3ea3ea85e5f551ee36668d441c925e2c848b4c4/ui/v2.5/src/hooks/VideoHover.ts#L45-L49

**Comment by HereIam80** [comment]
According to #576 there is no easy fix?! I would love having a delay or the thumbnail restored.

**Comment by WithoutPants** [comment]
I think this should be implemented alongside #576 .
