### ISSUE TITLE
Scene Filter for "Is missing dates" doesn't show scenes with "NULL" date

### ISSUE THREAD

**Issue by HereIam80** [stashapp/stash#735]
**Describe the bug**
Just as the title says if you choose to find your scenes with missing dates and set the filter accordinly ("Is Missing Is date") it just shows scenes for me with empty content in the date field. The scenes wich an actual "NULL" value doesn't show.
I don't know if either the empty or null value is not supposed to be there to begin with.

Minor bug though imho...

**Comment by WithoutPants** [comment]
How did you end up with `NULL` dates in the first place? I've been through my databases and can't find a single instance.

**Comment by HereIam80** [comment]
Well didn't really know if NULL was supposed to be there or not. Sounded right to me at first but I guess that this would be my own fault here.

Anyway ... easily fixable with some SQL.
