### ISSUE TITLE
[Feature] Movies are not sorted by scene #

### ISSUE THREAD

**Issue by Tweeticoats** [stashapp/stash#736]
**Describe the bug**
When viewing a movie with multiple scenes the scenes are sorted by date or another field.
None of these make sense as they would all be released at the same time when the dvd or movie was released.
Sorting by scene # and make this the default and possibly the only option.

**To Reproduce**
1. Navigate to /movies/1
2. Click the sort field button
3. The list does not contain sort by scene #

**Expected behavior**
You  should be able to sort by scene # for videos in a movie.

**Comment by seducingbits** [comment]
Agreed. This is my expected behaviour for the scenes which are listed on a movies page.

**Comment by VonTittyslappen** [comment]
Is there any update on this being implemented please? I don't know a lot about these things but it would appear that it should be a straight forward change to sort by scene number, but correct me if I'm wrong.

It's a much needed thing as movies should be in scene order by default :)

Thanks!

**Comment by ciaron88** [comment]
Hi is this being worked on? I agree with @VonTittyslappen this is very very very much needed and does not seem hard to implement
