### ISSUE TITLE
[RFC] Discord alternative? I personally like Element as a support channel

### ISSUE THREAD

**Issue by GETandSELECT** [stashapp/stash#738]
Hey

Discord is not Open Source and privacy friendly.

See https://www.privacytools.io/software/real-time-communication/ for alternatives.

I personally like 

> Element (formerly Riot) is the reference client for the Matrix network. The Matrix open standard is an open-source standard for secure, decentralized, real-time communication. VoIP 

There are lots of Porn communities on Element and there is no known case of censorship or privacy violation. Element is like a modern IRC.

**Comment by WithoutPants** [comment]
I don't think there is the critical mass of support to move to another support channel at this point. Closing for now.

**Comment by SCLogo** [comment]
I know it is old, but is there any community slack channel? As I see appscode workspace deleted.

**Comment by DogmaDragon** [comment]
@SCLogo no Slack, but we have Matrix.

Our official space is located at `#stashapp:unredacted.org`.
Invite link: [matrix.to/#/#stashapp:unredacted.org](https://matrix.to/#/#stashapp:unredacted.org)
Details: https://docs.stashapp.cc/matrix/
