### ISSUE TITLE
[Feature] Perfomer text

### ISSUE THREAD

**Issue by ghost** [stashapp/stash#746]
Would it be possible to add a text box to a performer, where the user can input text? The text box could be visible when opening a performers profile, and be edited together with other information such as Gender, Birthdate, Ethnicity. A text box could be used to describe the performer, add notes or simply list other information.

It's important that the saved text doesn't become formatted as one continuing text. Instead the user should be able to divide the text into paragraphs.

**Comment by WithoutPants** [comment]
This seems like a duplicate or at least a large overlap with #712.
