### ISSUE TITLE
[RFC] Release cycle

### ISSUE THREAD

**Issue by WithoutPants** [stashapp/stash#755]
## The issue

It was recently brought to my attention that many stash users are using the `develop` build of stash. This has the benefit of ensuring that bugs are discovered soon after they are discovered, however there are a number of drawbacks to the current situation:
* users underestimate the risk of using the "cutting-edge" version, and may not backup their database and generated files sufficiently,
* if a catastrophic bug is found, it is likely to affect are large contingent of users that may not be easily recover from
* if a dumb panic bug is introduced (which has happened as few times), there is no easy way to return to a previous build, since the latest development build is always overwritten. This puts further time pressure on maintainers (specifically me :) ) to fix these introduced bugs.

Given that it has been two months since the last release, and the rate at which features, improvements and bug fixes have been introduced, it is understandable that users choose to install and use the development build. 

## The proposal

I've currently been using milestones as a planning tool to scope stuff that I'm interested in working on for the next iteration. However, I feel that my eyes tend to be larger than my stomach and I commit to quite a large scope. 

I'd like to propose the following shift in approach:
* add a "Backlog" milestone. Maintainers can add issues that they are interested in working on to this milestone. This will allow me at least to be reminded of things that I committed to working on.
* move to a time-based release cycle, rather than a feature-based cycle. Given the current rate of pull requests, I'd make the next cycle one month long. I'd add a due date to the active release milestone. This will at least give me a defined unit of time and allow me make commitments accordingly. I'd suggest the last week should be for bug fixes and testing only.

If there isn't enough meat in the release to make it worth doing on a particular month, we can always extend it based on time availability and interest.

This should hopefully strike a better balance between encouraging users toward the stable releases and mitigating the risk inherent in using the cutting-edge builds, along with giving users on stable builds more frequent updates.

As an aside, should we go with this approach, I'd advocate toward doing a release shortly, probably including #741, #745, #753 and the bug fix for #747. We can push the upgrade to go 1.13 to the next release.

**Comment by bnkai** [comment]
Also 
- Bug fix releases should be back-ported and released ahead of schedule if needed 
- A warning message for the dev version could be printed somewhere in the stats/changelog page.
- We could explore the option of storing a fixed number of the latest dev releases so that a user can download if something goes wrong with the current dev release.

**Comment by WithoutPants** [comment]
Good feedback from Discord:

> Spincity07
> i'm not one of you, but i manage developers and dev lifecycle for a living and i'm a community member on the dev branch auto updating so some feedback from a community member:  If the stated concern is people updating from dev who aren't savvy enough to know that it could be dangerous (and i agree), then a time-based release cycle at monthly makes sense. From my perspective, Stash is great but the features in git to be worked on have a lot of meat to them so waiting a long time is certainly one of the things that drove me to dev branch. Moving to monthly releases will help the significantly. You could work on the Feature, Bug, Enhancement methodology where monthly releases are for features / db changes and bugs and enhancements could happen sooner like weekly, but i think the admin overhead may not be worth it. 
>
> I'd also recommend moving versioning to yyyy-mm-hotfix so the September release would be 2020.9 and a September hotfix would be 2020.9.1. Seeing those in git as milestones may help internalize exactly how much time you have and not bite off too much in each release. 
>
> Just some feedback from a community member. I know what it's like to make these decisions alone so figured you would want another voice. And nice work so far everyone. The tool is really fantastic!

I'm going hold off one switching versioning for the moment, since I think semantic versioning is still the generally recommended paradigm, but I will keep it in mind. We can always rename the milestones to be time-based for a similar benefit, but I'm not convinced that it's necessary.

**Comment by seducingbits** [comment]
great  idea. i am also on the dev branch because im impatient but could definetly use a monthly branch. i do make backups though but always hope that i dont need them since the home server already takes too much time to maintain.

having a year-month versioning theme is great imho because you can see pretty quick how recent a version is and if you should update.
