### ISSUE TITLE
[Feature] Lock metadata fields and scenes from being changed

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#762]
**Is your feature request related to a problem? Please describe.**
Sometimes the auto tagger will (correctly) add info to a scene you don't wish it too; the auto tagger will constantly add the wrong single name performer to a scene.

**Describe the solution you'd like**
Aside from implementing #422 to address the false positives of single name performers, please consider the following:

- Let users "lock" individual fields in a scene from being changed by the auto-tagger or a scrapper
- Let users "lock" the entire scene from being changed by the auto-tagger or a scrapper
- Using a tick-box in the auto-tagger section, allow the user to bypass the permissions of any locked fields/scenes (for edge case purposes)
- Let users filter scenes in a search by omitting locked scenes, which could symbolized that a scene is "organized".
- For the UI, maybe there could be a padlock button symbol by each field that is grayed out when disabled and bright when enabled; Have a "global" padlock for the scene that locks and unlocks all the fields with one click.

**Comment by bnkai** [comment]
related to #729

**Comment by WithoutPants** [comment]
Closing this as largely met by the Organized flag. Feel free to create another issue if there are remaining functions that are needed.
