### ISSUE TITLE
[Feature] More option for sceneByFragment (Scraper)

### ISSUE THREAD

**Issue by Belleyy** [stashapp/stash#791]
**Is your feature request related to a problem? Please describe.**
It would be good to have more option for sceneByFragment scraper.

**Describe the solution you'd like**
Having:
`{StudioURL}` - the Studio URL (if not set, return the studio name)
`{Basename}` - filename without extension.

**Describe alternatives you've considered**
A good thing should have a option to add **Regex** to these options, so we can remove junk text that can appear in the title/filename (like 1080p, "_",...). 
By filter this, we could get a better result (More accurate).

**Additional context**

Idea behind this request:
Basename - Could be used for JAV scraper, the filename is often the ID but with the extension it don't return result.
`https://www.javlibrary.com/en/vl_searchbyid.php?keyword=ABP-627` Work
`https://www.javlibrary.com/en/vl_searchbyid.php?keyword=ABP-627.mp4` Don't work

StudioURL - Could be used with Search Engine, i think if we set `site:{StudioURL} {Basename}`, we could possibly get the first result to be the good URL of the scene.

Exemple:
`https://duckduckgo.com/?t=ffab&q=site%3Abrazzers.com+unmasking_the_mistress&ia=web` 
First result is the correct one: 
`https://www.brazzers.com/video/4416793/unmasking-the-mistress`

**Comment by Belleyy** [comment]
Look like Regex will be added with #878 
So this fix `{Basename}` part for this Feature.
Thanks 👍

**Comment by bnkai** [comment]
@Belleyy  can we close this now ?

**Comment by Belleyy** [comment]
> 
> 
> @Belleyy can we close this now ?

Sure, we got regex it's was the main thing 😄
