### ISSUE TITLE
[Bug Report] Fail country filter when use "United States" or "United Kingdom"

### ISSUE THREAD

**Issue by caustico** [stashapp/stash#796]
**Describe the bug**
When you select a country filter, in the performers page, like "country is United States" is show the performers from the "United States" and "United Kingdom"

**To Reproduce**
1. Go to 'performers page'
2. Make a filter "country is United States"
3. See error

**Expected behavior**
Only show performers from the "United States"

**Comment by InfiniteTF** [comment]
You can avoid that by using quotes.

More generally we need to migrate the country field to ISO codes and all inputs to a country select. Unfortunately that involves potentially wiping country info if we don't match it properly, but there's no way around it.

**Comment by caustico** [comment]
OK. I will use quotes in my filters.
