### ISSUE TITLE
Delete performers and scenes via UI

### ISSUE THREAD

**Issue by StashAppDev** [stashapp/stash#8]
https://github.com/stashapp/StashServer/issues/37

**Comment by malcuk** [comment]
Is it also possible to delete scenes via the UI as well? I have discovered a couple of dupes at different resolutions and would be good to easily get rid of one of these.

**Comment by echo6ix** [comment]
If UI based scene deletion ever gets implemented it should probably delete the video file and all associated generated content as well, but this should come with a javascript alert of some kind to warn the user of file deletion and obtain user consent similar to a confirmation model dialog box.

it might be a bit of a headache when the user can just delete the file directly and then use the to-be-implemented /clean/ function.
