### ISSUE TITLE
Apply tags and metadata to search results

### ISSUE THREAD

**Issue by koala640** [stashapp/stash#80]
to quickly bulk tag you should be able to apply tags to search results:

1 - search for something
2 - apply tag or metadata like studio, performer (select one more more tags/performers/etc. or create new ones)
3 - when clicking ok it applies the tags to all content in search results (if already exists then ignore)

this is a good workaround to more complex bulk tagging

**Comment by GernBlanston12** [comment]
I would add, just for giggles, that this sort of "add x tag to everything I see on the screen/search results" functionality would likely work well when implementing playlists, if that is ever a thing. If you've got a file list to display, and I imagine you do, it's just syntax to create/append an .asx file or a playlist.  I think the bulk tag function would be easier to implement than filename-based auto-tagging, and be the next best thing, but I do think filename-based is also hugely important.

**Comment by Leopere** [comment]
This is mostly resolved with #92
