### ISSUE TITLE
[Bug Report] Last search not saved on Studios/Markers/Galleries pages

### ISSUE THREAD

**Issue by halorrr** [stashapp/stash#801]
**Describe the bug**
Not sure if this is a bug or just lake of feature parity across Stash, but I noticed some pages don't remember your last applied filters/searches and some do. 

Scenes, Movies, Performers, & Tags all will fantastically remember what search filters, typed search, or page order that I applied to their pages last. Whereas Markers, Galleries, & Studios treat every visit as if it is your first visit, not remembering any of what the other pages do.

**To Reproduce**
1. Go to 'Studios'
2. Type something in the search
3. Go to another page
4. Go back to Studios and see the search box is now empty
5. Go to 'Scenes'
6. Type something in the search
7. Go to another page
8. Go back to Scenes and see the search box still contains the previous search

**Expected behavior**
Consistent behaviour across different sections of Stash

**Screenshots**
Example here: https://screenshot.click/10-50-6164z-6ol34.mp4

**Stash Version: (from Settings -> About):**

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Browser Chrome
 - Version 85.0.4183.102

**Additional context**
N/A

**Comment by InfiniteTF** [comment]
Good catch, thanks for the excellent report!
