### ISSUE TITLE
GLIBC_2.28 not found, executable not working

### ISSUE THREAD

**Issue by yoshnopa** [stashapp/stash#806]
With the newest version in develop (from 9.11.20) glib 2.28 is required for running the executable. This makes it incompatible with my system of Ubuntu 18.04, which only has the version 2.24 (as determined by ldd --version)

I highly suspect this to be due to the update to go 1.13, the system doing the compiling is probably a new one. As my OS is at least in the linux world one of the more common, it would be great if you could revert/modify the compiling system to an older version of libc for greater compatibility.

Error Message:
/path/to/stash-linux: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /path/to/stash-linux)

**Comment by bnkai** [comment]
@yoshnopa you can try the build from the above PR( #808 ) it was saved here https://transfer.sh/hEylR/stash-linux 
It is a static build and should have no problem even with your ubuntu

**Comment by yoshnopa** [comment]
First, thank you for providing a solution so quickly!
I'd love to test it, unfortunately, transfer.sh seems to be down right now... However, as it's very likely that this will solve it, I can wait for the PR to be merged.

**Comment by supermayer** [comment]
@bnkai - I did test, it works now in my ubunutu 18.04. I did find 1 bug, it seems the scene cards no longer animate with this binary.  If you need any other testing just let me know.

**Comment by synsyn93** [comment]
Seems to work on ubuntu 18 with this binary now for me.
