### ISSUE TITLE
Allow multiple names for tags

### ISSUE THREAD

**Issue by AdultFunStuff** [stashapp/stash#809]
The tagging system would be much more usable if a single tag could be associated with multiple names or strings for the purpose of auto-tagging, or some kind of ability to link similar tags together. For example, one might have a tag for 'Behind the Scenes,' but have it match either "BTS" or "behind the scenes" when auto-tagging. Currently, to have the auto-tagger pick up both possibilities from the filename, tags need to exist for both possibilities - and that means that when searching or filtering BTS scenes, the search filter needs to include both tags.

"DP" and "double penetration" would be another use case, for example. Two tags are needed for the auto-tagger to match both possibilities, when both are the exact same thing and would be best represented under a single tag.

**Comment by WithoutPants** [comment]
Duplicates #675 and #121
