### ISSUE TITLE
[Feature] keyboard shortcuts

### ISSUE THREAD

**Issue by koala640** [stashapp/stash#81]
there should be keyboard shortcuts for quickly:

- [ ] rating a scene
- [ ] tagging a scene (with autocomplete)
- [ ] marking a scene
- [ ] adding performers to scene (with autocomplete)
- [ ] adding scene to studio (with autocomplete)
- [ ] ...

**Comment by Leopere** [comment]
A great user interface will contain things like this I'm slotting this in for the V0.2.0 the hover tooltips should all include the hotkey as well just to be more intuitive.  Also, a help dialog overlay triggered by the `?` key would be paramount.

**Comment by arvz-test** [comment]
Now that we have the new Multi-Scenes editing UI (from commit https://github.com/stashapp/stash/commit/455e16ece92bd4b61ea854d2623f79d7ff324f9c) 
I would want in the scenes page:

E - brings up the edit scenes UI 
D - brings up confirm deletion UI 

these should only work when the search text field is not selected, so if you were searching something you should have to click away from the search field first before the shortcuts work again
