### ISSUE TITLE
[Bug Report] supportedLocalesOf Fallback

### ISSUE THREAD

**Issue by Still34** [stashapp/stash#817]
**Describe the bug**
If the `Intl.DateTimeFormat.supportedLocalesOf()` function is not available on the guest browser, opening the web interface will result in a plain exception message.

```
Something went wrong.
TypeError: Intl.DateTimeFormat.supportedLocalesOf is not a function
in IntlProvider in n in hd in l in t in t
```

**To Reproduce**
1. Use any browser without the feature set available, or use an extension that blocks the function from being called (e.g. [Spoof Timezone](http://add0n.com/spoof-timezone.html))
2. Open the web interface
3. Exception occurs

**Expected behavior**
The JavaScript should fallback to `en-US` if the method is not available, instead of throwing an exception, causing service unavailability.

**Stash Version: (from Settings -> About):**
v0.3.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox Nightly
 - Version: 82.0a1 (2020-09-19) (64-bit)

**Comment by InfiniteTF** [comment]
@Still34 I'm unable to reproduce. There are no browsers made in the past seven years that don't support `Intl.DateTimeFormat.supportedLocalesOf`, and browsers that are that old can't run stash anyway.

Spoofing the timezone doesn't do it for me either, can you post the exact steps you used to reproduce?

**Comment by Still34** [comment]
I can repro with the add-on mentioned above.

**Comment by InfiniteTF** [comment]
> I can repro with the add-on mentioned above.

Sure, but what exact settings are you using in spoof timezone? Can you also try it in stable Firefox? The nightly is not a reliable browser.

**Comment by Still34** [comment]
Okay, that's odd. I can't repro anymore. Maybe it was indeed a one off bug with Nightly. Closing. Sorry for the trouble!
