### ISSUE TITLE
[Feature] Show actual percentage of task finished in Task Status

### ISSUE THREAD

**Issue by rg9400** [stashapp/stash#822]
**Is your feature request related to a problem? Please describe.**
Right now, the Task Status for scanning/generating files uses the total file count and the position of the files currently being processed to generate its percentage. For example, let's say I have 4000 scenes already stored in Stash, and I add 1000 more, but they all start with the letter `E`. Stash would scan these in, but the status would show 25% for the entirety of the scan because these files are located roughly 25% of the way into the scan of all files. As it is now, the percentage is fairly meaningless for established libraries.

**Describe the solution you'd like**
Stash outputs a line saying it knows how many new files are to be processed, or previews to be generated, at the start of any task. Ideally, it would know how many it has already processed or generated, divide it by this count, and return the percentage that way. From Discord though, it seems this is not as straightforward as it may appear.

**Describe alternatives you've considered**
I just ignore the percentage and wait.

**Comment by WithoutPants** [comment]
The scan task scans _all_ files in the stash library paths. It does this so that it can detect and generate any missing information such as generated files or hashes. The workload percentage is calculated on the number of files that are being processed, new and old. I think calculating the percentage based on new files only would be counter-intuitive and misleading.

**Comment by rg9400** [comment]
Yeah, I get what you're saying. It's just weird for me to see a scan stuck at 34% for a few hours even though there's been actual progress in the backend. There's just no visual indicator, and at times, it even seems like it's broken (though it is not). The log view is the only reason I would know that it wasn't.

By the way, I think the % is completely broken with the new image changes. Or at least, when I added a second path, my scan percentage was at 150% for most of the scan. Not sure if the images were causing issues, or if it was calculating and adding the percentages for each path separately (i.e. 100% of path 1, 50% of path 2).

**Comment by WithoutPants** [comment]
Closing this as I can't see a feasible way to implement it.
