### ISSUE TITLE
[Feature] Adding python and some libraries to docker container to allow scrapers to run

### ISSUE THREAD

**Issue by Tweeticoats** [stashapp/stash#823]
**Is your feature request related to a problem? Please describe.**
To run python based scrapers or plugins we need python  added to the docker runtime container.
Currently the legalporno.py needs python and the python-requests library.
I have also written a scraper that uses python and the sqlite library.
What are the plans on adding libraries to the runtime container?

**Describe the solution you'd like**
The docker container should add python and a list of useful libraries to allow these scripts to run.
Can we change the docker container to install the following additional packages for ubuntu.
RUN apt-get update && apt-get -y install ca-certificates python3 python-is-python3 python3-requests libsqlite3-0

**Comment by bnkai** [comment]
The latest (v0.5+ ) containers  have been updated so closing this.
