### ISSUE TITLE
[Feature] Add Tags to Performers

### ISSUE THREAD

**Issue by venturevoom** [stashapp/stash#828]
**Problem**
Millions of Performers and you have limited options to search them for what you are interested in. 

**Solutions**
It would be great to have the possibility to **add Tags to Performers** and have the subsequent filter options, so you could easily see all the _Redheads_ or performers working in a tagged _Genre_. 

**Describe alternatives you've considered**
Alternative would be the possibility to extend the Performer Dataset (and thus make the Fields scrapable)

**Comment by echo6ix** [comment]
Duplicate of #120 and already added to [backlog](https://github.com/stashapp/stash/milestone/5)
