### ISSUE TITLE
Allow multiple tasks to be queued up

### ISSUE THREAD

**Issue by com1234475** [stashapp/stash#829]
While running a plugin, if a mutation that requires a task, it can't be invoked.

for example. While running a plugin to decide which frame should be a thumbnail. invoking the `sceneGenerateScreenshot` will not fail but will also not run as the plugin is already running.

**Describe the solution you'd like**
If Stash could maintain a queue of tasks to be invoked it would allow a plugin to add tasks like `sceneGenerateScreenshot` it the queue for later processing after the plugin as completed.

**Comment by WithoutPants** [comment]
Tagging this as duplicate in favour of #962
