### ISSUE TITLE
[Feature] DLNA

### ISSUE THREAD

**Issue by SpedNSFW** [stashapp/stash#850]
DLNA is a technology that allows you to stream content from one device to any device on the network easily. A DLNA server will show in a list of network devices on supported devices such as but not limited to TVs, phones, and computers. XBVR, a similar service to Stash, uses DLNA to stream content to VR headsets and it works without issue in my experience.

The way XBVR does it you can set the server name and icon (icon only shows on devices that support it), and limit it to certain IPs on your local network. See below image for the available options.
![XBVR](https://user-images.githubusercontent.com/68614336/95971163-8ff65e00-0e5c-11eb-91d7-75bfa31bbac6.png)

**Comment by scruffynerf** [comment]
The main benefit is that DLNA access would/could mirror web access, vs just exposing the file system directly.  Browsing via titles andor performers, etc, vs just using a folder of movies, with actual file names, no metadata etc.

Cloning XBVRs approach would be a huge step forward.

**Comment by WithoutPants** [comment]
The last time I looked at this, I was going to lift some code from xbvr directly, but it does not have a license, so until that changes, I'd have to write it from scratch.

**Comment by scruffynerf** [comment]
> The last time I looked at this, I was going to lift some code from xbvr directly, but it does not have a license, so until that changes, I'd have to write it from scratch.

It's code from https://github.com/anacrolix/dms
Which is BSD, so you're fine. See https://github.com/xbapps/xbvr/issues/153
