### ISSUE TITLE
[Feature] Include child studios in studio filter

### ISSUE THREAD

**Issue by SpedNSFW** [stashapp/stash#851]
In the Studios filter for scenes, movies, and now images, I'd like to see an option to include the studio's child studios. For example, you could select "Brazzers" as the studio which would have none of its own scenes, but if a checkbox was selected, all the scenes from the twenty or so child studios would be listed.

Here's an example of how it could look.
![Example](https://user-images.githubusercontent.com/68614336/95993772-3cdfd380-0e7b-11eb-8a6c-8c052d3e225e.png)

This query successfully yields all the scenes of all child studios where the parent studio is "Brazzers", just for demonstration purposes.
```sql
SELECT sc.title
FROM studios st
JOIN (
	SELECT id
	FROM studios
	WHERE name = "Brazzers") q
ON st.parent_id = q.id OR st.id = q.id
JOIN scenes sc
ON sc.studio_id = st.id;
```

The `OR st.id = q.id` is responsible for yielding scenes from the inputted studio, otherwise it will only look for scenes from potential child studios.

UPDATE: One caveat of the above query is that it will not get scenes from grandchild studios, for example it will not get scenes from Massage Creep where Massage Creep is a child of Porn Pros and Porn Pros is a child of Whale Member.

EDIT: The implementation I'd like to see for this would be a checkbox on the studio filter for enabling child studio inclusion, and a input field next to it for the depth. So a depth of 1 would only get child studios while a depth of 2 would include grandchildren.

**Comment by gitgiggety** [comment]
I've started some work on this. Currently I have a very hackish version in which the low level stuff works (updated `queryBuilder` and `filterBuilder`, but hardcoded a part of the query in `sceneStudioCriterionHandler`). But will need to work my way up starting with a `...HandlerBuilder`, updating the studio filter handlers, updating the GraphQL API, changing the UI etc. But at least a part of the low level plumbing is already done.

With the solution I'm working on including grandchildren also shouldn't be a problem as it works recursively (by adding a recursive CTE to the query). A level filter (depth of 1, 2, 3 levels) should also be possible. But I'm just wondering how this would work in an "Excludes" scenario. If you set depth to 1 and the filter type to "Excludes", should grandchildren then be listed again? Kinda feels odd to me.
