### ISSUE TITLE
[Bug Report] Preview video continues to play when mousing away from scene card

### ISSUE THREAD

**Issue by ciaron88** [stashapp/stash#859]
**Describe the bug**
“Re-show preview thumbnail when mousing away from scene card” no longer occurs and the video preview still plays when mousing away from scene card

**To Reproduce**
Steps to reproduce the behaviour:
1. Hover over scene card
2. mouse away from scene card.

**Expected behaviour**
Scene card should re-show preview thumbnail when mousing away from scene card

**Stash Version:**
Version: | v0.3.0-34-g73eb5c7
Build hash: | 73eb5c7
Build time: | 2020-10-15 23:40:22

**Server**
 OS: Docker (Synology)

**Desktop:**
Browser: Firefox (On Windows 10)

**Comment by WithoutPants** [comment]
I'm not able to reproduce this. Tested on Firefox 81.0.2 on Windows.

**Comment by ciaron88** [comment]
> 
> 
> I'm not able to reproduce this. Tested on Firefox 81.0.2 on Windows.

OK Thanks. i will try Chrome and clearing my browser etc...

**Comment by ciaron88** [comment]
one of my firefox addons was messing with the video preview. works now. sorry my fault.
