### ISSUE TITLE
[Bug Report] Unable to assign a gallery to a scene

### ISSUE THREAD

**Issue by ciaron88** [stashapp/stash#860]
**Describe the bug**
In the “Edit Scene” the “Gallery” drop down list is empty but I have multiple galleries in the database

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a scene
2. Go to “Edit”
3. Click the dropdown box next to “Gallery”

**Expected behaviour**
A list of all galleries in the database should show

**Screenshots**
![Screenshot 2020-10-16 011918](https://user-images.githubusercontent.com/31342057/96198960-20609b80-0f4e-11eb-8662-e0adf81f96a5.png)

**Stash Version:**
Version: | v0.3.0-34-g73eb5c7
Build hash: | 73eb5c7
Build time: | 2020-10-15 23:40:22

**Server**
 OS: Docker (Synology)

**Desktop:**
Browser: Firefox (On Windows 10)

**Comment by WithoutPants** [comment]
This is related to the existing behaviour where it required the gallery zip to be in the same directory as the scene video file. This needs to be addressed.
