### ISSUE TITLE
[Feature] Galleries cover image

### ISSUE THREAD

**Issue by ciaron88** [stashapp/stash#863]
**Is your feature request related to a problem? Please describe.**
There is currently no way to set/change the cover image for a gallery. It just uses the first image.

**Describe the solution you'd like**
Add the ability to set a cover image like you can in a scene or have the gallery auto select the “Cover” filename as the cover image (It did do this in the past). I would prefer the first option.

**Comment by bnkai** [comment]
Auto created galleries get the cover page from an image that ends with `cover.jpg`
Closing as completed
