### ISSUE TITLE
[Bug Report] Studio: Is Missing Image filter doesn't work

### ISSUE THREAD

**Issue by SpedNSFW** [stashapp/stash#866]
The "Is Missing: Image" filter for Studios does not work, I assume because it still considers the placeholder image used as an image.
![Placeholder](https://user-images.githubusercontent.com/68614336/96370006-31a4e480-11a8-11eb-8817-f2c8bc6332e1.png)

In reality, it should treat the placeholder as though there was no image.

**Comment by WithoutPants** [comment]
The filter is working correctly, but the default image should no longer be set during studio creation. I'll fix this, but it will mean that existing studios with the default image won't be detected as missing. These will have to be found and fixed manually.
