### ISSUE TITLE
[Bug Report] Unable to update performer image

### ISSUE THREAD

**Issue by datuna7** [stashapp/stash#869]
**Describe the bug**
If a performer is created without an image. It's not possible to update it. It will show the new image until the save button is clicked, then it will show the default image. This is ok but causes and issue when creating a performer from a scene page scrape. 

**To Reproduce**
Go to performers
Create a new performer without image 
Scrape Freeones for image 
Click save 
New image is then replace. 

**Screenshots**
<img width="1129" alt="Screenshot 2020-10-18 at 22 27 17" src="https://user-images.githubusercontent.com/61197836/96386238-31e5b580-1191-11eb-93fd-42abbad7c08a.png">
<img width="1417" alt="Screenshot 2020-10-18 at 22 27 27" src="https://user-images.githubusercontent.com/61197836/96386240-3611d300-1191-11eb-9f6a-95a54682b2c0.png">
<img width="1423" alt="Screenshot 2020-10-18 at 22 27 34" src="https://user-images.githubusercontent.com/61197836/96386241-37430000-1191-11eb-8e8f-2a437478253e.png">

Version: | v0.3.0
Build hash: | 2638a9d
Build time: | 2020-09-02 03:00:47
Running in Docker

**Comment by niemands** [comment]
Have you shift reloaded the page after saving the performer? Usually this is a caching problem.

**Comment by datuna7** [comment]
I hadn't and you're correct. It's a caching issue. Reloading the page without cache now shows the performer image.
Thank you!
