### ISSUE TITLE
[request] adapative interface

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#87]
Modify the user interface so it adjusts to the various mobile screen's form factors. i think it might be a good idea to take inspiration from sites that have already perfected this, like pornhub or xhamster.

![xhamster](https://user-images.githubusercontent.com/37937507/62178299-98757e00-b316-11e9-9fe1-6c708c6a256c.png)

**Comment by echo6ix** [comment]
Reported scaling issue with ultra-wide monitor from [Discord](https://discordapp.com/channels/559159668438728723/559159668912553989) on August 19, 2019 by Keats:

> Yo guys, I just bought an ultrawide monitor and there is some ugly scaling issues with performers images. They turned into squares cutting the girls head lol
> I think it could be solved just by adding an option to select how many girl display on each row
Resolution is 3840x1600 [[screenshot attached](https://cdn.discordapp.com/attachments/559159668912553989/613001923049685023/Stassh.png)]

>With 5 instead of 4 I think they should turn back to portrait-sized ... But maybe forcing it baseline would fuck-up normal 16:9 users
>It would also be nice to have the option to reduce the size overall of the performers. As of now you can only really see 1,5 rows for each "scroll"

**Comment by WithoutPants** [comment]
With v2.5 I think this can be closed, unless there are any outstanding issues remaining.
