### ISSUE TITLE
[Bug Report] Stash reports "Unauthorized Access" when accessing after update to latest develop

### ISSUE THREAD

**Issue by malconfig** [stashapp/stash#870]
**Describe the bug**
Updated from latest_develop 12cba971922382b02c87cf3cfda014bee712e975 to 80199f7 , and now Stash returns "Unauthorized Access" when trying to load anything on my not password protected install.

**To Reproduce**
1. Update between the two versions mentioned
2. Reload Stash
3. _probably encounter bug_

**Expected behavior**
Stash to load frontpage like normal.

**Screenshots**
![Terminal output + Unauthorized Access error in browser](https://i.imgur.com/RFIGfzs.png)
![Browser Debug Tool](https://i.imgur.com/CLyd2kU.png)

**Stash Version(s): (from Terminal):**
stash version: v0.3.0-31-g12cba97 (12cba97) - 2020-10-13 04:29:48
stash version: v0.3.0-39-g80199f7 (80199f7) - 2020-10-18 21:31:23 

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit Pro
 - Browser: Waterfox, Chromium, Internet Explorer 11, Microsoft Edge, etc.
 - Version: Latest Stable (all browsers)

**Additional context**
- It was working properly in the minutes before updating, no changes in browser extensions (all ad-blockers and such have localhost whitelisted).
- Removed both the database file and config file (added extention .bak to the files), generated new ones like expected by opening the last known working executable, but it still returned a GET 401 error when trying to access Stash.
- Opening a previous version of Stash with a backed up database gives same error. I have no backup of the pre-update config.
- Config has not added any user that would suggest a password would be necessary to access.

**config.yml**
```
autostart_video: false
cache: I:\Stash
calculate_md5: true
config: ""
cssenabled: true
database: C:\Users\******\.stash\stash-go.sqlite
downloads: I:\Stash\metadata\downloads
exclude:
- sample\.mp4$
- .!ut$
forcehevc: true
forcemkv: true
generated: I:\Stash
host: 0.0.0.0
jwt_secret_key: *******
language: en-GB
logaccess: true
logfile: ""
logout: true
max_session_age: 3600
max_streaming_transcode_size: ORIGINAL
max_transcode_size: ORIGINAL
maximum_loop_duration: 0
metadata: I:\Stash\metadata
plugins_path: C:\Users\********\.stash\plugins
port: 9999
preview_exclude_end: "0"
preview_exclude_start: "0"
preview_preset: slow
preview_segment_duration: 0.75
preview_segments: 12
scraper_cdp_path: C:\Users\******\AppData\Local\Chromium\Application\chrome.exe
scraper_user_agent: ""
scrapers_path: C:\Users\******\.stash\scrapers
session_store_key: ********
show_studio_as_text: false
sound_on_preview: false
stash:
- I:\temp\configs\xcontent
- F:\*****\*****\Studios
- F:\stash
- D:\stash
- G:\stash
- J:\stash
username: ""
video_file_naming_algorithm: MD5
wall_playback: video
wall_show_title: true
```

**Comment by WithoutPants** [comment]
Can you take a look at the Chrome DevTools window, Network tab and hit F5? It should show the request and response.

You can also try navigating to localhost:9999/login

**Comment by bnkai** [comment]
Can you also try to open a new private window from waterfox or an incognito tab from chrome and try again?

**Comment by malconfig** [comment]
@WithoutPants 
> Can you take a look at the Chrome DevTools window, Network tab and hit F5? It should show the request and response.
> 
> You can also try navigating to localhost:9999/login

![ss (2020-10-19 at 11 39 23)](https://user-images.githubusercontent.com/45622433/96514831-c6185100-1253-11eb-8a18-fba2eeaac46e.jpg)
same response with `/login`
![ss (2020-10-19 at 11 41 42)](https://user-images.githubusercontent.com/45622433/96514900-e5af7980-1253-11eb-9670-9e25dd1a387e.jpg)

@bnkai 
> Can you also try to open a new private window from waterfox or an incognito tab from chrome and try again?

Tried again from phone, new user at a different computer and with lynx from a dedicated server outside my home. No difference there.

**Comment by bnkai** [comment]
Try editing the config file directly and setting the 
`cssenabled: true` to false?

**Comment by malconfig** [comment]
@bnkai 
> Try editing the config file directly and setting the
> `cssenabled: true` to false?

Still "Unauthorized Access" after the edit and a quick program restart

**Comment by WithoutPants** [comment]
Try changing the port to 9998 in the config.yml, restart and navigate to localhost:9998.

**Comment by malconfig** [comment]
@WithoutPants 
> Try changing the port to 9998 in the config.yml, restart and navigate to localhost:9998.

Stash loads like normal on new port, thank you.
If you need more troubleshooting, just ask.

**Comment by WithoutPants** [comment]
Ok, I think you have another application running on port 9999 that's causing this interference.

**Comment by bnkai** [comment]
If there was wouldn't it fail to bind the address?

**Comment by WithoutPants** [comment]
You'd think so, but this is ringing some very vague bells in my head. I suspect it's a Windows debug process or something.

**Comment by WithoutPants** [comment]
@malconfig Make sure stash is not running, in an elevated cmd prompt window (run cmd as Administrator), enter `netstat -anb`, look for something with `:9999`. If its stash, it will look like:

```
  TCP    0.0.0.0:9999           0.0.0.0:0              LISTENING
 [stash.exe]
```

If it's something else, which in your case it should be, the exe in square brackets will be different. You can redirect the output to a file to aid in search as needed, eg `netstat -anb > open.txt`.

**Comment by malconfig** [comment]
@WithoutPants
Found the culprit, BlueStacks the android emulator claimed the port during the Stash update downtime. Thanks for the help troubleshooting. I guess I can close the issue with this.
