### ISSUE TITLE
Inherited Tags

### ISSUE THREAD

**Issue by GernBlanston12** [stashapp/stash#88]
Essentially, the ability to tag a Performer, Studio, etc. and have whatever tag is associated to them be auto-tagged to every subsequent video that Performer or Studio is tagged to.  Example: I tag "2 Chicks Same Time" (a website/studio) with generic tag "threesome", because every video from them is a threesome.  Thus, every time I tag a video with that website, it also gets the threesome tag. This, along with filename-based auto-tagging, is a must-have for those with larger collections that deal often with material from themed websites and movie releases.

**Comment by echo6ix** [comment]
This would be cool. You're basically describing how Pornganizer auto-assigns tags to a scene via preexisting metadata. I requested this for the Ruby version and IIRC the dev was on board with implementing it.

**Comment by GernBlanston12** [comment]
Well, yes and no: The inherited tags feature would work nicely in tune with the filename-based tagging, but I thought of them as separate ideas.  Inherited tags means anything I tag with "My Family Pies" gets "pseudocest" tag automatically.  Filename-based means a file name with "My Family Pies" in it, gets studio tag "My Family Pies".  But, perhaps they could be handled in the same function? I don't know, I just thought they were separate things.

**Comment by echo6ix** [comment]
Okay, I think I understand you: if a performer or studio is tagged with the values "red; yellow; green" and a scene is associated with said performer or studio, then the scene inherits the tags "red; yellow; green". Also when filename-based tagging is implemented, if the automatic tagging matches any studio or performer with the database, your suggestion is to have the scene automatically inherit the tags associated with the studio or performer.

If I understand you correctly this seems like a good suggestion.

Tag improvements are on the [medium term roadmap](https://github.com/stashapp/stash/wiki/Roadmap#tag-improvements), and iirc something like this was discussed, including tag aliases for tag values that lexically mean the same thing but use different words words, eg: main tag = "car", tag aliases = "vehicle, automobile, auto".

**Comment by GernBlanston12** [comment]
You got it! That was a perfect description of what I was trying to get across.

**Comment by bnkai** [comment]
The original issue can now be resolved by an on update plugin?

**Comment by WithoutPants** [comment]
I don't intend on adding this to the core functionality. This should be possible using plugins.
