### ISSUE TITLE
[Feature] Partial scan/autotag based on path parameter

### ISSUE THREAD

**Issue by rg9400** [stashapp/stash#886]
**Is your feature request related to a problem? Please describe.**
After you do an initial scan and have a large library, subsequent scans/autotags to add new files can be incredibly time-consuming. Generate itself is fast since it only runs on new items. For my library of 24k scenes, a scan + generate + autotag can take 30 minutes or more. Additionally, it is not efficient to rescan the entire disk, especially if you use cloud storage. Finally, it makes automation more difficult as if you are running the above steps after a download, they can clog up the downloads which haven't been processed yet.

By specifying a path, it isolates the number of items a task would run on, and I think it could drastically cut down the total time as it would only be spent actually scanning/autotagging/generating vs running on existing files that have already been processed.

**Describe the solution you'd like**
Similarly to Plex/Emby/Jellyfin, give an option to run the scan and autotag processes on a specific subfolder only. Ideally, this option would be available in the web UI, but if it is only available via GraphQL, that can still work.

I know there's some refactoring to give the ability to run all 3 tasks via a single call, so ideally, this would work with that refactor as well.

**Describe alternatives you've considered**
Live with the inefficient scan times, and probably carve that out of any automation I would run. Instead, I would need to scan maybe every 24 hours only, which still results in inefficient scans, but would at least not clog up the download queue.

**Comment by rg9400** [comment]
One option for this feature is to add autotag and clean as parameters for a scan as well like is now available with generate tasks. This way, it would be possible to specify a path for a clean/autotag task by running a scan on it.

That way, if someone wants to develop a tool like [Autoscan ](https://github.com/Cloudbox/autoscan) for Stash (or extend it to Stash), it should be easier as only a single GraphQL call would need to be made for various triggers like inotify or maybe even a future Arr variant for this space. If a file is removed, renamed, added, etc., the impacted path could be passed along while running a scan with generate + clean + autotag on to basically bring that path up to date within Stash.

**Comment by WithoutPants** [comment]
> One option for this feature is to add autotag and clean as parameters for a scan as well like is now available with generate tasks. This way, it would be possible to specify a path for a clean/autotag task by running a scan on it.
> 
> That way, if someone wants to develop a tool like [Autoscan ](https://github.com/Cloudbox/autoscan) for Stash (or extend it to Stash), it should be easier as only a single GraphQL call would need to be made for various triggers like inotify or maybe even a future Arr variant for this space. If a file is removed, renamed, added, etc., the impacted path could be passed along while running a scan with generate + clean + autotag on to basically bring that path up to date within Stash.

To head off scope creep, I'm going to consider this out of scope for this issue. Please raise another issue for including auto-tag/clean in the scan task.
