### ISSUE TITLE
Debug Thumbnail already exists for this path... skipping, 

### ISSUE THREAD

**Issue by cloudstrife11** [stashapp/stash#892]
**Describe the bug**
Going trough my Thumbnails all the time when doing a scan. (this takes up to 2hours) when add 1 video file 

**To Reproduce**
1. Go to 'tab task'
2. Click on 'run'
3. go to tab logs
4. See error = debug Thumbnail already exists for this path... skipping https://ibb.co/s22vh67

**Expected behavior**
I expected to happen, when I run scan it will be much faster to add my new videos/images/galleries

**Stash Version:77da544

**Desktop (please complete the following information):**
 - windows 10
 - Browser chrome
 - Version latest

**Comment by bnkai** [comment]
The message outputed is normal, stash does some housekeeping when scanning that includes checking from missing screenshots,thumbnails. It only stats the files so it shouldn't take that long. ( takes only a few seconds for my ~ 12k scenes)
Can you reduce the log level to info or warning and check if something else is happening ?  Do you perhaps store your media collection / stash metadata using a network share / gdrive account and not locally ?

**Comment by cloudstrife11** [comment]
Thank you for reply me. I have around 648 scenes and 195,054 images. I am storing my files not on network or anything just on hdd.

**Comment by bnkai** [comment]
@cloudstrife11 are you sure it wasn't the first scan after the migration ? The first scan scans ALL images to calculate their checksums and add them as standalone images. 
Can you reduce the log level to info and do a new scan ?

**Comment by cloudstrife11** [comment]
No its not my first scan I scanned 2 days ago. around 6 times around 12hours total. (Can you reduce the log level to info and do a new scan ?) Is this in configurations log file. debug etc not going into the log file only info

**Comment by bnkai** [comment]
If you can provide the log file then scratch that. Go to configuration -> log level . Change that to debug . Hit save
Clear the old log file and start a new scan. Then get a pastebin with the contents of the log file is present in the configuration -> logging options

**Comment by cloudstrife11** [comment]
I dont know why u need the log. It almost only say this : 
time="2020-10-25T14:16:09+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:09+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:09+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:09+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:09+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:09+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:09+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:09+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:09+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:09+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:09+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:09+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:09+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:10+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:10+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:10+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:10+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:10+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:10+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:10+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:10+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:10+01:00" level=debug msg="Thumbnail already exists for this path... skipping"
time="2020-10-25T14:16:10+01:00" level=debug msg="Thumbnail already exists for this path... skipping"

**Comment by cloudstrife11** [comment]
Lol I have exceeded the maximum paste size of 512 kilobyte and the pastebin.com freeze

**Comment by bnkai** [comment]
Like i mentioned above you can ignore the `Thumbnail already exists for this path..` message
Can you zip the error log and upload to something like <https://easyupload.io> or <https://gofile.io> ?
From what you say my guess is that you have a lot of duplicate files ( maybe same images in zip and in folders ?) that get scanned everytime.
 Each time a scan starts it tries to count the new files and prints something like xxx new files found.That could be helpful to check between two scans. For duplicates at the moment the only thing you can do is move them outside stash's media paths so they don't get scanned every time (search for duplicate in the logs to find them)

**Comment by cloudstrife11** [comment]
this is the info I deleted the debug info ; https://pastebin.com/ywSumj7X

**Comment by cloudstrife11** [comment]
this is the scan after scan from 3 hours ago , still takes around 90 minutes,. Warning - Potentially offensive content ahead! : https://pastebin.com/FyaLjZhq

**Comment by bnkai** [comment]
```Taking too long to count content. Skipping...``` this shouldn't happen on local storage unless you have a LOT of directories/subdirectories/files.
Is the `y` drive maybe an extrenal usb? Do you have a lot of extra files  in the `y:\web` directory ( you can  get the number from file explorer ->  folder properties ) ?
The last scan seems alright except ofc for the time it took to finish.
You can try to go to <http://localhost:9999/settings?tab=configuration> and tick the exclude images from scan for all your paths. Then save and  do a new scan to see if it makes a difference. After the scan untick the excludes and save again.

**Comment by cloudstrife11** [comment]
My Y drive is an external hdd, Yes I have all my scenes and images stored in y:\web directory. it have 200,785 files in it. My scan today didnt even find anything all of my files are inside stash now. (images/scenes).

**Comment by cloudstrife11** [comment]
What I did is creating 25 folders in y:\Web with sitenames, And added these 25 subfolders to http://localhost:9999/settings?tab=configuration stashes. I thinks this is a good way around to fix the long scanning time. hope this wil be fixed in the future.

**Comment by bnkai** [comment]
@cloudstrife11 i think it comes down to  
a lot of files/folders 
on an external usb drive ( the latency of stating a file there should way more than a normal sata hdd ) 
and filepath.walk using a lot of stats ( https://github.com/golang/go/issues/16399 )

All these combined were killing the scan. 
What was the difference/speedup in scanning speed ( with no new files found ) when you reduced the subfolders ?

**Comment by cloudstrife11** [comment]
It didnt speed it up. I now need to rescan all of it to the new subfolders. but when I add 1 file to stash I can just click the subfolder in  http://localhost:9999/settings?tab=configuration stashes and Exclude Image for all the other subfolders to add my files faster without going trough all of it over and over again.

**Comment by bnkai** [comment]
Oh i misread that.
Do you mean you still have the 2800+ folder just grouped by sitenames ?

**Comment by cloudstrife11** [comment]
yes Still have the 2800 folders in y:\web

**Comment by bnkai** [comment]
oh nvm then ...
just make sure you don't hit the `clean` task when you have some paths with exclude image or video ticked.

**Comment by cloudstrife11** [comment]
Nice to know otherwise I did that soon. thanks for your help. (hope this wil fixed in the future)

**Comment by bnkai** [comment]
The clean removes entries from the db that shouldn't be there( not the actual files just the entries in the stash db). This includes deleted files or leftover files and files that aren't in the path anymore (if the path is changed ). I think excluding the images/videos like you do could fall to that category.

**Comment by cloudstrife11** [comment]
I start all over again still it goes still taking forever. But now I start again all over again  and made from all of my images zipped files and now it works perfect it scans for couple of minutes and its done.
