### ISSUE TITLE
[Bug Report] Scan options should be persisted

### ISSUE THREAD

**Issue by jeffward01** [stashapp/stash#908]
**Describe the bug**
When you check the checkbox ("Set name, date, details from metadata (if present)") inside the (Go to Settings -> Tasks) , it should be 'saved', and stay checked.  However it does not stay checked. Once you exit that page (Go to Settings -> Tasks), then return, the checkbox is not checked.

**To Reproduce**
1. Go to Settings -> Tasks
2. Click on: https://ibb.co/fxL2YSp "Set name, date, details from metadata (if present)"
3. Then exit, click on "Stash" on the top-left, just leave this screen.
4. Then return to: Go to Settings -> Tasks. The checkbox is now unchecked.

**Expected behavior**
When you check the checkbox, it should be 'saved', and stay checked.  However it does not stay checked.

**Screenshots**
If applicable, add screenshots to help explain your problem please ensure that your screenshots are SFW or at least appropriately censored.
https://ibb.co/fxL2YSp

**Stash Version: (from Settings -> About):**

Version: | v0.3.0-56-g01227ce 
Build hash: | 01227ce
Build time: | 2020-10-27 02:42:13
Latest Version Build Hash: | 01227ce

**Desktop (please complete the following information):**

Windows 10

**Smartphone (please complete the following information):**

**Additional context**

**Comment by InfiniteTF** [comment]
To actually save settings you have to press the save button at the bottom of the page. Due to the increasing length of the config pages, this is becoming more and more of a pitfall. We should either save changes automatically, or add a floating save button that pops up when changes are made so the user is aware they have to actually confirm.

**Comment by WithoutPants** [comment]
An alternative is to popup a dialog if the user navigates away from a page with unsaved information. This needs to be added for the edit pages in any case.

**Comment by WithoutPants** [comment]
I have misread the original intent of this issue. This is related to a task parameter that is not actually stored in the configuration. It isn't a setting, but a parameter.
