### ISSUE TITLE
[Bug Report] country query link and filter can provide wrong results

### ISSUE THREAD

**Issue by HereIam80** [stashapp/stash#910]
**Describe the bug**
The country query link and filter is looking for each individual word in the countrys name instead of the full name. This behaviour gets unwanted results if you look for "United Kingdom" while also having "United States" entries in the database for example.

**To Reproduce**
1. Have a performer with the country "United Kingdom" and a performer with the country "United States" in your database.
2. set the filter in the performer tab to "Country includes united kingdom" or click on the flag of the performer.
3. See the results

This would also be a problem for some other country combinations (Czech Republic, Dominican Republic).

Minor issue but it was the first thing I clicked when trying it out. ;-)

**Comment by SpedNSFW** [comment]
I was about to say that you need to wrap it in quotes, so instead of `United Kingdom`, you'd need `"United Kingdom"`, but that just introduces another, more important bug.
![](https://user-images.githubusercontent.com/68614336/97434503-34a39000-1973-11eb-8894-b43ccd10e6a8.png)

**Comment by HereIam80** [comment]
You are right, I also got that message.

The quotes could be typed if you set the filter manually but clicking the flag would still be wrong though.
