### ISSUE TITLE
Stash always create duplicates

### ISSUE THREAD

**Issue by cloudstrife11** [stashapp/stash#911]
**Describe the bug**
Stash cant find the file then it Calculating oshash then its  already exists. then it gives Duplicate. (With all of my files) I already been trying this now for 1 week did somany scans, and start from beginning few times but still.

**To Reproduce**
1. Go to 'settingsd'
2. Click on 'tab tasks'
3. start scan

**Expected behavior**
not create duplicates

**Scanlog**
https://pastebin.com/6S3PFHHr

**Stash Version: (from Settings -> About):**

**Desktop (please complete the following information):**
 - windows 10
 - chrome
 - latest

**Additional context**

**Comment by HereIam80** [comment]
I am by no means an expert here but I noticed, that stash scans  the drive "X:\" while the scenes in your DB seem to have the drive "x:\". Maybe it has something to do with the capitalization of your drive letter in the config?

**Comment by cloudstrife11** [comment]
that did if damn bro thanx a lot I did povd with hands. is there some way to assing the X to x without doing scanning all over again
