### ISSUE TITLE
[Bug Report] Can't favourite a performer with a stash-id 

### ISSUE THREAD

**Issue by JoeSmithStarkers** [stashapp/stash#915]
Can't favourite a performer with a StashIDs.

**To Reproduce**
1. Tag a scene via the tagger (stashbox) with a performer (ether create or link to an existing performer)
2. Then goto that performer and try to click the heart icon (favourite)
3. The backend returns a 422 error.

If i remove the performer's stashID then try to flag as favourite, no error occurs. So pretty sure it's related to the stashid.

**Comment by InfiniteTF** [comment]
Thanks for the heads up, I've added a fix to #912.
