### ISSUE TITLE
[Feature] Merge tags

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#918]
Sometimes we realize we have multiple redundant tags. Include the ability to merge/consolidate two or more tags into one unified tag.

**Describe the solution you'd like**
Navigating to the `tag page` > a tag > `edit` button > there could be a `merge` button.
- A text form field will allow the user to type from a list of existing tags
- The user clicks an `okay` button once they've typed any tags they want merged
- This opens a modal window (comparable to the scene scraper window) to confirm the list of tags and values that are being merged and and prompts the user with the new tag name
  - These values include: default tag name, thumbnail picture, and in the future can include any tag aliases (aka "sub tags")

**Comment by skinnerback** [comment]
I'd also like to see this.  Using the pierre-delecto/stash_theporndb_scraper and I'm noticing a lot of similar tags that would be best merged (i.e. Blond, Blond Hair, Blonde, Blonde Hair, Blonde Movies)

**Comment by jeremymeyers** [comment]
Would it make sense to build this as a more generic 'merge' codebase? For example to merge performers that are in the database multiple times under different names? or is the data structure too different?

**Comment by jeremymeyers** [comment]
Would also like to request that this include Studios so that merging things like "Shes New" vs "She's New" is less of a hassle.
