### ISSUE TITLE
Image Carousel Rotation

### ISSUE THREAD

**Issue by yoshnopa** [stashapp/stash#925]
**Describe the bug**
When getting to the last image of a page in galleries, it rotates back to the first one instead of continuing the gallery. This is of course mitigated by just increasing the page count to 1000, but it still is a design flaw that should be fixed in my opinion

**To Reproduce**
1. Galleries or images
2. Change to wall mode, reduce the number of results per page to a minimum
3. Click on image, click on right (with mouse, see #923) 
4. Do so until you reach the end of the result page in the carousel and click once more. You're now on the first image again

**Expected behavior**
It should continue with the first image on the next page

**Comment by WithoutPants** [comment]
This will require a replacement of the lightbox component. I'll look at doing this in the next release.
