### ISSUE TITLE
[Feature] Image Cropper

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#931]
**Is your feature request related to a problem? Please describe.**
The user has the ability to add a custom image to a scene, performer, tag, studio, etc., but often times the image does not have the optimized size or aspect ratio. 

**Describe the solution you'd like**
A built-in image cropper like such https://fengyuanchen.github.io/cropperjs/ after a user selects an image. The image cropper can have the optimized aspect ratio hardcoded depending on where they're adding it. eg. if it's a tag image, the aspect ratio can be set to 1:1

**Comment by feederbox826** [comment]
This has been accomplished by the set of "cropX" userscripts (now plugins)
- cropSceneCover
- cropPerformerImage
- cropTagImage

**Comment by echo6ix** [comment]
> This has been accomplished by the set of "cropX" userscripts (now plugins)
> 
> * cropSceneCover
> * cropPerformerImage
> * cropTagImage

I only see CropperJS into the CommunityScripts repo so I'm assuming CropX is different? If so, are they going into the CommunityScripts repo?

**Comment by feederbox826** [comment]
yes, they're all on track to be converted

**Comment by feederbox826** [comment]
for posterity, https://github.com/stashapp/CommunityScripts/pull/224
