### ISSUE TITLE
[Bug Report] Exclude Images tickbox is unselecting itself when Stash is restarted/updated (Stash via Docker)

### ISSUE THREAD

**Issue by VonTittyslappen** [stashapp/stash#936]
**Describe the bug**
The 'Exclude Image' tickbox in the Configuration screen is not remembering being ticked when Stash is restarted or updated, so I have to keep ticking it and pressing save.

I'm unsure if this also happens with the "Exclude Video" tickbox as well.

**To Reproduce**
1. Go to Configuration, tick the "Exclude Image" tickbox for the folder path (I only have one folder path listed)
2. Click on Save at the bottom of the Configuration page
3. Restart or Update Stash
4. Open Stash, and go into Configuration screen and the tickbox is de-selected.

**Stash Version: (from Settings -> About):**
Stash running via Docker on Synology NAS

Version: | v0.3.0-70-g6bb24d1
Build hash: | 6bb24d1
Build time: | 2020-11-09 01:33:43

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 86.0.4240.183 (Official Build) (64-bit)

**Comment by peolic** [comment]
I do not experience this issue (same OS), that's interesting.

Try ticking the box, saving, before you restart Stash,
check the actual `config.yml` file for something like this:
```yml
stash:
- path: D:\path\to\stash
  excludevideo: false
  excludeimage: true
```
`excludeimage` should be `true`.

If it is, then maybe it's something related to the UI and loading the configuration,
and you should look for errors in the browser console (<kbd>Ctrl+Shift+J</kbd>) as you are loading the configuration page.

If it's not, maybe backend-related, as in, the Go code unable to save the config file? Should try to watch the "Trace" level logs of Stash as you click "Save" if there's anything being logged about that.

**Comment by VonTittyslappen** [comment]
Hiya, yeah, the config.yml has updated to add this in:-

stash:
- path: /data/
  excludevideo: false
  excludeimage: true

Nothing appeared in the trace level logs when I hit save.

I've now just restarted Stash and opened the config.yml and it's moved the order around by itself, that's definitely a problem

stash:
- excludeimage: true
  excludevideo: false
  path: /data/

**Comment by peolic** [comment]
That order _shouldn't_ matter. 
And now after the restart it unticked the "Exclude Image" again?

**Comment by VonTittyslappen** [comment]
Okay, just thought I'd mention it, and yes, it has unticked again

**Comment by peolic** [comment]
🤔 
And anything on the browser console when you load the configuration page?

**Comment by VonTittyslappen** [comment]
> 🤔
> And anything on the browser console when you load the configuration page?

Sorry, just checking that now, if you mean in terms of warnings/errors in the console, no, nothing!

**Comment by bnkai** [comment]
@VonTittyslappen are you perhaps using a docker container ?
If yes can you check your setup to see that you are not using any env eg `STASH_STASH` that messes things up. There was a recent issue with that
Can you also change the path save and restart stash to see if the change is updated?

**Comment by VonTittyslappen** [comment]
> @VonTittyslappen are you perhaps using a docker container ?
> If yes can you check your setup to see that you are not using any env eg `STASH_STASH` that messes things up. There was a recent issue with that
> Can you also change the path save and restart stash to see if the change is updated?

Hiya!

Aha, yes I am using a docker container, and I do have the Environment stuff set up in there, it's safe to delete all of them out?

![image](https://user-images.githubusercontent.com/36613700/98713158-272cd380-237f-11eb-9c2d-62128756395a.png)

With regards to change the path save, where do you mean? Do you mean just add another path and save and see if it retains the path entry?

Cheers

**Comment by VonTittyslappen** [comment]
We moved the chat to Discord, but basically I removed all of those entries in the Environment tab except the top one, restarted Stash and now it remembers the checkbox. So it's useful info to those running Stash via Docker.

**Comment by peolic** [comment]
That makes sense now.

I did not know you were not **running** Stash on Windows 10, plus I did not even think about the environment variables.
At the very least, remove `STASH_STASH` because it (might) override the `stash` set in `config.yml`.
https://github.com/stashapp/stash/blob/beb84b8e9459009b871c32e6079a1a57d2407078/pkg/manager/manager.go#L134
It used to be a string / array of strings, but now it's an array of objects (maps), and that's probably getting overridden with every start of the container (until you save the config, which updates the value in memory).

**Comment by VonTittyslappen** [comment]
Lol yeah, woops, why the fuck did I put Windows 10....doh >.< should've mentioned Docker at the beginning, bugger! Mind you, I didnt think it would have been related to Docker in my defence :D

All is hunky dory now that I have removed all of these environment vars except PATH.

I'll update the topic & first post so it mentions Docker

Thanks guys.
