### ISSUE TITLE
[Bug Report] Movies with over 9 volumes don't appear in the correct order (eg. 1,10,11,12,13, 2, 3, 4....)

### ISSUE THREAD

**Issue by VonTittyslappen** [stashapp/stash#942]
**Describe the bug**
Movies that have more than 9 volumes (eg. Manuel's Fucking POV has 13 volumes) are not appearing in the correct order on the Movies section.

For example, the current order is as follows:-

Manuel's Fucking POV
Manuel's Fucking POV 11
Manuel's Fucking POV 12
Manuel's Fucking POV 13
Manuel's Fucking POV 2
Manuel's Fucking POV 3
Manuel's Fucking POV 4
Manuel's Fucking POV 5
Manuel's Fucking POV 6
Manuel's Fucking POV 7
Manuel's Fucking POV 8
Manuel's Fucking POV 9

**To Reproduce**
N/A

**Expected behavior**
Movies that have volumes that reach double figures should appear in the correct order, I shouldn't have to rename the single digit volumes to add a leading zero for this to all appear in the right order

**Screenshots**
Can be provided on request

**Stash Version: (from Settings -> About):**
Version: | v0.3.0-73-gc74f145
Build hash: | c74f145
Build time: | 2020-11-11 23:57:13

**Comment by SpedNSFW** [comment]
This is a simple and common problem. It's sorting the numbers as though they're strings (because they are in this instance) instead of as a number.

A probable fix would be to get all movies of a similar name, separated by title and number `(^.+?)\s+(\d+$)`, group by title, and sort by number.
