### ISSUE TITLE
[Bug Report] Performer scrapers

### ISSUE THREAD

**Issue by hassaffe** [stashapp/stash#944]
If you are looking for an actress and the performer scrapers. If there are several actresses with the same name, several names are displayed in the list. But no matter which entry in the list you select, the same actress is always loaded.

**Desktop (please complete the following information):**

 - OS: Linux
 - Browser Firefox, Chrome

![StashError](https://user-images.githubusercontent.com/55273555/99297856-1e3d7580-2849-11eb-9010-e72451b338bd.jpg)

**Comment by halorrr** [comment]
I was actually going to be bringing this up as a feature request https://github.com/stashapp/CommunityScrapers/pull/268#issuecomment-725230104

From a UX perspective it would be nice to give the pop up a max height and make it scrollable in my head.

From a function perspective as someone who downloads ever community scraper, it would be nice in settings, especially now that we have a scraper list to turn off search providers you don't want to show in the search list. (Example if you only use a particular scraper for the scene function, but it is taking up space in your performer list)

**Comment by bnkai** [comment]
The main issue mentioned here (the UX one is still valid) looks more like a specific scraper issue than a stash issue ( maybe scraper doesnt return correct name/url pairs). @hassaffe can you make an issue in <https://github.com/stashapp/CommunityScrapers/issues> for the specific scraper you used ?

**Comment by hassaffe** [comment]
yes I do

**Comment by bnkai** [comment]
Ok verified.
The graphql query seems to return correct results.
<https://pastebin.com/Qf8QT6qA>
If you search the query for `"barbie"` you'll see that all the results are there.
No matter which `barbie` you choose from the UI though the first with url `http://www.iafd.com/person.asp?perfid=barbie_rus_10&gender=f&barbie.htm` will be selected

**Comment by peolic** [comment]
Perhaps the value (which is later used to determine which item was selected) shouldn't use `name` in this case:
https://github.com/stashapp/stash/blob/21806decca8cb192ded92543d3a53553bae3bfbc/ui/v2.5/src/components/Shared/Select.tsx#L147
Maybe URL, as it will most likely be the unique value.
