### ISSUE TITLE
[Feature] Comics/Image Albums

### ISSUE THREAD

**Issue by SmoofBrane** [stashapp/stash#945]
**Is your feature request related to a problem? Please describe.**
I'd really like to be able to add comics or image albums to the server.
Although the focus of this program is videos, I'd like to manage my comics and the like as well, to keep it all in one place.

**Describe the solution you'd like**
Just a basic image parser so images can be added as grouped albums.
(Think comics or image galleries of people.)

**Describe alternatives you've considered**
There are many image server solutions, but I don't want to run two or three different servers, because I could just as well use my file explorer at that point. The idea is to keep everything organized and together.

**Additional context**
I have long tried to keep my folder structure for images and videos organized and separate, but having the option to organize them by metadata is much more powerful and efficient. Using the folders is quite tedious, so a feature like this would be very nice.
I have looked around fro a while in the "Issues" but I couldn't find a similar request, so I made this one.

**Comment by InfiniteTF** [comment]
CBZs or regular zips are already recognized by stash and will show up as galleries when scanned. The next release, v0.4, has further enhancements to galleries and images which should make image management more flexible.
