### ISSUE TITLE
[Feature] generic URL grabber

### ISSUE THREAD

**Issue by ghost** [stashapp/stash#953]
It would be very cool to have a kind of "generic URL grabber", which is based upon a external script, which uses the filename to create the URL for scraping.
 
I've done this with bash & curl - with some generic informations about a scene (studio, date, name or performers) it is usually easy to find the URL via google. 

What do you think?

**Comment by bnkai** [comment]
Most scrapers that can use filename parts to construct the url do that already (parse an id and construct the url from it)
A generic solution is not easy to implement.
This is probably more suited as a request for a google fragment scraper (populate the url from the filename) for <https://github.com/stashapp/CommunityScrapers/issues/73>
Closing
