### ISSUE TITLE
[Feature] same performer, different name (duplicate)

### ISSUE THREAD

**Issue by NoSwimsuite** [stashapp/stash#954]
It would be nice to set the different names of a performer to the studio where it is used.

e.g.:

Performer PN1
Studio S1 -> Name PN2
Studio S2 -> Name PN3
etc

Same for the different performer URLs.

**Comment by NoSwimsuite** [comment]
When someone is working on the performer section, it would be also cool to add different pictures of a performer. Portrait, with clothes, without, etc.

**Comment by bnkai** [comment]
possible duplicate
the features mentioned here are requested in #422 #571 #638 #703

**Comment by NoSwimsuite** [comment]
Yes. It is duplicate. Sorry.
