### ISSUE TITLE
Deleting tags?

### ISSUE THREAD

**Issue by goithoib** [stashapp/stash#96]
I accidentally created a tag I didn't want, but it seems as if there's no way to delete a tag. It's possible I'm missing something, of course. Any help would be greatly appreciated!

**Comment by jpegsarebad** [comment]
I was able to delete the tags in the sqlite database, but a simpler method in the ui would be nice.

**Comment by echo6ix** [comment]
There is no way to delete tags unless you're comfortable modifying the .sqlite file with a third party app like DB Browser (be sure to make a backup in case you corrupt the sqlite file). You might get more guidance doing this in the Discord #help channel.

I think there was a feature request to delete tags in the ruby version that the dev forgot to port here. It's a pretty essential feature. Thanks for bringing it up.

**Comment by GernBlanston12** [comment]
Does this issue cover deleting tag associations themselves, from the UI?  I accidentally associated the wrong studio to a video, does that mean I need to delete the reference in the db, or is there a way to do so from the UI?  If not, then perhaps that's a separate issue?
