### ISSUE TITLE
[Feature] Queue Tasks

### ISSUE THREAD

**Issue by rg9400** [stashapp/stash#962]
**Is your feature request related to a problem? Please describe.**
With the new selective scan task, it is possible to have only one folder scanned at a time, but users may want to queue up other scans/tasks while the current one is running. For example, if anyone is trying to do some automated scanning, and they run scans on downloads, the first downloaded file will start the process, but subsequent files will get stuck waiting for the first one to finish.

Additionally, with the new parallel task feature, it would be nice to actually leverage additional tasks as they come down the pipeline. Otherwise, if you are doing the above selective scans per file, it would still end up being sequential since the parallel tasks did not all belong to a single scan.

**Describe the solution you'd like**
Similar to my other requests, I use other media server software like Plex/Emby/Jellyfin as a guide. If requests are made for tasks while others are still ongoing, instead of ignoring them, queue them up. Allow concurrent/parallel tasks to be run based on how many are configured, and queue the rest up.

I guess this may be complex based on how this would impact the database.

**Describe alternatives you've considered**
Right now, you can set any automation software to first make sure Stash is idle before triggering a new task. However, as mentioned above, this often leads to it clogging up the tools doing the automation as they have to wait for each file.

**Comment by WithoutPants** [comment]
Resolved by #1379
