### ISSUE TITLE
[Feature] Extract metadata later

### ISSUE THREAD

**Issue by qqqzzzzzzqqq** [stashapp/stash#963]
Similar to my other feature request #957 ...

When I perform a scan, I am given the option "Set name, date, details from metadata (if present)".

If I run the scan with that setting unchecked, then there is no way to retroactively extract this metadata later without removing the file from the library and running the scan again.

It would be great if there was a way to retroactively do this job across a batch of files, or to run it on the whole existing database (e.g. "set date from metadata if not already set"). Alternatively, it could be a per-scene action, like those on the "Generate..." menu.

**Comment by DogmaDragon** [comment]
`Set name, date, details from metadata (if present)` flag was removed altogether since https://github.com/stashapp/stash/releases/tag/v0.17.0.

**Comment by Maista6969** [comment]
Can be closed

**Comment by AshenErn** [comment]
> `Set name, date, details from metadata (if present)` flag was removed altogether since https://github.com/stashapp/stash/releases/tag/v0.17.0.

Will this option return in another form someday?
Or is there a way to do the same with a plugin?
I didn't find any reported features about that...

**Comment by DogmaDragon** [comment]
It's unlikely it will get added to the core Stash, but it's a perfect feature for a plugin, or maybe it could even be a scraper.

**Comment by AshenErn** [comment]
Will this issue continue open to track this feature or i  request in another place?

**Comment by AshenErn** [comment]
They created a metadata scrape, but I can't use it. It only shows the formatted filename without underscores.
Could someone test it to see if it works or not?
[File Metadata](https://github.com/stashapp/CommunityScrapers/tree/master/scrapers/FileMetadata)

**Comment by QxxxGit** [comment]
> They created a metadata scrape, but I can't use it. It only shows the formatted filename without underlines. Could someone test it to see if it works or not? [File Metadata](https://github.com/stashapp/CommunityScrapers/tree/master/scrapers/FileMetadata)

Hey there! I wrote the scraper. The scraper pulls metadata from the primary video file, and I based it on yt-dlp. It works by attempting to grab the following metadata fields and assigning them to their respective Stash field:

* `title`
* `comment` (tends to be the URL where the video was downloaded)
* `description` (details)
* `date`
* `artist` (this is used for both studio and performer)

I worked with the maintainer of the scraper repo to test that it works, and I personally haven't ran into issues yet.

This may not be the best place to discuss potential issues with the scraper, so I recommend hopping into the Discord and giving me a ping (@Qx). I'll be happy to help!

This issue can be closed.

**Comment by Maista6969** [comment]
> They created a metadata scrape, but I can't use it. It only shows the formatted filename without underlines. Could someone test it to see if it works or not? [File Metadata](https://github.com/stashapp/CommunityScrapers/tree/master/scrapers/FileMetadata)

Just to follow up on what Qxxx posted, I have done even more testing on this and it works great! It uses `ffprobe` to get the metadata, so it should work on any platform.

If you're on Windows and you'd like to try an alternative I have also added one called [File Metadata (Windows)](https://github.com/stashapp/CommunityScrapers/tree/master/scrapers/FileMetadata_Windows) that uses Windows APIs to get additional attributes, but there's still no standard way of embedding metadata it makes the same mappings as the other scraper (with some additional heuristics for artists/tags/details)

**Comment by AshenErn** [comment]
You're right, it works indeed. QxxxGit helped me find the issue with my stash. I was using relative paths, and that's why it resulted in errors. Thanks for the help, this issue can be closed.

**Comment by Maista6969** [comment]
This can be closed since we now have scrapers for file metadata using both [ffmpeg](https://github.com/stashapp/CommunityScrapers/tree/master/scrapers/FileMetadata) and [Windows attributes](https://github.com/stashapp/CommunityScrapers/tree/master/scrapers/FileMetadata_Windows)
