### ISSUE TITLE
[Bug Report] Studio images not saved

### ISSUE THREAD

**Issue by Mercury9981** [stashapp/stash#967]
**Describe the bug**
When editing a Studio and adding an image, upon saving the uploaded image disappears and doesn't show from there on. This happens in some cases, not all the time and independent of file-type or file size or dimensions

Stash Version: v0.4.0
OS: Windows 10 20H2
Browser : Chrome 87.0.4280.66

**Comment by SpedNSFW** [comment]
The image is there, you just need to refresh. Probably a hard refresh. This is also probably a duplicate, I just can't find the issue ¯\\\_(ツ)_/¯

**Comment by Mercury9981** [comment]
The problem persisted on one PC, but not on another. After flushing cache and cookies, now everything is working fine.
