### ISSUE TITLE
[Feature] User customizable navbar items

### ISSUE THREAD

**Issue by aGlkZGVu** [stashapp/stash#970]
**Is your feature request related to a problem? Please describe.**
As the project grows, more specialized features are generally added. These features are useful to some people, but can be less useful to others. By letting the user customize parts of the UI to their liking, we can continue to provide powerful features without overwhelming the user.

**Describe the solution you'd like**
My suggestion is to let the user choose which items are shown on the navbar. Specifically, the user can show or hide any of these items based on their preference:

![image](https://user-images.githubusercontent.com/75143841/100485157-570a0400-30ff-11eb-8b43-4db4445918c6.png)

This becomes especially useful if, in the future, support for more content types is added (#11, #14).

**Describe alternatives you've considered**
I can't think of any.

**Additional context**
Here is a quick mockup of how the configuration could look:

![image](https://user-images.githubusercontent.com/75143841/100485396-2bd3e480-3100-11eb-851b-97e3e8279766.png)

**Comment by aGlkZGVu** [comment]
If there is support for this feature, I would like to give the implementation a shot.

**Comment by WithoutPants** [comment]
This should already be possible to do via css overrides.

**Comment by aGlkZGVu** [comment]
@WithoutPants absolutely. Personally, I think it would be nice to also have this feature through the interface settings. I think enough people would benefit from this to make it worth the space its taking up.

In addition, I could imagine a scenario in the future where we might want to hide some items by default (for example text/audio content). In that case there wouldn't be a way to communicate the existence of those items without a visible setting, so CSS override wouldn't be an option for those items.

**Comment by WithoutPants** [comment]
I don't personally have any issue with this addition.

**Comment by peolic** [comment]
Added a snippet if anyone else is looking to do it and doesn't know how.
https://github.com/stashapp/stash/wiki/Custom-CSS-snippets#hide-navigation-bar-items

**Comment by seducingbits** [comment]
@peolic thanks for that. would it also be possible to change the order of the items via css? I tend to click on wrong items because I think another order would be more intuitive.

**Comment by peolic** [comment]
@seducingbits
It turns out that, yes, you can indeed do that:
```css
.navbar-collapse > .navbar-nav {
  display: flex;
  flex-direction: row;
}
div.nav-link[data-rb-event-key="/tags"] {
  order: -3;
}
div.nav-link[data-rb-event-key="/movies"] {
  order: -2;
}
div.nav-link[data-rb-event-key="/scenes"] {
  order: -1;
}
```

You don't have to change the order on each link if you use order values that are less than 0.
