### ISSUE TITLE
[Feature] Stash minimize to tray

### ISSUE THREAD

**Issue by Mercury9981** [stashapp/stash#980]
First of all: you're all doing a wonderful job. I've finally found the perfect way to organize my stash! Thanks a million!

**Is your feature request related to a problem? Please describe.**
I always like to work on a clean desktop and taskbar. Currently the StashApp is an ugly (no offense) app residing in my taskbar.

**Describe the solution you'd like**
A way to minimize the working part of the app to the background, preferrably to the tray

**Describe alternatives you've considered**
I've tried to start StashApp as a service in windows, but this didn't seem to work properly.

**Comment by bnkai** [comment]
I think its a lot easir to run it in the background .... <https://superuser.com/questions/198525/how-can-i-execute-a-windows-command-line-in-background>

**Comment by WithoutPants** [comment]
Closing since there are other ways to do this already, and I think we'd struggle to do this in a platform-independent manner. Let us know if you need further help achieving this.
