### ISSUE TITLE
[Feature] Set default sort and item count

### ISSUE THREAD

**Issue by ciaron88** [stashapp/stash#981]
**Is your feature request related to a problem? Please describe.**
Changing the sort order and item count every time is tiresome

**Describe the solution you'd like**
an option in the settings to set the default sort order and item count for all sections - scenes, images, galleries, performer's scenes, images, galleries, movies and movies scenes etc... OR when changing a sort order and changing the item count make it save this change as default

**Describe alternatives you've considered**
the only option is the change it every time I go to a section/refresh

**Comment by WithoutPants** [comment]
Overlaps significantly with #956

**Comment by peolic** [comment]
This is now possible as of v0.8.0 using [saved filters](https://github.com/stashapp/stash/pull/1474) ("Set as default" option).
