### ISSUE TITLE
[Feature] Strip HTML Tags from Descriptions

### ISSUE THREAD

**Issue by SpedNSFW** [stashapp/stash#984]
Unsure if this is a bug (since anchor tags are cleaned) or a feature, though it doesn't matter too much.

I've just noticed that not all HTML tags get stripped. For example, the `<strong>` element remains and gets sent through as raw text which doesn't look great. I've noticed that anchor tags are stripped as well as breaks which are replaced by new lines.

I don't know if it's just strong tags or others such as `<b>`, `<u>`, `<i>` , `<span>` but they should all be stripped.

**Comment by bnkai** [comment]
I think this is mostly an issue with specific scrapers.
html.parse that stash uses parses ok the page data and replaces all above elements EXCEPT in the case where they are element attributes ( it shouldn't parse them anyway though ).
Most cases like this are descriptions scraped from  the `content` of `meta` elements  or from `script` data.
Sample of an actual case  <https://play.golang.org/p/OKs2ZvKWU7K> (nsfw description)
Scrapers that fall in the above case should regex replace whats needed imho and be done with it.

**Comment by WithoutPants** [comment]
To the best of my knowledge, this doesn't appear to be an issue with the main scraping engine. Please raise another case with a specific example if so.
