### ISSUE TITLE
[Feature] Allow user to set default scene page parameters in settings

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#99]
Whenever I go to my scene page I always have to set my _sortby_ to _created_at_, _sortdir_ to _desc_, and other sorting, filter, and display parameters exactly how I want them.

Consider having a section in the settings page that lets the user define the default parameters for the scene page.

**Comment by WithoutPants** [comment]
A better alternative might be to save these settings in a cookie, so that settings are persisted between visits to the scenes page.

**Comment by echo6ix** [comment]
I should have included the reasoning behind my suggestion: given the nature of the content being viewed, a lot of people may be like myself and only view Stash on an incognito/private browser mode rendering cookies inconsequential.

Maybe implementing both would be a good idea?

**Comment by joyov** [comment]
Another option would be to save the last used settings in the server's database. I do prefer a solution that doesn't require cookies too.

**Comment by WithoutPants** [comment]
#326 fixes the issue of queries persisting between page navigations. I'm thinking of tying this issue in with a broader Saved Queries feature, with the option of selecting a given query as the "default" query, which is what will be displayed if there is no saved query.
